import type { Question } from "@/content/types";

// situations:
// 002 講表哥換新車問你的車
// 003 講表哥去日本滑雪問你有沒有出國
// 004 講表哥辦健身房會員問你有沒有運動
// 005 講表哥考到證照問你有沒有進修
// 006 講表哥人脈都是老闆問你朋友圈
// 007 講表哥紅包包多少比你包的
// 008 講表哥換新手機問你的手機
// 009 舅媽朋友的小孩才藝比較
// 010 舅媽朋友的小孩成績比較
// 011 講表哥公司股票分紅比你多
// 012 講表哥車位在市中心
// 013 講表哥考上研究所問你學歷
// 014 講表哥出國進修問你有沒有計畫
// 015 講表哥買名牌包送女友問你有沒有
// 016 講表哥打高爾夫球問你有沒有興趣
// 017 講表哥的存款數字比你多
// 018 講表哥的頭銜響亮問你
// 019 講表哥連續三年考核甲等
// 020 講表哥公司尾牙抽到大獎
// 021 講表哥的社團朋友都是老闆

export default [
  {
    id: "sanjiuma-comparison-002",
    text: "表哥換新車了，你那台是什麼時候買的？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-002-a",
        text: "我這台是骨董，開出去比新車更吸引目光。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-002-b",
        text: "表哥新車什麼顏色？改天載我兜風嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-002-c",
        text: "舅媽這麼關心，要不要贊助我換新車？",
        archetype: "deflect",
        retort: "贊助？你自己努力賺啦。",
      },
      {
        id: "sanjiuma-comparison-002-d",
        text: "開很多年了，還沒錢換新的……",
        archetype: "meek",
        retort: "沒錢？那你都存去哪了？",
      },
      {
        id: "sanjiuma-comparison-002-e",
        text: "騎機車而已，還沒到買車的階段……",
        archetype: "meek",
        retort: "機車？那你什麼時候才要買車？",
      },
      {
        id: "sanjiuma-comparison-002-f",
        text: "我的車是限量款，限量到只有一台舊的。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-002-g",
        text: "車子不重要，重要的是開車的心情。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-002-h",
        text: "表哥新車該不會是舅舅出的頭期款。",
        archetype: "landmine",
        retort: "你！誰跟你講的！他才沒有！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-003",
    text: "表哥去日本滑雪了，你今年有出國嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-003-a",
        text: "沒出國，但我的心已經環遊世界很多次。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-003-b",
        text: "表哥滑雪好厲害，改天教教我怎麼存旅費。",
        archetype: "deflect",
        retort: "存旅費？你自己要有紀律。",
      },
      {
        id: "sanjiuma-comparison-003-c",
        text: "舅媽有沒有想去哪玩，我幫你查機票？",
        archetype: "deflect",
        retort: "查機票？你自己先出國吧。",
      },
      {
        id: "sanjiuma-comparison-003-d",
        text: "沒出國，錢都拿去繳房租了……",
        archetype: "meek",
        retort: "房租多少？那你怎麼存旅費？",
      },
      {
        id: "sanjiuma-comparison-003-e",
        text: "本來想去，但假期都被工作吃掉了……",
        archetype: "meek",
        retort: "吃掉了？那你有沒有去談休假？",
      },
      {
        id: "sanjiuma-comparison-003-f",
        text: "我在家看Youtube雲旅遊，一樣開心。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-003-g",
        text: "出不出國不重要，重要的是心境已飛。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-003-h",
        text: "表哥去滑雪該不會是舅舅出的旅費。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-004",
    text: "表哥辦了健身房會員，你有在運動嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-004-a",
        text: "我的運動是躲舅媽的問題，強度很夠。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的很會講。",
      },
      {
        id: "sanjiuma-comparison-004-b",
        text: "表哥練得怎樣，改天約我一起去嘛。",
        archetype: "deflect",
        retort: "好啊好啊，你自己要有恆心。",
      },
      {
        id: "sanjiuma-comparison-004-c",
        text: "舅媽有沒有在運動，要不要一起去走走？",
        archetype: "deflect",
        retort: "我這把年紀走走就好了。",
      },
      {
        id: "sanjiuma-comparison-004-d",
        text: "沒有耶，下班都只想躺著……",
        archetype: "meek",
        retort: "躺著？那你身體怎麼辦？",
      },
      {
        id: "sanjiuma-comparison-004-e",
        text: "有想過辦會員，但錢不夠……",
        archetype: "meek",
        retort: "不夠？那你要不要先存一存？",
      },
      {
        id: "sanjiuma-comparison-004-f",
        text: "我的健身房是我的床，訓練意志力。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-004-g",
        text: "運動不重要，重要的是心靈健身。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-004-h",
        text: "表哥辦會員該不會是舅舅幫忙付的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-005",
    text: "表哥又考到一張證照，你有在進修嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-005-a",
        text: "在進修，我修的是人生的抗壓學分。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-005-b",
        text: "表哥證照那麼多，教教我怎麼準備考試。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-005-c",
        text: "舅媽有沒有想考什麼，我陪你一起考？",
        archetype: "deflect",
        retort: "我這把年紀考什麼證照。",
      },
      {
        id: "sanjiuma-comparison-005-d",
        text: "沒有耶，下班太累不想讀書……",
        archetype: "meek",
        retort: "太累？那你要怎麼進步？",
      },
      {
        id: "sanjiuma-comparison-005-e",
        text: "有想考，但一直沒空準備……",
        archetype: "meek",
        retort: "沒空？那你打算拖到什麼時候？",
      },
      {
        id: "sanjiuma-comparison-005-f",
        text: "我考的是人生體驗證照，比較稀有。",
        archetype: "backfire",
        retort: "……（沒人聽懂，繼續吃飯）",
      },
      {
        id: "sanjiuma-comparison-005-g",
        text: "證照不重要，重要的是實戰經驗。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-comparison-005-h",
        text: "表哥證照那麼多是不是舅媽花錢送考的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-006",
    text: "表哥朋友都是老闆，你朋友圈都是誰？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-006-a",
        text: "我朋友都是未來的老闆，我先卡位認識。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-006-b",
        text: "表哥人脈這麼廣，改天介紹幾個給我。",
        archetype: "deflect",
        retort: "介紹？你自己要努力經營。",
      },
      {
        id: "sanjiuma-comparison-006-c",
        text: "舅媽朋友圈也很廣，要不要介紹客戶給我？",
        archetype: "deflect",
        retort: "介紹客戶？你先做出成績。",
      },
      {
        id: "sanjiuma-comparison-006-d",
        text: "我朋友都普通上班族，沒什麼大人物……",
        archetype: "meek",
        retort: "普通？那你怎麼不多認識人？",
      },
      {
        id: "sanjiuma-comparison-006-e",
        text: "沒什麼人脈，都是自己單打獨鬥……",
        archetype: "meek",
        retort: "單打獨鬥？那太辛苦了吧。",
      },
      {
        id: "sanjiuma-comparison-006-f",
        text: "我的人脈是隱藏版，深藏不露。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-comparison-006-g",
        text: "人脈不重要，重要的是真心朋友。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-006-h",
        text: "表哥那些老闆朋友該不會都是舅舅介紹的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-007",
    text: "表哥紅包包八千，你今年包多少？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-007-a",
        text: "我包的是誠意，數字寫在心裡最實在。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-007-b",
        text: "表哥八千好大方，改天教教我理財。",
        archetype: "deflect",
        retort: "這個要看緣分，你慢慢學。",
      },
      {
        id: "sanjiuma-comparison-007-c",
        text: "舅媽紅包行情怎樣，先透露一下？",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-comparison-007-d",
        text: "我大概包兩千，比較有限……",
        archetype: "meek",
        retort: "兩千？那你薪水夠不夠用？",
      },
      {
        id: "sanjiuma-comparison-007-e",
        text: "還沒包，怕包太少不好意思……",
        archetype: "meek",
        retort: "不好意思？那你到底包多少？",
      },
      {
        id: "sanjiuma-comparison-007-f",
        text: "紅包我用信用卡分期支付，划算。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-007-g",
        text: "金額不重要，重要的是紅包袋設計。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-007-h",
        text: "表哥包八千該不會是舅舅先塞給他的。",
        archetype: "landmine",
        retort: "你！誰跟你講的！他才沒有！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-008",
    text: "表哥換新手機了，你這支用幾年了？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-008-a",
        text: "用五年了，跟舅媽的碎念一樣耐操。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的很會講。",
      },
      {
        id: "sanjiuma-comparison-008-b",
        text: "表哥新手機好厲害，教我怎麼分期付款。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-008-c",
        text: "舅媽手機用得順嗎？我可以幫你設定。",
        archetype: "deflect",
        retort: "好啊，改天教教我怎麼用。",
      },
      {
        id: "sanjiuma-comparison-008-d",
        text: "用很多年了，螢幕都裂了……",
        archetype: "meek",
        retort: "裂了？那你怎麼不換一支？",
      },
      {
        id: "sanjiuma-comparison-008-e",
        text: "沒錢換，先將就用著……",
        archetype: "meek",
        retort: "將就？那你能撐多久？",
      },
      {
        id: "sanjiuma-comparison-008-f",
        text: "手機是舊的沒關係，靈魂是新的。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-008-g",
        text: "換不換手機不重要，重要的是內心科技感。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-008-h",
        text: "表哥新手機該不會是舅舅刷卡買的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-009",
    text: "我朋友的小孩會彈鋼琴，你會什麼才藝？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-009-a",
        text: "我的才藝是把場面聊得比鋼琴還動聽。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-009-b",
        text: "那個小孩好厲害，改天介紹我認識一下？",
        archetype: "deflect",
        retort: "認識幹嘛，你先顧好自己。",
      },
      {
        id: "sanjiuma-comparison-009-c",
        text: "舅媽有沒有才藝，教我一招防身？",
        archetype: "deflect",
        retort: "我這把年紀哪還有才藝。",
      },
      {
        id: "sanjiuma-comparison-009-d",
        text: "我沒什麼才藝，普通人一個……",
        archetype: "meek",
        retort: "普通？那你有什麼興趣沒有？",
      },
      {
        id: "sanjiuma-comparison-009-e",
        text: "小時候學過，早就忘光了……",
        archetype: "meek",
        retort: "忘光了？那你現在有在學什麼？",
      },
      {
        id: "sanjiuma-comparison-009-f",
        text: "我的才藝是深藏不露，藏到自己都忘了。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-comparison-009-g",
        text: "才藝不重要，重要的是有沒有觀眾。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-009-h",
        text: "那小孩是不是靠補習班硬塞出來的。",
        archetype: "landmine",
        retort: "你這孩子怎麼這樣講話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-010",
    text: "我朋友的小孩考第一名，你以前呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-010-a",
        text: "我以前考的是人緣第一名，比較實用。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-010-b",
        text: "那小孩好優秀，改天請他教教我。",
        archetype: "deflect",
        retort: "教什麼，你自己要努力。",
      },
      {
        id: "sanjiuma-comparison-010-c",
        text: "舅媽以前成績怎樣，先分享一下？",
        archetype: "deflect",
        retort: "我以前可是全班前三名的。",
      },
      {
        id: "sanjiuma-comparison-010-d",
        text: "我以前成績普普，中等而已……",
        archetype: "meek",
        retort: "中等？那現在工作有比較好嗎？",
      },
      {
        id: "sanjiuma-comparison-010-e",
        text: "沒考過第一名，都是後段班……",
        archetype: "meek",
        retort: "後段班？那你現在急起直追了嗎？",
      },
      {
        id: "sanjiuma-comparison-010-f",
        text: "成績不重要，重要的是社會歷練。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-010-g",
        text: "我的排名是隱藏關卡，沒人破解過。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-010-h",
        text: "那小孩考第一該不會是家教硬塞出來的。",
        archetype: "landmine",
        retort: "你這孩子怎麼這樣講話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-011",
    text: "表哥公司股票分紅一年多好幾萬，你呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-011-a",
        text: "我沒股票，但我的存在感就是紅利。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-011-b",
        text: "表哥公司股票這麼好，教我怎麼投資。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-011-c",
        text: "舅媽有沒有買股票，要不要跟我分享？",
        archetype: "deflect",
        retort: "我這年紀不玩股票了。",
      },
      {
        id: "sanjiuma-comparison-011-d",
        text: "沒有股票，公司也沒有分紅制度……",
        archetype: "meek",
        retort: "沒有？那你怎麼不去問清楚？",
      },
      {
        id: "sanjiuma-comparison-011-e",
        text: "有一點基金，但都套牢中……",
        archetype: "meek",
        retort: "套牢？那虧多少你要說清楚。",
      },
      {
        id: "sanjiuma-comparison-011-f",
        text: "我投資的是自己，複利算不完。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-011-g",
        text: "分紅不重要，重要的是公司氛圍。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-011-h",
        text: "表哥的分紅該不會是舅舅塞的股票。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-012",
    text: "表哥車位就在市中心，你停哪？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-012-a",
        text: "我停路邊，順便訓練停車技術，比較實用。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-012-b",
        text: "市中心車位好貴，表哥真的很厲害。",
        archetype: "deflect",
        retort: "當然，他很努力賺的。",
      },
      {
        id: "sanjiuma-comparison-012-c",
        text: "舅媽車停哪，改天陪你一起去繳費？",
        archetype: "deflect",
        retort: "陪我繳費？你別鬧了啦。",
      },
      {
        id: "sanjiuma-comparison-012-d",
        text: "沒車，也沒車位可以停……",
        archetype: "meek",
        retort: "沒車？那上班怎麼通勤的？",
      },
      {
        id: "sanjiuma-comparison-012-e",
        text: "騎機車，隨便找地方停就好……",
        archetype: "meek",
        retort: "隨便停？那有沒有被拖吊過？",
      },
      {
        id: "sanjiuma-comparison-012-f",
        text: "我把心停在市中心，比車位還精華。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-012-g",
        text: "車位不重要，重要的是騎車自由。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-012-h",
        text: "表哥車位該不會也是舅舅買的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-013",
    text: "表哥考上研究所了，你學歷到哪？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-013-a",
        text: "我學歷普通，但社會歷練是研究所等級。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-013-b",
        text: "表哥考上哪間，要不要陪我一起去考？",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-013-c",
        text: "舅媽當年學歷怎樣，跟我分享一下？",
        archetype: "deflect",
        retort: "我那個年代讀書機會少啦。",
      },
      {
        id: "sanjiuma-comparison-013-d",
        text: "我大學畢業，沒有繼續升學……",
        archetype: "meek",
        retort: "沒升學？那你有沒有後悔？",
      },
      {
        id: "sanjiuma-comparison-013-e",
        text: "本來想考，但沒時間準備……",
        archetype: "meek",
        retort: "沒時間？那你要不要現在報名？",
      },
      {
        id: "sanjiuma-comparison-013-f",
        text: "學歷不重要，重要的是我很有見識。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-013-g",
        text: "我的學歷是社會大學，比較硬派。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-013-h",
        text: "表哥考上研究所該不會是舅舅打點的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-014",
    text: "表哥要出國進修了，你有出國計畫嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-014-a",
        text: "有計畫，我打算先環遊我家附近，累積經驗。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-014-b",
        text: "表哥出國進修，改天教我怎麼申請。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-014-c",
        text: "舅媽有沒有想出國走走，我幫你查？",
        archetype: "deflect",
        retort: "我這把年紀不想出國了。",
      },
      {
        id: "sanjiuma-comparison-014-d",
        text: "沒計畫，光生活費就不夠了……",
        archetype: "meek",
        retort: "不夠？那你薪水到底多少？",
      },
      {
        id: "sanjiuma-comparison-014-e",
        text: "有想過，但語言能力不夠好……",
        archetype: "meek",
        retort: "不夠好？那你要不要去學？",
      },
      {
        id: "sanjiuma-comparison-014-f",
        text: "我的進修計畫是每天進修睡眠。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-014-g",
        text: "出國不重要，重要的是心境進修。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-014-h",
        text: "表哥出國進修學費是不是舅舅出的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-015",
    text: "表哥買名牌包送女友，你有送過什麼？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-015-a",
        text: "我送的是真心，比名牌包更難仿冒。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-015-b",
        text: "表哥女友一定很開心，他們感情真好。",
        archetype: "deflect",
        retort: "當然好，表哥很懂浪漫的。",
      },
      {
        id: "sanjiuma-comparison-015-c",
        text: "舅媽有沒有收過什麼禮物，分享一下？",
        archetype: "deflect",
        retort: "問我幹嘛，你自己去準備。",
      },
      {
        id: "sanjiuma-comparison-015-d",
        text: "還沒有對象，沒機會送禮物……",
        archetype: "meek",
        retort: "沒對象？那你打算單身多久？",
      },
      {
        id: "sanjiuma-comparison-015-e",
        text: "有送過小禮物，沒那麼貴重……",
        archetype: "meek",
        retort: "不貴重？那對方會不會嫌棄？",
      },
      {
        id: "sanjiuma-comparison-015-f",
        text: "我送的禮物是我自己，物超所值。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-015-g",
        text: "禮物不重要，重要的是陪伴的時間。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-015-h",
        text: "表哥買名牌包該不會是舅舅刷卡的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-016",
    text: "表哥開始打高爾夫球了，你有什麼興趣？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-016-a",
        text: "我的興趣是聽舅媽講表哥的事，很療癒。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的很會講。",
      },
      {
        id: "sanjiuma-comparison-016-b",
        text: "高爾夫聽起來很優雅，改天教教我嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-016-c",
        text: "舅媽有沒有興趣，要不要一起運動？",
        archetype: "deflect",
        retort: "我這把年紀運動就好了。",
      },
      {
        id: "sanjiuma-comparison-016-d",
        text: "沒什麼興趣，下班就只想耍廢……",
        archetype: "meek",
        retort: "耍廢？那你身體怎麼辦？",
      },
      {
        id: "sanjiuma-comparison-016-e",
        text: "有興趣但太貴，玩不起高爾夫……",
        archetype: "meek",
        retort: "太貴？那你有沒有別的運動？",
      },
      {
        id: "sanjiuma-comparison-016-f",
        text: "我的興趣是收藏沒興趣，很稀有。",
        archetype: "backfire",
        retort: "……（沒人聽懂，繼續吃飯）",
      },
      {
        id: "sanjiuma-comparison-016-g",
        text: "興趣不重要，重要的是內心平靜。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-016-h",
        text: "表哥打高爾夫該不會是舅舅出的會費。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-017",
    text: "表哥存款七位數了，你的存摺有幾位數？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-017-a",
        text: "我的存摺位數少，但幸福感位數很多。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-017-b",
        text: "表哥七位數好厲害，教教我怎麼存錢。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-017-c",
        text: "舅媽存款有幾位數，先透露一下嘛？",
        archetype: "deflect",
        retort: "這是秘密，不能隨便講。",
      },
      {
        id: "sanjiuma-comparison-017-d",
        text: "我的存摺只有五位數，差很多……",
        archetype: "meek",
        retort: "差很多？那你要怎麼追上？",
      },
      {
        id: "sanjiuma-comparison-017-e",
        text: "存款不多，月光族一個……",
        archetype: "meek",
        retort: "月光？那你打算什麼時候存？",
      },
      {
        id: "sanjiuma-comparison-017-f",
        text: "位數不重要，重要的是存摺封面漂亮。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-017-g",
        text: "我的財富是無形資產，看不見的。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-comparison-017-h",
        text: "表哥七位數是不是舅舅每年偷偷塞的。",
        archetype: "landmine",
        retort: "你！誰跟你講的！他才沒有！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-018",
    text: "表哥的名片頭銜是副理，你的呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-018-a",
        text: "我的頭銜是自由，比副理還難升等。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的厲害。",
      },
      {
        id: "sanjiuma-comparison-018-b",
        text: "表哥副理當得怎樣，教教我怎麼升遷。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-018-c",
        text: "舅媽以前頭銜是什麼，分享一下嘛？",
        archetype: "deflect",
        retort: "我以前是家庭主婦頭銜最大。",
      },
      {
        id: "sanjiuma-comparison-018-d",
        text: "我就是專員，沒什麼頭銜……",
        archetype: "meek",
        retort: "專員？那什麼時候能升遷？",
      },
      {
        id: "sanjiuma-comparison-018-e",
        text: "還是基層，升遷機會不多……",
        archetype: "meek",
        retort: "不多？那你有沒有去爭取？",
      },
      {
        id: "sanjiuma-comparison-018-f",
        text: "頭銜不重要，重要的是我心中是總裁。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-018-g",
        text: "我自封為快樂總監，職稱響亮。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-018-h",
        text: "表哥副理該不會是舅舅打點好的職位。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-019",
    text: "表哥連續三年考核甲等，你考核幾等？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-019-a",
        text: "我考核不重要，重要的是我從不缺席聚餐。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-019-b",
        text: "表哥考核那麼好，教教我怎麼表現。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-019-c",
        text: "舅媽以前工作表現怎樣，分享一下？",
        archetype: "deflect",
        retort: "我以前可是模範員工的。",
      },
      {
        id: "sanjiuma-comparison-019-d",
        text: "我大概乙等，普通表現……",
        archetype: "meek",
        retort: "乙等？那你有沒有想辦法提升？",
      },
      {
        id: "sanjiuma-comparison-019-e",
        text: "考核成績不太好，還在檢討……",
        archetype: "meek",
        retort: "不太好？那到底哪裡出問題？",
      },
      {
        id: "sanjiuma-comparison-019-f",
        text: "考核不重要，重要的是我天天笑臉迎人。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-019-g",
        text: "我的考核標準是自己開心就給甲等。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-019-h",
        text: "表哥連續甲等該不會是舅舅公司自己人。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-020",
    text: "表哥尾牙抽到出國機票，你抽到什麼？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-020-a",
        text: "我抽到跟舅媽聊天的機會，價值連城。",
        archetype: "perfect",
        retort: "……你這孩子，嘴巴真的很會講。",
      },
      {
        id: "sanjiuma-comparison-020-b",
        text: "表哥抽到機票太幸運了，要不要帶我去？",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-020-c",
        text: "舅媽尾牙有沒有抽到什麼，分享一下？",
        archetype: "deflect",
        retort: "我沒去尾牙，都在家等你們。",
      },
      {
        id: "sanjiuma-comparison-020-d",
        text: "沒抽到，只抽到一包面紙……",
        archetype: "meek",
        retort: "面紙？那你到底運氣多差？",
      },
      {
        id: "sanjiuma-comparison-020-e",
        text: "沒去尾牙，加班沒辦法參加……",
        archetype: "meek",
        retort: "加班？那薪水有比較多嗎？",
      },
      {
        id: "sanjiuma-comparison-020-f",
        text: "我把自己抽成了年度最佳氣氛擔當。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-comparison-020-g",
        text: "抽獎不重要，重要的是尾牙的美食。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-020-h",
        text: "表哥抽到機票該不會是內定的吧。",
        archetype: "landmine",
        retort: "你！誰跟你講的！他才沒有！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-021",
    text: "表哥社團裡朋友都是老闆，你朋友呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-021-a",
        text: "我朋友都在基層，但基層才是社會的骨幹。",
        archetype: "perfect",
        retort: "……你這孩子，講話一套一套的。",
      },
      {
        id: "sanjiuma-comparison-021-b",
        text: "表哥社團這麼厲害，介紹我加入嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-comparison-021-c",
        text: "舅媽有沒有參加什麼社團，分享一下？",
        archetype: "deflect",
        retort: "我這把年紀不參加社團了。",
      },
      {
        id: "sanjiuma-comparison-021-d",
        text: "我朋友都普通上班族，沒什麼老闆……",
        archetype: "meek",
        retort: "普通？那你怎麼不多認識人？",
      },
      {
        id: "sanjiuma-comparison-021-e",
        text: "沒參加社團，下班只想休息……",
        archetype: "meek",
        retort: "休息？那你怎麼拓展人脈？",
      },
      {
        id: "sanjiuma-comparison-021-f",
        text: "我的社團是深夜追劇同好會。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-comparison-021-g",
        text: "朋友職業不重要，重要的是真心。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-comparison-021-h",
        text: "表哥那些老闆朋友該不會都是舅媽介紹的。",
        archetype: "landmine",
        retort: "你這什麼意思！他是憑實力的！",
      },
    ],
  },
] satisfies Question[];
