import type { Question } from "@/content/types";

export default [
  {
    id: "sanjiuma-comparison-002",
    text: "表哥換新車了，你那台是什麼時候買的？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-002-a",
        text: "幹，表哥換車是舅舅換的吧，他自己有出半毛嗎？",
        archetype: "perfect",
        retort: "你他媽的胡說，錢是他自己賺的！",
      },
      {
        id: "sanjiuma-comparison-002-b",
        text: "靠，我這台開得順啦，舅媽要不要試坐看看？",
        archetype: "deflect",
        retort: "試坐？我才不要坐那台破車。",
      },
      {
        id: "sanjiuma-comparison-002-c",
        text: "笑死，代步夠用就好，跑車也是塞在路上。",
        archetype: "deflect",
        retort: "塞車也要塞得起面子啦。",
      },
      {
        id: "sanjiuma-comparison-002-d",
        text: "幹……開好幾年了，能省則省……",
        archetype: "meek",
        retort: "省成這樣，是要省到什麼時候？",
      },
      {
        id: "sanjiuma-comparison-002-e",
        text: "靠……車子壞了都捨不得換……",
        archetype: "meek",
        retort: "捨不得換，那你是要騎多久？",
      },
      {
        id: "sanjiuma-comparison-002-f",
        text: "靠，我車子是有故事的，不是有錢就能買到的啦。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-comparison-002-g",
        text: "他媽的，我這台其實是租的，別跟舅舅講。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-comparison-002-h",
        text: "機掰，表哥換車是舅舅換的，妳倒好意思說他能幹，老東西？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-003",
    text: "表哥去日本滑雪了，你今年有出國嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-003-a",
        text: "靠北，滑雪傷得多重，妳知道嗎，還是只知道打卡？",
        archetype: "perfect",
        retort: "去死啦你，講話這麼難聽！",
      },
      {
        id: "sanjiuma-comparison-003-b",
        text: "靠，沒去啦，舅媽要不要贊助我機票錢？",
        archetype: "deflect",
        retort: "贊助？你當我是航空公司喔。",
      },
      {
        id: "sanjiuma-comparison-003-c",
        text: "笑死，國內玩夠深度就好，不用跑那麼遠。",
        archetype: "deflect",
        retort: "深度？深度能拍照打卡嗎。",
      },
      {
        id: "sanjiuma-comparison-003-d",
        text: "幹……存款不夠出國，只能在家過年……",
        archetype: "meek",
        retort: "存款不夠，那要更努力賺啊。",
      },
      {
        id: "sanjiuma-comparison-003-e",
        text: "靠……機票太貴，捨不得花……",
        archetype: "meek",
        retort: "捨不得花，那你什麼時候要享受？",
      },
      {
        id: "sanjiuma-comparison-003-f",
        text: "幹，我出國是用夢遊的方式啦，比較省。",
        archetype: "backfire",
        retort: "……（舅媽轉頭滑手機）",
      },
      {
        id: "sanjiuma-comparison-003-g",
        text: "靠北，我其實有訂機票，結果訂錯日期。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-003-h",
        text: "幹你娘，滑雪摔斷腿算誰的，老太婆妳先想清楚再炫耀。",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-004",
    text: "表哥辦了健身房會員，你有在運動嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-004-a",
        text: "他媽的，辦會員跟真的運動是兩回事吧，舅媽妳懂嗎？",
        archetype: "perfect",
        retort: "你這什麼態度！他有在練好嗎！",
      },
      {
        id: "sanjiuma-comparison-004-b",
        text: "靠，還好啦，舅媽要不要跟我一起運動？",
        archetype: "deflect",
        retort: "跟你？我這把年紀還爬什麼山。",
      },
      {
        id: "sanjiuma-comparison-004-c",
        text: "笑死，我在家自己練，省會費啦。",
        archetype: "deflect",
        retort: "省會費，那你有練出成果嗎？",
      },
      {
        id: "sanjiuma-comparison-004-d",
        text: "幹……辦了會員都沒去，浪費錢……",
        archetype: "meek",
        retort: "浪費錢就要檢討自己啊。",
      },
      {
        id: "sanjiuma-comparison-004-e",
        text: "靠……沒錢辦會員，只能路跑……",
        archetype: "meek",
        retort: "路跑省錢是省錢，但曬得黑黑的。",
      },
      {
        id: "sanjiuma-comparison-004-f",
        text: "靠，我運動是用意念做的，比較高階。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-004-g",
        text: "機掰，我辦了會員結果去一次就辦退卡。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-comparison-004-h",
        text: "去你的，辦會員不去打卡跟妳供神明一樣，老東西，心誠則靈？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-005",
    text: "表哥又考到一張證照，你有在進修嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-005-a",
        text: "幹，考證照是他考的還是舅舅出錢買的？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己考的！",
      },
      {
        id: "sanjiuma-comparison-005-b",
        text: "靠北，有在準備啦，舅媽有考古題可以給我嗎？",
        archetype: "deflect",
        retort: "考古題？你當我是補習班喔。",
      },
      {
        id: "sanjiuma-comparison-005-c",
        text: "笑死，證照這種東西，有實力比較重要啦。",
        archetype: "deflect",
        retort: "有實力也要有證照證明啊。",
      },
      {
        id: "sanjiuma-comparison-005-d",
        text: "幹……最近太忙，沒空進修……",
        archetype: "meek",
        retort: "太忙？那你到底在忙什麼？",
      },
      {
        id: "sanjiuma-comparison-005-e",
        text: "靠……報名費太貴，捨不得繳……",
        archetype: "meek",
        retort: "捨不得繳，那你怎麼進步？",
      },
      {
        id: "sanjiuma-comparison-005-f",
        text: "靠，我的證照都放在心裡，看不到的那種。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在講幹話）",
      },
      {
        id: "sanjiuma-comparison-005-g",
        text: "他媽的，我報名了結果忘記去考。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-comparison-005-h",
        text: "幹，一張證照就那麼臭屁，妳是不是很閒，老太婆？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-006",
    text: "表哥朋友都是老闆，你朋友圈都是誰？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-006-a",
        text: "靠北，都是老闆，是不是都欠他錢，舅媽妳查過嗎？",
        archetype: "perfect",
        retort: "你這什麼意思，講話這麼賤！",
      },
      {
        id: "sanjiuma-comparison-006-b",
        text: "靠，我朋友都是普通人啦，舅媽要不要來認識？",
        archetype: "deflect",
        retort: "認識？我才沒空理你朋友。",
      },
      {
        id: "sanjiuma-comparison-006-c",
        text: "笑死，朋友重質不重量，夠用就好。",
        archetype: "deflect",
        retort: "質？我看你根本沒朋友吧。",
      },
      {
        id: "sanjiuma-comparison-006-d",
        text: "幹……我朋友圈都普通上班族，沒什麼厲害的……",
        archetype: "meek",
        retort: "普通有什麼好講的，多認識點人。",
      },
      {
        id: "sanjiuma-comparison-006-e",
        text: "靠……朋友不多，但都是真心的……",
        archetype: "meek",
        retort: "真心能換成錢嗎？",
      },
      {
        id: "sanjiuma-comparison-006-f",
        text: "幹，我朋友都是隱藏版老闆，你們不認識而已啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼」）",
      },
      {
        id: "sanjiuma-comparison-006-g",
        text: "靠北，我把朋友都得罪光了，最近很孤單。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-006-h",
        text: "幹你娘，表哥朋友都是老闆，是不是都靠舅舅牽線，老東西？",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-007",
    text: "表哥紅包包八千，你今年包多少？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-007-a",
        text: "機掰，紅包包八千，是他自己賺的還是舅舅塞的？",
        archetype: "perfect",
        retort: "你他媽的講話這麼衝，他自己賺的！",
      },
      {
        id: "sanjiuma-comparison-007-b",
        text: "靠，看心意啦，舅媽今年包多少給我？",
        archetype: "deflect",
        retort: "包多少關你什麼事啦。",
      },
      {
        id: "sanjiuma-comparison-007-c",
        text: "笑死，紅包意思到就好，不用比金額。",
        archetype: "deflect",
        retort: "不比金額，那你是嫌少喔？",
      },
      {
        id: "sanjiuma-comparison-007-d",
        text: "幹……我今年包得比較少，手頭緊……",
        archetype: "meek",
        retort: "手頭緊也要撐個面子啊。",
      },
      {
        id: "sanjiuma-comparison-007-e",
        text: "靠……包完紅包我自己都快沒錢吃飯了……",
        archetype: "meek",
        retort: "沒錢吃飯就別亂花錢啊。",
      },
      {
        id: "sanjiuma-comparison-007-f",
        text: "靠，我今年包的是心意，不是現金，比較特別。",
        archetype: "backfire",
        retort: "……（舅媽翻白眼）",
      },
      {
        id: "sanjiuma-comparison-007-g",
        text: "他媽的，我包錯紅包袋，包成喜帖的了。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-007-h",
        text: "去你的，包八千是不是舅舅塞給他的私房錢，老太婆？",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-008",
    text: "表哥換新手機了，你這支用幾年了？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-008-a",
        text: "幹，換新手機是換了殼還是換了腦袋，舅媽？",
        archetype: "perfect",
        retort: "你他媽的沒大沒小，欠罵是不是！",
      },
      {
        id: "sanjiuma-comparison-008-b",
        text: "靠北，還能用啦，舅媽要不要贊助我一支？",
        archetype: "deflect",
        retort: "贊助？你當我是電信公司喔。",
      },
      {
        id: "sanjiuma-comparison-008-c",
        text: "笑死，手機夠用就好，功能我又用不完。",
        archetype: "deflect",
        retort: "用不完，那你根本不需要新手機吧。",
      },
      {
        id: "sanjiuma-comparison-008-d",
        text: "幹……用了快五年，螢幕都裂了……",
        archetype: "meek",
        retort: "裂了怎麼不換，你在省什麼？",
      },
      {
        id: "sanjiuma-comparison-008-e",
        text: "靠……存錢中，捨不得買新的……",
        archetype: "meek",
        retort: "捨不得，那要存到什麼時候？",
      },
      {
        id: "sanjiuma-comparison-008-f",
        text: "靠，我這支手機是骨董，未來會增值啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-comparison-008-g",
        text: "機掰，我手機摔壞了正想換，結果又捨不得。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-comparison-008-h",
        text: "幹，換手機是不是舅舅刷卡付的，老東西妳臉不紅？",
        archetype: "landmine",
        retort: "你這什麼態度，欠教訓是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-009",
    text: "我朋友的小孩會彈鋼琴，你會什麼才藝？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-009-a",
        text: "他媽的，會彈鋼琴以後是要幫妳伴奏喔，舅媽？",
        archetype: "perfect",
        retort: "你這孩子講話越來越沒大沒小！",
      },
      {
        id: "sanjiuma-comparison-009-b",
        text: "靠，才藝很俗氣啦，舅媽妳會什麼？",
        archetype: "deflect",
        retort: "我會什麼關你屁事，讀書啦。",
      },
      {
        id: "sanjiuma-comparison-009-c",
        text: "笑死，才藝這種東西，長大就忘光了。",
        archetype: "deflect",
        retort: "忘光了，那你小時候學假的喔。",
      },
      {
        id: "sanjiuma-comparison-009-d",
        text: "幹……我什麼才藝都沒有，普通人一個……",
        archetype: "meek",
        retort: "普通人一個？那你要加油啊。",
      },
      {
        id: "sanjiuma-comparison-009-e",
        text: "靠……小時候沒錢學才藝，只能羨慕……",
        archetype: "meek",
        retort: "羨慕沒用，長大要自己補起來。",
      },
      {
        id: "sanjiuma-comparison-009-f",
        text: "幹，我會的才藝是講幹話，這個很稀有。",
        archetype: "backfire",
        retort: "……（舅媽完全聽不懂在說什麼）",
      },
      {
        id: "sanjiuma-comparison-009-g",
        text: "靠北，我以前學過鋼琴，結果彈到放棄。",
        archetype: "backfire",
        retort: "……（沒人回應）",
      },
      {
        id: "sanjiuma-comparison-009-h",
        text: "幹，表哥五音不全，也敢嫌別人沒才藝？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-010",
    text: "我朋友的小孩考第一名，你以前呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-010-a",
        text: "靠北，考第一名跟我有什麼關係，妳是他家長嗎？",
        archetype: "perfect",
        retort: "你這什麼話，胡說八道！",
      },
      {
        id: "sanjiuma-comparison-010-b",
        text: "靠，我以前成績還可以啦，舅媽要不要看成績單？",
        archetype: "deflect",
        retort: "成績單？都幾年前的事還拿出來。",
      },
      {
        id: "sanjiuma-comparison-010-c",
        text: "笑死，成績不重要，出社會又不考試。",
        archetype: "deflect",
        retort: "出社會不考試，但要考驗做人。",
      },
      {
        id: "sanjiuma-comparison-010-d",
        text: "幹……我以前成績普通，沒什麼好講的……",
        archetype: "meek",
        retort: "普通？那現在更要努力補回來。",
      },
      {
        id: "sanjiuma-comparison-010-e",
        text: "靠……以前唸書不專心，現在後悔……",
        archetype: "meek",
        retort: "後悔沒用，早幹嘛去了。",
      },
      {
        id: "sanjiuma-comparison-010-f",
        text: "靠，我以前是隱藏學霸，只是沒展現出來。",
        archetype: "backfire",
        retort: "……（舅媽覺得莫名其妙）",
      },
      {
        id: "sanjiuma-comparison-010-g",
        text: "他媽的，我以前作弊被抓過，別跟舅媽講。",
        archetype: "backfire",
        retort: "……（沒人搭話）",
      },
      {
        id: "sanjiuma-comparison-010-h",
        text: "去死啦，妳朋友的小孩考第一名關你屁事，老太婆很無聊喔？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-011",
    text: "表哥公司股票分紅一年多好幾萬，你呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-011-a",
        text: "幹，股票分紅好幾萬，是不是舅舅內線消息給他的？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己投資的！",
      },
      {
        id: "sanjiuma-comparison-011-b",
        text: "靠北，我沒股票啦，舅媽要不要教我怎麼買？",
        archetype: "deflect",
        retort: "教你？你會賠光我可不負責。",
      },
      {
        id: "sanjiuma-comparison-011-c",
        text: "笑死，我不玩股票，怕心臟不夠強。",
        archetype: "deflect",
        retort: "心臟不強，那你要怎麼賺錢？",
      },
      {
        id: "sanjiuma-comparison-011-d",
        text: "幹……我沒閒錢投資，光生活費都不夠……",
        archetype: "meek",
        retort: "不夠就要想辦法賺更多啊。",
      },
      {
        id: "sanjiuma-comparison-011-e",
        text: "靠……分紅這種事離我很遙遠……",
        archetype: "meek",
        retort: "遙遠也要有目標啊，別放棄。",
      },
      {
        id: "sanjiuma-comparison-011-f",
        text: "靠，我投資的是我的未來，暫時看不到報酬。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子壞了）",
      },
      {
        id: "sanjiuma-comparison-011-g",
        text: "機掰，我買的股票全部套牢，別提了。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-comparison-011-h",
        text: "幹你娘，分紅好幾萬是不是舅舅的公司做假帳，老太婆？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-012",
    text: "表哥車位就在市中心，你停哪？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-012-a",
        text: "他媽的，車位在市中心是要拿來收租吧，舅媽？",
        archetype: "perfect",
        retort: "你這孩子講話怎麼這麼毒！",
      },
      {
        id: "sanjiuma-comparison-012-b",
        text: "靠，我停路邊啦，舅媽要不要幫我付停車費？",
        archetype: "deflect",
        retort: "停車費？你當我銀行喔。",
      },
      {
        id: "sanjiuma-comparison-012-c",
        text: "笑死，路邊停免費，省錢又環保。",
        archetype: "deflect",
        retort: "省錢是省錢，被拖吊算誰的？",
      },
      {
        id: "sanjiuma-comparison-012-d",
        text: "幹……我連停車位都租不起，只能違停……",
        archetype: "meek",
        retort: "違停會被開單，你不怕喔？",
      },
      {
        id: "sanjiuma-comparison-012-e",
        text: "靠……騎機車不用煩惱車位，窮有窮的活法……",
        archetype: "meek",
        retort: "窮有窮的活法，那你要窮到什麼時候？",
      },
      {
        id: "sanjiuma-comparison-012-f",
        text: "幹，我的車位在我心裡，隨時能停啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在做夢）",
      },
      {
        id: "sanjiuma-comparison-012-g",
        text: "靠，我剛被拖吊，正在氣頭上。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-012-h",
        text: "幹，市中心車位是不是舅舅公司的名下，老東西？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-013",
    text: "表哥考上研究所了，你學歷到哪？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-013-a",
        text: "機掰，考研究所是他考的還是舅舅塞的推薦函？",
        archetype: "perfect",
        retort: "你！誰跟你講的！他自己考的！",
      },
      {
        id: "sanjiuma-comparison-013-b",
        text: "靠北，我學歷夠用啦，舅媽有推薦哪間學校嗎？",
        archetype: "deflect",
        retort: "推薦？你當我升學顧問喔。",
      },
      {
        id: "sanjiuma-comparison-013-c",
        text: "笑死，學歷不是唯一標準，實力才重要。",
        archetype: "deflect",
        retort: "實力重要，那你倒是拿出來啊。",
      },
      {
        id: "sanjiuma-comparison-013-d",
        text: "幹……我學歷普通，考不上研究所……",
        archetype: "meek",
        retort: "考不上就要加把勁補習啊。",
      },
      {
        id: "sanjiuma-comparison-013-e",
        text: "靠……沒錢補習，只能自己讀……",
        archetype: "meek",
        retort: "自己讀？那你考得上嗎？",
      },
      {
        id: "sanjiuma-comparison-013-f",
        text: "幹，我學歷雖然普通，但氣質過人啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-013-g",
        text: "靠北，我報名研究所結果考試日期記錯。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-comparison-013-h",
        text: "幹，研究所是他考的還是花錢買的，老太婆妳敢保證？",
        archetype: "landmine",
        retort: "去你的，沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-014",
    text: "表哥要出國進修了，你有出國計畫嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-014-a",
        text: "靠北，出國進修還是出國玩，舅媽妳分得清楚嗎？",
        archetype: "perfect",
        retort: "你這什麼意思！他是真的去進修！",
      },
      {
        id: "sanjiuma-comparison-014-b",
        text: "靠，還在規劃啦，舅媽有推薦的國家嗎？",
        archetype: "deflect",
        retort: "國家？你當我是旅行社喔。",
      },
      {
        id: "sanjiuma-comparison-014-c",
        text: "笑死，我在國內學也一樣，出國比較貴而已。",
        archetype: "deflect",
        retort: "貴就是差在那，你懂嗎。",
      },
      {
        id: "sanjiuma-comparison-014-d",
        text: "幹……存款不夠，出國進修想都不敢想……",
        archetype: "meek",
        retort: "不敢想？那你要一直原地踏步嗎？",
      },
      {
        id: "sanjiuma-comparison-014-e",
        text: "靠……英文不好，怕出國聽不懂……",
        archetype: "meek",
        retort: "聽不懂就要學啊，別找藉口。",
      },
      {
        id: "sanjiuma-comparison-014-f",
        text: "靠，我打算在家自學進修，比較省機票錢。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼廢話」）",
      },
      {
        id: "sanjiuma-comparison-014-g",
        text: "機掰，我護照過期了，出國計畫先擱著。",
        archetype: "backfire",
        retort: "……（全場沉默）",
      },
      {
        id: "sanjiuma-comparison-014-h",
        text: "幹，出國進修的錢是不是舅舅贊助的，老東西別裝清高。",
        archetype: "landmine",
        retort: "幹，你是欠罵是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-015",
    text: "表哥買名牌包送女友，你有送過什麼？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-015-a",
        text: "幹，買名牌包送女友，是舅舅刷的卡吧，舅媽？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己付的錢！",
      },
      {
        id: "sanjiuma-comparison-015-b",
        text: "靠北，我送過禮物啦，舅媽要不要看照片？",
        archetype: "deflect",
        retort: "照片？我才沒興趣看。",
      },
      {
        id: "sanjiuma-comparison-015-c",
        text: "笑死，禮物重心意，不是重價格。",
        archetype: "deflect",
        retort: "心意？那你送的東西值多少？",
      },
      {
        id: "sanjiuma-comparison-015-d",
        text: "幹……我沒錢買名牌，只能送小禮物……",
        archetype: "meek",
        retort: "小禮物？那你女友會不會嫌棄？",
      },
      {
        id: "sanjiuma-comparison-015-e",
        text: "靠……存錢中，怕送不出手……",
        archetype: "meek",
        retort: "送不出手，那你到底要拖多久？",
      },
      {
        id: "sanjiuma-comparison-015-f",
        text: "幹，我送她的是我的心，比包包貴重多了。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-comparison-015-g",
        text: "他媽的，我買錯尺寸，禮物退貨了。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-015-h",
        text: "幹你娘，名牌包是他買的還是舅舅的錢，老太婆妳查過帳嗎？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-016",
    text: "表哥開始打高爾夫球了，你有什麼興趣？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-016-a",
        text: "靠北，打高爾夫是運動還是社交裝闊，舅媽妳說呢？",
        archetype: "perfect",
        retort: "你這什麼態度！講話沒大沒小！",
      },
      {
        id: "sanjiuma-comparison-016-b",
        text: "靠，我興趣是爬山啦，舅媽要不要一起？",
        archetype: "deflect",
        retort: "一起？我這把年紀爬什麼山。",
      },
      {
        id: "sanjiuma-comparison-016-c",
        text: "笑死，興趣不用花大錢，簡單就好。",
        archetype: "deflect",
        retort: "簡單就好？那你根本沒生活品質。",
      },
      {
        id: "sanjiuma-comparison-016-d",
        text: "幹……我沒興趣，下班只想躺著……",
        archetype: "meek",
        retort: "躺著有什麼前途，找個興趣吧。",
      },
      {
        id: "sanjiuma-comparison-016-e",
        text: "靠……想學但學費太貴，只能放棄……",
        archetype: "meek",
        retort: "放棄？年輕人要有毅力。",
      },
      {
        id: "sanjiuma-comparison-016-f",
        text: "靠，我的興趣是數存款，餘額越看越開心。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-comparison-016-g",
        text: "機掰，我報名高爾夫課結果打到別人的球。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-comparison-016-h",
        text: "去你的，打高爾夫是不是舅舅公司請客，老東西別裝闊。",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-017",
    text: "表哥存款七位數了，你的存摺有幾位數？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-017-a",
        text: "他媽的，七位數存款是他存的還是舅舅過戶的，舅媽？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己存的！",
      },
      {
        id: "sanjiuma-comparison-017-b",
        text: "靠，我還在存啦，舅媽要不要分享理財訣竅？",
        archetype: "deflect",
        retort: "訣竅？你自己不會去查喔。",
      },
      {
        id: "sanjiuma-comparison-017-c",
        text: "笑死，存摺位數不重要，開心最重要。",
        archetype: "deflect",
        retort: "開心？開心能繳房租嗎。",
      },
      {
        id: "sanjiuma-comparison-017-d",
        text: "幹……我存摺位數少得可憐，別問了……",
        archetype: "meek",
        retort: "少得可憐，那要更努力存啊。",
      },
      {
        id: "sanjiuma-comparison-017-e",
        text: "靠……薪水都花完了，存不了多少……",
        archetype: "meek",
        retort: "花完了？那你要學會理財。",
      },
      {
        id: "sanjiuma-comparison-017-f",
        text: "靠，我的財富都在虛擬貨幣裡，看不到而已。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-comparison-017-g",
        text: "幹，我存摺印出來發現是負的。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-comparison-017-h",
        text: "幹，七位數存款是不是舅舅名下的錢，老太婆妳心虛什麼？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-018",
    text: "表哥的名片頭銜是副理，你的呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-018-a",
        text: "機掰，副理頭銜是他自己拚的還是舅舅安排的？",
        archetype: "perfect",
        retort: "你這什麼意思，講話這麼賤！",
      },
      {
        id: "sanjiuma-comparison-018-b",
        text: "靠北，頭銜而已啦，舅媽要不要幫我升官？",
        archetype: "deflect",
        retort: "升官？我又不是你老闆。",
      },
      {
        id: "sanjiuma-comparison-018-c",
        text: "笑死，頭銜是虛的，實質薪水才重要。",
        archetype: "deflect",
        retort: "實質薪水，那你薪水多少啦。",
      },
      {
        id: "sanjiuma-comparison-018-d",
        text: "幹……我職位很基層，沒什麼頭銜……",
        archetype: "meek",
        retort: "基層要努力往上爬啊。",
      },
      {
        id: "sanjiuma-comparison-018-e",
        text: "靠……公司升遷慢，職稱一直沒變……",
        archetype: "meek",
        retort: "一直沒變，那你要不要跳槽？",
      },
      {
        id: "sanjiuma-comparison-018-f",
        text: "幹，我名片上寫的是願景長，聽起來很潮。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在講幹話）",
      },
      {
        id: "sanjiuma-comparison-018-g",
        text: "靠北，我名片印錯字，職稱變成「副裡」。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-comparison-018-h",
        text: "幹你娘，副理是不是舅舅安排的酬庸，老東西妳說實話？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-019",
    text: "表哥連續三年考核甲等，你考核幾等？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-019-a",
        text: "幹，考核甲等是他表現好還是舅舅打的分數？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己表現好！",
      },
      {
        id: "sanjiuma-comparison-019-b",
        text: "靠，我考核還可以啦，舅媽要不要幫我美言幾句？",
        archetype: "deflect",
        retort: "美言？我又不是你主管。",
      },
      {
        id: "sanjiuma-comparison-019-c",
        text: "笑死，考核甲乙丙丁，反正薪水都一樣少。",
        archetype: "deflect",
        retort: "一樣少，那你更要爭氣一點。",
      },
      {
        id: "sanjiuma-comparison-019-d",
        text: "幹……我考核只有乙等，不上不下……",
        archetype: "meek",
        retort: "乙等？那你要檢討一下自己。",
      },
      {
        id: "sanjiuma-comparison-019-e",
        text: "靠……考核標準我看不懂，隨緣啦……",
        archetype: "meek",
        retort: "隨緣？年輕人要積極一點。",
      },
      {
        id: "sanjiuma-comparison-019-f",
        text: "靠，考核甲等我早就內定好了，別問怎麼做到的。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-019-g",
        text: "他媽的，我考核表寫錯自己的名字。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-comparison-019-h",
        text: "幹，甲等是不是舅舅打的分數，老太婆妳敢對神明發誓？",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-020",
    text: "表哥尾牙抽到出國機票，你抽到什麼？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-020-a",
        text: "靠北，抽到機票是運氣還是舅舅動的手腳，舅媽？",
        archetype: "perfect",
        retort: "你這什麼態度，胡說八道！",
      },
      {
        id: "sanjiuma-comparison-020-b",
        text: "靠，我抽到衛生紙啦，舅媽要不要交換？",
        archetype: "deflect",
        retort: "交換？我才不要你的衛生紙。",
      },
      {
        id: "sanjiuma-comparison-020-c",
        text: "笑死，抽到什麼都好，尾牙重點是吃飯。",
        archetype: "deflect",
        retort: "吃飯重點，那你怎麼不多吃點。",
      },
      {
        id: "sanjiuma-comparison-020-d",
        text: "幹……我什麼都沒抽到，摃龜……",
        archetype: "meek",
        retort: "摃龜？那你人緣是不是不好。",
      },
      {
        id: "sanjiuma-comparison-020-e",
        text: "靠……公司尾牙獎品普通，沒什麼好抽的……",
        archetype: "meek",
        retort: "普通？那公司也太小氣了吧。",
      },
      {
        id: "sanjiuma-comparison-020-f",
        text: "幹，我抽到的獎品其實是我自己準備的。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-comparison-020-g",
        text: "靠北，我抽獎抽到自己送的禮物。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-comparison-020-h",
        text: "幹，抽到機票是不是舅舅內定的，老東西妳說實話？",
        archetype: "landmine",
        retort: "你這什麼態度，欠教訓是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-021",
    text: "表哥社團裡朋友都是老闆，你朋友呢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-021-a",
        text: "他媽的，社團朋友都是老闆，是不是都要應酬陪笑，舅媽？",
        archetype: "perfect",
        retort: "你他媽的講話這麼衝，欠罵是不是！",
      },
      {
        id: "sanjiuma-comparison-021-b",
        text: "靠，我朋友職業普通啦，舅媽要不要來認識？",
        archetype: "deflect",
        retort: "認識？我才沒空理你朋友。",
      },
      {
        id: "sanjiuma-comparison-021-c",
        text: "笑死，朋友是拿來交心的，不是拿來炫耀的。",
        archetype: "deflect",
        retort: "交心？那你倒是交出一個給我看。",
      },
      {
        id: "sanjiuma-comparison-021-d",
        text: "幹……我朋友都普通上班族，沒什麼人脈……",
        archetype: "meek",
        retort: "沒人脈，那你要多社交啊。",
      },
      {
        id: "sanjiuma-comparison-021-e",
        text: "靠……朋友不多，但過年都會來看我……",
        archetype: "meek",
        retort: "過年來看你，那也只是應付吧。",
      },
      {
        id: "sanjiuma-comparison-021-f",
        text: "幹，我朋友其實都是網友，還沒見過面。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-comparison-021-g",
        text: "機掰，我朋友的老闆頭銜是自己封的。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-021-h",
        text: "幹你娘，社團裡都是老闆，是不是舅舅花錢辦的社團，老太婆？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
] satisfies Question[];
