import type { Question } from "@/content/types";

export default [
  {
    id: "sanjiuma-comparison-022",
    text: "表哥換工作被高薪挖角，你有人挖角嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-022-a",
        text: "幹，被挖角是真本事還是舅舅打電話拜託人家收留？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己本事！",
      },
      {
        id: "sanjiuma-comparison-022-b",
        text: "靠，還沒人挖角啦，舅媽要不要幫我介紹獵頭？",
        archetype: "deflect",
        retort: "獵頭？你當我人力銀行喔。",
      },
      {
        id: "sanjiuma-comparison-022-c",
        text: "笑死，沒人挖角也好，穩定就是幸福。",
        archetype: "deflect",
        retort: "穩定是好聽話，你根本沒本事吧。",
      },
      {
        id: "sanjiuma-comparison-022-d",
        text: "幹……我技能普通，沒人要挖角……",
        archetype: "meek",
        retort: "普通就要去進修啊，別擺爛。",
      },
      {
        id: "sanjiuma-comparison-022-e",
        text: "靠……公司太小，獵頭看不上……",
        archetype: "meek",
        retort: "看不上，那你要不要換公司？",
      },
      {
        id: "sanjiuma-comparison-022-f",
        text: "靠，其實有獵頭找過我，我拒絕了啦，很搶手的。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-comparison-022-g",
        text: "他媽的，我把獵頭的訊息當詐騙封鎖了。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-comparison-022-h",
        text: "機掰，挖角是不是舅舅塞紅包拜託的，老東西？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-023",
    text: "表哥員工旅遊去歐洲，你們公司去哪？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-023-a",
        text: "靠北，員工旅遊去歐洲，是公司賺錢還是舅舅贊助的？",
        archetype: "perfect",
        retort: "你這什麼話，胡說八道！",
      },
      {
        id: "sanjiuma-comparison-023-b",
        text: "靠，我們去台灣環島啦，舅媽要不要贊助我去歐洲？",
        archetype: "deflect",
        retort: "贊助？你當我開銀行喔。",
      },
      {
        id: "sanjiuma-comparison-023-c",
        text: "笑死，國內玩得深度一點也不錯啦。",
        archetype: "deflect",
        retort: "深度？深度能拍照打卡嗎。",
      },
      {
        id: "sanjiuma-comparison-023-d",
        text: "幹……我們公司小，員旅只能去附近……",
        archetype: "meek",
        retort: "附近？那你要不要換大公司。",
      },
      {
        id: "sanjiuma-comparison-023-e",
        text: "靠……公司沒錢辦員旅，自己出去玩……",
        archetype: "meek",
        retort: "自己出去玩？那也太可憐了。",
      },
      {
        id: "sanjiuma-comparison-023-f",
        text: "幹，我自己排了歐洲行程，只是還沒出發。",
        archetype: "backfire",
        retort: "……（舅媽轉頭滑手機）",
      },
      {
        id: "sanjiuma-comparison-023-g",
        text: "靠北，我報名員旅結果撞到自己的婚喪假。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-023-h",
        text: "幹你娘，去歐洲是不是舅舅出的錢，老太婆別裝闊。",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-024",
    text: "表哥升職還配了公務車，你通勤靠什麼？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-024-a",
        text: "他媽的，配公務車是升職還是舅舅塞的司機津貼？",
        archetype: "perfect",
        retort: "你這什麼態度！他自己升上去的！",
      },
      {
        id: "sanjiuma-comparison-024-b",
        text: "靠，我騎機車啦，舅媽要不要幫我加油？",
        archetype: "deflect",
        retort: "加油？你當我加油站喔。",
      },
      {
        id: "sanjiuma-comparison-024-c",
        text: "笑死，機車靈活好停車，比開車方便多了。",
        archetype: "deflect",
        retort: "方便是方便，但沒面子啊。",
      },
      {
        id: "sanjiuma-comparison-024-d",
        text: "幹……我連機車保養費都快付不出來……",
        archetype: "meek",
        retort: "保養費都付不起，那你怎麼過日子？",
      },
      {
        id: "sanjiuma-comparison-024-e",
        text: "靠……擠捷運上班，省錢又環保……",
        archetype: "meek",
        retort: "環保是好事，但也太委屈了。",
      },
      {
        id: "sanjiuma-comparison-024-f",
        text: "靠，我通勤靠意志力，比開車環保多了。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-024-g",
        text: "機掰，我機車昨天被拖吊，正在氣頭上。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-comparison-024-h",
        text: "去你的，公務車是不是舅舅公司塞的酬庸，老東西？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-025",
    text: "表哥年終比你一整個月薪水還多，怎麼想？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-025-a",
        text: "幹，年終比我一個月薪水多，那也是舅舅公司灌出來的吧？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己賺的！",
      },
      {
        id: "sanjiuma-comparison-025-b",
        text: "靠北，是有點差距啦，舅媽要不要分我一點？",
        archetype: "deflect",
        retort: "分你？你當我聚寶盆喔。",
      },
      {
        id: "sanjiuma-comparison-025-c",
        text: "笑死，錢夠用就好，比較多也不會比較快樂。",
        archetype: "deflect",
        retort: "不會比較快樂？你講得倒輕鬆。",
      },
      {
        id: "sanjiuma-comparison-025-d",
        text: "幹……我年終沒多少，聽了心很酸……",
        archetype: "meek",
        retort: "心酸就要努力升職啊。",
      },
      {
        id: "sanjiuma-comparison-025-e",
        text: "靠……公司今年虧錢，年終掛零……",
        archetype: "meek",
        retort: "掛零？那你要不要考慮轉職。",
      },
      {
        id: "sanjiuma-comparison-025-f",
        text: "靠，我把年終拿去投資了，現在還在等回本。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-comparison-025-g",
        text: "他媽的，我年終被扣到只剩紅包錢。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-comparison-025-h",
        text: "幹，年終高是不是舅舅公司做假帳灌出來的，老太婆？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-026",
    text: "表哥考到五張證照了，你有幾張？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-026-a",
        text: "靠北，五張證照是他考的還是舅舅買通考場的？",
        archetype: "perfect",
        retort: "你！誰跟你講的！都是他自己考的！",
      },
      {
        id: "sanjiuma-comparison-026-b",
        text: "靠，我在準備一張啦，舅媽有考古題嗎？",
        archetype: "deflect",
        retort: "考古題？你當我補習班喔。",
      },
      {
        id: "sanjiuma-comparison-026-c",
        text: "笑死，證照多不代表能力強，實戰比較重要。",
        archetype: "deflect",
        retort: "實戰重要，那你倒是拿出來啊。",
      },
      {
        id: "sanjiuma-comparison-026-d",
        text: "幹……我一張證照都沒有，慚愧……",
        archetype: "meek",
        retort: "慚愧就要去考啊，別光說不練。",
      },
      {
        id: "sanjiuma-comparison-026-e",
        text: "靠……報名費太貴，一次只能考一張……",
        archetype: "meek",
        retort: "一次一張？那你要考到什麼時候？",
      },
      {
        id: "sanjiuma-comparison-026-f",
        text: "幹，我的證照都收在心裡的資料夾，看不到的。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-026-g",
        text: "靠北，我報名五科結果只考了一科去。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-comparison-026-h",
        text: "幹，五張證照是不是舅舅花錢買的，老太婆妳敢對神明發誓？",
        archetype: "landmine",
        retort: "去你的，沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-027",
    text: "我朋友的小孩考上公職了，你考慮過嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-027-a",
        text: "機掰，考公職是鐵飯碗還是妳想拿來炫耀的獎盃？",
        archetype: "perfect",
        retort: "你這什麼意思！人家很認真考的！",
      },
      {
        id: "sanjiuma-comparison-027-b",
        text: "靠，有考慮啦，舅媽有內線消息嗎？",
        archetype: "deflect",
        retort: "內線？你當我在考古題班喔。",
      },
      {
        id: "sanjiuma-comparison-027-c",
        text: "笑死，公職不是人人適合，我走我的路。",
        archetype: "deflect",
        retort: "走你的路？你的路在哪裡啊。",
      },
      {
        id: "sanjiuma-comparison-027-d",
        text: "幹……我考不上公職，程度不夠……",
        archetype: "meek",
        retort: "程度不夠就要更努力讀書啊。",
      },
      {
        id: "sanjiuma-comparison-027-e",
        text: "靠……補習費太貴，只能自己啃書……",
        archetype: "meek",
        retort: "自己啃書，那你考得上嗎？",
      },
      {
        id: "sanjiuma-comparison-027-f",
        text: "靠，我其實在準備地下考試，比公職還難考。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼廢話」）",
      },
      {
        id: "sanjiuma-comparison-027-g",
        text: "機掰，我報名了公職考試結果忘記帶准考證。",
        archetype: "backfire",
        retort: "……（全場沉默）",
      },
      {
        id: "sanjiuma-comparison-027-h",
        text: "幹，妳朋友的小孩考上公職關我屁事，老東西很閒喔？",
        archetype: "landmine",
        retort: "幹，你是欠罵是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-028",
    text: "表哥辦公室在市中心蛋黃區，你在哪上班？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-028-a",
        text: "幹，蛋黃區辦公室是租的還是舅舅公司的地？",
        archetype: "perfect",
        retort: "你他媽的胡說，公司自己買的！",
      },
      {
        id: "sanjiuma-comparison-028-b",
        text: "靠北，我在郊區上班啦，舅媽要不要幫我介紹市中心工作？",
        archetype: "deflect",
        retort: "介紹？你當我人力銀行喔。",
      },
      {
        id: "sanjiuma-comparison-028-c",
        text: "笑死，郊區辦公室租金便宜，公司比較有賺頭。",
        archetype: "deflect",
        retort: "有賺頭？那你薪水怎麼沒漲。",
      },
      {
        id: "sanjiuma-comparison-028-d",
        text: "幹……我公司在很偏僻的地方，通勤很累……",
        archetype: "meek",
        retort: "很累就要考慮換工作啊。",
      },
      {
        id: "sanjiuma-comparison-028-e",
        text: "靠……在家工作，省下通勤時間……",
        archetype: "meek",
        retort: "省時間？那你根本沒出息。",
      },
      {
        id: "sanjiuma-comparison-028-f",
        text: "幹，我辦公室在雲端，很潮的那種。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-comparison-028-g",
        text: "他媽的，我公司其實在頂樓加蓋。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-028-h",
        text: "幹你娘，蛋黃區辦公室是不是舅舅公司炒地皮賺的，老太婆？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-029",
    text: "表哥同事都叫他經理，同事怎麼叫你？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-029-a",
        text: "靠北，同事叫他經理，是不是舅舅逼他們叫的？",
        archetype: "perfect",
        retort: "你這什麼態度！講話沒大沒小！",
      },
      {
        id: "sanjiuma-comparison-029-b",
        text: "靠，同事都叫我名字啦，舅媽要不要也這樣叫我？",
        archetype: "deflect",
        retort: "叫你名字？我才不要這麼親近。",
      },
      {
        id: "sanjiuma-comparison-029-c",
        text: "笑死，稱呼不重要，做事實在比較重要。",
        archetype: "deflect",
        retort: "實在？那你倒是實在給我看看。",
      },
      {
        id: "sanjiuma-comparison-029-d",
        text: "幹……同事都叫我菜鳥，有點難聽……",
        archetype: "meek",
        retort: "菜鳥？那你要快點升級啊。",
      },
      {
        id: "sanjiuma-comparison-029-e",
        text: "靠……大家都叫我的綽號，有點幼稚……",
        archetype: "meek",
        retort: "幼稚？那你要不要正經一點。",
      },
      {
        id: "sanjiuma-comparison-029-f",
        text: "靠，同事私下都叫我王者，只是不敢當面講。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-comparison-029-g",
        text: "機掰，同事幫我取的綽號其實是在罵我，我後來才知道。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-comparison-029-h",
        text: "去你的，經理是不是舅舅要求同事叫的，老東西別裝闊。",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-030",
    text: "表哥戴的手錶是名牌，你手上這支多少錢？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-030-a",
        text: "他媽的，名牌手錶是他買的還是舅舅送的生日禮物？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己買的！",
      },
      {
        id: "sanjiuma-comparison-030-b",
        text: "靠，我這支普通貨啦，舅媽要不要幫我升級？",
        archetype: "deflect",
        retort: "升級？你當我開錶店喔。",
      },
      {
        id: "sanjiuma-comparison-030-c",
        text: "笑死，看時間而已，貴的便宜的都一樣準。",
        archetype: "deflect",
        retort: "一樣準？那你買貴的幹嘛？",
      },
      {
        id: "sanjiuma-comparison-030-d",
        text: "幹……這支才幾百塊，別問了……",
        archetype: "meek",
        retort: "幾百塊？那你也太寒酸了吧。",
      },
      {
        id: "sanjiuma-comparison-030-e",
        text: "靠……戴電子錶，計步又計心跳，很實用……",
        archetype: "meek",
        retort: "實用？實用能撐場面嗎。",
      },
      {
        id: "sanjiuma-comparison-030-f",
        text: "靠，我這支手錶其實是傳家寶，價值連城。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-comparison-030-g",
        text: "幹，我手錶昨天泡水壞了，正在修。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-comparison-030-h",
        text: "幹，名牌錶是不是舅舅買的生日禮物，老太婆別幫他吹噓。",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-031",
    text: "表哥被挖去外商工作了，你有機會嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-031-a",
        text: "機掰，被挖去外商，是不是舅舅託朋友走的後門？",
        archetype: "perfect",
        retort: "你這什麼意思，講話這麼賤！",
      },
      {
        id: "sanjiuma-comparison-031-b",
        text: "靠北，還沒機會啦，舅媽有認識外商的人嗎？",
        archetype: "deflect",
        retort: "認識？你當我人力銀行喔。",
      },
      {
        id: "sanjiuma-comparison-031-c",
        text: "笑死，外商壓力大，我還是喜歡輕鬆一點。",
        archetype: "deflect",
        retort: "輕鬆？輕鬆能賺大錢嗎。",
      },
      {
        id: "sanjiuma-comparison-031-d",
        text: "幹……我英文不好，外商用不到我……",
        archetype: "meek",
        retort: "英文不好就要去學啊，別放棄。",
      },
      {
        id: "sanjiuma-comparison-031-e",
        text: "靠……履歷投了都沒回音，很挫折……",
        archetype: "meek",
        retort: "挫折就要檢討履歷啊。",
      },
      {
        id: "sanjiuma-comparison-031-f",
        text: "靠，我其實有面試外商，只是我拒絕了他們。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-comparison-031-g",
        text: "他媽的，我投履歷投到自己公司，超尷尬。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-comparison-031-h",
        text: "幹你娘，外商工作是不是舅舅託關係塞的，老東西？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-032",
    text: "表哥車貸都繳完了，你存款有多少？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-032-a",
        text: "幹，車貸繳完是他自己繳的還是舅舅一次付清的？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己繳的！",
      },
      {
        id: "sanjiuma-comparison-032-b",
        text: "靠北，我存款不多啦，舅媽要不要分享理財術？",
        archetype: "deflect",
        retort: "理財術？你自己不會查喔。",
      },
      {
        id: "sanjiuma-comparison-032-c",
        text: "笑死，存款位數不重要，活得開心最重要。",
        archetype: "deflect",
        retort: "開心？開心能繳房貸嗎。",
      },
      {
        id: "sanjiuma-comparison-032-d",
        text: "幹……我存款少得可憐，別再問了……",
        archetype: "meek",
        retort: "少得可憐，那要更努力存啊。",
      },
      {
        id: "sanjiuma-comparison-032-e",
        text: "靠……錢都花在生活費上，存不下來……",
        archetype: "meek",
        retort: "存不下來？那你要學會理財。",
      },
      {
        id: "sanjiuma-comparison-032-f",
        text: "靠，我的錢都投資在自己身上，看不到帳戶餘額而已。",
        archetype: "backfire",
        retort: "……（舅媽覺得莫名其妙）",
      },
      {
        id: "sanjiuma-comparison-032-g",
        text: "機掰，我存摺補摺發現餘額比想像中少很多。",
        archetype: "backfire",
        retort: "……（沒人搭話）",
      },
      {
        id: "sanjiuma-comparison-032-h",
        text: "幹，車貸繳完是不是舅舅一次付清的，老太婆別幫他臭屁。",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-033",
    text: "表哥尾牙代表公司致詞，你敢上台嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-033-a",
        text: "靠北，尾牙致詞是實力還是舅舅安排他上台的？",
        archetype: "perfect",
        retort: "你這什麼話，胡說八道！",
      },
      {
        id: "sanjiuma-comparison-033-b",
        text: "靠，我不敢上台啦，舅媽要不要幫我壯膽？",
        archetype: "deflect",
        retort: "壯膽？我又不是你的心理醫生。",
      },
      {
        id: "sanjiuma-comparison-033-c",
        text: "笑死，上台幹嘛，台下吃飯比較實在。",
        archetype: "deflect",
        retort: "吃飯實在？那你也太沒野心了。",
      },
      {
        id: "sanjiuma-comparison-033-d",
        text: "幹……我很怕上台，會抖到講不出話……",
        archetype: "meek",
        retort: "會抖就要練習啊，怕什麼。",
      },
      {
        id: "sanjiuma-comparison-033-e",
        text: "靠……公司尾牙我都躲在角落……",
        archetype: "meek",
        retort: "躲角落？那你什麼時候要出頭？",
      },
      {
        id: "sanjiuma-comparison-033-f",
        text: "靠，我私下練過致詞，只是還沒機會上台展現。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-comparison-033-g",
        text: "他媽的，我上次上台講到忘詞，全場尷尬。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-comparison-033-h",
        text: "幹，致詞是不是舅舅安排他上台的，老太婆別幫他造神。",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-034",
    text: "表哥機車都換重機了，你騎什麼上班？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-034-a",
        text: "幹，換重機是真愛騎車還是舅舅出錢裝闊？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己存錢買的！",
      },
      {
        id: "sanjiuma-comparison-034-b",
        text: "靠，我騎機車代步啦，舅媽要不要贊助我換車？",
        archetype: "deflect",
        retort: "贊助？你當我開車行喔。",
      },
      {
        id: "sanjiuma-comparison-034-c",
        text: "笑死，機車省油又好停，重機油錢很嚇人的。",
        archetype: "deflect",
        retort: "嚇人？那你根本騎不起吧。",
      },
      {
        id: "sanjiuma-comparison-034-d",
        text: "幹……我機車都快騎壞了，捨不得換……",
        archetype: "meek",
        retort: "捨不得換，那你騎到報廢喔？",
      },
      {
        id: "sanjiuma-comparison-034-e",
        text: "靠……存錢中，還在猶豫要不要換新的……",
        archetype: "meek",
        retort: "猶豫這麼久，你到底要不要換？",
      },
      {
        id: "sanjiuma-comparison-034-f",
        text: "靠，我打算改騎腳踏車，環保又健身，一舉兩得啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-comparison-034-g",
        text: "機掰，我機車昨天騎到一半沒油，超尷尬。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-comparison-034-h",
        text: "幹，重機是不是舅舅出錢買的，老東西別幫他裝闊。",
        archetype: "landmine",
        retort: "你這什麼態度，欠教訓是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-035",
    text: "表哥請了一對一健身教練，你怎麼運動？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-035-a",
        text: "他媽的，請一對一教練，是要練身材還是練舅舅的面子？",
        archetype: "perfect",
        retort: "你他媽的講話這麼衝，欠罵是不是！",
      },
      {
        id: "sanjiuma-comparison-035-b",
        text: "靠，我自己在家練啦，舅媽要不要跟我一起？",
        archetype: "deflect",
        retort: "跟你？我這把年紀還練什麼。",
      },
      {
        id: "sanjiuma-comparison-035-c",
        text: "笑死，自己練省錢，教練費太貴了啦。",
        archetype: "deflect",
        retort: "省錢是省錢，但練得起來嗎。",
      },
      {
        id: "sanjiuma-comparison-035-d",
        text: "幹……我沒錢請教練，只能看影片自學……",
        archetype: "meek",
        retort: "自學？那你有練出什麼成果嗎？",
      },
      {
        id: "sanjiuma-comparison-035-e",
        text: "靠……健身房太貴，只能在家做伏地挺身……",
        archetype: "meek",
        retort: "伏地挺身？那也太陽春了吧。",
      },
      {
        id: "sanjiuma-comparison-035-f",
        text: "靠，我的教練是我自己的意志力，比較省錢。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-comparison-035-g",
        text: "幹，我報名健身房結果去一次就沒去了。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-comparison-035-h",
        text: "幹你娘，請教練是不是舅舅出的錢，老太婆別幫他吹噓。",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-comparison-036",
    text: "表哥連續五年全勤，你有請過假嗎？",
    topic: "comparison",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-comparison-036-a",
        text: "靠北，全勤五年是認真還是舅舅怕他被開除天天盯著？",
        archetype: "perfect",
        retort: "你這什麼態度！講話沒大沒小！",
      },
      {
        id: "sanjiuma-comparison-036-b",
        text: "靠，我請過幾次假啦，舅媽要不要體諒一下上班族？",
        archetype: "deflect",
        retort: "體諒？我上班的時候都全勤。",
      },
      {
        id: "sanjiuma-comparison-036-c",
        text: "笑死，請假是權利，身體健康比全勤重要。",
        archetype: "deflect",
        retort: "身體重要？那你也太會找藉口了。",
      },
      {
        id: "sanjiuma-comparison-036-d",
        text: "幹……我常常請假，身體真的不太好……",
        archetype: "meek",
        retort: "身體不好就要去看醫生啊。",
      },
      {
        id: "sanjiuma-comparison-036-e",
        text: "靠……工作壓力大，偶爾要請假喘口氣……",
        archetype: "meek",
        retort: "喘口氣？年輕人抗壓性太差了。",
      },
      {
        id: "sanjiuma-comparison-036-f",
        text: "靠，我全勤紀錄是被公司搞丟了，其實我也很厲害。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-comparison-036-g",
        text: "機掰，我請假理由寫錯，結果被主管抓包。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-comparison-036-h",
        text: "去你的，全勤五年是不是舅舅威脅他不准請假，老東西？",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
] satisfies Question[];
