import type { Question } from "@/content/types";

// situations:
// 002 問頭期款存了多少
// 003 問要不要買預售屋
// 004 問貸款成數過了沒
// 005 講表哥新家幾房幾廳
// 006 講表哥房貸月付多少
// 007 問要不要搬回家住省房租
// 008 問租屋處會不會漏水
// 009 問有沒有考慮買車位
// 010 問要不要跟爸媽拿頭期款
// 011 問有沒有找房仲估價
// 012 問要不要把股票基金拿去湊頭期
// 013 問想買哪一區房子
// 014 問要幾坪才夠住
// 015 問電梯大樓還是公寓
// 016 問要不要跟朋友合資買房
// 017 問有沒有申請青年安心成家貸款
// 018 問房貸利率現在多少
// 019 問有沒有跟房東談降租
// 020 問要不要跟另一半一起買房
// 021 問老家那間要不要過戶給你

export default [
  {
    id: "sanjiuma-housing-002",
    text: "頭期款存多少了？表哥都存夠買車位了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-002-a",
        text: "存夠了，妳要不要也算算自己的房貸？",
        archetype: "perfect",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-housing-002-b",
        text: "舅媽這麼關心，要不要贊助我頭期款？",
        archetype: "deflect",
        retort: "贊助？你自己要努力存。",
      },
      {
        id: "sanjiuma-housing-002-c",
        text: "表哥頭期款怎麼存的，教教我啊。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-housing-002-d",
        text: "存了一點，但離目標還很遠……",
        archetype: "meek",
        retort: "還差多少？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-002-e",
        text: "存款都拿去繳房租了，存不了……",
        archetype: "meek",
        retort: "存不了？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-housing-002-f",
        text: "頭期款我用信用卡分期付款買緣分。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-002-g",
        text: "頭期款不重要，重要的是家的溫度。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-002-h",
        text: "頭期款，是不是舅舅塞紅包湊的？",
        archetype: "landmine",
        retort: "你說什麼！臉都綠了你知道嗎！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-003",
    text: "要不要買預售屋？表哥都買在蛋黃區。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-003-a",
        text: "蛋黃區，是他挑的，還是妳先訂的？",
        archetype: "perfect",
        retort: "舅媽瞪你一眼，改扒飯。",
      },
      {
        id: "sanjiuma-housing-003-b",
        text: "舅媽這麼懂房市，要不要幫我挑一間？",
        archetype: "deflect",
        retort: "挑房子？你自己要多看看。",
      },
      {
        id: "sanjiuma-housing-003-c",
        text: "表哥買的蛋黃區，要不要順便推薦我？",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-housing-003-d",
        text: "有在看，但預售屋壓力太大……",
        archetype: "meek",
        retort: "壓力多大？貸款多少你說。",
      },
      {
        id: "sanjiuma-housing-003-e",
        text: "看不起蛋黃區，只能看蛋殼區……",
        archetype: "meek",
        retort: "蛋殼區？那你打算住多久？",
      },
      {
        id: "sanjiuma-housing-003-f",
        text: "我打算住在心中那間豪宅。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-housing-003-g",
        text: "預售屋太麻煩，我等奇蹟出現。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-housing-003-h",
        text: "蛋黃區頭期款，是不是舅舅先出的？",
        archetype: "landmine",
        retort: "你嘛卡差不多咧！誰跟你講的！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-004",
    text: "貸款成數過了沒？表哥八成都過了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-004-a",
        text: "八成過件，是他信用好，還是妳去說項？",
        archetype: "perfect",
        retort: "……舅媽愣了一下，說你別亂猜。",
      },
      {
        id: "sanjiuma-housing-004-b",
        text: "舅媽這麼懂貸款，要不要幫我作保？",
        archetype: "deflect",
        retort: "作保？那個風險太大了啦。",
      },
      {
        id: "sanjiuma-housing-004-c",
        text: "表哥八成怎麼談的，教教我啊。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問。",
      },
      {
        id: "sanjiuma-housing-004-d",
        text: "只過六成，還要多存一點……",
        archetype: "meek",
        retort: "六成？差多少你要說清楚。",
      },
      {
        id: "sanjiuma-housing-004-e",
        text: "銀行嫌我信用不夠好……",
        archetype: "meek",
        retort: "信用不好？那你要趕快改善。",
      },
      {
        id: "sanjiuma-housing-004-f",
        text: "貸款成數我打算用星座來算。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-004-g",
        text: "成數不重要，重要的是緣分到了。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-004-h",
        text: "八成貸款，是不是舅舅去銀行喬的？",
        archetype: "landmine",
        retort: "你這孩子怎麼這樣講話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-005",
    text: "表哥新家四房兩廳，你租的幾坪？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-005-a",
        text: "四房兩廳，住的人多，還是妳去的多？",
        archetype: "perfect",
        retort: "舅媽哼一聲，你少在那邊會講。",
      },
      {
        id: "sanjiuma-housing-005-b",
        text: "四房兩廳好棒，改天邀我去參觀嘛。",
        archetype: "deflect",
        retort: "好啊好啊，隨時歡迎你來。",
      },
      {
        id: "sanjiuma-housing-005-c",
        text: "表哥新家風水怎麼樣，要不要一起看？",
        archetype: "deflect",
        retort: "風水喔？改天再說啦。",
      },
      {
        id: "sanjiuma-housing-005-d",
        text: "我租的套房，十來坪而已……",
        archetype: "meek",
        retort: "十來坪？夠住嗎，你老實說。",
      },
      {
        id: "sanjiuma-housing-005-e",
        text: "跟人合租，房間小小的……",
        archetype: "meek",
        retort: "合租？那隱私怎麼辦，說清楚。",
      },
      {
        id: "sanjiuma-housing-005-f",
        text: "坪數不重要，我心中的房子是無限大。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-005-g",
        text: "我把租的套房當成心靈豪宅。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-005-h",
        text: "四房兩廳，頭期款是舅舅出的吧？",
        archetype: "landmine",
        retort: "你這什麼意思！他自己賺的！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-006",
    text: "表哥房貸一個月繳三萬，壓力大喔。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-006-a",
        text: "壓力大，是他扛的，還是妳幫忙分擔？",
        archetype: "perfect",
        retort: "舅媽比個「呵呵」，轉頭夾菜。",
      },
      {
        id: "sanjiuma-housing-006-b",
        text: "三萬好高，表哥薪水真的很不錯耶。",
        archetype: "deflect",
        retort: "當然，他很努力的。",
      },
      {
        id: "sanjiuma-housing-006-c",
        text: "舅媽有沒有幫忙分攤一點房貸？",
        archetype: "deflect",
        retort: "少亂講，都他自己繳的。",
      },
      {
        id: "sanjiuma-housing-006-d",
        text: "我付房租一萬多，比較沒壓力……",
        archetype: "meek",
        retort: "一萬多？那你打算租到什麼時候？",
      },
      {
        id: "sanjiuma-housing-006-e",
        text: "光房租就快吃掉薪水一半了……",
        archetype: "meek",
        retort: "一半？那你怎麼存錢買房？",
      },
      {
        id: "sanjiuma-housing-006-f",
        text: "房貸壓力我用信仰扛過去。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-006-g",
        text: "三萬不算什麼，我心中的房貸更大。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-006-h",
        text: "三萬房貸，是不是妳每月偷偷補的？",
        archetype: "landmine",
        retort: "……（舅媽臉色瞬間僵住，說不出話）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-007",
    text: "要不要搬回家住？省下房租買房啊。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-007-a",
        text: "搬回家？那妳每天要多問我幾次？",
        archetype: "perfect",
        retort: "舅媽嘴硬：我是為你好而已。",
      },
      {
        id: "sanjiuma-housing-007-b",
        text: "舅媽這麼會規劃，要不要幫我算存款計畫？",
        archetype: "deflect",
        retort: "計畫？你自己要有紀律。",
      },
      {
        id: "sanjiuma-housing-007-c",
        text: "表哥當年有沒有搬回去住過？",
        archetype: "deflect",
        retort: "他早就自己買房了，不用。",
      },
      {
        id: "sanjiuma-housing-007-d",
        text: "有考慮，但通勤時間會拉長……",
        archetype: "meek",
        retort: "拉長多久？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-007-e",
        text: "怕搬回去會被念，壓力更大……",
        archetype: "meek",
        retort: "念什麼？那你到底要不要搬？",
      },
      {
        id: "sanjiuma-housing-007-f",
        text: "在外租房是我獨立宣言的一部分。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-007-g",
        text: "省房租不重要，重要的是自由。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-007-h",
        text: "搬回去也不會有人幫我付貸款吧？",
        archetype: "landmine",
        retort: "……（舅媽聲音發抖，說不出話）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-008",
    text: "租的房子會不會漏水？聽說很慘。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-008-a",
        text: "漏水總比妳的碎念好處理。",
        archetype: "perfect",
        retort: "舅媽拿長輩身分壓：沒大沒小。",
      },
      {
        id: "sanjiuma-housing-008-b",
        text: "舅媽這麼關心，要不要介紹好房東給我？",
        archetype: "deflect",
        retort: "介紹？我認識的也不多。",
      },
      {
        id: "sanjiuma-housing-008-c",
        text: "表哥新家有沒有漏水，順便問一下？",
        archetype: "deflect",
        retort: "他新房子怎麼可能漏水。",
      },
      {
        id: "sanjiuma-housing-008-d",
        text: "會啊，下雨天房間都會積水……",
        archetype: "meek",
        retort: "積水？那房東有沒有處理？",
      },
      {
        id: "sanjiuma-housing-008-e",
        text: "有一點漏，但房東說沒空修……",
        archetype: "meek",
        retort: "沒空修？那你住得下去嗎？",
      },
      {
        id: "sanjiuma-housing-008-f",
        text: "漏水是老天爺送我的免費SPA。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-008-g",
        text: "漏水不重要，重要的是租金便宜。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-008-h",
        text: "至少我房東沒有一直逼我買房。",
        archetype: "landmine",
        retort: "去，去叫你媽出來講清楚！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-009",
    text: "有沒有考慮買車位？表哥車位在市中心。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-009-a",
        text: "車位先不急，妳兒子的位子急著保吧。",
        archetype: "perfect",
        retort: "……（舅媽對表哥使眼色求救）",
      },
      {
        id: "sanjiuma-housing-009-b",
        text: "表哥車位那麼好，要不要租給我用？",
        archetype: "deflect",
        retort: "租給你？你自己買車再說。",
      },
      {
        id: "sanjiuma-housing-009-c",
        text: "舅媽這麼懂行情，車位一個多少錢？",
        archetype: "deflect",
        retort: "問我幹嘛，你自己去查啦。",
      },
      {
        id: "sanjiuma-housing-009-d",
        text: "連車都沒有，車位就更不用想了……",
        archetype: "meek",
        retort: "沒車？那你上班怎麼通勤？",
      },
      {
        id: "sanjiuma-housing-009-e",
        text: "有想過，但車位比套房還貴……",
        archetype: "meek",
        retort: "貴多少？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-009-f",
        text: "我的車位在心裡，永遠不用繳管理費。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-009-g",
        text: "車位不重要，重要的是騎車的自由。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-009-h",
        text: "市中心車位，是不是舅舅買的？",
        archetype: "landmine",
        retort: "你這什麼態度，明年別來了！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-010",
    text: "要不要跟爸媽拿頭期款？表哥就有拿。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-010-a",
        text: "自己存比較踏實，不用看誰臉色。",
        archetype: "perfect",
        retort: "舅媽笑僵在臉上，說改天再聊。",
      },
      {
        id: "sanjiuma-housing-010-b",
        text: "舅媽這麼想幫忙，要不要先贊助我？",
        archetype: "deflect",
        retort: "贊助？你自己要努力存。",
      },
      {
        id: "sanjiuma-housing-010-c",
        text: "表哥拿多少，我拿來當參考標準。",
        archetype: "deflect",
        retort: "問表哥幹嘛，問你自己的。",
      },
      {
        id: "sanjiuma-housing-010-d",
        text: "有想過開口，但不好意思拿……",
        archetype: "meek",
        retort: "不好意思？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-housing-010-e",
        text: "爸媽也沒多少錢可以給我……",
        archetype: "meek",
        retort: "沒多少？那到底有多少你說。",
      },
      {
        id: "sanjiuma-housing-010-f",
        text: "頭期款我打算用愛與勇氣支付。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-010-g",
        text: "靠自己比較浪漫，我拒絕世俗幫助。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-010-h",
        text: "他的頭期款，舅舅出了大半吧？",
        archetype: "landmine",
        retort: "……（舅媽翻舊帳：你小時候……）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-011",
    text: "有沒有找房仲估過價？表哥都在看了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-011-a",
        text: "估過價，妳兒子那區是內線消息嗎？",
        archetype: "perfect",
        retort: "舅媽突然說：菜要涼了，快吃。",
      },
      {
        id: "sanjiuma-housing-011-b",
        text: "舅媽這麼懂行情，要不要當我的房仲？",
        archetype: "deflect",
        retort: "當房仲？我沒那個本事。",
      },
      {
        id: "sanjiuma-housing-011-c",
        text: "表哥都在看哪一區，跟我說一下嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問。",
      },
      {
        id: "sanjiuma-housing-011-d",
        text: "有估過，但價格高到嚇死人……",
        archetype: "meek",
        retort: "多高？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-011-e",
        text: "還沒開始看，光想就頭痛……",
        archetype: "meek",
        retort: "頭痛？那你到底想不想買？",
      },
      {
        id: "sanjiuma-housing-011-f",
        text: "估價師被我的氣場嚇到不敢報價。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-011-g",
        text: "價格不重要，重要的是命中注定那間。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-011-h",
        text: "他看的那區，是不是有內線消息？",
        archetype: "landmine",
        retort: "你！他才沒有！你亂講什麼！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-012",
    text: "要不要把股票基金拿去湊頭期款？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-012-a",
        text: "股票留著，比拿去討好誰划算。",
        archetype: "perfect",
        retort: "……（舅媽把問題丟給隔壁阿姨）",
      },
      {
        id: "sanjiuma-housing-012-b",
        text: "舅媽有基金推薦嗎？順便幫我理財一下。",
        archetype: "deflect",
        retort: "理財？你自己學會存錢再說。",
      },
      {
        id: "sanjiuma-housing-012-c",
        text: "表哥的股票拿去湊頭期了嗎？問一下。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問。",
      },
      {
        id: "sanjiuma-housing-012-d",
        text: "我沒什麼股票，也沒什麼基金……",
        archetype: "meek",
        retort: "沒有？那你錢都花去哪了？",
      },
      {
        id: "sanjiuma-housing-012-e",
        text: "有一點點基金，套牢中不敢動……",
        archetype: "meek",
        retort: "套牢？那你打算等到什麼時候？",
      },
      {
        id: "sanjiuma-housing-012-f",
        text: "我的資產配置是快樂與自由。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-012-g",
        text: "頭期款不重要，重要的是心靈自由。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-012-h",
        text: "反正不是靠舅舅塞股票湊的。",
        archetype: "landmine",
        retort: "……（舅媽手一抖，湯匙掉了）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-013",
    text: "你想買哪一區？表哥買的是精華地段。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-013-a",
        text: "妳問這個，是想比較還是想炫耀？",
        archetype: "perfect",
        retort: "舅媽小聲碎念，你這什麼態度。",
      },
      {
        id: "sanjiuma-housing-013-b",
        text: "表哥精華地段怎麼挑的，教教我嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問。",
      },
      {
        id: "sanjiuma-housing-013-c",
        text: "舅媽這麼懂地段，要不要陪我去看房？",
        archetype: "deflect",
        retort: "看房？改天再約時間啦。",
      },
      {
        id: "sanjiuma-housing-013-d",
        text: "還沒想清楚，便宜的地方都很遠……",
        archetype: "meek",
        retort: "多遠？通勤要多久你說清楚。",
      },
      {
        id: "sanjiuma-housing-013-e",
        text: "看得起的區都在很邊緣的地方……",
        archetype: "meek",
        retort: "邊緣？那生活方便嗎，你說。",
      },
      {
        id: "sanjiuma-housing-013-f",
        text: "我想買的區在我夢裡，很方便。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-013-g",
        text: "地段不重要，重要的是有沒有Wifi。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-013-h",
        text: "精華地段，是不是舅舅先打聽好的？",
        archetype: "landmine",
        retort: "你這什麼意思！我這是關心你！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-014",
    text: "你要幾坪才夠住？表哥新家四十坪。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-014-a",
        text: "四十坪打掃起來，妳幫他打掃嗎？",
        archetype: "perfect",
        retort: "……（舅媽清清喉嚨，換話題）",
      },
      {
        id: "sanjiuma-housing-014-b",
        text: "四十坪好大，改天邀我去玩躲貓貓。",
        archetype: "deflect",
        retort: "好啊好啊，隨時歡迎你來。",
      },
      {
        id: "sanjiuma-housing-014-c",
        text: "舅媽覺得幾坪剛好，給我一點建議？",
        archetype: "deflect",
        retort: "這個要看預算，你自己算。",
      },
      {
        id: "sanjiuma-housing-014-d",
        text: "十坪左右就好，反正東西也不多……",
        archetype: "meek",
        retort: "十坪？那以後成家怎麼辦？",
      },
      {
        id: "sanjiuma-housing-014-e",
        text: "能負擔的坪數都很小，將就一下……",
        archetype: "meek",
        retort: "將就？那你要住到什麼時候？",
      },
      {
        id: "sanjiuma-housing-014-f",
        text: "坪數不重要，重要的是心的大小。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-014-g",
        text: "我要住的坪數，跟我的夢想一樣大。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-014-h",
        text: "四十坪，頭期款是舅舅出的吧？",
        archetype: "landmine",
        retort: "夠了，你這什麼態度啊你！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-015",
    text: "要買電梯大樓還是公寓？表哥住電梯的。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-015-a",
        text: "電梯大樓，還是舅舅幫忙按的鍵？",
        archetype: "perfect",
        retort: "舅媽翻白眼，隨便你怎麼想。",
      },
      {
        id: "sanjiuma-housing-015-b",
        text: "電梯大樓好方便，改天去表哥家蹭電梯。",
        archetype: "deflect",
        retort: "蹭電梯？你別鬧了啦。",
      },
      {
        id: "sanjiuma-housing-015-c",
        text: "舅媽覺得哪個好，給我一點意見？",
        archetype: "deflect",
        retort: "當然電梯好啊，你考慮一下。",
      },
      {
        id: "sanjiuma-housing-015-d",
        text: "只能買公寓，電梯大樓太貴……",
        archetype: "meek",
        retort: "太貴？貴多少你要說清楚。",
      },
      {
        id: "sanjiuma-housing-015-e",
        text: "還在猶豫，怕爬樓梯以後會後悔……",
        archetype: "meek",
        retort: "會後悔？那你到底要不要買？",
      },
      {
        id: "sanjiuma-housing-015-f",
        text: "電梯或樓梯不重要，重要的是心態年輕。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-015-g",
        text: "我選擇住在雲端，比電梯還高。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-015-h",
        text: "電梯大樓，頭期款是舅舅出的吧？",
        archetype: "landmine",
        retort: "……（舅媽氣到說起台語罵人）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-016",
    text: "要不要跟朋友合資買房？聽說能省很多。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-016-a",
        text: "合資買房，總比合資養妳的碎念好。",
        archetype: "perfect",
        retort: "……（舅媽把手機螢幕轉暗）",
      },
      {
        id: "sanjiuma-housing-016-b",
        text: "舅媽這麼懂投資，要不要當我的合夥人？",
        archetype: "deflect",
        retort: "合夥人？我沒那個資本。",
      },
      {
        id: "sanjiuma-housing-016-c",
        text: "表哥有沒有考慮合資，我拿來參考一下。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問。",
      },
      {
        id: "sanjiuma-housing-016-d",
        text: "有考慮，但怕以後撕破臉很麻煩……",
        archetype: "meek",
        retort: "撕破臉？那你想清楚了沒？",
      },
      {
        id: "sanjiuma-housing-016-e",
        text: "朋友也沒什麼錢，合資也難……",
        archetype: "meek",
        retort: "難在哪？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-016-f",
        text: "友情跟房產一起買，划算又浪漫。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-016-g",
        text: "合資不重要，重要的是有伴一起苦。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-016-h",
        text: "反正不是每個人都有舅舅可以靠。",
        archetype: "landmine",
        retort: "你這孩子，白養你這麼多年！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-017",
    text: "有沒有申請青年安心成家貸款？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-017-a",
        text: "申請補助，是我自己填的，不勞妳費心。",
        archetype: "perfect",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-housing-017-b",
        text: "舅媽這麼懂補助，要不要幫我填申請表？",
        archetype: "deflect",
        retort: "填表？你自己要學著來。",
      },
      {
        id: "sanjiuma-housing-017-c",
        text: "表哥有申請過嗎，跟我分享一下嘛。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去查。",
      },
      {
        id: "sanjiuma-housing-017-d",
        text: "有申請，但額度沒有想像中多……",
        archetype: "meek",
        retort: "多少？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-017-e",
        text: "資格卡在薪水門檻，過不了……",
        archetype: "meek",
        retort: "過不了？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-housing-017-f",
        text: "貸款不重要，重要的是成家的緣分。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-017-g",
        text: "我申請的是宇宙給我的成家補助。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-017-h",
        text: "這種補助，靠關係的人才不稀罕吧？",
        archetype: "landmine",
        retort: "……（舅媽瞪著你，眼眶紅了）",
      },
    ],
  },
  {
    id: "sanjiuma-housing-018",
    text: "現在房貸利率多少？你知道嗎？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-018-a",
        text: "利率我知道，妳問這個是想放款嗎？",
        archetype: "perfect",
        retort: "……（舅媽轉頭找別桌講話）",
      },
      {
        id: "sanjiuma-housing-018-b",
        text: "舅媽這麼專業，要不要幫我談利率？",
        archetype: "deflect",
        retort: "談利率？我哪有那個本事。",
      },
      {
        id: "sanjiuma-housing-018-c",
        text: "表哥貸款利率多少，我拿來比較一下。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去查。",
      },
      {
        id: "sanjiuma-housing-018-d",
        text: "不太清楚耶，還沒真的去查過……",
        archetype: "meek",
        retort: "沒查過？那你要怎麼買房？",
      },
      {
        id: "sanjiuma-housing-018-e",
        text: "查過但看不太懂，覺得好複雜……",
        archetype: "meek",
        retort: "看不懂？那你要找人問清楚。",
      },
      {
        id: "sanjiuma-housing-018-f",
        text: "利率不重要，重要的是緣分利率。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-018-g",
        text: "我對數字過敏，只信任感覺。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-018-h",
        text: "妳那間早繳完了，還好意思問利率？",
        archetype: "landmine",
        retort: "你信不信我現在就打電話問他！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-019",
    text: "有沒有跟房東談降租？表哥都不用煩這個。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-019-a",
        text: "談降租是我的本事，妳兒子不用學。",
        archetype: "perfect",
        retort: "……舅媽臉一僵，說你亂講。",
      },
      {
        id: "sanjiuma-housing-019-b",
        text: "舅媽這麼會談判，要不要幫我談降租？",
        archetype: "deflect",
        retort: "談判？我可沒那個本事。",
      },
      {
        id: "sanjiuma-housing-019-c",
        text: "表哥都不用煩房租，真好命耶。",
        archetype: "deflect",
        retort: "他當然好命，房子是自己的。",
      },
      {
        id: "sanjiuma-housing-019-d",
        text: "談過，但房東不肯降……",
        archetype: "meek",
        retort: "不肯降？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-housing-019-e",
        text: "不敢談，怕房東直接不租了……",
        archetype: "meek",
        retort: "不敢？那你要租到什麼時候？",
      },
      {
        id: "sanjiuma-housing-019-f",
        text: "我用真誠打動房東，降租靠緣分。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-019-g",
        text: "房租不重要，重要的是房東人好不好。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-019-h",
        text: "至少我房租沒讓舅舅補貼過。",
        archetype: "landmine",
        retort: "你這什麼態度！我這是關心他！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-020",
    text: "要不要跟對象一起買房？表哥結婚就買了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-020-a",
        text: "先自己存，總比婚後才發現對方沒錢好。",
        archetype: "perfect",
        retort: "……（舅媽沒接話，喝茶壓驚）",
      },
      {
        id: "sanjiuma-housing-020-b",
        text: "舅媽這麼會規劃，要不要先幫我介紹對象？",
        archetype: "deflect",
        retort: "介紹？你先把自己顧好。",
      },
      {
        id: "sanjiuma-housing-020-c",
        text: "表哥結婚買房，是不是舅舅幫忙的？",
        archetype: "deflect",
        retort: "少亂講，那是他自己努力的。",
      },
      {
        id: "sanjiuma-housing-020-d",
        text: "還沒有對象，也不敢想這麼遠……",
        archetype: "meek",
        retort: "沒對象？那你要單身多久？",
      },
      {
        id: "sanjiuma-housing-020-e",
        text: "有對象但還沒存夠，先觀望……",
        archetype: "meek",
        retort: "觀望多久？你要說清楚一點。",
      },
      {
        id: "sanjiuma-housing-020-f",
        text: "我打算跟緣分一起買房，比較浪漫。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-housing-020-g",
        text: "買房不重要，重要的是先買到愛情。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-housing-020-h",
        text: "他結婚買房，頭期款不是舅舅出的？",
        archetype: "landmine",
        retort: "你這什麼意思！臉都變了！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-021",
    text: "老家那間要不要過戶給你？考慮一下。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-021-a",
        text: "過戶名單，還不是妳說了算？",
        archetype: "perfect",
        retort: "舅媽乾笑兩聲，改扒飯。",
      },
      {
        id: "sanjiuma-housing-021-b",
        text: "舅媽這麼慷慨，要不要順便過戶給我一間？",
        archetype: "deflect",
        retort: "想得美，你自己去努力。",
      },
      {
        id: "sanjiuma-housing-021-c",
        text: "表哥有沒有分到，我拿來比較一下。",
        archetype: "deflect",
        retort: "問表哥幹嘛，問你自己的。",
      },
      {
        id: "sanjiuma-housing-021-d",
        text: "還沒討論過，怕家人為這個吵架……",
        archetype: "meek",
        retort: "吵架？那你要不要先開口問？",
      },
      {
        id: "sanjiuma-housing-021-e",
        text: "應該輪不到我，還有哥哥姊姊……",
        archetype: "meek",
        retort: "輪不到？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-housing-021-f",
        text: "老家對我來說是回憶，不是資產。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-housing-021-g",
        text: "過戶不重要，重要的是家人感情。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-housing-021-h",
        text: "過戶名單，是不是妳早就內定好了？",
        archetype: "landmine",
        retort: "……（舅媽臉色一沉，沒再說話）",
      },
    ],
  },
] satisfies Question[];
