import type { Question } from "@/content/types";

export default [
  {
    id: "sanjiuma-housing-002",
    text: "頭期款存多少了？表哥都存夠買車位了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-002-a",
        text: "幹，車位比人金貴，表哥是要跟車位結婚喔？",
        archetype: "perfect",
        retort: "你他媽的說什麼！表哥他很努力好嗎！",
      },
      {
        id: "sanjiuma-housing-002-b",
        text: "靠，舅媽這麼關心，先借我頭期款啊。",
        archetype: "deflect",
        retort: "借你？我哪來的閒錢啦。",
      },
      {
        id: "sanjiuma-housing-002-c",
        text: "還在存啦，笑死，存錢又不是比賽。",
        archetype: "deflect",
        retort: "比賽？你是輸定了啦。",
      },
      {
        id: "sanjiuma-housing-002-d",
        text: "幹……才存十幾萬，還早啦……",
        archetype: "meek",
        retort: "十幾萬？那要存到民國幾年？",
      },
      {
        id: "sanjiuma-housing-002-e",
        text: "靠……薪水都拿去繳房租了……",
        archetype: "meek",
        retort: "房租繳一繳，錢就沒了齁。",
      },
      {
        id: "sanjiuma-housing-002-f",
        text: "幹，我存的是回憶，不是頭期款啦。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-housing-002-g",
        text: "他媽的，我在等中樂透啦。",
        archetype: "backfire",
        retort: "……（沒人笑，全場安靜）",
      },
      {
        id: "sanjiuma-housing-002-h",
        text: "幹，老東西，車位比我重要是不是？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-003",
    text: "要不要買預售屋？表哥都買在蛋黃區。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-003-a",
        text: "蛋黃區喔？機掰，房價比我薪水高多了。",
        archetype: "perfect",
        retort: "你這什麼態度，講話這麼難聽！",
      },
      {
        id: "sanjiuma-housing-003-b",
        text: "靠北，舅媽要不要順便介紹代銷？",
        archetype: "deflect",
        retort: "介紹？你出得起錢再說啦。",
      },
      {
        id: "sanjiuma-housing-003-c",
        text: "還在看啦，笑死，看得到買不到。",
        archetype: "deflect",
        retort: "看得到買不到，是啊，加油。",
      },
      {
        id: "sanjiuma-housing-003-d",
        text: "幹……預售屋太貴，買不起啦……",
        archetype: "meek",
        retort: "買不起就要更努力賺啊。",
      },
      {
        id: "sanjiuma-housing-003-e",
        text: "靠……我連蛋殼區都買不起……",
        archetype: "meek",
        retort: "蛋殼區？那你要住哪裡？",
      },
      {
        id: "sanjiuma-housing-003-f",
        text: "靠，我要買的是精神時光屋啦。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨講話）",
      },
      {
        id: "sanjiuma-housing-003-g",
        text: "他媽的，我要買氣球屋啦。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-003-h",
        text: "幹你娘，蛋黃區是妳生的還妳買的，老太婆？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-004",
    text: "貸款成數過了沒？表哥八成都過了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-004-a",
        text: "他媽的，貸款過八成，是他信用好還是舅舅保的？",
        archetype: "perfect",
        retort: "你他媽的說什麼！他自己申請的！",
      },
      {
        id: "sanjiuma-housing-004-b",
        text: "靠，舅媽這麼關心，要不要當我保證人？",
        archetype: "deflect",
        retort: "保證人？你當我提款機喔。",
      },
      {
        id: "sanjiuma-housing-004-c",
        text: "還沒送件啦，笑死，急什麼。",
        archetype: "deflect",
        retort: "不急？你是要租一輩子嗎。",
      },
      {
        id: "sanjiuma-housing-004-d",
        text: "幹……信用沒那麼好，過不了啦……",
        archetype: "meek",
        retort: "過不了就要想辦法補啊。",
      },
      {
        id: "sanjiuma-housing-004-e",
        text: "靠……銀行嫌我薪水太低……",
        archetype: "meek",
        retort: "薪水低，那要怪誰？",
      },
      {
        id: "sanjiuma-housing-004-f",
        text: "幹，我信用好到銀行都想倒追我啦。",
        archetype: "backfire",
        retort: "……（舅媽笑而不語）",
      },
      {
        id: "sanjiuma-housing-004-g",
        text: "機掰，我信用卡都快被停了啦。",
        archetype: "backfire",
        retort: "……（全桌沉默）",
      },
      {
        id: "sanjiuma-housing-004-h",
        text: "機掰，八成是舅舅打電話關說的吧，老東西？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-005",
    text: "表哥新家四房兩廳，你租的幾坪？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-005-a",
        text: "幹，四房兩廳空著三間，是要養蚊子喔？",
        archetype: "perfect",
        retort: "你他媽的什麼意思，是在說表哥嗎！",
      },
      {
        id: "sanjiuma-housing-005-b",
        text: "靠北，我租的雖小但溫馨，舅媽要不要來坐？",
        archetype: "deflect",
        retort: "坐？我才不要擠那種小房間。",
      },
      {
        id: "sanjiuma-housing-005-c",
        text: "夠住啦，笑死，一個人要那麼大幹嘛。",
        archetype: "deflect",
        retort: "一個人才要住大一點才氣派。",
      },
      {
        id: "sanjiuma-housing-005-d",
        text: "幹……大概六坪，套房而已啦……",
        archetype: "meek",
        retort: "六坪？那是倉庫還是房間？",
      },
      {
        id: "sanjiuma-housing-005-e",
        text: "靠……住小小的，夠睡就好……",
        archetype: "meek",
        retort: "夠睡就好？年輕人要有志氣。",
      },
      {
        id: "sanjiuma-housing-005-f",
        text: "靠，小空間比較有安全感，這是心理學啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-housing-005-g",
        text: "他媽的，坪數不重要，坪效才重要啦。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-housing-005-h",
        text: "幹，四房兩廳空著給灰塵住，老太婆划算嗎？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-006",
    text: "表哥房貸一個月繳三萬，壓力大喔。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-006-a",
        text: "靠北，三萬房貸換來的失眠，值得嗎舅媽？",
        archetype: "perfect",
        retort: "你這孩子嘴巴怎麼這麼賤！",
      },
      {
        id: "sanjiuma-housing-006-b",
        text: "靠，舅媽妳兒子這麼拚，要不要多包他一點？",
        archetype: "deflect",
        retort: "包他？我自己都不夠用了。",
      },
      {
        id: "sanjiuma-housing-006-c",
        text: "他繳得起是他本事，笑死，我沒差。",
        archetype: "deflect",
        retort: "沒差是沒差，但你也該努力。",
      },
      {
        id: "sanjiuma-housing-006-d",
        text: "幹……我連房租一萬都吃緊了……",
        archetype: "meek",
        retort: "一萬都吃緊，那你薪水多少？",
      },
      {
        id: "sanjiuma-housing-006-e",
        text: "靠……三萬對我來說是天文數字……",
        archetype: "meek",
        retort: "天文數字？那你要加油了。",
      },
      {
        id: "sanjiuma-housing-006-f",
        text: "靠，三萬對我來說根本零用錢零頭啦。",
        archetype: "backfire",
        retort: "……（舅媽白眼翻到後腦勺）",
      },
      {
        id: "sanjiuma-housing-006-g",
        text: "機掰，我房租都靠信用卡繳的啦。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-006-h",
        text: "去死啦，壓力大就別炫耀啊，老東西是不是欠罵？",
        archetype: "landmine",
        retort: "去你的，沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-007",
    text: "要不要搬回家住？省下房租買房啊。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-007-a",
        text: "幹，搬回去是要跟妳一起盤點表哥薪水嗎？",
        archetype: "perfect",
        retort: "你講這什麼話，沒大沒小！",
      },
      {
        id: "sanjiuma-housing-007-b",
        text: "靠北，搬回去也行啊，舅媽妳先幫我打掃。",
        archetype: "deflect",
        retort: "打掃？你當我是誰啊。",
      },
      {
        id: "sanjiuma-housing-007-c",
        text: "我自己住習慣了啦，笑死，不用擔心。",
        archetype: "deflect",
        retort: "不擔心？我看你就是不聽勸。",
      },
      {
        id: "sanjiuma-housing-007-d",
        text: "幹……搬回去會被念到死，不要啦……",
        archetype: "meek",
        retort: "念你是為你好，你不懂喔。",
      },
      {
        id: "sanjiuma-housing-007-e",
        text: "靠……在外面住比較自由啦……",
        archetype: "meek",
        retort: "自由？自由能當飯吃嗎？",
      },
      {
        id: "sanjiuma-housing-007-f",
        text: "幹，我在外面修行，搬回去會破功啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉莫名其妙）",
      },
      {
        id: "sanjiuma-housing-007-g",
        text: "他媽的，我怕吵到你們作息啦。",
        archetype: "backfire",
        retort: "……（沒人相信）",
      },
      {
        id: "sanjiuma-housing-007-h",
        text: "幹你娘，妳是想我搬回去查勤嗎，老太婆？",
        archetype: "landmine",
        retort: "幹，你是欠罵是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-008",
    text: "租的房子會不會漏水？聽說很慘。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-008-a",
        text: "他媽的，漏水總比漏財好吧，舅媽妳說是不是？",
        archetype: "perfect",
        retort: "你他媽的什麼意思，是在說表哥嗎！",
      },
      {
        id: "sanjiuma-housing-008-b",
        text: "靠，是有一點啦，舅媽要不要幫我出修繕費？",
        archetype: "deflect",
        retort: "修繕費？你當我開銀行喔。",
      },
      {
        id: "sanjiuma-housing-008-c",
        text: "還好啦，笑死，下雨天正好免費洗地。",
        archetype: "deflect",
        retort: "這麼樂觀，是自我安慰吧。",
      },
      {
        id: "sanjiuma-housing-008-d",
        text: "幹……天花板真的有漏，房東不理我……",
        archetype: "meek",
        retort: "不理你就要去申訴啊。",
      },
      {
        id: "sanjiuma-housing-008-e",
        text: "靠……漏得我書都濕了，很崩潰……",
        archetype: "meek",
        retort: "崩潰有用嗎？趕快搬家啊。",
      },
      {
        id: "sanjiuma-housing-008-f",
        text: "靠北，漏水讓我體驗了大自然的瀑布秀。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有問題）",
      },
      {
        id: "sanjiuma-housing-008-g",
        text: "機掰，我把漏水的地方拿去養魚啦。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-housing-008-h",
        text: "幹，妳這房子三十年前買的，妳才該檢查漏水吧，老東西？",
        archetype: "landmine",
        retort: "閉嘴啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-009",
    text: "有沒有考慮買車位？表哥車位在市中心。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-009-a",
        text: "幹，車位在市中心，是要拿來拜的嗎？",
        archetype: "perfect",
        retort: "拜什麼拜，你講話越來越難聽！",
      },
      {
        id: "sanjiuma-housing-009-b",
        text: "靠北，車位是要停車不是拿來比較的吧？",
        archetype: "deflect",
        retort: "比較一下會怎樣，你這麼敏感。",
      },
      {
        id: "sanjiuma-housing-009-c",
        text: "還沒有車啦，笑死，先讓我買車再說。",
        archetype: "deflect",
        retort: "先買車？那你猴年馬月才買房。",
      },
      {
        id: "sanjiuma-housing-009-d",
        text: "幹……車位比我房租還貴，哪買得起……",
        archetype: "meek",
        retort: "買不起就要想辦法存啊。",
      },
      {
        id: "sanjiuma-housing-009-e",
        text: "靠……我連機車格都搶不到……",
        archetype: "meek",
        retort: "機車格搶不到？那你怎麼停車？",
      },
      {
        id: "sanjiuma-housing-009-f",
        text: "靠，我的車位在我心裡，隨時能停啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在講幹話）",
      },
      {
        id: "sanjiuma-housing-009-g",
        text: "他媽的，我用共享機車啦，很潮的。",
        archetype: "backfire",
        retort: "……（沒人覺得潮）",
      },
      {
        id: "sanjiuma-housing-009-h",
        text: "幹，車位錢是不是舅舅出的，老太婆敢認？",
        archetype: "landmine",
        retort: "你他媽很敢問，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-010",
    text: "要不要跟爸媽拿頭期款？表哥就有拿。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-010-a",
        text: "靠北，表哥拿的是舅舅公司的錢吧，不是頭期款？",
        archetype: "perfect",
        retort: "你！誰跟你講的！他自己存的！",
      },
      {
        id: "sanjiuma-housing-010-b",
        text: "靠，舅媽要不要也贊助我一點，公平一點？",
        archetype: "deflect",
        retort: "贊助你？我自己都要存了。",
      },
      {
        id: "sanjiuma-housing-010-c",
        text: "自己來啦，笑死，靠爸族不是我的路線。",
        archetype: "deflect",
        retort: "路線？你這樣講太酸了吧。",
      },
      {
        id: "sanjiuma-housing-010-d",
        text: "幹……爸媽也沒多少錢，不好意思開口……",
        archetype: "meek",
        retort: "不開口，那你要買到什麼時候？",
      },
      {
        id: "sanjiuma-housing-010-e",
        text: "靠……我自己存比較心安啦……",
        archetype: "meek",
        retort: "心安能當頭期款用嗎？",
      },
      {
        id: "sanjiuma-housing-010-f",
        text: "幹，我打算跟銀行借啦，銀行也是我家人。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在講什麼」）",
      },
      {
        id: "sanjiuma-housing-010-g",
        text: "機掰，我在存零錢筒，快滿了啦。",
        archetype: "backfire",
        retort: "……（全桌沉默）",
      },
      {
        id: "sanjiuma-housing-010-h",
        text: "機掰，表哥靠爸買房還敢說努力，老東西妳臉不紅？",
        archetype: "landmine",
        retort: "你他媽的血口噴人，給我道歉！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-011",
    text: "有沒有找房仲估過價？表哥都在看了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-011-a",
        text: "他媽的，估價前先估一下表哥的良心值多少？",
        archetype: "perfect",
        retort: "你這什麼話！他心地多好你不知道！",
      },
      {
        id: "sanjiuma-housing-011-b",
        text: "靠，有啊，舅媽要不要幫我介紹便宜一點的？",
        archetype: "deflect",
        retort: "便宜？現在哪有便宜房子啦。",
      },
      {
        id: "sanjiuma-housing-011-c",
        text: "還在看啦，笑死，看房也是一種紓壓。",
        archetype: "deflect",
        retort: "紓壓？看得到買不到才是壓力吧。",
      },
      {
        id: "sanjiuma-housing-011-d",
        text: "幹……估完價我更絕望了……",
        archetype: "meek",
        retort: "絕望就要更努力賺錢啊。",
      },
      {
        id: "sanjiuma-housing-011-e",
        text: "靠……房價高到我想哭……",
        archetype: "meek",
        retort: "哭有用嗎？擦乾眼淚繼續存。",
      },
      {
        id: "sanjiuma-housing-011-f",
        text: "靠北，估價師說我氣場值千萬啦。",
        archetype: "backfire",
        retort: "……（舅媽翻白眼）",
      },
      {
        id: "sanjiuma-housing-011-g",
        text: "幹，估完我直接把估價單燒了洩憤。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-011-h",
        text: "幹你娘，估完才知道妳那間根本沒漲，老太婆別臭屁。",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-012",
    text: "要不要把股票基金拿去湊頭期款？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-012-a",
        text: "靠北，把股票變房子，跟妳把表哥變神一樣難吧？",
        archetype: "perfect",
        retort: "你這什麼比喻，講話不得體！",
      },
      {
        id: "sanjiuma-housing-012-b",
        text: "靠，舅媽有明牌的話先跟我說啦。",
        archetype: "deflect",
        retort: "明牌？你是要害死我嗎。",
      },
      {
        id: "sanjiuma-housing-012-c",
        text: "先放著長期投資啦，笑死，急什麼。",
        archetype: "deflect",
        retort: "不急？你都幾歲了還租房。",
      },
      {
        id: "sanjiuma-housing-012-d",
        text: "幹……那點股票賣了也湊不到零頭……",
        archetype: "meek",
        retort: "湊不到，那你要怎麼買房？",
      },
      {
        id: "sanjiuma-housing-012-e",
        text: "靠……基金套牢中，不敢動……",
        archetype: "meek",
        retort: "套牢就要認賠啊，猶豫什麼。",
      },
      {
        id: "sanjiuma-housing-012-f",
        text: "靠，我的股票是拿來傳家的，不是拿來花的。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-housing-012-g",
        text: "他媽的，我全部押迷因幣啦。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-012-h",
        text: "幹，妳那三十年前的房子連基金報酬率都輸，老東西。",
        archetype: "landmine",
        retort: "你這什麼態度，欠教訓是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-013",
    text: "你想買哪一區？表哥買的是精華地段。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-013-a",
        text: "機掰，精華地段是精華，房貸也很精華，三十年都繳不完。",
        archetype: "perfect",
        retort: "你這孩子講話越來越沒大沒小！",
      },
      {
        id: "sanjiuma-housing-013-b",
        text: "靠北，哪一區都好，舅媽有內線消息嗎？",
        archetype: "deflect",
        retort: "內線？你當我是投顧老師喔。",
      },
      {
        id: "sanjiuma-housing-013-c",
        text: "隨便啦，笑死，能住就好，不挑。",
        archetype: "deflect",
        retort: "不挑？年輕人要有目標啦。",
      },
      {
        id: "sanjiuma-housing-013-d",
        text: "幹……哪一區都買不起，隨便問問而已……",
        archetype: "meek",
        retort: "隨便問問？你根本沒在規劃吧。",
      },
      {
        id: "sanjiuma-housing-013-e",
        text: "靠……離公司近一點就好，不敢奢求……",
        archetype: "meek",
        retort: "不敢奢求，那你什麼時候才有房？",
      },
      {
        id: "sanjiuma-housing-013-f",
        text: "幹，我要買元宇宙的房子，比較潮。",
        archetype: "backfire",
        retort: "……（舅媽完全聽不懂在說什麼）",
      },
      {
        id: "sanjiuma-housing-013-g",
        text: "靠，我是想買，但夢想跟現實差很多啦。",
        archetype: "backfire",
        retort: "……（沒人回應）",
      },
      {
        id: "sanjiuma-housing-013-h",
        text: "幹，精華地段是精華，妳心眼比較不精華吧老太婆？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-014",
    text: "你要幾坪才夠住？表哥新家四十坪。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-014-a",
        text: "他媽的，四十坪一個人住，是要開廟嗎？",
        archetype: "perfect",
        retort: "開什麼廟！你嘴巴放乾淨一點！",
      },
      {
        id: "sanjiuma-housing-014-b",
        text: "靠，夠住就好，舅媽要不要分我幾坪？",
        archetype: "deflect",
        retort: "分你？你當那是蛋糕喔。",
      },
      {
        id: "sanjiuma-housing-014-c",
        text: "十幾坪就夠啦，笑死，我不貪心。",
        archetype: "deflect",
        retort: "不貪心是好事，但也太委屈了吧。",
      },
      {
        id: "sanjiuma-housing-014-d",
        text: "幹……有間小套房遮風避雨就好……",
        archetype: "meek",
        retort: "遮風避雨就好？太沒志氣了吧。",
      },
      {
        id: "sanjiuma-housing-014-e",
        text: "靠……坪數小沒關係，租金付得起就好……",
        archetype: "meek",
        retort: "付得起，那你什麼時候要買？",
      },
      {
        id: "sanjiuma-housing-014-f",
        text: "幹，我要住膠囊旅館風，這叫極簡主義。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說笑吧」）",
      },
      {
        id: "sanjiuma-housing-014-g",
        text: "機掰，我連掃地機器人都塞不進去啦。",
        archetype: "backfire",
        retort: "……（沒人笑）",
      },
      {
        id: "sanjiuma-housing-014-h",
        text: "幹，四十坪空一半給灰塵住，老太婆妳是嫌命長？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-015",
    text: "要買電梯大樓還是公寓？表哥住電梯的。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-015-a",
        text: "靠北，電梯大樓管理費是不是比表哥薪水漲得快？",
        archetype: "perfect",
        retort: "你這什麼話，胡說八道！",
      },
      {
        id: "sanjiuma-housing-015-b",
        text: "靠，都可以啦，舅媽有推薦的建案嗎？",
        archetype: "deflect",
        retort: "建案？你當我房仲喔。",
      },
      {
        id: "sanjiuma-housing-015-c",
        text: "公寓也不錯啦，笑死，爬樓梯還能減肥。",
        archetype: "deflect",
        retort: "減肥？你是要爬到瘦死喔。",
      },
      {
        id: "sanjiuma-housing-015-d",
        text: "幹……公寓比較便宜，只能將就……",
        archetype: "meek",
        retort: "將就？你要住到什麼時候？",
      },
      {
        id: "sanjiuma-housing-015-e",
        text: "靠……沒電梯是辛苦一點，但省錢……",
        archetype: "meek",
        retort: "省錢是省錢，但腳不會抗議喔？",
      },
      {
        id: "sanjiuma-housing-015-f",
        text: "靠北，我在練習爬樓梯，為未來的透天厝準備啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得莫名其妙）",
      },
      {
        id: "sanjiuma-housing-015-g",
        text: "他媽的，我怕電梯故障被關，還是公寓好。",
        archetype: "backfire",
        retort: "……（沒人搭話）",
      },
      {
        id: "sanjiuma-housing-015-h",
        text: "去死啦，電梯是給人用的，不是給妳這老東西吹噓的。",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-016",
    text: "要不要跟朋友合資買房？聽說能省很多。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-016-a",
        text: "幹，合資買房跟合資養表哥一樣，最後都是妳在管帳吧？",
        archetype: "perfect",
        retort: "你這什麼意思！我哪有在管他錢！",
      },
      {
        id: "sanjiuma-housing-016-b",
        text: "靠北，合資是個方法啦，舅媽要不要入股？",
        archetype: "deflect",
        retort: "入股？我才不要淌這渾水。",
      },
      {
        id: "sanjiuma-housing-016-c",
        text: "還在研究啦，笑死，風險要評估。",
        archetype: "deflect",
        retort: "評估半天，你到底要不要買啊。",
      },
      {
        id: "sanjiuma-housing-016-d",
        text: "幹……合資怕跟朋友撕破臉，不敢……",
        archetype: "meek",
        retort: "不敢？那你永遠買不了房。",
      },
      {
        id: "sanjiuma-housing-016-e",
        text: "靠……朋友也沒錢，合資合不起來……",
        archetype: "meek",
        retort: "合不起來，那就自己努力啊。",
      },
      {
        id: "sanjiuma-housing-016-f",
        text: "靠北，我打算跟我養的貓合資啦，牠比較穩。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子壞了）",
      },
      {
        id: "sanjiuma-housing-016-g",
        text: "機掰，合資到最後應該會友情破裂吧，先撤。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-016-h",
        text: "幹你娘，妳那間該不會也是跟舅舅合資騙來的吧，老太婆？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-017",
    text: "有沒有申請青年安心成家貸款？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-017-a",
        text: "他媽的，安心成家喔，成的是家還是負債？",
        archetype: "perfect",
        retort: "你這孩子講話怎麼這麼毒！",
      },
      {
        id: "sanjiuma-housing-017-b",
        text: "靠，有在查啦，舅媽妳懂的話教教我啊。",
        archetype: "deflect",
        retort: "教你？我哪懂那些條文。",
      },
      {
        id: "sanjiuma-housing-017-c",
        text: "還在研究資格啦，笑死，條件一大堆。",
        archetype: "deflect",
        retort: "條件多也要去申請啊，拖什麼。",
      },
      {
        id: "sanjiuma-housing-017-d",
        text: "幹……資格卡在收入太低，申請不過……",
        archetype: "meek",
        retort: "收入低，那要不要換工作？",
      },
      {
        id: "sanjiuma-housing-017-e",
        text: "靠……利率補貼也沒多少，杯水車薪……",
        archetype: "meek",
        retort: "杯水車薪也要喝啊，別放棄。",
      },
      {
        id: "sanjiuma-housing-017-f",
        text: "幹，我在等政府直接送我一間房啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在做夢）",
      },
      {
        id: "sanjiuma-housing-017-g",
        text: "靠，申請表填到一半我睡著了。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-017-h",
        text: "去你的，青年貸款是給年輕人的，不是給老東西酸的。",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-018",
    text: "現在房貸利率多少？你知道嗎？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-018-a",
        text: "機掰，利率我知道，妳知道表哥薪水多久沒漲嗎？",
        archetype: "perfect",
        retort: "你！他薪水穩定得很，關你什麼事！",
      },
      {
        id: "sanjiuma-housing-018-b",
        text: "靠北，利率的事，舅媽妳消息比較靈通吧？",
        archetype: "deflect",
        retort: "靈通？我哪懂那些數字。",
      },
      {
        id: "sanjiuma-housing-018-c",
        text: "不太清楚耶，笑死，反正買不起算了。",
        archetype: "deflect",
        retort: "算了？年輕人怎麼這麼沒鬥志。",
      },
      {
        id: "sanjiuma-housing-018-d",
        text: "幹……利率漲一直漲，我算不出來……",
        archetype: "meek",
        retort: "算不出來，那你怎麼規劃買房？",
      },
      {
        id: "sanjiuma-housing-018-e",
        text: "靠……聽新聞說在漲，很怕……",
        archetype: "meek",
        retort: "怕就要提早準備啊，別拖了。",
      },
      {
        id: "sanjiuma-housing-018-f",
        text: "幹，利率我不管啦，我信仰通膨解決一切。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-housing-018-g",
        text: "他媽的，我以為利率是超商咖啡的意思。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-housing-018-h",
        text: "幹，利率漲成這樣，妳當年利率才多低，老太婆閉嘴啦。",
        archetype: "landmine",
        retort: "去你的，沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-019",
    text: "有沒有跟房東談降租？表哥都不用煩這個。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-019-a",
        text: "靠北，表哥不用煩是因為妳幫他繳吧，舅媽？",
        archetype: "perfect",
        retort: "你這什麼意思！他自己繳得起！",
      },
      {
        id: "sanjiuma-housing-019-b",
        text: "靠，有在談啦，舅媽要不要幫我出面談？",
        archetype: "deflect",
        retort: "出面？你當我是誰的媽喔。",
      },
      {
        id: "sanjiuma-housing-019-c",
        text: "還沒開口啦，笑死，房東比我還兇。",
        archetype: "deflect",
        retort: "比你兇？那你要更會講話啊。",
      },
      {
        id: "sanjiuma-housing-019-d",
        text: "幹……不敢開口談，怕被趕出去……",
        archetype: "meek",
        retort: "不敢談，那你只能一直被欺負。",
      },
      {
        id: "sanjiuma-housing-019-e",
        text: "靠……房東說漲就漲，我沒得選……",
        archetype: "meek",
        retort: "沒得選，那你要不要考慮搬家？",
      },
      {
        id: "sanjiuma-housing-019-f",
        text: "靠，我準備用眼神跟房東談判啦。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼廢話」）",
      },
      {
        id: "sanjiuma-housing-019-g",
        text: "機掰，我傳訊息給房東結果傳錯人。",
        archetype: "backfire",
        retort: "……（全場沉默）",
      },
      {
        id: "sanjiuma-housing-019-h",
        text: "機掰，妳催我談降租，怎麼不去催表哥的公司加薪，老東西？",
        archetype: "landmine",
        retort: "幹，你是欠罵是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-020",
    text: "要不要跟對象一起買房？表哥結婚就買了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-020-a",
        text: "幹，表哥結婚買房，是舅舅出的頭期款吧，不是他？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己付的！",
      },
      {
        id: "sanjiuma-housing-020-b",
        text: "靠北，有對象再說啦，舅媽要不要幫我介紹？",
        archetype: "deflect",
        retort: "介紹？我哪有那種美國時間。",
      },
      {
        id: "sanjiuma-housing-020-c",
        text: "還沒對象啦，笑死，先讓我有人再說買房。",
        archetype: "deflect",
        retort: "沒對象？那你要加把勁了。",
      },
      {
        id: "sanjiuma-housing-020-d",
        text: "幹……連對象都沒有，買房更遙遠了……",
        archetype: "meek",
        retort: "沒對象是要怪誰，趕快去交往啊。",
      },
      {
        id: "sanjiuma-housing-020-e",
        text: "靠……一個人買房壓力太大了……",
        archetype: "meek",
        retort: "壓力大就要找人分擔啊。",
      },
      {
        id: "sanjiuma-housing-020-f",
        text: "幹，我打算跟存款簿結婚啦，比較穩定。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-housing-020-g",
        text: "他媽的，我單身太久，都忘記怎麼跟人講話了。",
        archetype: "backfire",
        retort: "……（舅媽沒接話，喝口茶）",
      },
      {
        id: "sanjiuma-housing-020-h",
        text: "幹你娘，結婚買房是妳出錢，好意思說是他本事，老太婆？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-021",
    text: "老家那間要不要過戶給你？考慮一下。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-021-a",
        text: "靠北，過戶給我？那我要不要順便繼承妳的臭脾氣？",
        archetype: "perfect",
        retort: "你這什麼態度！講話沒大沒小！",
      },
      {
        id: "sanjiuma-housing-021-b",
        text: "靠，真的假的？舅媽妳說話算話喔？",
        archetype: "deflect",
        retort: "說話算話？你少得意忘形。",
      },
      {
        id: "sanjiuma-housing-021-c",
        text: "再看看啦，笑死，先不要高興得太早。",
        archetype: "deflect",
        retort: "高興？誰跟你說要給你了。",
      },
      {
        id: "sanjiuma-housing-021-d",
        text: "幹……我怕過戶了以後還要負責修繕……",
        archetype: "meek",
        retort: "修繕怕什麼，房子是你的耶。",
      },
      {
        id: "sanjiuma-housing-021-e",
        text: "靠……老家那間感覺很舊，怕接手麻煩……",
        archetype: "meek",
        retort: "嫌舊？那我留給表哥好了。",
      },
      {
        id: "sanjiuma-housing-021-f",
        text: "靠，我對老家有情感，但情感不能拿來繳房屋稅。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-housing-021-g",
        text: "機掰，我以為妳在開玩笑，結果是認真的，嚇到我了。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-housing-021-h",
        text: "去死啦，是想把爛房子丟給我，還敢說是考慮，老東西？",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
] satisfies Question[];
