import type { Question } from "@/content/types";

export default [
  {
    id: "sanjiuma-housing-022",
    text: "表哥車貸房貸一起繳都不喘，你呢？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-022-a",
        text: "幹，兩貸都不喘，是不是舅舅在背後偷偷幫他繳？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己繳的！",
      },
      {
        id: "sanjiuma-housing-022-b",
        text: "靠，我只繳房租啦，舅媽要不要幫我分擔？",
        archetype: "deflect",
        retort: "分擔？你當我提款機喔。",
      },
      {
        id: "sanjiuma-housing-022-c",
        text: "笑死，沒有貸款壓力，反而過得比較輕鬆。",
        archetype: "deflect",
        retort: "輕鬆？那你根本沒資產吧。",
      },
      {
        id: "sanjiuma-housing-022-d",
        text: "幹……我光房租就快喘不過氣了……",
        archetype: "meek",
        retort: "喘不過氣就要想辦法加薪啊。",
      },
      {
        id: "sanjiuma-housing-022-e",
        text: "靠……薪水一半都拿去繳房租了……",
        archetype: "meek",
        retort: "一半？那你怎麼存錢買房？",
      },
      {
        id: "sanjiuma-housing-022-f",
        text: "靠，我沒有貸款壓力，因為我根本沒資格貸款啦。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-housing-022-g",
        text: "他媽的，我試算過房貸，結果直接被系統拒絕。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-housing-022-h",
        text: "幹，兩貸不喘是不是舅舅偷偷貼補的，老東西別幫他吹噓。",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-023",
    text: "舅媽的私房錢要不要借你投資房地產？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-023-a",
        text: "靠北，私房錢是舅舅存的還是從表哥薪水扣的？",
        archetype: "perfect",
        retort: "去死啦你，講話這麼難聽！",
      },
      {
        id: "sanjiuma-housing-023-b",
        text: "靠，真的假的？舅媽妳認真要借我喔？",
        archetype: "deflect",
        retort: "認真？你少作夢了。",
      },
      {
        id: "sanjiuma-housing-023-c",
        text: "笑死，投資有賺有賠，舅媽的錢我不敢碰。",
        archetype: "deflect",
        retort: "不敢碰？那你膽子也太小了。",
      },
      {
        id: "sanjiuma-housing-023-d",
        text: "幹……我怕投資失敗，不敢跟妳借……",
        archetype: "meek",
        retort: "怕失敗就永遠不會成功啊。",
      },
      {
        id: "sanjiuma-housing-023-e",
        text: "靠……房地產門檻太高，借了也不敢投……",
        archetype: "meek",
        retort: "不敢投，那你要窮到什麼時候？",
      },
      {
        id: "sanjiuma-housing-023-f",
        text: "幹，我打算拿舅媽的私房錢去買樂透，穩賺不賠。",
        archetype: "backfire",
        retort: "……（舅媽轉頭滑手機）",
      },
      {
        id: "sanjiuma-housing-023-g",
        text: "靠北，我把投資計畫講得天花亂墜，結果自己都聽不懂。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-023-h",
        text: "幹你娘，私房錢是不是從表哥薪水偷扣的，老太婆？",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-024",
    text: "租屋通勤要多久？聽說很辛苦。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-024-a",
        text: "他媽的，通勤辛苦總比表哥被舅舅管一輩子辛苦吧？",
        archetype: "perfect",
        retort: "你這什麼話！他哪有被誰管！",
      },
      {
        id: "sanjiuma-housing-024-b",
        text: "靠，還好啦，舅媽要不要來體驗一次？",
        archetype: "deflect",
        retort: "體驗？我才不要擠那種車廂。",
      },
      {
        id: "sanjiuma-housing-024-c",
        text: "笑死，通勤時間拿來追劇，一點都不辛苦。",
        archetype: "deflect",
        retort: "追劇？那你根本不專心工作吧。",
      },
      {
        id: "sanjiuma-housing-024-d",
        text: "幹……單程一個半小時，累到快睡著……",
        archetype: "meek",
        retort: "累也要撐啊，誰叫你住那麼遠。",
      },
      {
        id: "sanjiuma-housing-024-e",
        text: "靠……每天摸黑出門，摸黑回家……",
        archetype: "meek",
        retort: "摸黑出門？那也太可憐了。",
      },
      {
        id: "sanjiuma-housing-024-f",
        text: "靠，我通勤時間拿來冥想，比表哥開車還修身養性。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-housing-024-g",
        text: "機掰，我坐過站坐到終點站，遲到兩小時。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-housing-024-h",
        text: "去你的，通勤辛苦關妳屁事，老東西不會累喔？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-025",
    text: "要不要跟舅舅借點錢買房？他很有辦法。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-025-a",
        text: "幹，跟舅舅借錢是不是要簽賣身契，舅媽？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他很大方好嗎！",
      },
      {
        id: "sanjiuma-housing-025-b",
        text: "靠北，真的可以借嗎？舅媽妳先幫我問問。",
        archetype: "deflect",
        retort: "問問？你少得意忘形。",
      },
      {
        id: "sanjiuma-housing-025-c",
        text: "笑死，借錢是要還的，我不想欠人情。",
        archetype: "deflect",
        retort: "不想欠人情？那你永遠買不了房。",
      },
      {
        id: "sanjiuma-housing-025-d",
        text: "幹……不好意思開口跟長輩借錢……",
        archetype: "meek",
        retort: "不開口，那你要買到民國幾年？",
      },
      {
        id: "sanjiuma-housing-025-e",
        text: "靠……欠錢感覺很有壓力，還是算了……",
        archetype: "meek",
        retort: "算了？那你就繼續租房子吧。",
      },
      {
        id: "sanjiuma-housing-025-f",
        text: "靠，我打算跟舅舅借的時候順便談分潤，比較划算。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-housing-025-g",
        text: "他媽的，我開口借錢結果緊張到忘記講重點。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-025-h",
        text: "幹，跟舅舅借錢是不是要簽一輩子聽話的合約，老太婆？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-026",
    text: "嫁妝聘金能不能湊一湊當頭期款？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-026-a",
        text: "靠北，嫁妝聘金拿來買房，那以後算誰的名字？",
        archetype: "perfect",
        retort: "你這什麼意思，講話這麼賤！",
      },
      {
        id: "sanjiuma-housing-026-b",
        text: "靠，還沒結婚啦，舅媽要不要先幫我存嫁妝？",
        archetype: "deflect",
        retort: "存嫁妝？你性別搞錯了吧。",
      },
      {
        id: "sanjiuma-housing-026-c",
        text: "笑死，這種事要看緣分，急不來的。",
        archetype: "deflect",
        retort: "緣分急不來，那你要單身到幾歲？",
      },
      {
        id: "sanjiuma-housing-026-d",
        text: "幹……連對象都沒有，聘金更是想都別想……",
        archetype: "meek",
        retort: "沒對象就要去交往啊，別放棄。",
      },
      {
        id: "sanjiuma-housing-026-e",
        text: "靠……以後結婚再說，現在不敢亂想……",
        archetype: "meek",
        retort: "不敢想？那你打算單身一輩子？",
      },
      {
        id: "sanjiuma-housing-026-f",
        text: "靠，我打算跟自己聘自己，比較省事。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼」）",
      },
      {
        id: "sanjiuma-housing-026-g",
        text: "機掰，我算聘金算到自己都嚇死。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-026-h",
        text: "幹你娘，聘金湊頭期款是不是妳的如意算盤，老東西？",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-027",
    text: "老家土地要不要都更改建？聽說能賺。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-027-a",
        text: "機掰，都更能賺，妳知道要拖幾年才會有結果嗎？",
        archetype: "perfect",
        retort: "你這什麼態度！都更是好事！",
      },
      {
        id: "sanjiuma-housing-027-b",
        text: "靠，都更是好啦，舅媽要不要找建商來談？",
        archetype: "deflect",
        retort: "找建商？你當我是里長喔。",
      },
      {
        id: "sanjiuma-housing-027-c",
        text: "笑死，改建太麻煩，我還是先租房子好。",
        archetype: "deflect",
        retort: "太麻煩？那你就繼續當房客吧。",
      },
      {
        id: "sanjiuma-housing-027-d",
        text: "幹……都更牽扯的人太多，很怕吵架……",
        archetype: "meek",
        retort: "怕吵架就別碰這種事了。",
      },
      {
        id: "sanjiuma-housing-027-e",
        text: "靠……老家的事我不敢插手，怕得罪人……",
        archetype: "meek",
        retort: "得罪人？那你永遠只能旁觀。",
      },
      {
        id: "sanjiuma-housing-027-f",
        text: "靠，我打算自己蓋一棟，比都更快。",
        archetype: "backfire",
        retort: "……（舅媽翻白眼）",
      },
      {
        id: "sanjiuma-housing-027-g",
        text: "他媽的，我提議都更結果被親戚圍剿。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-027-h",
        text: "去你的，都更能賺是不是妳早就算計好的，老太婆？",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-028",
    text: "預售屋交屋驗屋了沒？表哥驗得很仔細。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-028-a",
        text: "幹，驗屋驗得仔細，是不是怕舅舅出的錢被建商A走？",
        archetype: "perfect",
        retort: "你他媽的胡說，他自己謹慎！",
      },
      {
        id: "sanjiuma-housing-028-b",
        text: "靠北，我還沒買，等我買了一定驗仔細。",
        archetype: "deflect",
        retort: "仔細？你連頭期款都沒有咧。",
      },
      {
        id: "sanjiuma-housing-028-c",
        text: "笑死，租的房子不用驗屋，省事多了。",
        archetype: "deflect",
        retort: "省事？那你就一輩子租房吧。",
      },
      {
        id: "sanjiuma-housing-028-d",
        text: "幹……買不起預售屋，驗屋輪不到我……",
        archetype: "meek",
        retort: "輪不到你，那你要努力賺錢啊。",
      },
      {
        id: "sanjiuma-housing-028-e",
        text: "靠……連看房都不敢去看，怕更絕望……",
        archetype: "meek",
        retort: "絕望也要面對啊，別逃避。",
      },
      {
        id: "sanjiuma-housing-028-f",
        text: "靠，我驗屋的標準是有沒有鬼故事，比較重要。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-housing-028-g",
        text: "機掰，我去看房結果被業務推銷到崩潰。",
        archetype: "backfire",
        retort: "……（沒人笑得出來）",
      },
      {
        id: "sanjiuma-housing-028-h",
        text: "幹，驗屋驗得仔細是不是怕舅舅的錢被A走，老太婆？",
        archetype: "landmine",
        retort: "你這什麼態度，欠教訓是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-029",
    text: "房子座向風水有沒有看？表哥都請老師看。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-029-a",
        text: "他媽的，風水看再好，房貸利率也不會變低吧，舅媽？",
        archetype: "perfect",
        retort: "你這孩子講話怎麼這麼毒！",
      },
      {
        id: "sanjiuma-housing-029-b",
        text: "靠，我沒看風水啦，舅媽要不要幫我介紹老師？",
        archetype: "deflect",
        retort: "介紹？你當我是命理館喔。",
      },
      {
        id: "sanjiuma-housing-029-c",
        text: "笑死，風水信一半就好，還是現實比較重要。",
        archetype: "deflect",
        retort: "現實重要，那你怎麼還不買房。",
      },
      {
        id: "sanjiuma-housing-029-d",
        text: "幹……我連房子都沒有，風水想都別想……",
        archetype: "meek",
        retort: "想都別想？那你要努力存錢啊。",
      },
      {
        id: "sanjiuma-housing-029-e",
        text: "靠……租的房子座向不能挑，只能將就……",
        archetype: "meek",
        retort: "將就？那你什麼時候要買自己的？",
      },
      {
        id: "sanjiuma-housing-029-f",
        text: "靠，我房間座向是我自己算的，很準的啦。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-housing-029-g",
        text: "幹，我請老師看完風水，結果他叫我搬家。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-029-h",
        text: "幹，風水看再準，也算不出妳這老太婆的心眼多黑。",
        archetype: "landmine",
        retort: "幹你娘咧，你什麼意思！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-030",
    text: "舅媽拿房仲廣告單問你，這間你買得起？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-030-a",
        text: "靠北，這間我買得起，前提是舅媽妳先幫我付清。",
        archetype: "perfect",
        retort: "你！誰跟你講的！我才不會幫你付！",
      },
      {
        id: "sanjiuma-housing-030-b",
        text: "靠，這間不錯啦，舅媽要不要幫我斡旋？",
        archetype: "deflect",
        retort: "斡旋？你當我房仲喔。",
      },
      {
        id: "sanjiuma-housing-030-c",
        text: "笑死，看看就好，過過乾癮而已。",
        archetype: "deflect",
        retort: "乾癮？那你什麼時候要實際行動。",
      },
      {
        id: "sanjiuma-housing-030-d",
        text: "幹……這間我一輩子都買不起，別問了……",
        archetype: "meek",
        retort: "一輩子？那你要不要換個目標。",
      },
      {
        id: "sanjiuma-housing-030-e",
        text: "靠……這種價位對我來說是天方夜譚……",
        archetype: "meek",
        retort: "天方夜譚，那你要更努力賺錢啊。",
      },
      {
        id: "sanjiuma-housing-030-f",
        text: "靠，這間我早就內定了，只是還沒付錢。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-housing-030-g",
        text: "他媽的，我把廣告單看成中獎通知，空歡喜一場。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-030-h",
        text: "幹，拿廣告單問我買得起，老太婆是想看我笑話吧？",
        archetype: "landmine",
        retort: "去你的，沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-031",
    text: "租屋有沒有簽約？有保障嗎？別被騙。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-031-a",
        text: "幹，有沒有簽約，是要保障我還是保障妳的八卦資料？",
        archetype: "perfect",
        retort: "你這什麼意思！我是關心你！",
      },
      {
        id: "sanjiuma-housing-031-b",
        text: "靠，有簽啦，舅媽要不要幫我看合約？",
        archetype: "deflect",
        retort: "看合約？妳看得懂法律條文喔。",
      },
      {
        id: "sanjiuma-housing-031-c",
        text: "笑死，簽約當然要看仔細，我又不是笨蛋。",
        archetype: "deflect",
        retort: "不是笨蛋，那你租金怎麼被漲。",
      },
      {
        id: "sanjiuma-housing-031-d",
        text: "幹……簽約的時候太緊張，沒看清楚條款……",
        archetype: "meek",
        retort: "沒看清楚，那你不就等著被坑。",
      },
      {
        id: "sanjiuma-housing-031-e",
        text: "靠……房東給的合約看不太懂，硬簽了……",
        archetype: "meek",
        retort: "硬簽？那你風險自己扛喔。",
      },
      {
        id: "sanjiuma-housing-031-f",
        text: "靠，我合約簽好之後房東就消失了，比較刺激。",
        archetype: "backfire",
        retort: "……（舅媽覺得莫名其妙）",
      },
      {
        id: "sanjiuma-housing-031-g",
        text: "機掰，我把合約放在洗衣機裡洗爛了。",
        archetype: "backfire",
        retort: "……（沒人搭話）",
      },
      {
        id: "sanjiuma-housing-031-h",
        text: "幹你娘，妳問我簽約，是想找把柄去跟表哥比較吧，老東西？",
        archetype: "landmine",
        retort: "機掰你，講這什麼話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-032",
    text: "要不要先租後買？表哥直接就買了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-032-a",
        text: "靠北，先租後買是理性，表哥直接買是舅舅出頭期款吧？",
        archetype: "perfect",
        retort: "你這什麼話，胡說八道！",
      },
      {
        id: "sanjiuma-housing-032-b",
        text: "靠，先租感覺比較保險，舅媽有推薦的地區嗎？",
        archetype: "deflect",
        retort: "地區？你當我房仲喔。",
      },
      {
        id: "sanjiuma-housing-032-c",
        text: "笑死，租屋自由，想搬就搬，比買房輕鬆多了。",
        archetype: "deflect",
        retort: "輕鬆？那你什麼時候要定下來。",
      },
      {
        id: "sanjiuma-housing-032-d",
        text: "幹……我還在存錢，先租著等機會……",
        archetype: "meek",
        retort: "等機會？機會不會等你太久喔。",
      },
      {
        id: "sanjiuma-housing-032-e",
        text: "靠……買房太可怕了，先租著比較安心……",
        archetype: "meek",
        retort: "安心？安心能當資產嗎。",
      },
      {
        id: "sanjiuma-housing-032-f",
        text: "靠，我先租後買的策略是租到房東把房子送我。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你在說什麼廢話」）",
      },
      {
        id: "sanjiuma-housing-032-g",
        text: "他媽的，我租屋租到跟房東吵架搬家三次。",
        archetype: "backfire",
        retort: "……（全場沉默）",
      },
      {
        id: "sanjiuma-housing-032-h",
        text: "幹，先租後買是不是妳嫌棄我買不起才這樣說，老太婆？",
        archetype: "landmine",
        retort: "幹，你是欠罵是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-033",
    text: "表哥買第二間房收租了，你有一間嗎？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-033-a",
        text: "機掰，第二間房收租，是不是舅舅出的頭期款當包租公？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己買的！",
      },
      {
        id: "sanjiuma-housing-033-b",
        text: "靠北，我連第一間都沒有啦，舅媽要不要送我一間？",
        archetype: "deflect",
        retort: "送你？你想得美。",
      },
      {
        id: "sanjiuma-housing-033-c",
        text: "笑死，一間都沒有反而輕鬆，沒房貸壓力。",
        archetype: "deflect",
        retort: "輕鬆？那你就是沒本事吧。",
      },
      {
        id: "sanjiuma-housing-033-d",
        text: "幹……我連租都快租不起了，別說買第二間……",
        archetype: "meek",
        retort: "租不起？那你要多兼一份工作。",
      },
      {
        id: "sanjiuma-housing-033-e",
        text: "靠……存錢中，離第一間都還很遠……",
        archetype: "meek",
        retort: "很遠？那你到底在拖什麼。",
      },
      {
        id: "sanjiuma-housing-033-f",
        text: "靠，我的第二間房在我夢裡，很豪華的那種。",
        archetype: "backfire",
        retort: "……（舅媽覺得你腦子有洞）",
      },
      {
        id: "sanjiuma-housing-033-g",
        text: "幹，我投資的房地產遊戲破產了，別提了。",
        archetype: "backfire",
        retort: "……（沒人接話）",
      },
      {
        id: "sanjiuma-housing-033-h",
        text: "幹你娘，第二間房收租是不是舅舅名下暗槓的，老太婆？",
        archetype: "landmine",
        retort: "你他媽的講話這麼衝，滾一邊去！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-034",
    text: "有沒有申請社會住宅？候補到了嗎？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-034-a",
        text: "他媽的，候補社會住宅還不如候補表哥被開除比較快吧？",
        archetype: "perfect",
        retort: "你這什麼詛咒！嘴巴放乾淨點！",
      },
      {
        id: "sanjiuma-housing-034-b",
        text: "靠，有申請啦，舅媽要不要幫我關說一下？",
        archetype: "deflect",
        retort: "關說？你當我認識議員喔。",
      },
      {
        id: "sanjiuma-housing-034-c",
        text: "笑死，候補中，反正租屋也還過得去。",
        archetype: "deflect",
        retort: "過得去？那你就繼續租一輩子。",
      },
      {
        id: "sanjiuma-housing-034-d",
        text: "幹……候補號碼排到天荒地老，看不到希望……",
        archetype: "meek",
        retort: "看不到希望？那你要不要換方法。",
      },
      {
        id: "sanjiuma-housing-034-e",
        text: "靠……社會住宅太搶手，機會渺茫……",
        archetype: "meek",
        retort: "渺茫？那你要不要考慮買房。",
      },
      {
        id: "sanjiuma-housing-034-f",
        text: "靠，我候補社會住宅候補到都能出書了。",
        archetype: "backfire",
        retort: "……（舅媽一臉聽不懂）",
      },
      {
        id: "sanjiuma-housing-034-g",
        text: "機掰，我申請文件寄丟了，重新排隊。",
        archetype: "backfire",
        retort: "……（沒人知道你在講什麼）",
      },
      {
        id: "sanjiuma-housing-034-h",
        text: "幹，社會住宅候補這麼久，妳是不是巴不得我一輩子租房，老東西？",
        archetype: "landmine",
        retort: "去死啦你，講話這麼難聽！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-035",
    text: "你搬家好幾次，是不是租不起久住？",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-035-a",
        text: "幹，搬家好幾次，總比表哥搬回舅舅家啃老好吧？",
        archetype: "perfect",
        retort: "你他媽的胡說，他才沒有啃老！",
      },
      {
        id: "sanjiuma-housing-035-b",
        text: "靠北，搬家是因為要找更好的地方啦，舅媽別誤會。",
        archetype: "deflect",
        retort: "別誤會？你分明就是租不起。",
      },
      {
        id: "sanjiuma-housing-035-c",
        text: "笑死，搬家當作換季，換個心情而已。",
        archetype: "deflect",
        retort: "換心情？那你的錢包心情好嗎。",
      },
      {
        id: "sanjiuma-housing-035-d",
        text: "幹……搬家是因為房租一直漲，撐不住……",
        archetype: "meek",
        retort: "撐不住就要努力多賺一點。",
      },
      {
        id: "sanjiuma-housing-035-e",
        text: "靠……房東一直要收回房子，我也很無奈……",
        archetype: "meek",
        retort: "無奈就要早點做打算啊。",
      },
      {
        id: "sanjiuma-housing-035-f",
        text: "靠，我搬家是為了體驗不同的鄰居文化。",
        archetype: "backfire",
        retort: "……（舅媽覺得你在唬爛）",
      },
      {
        id: "sanjiuma-housing-035-g",
        text: "他媽的，我搬家搬到東西弄丟一半。",
        archetype: "backfire",
        retort: "……（全場尷尬）",
      },
      {
        id: "sanjiuma-housing-035-h",
        text: "幹，搬這麼多次是不是妳巴不得看我笑話，老太婆？",
        archetype: "landmine",
        retort: "滾啦你，講這什麼難聽話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-036",
    text: "退休後房子怎麼打算？表哥都想好了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-036-a",
        text: "靠北，表哥退休想好了，是不是靠舅舅留給他的房子？",
        archetype: "perfect",
        retort: "你這什麼態度！他自己規劃的！",
      },
      {
        id: "sanjiuma-housing-036-b",
        text: "靠，我還沒想那麼遠啦，舅媽要不要幫我規劃？",
        archetype: "deflect",
        retort: "規劃？你當我理財顧問喔。",
      },
      {
        id: "sanjiuma-housing-036-c",
        text: "笑死，退休還早，先顧好現在租的房子吧。",
        archetype: "deflect",
        retort: "還早？你這樣以後會後悔。",
      },
      {
        id: "sanjiuma-housing-036-d",
        text: "幹……退休金我看了都想哭，別提了……",
        archetype: "meek",
        retort: "想哭就要提早準備啊。",
      },
      {
        id: "sanjiuma-housing-036-e",
        text: "靠……現在都不夠用了，哪敢想退休……",
        archetype: "meek",
        retort: "不敢想，那你要工作到幾歲？",
      },
      {
        id: "sanjiuma-housing-036-f",
        text: "靠，我退休打算靠中樂透，機率跟買房差不多。",
        archetype: "backfire",
        retort: "……（舅媽一臉「你到底要不要」）",
      },
      {
        id: "sanjiuma-housing-036-g",
        text: "機掰，我算了退休金發現要工作到一百二十歲。",
        archetype: "backfire",
        retort: "……（全場無語）",
      },
      {
        id: "sanjiuma-housing-036-h",
        text: "幹，退休都想好了是不是靠妳留的房子，老東西別替他邀功。",
        archetype: "landmine",
        retort: "北七喔你，講這什麼幹話！",
      },
    ],
  },
  {
    id: "sanjiuma-housing-037",
    text: "有沒有跟爸媽商量買房預算？表哥都談好了。",
    topic: "housing",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-housing-037-a",
        text: "他媽的，跟爸媽談好預算，是不是舅舅直接把錢匯過去？",
        archetype: "perfect",
        retort: "你他媽的血口噴人，他自己談的！",
      },
      {
        id: "sanjiuma-housing-037-b",
        text: "靠，有稍微聊過啦，舅媽要不要幫我跟我爸媽談？",
        archetype: "deflect",
        retort: "幫你談？你自己不會開口喔。",
      },
      {
        id: "sanjiuma-housing-037-c",
        text: "笑死，預算談了也買不起，不如不談。",
        archetype: "deflect",
        retort: "不談？那你永遠停在原地。",
      },
      {
        id: "sanjiuma-housing-037-d",
        text: "幹……我爸媽也沒錢，預算根本談不出來……",
        archetype: "meek",
        retort: "談不出來，那你要自己想辦法。",
      },
      {
        id: "sanjiuma-housing-037-e",
        text: "靠……不好意思跟爸媽談錢，覺得很丟臉……",
        archetype: "meek",
        retort: "丟臉？不談你更買不起房。",
      },
      {
        id: "sanjiuma-housing-037-f",
        text: "靠，我跟爸媽談的預算單位是新台幣一元起。",
        archetype: "backfire",
        retort: "……（舅媽白眼，喝了口茶）",
      },
      {
        id: "sanjiuma-housing-037-g",
        text: "他媽的，我跟爸媽談預算談到吵架，不歡而散。",
        archetype: "backfire",
        retort: "……（全場安靜）",
      },
      {
        id: "sanjiuma-housing-037-h",
        text: "幹，跟爸媽談好預算是不是舅舅逼他們掏錢的，老太婆？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
] satisfies Question[];
