import type { Question } from "@/content/types";

// situations:
// 002 轉桌問薪水一年調整多少
// 003 舅媽翻名片問公司名字
// 004 算年終幾個月
// 005 問加班費有沒有
// 006 問有沒有繳勞退自提
// 007 問有沒有在買股票
// 008 問存款有多少
// 009 問公司幾個人是不是小公司
// 010 問薪水有沒有跟著表哥調
// 011 問試用期轉正了沒
// 012 問年終獎金拿多少
// 013 問要不要考公職求穩定
// 014 問幾點下班常不常加班
// 015 問有沒有買保險
// 016 問月薪養不養得起自己
// 017 問有沒有接案賺外快
// 018 問公司有沒有分紅
// 019 手機跳薪轉通知被舅媽瞄到
// 020 問以後結婚能不能養家
// 021 問工作幾年薪水漲多少

export default [
  {
    id: "sanjiuma-salary_job-002",
    text: "轉桌轉到你，薪水一年調整幅度多少？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-002-a",
        text: "幹，妳問調薪是要幫我加薪嗎？",
        archetype: "perfect",
        retort: "靠北，你嘴巴留點口德。",
      },
      {
        id: "sanjiuma-salary_job-002-b",
        text: "笑死，我都忘了自己領多少。",
        archetype: "deflect",
        retort: "少來，你心裡清楚得很。",
      },
      {
        id: "sanjiuma-salary_job-002-c",
        text: "靠，舅媽先說表哥調薪多少？",
        archetype: "deflect",
        retort: "問表哥幹嘛，問你自己啦。",
      },
      {
        id: "sanjiuma-salary_job-002-d",
        text: "幹……沒調整，公司說不景氣……",
        archetype: "meek",
        retort: "沒調？那你去年做假的？",
      },
      {
        id: "sanjiuma-salary_job-002-e",
        text: "有調一點，通膨全吃掉了……",
        archetype: "meek",
        retort: "調多少？說個數字來聽。",
      },
      {
        id: "sanjiuma-salary_job-002-f",
        text: "我他媽薪水是秘密，不能說。",
        archetype: "backfire",
        retort: "……（全桌安靜，沒人想理你）",
      },
      {
        id: "sanjiuma-salary_job-002-g",
        text: "薪水小事，我他媽靠信仰過日。",
        archetype: "backfire",
        retort: "……（表哥低頭滑手機沒接話）",
      },
      {
        id: "sanjiuma-salary_job-002-h",
        text: "去你的，死老太婆退休領勞保還敢問？",
        archetype: "landmine",
        retort: "幹！叫你媽出來！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-003",
    text: "把你名片翻過來，公司叫什麼名字？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-003-a",
        text: "靠北，公司名字不重要，沒靠關係進的。",
        archetype: "perfect",
        retort: "他媽的，你亂講什麼東西！",
      },
      {
        id: "sanjiuma-salary_job-003-b",
        text: "笑死，舅媽要不要收藏一張？",
        archetype: "deflect",
        retort: "少來，你話題轉真快。",
      },
      {
        id: "sanjiuma-salary_job-003-c",
        text: "哭爸，舅媽問這個想介紹客戶？",
        archetype: "deflect",
        retort: "介紹客戶？先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-003-d",
        text: "小公司啦，沒什麼名氣……",
        archetype: "meek",
        retort: "小公司？做什麼的說清楚。",
      },
      {
        id: "sanjiuma-salary_job-003-e",
        text: "幹……就一般貿易公司，不大……",
        archetype: "meek",
        retort: "不大？那薪水夠用嗎？",
      },
      {
        id: "sanjiuma-salary_job-003-f",
        text: "我公司名字機密，跟007一樣。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-003-g",
        text: "他媽的，我在幕後不方便說。",
        archetype: "backfire",
        retort: "……（表哥在旁邊尷尬地笑）",
      },
      {
        id: "sanjiuma-salary_job-003-h",
        text: "機掰，反正不像舅舅關係養的公司。",
        archetype: "landmine",
        retort: "明年不用他媽的來了！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-004",
    text: "年終領幾個月？表哥今年領六個月喔。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-004-a",
        text: "他媽的，六個月是他行還是自己人？",
        archetype: "perfect",
        retort: "（氣到講台語）幹恁娘咧",
      },
      {
        id: "sanjiuma-salary_job-004-b",
        text: "笑死，舅媽數字記得比我媽清楚。",
        archetype: "deflect",
        retort: "哎唷，這個要留意才知道。",
      },
      {
        id: "sanjiuma-salary_job-004-c",
        text: "靠，表哥領六個月要包紅包分我？",
        archetype: "deflect",
        retort: "紅包紅包，你只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-004-d",
        text: "我大概一個月吧，公司不景氣……",
        archetype: "meek",
        retort: "一個月？那年終算白拿？",
      },
      {
        id: "sanjiuma-salary_job-004-e",
        text: "幹……沒有耶，今年說不發……",
        archetype: "meek",
        retort: "不發？你有沒有問清楚？",
      },
      {
        id: "sanjiuma-salary_job-004-f",
        text: "我他媽領的是快樂，無價。",
        archetype: "backfire",
        retort: "……（舅媽看向表哥，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-004-g",
        text: "年終不重要，重要的是心意啦。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-004-h",
        text: "去死，六個月年終還不是老不死塞的？",
        archetype: "landmine",
        retort: "幹恁娘，你很沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-005",
    text: "加班有沒有加班費？表哥公司都有算。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-005-a",
        text: "機掰，沒加班費所以少加班。",
        archetype: "perfect",
        retort: "幹，你是不是欠揍啊。",
      },
      {
        id: "sanjiuma-salary_job-005-b",
        text: "笑死，要不要幫我跟老闆說？",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-salary_job-005-c",
        text: "靠，表哥公司福利真好，教我媽。",
        archetype: "deflect",
        retort: "這個要看公司，不是每間都有。",
      },
      {
        id: "sanjiuma-salary_job-005-d",
        text: "幹……沒有耶，責任制沒加班費……",
        archetype: "meek",
        retort: "責任制？一個月加多久？",
      },
      {
        id: "sanjiuma-salary_job-005-e",
        text: "有一點點，但很少加班到晚……",
        archetype: "meek",
        retort: "很晚是幾點，說清楚點。",
      },
      {
        id: "sanjiuma-salary_job-005-f",
        text: "我他媽把加班費換成經驗值。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-005-g",
        text: "沒加班費沒差，幹，心中自有時薪。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-005-h",
        text: "幹你娘，妳兒子加班費妳比我清楚？",
        archetype: "landmine",
        retort: "你他媽的欠教訓，滾！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-006",
    text: "勞退有沒有自提？以後退休才夠用。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-006-a",
        text: "機掰，自提總比靠兒子養老實在。",
        archetype: "perfect",
        retort: "他媽的沒大沒小，欠罵是不是。",
      },
      {
        id: "sanjiuma-salary_job-006-b",
        text: "笑死，舅媽這麼懂退休教教我？",
        archetype: "deflect",
        retort: "這個要早準備，你聽好。",
      },
      {
        id: "sanjiuma-salary_job-006-c",
        text: "靠，舅媽退休金規劃得如何？",
        archetype: "deflect",
        retort: "問我幹嘛，問你自己的。",
      },
      {
        id: "sanjiuma-salary_job-006-d",
        text: "幹……有自提一點點，存不了多少……",
        archetype: "meek",
        retort: "一點點是多少？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-006-e",
        text: "還沒開始想退休這件事……",
        archetype: "meek",
        retort: "不想？那你老了怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-006-f",
        text: "退休這種事，他媽交給緣分。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-006-g",
        text: "我打算工作到死，不用退休金。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-006-h",
        text: "去死，妳這老東西退休金領那麼多？",
        archetype: "landmine",
        retort: "去你的，我養你這麼大！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-007",
    text: "有沒有在買股票？表哥都買到賺翻了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-007-a",
        text: "幹，買股票是想抽成嗎？",
        archetype: "perfect",
        retort: "幹，你翅膀硬了是不是。",
      },
      {
        id: "sanjiuma-salary_job-007-b",
        text: "笑死，舅媽這麼會理財開群組？",
        archetype: "deflect",
        retort: "投資群組？先學會存錢。",
      },
      {
        id: "sanjiuma-salary_job-007-c",
        text: "靠，表哥買哪支賺翻的說一下？",
        archetype: "deflect",
        retort: "問表哥幹嘛，自己不會研究？",
      },
      {
        id: "sanjiuma-salary_job-007-d",
        text: "幹……有買一點點，都套在裡面……",
        archetype: "meek",
        retort: "套多少？虧了沒有說清楚。",
      },
      {
        id: "sanjiuma-salary_job-007-e",
        text: "沒有耶，薪水都不夠存了……",
        archetype: "meek",
        retort: "不夠存？那都花去哪了？",
      },
      {
        id: "sanjiuma-salary_job-007-f",
        text: "我他媽投資組合是回憶，全賠。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-007-g",
        text: "股票太麻煩，幹，我只投資快樂。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-007-h",
        text: "幹，妳去年不是才被套牢在那哭？",
        archetype: "landmine",
        retort: "幹，你這什麼死樣子！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-008",
    text: "存款有多少？表哥都存到能買車了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-008-a",
        text: "靠杯，比存款是要頒獎狀嗎，舅媽？",
        archetype: "perfect",
        retort: "頒獎狀？你才欠罵勒！",
      },
      {
        id: "sanjiuma-salary_job-008-b",
        text: "哭爸，舅媽關心存款要包紅包？",
        archetype: "deflect",
        retort: "紅包？自己不會存喔。",
      },
      {
        id: "sanjiuma-salary_job-008-c",
        text: "靠，舅媽自己存款有多少？先說。",
        archetype: "deflect",
        retort: "問我幹嘛，問你自己的事。",
      },
      {
        id: "sanjiuma-salary_job-008-d",
        text: "幹……存不到十萬，房租吃大半……",
        archetype: "meek",
        retort: "十萬都不到？那怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-008-e",
        text: "沒剩多少，月光族一個……",
        archetype: "meek",
        retort: "月光？那打算什麼時候存？",
      },
      {
        id: "sanjiuma-salary_job-008-f",
        text: "我他媽存款都投資在快樂上。",
        archetype: "backfire",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-salary_job-008-g",
        text: "存款這種東西，我早佛系了。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-008-h",
        text: "他媽的，存款老太婆不是被他周轉？",
        archetype: "landmine",
        retort: "他媽的，白眼狼是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-009",
    text: "你們公司幾個人？該不會很小間吧。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-009-a",
        text: "幹恁娘，小公司好，沒人靠關係塞。",
        archetype: "perfect",
        retort: "幹，你這孩子嘴巴怎麼賤。",
      },
      {
        id: "sanjiuma-salary_job-009-b",
        text: "笑死，舅媽問這麼細想投資？",
        archetype: "deflect",
        retort: "投資？你先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-009-c",
        text: "靠，小歸小但氣氛好，來玩？",
        archetype: "deflect",
        retort: "來玩？我還有事，改天。",
      },
      {
        id: "sanjiuma-salary_job-009-d",
        text: "幹……十幾個人吧，算蠻小的……",
        archetype: "meek",
        retort: "十幾個？發展空間夠嗎？",
      },
      {
        id: "sanjiuma-salary_job-009-e",
        text: "不到十個人，很多事自己做……",
        archetype: "meek",
        retort: "自己做？那有沒有加薪？",
      },
      {
        id: "sanjiuma-salary_job-009-f",
        text: "人數不重要，他媽的我很重要。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-009-g",
        text: "我們公司雖小，志氣比101高。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-009-h",
        text: "去你的，反正不是靠關係進的小公司。",
        archetype: "landmine",
        retort: "……（舅媽氣到，罵了聲幹）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-010",
    text: "表哥調薪你有跟著調嗎？同公司體系耶。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-010-a",
        text: "他媽的，我靠自己調薪，他靠誰？",
        archetype: "perfect",
        retort: "他媽的，含糊帶過算了。",
      },
      {
        id: "sanjiuma-salary_job-010-b",
        text: "笑死，舅媽消息真靈通。",
        archetype: "deflect",
        retort: "當然，我兒子的事都知道。",
      },
      {
        id: "sanjiuma-salary_job-010-c",
        text: "哭爸，表哥調薪要不要分我喜氣？",
        archetype: "deflect",
        retort: "喜氣？你自己去努力賺。",
      },
      {
        id: "sanjiuma-salary_job-010-d",
        text: "幹……沒有耶，公司體系不一樣……",
        archetype: "meek",
        retort: "不一樣？那薪水到底多少？",
      },
      {
        id: "sanjiuma-salary_job-010-e",
        text: "沒跟著調，公司今年凍漲……",
        archetype: "meek",
        retort: "凍漲？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-010-f",
        text: "我他媽調薪標準是自己開心。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-010-g",
        text: "薪水小事，他媽交給宇宙決定。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-010-h",
        text: "機掰，他調薪還不是死老太婆點頭？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-011",
    text: "試用期過了沒？轉正了嗎？表哥早正職了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-011-a",
        text: "機掰，轉正靠實力不是靠電話。",
        archetype: "perfect",
        retort: "去你的，你很欠教訓。",
      },
      {
        id: "sanjiuma-salary_job-011-b",
        text: "笑死，舅媽要不要幫我加油？",
        archetype: "deflect",
        retort: "加油？你自己好好表現。",
      },
      {
        id: "sanjiuma-salary_job-011-c",
        text: "靠，轉正了要不要包開工紅包？",
        archetype: "deflect",
        retort: "紅包紅包，你只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-011-d",
        text: "幹……剛到新單位，還在摸索……",
        archetype: "meek",
        retort: "緊張什麼，到底做多久了？",
      },
      {
        id: "sanjiuma-salary_job-011-e",
        text: "延長試用期了，主管說再看看……",
        archetype: "meek",
        retort: "再看看？要撐到什麼時候？",
      },
      {
        id: "sanjiuma-salary_job-011-f",
        text: "轉正不重要，他媽的早內心正職。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-011-g",
        text: "我把自己轉正成快樂員工啦。",
        archetype: "backfire",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-salary_job-011-h",
        text: "去死，反正不像他靠舅舅一句話轉正。",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-012",
    text: "年終獎金拿多少？別藏，說個數字。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-012-a",
        text: "幹，年終別問，問了妳會嫌他少。",
        archetype: "perfect",
        retort: "靠北，你嘴巴留點口德。",
      },
      {
        id: "sanjiuma-salary_job-012-b",
        text: "笑死，舅媽這麼想知道要理財？",
        archetype: "deflect",
        retort: "理財？你自己存好嗎？",
      },
      {
        id: "sanjiuma-salary_job-012-c",
        text: "靠，表哥年終多少，拿來當目標。",
        archetype: "deflect",
        retort: "目標是好事，你要加油。",
      },
      {
        id: "sanjiuma-salary_job-012-d",
        text: "幹……沒多少，公司說業績普通……",
        archetype: "meek",
        retort: "沒多少是多少？說清楚。",
      },
      {
        id: "sanjiuma-salary_job-012-e",
        text: "大概一個月薪水，扣稅更少……",
        archetype: "meek",
        retort: "扣稅後多少？你要說明白。",
      },
      {
        id: "sanjiuma-salary_job-012-f",
        text: "我他媽年終是家人的愛，無價。",
        archetype: "backfire",
        retort: "……（舅媽看向表哥，表哥低頭滑手機）",
      },
      {
        id: "sanjiuma-salary_job-012-g",
        text: "年終不重要，重要明年更努力。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-012-h",
        text: "幹你娘，他年終還不是老不死簽的？",
        archetype: "landmine",
        retort: "幹！叫你媽出來！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-013",
    text: "要不要考公職？穩定，表哥都羨慕。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-013-a",
        text: "靠北，公職穩，但沒靠山那麼穩。",
        archetype: "perfect",
        retort: "他媽的，你亂講什麼東西！",
      },
      {
        id: "sanjiuma-salary_job-013-b",
        text: "笑死，舅媽這麼推薦有內幕？",
        archetype: "deflect",
        retort: "內部消息？你自己去查。",
      },
      {
        id: "sanjiuma-salary_job-013-c",
        text: "靠，考公職好，陪我去考？",
        archetype: "deflect",
        retort: "我這把年紀了，你自己考。",
      },
      {
        id: "sanjiuma-salary_job-013-d",
        text: "幹……有想過，但覺得考試很難……",
        archetype: "meek",
        retort: "難？到底有沒有去準備？",
      },
      {
        id: "sanjiuma-salary_job-013-e",
        text: "還在猶豫，怕考不上浪費時間……",
        archetype: "meek",
        retort: "猶豫什麼，時間不等人。",
      },
      {
        id: "sanjiuma-salary_job-013-f",
        text: "我他媽天生穩定型，不用考試。",
        archetype: "backfire",
        retort: "……（沒人聽懂，繼續吃飯）",
      },
      {
        id: "sanjiuma-salary_job-013-g",
        text: "公職太無聊，幹，我要自由靈魂。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-013-h",
        text: "機掰，考公職跟靠舅舅安插不一樣。",
        archetype: "landmine",
        retort: "明年不用他媽的來了！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-014",
    text: "你幾點下班？常常加班嗎？別累壞了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-014-a",
        text: "他媽的，準時下班不用誰施捨。",
        archetype: "perfect",
        retort: "（氣到講台語）幹恁娘咧",
      },
      {
        id: "sanjiuma-salary_job-014-b",
        text: "笑死，舅媽關心煮飯補補身體？",
        archetype: "deflect",
        retort: "好啦好啦，下次來吃飯。",
      },
      {
        id: "sanjiuma-salary_job-014-c",
        text: "靠，表哥常加班要多注意身體？",
        archetype: "deflect",
        retort: "他身體好得很，別擔心。",
      },
      {
        id: "sanjiuma-salary_job-014-d",
        text: "幹……常常九點多才下班，有點累……",
        archetype: "meek",
        retort: "九點？薪水有比較多嗎？",
      },
      {
        id: "sanjiuma-salary_job-014-e",
        text: "看案子啦，忙的時候到很晚……",
        archetype: "meek",
        retort: "很晚是幾點，你要說清楚。",
      },
      {
        id: "sanjiuma-salary_job-014-f",
        text: "下班時間他媽是相對的，活在當下。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-014-g",
        text: "我把加班當修行，越晚越開悟。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-014-h",
        text: "幹，問下班時間，老東西查得比公司勤。",
        archetype: "landmine",
        retort: "幹恁娘，你很沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-015",
    text: "有沒有買保險？表哥保單一堆，很有計畫。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-015-a",
        text: "去死啦，先不買怕搶妳兒子業績。",
        archetype: "perfect",
        retort: "幹，你是不是欠揍啊。",
      },
      {
        id: "sanjiuma-salary_job-015-b",
        text: "笑死，舅媽這麼專業幫我規劃？",
        archetype: "deflect",
        retort: "這個要找專業的，不是我。",
      },
      {
        id: "sanjiuma-salary_job-015-c",
        text: "靠，表哥保單那麼多是妳業績？",
        archetype: "deflect",
        retort: "少亂講，那是他自己買的。",
      },
      {
        id: "sanjiuma-salary_job-015-d",
        text: "幹……有買一點基本的醫療險……",
        archetype: "meek",
        retort: "基本的夠嗎？你要再加保。",
      },
      {
        id: "sanjiuma-salary_job-015-e",
        text: "還沒買，一直想說再等等……",
        archetype: "meek",
        retort: "等等？出事怎麼辦，快去買。",
      },
      {
        id: "sanjiuma-salary_job-015-f",
        text: "我他媽最大的保險是樂觀心態。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-015-g",
        text: "保險太貴，我靠信念保平安。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-015-h",
        text: "他媽的，他保單那麼多不就妳業績？",
        archetype: "landmine",
        retort: "你他媽的欠教訓，滾！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-016",
    text: "你月薪養得起自己嗎？別打腫臉充胖子。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-016-a",
        text: "機掰，養得起，不用靠誰養活。",
        archetype: "perfect",
        retort: "他媽的沒大沒小，欠罵是不是。",
      },
      {
        id: "sanjiuma-salary_job-016-b",
        text: "笑死，舅媽關心要包紅包補貼？",
        archetype: "deflect",
        retort: "紅包紅包，你只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-016-c",
        text: "靠，養得起啦，別擔心吃飽睡好。",
        archetype: "deflect",
        retort: "吃飽就好？你要存錢啊。",
      },
      {
        id: "sanjiuma-salary_job-016-d",
        text: "幹……勉強養得起，月底很緊……",
        archetype: "meek",
        retort: "緊到什麼程度？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-016-e",
        text: "有時候要靠信用卡撐一下……",
        archetype: "meek",
        retort: "刷卡？欠多少說清楚。",
      },
      {
        id: "sanjiuma-salary_job-016-f",
        text: "我他媽養的是靈魂不是肉體。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-016-g",
        text: "錢夠不夠不重要，快樂重要。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-016-h",
        text: "去你的，至少不是靠老太婆公司養活。",
        archetype: "landmine",
        retort: "去你的，我養你這麼大！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-017",
    text: "有沒有接案賺外快？表哥副業也做很大。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-017-a",
        text: "去死啦，接案靠實力，表哥呢？",
        archetype: "perfect",
        retort: "幹，你翅膀硬了是不是。",
      },
      {
        id: "sanjiuma-salary_job-017-b",
        text: "笑死，舅媽有案子幫忙介紹？",
        archetype: "deflect",
        retort: "介紹？我哪有那種門路。",
      },
      {
        id: "sanjiuma-salary_job-017-c",
        text: "靠，表哥副業做什麼教教我？",
        archetype: "deflect",
        retort: "問表哥幹嘛，自己去問他。",
      },
      {
        id: "sanjiuma-salary_job-017-d",
        text: "幹……有接一點小案子，賺不多……",
        archetype: "meek",
        retort: "不多是多少？說清楚點。",
      },
      {
        id: "sanjiuma-salary_job-017-e",
        text: "想接但沒時間，本業快忙死……",
        archetype: "meek",
        retort: "忙死了？薪水有比較多？",
      },
      {
        id: "sanjiuma-salary_job-017-f",
        text: "我他媽副業是散播快樂不收費。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-017-g",
        text: "外快太俗氣，我專注內心成長。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-017-h",
        text: "機掰，他副業那麼大是不是妳牽線？",
        archetype: "landmine",
        retort: "幹，你這什麼死樣子！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-018",
    text: "公司有沒有分紅？表哥公司股票分很多。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-018-a",
        text: "幹你娘，沒分紅但沒人堵我的嘴。",
        archetype: "perfect",
        retort: "他媽的沒大沒小，欠罵是不是。",
      },
      {
        id: "sanjiuma-salary_job-018-b",
        text: "笑死，舅媽這麼懂投資我們公司？",
        archetype: "deflect",
        retort: "投資？你先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-018-c",
        text: "靠，表哥分紅那麼多分我一點？",
        archetype: "deflect",
        retort: "分你？你自己去賺啦。",
      },
      {
        id: "sanjiuma-salary_job-018-d",
        text: "幹……沒有分紅，公司說沒賺錢……",
        archetype: "meek",
        retort: "沒賺錢？薪水穩不穩？",
      },
      {
        id: "sanjiuma-salary_job-018-e",
        text: "有一點點，但少到可以忽略……",
        archetype: "meek",
        retort: "少到多少？說個數字給我。",
      },
      {
        id: "sanjiuma-salary_job-018-f",
        text: "我他媽把分紅換成內心富足。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-018-g",
        text: "分紅太複雜，我只信任緣分。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-018-h",
        text: "去死，他分紅那麼多是死老太婆塞的？",
        archetype: "landmine",
        retort: "他媽的，白眼狼是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-019",
    text: "你手機跳薪轉通知，舅媽瞄到囉，多少？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-019-a",
        text: "幹恁娘，偷看別人手機是查勤？",
        archetype: "perfect",
        retort: "（氣到講台語）幹恁娘咧",
      },
      {
        id: "sanjiuma-salary_job-019-b",
        text: "笑死，舅媽偷看要罰紅包一個。",
        archetype: "deflect",
        retort: "偷看什麼，我不小心的。",
      },
      {
        id: "sanjiuma-salary_job-019-c",
        text: "靠，舅媽視力真好，陪我驗光？",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-salary_job-019-d",
        text: "幹……那個是薪水沒錯，不多啦……",
        archetype: "meek",
        retort: "不多是多少？說清楚點。",
      },
      {
        id: "sanjiuma-salary_job-019-e",
        text: "被看到了……扣完稅沒多少……",
        archetype: "meek",
        retort: "剩多少？你要老實講清楚。",
      },
      {
        id: "sanjiuma-salary_job-019-f",
        text: "那他媽不是薪水，是心靈存款。",
        archetype: "backfire",
        retort: "……（舅媽瞇眼，不太相信）",
      },
      {
        id: "sanjiuma-salary_job-019-g",
        text: "手機借我看，妳眼花了吧。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-019-h",
        text: "幹你娘，妳愛看別人手機管太多了。",
        archetype: "landmine",
        retort: "……（舅媽氣到，罵了聲幹）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-020",
    text: "以後結婚能養家嗎？表哥都準備好了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-020-a",
        text: "他媽的，養家靠實力不是塞紅包。",
        archetype: "perfect",
        retort: "他媽的，含糊帶過算了。",
      },
      {
        id: "sanjiuma-salary_job-020-b",
        text: "笑死，舅媽關心先幫我介紹對象？",
        archetype: "deflect",
        retort: "介紹？你先把自己顧好。",
      },
      {
        id: "sanjiuma-salary_job-020-c",
        text: "靠，表哥準備得怎樣，參考一下？",
        archetype: "deflect",
        retort: "問表哥幹嘛，自己去努力。",
      },
      {
        id: "sanjiuma-salary_job-020-d",
        text: "幹……應該可以吧，存款還不太夠……",
        archetype: "meek",
        retort: "不夠是差多少？說清楚。",
      },
      {
        id: "sanjiuma-salary_job-020-e",
        text: "還在努力存錢，暫時沒把握……",
        archetype: "meek",
        retort: "沒把握？打算什麼時候有？",
      },
      {
        id: "sanjiuma-salary_job-020-f",
        text: "養家靠他媽的是愛，不是數字。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-020-g",
        text: "我打算讓對方養我，比較浪漫。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-020-h",
        text: "去死，反正不是靠老不死塞紅包養家。",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-021",
    text: "工作幾年了？薪水漲了多少？算給我聽。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-021-a",
        text: "機掰，妳問漲幅是想比較而已？",
        archetype: "perfect",
        retort: "去你的，你很欠教訓。",
      },
      {
        id: "sanjiuma-salary_job-021-b",
        text: "笑死，舅媽記性真好，連這都算？",
        archetype: "deflect",
        retort: "當然，我什麼都記得清楚。",
      },
      {
        id: "sanjiuma-salary_job-021-c",
        text: "靠，表哥薪水漲多少，當目標。",
        archetype: "deflect",
        retort: "目標是好事，你要加油喔。",
      },
      {
        id: "sanjiuma-salary_job-021-d",
        text: "幹……漲得不多，大概幾千塊……",
        archetype: "meek",
        retort: "幾千塊？那幾年才漲這樣？",
      },
      {
        id: "sanjiuma-salary_job-021-e",
        text: "老實說幾乎沒漲，卡在原地……",
        archetype: "meek",
        retort: "沒漲？那你有沒有去談過？",
      },
      {
        id: "sanjiuma-salary_job-021-f",
        text: "我他媽薪水漲幅是秘密指數。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-021-g",
        text: "薪水沒漲沒關係，經驗值漲多。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-021-h",
        text: "幹，反正不是靠舅舅一句話調薪的。",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
    ],
  },
] satisfies Question[];
