import type { Question } from "@/content/types";

// situations:
// 022 問要不要跳槽薪水會不會更高
// 023 舅媽朋友的小孩起薪比較
// 024 表哥的年薪成長曲線拿出來比
// 025 問三節獎金有沒有
// 026 問颱風假會不會扣薪水
// 027 問有沒有在做投資理財
// 028 問信用卡額度多少
// 029 問薪轉戶頭餘額
// 030 問有沒有做外送兼職
// 031 問畢業起薪跟現在比
// 032 問換工作次數太多是不是薪水亂
// 033 問產業別是不是薪水天生比較低
// 034 問是不是靠死薪水過活
// 035 問尾牙有沒有抽到獎金
// 036 問有沒有報稅退稅多少
// 037 舅媽朋友的小孩薪水更高來比較

export default [
  {
    id: "sanjiuma-salary_job-022",
    text: "要不要跳槽？聽說外面薪水更高。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-022-a",
        text: "幹，跳槽考慮中，妳是怕我走？",
        archetype: "perfect",
        retort: "靠北，你嘴巴留點口德。",
      },
      {
        id: "sanjiuma-salary_job-022-b",
        text: "笑死，舅媽有內線哪家薪水高？",
        archetype: "deflect",
        retort: "內線？我上哪知道去。",
      },
      {
        id: "sanjiuma-salary_job-022-c",
        text: "靠，表哥要不要也跳槽比較賺？",
        archetype: "deflect",
        retort: "他好好的跳什麼槽。",
      },
      {
        id: "sanjiuma-salary_job-022-d",
        text: "幹……有在考慮，怕新工作不穩……",
        archetype: "meek",
        retort: "不穩定？到底想清楚沒？",
      },
      {
        id: "sanjiuma-salary_job-022-e",
        text: "投了幾封履歷，還沒下文……",
        archetype: "meek",
        retort: "沒下文？要不要再改改？",
      },
      {
        id: "sanjiuma-salary_job-022-f",
        text: "我他媽在等宇宙給訊號。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-022-g",
        text: "跳槽太麻煩，他媽的選擇躺平。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-022-h",
        text: "他媽的，反正不是誰都能靠老東西安排工作。",
        archetype: "landmine",
        retort: "幹！叫你媽出來！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-023",
    text: "我朋友的小孩起薪四萬五，你呢？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-023-a",
        text: "幹，起薪四萬五跟本事有關嗎？",
        archetype: "perfect",
        retort: "他媽的，你亂講什麼東西！",
      },
      {
        id: "sanjiuma-salary_job-023-b",
        text: "笑死，舅媽朋友小孩好厲害？",
        archetype: "deflect",
        retort: "認識幹嘛，你先顧好自己。",
      },
      {
        id: "sanjiuma-salary_job-023-c",
        text: "靠，四萬五好強，什麼行業啊？",
        archetype: "deflect",
        retort: "問這個幹嘛，自己去比較。",
      },
      {
        id: "sanjiuma-salary_job-023-d",
        text: "幹……我起薪三萬二，比較低……",
        archetype: "meek",
        retort: "三萬二？那現在漲多少？",
      },
      {
        id: "sanjiuma-salary_job-023-e",
        text: "沒那麼高啦，普通行情而已……",
        archetype: "meek",
        retort: "普通行情是多少，說清楚。",
      },
      {
        id: "sanjiuma-salary_job-023-f",
        text: "起薪不重要，他媽的我很有型。",
        archetype: "backfire",
        retort: "……（冷場，表哥猛扒飯）",
      },
      {
        id: "sanjiuma-salary_job-023-g",
        text: "薪水是數字，我追求的是境界。",
        archetype: "backfire",
        retort: "……（舅媽皺眉，聽不懂裝懂）",
      },
      {
        id: "sanjiuma-salary_job-023-h",
        text: "幹你娘，那小孩起薪高是不是靠關係？",
        archetype: "landmine",
        retort: "明年不用他媽的來了！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-024",
    text: "表哥年薪五年翻三倍，你的曲線呢？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-024-a",
        text: "幹，翻三倍是能力還是姓對了？",
        archetype: "perfect",
        retort: "（氣到講台語）幹恁娘咧",
      },
      {
        id: "sanjiuma-salary_job-024-b",
        text: "笑死，表哥曲線漂亮教教我？",
        archetype: "deflect",
        retort: "這個要天分，你慢慢學。",
      },
      {
        id: "sanjiuma-salary_job-024-c",
        text: "靠，舅媽把曲線畫出來當海報？",
        archetype: "deflect",
        retort: "激勵海報？你別鬧了。",
      },
      {
        id: "sanjiuma-salary_job-024-d",
        text: "幹……我的曲線比較平，沒起伏……",
        archetype: "meek",
        retort: "平？到底有沒有在努力？",
      },
      {
        id: "sanjiuma-salary_job-024-e",
        text: "翻不了三倍，能持平就不錯……",
        archetype: "meek",
        retort: "持平？你不會想更好嗎？",
      },
      {
        id: "sanjiuma-salary_job-024-f",
        text: "我他媽曲線是抽象藝術，看不懂。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-024-g",
        text: "數字不重要，重要心靈成長曲線。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-024-h",
        text: "機掰，翻三倍還不是靠老太婆公司卡位？",
        archetype: "landmine",
        retort: "幹恁娘，你很沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-025",
    text: "三節獎金有沒有？表哥公司都給滿。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-025-a",
        text: "幹，三節獎金有，不用靠誰簽名。",
        archetype: "perfect",
        retort: "幹，你是不是欠揍啊。",
      },
      {
        id: "sanjiuma-salary_job-025-b",
        text: "笑死，舅媽關心要幫我包紅包？",
        archetype: "deflect",
        retort: "紅包紅包，你只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-025-c",
        text: "靠，表哥三節領多少當目標。",
        archetype: "deflect",
        retort: "目標是好事，你要加油。",
      },
      {
        id: "sanjiuma-salary_job-025-d",
        text: "幹……有一點，但比公定少很多……",
        archetype: "meek",
        retort: "少多少？你要說明白點。",
      },
      {
        id: "sanjiuma-salary_job-025-e",
        text: "沒有耶，公司說今年沒賺錢……",
        archetype: "meek",
        retort: "沒賺錢？薪水穩不穩？",
      },
      {
        id: "sanjiuma-salary_job-025-f",
        text: "我他媽三節獎金是心意，無法量化。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-025-g",
        text: "獎金不重要，重要團圓的感覺。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-025-h",
        text: "去死，反正不像他獎金是舅舅簽的。",
        archetype: "landmine",
        retort: "你他媽的欠教訓，滾！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-026",
    text: "放颱風假會扣薪水嗎？表哥公司照發。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-026-a",
        text: "幹，照發是佛心，還是怕表哥去哭訴？",
        archetype: "perfect",
        retort: "他媽的沒大沒小，欠罵是不是。",
      },
      {
        id: "sanjiuma-salary_job-026-b",
        text: "笑死，表哥公司照發教我老闆？",
        archetype: "deflect",
        retort: "這個要看老闆佛不佛心。",
      },
      {
        id: "sanjiuma-salary_job-026-c",
        text: "靠，舅媽關心薪水還是安全？",
        archetype: "deflect",
        retort: "當然是安全，薪水其次啦。",
      },
      {
        id: "sanjiuma-salary_job-026-d",
        text: "幹……會扣一半，公司說看情況……",
        archetype: "meek",
        retort: "扣一半？那你划不划算？",
      },
      {
        id: "sanjiuma-salary_job-026-e",
        text: "不確定耶，看老闆心情……",
        archetype: "meek",
        retort: "心情？要不要問清楚？",
      },
      {
        id: "sanjiuma-salary_job-026-f",
        text: "颱風假他媽是老天給的年假。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-026-g",
        text: "扣不扣不重要，重要有沒斷電。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-026-h",
        text: "幹你娘，颱風假還不是死老太婆關說的？",
        archetype: "landmine",
        retort: "去你的，我養你這麼大！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-027",
    text: "有沒有在理財？表哥都買基金定期定額。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-027-a",
        text: "幹，定期定額投資自己，不靠報明牌。",
        archetype: "perfect",
        retort: "幹，你翅膀硬了是不是。",
      },
      {
        id: "sanjiuma-salary_job-027-b",
        text: "笑死，表哥買哪支跟他報明牌？",
        archetype: "deflect",
        retort: "報明牌？先學會存錢。",
      },
      {
        id: "sanjiuma-salary_job-027-c",
        text: "靠，舅媽這麼會理財開課教我？",
        archetype: "deflect",
        retort: "開課？我哪有那個閒工夫。",
      },
      {
        id: "sanjiuma-salary_job-027-d",
        text: "幹……有定期定額一點點，金額很小……",
        archetype: "meek",
        retort: "很小是多少？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-027-e",
        text: "還沒開始，一直說要學沒行動……",
        archetype: "meek",
        retort: "沒行動？錢都花去哪？",
      },
      {
        id: "sanjiuma-salary_job-027-f",
        text: "我他媽投資的是人脈，比基金穩。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-027-g",
        text: "理財太複雜，我專心投資快樂。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-027-h",
        text: "他媽的，他買的基金是不是舅舅塞的？",
        archetype: "landmine",
        retort: "幹，你這什麼死樣子！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-028",
    text: "信用卡額度多少？表哥額度都破百萬。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-028-a",
        text: "幹，額度不高，沒靠誰打電話關說。",
        archetype: "perfect",
        retort: "靠杯，你是不是欠罵啊。",
      },
      {
        id: "sanjiuma-salary_job-028-b",
        text: "笑死，舅媽問這個要提高額度？",
        archetype: "deflect",
        retort: "提高額度？自己去銀行問。",
      },
      {
        id: "sanjiuma-salary_job-028-c",
        text: "靠，表哥額度破百萬，妳擔保的？",
        archetype: "deflect",
        retort: "少亂講，那是他自己申請。",
      },
      {
        id: "sanjiuma-salary_job-028-d",
        text: "幹……沒多高啦，就基本額度而已……",
        archetype: "meek",
        retort: "基本是多少？說清楚點。",
      },
      {
        id: "sanjiuma-salary_job-028-e",
        text: "額度是有，但都刷到快滿了……",
        archetype: "meek",
        retort: "刷滿了？那你要怎麼還？",
      },
      {
        id: "sanjiuma-salary_job-028-f",
        text: "我他媽的額度是信任，無上限。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-028-g",
        text: "額度不重要，重要刷卡的手感。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-028-h",
        text: "幹，破百萬額度是不是老不死關說的？",
        archetype: "landmine",
        retort: "他媽的，白眼狼是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-029",
    text: "薪轉戶頭餘額多少？別跟我裝窮。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-029-a",
        text: "幹，餘額多少，妳問這個想借錢？",
        archetype: "perfect",
        retort: "幹，你這孩子嘴巴怎麼賤。",
      },
      {
        id: "sanjiuma-salary_job-029-b",
        text: "笑死，舅媽想知道要幫我補貼？",
        archetype: "deflect",
        retort: "補貼？你自己去努力賺啦。",
      },
      {
        id: "sanjiuma-salary_job-029-c",
        text: "靠，舅媽要不要看我存摺封面？",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-salary_job-029-d",
        text: "幹……剩沒多少，月初就快花光了……",
        archetype: "meek",
        retort: "花光了？花去哪了說清楚。",
      },
      {
        id: "sanjiuma-salary_job-029-e",
        text: "餘額三位數，撐到月底而已……",
        archetype: "meek",
        retort: "三位數？那你要怎麼過？",
      },
      {
        id: "sanjiuma-salary_job-029-f",
        text: "餘額他媽是隱私，跟身分證一樣。",
        archetype: "backfire",
        retort: "……（舅媽瞇眼，不太相信）",
      },
      {
        id: "sanjiuma-salary_job-029-g",
        text: "戶頭餘額是心靈富足的倒影。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-029-h",
        text: "他媽的，妳自己戶頭是不是也沒剩多少？",
        archetype: "landmine",
        retort: "他媽的，白眼狼是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-030",
    text: "有沒有兼職送外送？補貼一下家用。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-030-a",
        text: "幹，兼職外送總比靠關係拿閒差。",
        archetype: "perfect",
        retort: "他媽的，含糊帶過算了。",
      },
      {
        id: "sanjiuma-salary_job-030-b",
        text: "笑死，舅媽關心要幫我叫幾單？",
        archetype: "deflect",
        retort: "叫幾單？我哪知道怎麼叫。",
      },
      {
        id: "sanjiuma-salary_job-030-c",
        text: "靠，表哥要不要來體驗外送生活？",
        archetype: "deflect",
        retort: "他哪有空做那個，別鬧。",
      },
      {
        id: "sanjiuma-salary_job-030-d",
        text: "幹……有接一點，補貼交通費而已……",
        archetype: "meek",
        retort: "補貼多少？你要說清楚點。",
      },
      {
        id: "sanjiuma-salary_job-030-e",
        text: "偶爾接，賺的錢很少……",
        archetype: "meek",
        retort: "很少是多少？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-030-f",
        text: "外送他媽是我體驗人生百態。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-030-g",
        text: "兼職不重要，重要路上的風景。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-030-h",
        text: "去你的，至少不是靠老東西塞的閒差。",
        archetype: "landmine",
        retort: "……（舅媽氣到，罵了聲幹）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-031",
    text: "畢業起薪跟現在比，漲了多少？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-031-a",
        text: "幹，漲了不少，跟他升職靠誰無關。",
        archetype: "perfect",
        retort: "去你的，你很欠教訓。",
      },
      {
        id: "sanjiuma-salary_job-031-b",
        text: "笑死，舅媽連畢業起薪都記得？",
        archetype: "deflect",
        retort: "當然，你的事我都關心。",
      },
      {
        id: "sanjiuma-salary_job-031-c",
        text: "靠，表哥畢業起薪多少比較一下？",
        archetype: "deflect",
        retort: "問表哥幹嘛，問你自己。",
      },
      {
        id: "sanjiuma-salary_job-031-d",
        text: "幹……漲了幾千塊，速度不算快……",
        archetype: "meek",
        retort: "幾千塊？那幾年才漲這樣？",
      },
      {
        id: "sanjiuma-salary_job-031-e",
        text: "老實說差不多，幾乎沒漲……",
        archetype: "meek",
        retort: "沒漲？那你有沒有去談過？",
      },
      {
        id: "sanjiuma-salary_job-031-f",
        text: "起薪現在都他媽是機密，不能說。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-031-g",
        text: "薪水漲幅是我內心的秘密花園。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-031-h",
        text: "機掰，反正不是靠舅舅一句話調上去。",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-032",
    text: "換那麼多工作，薪水是不是很亂？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-032-a",
        text: "幹，換工作是自己找的，不是誰塞的。",
        archetype: "perfect",
        retort: "他媽的，你亂講什麼東西！",
      },
      {
        id: "sanjiuma-salary_job-032-b",
        text: "笑死，舅媽關心職涯當我顧問？",
        archetype: "deflect",
        retort: "顧問？我可沒那個本事。",
      },
      {
        id: "sanjiuma-salary_job-032-c",
        text: "靠，表哥沒換過工作是很穩定？",
        archetype: "deflect",
        retort: "他當然穩，公司自家人開的。",
      },
      {
        id: "sanjiuma-salary_job-032-d",
        text: "幹……換了三次，每次都想找更好……",
        archetype: "meek",
        retort: "更好？那到底有沒有更好？",
      },
      {
        id: "sanjiuma-salary_job-032-e",
        text: "換來換去，薪水好像沒差多少……",
        archetype: "meek",
        retort: "沒差？那你換什麼換？",
      },
      {
        id: "sanjiuma-salary_job-032-f",
        text: "換工作他媽是我人生探索之旅。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-032-g",
        text: "次數不重要，重要每次有故事。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-032-h",
        text: "去死，至少每次都自己找不是老太婆關說。",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-033",
    text: "你這行業是不是天生薪水就比較低？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-033-a",
        text: "幹，這行薪水低，但沒靠誰公司卡位。",
        archetype: "perfect",
        retort: "幹！叫你媽出來！",
      },
      {
        id: "sanjiuma-salary_job-033-b",
        text: "笑死，舅媽懂產業行情幫我轉職？",
        archetype: "deflect",
        retort: "轉職？你自己要有本事。",
      },
      {
        id: "sanjiuma-salary_job-033-c",
        text: "靠，表哥那行薪水高，引薦我？",
        archetype: "deflect",
        retort: "引薦？你先把自己顧好。",
      },
      {
        id: "sanjiuma-salary_job-033-d",
        text: "幹……這行業確實比較低薪，沒辦法……",
        archetype: "meek",
        retort: "沒辦法？要不要轉行？",
      },
      {
        id: "sanjiuma-salary_job-033-e",
        text: "行情就是這樣，大家都差不多……",
        archetype: "meek",
        retort: "差不多是多少，你說清楚。",
      },
      {
        id: "sanjiuma-salary_job-033-f",
        text: "薪水低沒關係，他媽的靈魂很富有。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-033-g",
        text: "行業不重要，重要我熱愛工作。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-033-h",
        text: "幹你娘，我這行不是靠舅舅一句話進去。",
        archetype: "landmine",
        retort: "明年不用他媽的來了！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-034",
    text: "你是不是就靠死薪水過活，沒別的？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-034-a",
        text: "幹，死薪水過活，總比靠家裡養光榮。",
        archetype: "perfect",
        retort: "（氣到講台語）幹恁娘咧",
      },
      {
        id: "sanjiuma-salary_job-034-b",
        text: "笑死，舅媽關心教我怎麼開源？",
        archetype: "deflect",
        retort: "開源？你自己也要努力想。",
      },
      {
        id: "sanjiuma-salary_job-034-c",
        text: "靠，表哥除了死薪水還有什麼？",
        archetype: "deflect",
        retort: "問表哥幹嘛，自己去問他。",
      },
      {
        id: "sanjiuma-salary_job-034-d",
        text: "幹……對，就靠薪水，沒有其他收入……",
        archetype: "meek",
        retort: "沒有？怎麼不多想辦法？",
      },
      {
        id: "sanjiuma-salary_job-034-e",
        text: "是啊，能存的真的不多……",
        archetype: "meek",
        retort: "不多是多少？你要說清楚。",
      },
      {
        id: "sanjiuma-salary_job-034-f",
        text: "我他媽靠的是信念，薪水是配菜。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-034-g",
        text: "死薪水沒關係，我活得很有生命力。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-034-h",
        text: "機掰，至少不是靠死老太婆塞紅包過活。",
        archetype: "landmine",
        retort: "幹恁娘，你很沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-035",
    text: "尾牙有沒有抽到獎金？表哥抽到機車。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-035-a",
        text: "幹，抽到機車是運氣還是早內定？",
        archetype: "perfect",
        retort: "幹，你是不是欠揍啊。",
      },
      {
        id: "sanjiuma-salary_job-035-b",
        text: "笑死，表哥抽到機車載我兜風？",
        archetype: "deflect",
        retort: "他自己都沒空，你想什麼。",
      },
      {
        id: "sanjiuma-salary_job-035-c",
        text: "靠，舅媽尾牙有抽到跟我分享？",
        archetype: "deflect",
        retort: "我哪有去，都在家等你們。",
      },
      {
        id: "sanjiuma-salary_job-035-d",
        text: "幹……沒抽到，只抽到一包衛生紙……",
        archetype: "meek",
        retort: "衛生紙？運氣多差啦？",
      },
      {
        id: "sanjiuma-salary_job-035-e",
        text: "我們公司尾牙沒抽獎，運氣不好……",
        archetype: "meek",
        retort: "沒抽獎？那薪水有比較多？",
      },
      {
        id: "sanjiuma-salary_job-035-f",
        text: "我他媽把自己抽成年度最佳員工。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-035-g",
        text: "抽獎不重要，重要尾牙的雞腿。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-035-h",
        text: "幹，抽到機車是不是早就內定好的？",
        archetype: "landmine",
        retort: "幹恁娘，你很沒大沒小！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-036",
    text: "報稅退了多少？表哥退稅退很多喔。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-036-a",
        text: "幹，退稅多是薪水高還是報表會編？",
        archetype: "perfect",
        retort: "他媽的沒大沒小，欠罵是不是。",
      },
      {
        id: "sanjiuma-salary_job-036-b",
        text: "笑死，舅媽這麼懂節稅教教我？",
        archetype: "deflect",
        retort: "這個要慢慢學，你要耐心。",
      },
      {
        id: "sanjiuma-salary_job-036-c",
        text: "靠，表哥退那麼多有做扣除額？",
        archetype: "deflect",
        retort: "問表哥幹嘛，自己去查。",
      },
      {
        id: "sanjiuma-salary_job-036-d",
        text: "幹……沒退多少，只有幾百塊而已……",
        archetype: "meek",
        retort: "幾百塊？那你薪水到底多少？",
      },
      {
        id: "sanjiuma-salary_job-036-e",
        text: "反而要補稅，扣了一大筆……",
        archetype: "meek",
        retort: "補稅？那你到底賺多少？",
      },
      {
        id: "sanjiuma-salary_job-036-f",
        text: "退稅他媽是國家給的紅包，開心。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-036-g",
        text: "退多退少不重要，報完就輕鬆。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-036-h",
        text: "他媽的，他退那麼多老不死是不是動手腳？",
        archetype: "landmine",
        retort: "你他媽的欠教訓，滾！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-037",
    text: "我朋友的小孩月薪八萬，你差好多。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-037-a",
        text: "幹，月薪八萬是本事還是靠關係？",
        archetype: "perfect",
        retort: "幹，你翅膀硬了是不是。",
      },
      {
        id: "sanjiuma-salary_job-037-b",
        text: "笑死，舅媽朋友小孩做什麼的？",
        archetype: "deflect",
        retort: "問這個幹嘛，你自己去比。",
      },
      {
        id: "sanjiuma-salary_job-037-c",
        text: "靠，八萬好強，介紹給我媽認識？",
        archetype: "deflect",
        retort: "認識幹嘛，你先顧好自己。",
      },
      {
        id: "sanjiuma-salary_job-037-d",
        text: "幹……我沒有那麼多，差了快一半……",
        archetype: "meek",
        retort: "差一半？那你要怎麼追上？",
      },
      {
        id: "sanjiuma-salary_job-037-e",
        text: "沒辦法比，人家可能運氣好……",
        archetype: "meek",
        retort: "運氣？那你自己有沒有努力？",
      },
      {
        id: "sanjiuma-salary_job-037-f",
        text: "薪水他媽不重要，重要我很快樂。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-037-g",
        text: "八萬算什麼，我的夢想是無價的。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-037-h",
        text: "去你的，那小孩月薪八萬是不是也靠關係？",
        archetype: "landmine",
        retort: "夠了！你他媽怎麼這樣講話！",
      },
    ],
  },
] satisfies Question[];
