import type { Question } from "@/content/types";

// situations:
// 002 轉桌問薪水一年調整多少
// 003 舅媽翻名片問公司名字
// 004 算年終幾個月
// 005 問加班費有沒有
// 006 問有沒有繳勞退自提
// 007 問有沒有在買股票
// 008 問存款有多少
// 009 問公司幾個人是不是小公司
// 010 問薪水有沒有跟著表哥調
// 011 問試用期轉正了沒
// 012 問年終獎金拿多少
// 013 問要不要考公職求穩定
// 014 問幾點下班常不常加班
// 015 問有沒有買保險
// 016 問月薪養不養得起自己
// 017 問有沒有接案賺外快
// 018 問公司有沒有分紅
// 019 手機跳薪轉通知被舅媽瞄到
// 020 問以後結婚能不能養家
// 021 問工作幾年薪水漲多少

export default [
  {
    id: "sanjiuma-salary_job-002",
    text: "轉桌轉到你，薪水一年調整幅度多少？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-002-a",
        text: "調薪幅度，妳問這個是要幫我加薪嗎？",
        archetype: "perfect",
        retort: "舅媽翻白眼，隨便你怎麼想。",
      },
      {
        id: "sanjiuma-salary_job-002-b",
        text: "舅媽記性真好，我都忘了自己領多少。",
        archetype: "deflect",
        retort: "少來，你心裡清楚得很。",
      },
      {
        id: "sanjiuma-salary_job-002-c",
        text: "舅媽先說表哥調薪多少，我再算給你聽。",
        archetype: "deflect",
        retort: "問表哥幹嘛，問你自己的。",
      },
      {
        id: "sanjiuma-salary_job-002-d",
        text: "沒調整耶，公司說今年不景氣……",
        archetype: "meek",
        retort: "沒調？那你去年是做假的？",
      },
      {
        id: "sanjiuma-salary_job-002-e",
        text: "有調一點，但通膨都吃掉了……",
        archetype: "meek",
        retort: "調多少？說個數字來聽聽。",
      },
      {
        id: "sanjiuma-salary_job-002-f",
        text: "我的薪水是秘密，跟初戀一樣不能說。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-002-g",
        text: "薪水這種小事，我都用信仰過日子。",
        archetype: "backfire",
        retort: "……（表哥低頭滑手機沒接話）",
      },
      {
        id: "sanjiuma-salary_job-002-h",
        text: "妳自己退休領勞保了，還好意思問？",
        archetype: "landmine",
        retort: "你說什麼！我這是關心你！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-003",
    text: "把你名片翻過來，公司叫什麼名字？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-003-a",
        text: "公司名字不重要，重要的是不靠關係進的。",
        archetype: "perfect",
        retort: "……（舅媽把手機螢幕轉暗）",
      },
      {
        id: "sanjiuma-salary_job-003-b",
        text: "舅媽要不要收藏一張？很有紀念價值。",
        archetype: "deflect",
        retort: "少來，你話題轉得真快。",
      },
      {
        id: "sanjiuma-salary_job-003-c",
        text: "舅媽問這個，是不是想介紹客戶給我？",
        archetype: "deflect",
        retort: "介紹客戶？你先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-003-d",
        text: "小公司啦，沒什麼名氣……",
        archetype: "meek",
        retort: "小公司？做什麼的，說清楚。",
      },
      {
        id: "sanjiuma-salary_job-003-e",
        text: "就一般貿易公司，不大……",
        archetype: "meek",
        retort: "不大？那你薪水夠用嗎？",
      },
      {
        id: "sanjiuma-salary_job-003-f",
        text: "我公司名字是機密，跟007一樣。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-003-g",
        text: "我在幕後工作，不方便透露太多。",
        archetype: "backfire",
        retort: "……（表哥在旁邊尷尬地笑）",
      },
      {
        id: "sanjiuma-salary_job-003-h",
        text: "反正不像舅舅那種靠關係養的公司。",
        archetype: "landmine",
        retort: "你嘛卡差不多咧！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-004",
    text: "年終領幾個月？表哥今年領六個月喔。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-004-a",
        text: "六個月，是他厲害，還是舅舅公司自己人？",
        archetype: "perfect",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-004-b",
        text: "舅媽記性真好，數字記得比我媽還清楚。",
        archetype: "deflect",
        retort: "哎唷，這個要留意才知道啦。",
      },
      {
        id: "sanjiuma-salary_job-004-c",
        text: "表哥領六個月，是不是要包紅包分我？",
        archetype: "deflect",
        retort: "紅包紅包，你就只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-004-d",
        text: "我大概一個月吧，公司不景氣……",
        archetype: "meek",
        retort: "一個月？那年終算白拿的？",
      },
      {
        id: "sanjiuma-salary_job-004-e",
        text: "沒有耶，今年公司說不發……",
        archetype: "meek",
        retort: "不發？那你有沒有去問清楚？",
      },
      {
        id: "sanjiuma-salary_job-004-f",
        text: "我領的是快樂，快樂無價。",
        archetype: "backfire",
        retort: "……（舅媽看向表哥，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-004-g",
        text: "年終不重要，重要的是心意。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-004-h",
        text: "六個月年終，是不是在舅舅公司才有？",
        archetype: "landmine",
        retort: "……（舅媽氣到說起台語罵人）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-005",
    text: "加班有沒有加班費？表哥公司都有算。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-005-a",
        text: "沒加班費，所以我很少加班，妳兒子呢？",
        archetype: "perfect",
        retort: "……（舅媽轉頭找別桌講話）",
      },
      {
        id: "sanjiuma-salary_job-005-b",
        text: "舅媽這麼關心，要不要幫我去跟老闆說？",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-salary_job-005-c",
        text: "表哥公司福利真好，改天教教我媽。",
        archetype: "deflect",
        retort: "這個要看公司啦，不是每間都有。",
      },
      {
        id: "sanjiuma-salary_job-005-d",
        text: "沒有耶，公司說責任制沒加班費……",
        archetype: "meek",
        retort: "責任制？那你一個月加多久？",
      },
      {
        id: "sanjiuma-salary_job-005-e",
        text: "有一點點，但很少加班到很晚……",
        archetype: "meek",
        retort: "很晚是幾點，說清楚一點。",
      },
      {
        id: "sanjiuma-salary_job-005-f",
        text: "我把加班費換算成人生經驗值。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-005-g",
        text: "沒加班費沒關係，我心中自有時薪。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-005-h",
        text: "妳兒子加班費多少，妳比我還清楚吧？",
        archetype: "landmine",
        retort: "你這孩子，白養你這麼多年！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-006",
    text: "勞退有沒有自提？以後退休才夠用。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-006-a",
        text: "自提退休金，總比靠兒子養老實在。",
        archetype: "perfect",
        retort: "……舅媽臉一僵，說你亂講。",
      },
      {
        id: "sanjiuma-salary_job-006-b",
        text: "舅媽對退休這麼有研究，要不要教教我？",
        archetype: "deflect",
        retort: "這個要早準備，你要聽好。",
      },
      {
        id: "sanjiuma-salary_job-006-c",
        text: "舅媽退休金規劃得怎麼樣？分享一下嘛。",
        archetype: "deflect",
        retort: "問我幹嘛，問你自己的。",
      },
      {
        id: "sanjiuma-salary_job-006-d",
        text: "有自提一點點，但存不了太多……",
        archetype: "meek",
        retort: "一點點是多少？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-006-e",
        text: "還沒開始想退休這件事……",
        archetype: "meek",
        retort: "不想？那你老了怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-006-f",
        text: "退休這種事，交給緣分就好。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-006-g",
        text: "我打算工作到死，不用退休金。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-006-h",
        text: "妳退休金領那麼多，還好意思問我？",
        archetype: "landmine",
        retort: "你說什麼！我這是關心你！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-007",
    text: "有沒有在買股票？表哥都買到賺翻了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-007-a",
        text: "有買股票，妳問這個是想抽成嗎？",
        archetype: "perfect",
        retort: "……（舅媽沒接話，喝茶壓驚）",
      },
      {
        id: "sanjiuma-salary_job-007-b",
        text: "舅媽這麼會理財，要不要開個投資群組？",
        archetype: "deflect",
        retort: "投資群組？你先學會存錢再說。",
      },
      {
        id: "sanjiuma-salary_job-007-c",
        text: "表哥買哪支賺翻的，跟我說一下吧。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己不會研究？",
      },
      {
        id: "sanjiuma-salary_job-007-d",
        text: "有買一點點，但都套在裡面……",
        archetype: "meek",
        retort: "套多少？虧了沒有，說清楚。",
      },
      {
        id: "sanjiuma-salary_job-007-e",
        text: "沒有耶，薪水都不夠存了……",
        archetype: "meek",
        retort: "不夠存？那你都花去哪了？",
      },
      {
        id: "sanjiuma-salary_job-007-f",
        text: "我的投資組合是回憶，通通都賠了。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-007-g",
        text: "股票太麻煩，我都投資自己的快樂。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-007-h",
        text: "妳去年不是才被套牢在那邊哭？",
        archetype: "landmine",
        retort: "……（舅媽瞪著你，眼眶紅了）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-008",
    text: "存款有多少？表哥都存到能買車了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-008-a",
        text: "存款不多，但沒欠誰人情，妳懂嗎？",
        archetype: "perfect",
        retort: "舅媽乾笑兩聲，改扒飯。",
      },
      {
        id: "sanjiuma-salary_job-008-b",
        text: "舅媽這麼關心存款，是要包紅包給我嗎？",
        archetype: "deflect",
        retort: "紅包？你自己不會存喔。",
      },
      {
        id: "sanjiuma-salary_job-008-c",
        text: "舅媽自己存款有多少，要不要先講？",
        archetype: "deflect",
        retort: "問我幹嘛，問你自己的事。",
      },
      {
        id: "sanjiuma-salary_job-008-d",
        text: "存不到十萬，房租吃掉大半……",
        archetype: "meek",
        retort: "十萬都不到？那你要怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-008-e",
        text: "沒剩多少，月光族一個……",
        archetype: "meek",
        retort: "月光？那你打算什麼時候存？",
      },
      {
        id: "sanjiuma-salary_job-008-f",
        text: "我把存款都投資在快樂上了。",
        archetype: "backfire",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-salary_job-008-g",
        text: "存款這種東西，我早就佛系了。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-008-h",
        text: "妳的存款，不是都被他拿去周轉？",
        archetype: "landmine",
        retort: "你信不信我現在就打電話問他！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-009",
    text: "你們公司幾個人？該不會很小間吧。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-009-a",
        text: "小公司好，至少同事不是靠關係塞的。",
        archetype: "perfect",
        retort: "……（舅媽轉頭滑手機，沒接話）",
      },
      {
        id: "sanjiuma-salary_job-009-b",
        text: "舅媽問這麼細，是要來我們公司投資嗎？",
        archetype: "deflect",
        retort: "投資？你先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-009-c",
        text: "小歸小，但氣氛好，改天請你來玩。",
        archetype: "deflect",
        retort: "來玩？我還有事，改天啦。",
      },
      {
        id: "sanjiuma-salary_job-009-d",
        text: "十幾個人吧，算蠻小的公司……",
        archetype: "meek",
        retort: "十幾個？那你發展空間夠嗎？",
      },
      {
        id: "sanjiuma-salary_job-009-e",
        text: "不到十個人，很多事都我自己做……",
        archetype: "meek",
        retort: "自己做？那有沒有加薪？",
      },
      {
        id: "sanjiuma-salary_job-009-f",
        text: "人數不重要，重要的是我很重要。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-009-g",
        text: "我們公司雖小，志氣比101還高。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-009-h",
        text: "反正不是靠關係進去的小公司。",
        archetype: "landmine",
        retort: "你這什麼態度！我這是關心他！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-010",
    text: "表哥調薪你有跟著調嗎？同公司體系耶。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-010-a",
        text: "不同公司，我靠自己調薪，妳兒子靠誰？",
        archetype: "perfect",
        retort: "舅媽臉一僵，含糊帶過。",
      },
      {
        id: "sanjiuma-salary_job-010-b",
        text: "舅媽消息真靈通，表哥調薪都知道。",
        archetype: "deflect",
        retort: "當然，我兒子的事我都知道。",
      },
      {
        id: "sanjiuma-salary_job-010-c",
        text: "表哥調薪要不要分我一點喜氣？",
        archetype: "deflect",
        retort: "喜氣？你自己去努力賺啦。",
      },
      {
        id: "sanjiuma-salary_job-010-d",
        text: "沒有耶，我們公司體系不一樣……",
        archetype: "meek",
        retort: "不一樣？那你薪水到底多少？",
      },
      {
        id: "sanjiuma-salary_job-010-e",
        text: "沒跟著調，公司今年凍漲……",
        archetype: "meek",
        retort: "凍漲？那你打算怎麼辦？",
      },
      {
        id: "sanjiuma-salary_job-010-f",
        text: "我的調薪標準是我自己開心就好。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-010-g",
        text: "薪水這種小事，交給宇宙決定。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-010-h",
        text: "他調薪，還不是舅舅點頭就有？",
        archetype: "landmine",
        retort: "你這什麼意思！臉都變了！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-011",
    text: "試用期過了沒？轉正了嗎？表哥早正職了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-011-a",
        text: "轉正靠實力，不是靠一通電話講的。",
        archetype: "perfect",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-011-b",
        text: "舅媽這麼關心，要不要來公司幫我加油？",
        archetype: "deflect",
        retort: "加油？你自己好好表現啦。",
      },
      {
        id: "sanjiuma-salary_job-011-c",
        text: "轉正了，舅媽要不要包個開工紅包？",
        archetype: "deflect",
        retort: "紅包紅包，你就只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-011-d",
        text: "剛到新單位，還在摸索狀況……",
        archetype: "meek",
        retort: "緊張什麼，你到底做多久了？",
      },
      {
        id: "sanjiuma-salary_job-011-e",
        text: "延長試用期了，主管說再看看……",
        archetype: "meek",
        retort: "再看看？那你要撐到什麼時候？",
      },
      {
        id: "sanjiuma-salary_job-011-f",
        text: "轉正不重要，我早就內心正職了。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-011-g",
        text: "我把自己轉正成快樂員工。",
        archetype: "backfire",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-salary_job-011-h",
        text: "反正不像他靠舅舅一句話就轉正。",
        archetype: "landmine",
        retort: "……（舅媽臉色一沉，沒再說話）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-012",
    text: "年終獎金拿多少？別藏，說個數字。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-012-a",
        text: "年終數字別問，問了妳會嫌他少。",
        archetype: "perfect",
        retort: "……（舅媽愣住，喝了口茶）",
      },
      {
        id: "sanjiuma-salary_job-012-b",
        text: "舅媽這麼想知道，是不是要幫我理財？",
        archetype: "deflect",
        retort: "理財？你自己存好嗎？",
      },
      {
        id: "sanjiuma-salary_job-012-c",
        text: "表哥年終多少，我拿來當目標努力。",
        archetype: "deflect",
        retort: "目標是好事，你要加油。",
      },
      {
        id: "sanjiuma-salary_job-012-d",
        text: "沒多少，公司說今年業績普通……",
        archetype: "meek",
        retort: "沒多少是多少？說清楚一點。",
      },
      {
        id: "sanjiuma-salary_job-012-e",
        text: "大概一個月薪水，扣稅後更少……",
        archetype: "meek",
        retort: "扣稅後多少？你要說明白。",
      },
      {
        id: "sanjiuma-salary_job-012-f",
        text: "我的年終是家人的愛，無價的。",
        archetype: "backfire",
        retort: "……（舅媽看向表哥，表哥低頭滑手機）",
      },
      {
        id: "sanjiuma-salary_job-012-g",
        text: "年終不重要，重要的是明年更努力。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-012-h",
        text: "反正不像他的年終是舅舅簽的。",
        archetype: "landmine",
        retort: "夠了！你這孩子怎麼這樣講話！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-013",
    text: "要不要考公職？穩定，表哥都羨慕。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-013-a",
        text: "公職穩定，但沒有妳兒子那種靠山穩。",
        archetype: "perfect",
        retort: "舅媽瞪你一眼，改扒飯。",
      },
      {
        id: "sanjiuma-salary_job-013-b",
        text: "舅媽這麼推薦，是不是有內部消息？",
        archetype: "deflect",
        retort: "內部消息？你自己去查啦。",
      },
      {
        id: "sanjiuma-salary_job-013-c",
        text: "考公職好啊，舅媽要不要陪我去考？",
        archetype: "deflect",
        retort: "我都這把年紀了，你自己考。",
      },
      {
        id: "sanjiuma-salary_job-013-d",
        text: "有想過，但覺得考試很難……",
        archetype: "meek",
        retort: "難？那你到底有沒有去準備？",
      },
      {
        id: "sanjiuma-salary_job-013-e",
        text: "還在猶豫，怕考不上浪費時間……",
        archetype: "meek",
        retort: "猶豫什麼，時間不等人的。",
      },
      {
        id: "sanjiuma-salary_job-013-f",
        text: "我天生就是穩定型人格，不用考試。",
        archetype: "backfire",
        retort: "……（沒人聽懂，繼續吃飯）",
      },
      {
        id: "sanjiuma-salary_job-013-g",
        text: "公職太無聊，我要追求自由靈魂。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-013-h",
        text: "考公職？跟靠舅舅安插不一樣好嗎。",
        archetype: "landmine",
        retort: "你嘛卡差不多咧！他是憑實力的！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-014",
    text: "你幾點下班？常常加班嗎？別累壞了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-014-a",
        text: "準時下班，我的時間不用靠誰施捨。",
        archetype: "perfect",
        retort: "……舅媽愣了一下，說你別亂猜。",
      },
      {
        id: "sanjiuma-salary_job-014-b",
        text: "舅媽這麼關心，改天煮飯給我補補身體。",
        archetype: "deflect",
        retort: "好啦好啦，下次來舅媽家吃。",
      },
      {
        id: "sanjiuma-salary_job-014-c",
        text: "表哥常加班嗎？要不要多注意他身體？",
        archetype: "deflect",
        retort: "他身體好得很，你別擔心。",
      },
      {
        id: "sanjiuma-salary_job-014-d",
        text: "常常九點多才下班，有點累……",
        archetype: "meek",
        retort: "九點？那你薪水有比較多嗎？",
      },
      {
        id: "sanjiuma-salary_job-014-e",
        text: "看案子啦，忙的時候會到很晚……",
        archetype: "meek",
        retort: "很晚是幾點，你要說清楚。",
      },
      {
        id: "sanjiuma-salary_job-014-f",
        text: "下班時間是相對的，人生要活在當下。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-014-g",
        text: "我把加班當成修行，越晚越開悟。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-014-h",
        text: "問下班時間，妳查勤查得比公司還勤。",
        archetype: "landmine",
        retort: "你欠教訓是不是，我跟你媽講！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-015",
    text: "有沒有買保險？表哥保單一堆，很有計畫。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-015-a",
        text: "保單先不買，怕買到妳兒子的業績。",
        archetype: "perfect",
        retort: "舅媽哼一聲，你少在那邊會講。",
      },
      {
        id: "sanjiuma-salary_job-015-b",
        text: "舅媽這麼專業，要不要幫我規劃一下？",
        archetype: "deflect",
        retort: "這個要找專業的，不是我。",
      },
      {
        id: "sanjiuma-salary_job-015-c",
        text: "表哥保單那麼多，是不是舅媽業績？",
        archetype: "deflect",
        retort: "少亂講，那是他自己買的。",
      },
      {
        id: "sanjiuma-salary_job-015-d",
        text: "有買一點基本的，醫療險而已……",
        archetype: "meek",
        retort: "基本的夠嗎？你要再加保。",
      },
      {
        id: "sanjiuma-salary_job-015-e",
        text: "還沒買，一直想說再等等……",
        archetype: "meek",
        retort: "等等？出事怎麼辦，快去買。",
      },
      {
        id: "sanjiuma-salary_job-015-f",
        text: "我最大的保險是樂觀的心態。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-015-g",
        text: "保險太貴，我靠信念保平安。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-015-h",
        text: "他保單那麼多，不就是妳的業績？",
        archetype: "landmine",
        retort: "你說什麼！我這是關心他！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-016",
    text: "你月薪養得起自己嗎？別打腫臉充胖子。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-016-a",
        text: "養得起自己，不用靠誰公司養活。",
        archetype: "perfect",
        retort: "舅媽比個「呵呵」，轉頭夾菜。",
      },
      {
        id: "sanjiuma-salary_job-016-b",
        text: "舅媽這麼關心，要不要包紅包補貼我？",
        archetype: "deflect",
        retort: "紅包紅包，你就只想到這個。",
      },
      {
        id: "sanjiuma-salary_job-016-c",
        text: "養得起啦，舅媽別擔心，吃飽睡好。",
        archetype: "deflect",
        retort: "吃飽就好？你要存錢啊。",
      },
      {
        id: "sanjiuma-salary_job-016-d",
        text: "勉強養得起，月底常常很緊……",
        archetype: "meek",
        retort: "緊到什麼程度？說個數字。",
      },
      {
        id: "sanjiuma-salary_job-016-e",
        text: "有時候要靠信用卡撐一下……",
        archetype: "meek",
        retort: "刷卡？那你欠多少，說清楚。",
      },
      {
        id: "sanjiuma-salary_job-016-f",
        text: "我養的是靈魂，不是肉體開銷。",
        archetype: "backfire",
        retort: "……（沒人聽懂，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-016-g",
        text: "錢夠不夠不重要，快樂最重要。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-016-h",
        text: "至少不是靠舅舅公司養活的。",
        archetype: "landmine",
        retort: "……（舅媽摔筷子，全場安靜了）",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-017",
    text: "有沒有接案賺外快？表哥副業也做很大。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-017-a",
        text: "接案賺外快，不用靠誰牽線介紹。",
        archetype: "perfect",
        retort: "舅媽嘴硬：我是為你好而已。",
      },
      {
        id: "sanjiuma-salary_job-017-b",
        text: "舅媽有沒有案子？我可以幫忙介紹一下。",
        archetype: "deflect",
        retort: "介紹？我哪有那種門路。",
      },
      {
        id: "sanjiuma-salary_job-017-c",
        text: "表哥副業做什麼，要不要教教我？",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去問他。",
      },
      {
        id: "sanjiuma-salary_job-017-d",
        text: "有接一點小案子，賺得不多……",
        archetype: "meek",
        retort: "不多是多少？說清楚一點。",
      },
      {
        id: "sanjiuma-salary_job-017-e",
        text: "想接但沒時間，本業就快忙死了……",
        archetype: "meek",
        retort: "忙死了？那你薪水有比較多？",
      },
      {
        id: "sanjiuma-salary_job-017-f",
        text: "我的副業是散播快樂，不收費的。",
        archetype: "backfire",
        retort: "……（舅媽轉頭跟阿姨聊別的了）",
      },
      {
        id: "sanjiuma-salary_job-017-g",
        text: "外快太俗氣，我專注在內心成長。",
        archetype: "backfire",
        retort: "……（表哥假裝在看電視）",
      },
      {
        id: "sanjiuma-salary_job-017-h",
        text: "他副業做那麼大，是不是舅舅牽線？",
        archetype: "landmine",
        retort: "你這孩子是白眼狼是不是！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-018",
    text: "公司有沒有分紅？表哥公司股票分很多。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-018-a",
        text: "沒分紅，但沒人能拿股票堵我的嘴。",
        archetype: "perfect",
        retort: "舅媽拿長輩身分壓：沒大沒小。",
      },
      {
        id: "sanjiuma-salary_job-018-b",
        text: "舅媽這麼懂分紅，要不要投資我們公司？",
        archetype: "deflect",
        retort: "投資？你先做出成績再說。",
      },
      {
        id: "sanjiuma-salary_job-018-c",
        text: "表哥分紅那麼多，要不要分我一點？",
        archetype: "deflect",
        retort: "分你？你自己去賺啦。",
      },
      {
        id: "sanjiuma-salary_job-018-d",
        text: "沒有分紅，公司說今年沒賺錢……",
        archetype: "meek",
        retort: "沒賺錢？那你薪水穩不穩？",
      },
      {
        id: "sanjiuma-salary_job-018-e",
        text: "有一點點，但少到可以忽略……",
        archetype: "meek",
        retort: "少到多少？說個數字給我。",
      },
      {
        id: "sanjiuma-salary_job-018-f",
        text: "我把分紅換成內心的富足感。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-018-g",
        text: "分紅太複雜，我只信任緣分。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-018-h",
        text: "他分紅那麼多，是不是舅舅塞的股票？",
        archetype: "landmine",
        retort: "你說什麼！我跟你講他很爭氣！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-019",
    text: "你手機跳薪轉通知，舅媽瞄到囉，多少？",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-019-a",
        text: "偷看別人手機，是關心還是查勤？",
        archetype: "perfect",
        retort: "……（舅媽對表哥使眼色求救）",
      },
      {
        id: "sanjiuma-salary_job-019-b",
        text: "舅媽偷看喔？那要罰紅包一個。",
        archetype: "deflect",
        retort: "偷看什麼，我不小心的啦。",
      },
      {
        id: "sanjiuma-salary_job-019-c",
        text: "舅媽視力真好，改天陪我去驗光。",
        archetype: "deflect",
        retort: "少貧了，正經回答問題。",
      },
      {
        id: "sanjiuma-salary_job-019-d",
        text: "呃……那個是薪水沒錯，不多啦……",
        archetype: "meek",
        retort: "不多是多少？說清楚一點。",
      },
      {
        id: "sanjiuma-salary_job-019-e",
        text: "被看到了……扣完稅剩沒多少……",
        archetype: "meek",
        retort: "剩多少？你要老實講清楚。",
      },
      {
        id: "sanjiuma-salary_job-019-f",
        text: "那不是薪水，是我的心靈存款。",
        archetype: "backfire",
        retort: "……（舅媽瞇眼，不太相信）",
      },
      {
        id: "sanjiuma-salary_job-019-g",
        text: "手機借我看一下，你眼花了吧。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-019-h",
        text: "妳這麼愛看別人手機，管太多了吧？",
        archetype: "landmine",
        retort: "你這孩子怎麼這樣講話！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-020",
    text: "以後結婚能養家嗎？表哥都準備好了。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-020-a",
        text: "養家靠實力，不是靠誰塞紅包幫忙。",
        archetype: "perfect",
        retort: "舅媽笑僵在臉上，說改天再聊。",
      },
      {
        id: "sanjiuma-salary_job-020-b",
        text: "舅媽這麼關心，要不要先幫我介紹對象？",
        archetype: "deflect",
        retort: "介紹？你先把自己顧好。",
      },
      {
        id: "sanjiuma-salary_job-020-c",
        text: "表哥準備得怎樣，我可以參考一下。",
        archetype: "deflect",
        retort: "問表哥幹嘛，你自己去努力。",
      },
      {
        id: "sanjiuma-salary_job-020-d",
        text: "應該可以吧，但存款還不太夠……",
        archetype: "meek",
        retort: "不夠是差多少？說清楚一點。",
      },
      {
        id: "sanjiuma-salary_job-020-e",
        text: "還在努力存錢，暫時沒把握……",
        archetype: "meek",
        retort: "沒把握？那你打算什麼時候有？",
      },
      {
        id: "sanjiuma-salary_job-020-f",
        text: "養家靠的是愛，不是數字。",
        archetype: "backfire",
        retort: "……（舅媽嘆氣，繼續滑手機）",
      },
      {
        id: "sanjiuma-salary_job-020-g",
        text: "我打算讓對方養我，比較浪漫。",
        archetype: "backfire",
        retort: "……（沒人笑，表哥低頭吃菜）",
      },
      {
        id: "sanjiuma-salary_job-020-h",
        text: "反正不是靠舅舅塞紅包才能養家。",
        archetype: "landmine",
        retort: "你這什麼意思！他自己賺的！",
      },
    ],
  },
  {
    id: "sanjiuma-salary_job-021",
    text: "工作幾年了？薪水漲了多少？算給我聽。",
    topic: "salary_job",
    bossId: "sanjiuma",
    options: [
      {
        id: "sanjiuma-salary_job-021-a",
        text: "薪水漲幅，妳問這個是想比較誰而已？",
        archetype: "perfect",
        retort: "舅媽突然說：菜要涼了，快吃。",
      },
      {
        id: "sanjiuma-salary_job-021-b",
        text: "舅媽記性真好，連這個都要算。",
        archetype: "deflect",
        retort: "當然，我什麼都記得清楚。",
      },
      {
        id: "sanjiuma-salary_job-021-c",
        text: "表哥薪水漲多少，我拿來當目標。",
        archetype: "deflect",
        retort: "目標是好事，你要加油喔。",
      },
      {
        id: "sanjiuma-salary_job-021-d",
        text: "漲得不多，大概幾千塊而已……",
        archetype: "meek",
        retort: "幾千塊？那幾年才漲這樣？",
      },
      {
        id: "sanjiuma-salary_job-021-e",
        text: "老實說幾乎沒漲，卡在原地……",
        archetype: "meek",
        retort: "沒漲？那你有沒有去談過？",
      },
      {
        id: "sanjiuma-salary_job-021-f",
        text: "我的薪水漲幅是秘密指數，機密。",
        archetype: "backfire",
        retort: "……（舅媽沒聽懂，繼續問下去）",
      },
      {
        id: "sanjiuma-salary_job-021-g",
        text: "薪水沒漲沒關係，經驗值漲很多。",
        archetype: "backfire",
        retort: "……（沒人接話，空氣安靜了）",
      },
      {
        id: "sanjiuma-salary_job-021-h",
        text: "反正不是靠舅舅一句話就調薪的。",
        archetype: "landmine",
        retort: "……（舅媽臉色瞬間僵住，說不出話）",
      },
    ],
  },
] satisfies Question[];
