// AUTO-GENERATED by scripts/build-content-index.mjs — do not edit by hand.
// Run `pnpm content:index` after adding or removing question files.
import type { Question } from "@/content/types";
import q0 from "./ama/food_push";
import q1 from "./ama/marriage";
import q2 from "./ama/religion";
import q3 from "./biaojie/kids-1";
import q4 from "./biaojie/kids-2";
import q5 from "./dabo/education-1";
import q6 from "./dabo/education-2";
import q7 from "./dabo/politics-1";
import q8 from "./dabo/politics-2";
import q9 from "./dabo/salary_job-1";
import q10 from "./dabo/salary_job-2";
import q11 from "./generic/housing";
import q12 from "./generic/kids";
import q13 from "./generic/marriage";
import q14 from "./generic/salary_job";
import q15 from "./guzhang/elder_health-1";
import q16 from "./guzhang/elder_health-2";
import q17 from "./guzhang/food_push-1";
import q18 from "./guzhang/food_push-2";
import q19 from "./guzhang/politics-1";
import q20 from "./guzhang/politics-2";
import q21 from "./neighbor-chen/comparison-1";
import q22 from "./neighbor-chen/comparison-2";
import q23 from "./neighbor-chen/marriage-1";
import q24 from "./neighbor-chen/marriage-2";
import q25 from "./neighbor-chen/salary_job-1";
import q26 from "./neighbor-chen/salary_job-2";
import q27 from "./sangu/comparison-1";
import q28 from "./sangu/housing-1";
import q29 from "./sangu/kids-1";
import q30 from "./sangu/marriage-1";
import q31 from "./sangu/salary_job-1";
import q32 from "./sanjiuma/comparison";
import q33 from "./sanjiuma/housing-1";
import q34 from "./sanjiuma/housing";
import q35 from "./sanjiuma/salary_job-1";
import q36 from "./sanjiuma/salary_job-2";
import q37 from "./sanjiuma/salary_job";
import q38 from "./xiao-biaodi/appearance";
import q39 from "./xiao-biaodi/comparison";
import q40 from "./xiao-biaodi/red_envelope";

export const QUESTIONS: Question[] = [
  ...q0,
  ...q1,
  ...q2,
  ...q3,
  ...q4,
  ...q5,
  ...q6,
  ...q7,
  ...q8,
  ...q9,
  ...q10,
  ...q11,
  ...q12,
  ...q13,
  ...q14,
  ...q15,
  ...q16,
  ...q17,
  ...q18,
  ...q19,
  ...q20,
  ...q21,
  ...q22,
  ...q23,
  ...q24,
  ...q25,
  ...q26,
  ...q27,
  ...q28,
  ...q29,
  ...q30,
  ...q31,
  ...q32,
  ...q33,
  ...q34,
  ...q35,
  ...q36,
  ...q37,
  ...q38,
  ...q39,
  ...q40,
];

export const QUESTION_FILES = [
  "ama/food_push",
  "ama/marriage",
  "ama/religion",
  "biaojie/kids-1",
  "biaojie/kids-2",
  "dabo/education-1",
  "dabo/education-2",
  "dabo/politics-1",
  "dabo/politics-2",
  "dabo/salary_job-1",
  "dabo/salary_job-2",
  "generic/housing",
  "generic/kids",
  "generic/marriage",
  "generic/salary_job",
  "guzhang/elder_health-1",
  "guzhang/elder_health-2",
  "guzhang/food_push-1",
  "guzhang/food_push-2",
  "guzhang/politics-1",
  "guzhang/politics-2",
  "neighbor-chen/comparison-1",
  "neighbor-chen/comparison-2",
  "neighbor-chen/marriage-1",
  "neighbor-chen/marriage-2",
  "neighbor-chen/salary_job-1",
  "neighbor-chen/salary_job-2",
  "sangu/comparison-1",
  "sangu/housing-1",
  "sangu/kids-1",
  "sangu/marriage-1",
  "sangu/salary_job-1",
  "sanjiuma/comparison",
  "sanjiuma/housing-1",
  "sanjiuma/housing",
  "sanjiuma/salary_job-1",
  "sanjiuma/salary_job-2",
  "sanjiuma/salary_job",
  "xiao-biaodi/appearance",
  "xiao-biaodi/comparison",
  "xiao-biaodi/red_envelope"
] as const;
