// AUTO-GENERATED by scripts/build-content-index.mjs — do not edit by hand.
// Run `pnpm content:index` after adding or removing question files.
import type { Question } from "@/content/types";
import q0 from "./ama/food_push";
import q1 from "./ama/marriage";
import q2 from "./ama/religion";
import q3 from "./biaojie/comparison-1";
import q4 from "./biaojie/comparison-2";
import q5 from "./biaojie/housing-1";
import q6 from "./biaojie/housing-2";
import q7 from "./biaojie/kids-1";
import q8 from "./biaojie/kids-2";
import q9 from "./dabo/education-1";
import q10 from "./dabo/education-2";
import q11 from "./dabo/politics-1";
import q12 from "./dabo/politics-2";
import q13 from "./dabo/salary_job-1";
import q14 from "./dabo/salary_job-2";
import q15 from "./generic/appearance";
import q16 from "./generic/comparison";
import q17 from "./generic/education";
import q18 from "./generic/elder_health";
import q19 from "./generic/food_push";
import q20 from "./generic/housing";
import q21 from "./generic/kids";
import q22 from "./generic/marriage";
import q23 from "./generic/politics";
import q24 from "./generic/red_envelope";
import q25 from "./generic/religion";
import q26 from "./generic/salary_job";
import q27 from "./guzhang/elder_health-1";
import q28 from "./guzhang/elder_health-2";
import q29 from "./guzhang/food_push-1";
import q30 from "./guzhang/food_push-2";
import q31 from "./guzhang/politics-1";
import q32 from "./guzhang/politics-2";
import q33 from "./neighbor-chen/comparison-1";
import q34 from "./neighbor-chen/comparison-2";
import q35 from "./neighbor-chen/marriage-1";
import q36 from "./neighbor-chen/marriage-2";
import q37 from "./neighbor-chen/salary_job-1";
import q38 from "./neighbor-chen/salary_job-2";
import q39 from "./sangu/comparison-1";
import q40 from "./sangu/housing-1";
import q41 from "./sangu/kids-1";
import q42 from "./sangu/marriage-1";
import q43 from "./sangu/salary_job-1";
import q44 from "./sanjiuma/comparison-1";
import q45 from "./sanjiuma/comparison-2";
import q46 from "./sanjiuma/comparison";
import q47 from "./sanjiuma/housing-1";
import q48 from "./sanjiuma/housing-2";
import q49 from "./sanjiuma/housing";
import q50 from "./sanjiuma/salary_job-1";
import q51 from "./sanjiuma/salary_job-2";
import q52 from "./sanjiuma/salary_job";
import q53 from "./xiao-biaodi/appearance-1";
import q54 from "./xiao-biaodi/appearance-2";
import q55 from "./xiao-biaodi/appearance";
import q56 from "./xiao-biaodi/comparison-1";
import q57 from "./xiao-biaodi/comparison-2";
import q58 from "./xiao-biaodi/comparison";
import q59 from "./xiao-biaodi/red_envelope-1";
import q60 from "./xiao-biaodi/red_envelope-2";
import q61 from "./xiao-biaodi/red_envelope";

export const QUESTIONS: Question[] = [
  ...q0,
  ...q1,
  ...q2,
  ...q3,
  ...q4,
  ...q5,
  ...q6,
  ...q7,
  ...q8,
  ...q9,
  ...q10,
  ...q11,
  ...q12,
  ...q13,
  ...q14,
  ...q15,
  ...q16,
  ...q17,
  ...q18,
  ...q19,
  ...q20,
  ...q21,
  ...q22,
  ...q23,
  ...q24,
  ...q25,
  ...q26,
  ...q27,
  ...q28,
  ...q29,
  ...q30,
  ...q31,
  ...q32,
  ...q33,
  ...q34,
  ...q35,
  ...q36,
  ...q37,
  ...q38,
  ...q39,
  ...q40,
  ...q41,
  ...q42,
  ...q43,
  ...q44,
  ...q45,
  ...q46,
  ...q47,
  ...q48,
  ...q49,
  ...q50,
  ...q51,
  ...q52,
  ...q53,
  ...q54,
  ...q55,
  ...q56,
  ...q57,
  ...q58,
  ...q59,
  ...q60,
  ...q61,
];

export const QUESTION_FILES = [
  "ama/food_push",
  "ama/marriage",
  "ama/religion",
  "biaojie/comparison-1",
  "biaojie/comparison-2",
  "biaojie/housing-1",
  "biaojie/housing-2",
  "biaojie/kids-1",
  "biaojie/kids-2",
  "dabo/education-1",
  "dabo/education-2",
  "dabo/politics-1",
  "dabo/politics-2",
  "dabo/salary_job-1",
  "dabo/salary_job-2",
  "generic/appearance",
  "generic/comparison",
  "generic/education",
  "generic/elder_health",
  "generic/food_push",
  "generic/housing",
  "generic/kids",
  "generic/marriage",
  "generic/politics",
  "generic/red_envelope",
  "generic/religion",
  "generic/salary_job",
  "guzhang/elder_health-1",
  "guzhang/elder_health-2",
  "guzhang/food_push-1",
  "guzhang/food_push-2",
  "guzhang/politics-1",
  "guzhang/politics-2",
  "neighbor-chen/comparison-1",
  "neighbor-chen/comparison-2",
  "neighbor-chen/marriage-1",
  "neighbor-chen/marriage-2",
  "neighbor-chen/salary_job-1",
  "neighbor-chen/salary_job-2",
  "sangu/comparison-1",
  "sangu/housing-1",
  "sangu/kids-1",
  "sangu/marriage-1",
  "sangu/salary_job-1",
  "sanjiuma/comparison-1",
  "sanjiuma/comparison-2",
  "sanjiuma/comparison",
  "sanjiuma/housing-1",
  "sanjiuma/housing-2",
  "sanjiuma/housing",
  "sanjiuma/salary_job-1",
  "sanjiuma/salary_job-2",
  "sanjiuma/salary_job",
  "xiao-biaodi/appearance-1",
  "xiao-biaodi/appearance-2",
  "xiao-biaodi/appearance",
  "xiao-biaodi/comparison-1",
  "xiao-biaodi/comparison-2",
  "xiao-biaodi/comparison",
  "xiao-biaodi/red_envelope-1",
  "xiao-biaodi/red_envelope-2",
  "xiao-biaodi/red_envelope"
] as const;
