import type { Question } from "@/content/types";

// situations: 021 示範拔罐 / 022 刮痧工具開箱 / 023 推銷按摩椅 / 024 公園用健走杖
// 025 逼你站體脂計 / 026 遞益生菌酵素飲 / 027 老薑黑糖茶 / 028 醋精稀釋液
// 029 打芹菜汁遞給你 / 030 苦瓜汁遞給你 / 031 早晨檸檬水 / 032 小蘇打水
// 033 教腹式呼吸法 / 034 群組洗版養生長輩圖 / 035 開車聽health call-in節目
// 036 練外丹功拉你加入 / 037 拉你加LINE養生社團 / 038 推銷按摩槍
// 039 清晨敲門找你晨走 / 040 初一遞保健品當紅包替代
export default [
  {
    id: "guzhang-elder_health-021",
    text: "來，拔罐通血路，趴下我幫你拔。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-021-a",
        text: "好，我回去查一下拔罐原理。",
        archetype: "perfect",
        retort: "對，了解原理才不會怕。",
      },
      {
        id: "guzhang-elder_health-021-b",
        text: "姑丈這技術是自學的嗎，好厲害。",
        archetype: "deflect",
        retort: "跟師傅學過幾堂課，有基礎。",
      },
      {
        id: "guzhang-elder_health-021-c",
        text: "姑丈自己拔給我看示範一次。",
        archetype: "deflect",
        retort: "好，你看我背上這幾個。",
      },
      {
        id: "guzhang-elder_health-021-d",
        text: "會很痛嗎，我有點害怕……",
        archetype: "meek",
        retort: "不會痛，就吸一下而已。",
      },
      {
        id: "guzhang-elder_health-021-e",
        text: "我等一下要出門，改天再拔……",
        archetype: "meek",
        retort: "改天你就忘記了，現在拔。",
      },
      {
        id: "guzhang-elder_health-021-f",
        text: "拔完是不是背後會長章魚圖案？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加罐子）",
      },
      {
        id: "guzhang-elder_health-021-g",
        text: "拔罐拔到飛起來會不會太用力？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在唱反調）",
      },
      {
        id: "guzhang-elder_health-021-h",
        text: "這個瘀青一片很嚇人，不想拔。",
        archetype: "landmine",
        retort: "……好，那就不要拔了。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-022",
    text: "這個刮痧板剛買，來，刮一下肩頸。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-022-a",
        text: "好，我回去查一下正確手法。",
        archetype: "perfect",
        retort: "查完再讓我幫你刮，更順。",
      },
      {
        id: "guzhang-elder_health-022-b",
        text: "姑丈買刮痧板都做功課的喔。",
        archetype: "deflect",
        retort: "那當然，材質要選對的。",
      },
      {
        id: "guzhang-elder_health-022-c",
        text: "姑丈幫我看看哪裡最緊繃。",
        archetype: "deflect",
        retort: "來，肩膀這邊最硬，我刮給你。",
      },
      {
        id: "guzhang-elder_health-022-d",
        text: "刮下去有點刺，力道輕一點……",
        archetype: "meek",
        retort: "輕一點就沒效果了啦。",
      },
      {
        id: "guzhang-elder_health-022-e",
        text: "我皮膚比較敏感，容易紅腫……",
        archetype: "meek",
        retort: "那我輕輕來，別緊張。",
      },
      {
        id: "guzhang-elder_health-022-f",
        text: "刮完是不是能拿去當洗衣板？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解功效）",
      },
      {
        id: "guzhang-elder_health-022-g",
        text: "刮痧痕越紅是不是代表越紅牌？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍嘴皮）",
      },
      {
        id: "guzhang-elder_health-022-h",
        text: "刮這個滿身紅痕出門很奇怪。",
        archetype: "landmine",
        retort: "……我是想幫你放鬆肩頸耶。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-023",
    text: "這台按摩椅買一台，坐一下試試。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-023-a",
        text: "好舒服，好，我回去查一下價格。",
        archetype: "perfect",
        retort: "查一下，划算的話趕快下手。",
      },
      {
        id: "guzhang-elder_health-023-b",
        text: "姑丈退休生活真的很有品質。",
        archetype: "deflect",
        retort: "那當然，辛苦一輩子了。",
      },
      {
        id: "guzhang-elder_health-023-c",
        text: "姑丈教我怎麼調整力道等級。",
        archetype: "deflect",
        retort: "來，這顆按鈕調強弱，很簡單。",
      },
      {
        id: "guzhang-elder_health-023-d",
        text: "力道有點強，我腰快斷了……",
        archetype: "meek",
        retort: "調弱一點就好，別喊斷啦。",
      },
      {
        id: "guzhang-elder_health-023-e",
        text: "我家裡空間太小，放不下這台……",
        archetype: "meek",
        retort: "小台的也有，我幫你查。",
      },
      {
        id: "guzhang-elder_health-023-f",
        text: "坐這個是不是會被搖到散架？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太誇張）",
      },
      {
        id: "guzhang-elder_health-023-g",
        text: "按摩椅配薑黃是不是雙倍舒暢？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始長篇解說）",
      },
      {
        id: "guzhang-elder_health-023-h",
        text: "這台看起來很貴，不用買啦。",
        archetype: "landmine",
        retort: "……我是想讓你舒服一下而已。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-024",
    text: "拿健走杖，公園走一圈練心肺。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-024-a",
        text: "好，我拿著走，回去也查用法。",
        archetype: "perfect",
        retort: "很好，用法查一下更有效。",
      },
      {
        id: "guzhang-elder_health-024-b",
        text: "姑丈這兩支杖看起來好專業。",
        archetype: "deflect",
        retort: "那當然，登山用的等級呢。",
      },
      {
        id: "guzhang-elder_health-024-c",
        text: "姑丈教我正確的握杖姿勢。",
        archetype: "deflect",
        retort: "來，手腕放鬆，這樣握。",
      },
      {
        id: "guzhang-elder_health-024-d",
        text: "杖有點重，我拿不太穩……",
        archetype: "meek",
        retort: "拿久就習慣了，別喊重。",
      },
      {
        id: "guzhang-elder_health-024-e",
        text: "我今天穿拖鞋，走不太方便……",
        archetype: "meek",
        retort: "那你去換雙鞋再來走。",
      },
      {
        id: "guzhang-elder_health-024-f",
        text: "拿這個是不是要去登喜馬拉雅山？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續往前走）",
      },
      {
        id: "guzhang-elder_health-024-g",
        text: "健走杖是不是也能拿來撐傘？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不專心）",
      },
      {
        id: "guzhang-elder_health-024-h",
        text: "拿這兩支很像老人耶，不想拿。",
        archetype: "landmine",
        retort: "……我自己也拿啊，你嫌什麼。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-025",
    text: "站上體脂計，看你有沒有變油。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-025-a",
        text: "好，我回去查一下正常數值範圍。",
        archetype: "perfect",
        retort: "查一下比較準，別自己嚇自己。",
      },
      {
        id: "guzhang-elder_health-025-b",
        text: "姑丈這台機器功能真齊全。",
        archetype: "deflect",
        retort: "那當然，連內臟脂肪都測得到。",
      },
      {
        id: "guzhang-elder_health-025-c",
        text: "姑丈自己數值多少，先示範一下。",
        archetype: "deflect",
        retort: "我這數字，標準得很，你看。",
      },
      {
        id: "guzhang-elder_health-025-d",
        text: "好啦，我站上去，有點緊張……",
        archetype: "meek",
        retort: "緊張什麼，數字看看就好。",
      },
      {
        id: "guzhang-elder_health-025-e",
        text: "我剛吃飽，數字可能不準……",
        archetype: "meek",
        retort: "那你等一下消化完再量。",
      },
      {
        id: "guzhang-elder_health-025-f",
        text: "這台是不是也能測我的運氣？",
        archetype: "backfire",
        retort: "（姑丈一臉正經，搖頭否認）",
      },
      {
        id: "guzhang-elder_health-025-g",
        text: "體脂高一點是不是比較耐餓？",
        archetype: "backfire",
        retort: "（姑丈皺眉，開始糾正觀念）",
      },
      {
        id: "guzhang-elder_health-025-h",
        text: "不用量啦，我自己身材我清楚。",
        archetype: "landmine",
        retort: "……好，那就不要量了。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-026",
    text: "這瓶益生菌酵素喝一口，腸胃順暢。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-026-a",
        text: "好，我回去查一下菌種成分。",
        archetype: "perfect",
        retort: "對，成分要看清楚，別亂喝。",
      },
      {
        id: "guzhang-elder_health-026-b",
        text: "姑丈家的冰箱是不是保健品專區？",
        archetype: "deflect",
        retort: "那當然，分類都很整齊。",
      },
      {
        id: "guzhang-elder_health-026-c",
        text: "姑丈喝多久了，感覺怎麼樣？",
        archetype: "deflect",
        retort: "喝了三個月，整個人很輕鬆。",
      },
      {
        id: "guzhang-elder_health-026-d",
        text: "味道有點酸，我小口喝就好……",
        archetype: "meek",
        retort: "酸才代表發酵得好啦。",
      },
      {
        id: "guzhang-elder_health-026-e",
        text: "我腸胃最近怪怪的，怕喝了更糟……",
        archetype: "meek",
        retort: "那你少量喝，慢慢適應。",
      },
      {
        id: "guzhang-elder_health-026-f",
        text: "喝這個是不是能練出鋼鐵胃？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒出一杯）",
      },
      {
        id: "guzhang-elder_health-026-g",
        text: "益生菌是不是我肚子裡的室友？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你講話很奇怪）",
      },
      {
        id: "guzhang-elder_health-026-h",
        text: "這種東西根本喝心安的而已。",
        archetype: "landmine",
        retort: "……我特地留給你喝的耶。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-027",
    text: "老薑黑糖茶煮好了，這杯喝掉。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-027-a",
        text: "好喝，好，我回去查一下配方。",
        archetype: "perfect",
        retort: "查一下比例，煮起來更香。",
      },
      {
        id: "guzhang-elder_health-027-b",
        text: "姑丈煮的茶真的比外面好喝。",
        archetype: "deflect",
        retort: "那當然，薑都自己挑的。",
      },
      {
        id: "guzhang-elder_health-027-c",
        text: "姑丈教我怎麼熬才會這麼香。",
        archetype: "deflect",
        retort: "秘訣是小火慢熬，我教你。",
      },
      {
        id: "guzhang-elder_health-027-d",
        text: "有點燙，我等涼一點再喝……",
        archetype: "meek",
        retort: "趁熱喝才有效啦，快點。",
      },
      {
        id: "guzhang-elder_health-027-e",
        text: "我剛喝過飲料，肚子有點滿……",
        archetype: "meek",
        retort: "那你放涼一點，等一下喝。",
      },
      {
        id: "guzhang-elder_health-027-f",
        text: "喝完是不是全身會冒煙發熱？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續添茶）",
      },
      {
        id: "guzhang-elder_health-027-g",
        text: "黑糖薑茶配薑黃是不是三合一？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始研究配方）",
      },
      {
        id: "guzhang-elder_health-027-h",
        text: "這茶太甜了，我不太想喝。",
        archetype: "landmine",
        retort: "……我熬了一下午你這樣講。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-028",
    text: "這瓶醋精加水稀釋，早上喝一杯。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-028-a",
        text: "好，我回去查一下正確稀釋比例。",
        archetype: "perfect",
        retort: "對，比例抓對才不會傷胃。",
      },
      {
        id: "guzhang-elder_health-028-b",
        text: "姑丈連比例都算好，太細心了。",
        archetype: "deflect",
        retort: "那當然，這是門學問呢。",
      },
      {
        id: "guzhang-elder_health-028-c",
        text: "姑丈教我怎麼稀釋不會太酸。",
        archetype: "deflect",
        retort: "一比十就好，我教你調。",
      },
      {
        id: "guzhang-elder_health-028-d",
        text: "味道有點刺激，我小口喝……",
        archetype: "meek",
        retort: "刺激才代表在發揮效果啦。",
      },
      {
        id: "guzhang-elder_health-028-e",
        text: "我胃比較敏感，怕喝了不舒服……",
        archetype: "meek",
        retort: "那再多加點水稀釋一下。",
      },
      {
        id: "guzhang-elder_health-028-f",
        text: "這味道，我拿去醃泡菜好了。",
        archetype: "backfire",
        retort: "（姑丈皺眉，把瓶子拿回去）",
      },
      {
        id: "guzhang-elder_health-028-g",
        text: "喝完是不是嘴巴會變醋罈子？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒進杯子）",
      },
      {
        id: "guzhang-elder_health-028-h",
        text: "這種偏方喝了根本沒感覺啦。",
        archetype: "landmine",
        retort: "……你都沒認真試過就這樣講。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-029",
    text: "芹菜汁打好了，喝下去降降火。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-029-a",
        text: "好，我回去查一下這個說法。",
        archetype: "perfect",
        retort: "查完你就懂，這汁很厲害。",
      },
      {
        id: "guzhang-elder_health-029-b",
        text: "姑丈打果汁機的技術也太厲害。",
        archetype: "deflect",
        retort: "那當然，退休就是要練這個。",
      },
      {
        id: "guzhang-elder_health-029-c",
        text: "姑丈天天喝這個嗎，習慣嗎？",
        archetype: "deflect",
        retort: "天天喝，早就習慣這個味道。",
      },
      {
        id: "guzhang-elder_health-029-d",
        text: "味道有點草味，我皺著眉喝……",
        archetype: "meek",
        retort: "皺什麼眉，這是天然的味道。",
      },
      {
        id: "guzhang-elder_health-029-e",
        text: "我等一下要開會，怕味道太重……",
        archetype: "meek",
        retort: "那你喝完記得漱一下口。",
      },
      {
        id: "guzhang-elder_health-029-f",
        text: "喝完是不是會變成一根芹菜？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加芹菜進去）",
      },
      {
        id: "guzhang-elder_health-029-g",
        text: "芹菜汁配薑黃會是什麼顏色？",
        archetype: "backfire",
        retort: "（姑丈認真思考這個組合）",
      },
      {
        id: "guzhang-elder_health-029-h",
        text: "這個味道很難喝，我不要喝。",
        archetype: "landmine",
        retort: "……我特地打給你的耶。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-030",
    text: "苦瓜汁最退火，喝完精神百倍。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-030-a",
        text: "好，我回去查一下苦瓜的功效。",
        archetype: "perfect",
        retort: "查完你會發現，這汁超划算。",
      },
      {
        id: "guzhang-elder_health-030-b",
        text: "姑丈喝這個都不怕苦嗎，佩服。",
        archetype: "deflect",
        retort: "習慣就好，苦後回甘啦。",
      },
      {
        id: "guzhang-elder_health-030-c",
        text: "姑丈有加蜂蜜嗎，教我調一下。",
        archetype: "deflect",
        retort: "有喔，加一點會順口很多。",
      },
      {
        id: "guzhang-elder_health-030-d",
        text: "真的好苦，我皺著臉喝完了……",
        archetype: "meek",
        retort: "皺臉表示排毒有效果啦。",
      },
      {
        id: "guzhang-elder_health-030-e",
        text: "我怕太苦，可以先喝一半嗎……",
        archetype: "meek",
        retort: "喝一半也算有心，加油。",
      },
      {
        id: "guzhang-elder_health-030-f",
        text: "喝完是不是連笑容都變苦瓜臉？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解退火）",
      },
      {
        id: "guzhang-elder_health-030-g",
        text: "苦瓜汁是不是能拿去嚇跑蚊子？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍寶）",
      },
      {
        id: "guzhang-elder_health-030-h",
        text: "這麼苦誰要喝啦，倒掉算了。",
        archetype: "landmine",
        retort: "……我榨了半天你這樣講。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-031",
    text: "早上第一件事，先喝杯檸檬水。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-031-a",
        text: "好，我回去查一下正確濃度。",
        archetype: "perfect",
        retort: "對，濃度抓好，效果加倍。",
      },
      {
        id: "guzhang-elder_health-031-b",
        text: "姑丈連檸檬都要精算比例喔。",
        archetype: "deflect",
        retort: "那當然，這是我研究出來的。",
      },
      {
        id: "guzhang-elder_health-031-c",
        text: "姑丈幾點起床開始這個儀式？",
        archetype: "deflect",
        retort: "五點半，跟早安圖一起開始。",
      },
      {
        id: "guzhang-elder_health-031-d",
        text: "空腹喝有點酸，我皺著臉……",
        archetype: "meek",
        retort: "酸一下就過去了，忍耐點。",
      },
      {
        id: "guzhang-elder_health-031-e",
        text: "我早上都趕時間，沒空弄……",
        archetype: "meek",
        retort: "那前一晚先準備好放冰箱。",
      },
      {
        id: "guzhang-elder_health-031-f",
        text: "喝完是不是整張臉會變檸檬色？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續切檸檬）",
      },
      {
        id: "guzhang-elder_health-031-g",
        text: "檸檬水配薑黃是不是酸辣過癮？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真考慮起來）",
      },
      {
        id: "guzhang-elder_health-031-h",
        text: "這個網路早就說沒什麼用了啦。",
        archetype: "landmine",
        retort: "……你什麼都要跟網路比就對了。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-032",
    text: "這杯小蘇打水中和一下胃酸。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-032-a",
        text: "好，我回去查一下適合的濃度。",
        archetype: "perfect",
        retort: "對，濃度別亂調，查清楚最好。",
      },
      {
        id: "guzhang-elder_health-032-b",
        text: "姑丈連小蘇打都有研究，厲害。",
        archetype: "deflect",
        retort: "那當然，這是基本常識啦。",
      },
      {
        id: "guzhang-elder_health-032-c",
        text: "姑丈平常都拿它做什麼用？",
        archetype: "deflect",
        retort: "刷牙、清潔都能用，一舉多得。",
      },
      {
        id: "guzhang-elder_health-032-d",
        text: "味道怪怪的，我小口喝一下……",
        archetype: "meek",
        retort: "怪一下就過去了，快喝。",
      },
      {
        id: "guzhang-elder_health-032-e",
        text: "我最近胃有點不舒服，怕喝了更差……",
        archetype: "meek",
        retort: "那你先少喝一點試試看。",
      },
      {
        id: "guzhang-elder_health-032-f",
        text: "喝完是不是能拿去發麵包？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解用途）",
      },
      {
        id: "guzhang-elder_health-032-g",
        text: "小蘇打水配醋是不是會冒泡？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在搞實驗）",
      },
      {
        id: "guzhang-elder_health-032-h",
        text: "這種東西喝了根本沒差好嗎。",
        archetype: "landmine",
        retort: "……我是為你的胃著想耶。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-033",
    text: "來，教你腹式呼吸，吸氣到肚子。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-033-a",
        text: "好，我學著呼吸，回去再查資料。",
        archetype: "perfect",
        retort: "很好，學會這招一輩子受用。",
      },
      {
        id: "guzhang-elder_health-033-b",
        text: "姑丈連呼吸都研究，太專業了。",
        archetype: "deflect",
        retort: "那當然，呼吸也是門學問。",
      },
      {
        id: "guzhang-elder_health-033-c",
        text: "姑丈示範一次，我在旁邊學。",
        archetype: "deflect",
        retort: "好，你看，肚子這樣鼓起來。",
      },
      {
        id: "guzhang-elder_health-033-d",
        text: "我吸氣吸到頭有點暈……",
        archetype: "meek",
        retort: "慢慢吸就好，別太用力。",
      },
      {
        id: "guzhang-elder_health-033-e",
        text: "我肚子有點脹，吸不太進去……",
        archetype: "meek",
        retort: "那你先躺下來，比較好練。",
      },
      {
        id: "guzhang-elder_health-033-f",
        text: "吸氣到肚子是不是會變氣球？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續示範動作）",
      },
      {
        id: "guzhang-elder_health-033-g",
        text: "這樣呼吸是不是能吹出泡泡？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不專心）",
      },
      {
        id: "guzhang-elder_health-033-h",
        text: "呼吸而已，有需要教這麼久嗎。",
        archetype: "landmine",
        retort: "……我是想幫你放鬆一下而已。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-034",
    text: "家庭群組又洗版了，你倒是看一下。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-034-a",
        text: "都看了，好，我回去整理重點。",
        archetype: "perfect",
        retort: "很好，整理起來以後方便查。",
      },
      {
        id: "guzhang-elder_health-034-b",
        text: "姑丈一天到底轉發幾篇啊，厲害。",
        archetype: "deflect",
        retort: "至少十篇，都精心挑選的。",
      },
      {
        id: "guzhang-elder_health-034-c",
        text: "姑丈挑一篇你最推的講給我聽。",
        archetype: "deflect",
        retort: "好，那就這篇薑黃的最實用。",
      },
      {
        id: "guzhang-elder_health-034-d",
        text: "訊息太多了，我都直接略過……",
        archetype: "meek",
        retort: "略過就浪費我一片心意了。",
      },
      {
        id: "guzhang-elder_health-034-e",
        text: "手機容量快滿了，都是這些圖……",
        archetype: "meek",
        retort: "那你買個記憶卡就好了嘛。",
      },
      {
        id: "guzhang-elder_health-034-f",
        text: "這樣洗版是不是能練出手速？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續轉發下一篇）",
      },
      {
        id: "guzhang-elder_health-034-g",
        text: "群組是不是快變成養生資料庫？",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得是稱讚）",
      },
      {
        id: "guzhang-elder_health-034-h",
        text: "拜託不要再洗版了，很煩耶。",
        archetype: "landmine",
        retort: "……好，那我以後不傳給你了。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-035",
    text: "開車聽這個養生節目，主持人很懂。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-035-a",
        text: "好，我回去查一下這個節目。",
        archetype: "perfect",
        retort: "查一下，每天都有新內容。",
      },
      {
        id: "guzhang-elder_health-035-b",
        text: "姑丈開車都聽這個，太養生了。",
        archetype: "deflect",
        retort: "那當然，開車時間也不能浪費。",
      },
      {
        id: "guzhang-elder_health-035-c",
        text: "這主持人講的哪句最讓你認同？",
        archetype: "deflect",
        retort: "他說薑黃最好，我最認同。",
      },
      {
        id: "guzhang-elder_health-035-d",
        text: "聲音有點吵，我想睡一下……",
        archetype: "meek",
        retort: "睡什麼睡，這節目很重要。",
      },
      {
        id: "guzhang-elder_health-035-e",
        text: "我在暈車，沒辦法專心聽……",
        archetype: "meek",
        retort: "那你把窗戶打開透透氣。",
      },
      {
        id: "guzhang-elder_health-035-f",
        text: "這節目是不是專門賣藥給你？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你亂猜疑）",
      },
      {
        id: "guzhang-elder_health-035-g",
        text: "主持人講話是不是都同一套？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續轉大音量）",
      },
      {
        id: "guzhang-elder_health-035-h",
        text: "這種call-in節目根本亂講的啦。",
        archetype: "landmine",
        retort: "……你連這個都不相信我。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-036",
    text: "來練外丹功，跟著我抖動雙手。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-036-a",
        text: "好，我跟著抖，回去再查招式。",
        archetype: "perfect",
        retort: "很好，練久了氣血就通了。",
      },
      {
        id: "guzhang-elder_health-036-b",
        text: "姑丈練這個練多久了啊，好強。",
        archetype: "deflect",
        retort: "退休那年開始，快五年了。",
      },
      {
        id: "guzhang-elder_health-036-c",
        text: "姑丈慢動作示範一次給我看。",
        archetype: "deflect",
        retort: "好，你仔細看這個抖動節奏。",
      },
      {
        id: "guzhang-elder_health-036-d",
        text: "抖一下手就痠了，好累……",
        archetype: "meek",
        retort: "才抖一下就喊累，太年輕。",
      },
      {
        id: "guzhang-elder_health-036-e",
        text: "動作我抓不到節奏，姑丈再教一次……",
        archetype: "meek",
        retort: "好，我放慢一點再示範。",
      },
      {
        id: "guzhang-elder_health-036-f",
        text: "抖成這樣是不是要通電了？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續認真抖動）",
      },
      {
        id: "guzhang-elder_health-036-g",
        text: "外丹功是不是能拿來甩掉衰運？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不夠認真）",
      },
      {
        id: "guzhang-elder_health-036-h",
        text: "這個動作看起來很滑稽，不練。",
        archetype: "landmine",
        retort: "……好，那你就在旁邊看。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-037",
    text: "加一下這個LINE養生社群，資訊多。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-037-a",
        text: "好，我回去研究一下這個社群。",
        archetype: "perfect",
        retort: "對，進去看看就知道多實用。",
      },
      {
        id: "guzhang-elder_health-037-b",
        text: "姑丈是不是這社群的活躍成員？",
        archetype: "deflect",
        retort: "那當然，我每篇都留言。",
      },
      {
        id: "guzhang-elder_health-037-c",
        text: "姑丈推薦一篇裡面最經典的文。",
        archetype: "deflect",
        retort: "好，那篇薑黃神文一定要看。",
      },
      {
        id: "guzhang-elder_health-037-d",
        text: "群組太多我快分不清了……",
        archetype: "meek",
        retort: "分清楚啊，這個最重要。",
      },
      {
        id: "guzhang-elder_health-037-e",
        text: "我平常訊息就已經看不完了……",
        archetype: "meek",
        retort: "那你要挪出時間看這個。",
      },
      {
        id: "guzhang-elder_health-037-f",
        text: "加入是不是要先考個養生證照？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續傳邀請連結）",
      },
      {
        id: "guzhang-elder_health-037-g",
        text: "這種群組是不是都同一群阿伯？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得被冒犯了一下）",
      },
      {
        id: "guzhang-elder_health-037-h",
        text: "這種社群裡面都是詐騙啦，別加。",
        archetype: "landmine",
        retort: "……你怎麼講話跟你爸一樣。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-038",
    text: "這把按摩槍打一下肩膀，超舒壓。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-038-a",
        text: "好舒服，好，我回去查一下款式。",
        archetype: "perfect",
        retort: "查一下，這款CP值最高。",
      },
      {
        id: "guzhang-elder_health-038-b",
        text: "姑丈買的裝備都好先進喔。",
        archetype: "deflect",
        retort: "那當然，退休生活要跟上時代。",
      },
      {
        id: "guzhang-elder_health-038-c",
        text: "姑丈教我怎麼調整強度檔位。",
        archetype: "deflect",
        retort: "來，這顆鈕調強弱，很簡單。",
      },
      {
        id: "guzhang-elder_health-038-d",
        text: "力道有點強，我肩膀快麻了……",
        archetype: "meek",
        retort: "調弱一點就好，別喊麻啦。",
      },
      {
        id: "guzhang-elder_health-038-e",
        text: "我怕吵，這聲音有點大聲……",
        archetype: "meek",
        retort: "小聲的檔位在這裡，換一下。",
      },
      {
        id: "guzhang-elder_health-038-f",
        text: "打完是不是肩膀會裝上馬達？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續打另一邊）",
      },
      {
        id: "guzhang-elder_health-038-g",
        text: "按摩槍是不是能拿來鑽木取火？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂講）",
      },
      {
        id: "guzhang-elder_health-038-h",
        text: "這台看起來很吵，我不想試。",
        archetype: "landmine",
        retort: "……我是想幫你放鬆一下而已。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-039",
    text: "清晨六點敲門，走啦，一起去晨走。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-039-a",
        text: "好，等我五分鐘，回去也查路線。",
        archetype: "perfect",
        retort: "很好，準時的孩子最健康。",
      },
      {
        id: "guzhang-elder_health-039-b",
        text: "姑丈這麼早就精神奕奕，佩服。",
        archetype: "deflect",
        retort: "退休就是要早睡早起，你也要。",
      },
      {
        id: "guzhang-elder_health-039-c",
        text: "姑丈今天要走哪條路線，介紹一下。",
        archetype: "deflect",
        retort: "河堤那條，風景最好，走吧。",
      },
      {
        id: "guzhang-elder_health-039-d",
        text: "好啦，我五分鐘後下去……",
        archetype: "meek",
        retort: "現在就下來，別拖拖拉拉。",
      },
      {
        id: "guzhang-elder_health-039-e",
        text: "我昨晚太晚睡，好想再躺一下……",
        archetype: "meek",
        retort: "那你以後要早點睡，快起來。",
      },
      {
        id: "guzhang-elder_health-039-f",
        text: "這麼早敲門是不是要來抓賊？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續敲門催促）",
      },
      {
        id: "guzhang-elder_health-039-g",
        text: "晨走是不是能順便練成鐵人？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍嘴皮）",
      },
      {
        id: "guzhang-elder_health-039-h",
        text: "這麼早是要吵醒全家人喔。",
        archetype: "landmine",
        retort: "……我是好意找你一起運動。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-040",
    text: "紅包我換成這盒保健品，更實用。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-040-a",
        text: "謝謝姑丈，好，我回去查一下成分。",
        archetype: "perfect",
        retort: "查一下就知道，這比紅包實在。",
      },
      {
        id: "guzhang-elder_health-040-b",
        text: "姑丈這份心意比紅包還珍貴啦。",
        archetype: "deflect",
        retort: "哎唷，你這孩子真會講話。",
      },
      {
        id: "guzhang-elder_health-040-c",
        text: "姑丈幫我看看要怎麼吃比較好。",
        archetype: "deflect",
        retort: "來，早晚各一顆，我教你。",
      },
      {
        id: "guzhang-elder_health-040-d",
        text: "喔……好，那紅包呢，開玩笑的……",
        archetype: "meek",
        retort: "紅包當然也有，別緊張。",
      },
      {
        id: "guzhang-elder_health-040-e",
        text: "我家已經有很多保健品了……",
        archetype: "meek",
        retort: "多一盒也沒關係，換著吃。",
      },
      {
        id: "guzhang-elder_health-040-f",
        text: "這是不是能拿去夜市擺攤賣？",
        archetype: "backfire",
        retort: "（姑丈皺眉，把盒子收回去）",
      },
      {
        id: "guzhang-elder_health-040-g",
        text: "保健品當紅包是不是全國首創？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續介紹功效）",
      },
      {
        id: "guzhang-elder_health-040-h",
        text: "過年還是包現金實際啦，姑丈。",
        archetype: "landmine",
        retort: "……好，那你不要這盒了。",
      },
    ],
  },
] satisfies Question[];
