import type { Question } from "@/content/types";

// situations: 001 五點早安圖 / 002 轉傳薑黃黑胡椒文 / 003 餐桌遞醋泡蛋 / 004 陽台曬黑蒜
// 005 逼你關飛航防輻射 / 006 微波爐加熱剩菜警告 / 007 遞溫水不准喝冰的 / 008 客廳量血壓機
// 009 拿出魚油罐要你吃 / 010 公園健走分享秘方 / 011 廟口聊偏方 / 012 教你拍打拉筋
// 013 甩手功早操示範 / 014 睡前要關wifi分享器 / 015 電風扇整夜警告 / 016 空腹吃水果迷思
// 017 隔夜菜能不能吃 / 018 生薑泡腳法 / 019 綠豆湯解百毒 / 020 轉傳食物相剋文章
export default [
  {
    id: "guzhang-elder_health-001",
    text: "五點傳早安圖，已讀不回是怎樣？",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-001-a",
        text: "幹……看到了啦，眼睛還沒睜開……",
        archetype: "meek",
        retort: "五點不起來，你以後會後悔！",
      },
      {
        id: "guzhang-elder_health-001-b",
        text: "幹，五點傳圖是想證明我失眠？",
        archetype: "perfect",
        retort: "他語塞，乾笑轉頭找話題。",
      },
      {
        id: "guzhang-elder_health-001-c",
        text: "姑丈才是本家族晨型霸主啦。",
        archetype: "deflect",
        retort: "哎唷，退休就要早起活動。",
      },
      {
        id: "guzhang-elder_health-001-d",
        text: "幹，早安圖是不是都套同個模板？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，又傳一張）",
      },
      {
        id: "guzhang-elder_health-001-e",
        text: "幹，死老頭退休沒事做，只剩洗版找存在感？",
        archetype: "landmine",
        retort: "他臉一垮，摔杯罵你欠揍！",
      },
      {
        id: "guzhang-elder_health-001-f",
        text: "手機都設靜音，晚點才看到啦……",
        archetype: "meek",
        retort: "那你設定不對，改一下。",
      },
      {
        id: "guzhang-elder_health-001-g",
        text: "靠，姑丈要不要開個早安圖工作室？",
        archetype: "deflect",
        retort: "你這提議，不錯喔！",
      },
      {
        id: "guzhang-elder_health-001-h",
        text: "他媽的，五點傳圖比打卡鬧鐘還準時。",
        archetype: "backfire",
        retort: "（姑丈得意，真心收下稱讚）",
      },
    ],
  },
  {
    id: "guzhang-elder_health-002",
    text: "薑黃配黑胡椒，我朋友的朋友試過。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-002-a",
        text: "幹，朋友的朋友怎麼每次都缺席？",
        archetype: "perfect",
        retort: "他語塞，乾笑罵一句幹恁娘。",
      },
      {
        id: "guzhang-elder_health-002-b",
        text: "姑丈朋友的朋友是不是全年無休？",
        archetype: "deflect",
        retort: "他很忙沒錯，但很照顧朋友。",
      },
      {
        id: "guzhang-elder_health-002-c",
        text: "靠，那姑丈自己在吃嗎，效果如何？",
        archetype: "deflect",
        retort: "當然，你看我氣色多好！",
      },
      {
        id: "guzhang-elder_health-002-d",
        text: "幹……好，我等一下查查看……",
        archetype: "meek",
        retort: "不是等一下，現在就查！",
      },
      {
        id: "guzhang-elder_health-002-e",
        text: "我對黑胡椒過敏，可能沒辦法……",
        archetype: "meek",
        retort: "那換成別的辛香料也可以啦。",
      },
      {
        id: "guzhang-elder_health-002-f",
        text: "幹，加咖哩一起吃是不是更強？",
        archetype: "backfire",
        retort: "（姑丈認真思考，傳來連結）",
      },
      {
        id: "guzhang-elder_health-002-g",
        text: "薑黃拿去染布應該也不錯啦哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒接話，繼續講功效）",
      },
      {
        id: "guzhang-elder_health-002-h",
        text: "幹你娘，朋友的朋友根本不存在吧。",
        archetype: "landmine",
        retort: "他氣到爆粗口，摔杯轉身。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-003",
    text: "這杯醋泡蛋喝掉，排毒又養生。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-003-a",
        text: "他媽的這麼養生，怎麼血壓還高？",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到肩膀抖。",
      },
      {
        id: "guzhang-elder_health-003-b",
        text: "姑丈自己泡的？手藝真不錯。",
        archetype: "deflect",
        retort: "那當然，退休後天天研究。",
      },
      {
        id: "guzhang-elder_health-003-c",
        text: "靠，姑丈先喝一口示範一下嘛。",
        archetype: "deflect",
        retort: "好啊，看我喝給你看！",
      },
      {
        id: "guzhang-elder_health-003-d",
        text: "幹……味道有點特別，我小口喝……",
        archetype: "meek",
        retort: "習慣就好，多喝幾杯就順口。",
      },
      {
        id: "guzhang-elder_health-003-e",
        text: "我腸胃比較敏感，怕喝了不舒服……",
        archetype: "meek",
        retort: "那你少量試試看就好啦。",
      },
      {
        id: "guzhang-elder_health-003-f",
        text: "幹，這味道拿去當萬用清潔劑好了。",
        archetype: "backfire",
        retort: "（姑丈皺眉，把杯子推回來）",
      },
      {
        id: "guzhang-elder_health-003-g",
        text: "靠，喝完會不會變成醋罈子啊哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂梗，繼續講功效）",
      },
      {
        id: "guzhang-elder_health-003-h",
        text: "去你的偏方，喝這麼多年有一個有效嗎？",
        archetype: "landmine",
        retort: "他臉一垮，罵你欠教訓。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-004",
    text: "陽台曬的黑蒜，抗氧化超強喔。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-004-a",
        text: "靠北，抗氧化這麼強，姑姑怎麼不吃？",
        archetype: "perfect",
        retort: "他改口說回去查查看。",
      },
      {
        id: "guzhang-elder_health-004-b",
        text: "姑丈這技術可以去開店了吧。",
        archetype: "deflect",
        retort: "哎唷，退休生活就是要有事做。",
      },
      {
        id: "guzhang-elder_health-004-c",
        text: "靠，曬幾天才變這樣，教教我啦。",
        archetype: "deflect",
        retort: "至少要一個月，慢慢等。",
      },
      {
        id: "guzhang-elder_health-004-d",
        text: "幹……看起來有點像燒焦的……",
        archetype: "meek",
        retort: "這是熟成，不是燒焦啦！",
      },
      {
        id: "guzhang-elder_health-004-e",
        text: "我怕蒜味太重，等一下再吃……",
        archetype: "meek",
        retort: "黑蒜不會臭，你吃吃看。",
      },
      {
        id: "guzhang-elder_health-004-f",
        text: "幹，陽台是不是快變成中藥行了？",
        archetype: "backfire",
        retort: "（姑丈認真點頭，沒發現玩笑）",
      },
      {
        id: "guzhang-elder_health-004-g",
        text: "黑蒜配咖啡應該很特別齁哈哈。",
        archetype: "backfire",
        retort: "（姑丈一臉認真考慮這組合）",
      },
      {
        id: "guzhang-elder_health-004-h",
        text: "幹，死老頭曬這些偏方，不如曬曬你血壓。",
        archetype: "landmine",
        retort: "他吼一句幹恁娘，甩門進房。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-005",
    text: "手機開飛航啦，輻射對身體不好。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-005-a",
        text: "他媽的那你自己怎麼還在滑手機？",
        archetype: "perfect",
        retort: "他訕笑，轉頭找姑姑討救兵。",
      },
      {
        id: "guzhang-elder_health-005-b",
        text: "姑丈的手機也開飛航了嗎？",
        archetype: "deflect",
        retort: "我當然有啊，睡覺前都開。",
      },
      {
        id: "guzhang-elder_health-005-c",
        text: "靠，姑丈教我怎麼設定飛航模式吧。",
        archetype: "deflect",
        retort: "來來來，我教你，很簡單。",
      },
      {
        id: "guzhang-elder_health-005-d",
        text: "幹……可是開了朋友傳訊息看不到……",
        archetype: "meek",
        retort: "睡覺誰找你啦，快關一關。",
      },
      {
        id: "guzhang-elder_health-005-e",
        text: "好啦好啦，我等一下開……",
        archetype: "meek",
        retort: "現在就開，不要等一下。",
      },
      {
        id: "guzhang-elder_health-005-f",
        text: "幹，那我把手機丟進冰箱好了。",
        archetype: "backfire",
        retort: "（姑丈皺眉，不覺得好笑）",
      },
      {
        id: "guzhang-elder_health-005-g",
        text: "輻射那麼強，微波爐更可怕吧。",
        archetype: "backfire",
        retort: "（姑丈認真接話，開始講微波爐）",
      },
      {
        id: "guzhang-elder_health-005-h",
        text: "去你的，怕輻射怎麼不怕被詐騙訊息騙？",
        archetype: "landmine",
        retort: "他臉一垮，罵你三小，別過頭。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-006",
    text: "剩菜不要微波，會破壞營養喔。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-006-a",
        text: "幹，你這養生知識是被誰騙的？",
        archetype: "perfect",
        retort: "他愣了一下，眉頭挑起來。",
      },
      {
        id: "guzhang-elder_health-006-b",
        text: "那姑丈平常都怎麼加熱菜？",
        archetype: "deflect",
        retort: "電鍋蒸最好，慢慢來。",
      },
      {
        id: "guzhang-elder_health-006-c",
        text: "靠，姑丈教我電鍋的正確用法。",
        archetype: "deflect",
        retort: "好，來，我示範給你看。",
      },
      {
        id: "guzhang-elder_health-006-d",
        text: "幹……可是微波比較快，我懶得等……",
        archetype: "meek",
        retort: "懶惰是會影響健康的知道嗎。",
      },
      {
        id: "guzhang-elder_health-006-e",
        text: "家裡沒有電鍋，只能微波……",
        archetype: "meek",
        retort: "那你要買一台，我幫你選。",
      },
      {
        id: "guzhang-elder_health-006-f",
        text: "幹，那我用炭火烤好了最養生。",
        archetype: "backfire",
        retort: "（姑丈翻白眼，繼續碎念）",
      },
      {
        id: "guzhang-elder_health-006-g",
        text: "靠，微波爐是不是會把菜變機器人？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，一臉疑惑）",
      },
      {
        id: "guzhang-elder_health-006-h",
        text: "他媽的這種說法，跟你被騙那次一樣準。",
        archetype: "landmine",
        retort: "他氣到講台語，罵你白目。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-007",
    text: "這杯溫水喝掉，不要一直喝冰的。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-007-a",
        text: "幹，溫水這麼神怎麼沒治好血壓？",
        archetype: "perfect",
        retort: "他嘴硬，眼神卻閃躲。",
      },
      {
        id: "guzhang-elder_health-007-b",
        text: "姑丈連水溫都幫我顧，太貼心了。",
        archetype: "deflect",
        retort: "那當然，這是我的專業。",
      },
      {
        id: "guzhang-elder_health-007-c",
        text: "靠，姑丈平常喝幾杯溫水啊？",
        archetype: "deflect",
        retort: "早中晚各三杯，你也要學。",
      },
      {
        id: "guzhang-elder_health-007-d",
        text: "幹……好啦，我慢慢喝，有點燙……",
        archetype: "meek",
        retort: "燙才有效，忍一下就好。",
      },
      {
        id: "guzhang-elder_health-007-e",
        text: "我比較習慣喝冰的，不太適應……",
        archetype: "meek",
        retort: "習慣是可以改的，慢慢來。",
      },
      {
        id: "guzhang-elder_health-007-f",
        text: "幹，那我加冰塊中和一下好了。",
        archetype: "backfire",
        retort: "（姑丈一把搶走冰塊）",
      },
      {
        id: "guzhang-elder_health-007-g",
        text: "溫水配薑黃是不是無敵組合？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，長篇大論）",
      },
      {
        id: "guzhang-elder_health-007-h",
        text: "幹，姑姑早把你群組設靜音了老東西。",
        archetype: "landmine",
        retort: "他臉一垮，轉頭找姑姑理論。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-008",
    text: "來，量個血壓，退休後我很閒。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-008-a",
        text: "靠北，你血壓標準是換新機器吧？",
        archetype: "perfect",
        retort: "他愣住，手機螢幕暗掉。",
      },
      {
        id: "guzhang-elder_health-008-b",
        text: "姑丈這台機器哪裡買的，好專業。",
        archetype: "deflect",
        retort: "網路買的，功能超多喔。",
      },
      {
        id: "guzhang-elder_health-008-c",
        text: "靠，姑丈自己數值正常嗎？分享一下。",
        archetype: "deflect",
        retort: "我很標準，都在正常範圍。",
      },
      {
        id: "guzhang-elder_health-008-d",
        text: "幹……好啦，坐下來量，會不會很痛……",
        archetype: "meek",
        retort: "不會痛，就夾一下而已。",
      },
      {
        id: "guzhang-elder_health-008-e",
        text: "我剛跑完步，數值可能會偏高……",
        archetype: "meek",
        retort: "那你先休息五分鐘再量。",
      },
      {
        id: "guzhang-elder_health-008-f",
        text: "幹，血壓機是不是能順便測心情？",
        archetype: "backfire",
        retort: "（姑丈一臉正經地搖頭）",
      },
      {
        id: "guzhang-elder_health-008-g",
        text: "量完是不是要發文昭告天下？",
        archetype: "backfire",
        retort: "（姑丈認真思考要不要發群組）",
      },
      {
        id: "guzhang-elder_health-008-h",
        text: "他媽的退休這麼閒，量血壓找存在感？",
        archetype: "landmine",
        retort: "他臉一垮，冷著臉罵你欠揍。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-009",
    text: "這罐魚油吃一顆，我朋友推薦的。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-009-a",
        text: "幹，朋友推薦的，你查過真假沒？",
        archetype: "perfect",
        retort: "他語塞，重新想措辭。",
      },
      {
        id: "guzhang-elder_health-009-b",
        text: "姑丈你的保健品收藏真齊全。",
        archetype: "deflect",
        retort: "那當然，這是我的興趣。",
      },
      {
        id: "guzhang-elder_health-009-c",
        text: "靠，姑丈吃了多久，效果怎麼樣？",
        archetype: "deflect",
        retort: "半年了，感覺整個人更靈活。",
      },
      {
        id: "guzhang-elder_health-009-d",
        text: "幹……顆粒有點大，我怕吞不下去……",
        archetype: "meek",
        retort: "配溫水一口吞就好了啦。",
      },
      {
        id: "guzhang-elder_health-009-e",
        text: "我平常有在吃別的保健品了……",
        archetype: "meek",
        retort: "那也可以一起吃啊，沒關係。",
      },
      {
        id: "guzhang-elder_health-009-f",
        text: "幹，吃這麼多顆是不是會變魚？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒出更多）",
      },
      {
        id: "guzhang-elder_health-009-g",
        text: "靠，這罐是不是能拿去釣魚當餌？",
        archetype: "backfire",
        retort: "（姑丈臉一沉，把罐子收回去）",
      },
      {
        id: "guzhang-elder_health-009-h",
        text: "去死啦，朋友的朋友怎麼每次都缺席老不死？",
        archetype: "landmine",
        retort: "他氣到講台語，罵你不聽老人言。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-010",
    text: "公園健走遇到，快跟上我的節奏。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-010-a",
        text: "靠北，走這麼快是要甩開誰的閒言？",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到眼淚都出來。",
      },
      {
        id: "guzhang-elder_health-010-b",
        text: "姑丈走這麼快，體力真的驚人。",
        archetype: "deflect",
        retort: "退休後天天練，當然厲害。",
      },
      {
        id: "guzhang-elder_health-010-c",
        text: "靠，姑丈教我正確的健走姿勢吧。",
        archetype: "deflect",
        retort: "來，跟著我這樣擺手。",
      },
      {
        id: "guzhang-elder_health-010-d",
        text: "幹……有點喘，我需要休息一下……",
        archetype: "meek",
        retort: "才走這樣就喘，太不像話。",
      },
      {
        id: "guzhang-elder_health-010-e",
        text: "我昨天沒睡好，走不快……",
        archetype: "meek",
        retort: "那早點睡，明天再一起走。",
      },
      {
        id: "guzhang-elder_health-010-f",
        text: "幹，姑丈是不是要出道當教練了？",
        archetype: "backfire",
        retort: "（姑丈點頭稱是，繼續加速）",
      },
      {
        id: "guzhang-elder_health-010-g",
        text: "健走這麼快是要去哪裡比賽？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，只顧著走）",
      },
      {
        id: "guzhang-elder_health-010-h",
        text: "他媽的健走治不好血壓，死老頭別騙自己了。",
        archetype: "landmine",
        retort: "他臉一垮，猛地站起來罵人。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-011",
    text: "廟口那攤說的偏方，你要聽一下。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-011-a",
        text: "幹，廟口聽的跟詐騙電話有差嗎？",
        archetype: "perfect",
        retort: "他愣住，半天擠不出話。",
      },
      {
        id: "guzhang-elder_health-011-b",
        text: "姑丈在廟口人面真的很廣耶。",
        archetype: "deflect",
        retort: "那當然，退休就是要多交朋友。",
      },
      {
        id: "guzhang-elder_health-011-c",
        text: "靠，那攤老闆還說了什麼，講給我聽。",
        archetype: "deflect",
        retort: "他說的可多了，慢慢跟你講。",
      },
      {
        id: "guzhang-elder_health-011-d",
        text: "幹……喔好，我姑且聽聽看……",
        archetype: "meek",
        retort: "不是姑且，是要認真聽！",
      },
      {
        id: "guzhang-elder_health-011-e",
        text: "廟口那麼多人，我怕聽不清楚……",
        archetype: "meek",
        retort: "那你靠近一點聽，別怕人多。",
      },
      {
        id: "guzhang-elder_health-011-f",
        text: "幹，廟口的偏方是不是都要收驚費？",
        archetype: "backfire",
        retort: "（姑丈搖頭，覺得你不識貨）",
      },
      {
        id: "guzhang-elder_health-011-g",
        text: "偏方講久了會不會變真理啊？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續轉述）",
      },
      {
        id: "guzhang-elder_health-011-h",
        text: "去你的，你上次被騙也是聽人家說的吧。",
        archetype: "landmine",
        retort: "他吼一句幹恁娘，轉身走開。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-012",
    text: "來，教你拍打拉筋，全身都通。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-012-a",
        text: "靠北，這麼神怎麼沒拍醒你自己？",
        archetype: "perfect",
        retort: "他假笑，轉頭跟別人聊。",
      },
      {
        id: "guzhang-elder_health-012-b",
        text: "姑丈這招是跟哪位大師學的？",
        archetype: "deflect",
        retort: "網路影片自學的，很厲害吧。",
      },
      {
        id: "guzhang-elder_health-012-c",
        text: "靠，姑丈示範一次，我在旁邊看。",
        archetype: "deflect",
        retort: "好，你看仔細，這樣拍。",
      },
      {
        id: "guzhang-elder_health-012-d",
        text: "幹……拍下去有點痛耶，會瘀青嗎……",
        archetype: "meek",
        retort: "瘀青才代表有效果啦。",
      },
      {
        id: "guzhang-elder_health-012-e",
        text: "我手比較沒力，拍不太動……",
        archetype: "meek",
        retort: "那你多練練，慢慢會有力。",
      },
      {
        id: "guzhang-elder_health-012-f",
        text: "幹，拍成這樣是不是要去報警了？",
        archetype: "backfire",
        retort: "（姑丈一臉正經，沒聽懂笑點）",
      },
      {
        id: "guzhang-elder_health-012-g",
        text: "靠，拉筋拉到骨頭喀喀響很酷耶。",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍寶）",
      },
      {
        id: "guzhang-elder_health-012-h",
        text: "他媽的拍打拉筋，你信的都是唬爛的老東西。",
        archetype: "landmine",
        retort: "他臉一垮，甩開手罵三小。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-013",
    text: "甩手功來一百下，姑丈示範給你看。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-013-a",
        text: "幹，甩這麼勤怎麼沒甩掉高血壓？",
        archetype: "perfect",
        retort: "他語塞，清了清喉嚨。",
      },
      {
        id: "guzhang-elder_health-013-b",
        text: "姑丈甩得比我還標準耶。",
        archetype: "deflect",
        retort: "那當然，我練很久了。",
      },
      {
        id: "guzhang-elder_health-013-c",
        text: "靠，姑丈甩手功是跟誰學的啊？",
        archetype: "deflect",
        retort: "公園那個老師教的，很專業。",
      },
      {
        id: "guzhang-elder_health-013-d",
        text: "幹……才甩十下手就痠了，好累……",
        archetype: "meek",
        retort: "才十下就喊累，太年輕了吧。",
      },
      {
        id: "guzhang-elder_health-013-e",
        text: "動作我記不太住，姑丈再教一次……",
        archetype: "meek",
        retort: "好，我再示範一次給你看。",
      },
      {
        id: "guzhang-elder_health-013-f",
        text: "幹，甩成這樣是不是要飛起來了？",
        archetype: "backfire",
        retort: "（姑丈沒理你，繼續認真甩）",
      },
      {
        id: "guzhang-elder_health-013-g",
        text: "甩手功配薑黃是不是天下無敵？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始長篇分析）",
      },
      {
        id: "guzhang-elder_health-013-h",
        text: "去你的，甩手功年年甩，血壓年年高死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，撂下狠話。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-014",
    text: "睡前記得關wifi分享器，才好睡。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-014-a",
        text: "幹，關wifi助眠？你血壓才是禍首吧。",
        archetype: "perfect",
        retort: "他愣住，動作停在半空。",
      },
      {
        id: "guzhang-elder_health-014-b",
        text: "姑丈家的分享器都固定關嗎？",
        archetype: "deflect",
        retort: "每天九點準時關，很規律。",
      },
      {
        id: "guzhang-elder_health-014-c",
        text: "靠，姑丈教我怎麼設定定時關機。",
        archetype: "deflect",
        retort: "好，這功能很簡單，我教你。",
      },
      {
        id: "guzhang-elder_health-014-d",
        text: "幹……可是關了就不能追劇了……",
        archetype: "meek",
        retort: "追劇哪有睡眠重要啦。",
      },
      {
        id: "guzhang-elder_health-014-e",
        text: "我房間分享器不是我在管的……",
        archetype: "meek",
        retort: "那你去跟房東說一下嘛。",
      },
      {
        id: "guzhang-elder_health-014-f",
        text: "幹，那我乾脆睡覺前拔電源好了。",
        archetype: "backfire",
        retort: "（姑丈點頭，覺得你終於懂了）",
      },
      {
        id: "guzhang-elder_health-014-g",
        text: "wifi關了，鬼故事會不會找上門？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講輻射）",
      },
      {
        id: "guzhang-elder_health-014-h",
        text: "他媽的難怪姑姑把你群組設靜音，老東西。",
        archetype: "landmine",
        retort: "他臉一垮，重重罵一句幹。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-015",
    text: "電風扇不要吹整晚，很傷身體。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-015-a",
        text: "靠北，怕風扇？你比較該怕自己血壓。",
        archetype: "perfect",
        retort: "他訕訕地把話題帶過。",
      },
      {
        id: "guzhang-elder_health-015-b",
        text: "姑丈晚上都怎麼降溫的？",
        archetype: "deflect",
        retort: "我開一下下就關，你要學。",
      },
      {
        id: "guzhang-elder_health-015-c",
        text: "靠，姑丈幫我調一下風扇角度嘛。",
        archetype: "deflect",
        retort: "好，這樣吹比較均勻。",
      },
      {
        id: "guzhang-elder_health-015-d",
        text: "幹……可是不吹風扇我會很熱睡不著……",
        archetype: "meek",
        retort: "那你設定時器，別整晚開。",
      },
      {
        id: "guzhang-elder_health-015-e",
        text: "我房間沒冷氣，只能靠風扇……",
        archetype: "meek",
        retort: "那你要多蓋條毛巾被保暖。",
      },
      {
        id: "guzhang-elder_health-015-f",
        text: "幹，那我乾脆抱冰塊睡好了。",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不當一回事）",
      },
      {
        id: "guzhang-elder_health-015-g",
        text: "靠，風扇轉一整晚是不是會變仙人？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續叮嚀）",
      },
      {
        id: "guzhang-elder_health-015-h",
        text: "他媽的你的偏方跟風扇一樣，吹好玩的。",
        archetype: "landmine",
        retort: "他臉一垮，翻起去年的舊帳。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-016",
    text: "水果不要空腹吃，會傷胃知道嗎。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-016-a",
        text: "幹，空腹傷胃？空腹信謠言更傷。",
        archetype: "perfect",
        retort: "他語塞，臉紅了一下。",
      },
      {
        id: "guzhang-elder_health-016-b",
        text: "姑丈都幾點吃水果最養生？",
        archetype: "deflect",
        retort: "下午三點，剛剛好，你也學。",
      },
      {
        id: "guzhang-elder_health-016-c",
        text: "靠，姑丈幫我選一下要吃哪種水果。",
        archetype: "deflect",
        retort: "來，這顆芭樂最適合你。",
      },
      {
        id: "guzhang-elder_health-016-d",
        text: "幹……喔，我肚子餓才想吃水果耶……",
        archetype: "meek",
        retort: "餓也要忍一下，先吃飯。",
      },
      {
        id: "guzhang-elder_health-016-e",
        text: "我平常都亂吃，沒特別注意……",
        archetype: "meek",
        retort: "那你要開始注意了，別亂吃。",
      },
      {
        id: "guzhang-elder_health-016-f",
        text: "幹，那我把水果打成汁配飯吃好了。",
        archetype: "backfire",
        retort: "（姑丈一臉困惑，搖頭不語）",
      },
      {
        id: "guzhang-elder_health-016-g",
        text: "空腹吃水果是不是會變酸民？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續解釋原理）",
      },
      {
        id: "guzhang-elder_health-016-h",
        text: "去你的，這些說法跟你被騙那次一樣準死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，收拾東西就走。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-017",
    text: "隔夜菜到底能不能吃，我查給你聽。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-017-a",
        text: "幹，查這麼久怎麼沒查你的偏方？",
        archetype: "perfect",
        retort: "他愣住，眉頭皺了一下。",
      },
      {
        id: "guzhang-elder_health-017-b",
        text: "姑丈連這個都研究，太用心了。",
        archetype: "deflect",
        retort: "退休後時間多，當然要研究。",
      },
      {
        id: "guzhang-elder_health-017-c",
        text: "靠，那姑丈家的隔夜菜都怎麼處理？",
        archetype: "deflect",
        retort: "冰起來，隔天蒸熱再吃。",
      },
      {
        id: "guzhang-elder_health-017-d",
        text: "幹……喔好，那我等一下丟掉好了……",
        archetype: "meek",
        retort: "不用丟啦，聽我說完再決定。",
      },
      {
        id: "guzhang-elder_health-017-e",
        text: "我昨天的菜已經吃掉了耶……",
        archetype: "meek",
        retort: "那你要注意肚子有沒有不舒服。",
      },
      {
        id: "guzhang-elder_health-017-f",
        text: "幹，隔夜菜是不是會半夜自己動？",
        archetype: "backfire",
        retort: "（姑丈一臉正經，沒聽懂玩笑）",
      },
      {
        id: "guzhang-elder_health-017-g",
        text: "隔夜菜放越久是不是越入味？",
        archetype: "backfire",
        retort: "（姑丈搖頭，開始糾正你觀念）",
      },
      {
        id: "guzhang-elder_health-017-h",
        text: "他媽的查證這麼認真，怎麼還會被詐騙老不死？",
        archetype: "landmine",
        retort: "他臉一垮，罵你明年不用來了。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-018",
    text: "來，泡個生薑水，腳泡下去。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-018-a",
        text: "靠北，泡腳降火，先降降你的火氣吧。",
        archetype: "perfect",
        retort: "他語塞，找不到反駁的話。",
      },
      {
        id: "guzhang-elder_health-018-b",
        text: "姑丈這桶泡腳水好講究喔。",
        archetype: "deflect",
        retort: "那當然，材料都是精選的。",
      },
      {
        id: "guzhang-elder_health-018-c",
        text: "靠，姑丈平常泡多久，教教我。",
        archetype: "deflect",
        retort: "二十分鐘剛好，泡到微微出汗。",
      },
      {
        id: "guzhang-elder_health-018-d",
        text: "幹……水有點燙，我腳伸不進去……",
        archetype: "meek",
        retort: "加點冷水，別怕燙嘛。",
      },
      {
        id: "guzhang-elder_health-018-e",
        text: "我等一下要出門，沒時間泡……",
        archetype: "meek",
        retort: "那你回來再泡，別偷懶。",
      },
      {
        id: "guzhang-elder_health-018-f",
        text: "幹，泡完是不是會變成薑母鴨？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加薑片）",
      },
      {
        id: "guzhang-elder_health-018-g",
        text: "泡腳配薑黃是不是效果加倍？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始滔滔不絕）",
      },
      {
        id: "guzhang-elder_health-018-h",
        text: "去你的，泡腳降不了火，你血壓還是高。",
        archetype: "landmine",
        retort: "他臉一垮，狠狠瞪你罵三小。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-019",
    text: "這鍋綠豆湯解百毒，多喝一點。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-019-a",
        text: "他媽的解百毒？先解一下你的偏聽吧。",
        archetype: "perfect",
        retort: "姑姑在旁邊憋笑憋很辛苦。",
      },
      {
        id: "guzhang-elder_health-019-b",
        text: "姑丈煮的綠豆湯真的很香。",
        archetype: "deflect",
        retort: "那當然，我熬了三小時。",
      },
      {
        id: "guzhang-elder_health-019-c",
        text: "靠，姑丈教我怎麼煮這麼綿密。",
        archetype: "deflect",
        retort: "秘訣是小火慢熬，我教你。",
      },
      {
        id: "guzhang-elder_health-019-d",
        text: "幹……我喝甜的容易脹氣，喝一點就好……",
        archetype: "meek",
        retort: "脹氣才代表在排毒啦。",
      },
      {
        id: "guzhang-elder_health-019-e",
        text: "我剛喝過水，肚子有點滿了……",
        archetype: "meek",
        retort: "那你先放涼，等一下再喝。",
      },
      {
        id: "guzhang-elder_health-019-f",
        text: "幹，解百毒是不是連八卦都能解？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盛湯）",
      },
      {
        id: "guzhang-elder_health-019-g",
        text: "綠豆湯加薑黃會不會變綠色？",
        archetype: "backfire",
        retort: "（姑丈認真思考這個組合）",
      },
      {
        id: "guzhang-elder_health-019-h",
        text: "去死啦，解百毒怎麼解不了你愛轉發老東西？",
        archetype: "landmine",
        retort: "他氣到講台語，轉頭不說話。",
      },
    ],
  },
  {
    id: "guzhang-elder_health-020",
    text: "這篇食物相剋你看一下，很重要。",
    topic: "elder_health",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-elder_health-020-a",
        text: "幹，這篇文章跟你上次的謠言一樣。",
        archetype: "perfect",
        retort: "他愣住，手指抓了抓後腦。",
      },
      {
        id: "guzhang-elder_health-020-b",
        text: "姑丈的LINE收藏是不是有寶庫？",
        archetype: "deflect",
        retort: "那當然，都是精選文章。",
      },
      {
        id: "guzhang-elder_health-020-c",
        text: "靠，姑丈記得住這麼多組合，太強了。",
        archetype: "deflect",
        retort: "多看幾次就記住了，你也可以。",
      },
      {
        id: "guzhang-elder_health-020-d",
        text: "幹……我看不完啦，字好多……",
        archetype: "meek",
        retort: "慢慢看，這是為你好。",
      },
      {
        id: "guzhang-elder_health-020-e",
        text: "我昨天才把相剋的都吃在一起……",
        archetype: "meek",
        retort: "那你要多注意身體有沒有異狀。",
      },
      {
        id: "guzhang-elder_health-020-f",
        text: "幹，食物相剋是不是像武俠招式？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解禁忌）",
      },
      {
        id: "guzhang-elder_health-020-g",
        text: "這篇是不是跟上次那篇矛盾啊？",
        archetype: "backfire",
        retort: "（姑丈語塞，翻找上一篇文章）",
      },
      {
        id: "guzhang-elder_health-020-h",
        text: "他媽的這篇八成也是詐騙集團寫的老東西。",
        archetype: "landmine",
        retort: "他臉一垮，別開臉罵幹。",
      },
    ],
  },
] satisfies Question[];
