import type { Question } from "@/content/types";

// situations: 021 逼你陪吃薑母鴨 / 022 麻辣鍋加辣逼你吃 / 023 端出自釀梅酒
// 024 逼你吃最後一塊蘿蔔糕 / 025 逼你喝溫紹興酒 / 026 夾佛跳牆料硬塞
// 027 逼你再吃一顆水煮蛋 / 028 硬塞雞精給你 / 029 逼你吃炸蘿蔔球
// 030 逼你多喝一杯敬祖先 / 031 逼你吃湯裡中藥材 / 032 硬塞自己包的水餃
// 033 逼你續碗麵線 / 034 逼你喝一整碗魚湯 / 035 逼你吃完整盤滷味
export default [
  {
    id: "guzhang-food_push-021",
    text: "薑母鴨再夾一塊，冬天就是要進補。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-021-a",
        text: "冬天進補，補不了信謠言的毛病。",
        archetype: "perfect",
        retort: "他愣住，說不出話來。",
      },
      {
        id: "guzhang-food_push-021-b",
        text: "姑丈煮這鍋花了多久時間？",
        archetype: "deflect",
        retort: "燉了四小時，慢工出細活。",
      },
      {
        id: "guzhang-food_push-021-c",
        text: "姑丈教我怎麼喝湯才夠味。",
        archetype: "deflect",
        retort: "湯要先喝，我教你怎麼配。",
      },
      {
        id: "guzhang-food_push-021-d",
        text: "我剛吃了一塊，真的很飽很暖……",
        archetype: "meek",
        retort: "暖了才要再吃一塊，冬天嘛。",
      },
      {
        id: "guzhang-food_push-021-e",
        text: "我對薑味比較敏感，吃一點就好……",
        archetype: "meek",
        retort: "敏感也要習慣一下，很補的。",
      },
      {
        id: "guzhang-food_push-021-f",
        text: "吃完是不是全身會冒煙發熱？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續夾鴨肉）",
      },
      {
        id: "guzhang-food_push-021-g",
        text: "薑母鴨配薑黃是不是薑力全開？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真思考起來）",
      },
      {
        id: "guzhang-food_push-021-h",
        text: "燉四小時，燉不出一次準偏方。",
        archetype: "landmine",
        retort: "他臉一垮，半天說不出話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-022",
    text: "麻辣鍋加辣，過年就是要夠味。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-022-a",
        text: "夠味？你嘴巴才是全場最辣的。",
        archetype: "perfect",
        retort: "他語塞，乾笑兩聲。",
      },
      {
        id: "guzhang-food_push-022-b",
        text: "姑丈吃辣的功力真是驚人。",
        archetype: "deflect",
        retort: "那當然，年輕時練出來的。",
      },
      {
        id: "guzhang-food_push-022-c",
        text: "姑丈教我怎麼吃辣才不會辣到哭。",
        archetype: "deflect",
        retort: "配白飯吃，我教你這一招。",
      },
      {
        id: "guzhang-food_push-022-d",
        text: "我真的不太能吃辣，加一點就好……",
        archetype: "meek",
        retort: "一點哪算辣，多加才過癮。",
      },
      {
        id: "guzhang-food_push-022-e",
        text: "我腸胃比較弱，怕吃辣不舒服……",
        archetype: "meek",
        retort: "少量試試看，慢慢會習慣。",
      },
      {
        id: "guzhang-food_push-022-f",
        text: "加這麼辣是不是要噴火了？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加辣椒醬）",
      },
      {
        id: "guzhang-food_push-022-g",
        text: "麻辣配薑黃是不是雙倍刺激？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂搭配）",
      },
      {
        id: "guzhang-food_push-022-h",
        text: "加這麼辣，辣不醒你判斷力。",
        archetype: "landmine",
        retort: "他氣到講台語，轉身不理你。",
      },
    ],
  },
  {
    id: "guzhang-food_push-023",
    text: "自釀梅酒開瓶了，喝一小杯試試。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-023-a",
        text: "釀一年，釀不出一句可信的話。",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到肩膀抖。",
      },
      {
        id: "guzhang-food_push-023-b",
        text: "姑丈釀這罐花了多久時間？",
        archetype: "deflect",
        retort: "整整一年，急不得的。",
      },
      {
        id: "guzhang-food_push-023-c",
        text: "姑丈教我怎麼釀才會這麼甜。",
        archetype: "deflect",
        retort: "秘訣是糖跟梅子比例，我教你。",
      },
      {
        id: "guzhang-food_push-023-d",
        text: "我等一下還要騎車耶，喝一點點……",
        archetype: "meek",
        retort: "一點點沒關係啦，很順口的。",
      },
      {
        id: "guzhang-food_push-023-e",
        text: "我對酒精比較敏感，小口喝……",
        archetype: "meek",
        retort: "小口也算數，慢慢品嚐。",
      },
      {
        id: "guzhang-food_push-023-f",
        text: "喝完是不是會變成一顆梅子？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒下一杯）",
      },
      {
        id: "guzhang-food_push-023-g",
        text: "梅酒配薑黃是不是新口味？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-food_push-023-h",
        text: "釀這罐，跟你被騙那次一樣久。",
        archetype: "landmine",
        retort: "他臉一垮，要姑姑幫他評評理。",
      },
    ],
  },
  {
    id: "guzhang-food_push-024",
    text: "最後一塊蘿蔔糕別客氣，吃掉它。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-024-a",
        text: "煎這麼酥，酥不過你的偏方話術。",
        archetype: "perfect",
        retort: "他改口說我回去查查看。",
      },
      {
        id: "guzhang-food_push-024-b",
        text: "姑丈這塊蘿蔔糕是自己磨的嗎？",
        archetype: "deflect",
        retort: "那當然，蘿蔔絲都自己刨的。",
      },
      {
        id: "guzhang-food_push-024-c",
        text: "姑丈教我沾什麼醬料最搭。",
        archetype: "deflect",
        retort: "沾甜辣醬最對味，我教你。",
      },
      {
        id: "guzhang-food_push-024-d",
        text: "我已經吃了兩塊，真的很飽了……",
        archetype: "meek",
        retort: "兩塊哪夠，最後一塊也要吃。",
      },
      {
        id: "guzhang-food_push-024-e",
        text: "我在控制澱粉，吃半塊好嗎……",
        archetype: "meek",
        retort: "半塊太少，過年破例一次。",
      },
      {
        id: "guzhang-food_push-024-f",
        text: "最後一塊是不是要用猜拳決定？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，直接夾給你）",
      },
      {
        id: "guzhang-food_push-024-g",
        text: "蘿蔔糕配薑黃是不是黑暗料理？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太誇張）",
      },
      {
        id: "guzhang-food_push-024-h",
        text: "這塊蘿蔔糕，比你的偏方還真。",
        archetype: "landmine",
        retort: "他吼一句台語，甩門進房間。",
      },
    ],
  },
  {
    id: "guzhang-food_push-025",
    text: "紹興酒溫好了，這杯趁熱喝掉。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-025-a",
        text: "溫度抓這麼準，血壓抓不準吧。",
        archetype: "perfect",
        retort: "他訕笑，轉頭跟姑姑討救兵。",
      },
      {
        id: "guzhang-food_push-025-b",
        text: "姑丈溫酒的溫度怎麼抓的？",
        archetype: "deflect",
        retort: "隔水加熱，慢慢來，我教你。",
      },
      {
        id: "guzhang-food_push-025-c",
        text: "姑丈平常配什麼小菜喝紹興酒？",
        archetype: "deflect",
        retort: "配話梅最搭，來一起吃。",
      },
      {
        id: "guzhang-food_push-025-d",
        text: "我等一下要騎車，喝一點就好……",
        archetype: "meek",
        retort: "一點點不會怎樣，喝吧。",
      },
      {
        id: "guzhang-food_push-025-e",
        text: "我對紹興酒的味道不太習慣……",
        archetype: "meek",
        retort: "不習慣多喝幾次就習慣了。",
      },
      {
        id: "guzhang-food_push-025-f",
        text: "溫過的酒是不是能拿去泡澡？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂講）",
      },
      {
        id: "guzhang-food_push-025-g",
        text: "紹興酒配薑黃是不是新喝法？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真討論起來）",
      },
      {
        id: "guzhang-food_push-025-h",
        text: "溫這杯酒，溫不熱冷掉的偏方。",
        archetype: "landmine",
        retort: "他臉一垮，別過頭不看你。",
      },
    ],
  },
  {
    id: "guzhang-food_push-026",
    text: "佛跳牆夾一塊，這是年菜的靈魂。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-026-a",
        text: "料多得像寶藏，藏不住血壓高。",
        archetype: "perfect",
        retort: "他愣了一下，眉頭挑起來。",
      },
      {
        id: "guzhang-food_push-026-b",
        text: "姑丈這鍋燉了多久時間啊？",
        archetype: "deflect",
        retort: "一整天，火候得慢慢顧。",
      },
      {
        id: "guzhang-food_push-026-c",
        text: "姑丈幫我挑一塊最精華的料。",
        archetype: "deflect",
        retort: "好，這塊筍絲最入味，給你。",
      },
      {
        id: "guzhang-food_push-026-d",
        text: "我剛吃了很多菜，先吃一小塊……",
        archetype: "meek",
        retort: "一小塊哪夠，這麼多料。",
      },
      {
        id: "guzhang-food_push-026-e",
        text: "我對海鮮料比較不敢吃太多……",
        archetype: "meek",
        retort: "不敢吃也要試試味道嘛。",
      },
      {
        id: "guzhang-food_push-026-f",
        text: "佛跳牆是不是連佛都會餓？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續舀湯給你）",
      },
      {
        id: "guzhang-food_push-026-g",
        text: "佛跳牆配薑黃是不是超級版？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-food_push-026-h",
        text: "燉一整天，燉不出一次真話。",
        archetype: "landmine",
        retort: "他氣到講台語，說你很白目。",
      },
    ],
  },
  {
    id: "guzhang-food_push-027",
    text: "再吃一顆水煮蛋，補蛋白質。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-027-a",
        text: "算得這麼準，算算你血壓多高。",
        archetype: "perfect",
        retort: "他嘴硬，眼神卻閃躲。",
      },
      {
        id: "guzhang-food_push-027-b",
        text: "姑丈煮蛋的秒數是怎麼抓的？",
        archetype: "deflect",
        retort: "七分鐘，蛋黃剛好凝固。",
      },
      {
        id: "guzhang-food_push-027-c",
        text: "姑丈教我怎麼剝蛋殼才乾淨。",
        archetype: "deflect",
        retort: "先敲裂再剝，我教你這招。",
      },
      {
        id: "guzhang-food_push-027-d",
        text: "我已經吃兩顆了，真的飽了……",
        archetype: "meek",
        retort: "兩顆不夠啦，蛋白質要夠。",
      },
      {
        id: "guzhang-food_push-027-e",
        text: "我對蛋比較容易脹氣，吃一顆好……",
        archetype: "meek",
        retort: "脹氣也是消化，繼續吃。",
      },
      {
        id: "guzhang-food_push-027-f",
        text: "吃這麼多蛋是不是要孵小雞？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續剝蛋殼）",
      },
      {
        id: "guzhang-food_push-027-g",
        text: "水煮蛋配薑黃是不是變彩蛋？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個做法）",
      },
      {
        id: "guzhang-food_push-027-h",
        text: "煮這麼多蛋，煮不出判斷力。",
        archetype: "landmine",
        retort: "他臉一垮，轉頭找姑姑理論。",
      },
    ],
  },
  {
    id: "guzhang-food_push-028",
    text: "這罐雞精喝一瓶，補一下精神。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-028-a",
        text: "囤這麼多瓶，囤的都是心安而已。",
        archetype: "perfect",
        retort: "他愣住，手機螢幕暗掉。",
      },
      {
        id: "guzhang-food_push-028-b",
        text: "姑丈平常什麼時候喝雞精啊？",
        archetype: "deflect",
        retort: "熬夜隔天喝，效果最明顯。",
      },
      {
        id: "guzhang-food_push-028-c",
        text: "姑丈自己也天天喝一瓶嗎？",
        archetype: "deflect",
        retort: "當然，這是我的日常補品。",
      },
      {
        id: "guzhang-food_push-028-d",
        text: "我今天不算累，喝半瓶就好……",
        archetype: "meek",
        retort: "半瓶不夠力，整瓶喝完。",
      },
      {
        id: "guzhang-food_push-028-e",
        text: "我不太習慣這個味道，小口喝……",
        archetype: "meek",
        retort: "小口也要撐著喝完啦。",
      },
      {
        id: "guzhang-food_push-028-f",
        text: "喝完是不是會突然精神百倍尖叫？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續遞下一瓶）",
      },
      {
        id: "guzhang-food_push-028-g",
        text: "雞精配薑黃是不是究極補品？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真研究起來）",
      },
      {
        id: "guzhang-food_push-028-h",
        text: "喝這瓶，喝不出一次有效偏方。",
        archetype: "landmine",
        retort: "他臉一垮，冷著臉不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-029",
    text: "炸蘿蔔球剛起鍋，趁熱吃一顆。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-029-a",
        text: "炸這麼酥，酥不過你臉皮厚。",
        archetype: "perfect",
        retort: "他語塞，重新想措辭。",
      },
      {
        id: "guzhang-food_push-029-b",
        text: "姑丈炸這個油溫怎麼抓的？",
        archetype: "deflect",
        retort: "中火慢炸，我教你這一招。",
      },
      {
        id: "guzhang-food_push-029-c",
        text: "姑丈幫我挑一顆最酥脆的。",
        archetype: "deflect",
        retort: "好，這顆剛起鍋，給你。",
      },
      {
        id: "guzhang-food_push-029-d",
        text: "我剛吃很多炸物了，吃一顆就好……",
        archetype: "meek",
        retort: "一顆哪夠，趁熱多吃幾顆。",
      },
      {
        id: "guzhang-food_push-029-e",
        text: "我怕燙，等涼一點再吃……",
        archetype: "meek",
        retort: "涼了就不酥了，快趁熱吃。",
      },
      {
        id: "guzhang-food_push-029-f",
        text: "這球是不是能拿去打保齡球？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續炸下一批）",
      },
      {
        id: "guzhang-food_push-029-g",
        text: "蘿蔔球配薑黃是不是新吃法？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-food_push-029-h",
        text: "炸這顆，炸不出一次準消息。",
        archetype: "landmine",
        retort: "他氣到講台語，罵你不聽老人言。",
      },
    ],
  },
  {
    id: "guzhang-food_push-030",
    text: "再乾一杯高粱，敬一下列祖列宗。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-030-a",
        text: "敬祖先，先敬敬你自己的肝。",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到眼淚都出來。",
      },
      {
        id: "guzhang-food_push-030-b",
        text: "姑丈知道祖先以前的故事嗎？",
        archetype: "deflect",
        retort: "當然，來，我慢慢跟你講。",
      },
      {
        id: "guzhang-food_push-030-c",
        text: "姑丈先敬一杯，我在旁邊學。",
        archetype: "deflect",
        retort: "好，看好了，這才叫誠意。",
      },
      {
        id: "guzhang-food_push-030-d",
        text: "剛剛已經敬過了，這杯少一點……",
        archetype: "meek",
        retort: "敬祖先不能少，要滿杯。",
      },
      {
        id: "guzhang-food_push-030-e",
        text: "我用茶代替可以嗎，敬意一樣……",
        archetype: "meek",
        retort: "茶也行啦，心意到就好。",
      },
      {
        id: "guzhang-food_push-030-f",
        text: "祖先是不是也想喝點薑黃水？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太隨便）",
      },
      {
        id: "guzhang-food_push-030-g",
        text: "敬祖先是不是要敬滿一百杯？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒滿）",
      },
      {
        id: "guzhang-food_push-030-h",
        text: "敬這麼多杯，敬出來的只有血壓。",
        archetype: "landmine",
        retort: "他臉一垮，猛地站起來。",
      },
    ],
  },
  {
    id: "guzhang-food_push-031",
    text: "湯裡的當歸枸杞也要吃，不能挑掉。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-031-a",
        text: "藥材下得道地，判斷力不道地。",
        archetype: "perfect",
        retort: "他愣住，半天擠不出一句話。",
      },
      {
        id: "guzhang-food_push-031-b",
        text: "姑丈是跟哪個中藥行買材料的？",
        archetype: "deflect",
        retort: "巷口那間，老闆很有信譽。",
      },
      {
        id: "guzhang-food_push-031-c",
        text: "姑丈教我怎麼分辨當歸跟枸杞。",
        archetype: "deflect",
        retort: "好，這片是當歸，我教你認。",
      },
      {
        id: "guzhang-food_push-031-d",
        text: "藥材味有點重，我挑一點出來……",
        archetype: "meek",
        retort: "挑什麼挑，這才是精華。",
      },
      {
        id: "guzhang-food_push-031-e",
        text: "我怕苦味，先喝湯就好……",
        archetype: "meek",
        retort: "不苦啦，你吃吃看就知道。",
      },
      {
        id: "guzhang-food_push-031-f",
        text: "吃完是不是能開一間中藥行？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續舀湯給你）",
      },
      {
        id: "guzhang-food_push-031-g",
        text: "當歸配薑黃是不是究極藥膳？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真討論起來）",
      },
      {
        id: "guzhang-food_push-031-h",
        text: "燉這鍋，燉不出一次準偏方。",
        archetype: "landmine",
        retort: "他吼一句台語，轉身走開。",
      },
    ],
  },
  {
    id: "guzhang-food_push-032",
    text: "這是我自己包的水餃，吃幾顆看看。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-032-a",
        text: "包這麼扎實，扎實不了你的偏方。",
        archetype: "perfect",
        retort: "他假笑，轉頭跟別人聊。",
      },
      {
        id: "guzhang-food_push-032-b",
        text: "姑丈這摺法真的很有水準。",
        archetype: "deflect",
        retort: "那當然，練了幾十年的手藝。",
      },
      {
        id: "guzhang-food_push-032-c",
        text: "姑丈教我怎麼包才不會露餡。",
        archetype: "deflect",
        retort: "好，皮邊要捏緊，我教你。",
      },
      {
        id: "guzhang-food_push-032-d",
        text: "我剛吃很多了，吃幾顆就好……",
        archetype: "meek",
        retort: "幾顆不夠，多吃才夠意思。",
      },
      {
        id: "guzhang-food_push-032-e",
        text: "我對韭菜餡比較不敢吃太多……",
        archetype: "meek",
        retort: "不敢吃也要嘗嘗看嘛。",
      },
      {
        id: "guzhang-food_push-032-f",
        text: "這顆是不是包了整個宇宙的餡？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續夾給你）",
      },
      {
        id: "guzhang-food_push-032-g",
        text: "水餃配薑黃是不是異國創意料理？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-food_push-032-h",
        text: "包這麼多顆，包不出一句真話。",
        archetype: "landmine",
        retort: "他臉一垮，甩開手不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-033",
    text: "麵線再續一碗，長長久久嘛。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-033-a",
        text: "長長久久，久不過偏方沒效。",
        archetype: "perfect",
        retort: "他語塞，清了清喉嚨。",
      },
      {
        id: "guzhang-food_push-033-b",
        text: "姑丈這碗湯頭是怎麼熬的？",
        archetype: "deflect",
        retort: "柴魚跟大骨一起熬，我教你。",
      },
      {
        id: "guzhang-food_push-033-c",
        text: "姑丈幫我加點滷汁提味嘛。",
        archetype: "deflect",
        retort: "好，這樣加才夠香，來。",
      },
      {
        id: "guzhang-food_push-033-d",
        text: "我已經吃一碗了，真的飽了……",
        archetype: "meek",
        retort: "一碗哪夠，長長久久要多吃。",
      },
      {
        id: "guzhang-food_push-033-e",
        text: "我對麵線比較沒特別想吃……",
        archetype: "meek",
        retort: "沒興趣也要吃一點取吉利。",
      },
      {
        id: "guzhang-food_push-033-f",
        text: "續碗是不是代表壽命變更長？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盛給你）",
      },
      {
        id: "guzhang-food_push-033-g",
        text: "麵線配薑黃是不是變黃金麵線？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真考慮起來）",
      },
      {
        id: "guzhang-food_push-033-h",
        text: "續這碗，續不出你判斷力。",
        archetype: "landmine",
        retort: "他氣到講台語，撂下一句狠話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-034",
    text: "這整碗魚湯喝完，吃魚才會有餘。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-034-a",
        text: "年年有餘，餘不下你判斷力。",
        archetype: "perfect",
        retort: "他愣住，動作停在半空。",
      },
      {
        id: "guzhang-food_push-034-b",
        text: "姑丈這魚是在哪裡買的啊？",
        archetype: "deflect",
        retort: "早市買的，新鮮才夠味。",
      },
      {
        id: "guzhang-food_push-034-c",
        text: "姑丈教我怎麼喝湯才不會有腥味。",
        archetype: "deflect",
        retort: "先喝湯再吃肉，我教你順序。",
      },
      {
        id: "guzhang-food_push-034-d",
        text: "我已經喝了雞湯，肚子有點滿……",
        archetype: "meek",
        retort: "滿了也要喝，年年有餘啊。",
      },
      {
        id: "guzhang-food_push-034-e",
        text: "我對魚腥味比較敏感，喝一點……",
        archetype: "meek",
        retort: "一點也要喝完，別浪費。",
      },
      {
        id: "guzhang-food_push-034-f",
        text: "喝完是不是會突然變成美人魚？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盛湯給你）",
      },
      {
        id: "guzhang-food_push-034-g",
        text: "魚湯配薑黃是不是金黃色湯頭？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個做法）",
      },
      {
        id: "guzhang-food_push-034-h",
        text: "喝這碗，喝不出一次準消息。",
        archetype: "landmine",
        retort: "他臉一垮，重重嘆了口氣。",
      },
    ],
  },
  {
    id: "guzhang-food_push-035",
    text: "這盤滷味吃完，過年才有好兆頭。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-035-a",
        text: "滷十年的老滷，滷不出新判斷力。",
        archetype: "perfect",
        retort: "他訕訕地把話題帶過。",
      },
      {
        id: "guzhang-food_push-035-b",
        text: "姑丈這滷汁是傳幾代的秘方？",
        archetype: "deflect",
        retort: "從我爸那代傳下來的，寶貝呢。",
      },
      {
        id: "guzhang-food_push-035-c",
        text: "姑丈幫我挑幾樣最入味的。",
        archetype: "deflect",
        retort: "好，這幾樣最軟最香，給你。",
      },
      {
        id: "guzhang-food_push-035-d",
        text: "我已經吃很多了，吃幾樣就好……",
        archetype: "meek",
        retort: "幾樣哪夠，整盤都要吃完。",
      },
      {
        id: "guzhang-food_push-035-e",
        text: "我對內臟類比較不敢吃太多……",
        archetype: "meek",
        retort: "不敢吃也要試試看好料。",
      },
      {
        id: "guzhang-food_push-035-f",
        text: "吃完整盤是不是能開滷味攤？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續夾給你）",
      },
      {
        id: "guzhang-food_push-035-g",
        text: "滷味配薑黃是不是十年老滷2.0？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真考慮起來）",
      },
      {
        id: "guzhang-food_push-035-h",
        text: "吃這盤，吃不出朋友的朋友。",
        archetype: "landmine",
        retort: "他臉一垮，翻起去年的舊帳。",
      },
    ],
  },
] satisfies Question[];
