import type { Question } from "@/content/types";

// situations: 001 倒高粱要你乾杯 / 002 倒台灣啤酒續杯 / 003 盛雞湯逼你喝完
// 004 夾菜要你再吃一碗飯 / 005 切水果硬塞給你 / 006 火鍋料一直加進碗裡
// 007 烤肉攤前逼你吃第二份 / 008 開紅酒要你陪喝 / 009 甜湯圓再來一碗
// 010 花生瓜子硬塞 / 011 逼你吃他滷的豬腳 / 012 端出自製藥酒要你嚐
// 013 尾牙式勸酒繞桌 / 014 敬酒繞桌輪一圈 / 015 逼你吃鄰居送的伴手禮
// 016 年糕再切一塊 / 017 燒酒雞鍋底加料 / 018 逼你喝完保久乳
// 019 夜市買的香腸硬塞 / 020 逼你吃轉大人補品
export default [
  {
    id: "guzhang-food_push-001",
    text: "來，高粱倒滿，這杯乾了才是男人。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-001-a",
        text: "乾杯是男人？那你怎麼血壓超標？",
        archetype: "perfect",
        retort: "他愣住，半天擠不出一句話。",
      },
      {
        id: "guzhang-food_push-001-b",
        text: "姑丈的酒量真的是傳說等級。",
        archetype: "deflect",
        retort: "那當然，年輕時練出來的。",
      },
      {
        id: "guzhang-food_push-001-c",
        text: "姑丈教我怎麼喝才不會醉。",
        archetype: "deflect",
        retort: "來，小口小口喝，我教你。",
      },
      {
        id: "guzhang-food_push-001-d",
        text: "我等一下要開車，喝一點就好……",
        archetype: "meek",
        retort: "一點點沒關係啦，喝喝喝。",
      },
      {
        id: "guzhang-food_push-001-e",
        text: "我酒量真的不好，會臉紅……",
        archetype: "meek",
        retort: "臉紅代表氣血循環好，喝！",
      },
      {
        id: "guzhang-food_push-001-f",
        text: "我用茶代替，感情一樣深啦哈哈。",
        archetype: "backfire",
        retort: "（姑丈搖頭，覺得你不夠意思）",
      },
      {
        id: "guzhang-food_push-001-g",
        text: "高粱是不是能拿去消毒傷口？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒酒）",
      },
      {
        id: "guzhang-food_push-001-h",
        text: "你那身血壓，是乾出來的吧姑丈。",
        archetype: "landmine",
        retort: "他吼一句台語，轉身走開。",
      },
    ],
  },
  {
    id: "guzhang-food_push-002",
    text: "啤酒續杯，這罐開了不喝完浪費。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-002-a",
        text: "怕浪費？你那些偏方才真的浪費。",
        archetype: "perfect",
        retort: "他假笑，轉頭跟別人聊。",
      },
      {
        id: "guzhang-food_push-002-b",
        text: "姑丈開瓶技術真的很俐落耶。",
        archetype: "deflect",
        retort: "那當然，開瓶器都自己選的。",
      },
      {
        id: "guzhang-food_push-002-c",
        text: "姑丈平常都配什麼下酒菜啊？",
        archetype: "deflect",
        retort: "花生最搭，來，配著喝。",
      },
      {
        id: "guzhang-food_push-002-d",
        text: "我已經有點脹了，喝一半就好……",
        archetype: "meek",
        retort: "一半太少了，再多喝一點。",
      },
      {
        id: "guzhang-food_push-002-e",
        text: "我等一下要騎車回家……",
        archetype: "meek",
        retort: "那你留下來過夜就好啦。",
      },
      {
        id: "guzhang-food_push-002-f",
        text: "啤酒配薑黃是不是更養生？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始認真思考）",
      },
      {
        id: "guzhang-food_push-002-g",
        text: "開了不喝完是不是會被罰站？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒進杯子）",
      },
      {
        id: "guzhang-food_push-002-h",
        text: "你肝那麼硬，是被你自己灌壞的。",
        archetype: "landmine",
        retort: "他臉一垮，甩開手不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-003",
    text: "這碗雞湯喝完，一滴都不能留。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-003-a",
        text: "燉三小時，燉得出血壓正常嗎？",
        archetype: "perfect",
        retort: "他語塞，清了清喉嚨。",
      },
      {
        id: "guzhang-food_push-003-b",
        text: "姑丈燉湯的秘訣是什麼啊？",
        archetype: "deflect",
        retort: "秘訣是耐心，慢火慢熬。",
      },
      {
        id: "guzhang-food_push-003-c",
        text: "這湯配薑黃是不是更有味道？",
        archetype: "deflect",
        retort: "有加喔，你喝得出來嗎？",
      },
      {
        id: "guzhang-food_push-003-d",
        text: "我肚子已經很飽了，喝一半好嗎……",
        archetype: "meek",
        retort: "一半怎麼行，這麼補的湯。",
      },
      {
        id: "guzhang-food_push-003-e",
        text: "有點燙，我等一下慢慢喝……",
        archetype: "meek",
        retort: "快喝，涼了就不好喝了。",
      },
      {
        id: "guzhang-food_push-003-f",
        text: "喝完是不是能長出雞翅膀？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盛湯）",
      },
      {
        id: "guzhang-food_push-003-g",
        text: "這湯是不是能拿去參加比賽？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在敷衍）",
      },
      {
        id: "guzhang-food_push-003-h",
        text: "這湯再補，也補不回你判斷力。",
        archetype: "landmine",
        retort: "他氣到講台語，撂下一句狠話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-004",
    text: "再吃一碗飯，配這道菜剛剛好。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-004-a",
        text: "過年吃三碗，是怕紅包吃不夠本？",
        archetype: "perfect",
        retort: "他愣住，動作停在半空。",
      },
      {
        id: "guzhang-food_push-004-b",
        text: "姑丈這道菜是自己滷的嗎？",
        archetype: "deflect",
        retort: "那當然，滷了一整個下午。",
      },
      {
        id: "guzhang-food_push-004-c",
        text: "姑丈幫我盛，這樣才有過年感。",
        archetype: "deflect",
        retort: "好，來，姑丈盛給你最豪邁。",
      },
      {
        id: "guzhang-food_push-004-d",
        text: "我剛吃了兩碗，真的飽了……",
        archetype: "meek",
        retort: "才兩碗，過年要吃三碗才夠。",
      },
      {
        id: "guzhang-food_push-004-e",
        text: "我在控制澱粉，少吃一點……",
        archetype: "meek",
        retort: "過年不用控制啦，吃！",
      },
      {
        id: "guzhang-food_push-004-f",
        text: "再吃一碗是不是要辦大胃王賽？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盛飯）",
      },
      {
        id: "guzhang-food_push-004-g",
        text: "吃這麼多是不是要練舉重？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在打岔）",
      },
      {
        id: "guzhang-food_push-004-h",
        text: "吃這麼多，判斷力倒一口都沒有。",
        archetype: "landmine",
        retort: "他臉一垮，重重嘆了口氣。",
      },
    ],
  },
  {
    id: "guzhang-food_push-005",
    text: "水果切好了，這盤芭樂全部吃完。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-005-a",
        text: "刀工這麼細，怎麼識人這麼粗？",
        archetype: "perfect",
        retort: "他訕訕地把話題帶過。",
      },
      {
        id: "guzhang-food_push-005-b",
        text: "姑丈切水果的手藝真的一流。",
        archetype: "deflect",
        retort: "那當然，退休生活多練習。",
      },
      {
        id: "guzhang-food_push-005-c",
        text: "姑丈教我怎麼切才不會歪。",
        archetype: "deflect",
        retort: "好，來，我示範一次給你看。",
      },
      {
        id: "guzhang-food_push-005-d",
        text: "我剛吃很飽，先吃幾片就好……",
        archetype: "meek",
        retort: "幾片怎麼夠，這麼大盤。",
      },
      {
        id: "guzhang-food_push-005-e",
        text: "我對芭樂比較沒興趣，吃一點……",
        archetype: "meek",
        retort: "多吃一點，對身體才好。",
      },
      {
        id: "guzhang-food_push-005-f",
        text: "吃完是不是要負責洗籽？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續切下一顆）",
      },
      {
        id: "guzhang-food_push-005-g",
        text: "芭樂配薑黃是不是新吃法？",
        archetype: "backfire",
        retort: "（姑丈認真考慮這個組合）",
      },
      {
        id: "guzhang-food_push-005-h",
        text: "這盤芭樂，比你的偏方還有用。",
        archetype: "landmine",
        retort: "他臉一垮，翻起去年的舊帳。",
      },
    ],
  },
  {
    id: "guzhang-food_push-006",
    text: "火鍋料一直加，這丸子也給你吃。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-006-a",
        text: "料加這麼多，是想淹死我的碗？",
        archetype: "perfect",
        retort: "他語塞，臉紅了一下。",
      },
      {
        id: "guzhang-food_push-006-b",
        text: "姑丈最愛吃哪個料，先讓給你。",
        archetype: "deflect",
        retort: "哎唷，你這麼貼心，來一起吃。",
      },
      {
        id: "guzhang-food_push-006-c",
        text: "姑丈教我怎麼涮才不會老。",
        archetype: "deflect",
        retort: "秒數要抓好，我教你涮法。",
      },
      {
        id: "guzhang-food_push-006-d",
        text: "碗裡已經滿出來了，吃不完……",
        archetype: "meek",
        retort: "滿出來才夠味，快吃。",
      },
      {
        id: "guzhang-food_push-006-e",
        text: "我對海鮮丸子比較沒興趣……",
        archetype: "meek",
        retort: "沒興趣也要試試看嘛。",
      },
      {
        id: "guzhang-food_push-006-f",
        text: "碗都快滿到姑丈臉了哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加料）",
      },
      {
        id: "guzhang-food_push-006-g",
        text: "這樣加是不是要開火鍋店？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不領情）",
      },
      {
        id: "guzhang-food_push-006-h",
        text: "料越加越多，你的謠言也是。",
        archetype: "landmine",
        retort: "他氣到講台語，收拾東西就走。",
      },
    ],
  },
  {
    id: "guzhang-food_push-007",
    text: "烤肉再吃一份，這攤位是我顧的。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-007-a",
        text: "顧攤位這麼久，顧得了血壓嗎？",
        archetype: "perfect",
        retort: "他愣住，眉頭皺了一下。",
      },
      {
        id: "guzhang-food_push-007-b",
        text: "姑丈烤肉手藝可以去擺攤了。",
        archetype: "deflect",
        retort: "退休生活嘛，多練幾手。",
      },
      {
        id: "guzhang-food_push-007-c",
        text: "姑丈教我怎麼烤才不會焦。",
        archetype: "deflect",
        retort: "好，火不要太大，我教你。",
      },
      {
        id: "guzhang-food_push-007-d",
        text: "我剛吃了一份，真的很飽……",
        archetype: "meek",
        retort: "一份哪夠，過年就是要多吃。",
      },
      {
        id: "guzhang-food_push-007-e",
        text: "我在控制熱量，少吃烤肉……",
        archetype: "meek",
        retort: "控制什麼，過年破例一次。",
      },
      {
        id: "guzhang-food_push-007-f",
        text: "再吃是不是要付攤位費啊哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續翻面烤肉）",
      },
      {
        id: "guzhang-food_push-007-g",
        text: "烤肉配薑黃是不是新吃法？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-food_push-007-h",
        text: "烤這麼多份，烤不熟你的偏方。",
        archetype: "landmine",
        retort: "他臉一垮，說明年不用來了。",
      },
    ],
  },
  {
    id: "guzhang-food_push-008",
    text: "開瓶紅酒，難得過年陪姑丈喝一杯。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-008-a",
        text: "敬退休精彩，先敬血壓別破表。",
        archetype: "perfect",
        retort: "他語塞，找不到反駁的話。",
      },
      {
        id: "guzhang-food_push-008-b",
        text: "姑丈這瓶紅酒是哪裡買的？",
        archetype: "deflect",
        retort: "朋友送的，年份還不錯呢。",
      },
      {
        id: "guzhang-food_push-008-c",
        text: "姑丈教我怎麼品酒才專業。",
        archetype: "deflect",
        retort: "來，先聞香再入口，我教你。",
      },
      {
        id: "guzhang-food_push-008-d",
        text: "我對紅酒沒研究，喝一小口……",
        archetype: "meek",
        retort: "一小口太少，多喝一點。",
      },
      {
        id: "guzhang-food_push-008-e",
        text: "我等一下要幫忙洗碗，先不喝……",
        archetype: "meek",
        retort: "洗碗等一下，先喝再說。",
      },
      {
        id: "guzhang-food_push-008-f",
        text: "紅酒配薑黃是不是變成藥酒？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始認真討論）",
      },
      {
        id: "guzhang-food_push-008-g",
        text: "紅酒杯是不是要拿去養魚？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不識貨）",
      },
      {
        id: "guzhang-food_push-008-h",
        text: "喝這杯，你血壓比酒還紅吧。",
        archetype: "landmine",
        retort: "他臉一垮，狠狠瞪你一眼。",
      },
    ],
  },
  {
    id: "guzhang-food_push-009",
    text: "甜湯圓再來一碗，圓圓滿滿嘛。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-009-a",
        text: "圓圓滿滿，滿不過你嘴巴會講。",
        archetype: "perfect",
        retort: "姑姑在旁邊憋笑憋很辛苦。",
      },
      {
        id: "guzhang-food_push-009-b",
        text: "姑丈搓湯圓的手藝真不錯。",
        archetype: "deflect",
        retort: "那當然，搓了一整個下午。",
      },
      {
        id: "guzhang-food_push-009-c",
        text: "姑丈教我怎麼搓才會圓。",
        archetype: "deflect",
        retort: "好，來，手心這樣轉，我教你。",
      },
      {
        id: "guzhang-food_push-009-d",
        text: "我已經吃一碗了，真的很甜很飽……",
        archetype: "meek",
        retort: "甜才有福氣，再吃一碗。",
      },
      {
        id: "guzhang-food_push-009-e",
        text: "我怕太甜，晚上會睡不著……",
        archetype: "meek",
        retort: "睡不著就再吃一碗提神。",
      },
      {
        id: "guzhang-food_push-009-f",
        text: "湯圓是不是能拿去打乒乓球？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續舀湯圓）",
      },
      {
        id: "guzhang-food_push-009-g",
        text: "圓圓滿滿是不是也代表我要變圓？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你想太多）",
      },
      {
        id: "guzhang-food_push-009-h",
        text: "你煮的湯圓，沒一顆比你可信。",
        archetype: "landmine",
        retort: "他氣到講台語，轉頭不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-010",
    text: "花生瓜子抓一把，配電視配到底。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-010-a",
        text: "嗑瓜子的功夫，怎麼不拿去查證？",
        archetype: "perfect",
        retort: "他愣住，手指抓了抓後腦。",
      },
      {
        id: "guzhang-food_push-010-b",
        text: "姑丈嗑瓜子的速度真的驚人。",
        archetype: "deflect",
        retort: "那當然，練了幾十年的功夫。",
      },
      {
        id: "guzhang-food_push-010-c",
        text: "姑丈教我怎麼嗑才不會咬到殼。",
        archetype: "deflect",
        retort: "來，用門牙輕輕一咬，我教你。",
      },
      {
        id: "guzhang-food_push-010-d",
        text: "我剛吃完飯，先不吃零食好了……",
        archetype: "meek",
        retort: "零食是配電視用的，吃啦。",
      },
      {
        id: "guzhang-food_push-010-e",
        text: "我吃瓜子牙齒會痠，吃花生就好……",
        archetype: "meek",
        retort: "那你就多吃花生，別客氣。",
      },
      {
        id: "guzhang-food_push-010-f",
        text: "嗑瓜子是不是能練出鋼牙？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續嗑瓜子）",
      },
      {
        id: "guzhang-food_push-010-g",
        text: "殼堆這麼多是不是能蓋房子？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍寶）",
      },
      {
        id: "guzhang-food_push-010-h",
        text: "嗑這堆殼，也嗑不出一句真話。",
        archetype: "landmine",
        retort: "他臉一垮，別開臉不吭聲。",
      },
    ],
  },
  {
    id: "guzhang-food_push-011",
    text: "這鍋滷豬腳吃一支，補膠原蛋白。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-011-a",
        text: "補膠原蛋白，先補一下耳根子。",
        archetype: "perfect",
        retort: "他語塞，假裝在看別的地方。",
      },
      {
        id: "guzhang-food_push-011-b",
        text: "姑丈滷豬腳的秘方能透露嗎？",
        archetype: "deflect",
        retort: "秘方就是耐心，慢慢滷四小時。",
      },
      {
        id: "guzhang-food_push-011-c",
        text: "姑丈幫我挑一支肉最多的。",
        archetype: "deflect",
        retort: "好，這支給你，肉最厚。",
      },
      {
        id: "guzhang-food_push-011-d",
        text: "我剛吃很多菜了，先吃半支好嗎……",
        archetype: "meek",
        retort: "半支怎麼夠，這麼補的東西。",
      },
      {
        id: "guzhang-food_push-011-e",
        text: "我對滷味比較不敢吃太多……",
        archetype: "meek",
        retort: "不敢吃也要試試看嘛。",
      },
      {
        id: "guzhang-food_push-011-f",
        text: "吃完是不是皮膚會變豬皮亮？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續夾豬腳）",
      },
      {
        id: "guzhang-food_push-011-g",
        text: "滷豬腳配薑黃是不是更補？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真思考起來）",
      },
      {
        id: "guzhang-food_push-011-h",
        text: "滷四小時，滷不出一次準偏方。",
        archetype: "landmine",
        retort: "他吼一句台語，摔門進房。",
      },
    ],
  },
  {
    id: "guzhang-food_push-012",
    text: "這罐藥酒嚐一口，我自己泡的。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-012-a",
        text: "自己泡的？跟朋友的朋友一樣可疑。",
        archetype: "perfect",
        retort: "他愣住，表情僵了一下。",
      },
      {
        id: "guzhang-food_push-012-b",
        text: "姑丈這罐泡了多久，好講究。",
        archetype: "deflect",
        retort: "泡了一年多，材料都精選的。",
      },
      {
        id: "guzhang-food_push-012-c",
        text: "姑丈教我怎麼分辨泡得夠不夠。",
        archetype: "deflect",
        retort: "顏色要深，聞起來要香，我教你。",
      },
      {
        id: "guzhang-food_push-012-d",
        text: "味道有點嗆，我小口喝就好……",
        archetype: "meek",
        retort: "嗆才有效果，多喝一口。",
      },
      {
        id: "guzhang-food_push-012-e",
        text: "我對藥酒不太熟，怕喝出問題……",
        archetype: "meek",
        retort: "沒事的，一小杯不會怎樣。",
      },
      {
        id: "guzhang-food_push-012-f",
        text: "這味道，我拿去泡腳好了。",
        archetype: "backfire",
        retort: "（姑丈皺眉，把罐子收回去）",
      },
      {
        id: "guzhang-food_push-012-g",
        text: "藥酒配薑黃是不是究極版？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，開始長篇解說）",
      },
      {
        id: "guzhang-food_push-012-h",
        text: "這罐藥酒，比你信的謠言可疑。",
        archetype: "landmine",
        retort: "他臉一垮，冷笑一聲不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-013",
    text: "尾牙式敬酒，繞一圈每人都要喝。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-013-a",
        text: "繞一圈敬酒，繞不出血壓正常。",
        archetype: "perfect",
        retort: "他訕笑，改口說算你厲害。",
      },
      {
        id: "guzhang-food_push-013-b",
        text: "姑丈這敬酒詞是不是每年都不同？",
        archetype: "deflect",
        retort: "那當然，每年都要與時俱進。",
      },
      {
        id: "guzhang-food_push-013-c",
        text: "姑丈先敬一輪，我在旁邊學。",
        archetype: "deflect",
        retort: "好，看好了，這才叫氣勢。",
      },
      {
        id: "guzhang-food_push-013-d",
        text: "繞一圈我已經喝三杯了，有點暈……",
        archetype: "meek",
        retort: "暈才代表氣氛到位，繼續！",
      },
      {
        id: "guzhang-food_push-013-e",
        text: "我用可樂代替可以嗎……",
        archetype: "meek",
        retort: "可樂也行，心意最重要。",
      },
      {
        id: "guzhang-food_push-013-f",
        text: "這樣繞圈是不是在跳土風舞？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒下一杯）",
      },
      {
        id: "guzhang-food_push-013-g",
        text: "敬酒是不是能算運動量？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在唱反調）",
      },
      {
        id: "guzhang-food_push-013-h",
        text: "敬成這樣，你肝比立場還硬。",
        archetype: "landmine",
        retort: "他氣到講台語，罵你講話白目。",
      },
    ],
  },
  {
    id: "guzhang-food_push-014",
    text: "來，敬酒輪到你，這杯不能少。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-014-a",
        text: "這杯不能少，判斷力倒缺很多。",
        archetype: "perfect",
        retort: "他語塞，講到一半改口。",
      },
      {
        id: "guzhang-food_push-014-b",
        text: "姑丈是不是每桌都要敬一輪？",
        archetype: "deflect",
        retort: "那當然，這是我的堅持。",
      },
      {
        id: "guzhang-food_push-014-c",
        text: "姑丈教我怎麼敬酒才有禮貌。",
        archetype: "deflect",
        retort: "杯子要低一點，我教你。",
      },
      {
        id: "guzhang-food_push-014-d",
        text: "剛剛已經敬過一輪了，真的飽和了……",
        archetype: "meek",
        retort: "飽和也要再乾一杯啊。",
      },
      {
        id: "guzhang-food_push-014-e",
        text: "我等一下要開車回台北……",
        archetype: "meek",
        retort: "那你今晚別開車，留下來。",
      },
      {
        id: "guzhang-food_push-014-f",
        text: "敬酒是不是可以用眼神代替？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太隨便）",
      },
      {
        id: "guzhang-food_push-014-g",
        text: "杯子這麼小是不是要喝一百杯？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續倒滿）",
      },
      {
        id: "guzhang-food_push-014-h",
        text: "喝這麼多年，喝出的只有血壓高。",
        archetype: "landmine",
        retort: "他臉一垮，起身走去別桌。",
      },
    ],
  },
  {
    id: "guzhang-food_push-015",
    text: "鄰居送的伴手禮吃一塊，人情要顧。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-015-a",
        text: "人情要顧，你的耳根更該顧好。",
        archetype: "perfect",
        retort: "他愣住，話卡在喉嚨。",
      },
      {
        id: "guzhang-food_push-015-b",
        text: "姑丈跟鄰居感情真的很好耶。",
        archetype: "deflect",
        retort: "那當然，遠親不如近鄰。",
      },
      {
        id: "guzhang-food_push-015-c",
        text: "姑丈幫我挑一塊你最愛的口味。",
        archetype: "deflect",
        retort: "好，這塊芋頭餡的最讚。",
      },
      {
        id: "guzhang-food_push-015-d",
        text: "我剛吃了很多甜的，先吃半塊……",
        archetype: "meek",
        retort: "半塊哪算數，整塊吃完。",
      },
      {
        id: "guzhang-food_push-015-e",
        text: "我對這口味不太熟，先試一口……",
        archetype: "meek",
        retort: "試一口也要吃完，別浪費。",
      },
      {
        id: "guzhang-food_push-015-f",
        text: "吃完是不是要回禮包個紅包？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續切下一塊）",
      },
      {
        id: "guzhang-food_push-015-g",
        text: "這禮盒是不是也送了薑黃口味？",
        archetype: "backfire",
        retort: "（姑丈認真翻找禮盒內容物）",
      },
      {
        id: "guzhang-food_push-015-h",
        text: "這禮盒，跟朋友的朋友一樣不存在。",
        archetype: "landmine",
        retort: "他氣到講台語，說你沒大沒小。",
      },
    ],
  },
  {
    id: "guzhang-food_push-016",
    text: "年糕再切一塊，年年高升就靠這個。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-016-a",
        text: "年年高升，升不了你判斷力。",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到快岔氣。",
      },
      {
        id: "guzhang-food_push-016-b",
        text: "姑丈煎年糕的火候真的到位。",
        archetype: "deflect",
        retort: "那當然，火太大就焦了。",
      },
      {
        id: "guzhang-food_push-016-c",
        text: "姑丈教我怎麼煎才不會黏鍋。",
        archetype: "deflect",
        retort: "好，油要先熱，我教你。",
      },
      {
        id: "guzhang-food_push-016-d",
        text: "已經吃了一塊，真的黏牙又飽……",
        archetype: "meek",
        retort: "黏牙才夠Q，再吃一塊。",
      },
      {
        id: "guzhang-food_push-016-e",
        text: "我對年糕不太有感覺，吃一小口……",
        archetype: "meek",
        retort: "一小口太少，多吃才吉利。",
      },
      {
        id: "guzhang-food_push-016-f",
        text: "年年高升是不是吃了會長高？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續切下一塊）",
      },
      {
        id: "guzhang-food_push-016-g",
        text: "年糕配薑黃是不是變年獸？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂講）",
      },
      {
        id: "guzhang-food_push-016-h",
        text: "這年糕黏牙，比不上你嘴硬。",
        archetype: "landmine",
        retort: "他臉一垮，深吸一口氣不說話。",
      },
    ],
  },
  {
    id: "guzhang-food_push-017",
    text: "燒酒雞鍋底再加料，湯頭才夠力。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-017-a",
        text: "湯頭夠力，你的立場倒是很軟。",
        archetype: "perfect",
        retort: "他語塞，眼神飄向別處。",
      },
      {
        id: "guzhang-food_push-017-b",
        text: "姑丈煮燒酒雞的手藝真專業。",
        archetype: "deflect",
        retort: "那當然，這是我的招牌菜。",
      },
      {
        id: "guzhang-food_push-017-c",
        text: "姑丈教我怎麼掌握米酒比例。",
        archetype: "deflect",
        retort: "秘訣是慢慢加，我教你。",
      },
      {
        id: "guzhang-food_push-017-d",
        text: "我對米酒味比較敏感，喝一點就好……",
        archetype: "meek",
        retort: "酒精都煮掉了啦，多喝點。",
      },
      {
        id: "guzhang-food_push-017-e",
        text: "我剛喝了雞湯，肚子有點滿了……",
        archetype: "meek",
        retort: "滿了也要再喝一碗才夠意思。",
      },
      {
        id: "guzhang-food_push-017-f",
        text: "喝完是不是會醉到不會走路？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加米酒）",
      },
      {
        id: "guzhang-food_push-017-g",
        text: "燒酒雞配薑黃是不是雙倍發燙？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真考慮起來）",
      },
      {
        id: "guzhang-food_push-017-h",
        text: "加這麼多料，蓋不了偏方沒效。",
        archetype: "landmine",
        retort: "他吼一句台語，轉頭不理你。",
      },
    ],
  },
  {
    id: "guzhang-food_push-018",
    text: "保久乳一箱都打開了，喝完一瓶。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-018-a",
        text: "囤這一箱，跟你囤的謠言一樣多。",
        archetype: "perfect",
        retort: "他愣住，動作僵在原地。",
      },
      {
        id: "guzhang-food_push-018-b",
        text: "姑丈怎麼一次買這麼多箱啊？",
        archetype: "deflect",
        retort: "特價才划算，屯起來慢慢喝。",
      },
      {
        id: "guzhang-food_push-018-c",
        text: "姑丈平常都幾點喝這個補鈣？",
        archetype: "deflect",
        retort: "早晚各一瓶，你也該養成習慣。",
      },
      {
        id: "guzhang-food_push-018-d",
        text: "我今天已經喝了牛奶了……",
        archetype: "meek",
        retort: "再喝一瓶，鈣質不嫌多。",
      },
      {
        id: "guzhang-food_push-018-e",
        text: "我喝乳製品容易脹氣，喝一半……",
        archetype: "meek",
        retort: "喝一半也要撐著喝完。",
      },
      {
        id: "guzhang-food_push-018-f",
        text: "這箱是不是要囤到下個過年？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在虧他）",
      },
      {
        id: "guzhang-food_push-018-g",
        text: "保久乳配薑黃是不是新配方？",
        archetype: "backfire",
        retort: "（姑丈認真思考起這個組合）",
      },
      {
        id: "guzhang-food_push-018-h",
        text: "囤這箱，跟你被騙那次一樣衝動。",
        archetype: "landmine",
        retort: "他臉一垮，甩手不想理你。",
      },
    ],
  },
  {
    id: "guzhang-food_push-019",
    text: "夜市買的香腸，吃一根配蒜片。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-019-a",
        text: "排隊排最長，排不出真的偏方。",
        archetype: "perfect",
        retort: "他嘴硬回一句，但沒底氣。",
      },
      {
        id: "guzhang-food_push-019-b",
        text: "姑丈是不是每攤都試吃過？",
        archetype: "deflect",
        retort: "那當然，要試過才知道哪攤好。",
      },
      {
        id: "guzhang-food_push-019-c",
        text: "姑丈幫我配蒜片，剛剛好的量。",
        archetype: "deflect",
        retort: "好，多加點蒜片才夠味。",
      },
      {
        id: "guzhang-food_push-019-d",
        text: "我剛吃了很多，一根就好……",
        archetype: "meek",
        retort: "一根不夠意思，再吃一根。",
      },
      {
        id: "guzhang-food_push-019-e",
        text: "我對蒜片比較敏感，少放一點……",
        archetype: "meek",
        retort: "少放就少放，還是要吃完。",
      },
      {
        id: "guzhang-food_push-019-f",
        text: "吃完是不是全身會有蒜味走天下？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續遞下一根）",
      },
      {
        id: "guzhang-food_push-019-g",
        text: "香腸配薑黃是不是黑暗料理？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太誇張）",
      },
      {
        id: "guzhang-food_push-019-h",
        text: "這根香腸，比你的消息還可疑。",
        archetype: "landmine",
        retort: "他氣到講台語，冷哼一聲。",
      },
    ],
  },
  {
    id: "guzhang-food_push-020",
    text: "這罐轉大人補品喝一口，長高有望。",
    topic: "food_push",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-food_push-020-a",
        text: "轉大人？先轉一下你判斷力。",
        archetype: "perfect",
        retort: "他語塞，尷尬地清清喉嚨。",
      },
      {
        id: "guzhang-food_push-020-b",
        text: "姑丈這麼細心，連這個都準備。",
        archetype: "deflect",
        retort: "那當然，家人就是要互相照顧。",
      },
      {
        id: "guzhang-food_push-020-c",
        text: "姑丈自己也有喝這款的嗎？",
        archetype: "deflect",
        retort: "有喔，我每天早上都喝一瓶。",
      },
      {
        id: "guzhang-food_push-020-d",
        text: "我早就過了轉大人的年紀了……",
        archetype: "meek",
        retort: "年紀哪有關係，喝了都有效。",
      },
      {
        id: "guzhang-food_push-020-e",
        text: "我對這種補品比較沒信心……",
        archetype: "meek",
        retort: "沒信心也要試試看嘛。",
      },
      {
        id: "guzhang-food_push-020-f",
        text: "喝完是不是明天就會長高十公分？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解成分）",
      },
      {
        id: "guzhang-food_push-020-g",
        text: "轉大人補品配薑黃是不是升級版？",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真研究起來）",
      },
      {
        id: "guzhang-food_push-020-h",
        text: "喝這罐，喝不出一次準偏方。",
        archetype: "landmine",
        retort: "他臉一垮，安靜了整整十秒。",
      },
    ],
  },
] satisfies Question[];
