import type { Question } from "@/content/types";

// situations: 021 聊造勢晚會人潮塞車 / 022 聊公投案又要花錢辦 / 023 聊台股新高薪水沒漲
// 024 接到選舉宣傳電話騷擾 / 025 聊電費又要漲 / 026 聊里長選舉發傳單
// 027 聊電視退休金政策辯論 / 028 聊政論節目網路酸民互罵 / 029 聊年金改革草案卡關
// 030 聊媒體農場假新聞滿天飛 / 031 聊出國機票太貴 / 032 聊里長競選送毛巾
// 033 聊政府普發現金怎麼領 / 034 聊選前之夜造勢晚會佔車位 / 035 聊政論節目老班底固定來賓
export default [
  {
    id: "guzhang-politics-021",
    text: "昨晚造勢晚會，整條路都塞死了。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-021-a",
        text: "辛苦了，好，我回去查一下路況。",
        archetype: "perfect",
        retort: "查一下，以後就知道要繞路。",
      },
      {
        id: "guzhang-politics-021-b",
        text: "姑丈昨晚是不是也去湊熱鬧了？",
        archetype: "deflect",
        retort: "有去看一下，人真的很多。",
      },
      {
        id: "guzhang-politics-021-c",
        text: "姑丈教我怎麼避開這種塞車路段。",
        archetype: "deflect",
        retort: "好，走這條巷子最快，我教你。",
      },
      {
        id: "guzhang-politics-021-d",
        text: "我昨天塞了一個多小時才回到家……",
        archetype: "meek",
        retort: "那你要提早出門避開時間。",
      },
      {
        id: "guzhang-politics-021-e",
        text: "我都不知道昨晚有活動，白白塞車……",
        archetype: "meek",
        retort: "以後要多注意新聞公告啊。",
      },
      {
        id: "guzhang-politics-021-f",
        text: "那我乾脆坐直升機回家好了哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念交通）",
      },
      {
        id: "guzhang-politics-021-g",
        text: "造勢晚會是不是也能發薑黃紀念品？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個提議）",
      },
      {
        id: "guzhang-politics-021-h",
        text: "選舉真的很煩，一天到晚辦活動。",
        archetype: "landmine",
        retort: "……這是民主社會，你要包容一下。",
      },
    ],
  },
  {
    id: "guzhang-politics-022",
    text: "公投又要辦了，這次花的錢也不少。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-022-a",
        text: "確實，好，我回去查一下花費明細。",
        archetype: "perfect",
        retort: "查一下，你會更清楚整個流程。",
      },
      {
        id: "guzhang-politics-022-b",
        text: "姑丈每次公投都有去投票吧。",
        archetype: "deflect",
        retort: "那當然，這是公民義務。",
      },
      {
        id: "guzhang-politics-022-c",
        text: "姑丈幫我解釋一下這次的議題。",
        archetype: "deflect",
        retort: "好，我慢慢跟你講清楚。",
      },
      {
        id: "guzhang-politics-022-d",
        text: "我對這次的議題不是很清楚……",
        archetype: "meek",
        retort: "不清楚就要花時間了解一下。",
      },
      {
        id: "guzhang-politics-022-e",
        text: "我平常太忙，沒空研究這些……",
        archetype: "meek",
        retort: "再忙也要抽空關心一下國事。",
      },
      {
        id: "guzhang-politics-022-f",
        text: "那我提案全民一起喝薑黃湯好了。",
        archetype: "backfire",
        retort: "（姑丈認真思考這個提案）",
      },
      {
        id: "guzhang-politics-022-g",
        text: "公投是不是也能用擲筊決定結果？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍寶）",
      },
      {
        id: "guzhang-politics-022-h",
        text: "反正投了也不會改變什麼結果啦。",
        archetype: "landmine",
        retort: "……你這樣講讓我很失望。",
      },
    ],
  },
  {
    id: "guzhang-politics-023",
    text: "台股又創新高，但薪水一直沒漲。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-023-a",
        text: "有感觸，好，我回去查一下差距數據。",
        archetype: "perfect",
        retort: "查一下，你會發現問題不小。",
      },
      {
        id: "guzhang-politics-023-b",
        text: "姑丈這波股市漲得開心嗎？",
        archetype: "deflect",
        retort: "還算開心，但也不敢太貪心。",
      },
      {
        id: "guzhang-politics-023-c",
        text: "姑丈教我怎麼開始學理財。",
        archetype: "deflect",
        retort: "好，先從定期定額開始，我教你。",
      },
      {
        id: "guzhang-politics-023-d",
        text: "對啊，我薪水這幾年都沒什麼變……",
        archetype: "meek",
        retort: "沒變也要學會理財才行。",
      },
      {
        id: "guzhang-politics-023-e",
        text: "我沒什麼閒錢投資，只能看著漲……",
        archetype: "meek",
        retort: "先存錢，等有餘力再投資。",
      },
      {
        id: "guzhang-politics-023-f",
        text: "那我改投資薑黃期貨好了哈哈。",
        archetype: "backfire",
        retort: "（姑丈認真回應，覺得可以研究）",
      },
      {
        id: "guzhang-politics-023-g",
        text: "股市創新高是不是也算通貨膨脹？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講他的觀察）",
      },
      {
        id: "guzhang-politics-023-h",
        text: "反正這種事跟我也沒什麼關係啦。",
        archetype: "landmine",
        retort: "……你這樣講太消極了吧。",
      },
    ],
  },
  {
    id: "guzhang-politics-024",
    text: "又接到選舉宣傳電話，真的很煩。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-024-a",
        text: "是很煩，好，我回去查一下封鎖方法。",
        archetype: "perfect",
        retort: "查一下，封鎖起來就清淨了。",
      },
      {
        id: "guzhang-politics-024-b",
        text: "姑丈一天接幾通啊，真辛苦。",
        archetype: "deflect",
        retort: "至少三通，煩死人了。",
      },
      {
        id: "guzhang-politics-024-c",
        text: "姑丈教我怎麼分辨這種電話。",
        archetype: "deflect",
        retort: "好，號碼怪怪的就不要接，我教你。",
      },
      {
        id: "guzhang-politics-024-d",
        text: "我也接過，講話講很久掛不掉……",
        archetype: "meek",
        retort: "掛不掉就要直接說沒興趣。",
      },
      {
        id: "guzhang-politics-024-e",
        text: "我手機都不太會設定封鎖……",
        archetype: "meek",
        retort: "那你要學一下，我教你設定。",
      },
      {
        id: "guzhang-politics-024-f",
        text: "那我推薦他們改推銷薑黃好了哈哈。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念電話騷擾）",
      },
      {
        id: "guzhang-politics-024-g",
        text: "宣傳電話是不是比詐騙集團更煩？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在誇張比較）",
      },
      {
        id: "guzhang-politics-024-h",
        text: "接個電話而已，姑丈不用那麼氣。",
        archetype: "landmine",
        retort: "……你沒接過才會這樣講。",
      },
    ],
  },
  {
    id: "guzhang-politics-025",
    text: "電費又要漲了，冷氣都不太敢開。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-025-a",
        text: "了解，好，我回去查一下省電方法。",
        archetype: "perfect",
        retort: "查一下，我教你幾招省電技巧。",
      },
      {
        id: "guzhang-politics-025-b",
        text: "姑丈家裡的省電方式真的厲害。",
        archetype: "deflect",
        retort: "那當然，退休就要精打細算。",
      },
      {
        id: "guzhang-politics-025-c",
        text: "姑丈教我怎麼調冷氣才省電。",
        archetype: "deflect",
        retort: "好，設二十六度剛剛好，我教你。",
      },
      {
        id: "guzhang-politics-025-d",
        text: "我這個月電費也漲了不少……",
        archetype: "meek",
        retort: "那你要開始注意用電習慣了。",
      },
      {
        id: "guzhang-politics-025-e",
        text: "我不太會看電費帳單，沒特別注意……",
        archetype: "meek",
        retort: "那你要開始學會看，很重要的。",
      },
      {
        id: "guzhang-politics-025-f",
        text: "那我改用薑黃當暖爐好了哈哈。",
        archetype: "backfire",
        retort: "（姑丈認真思考這個提議）",
      },
      {
        id: "guzhang-politics-025-g",
        text: "電費漲是不是要順便漲薪水？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念電費）",
      },
      {
        id: "guzhang-politics-025-h",
        text: "漲一點電費而已，姑丈不用省成這樣。",
        archetype: "landmine",
        retort: "……積少成多，你以後就懂了。",
      },
    ],
  },
  {
    id: "guzhang-politics-026",
    text: "里長來發傳單了，你要不要投他一票。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-026-a",
        text: "好，我回去查一下他的政見。",
        archetype: "perfect",
        retort: "查一下，這樣投票才有依據。",
      },
      {
        id: "guzhang-politics-026-b",
        text: "姑丈跟里長認識很久了嗎？",
        archetype: "deflect",
        retort: "認識十幾年了，很熟的。",
      },
      {
        id: "guzhang-politics-026-c",
        text: "姑丈覺得里長做得怎麼樣？",
        archetype: "deflect",
        retort: "還不錯，社區的事都很盡心。",
      },
      {
        id: "guzhang-politics-026-d",
        text: "我對里長選舉不太關心……",
        archetype: "meek",
        retort: "不關心不行，里長跟生活最近了。",
      },
      {
        id: "guzhang-politics-026-e",
        text: "我還沒把戶籍遷過來，不能投……",
        archetype: "meek",
        retort: "那你要考慮遷戶籍的事了。",
      },
      {
        id: "guzhang-politics-026-f",
        text: "傳單是不是能拿去墊薑黃盆栽？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續介紹候選人）",
      },
      {
        id: "guzhang-politics-026-g",
        text: "里長選舉是不是全里最小的戰場？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在小看這件事）",
      },
      {
        id: "guzhang-politics-026-h",
        text: "里長選舉沒什麼好關心的啦。",
        archetype: "landmine",
        retort: "……里長跟你生活最有關係耶。",
      },
    ],
  },
  {
    id: "guzhang-politics-027",
    text: "電視在辯論退休金政策，你怎麼看。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-027-a",
        text: "好，我回去查一下雙方的方案。",
        archetype: "perfect",
        retort: "查一下，比較清楚以後才好判斷。",
      },
      {
        id: "guzhang-politics-027-b",
        text: "姑丈當年退休領得還算安穩吧。",
        archetype: "deflect",
        retort: "那當然，我算幸運的一代。",
      },
      {
        id: "guzhang-politics-027-c",
        text: "姑丈覺得哪個方案比較合理？",
        archetype: "deflect",
        retort: "應該要循序漸進，我覺得啦。",
      },
      {
        id: "guzhang-politics-027-d",
        text: "我對這些方案的細節不太懂……",
        archetype: "meek",
        retort: "不懂就要多花時間了解一下。",
      },
      {
        id: "guzhang-politics-027-e",
        text: "我覺得自己以後可能領不到什麼……",
        archetype: "meek",
        retort: "那更要提早自己存一份。",
      },
      {
        id: "guzhang-politics-027-f",
        text: "那我把退休金都換成薑黃儲值好了。",
        archetype: "backfire",
        retort: "（姑丈認真思考起這個做法）",
      },
      {
        id: "guzhang-politics-027-g",
        text: "退休金辯論是不是每次都吵不出結果？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太悲觀）",
      },
      {
        id: "guzhang-politics-027-h",
        text: "反正輪不到我領，不用關心了啦。",
        archetype: "landmine",
        retort: "……你這樣講讓我聽了很難過。",
      },
    ],
  },
  {
    id: "guzhang-politics-028",
    text: "網路留言又在吵，一堆酸民在互罵。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-028-a",
        text: "是啊，好，我回去查一下事件源頭。",
        archetype: "perfect",
        retort: "查一下，才不會被片面說法帶著走。",
      },
      {
        id: "guzhang-politics-028-b",
        text: "姑丈都不留言，真的很自律。",
        archetype: "deflect",
        retort: "那當然，看看就好，不必回嘴。",
      },
      {
        id: "guzhang-politics-028-c",
        text: "姑丈覺得這種留言該怎麼看待？",
        archetype: "deflect",
        retort: "看看就好，別太認真，我教你。",
      },
      {
        id: "guzhang-politics-028-d",
        text: "我看了留言心情也跟著不好……",
        archetype: "meek",
        retort: "那你就不要看那麼久啦。",
      },
      {
        id: "guzhang-politics-028-e",
        text: "我有時候也會忍不住回嘴幾句……",
        archetype: "meek",
        retort: "回嘴也解決不了什麼問題啊。",
      },
      {
        id: "guzhang-politics-028-f",
        text: "那我留言推薦大家喝薑黃冷靜一下。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續滑手機看留言）",
      },
      {
        id: "guzhang-politics-028-g",
        text: "酸民是不是也是靠嘴巴上班的？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍嘴皮）",
      },
      {
        id: "guzhang-politics-028-h",
        text: "這種網路留言根本不用理會啦。",
        archetype: "landmine",
        retort: "……那也要看看內容才知道吧。",
      },
    ],
  },
  {
    id: "guzhang-politics-029",
    text: "年金改革草案又卡關了，真的很牛步。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-029-a",
        text: "確實牛步，好，我回去查一下進度。",
        archetype: "perfect",
        retort: "查一下，你會發現卡在哪個環節。",
      },
      {
        id: "guzhang-politics-029-b",
        text: "姑丈這方面的資訊真的很靈通。",
        archetype: "deflect",
        retort: "那當然，退休就是要關心這個。",
      },
      {
        id: "guzhang-politics-029-c",
        text: "姑丈覺得卡關的原因是什麼？",
        archetype: "deflect",
        retort: "應該是各方利益喬不攏，我猜。",
      },
      {
        id: "guzhang-politics-029-d",
        text: "我對年金這個議題不太了解……",
        archetype: "meek",
        retort: "不了解就要多查一下資料。",
      },
      {
        id: "guzhang-politics-029-e",
        text: "這種議題我覺得離我還很遠……",
        archetype: "meek",
        retort: "不會遠啦，要早點關心。",
      },
      {
        id: "guzhang-politics-029-f",
        text: "那我提議年金改成薑黃分紅好了。",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個提案）",
      },
      {
        id: "guzhang-politics-029-g",
        text: "卡關是不是也算一種穩定？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念進度）",
      },
      {
        id: "guzhang-politics-029-h",
        text: "反正這種事永遠都改不好啦。",
        archetype: "landmine",
        retort: "……你這樣講太悲觀了吧。",
      },
    ],
  },
  {
    id: "guzhang-politics-030",
    text: "這篇媒體農場的文章，是假新聞啦。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-030-a",
        text: "好，我回去查一下這篇的來源。",
        archetype: "perfect",
        retort: "查一下，以後就知道怎麼分辨。",
      },
      {
        id: "guzhang-politics-030-b",
        text: "姑丈是怎麼看出來是假新聞的？",
        archetype: "deflect",
        retort: "標題太誇張，看多就會分辨了。",
      },
      {
        id: "guzhang-politics-030-c",
        text: "姑丈教我怎麼查證新聞真假。",
        archetype: "deflect",
        retort: "好，查來源跟日期，我教你。",
      },
      {
        id: "guzhang-politics-030-d",
        text: "我剛剛也差點被這篇騙到了……",
        archetype: "meek",
        retort: "差點就好，以後要多留意。",
      },
      {
        id: "guzhang-politics-030-e",
        text: "我平常都不太查證就轉發……",
        archetype: "meek",
        retort: "轉發前要先查一下，很重要。",
      },
      {
        id: "guzhang-politics-030-f",
        text: "那我來闢謠說薑黃才是真相好了。",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得你懂了）",
      },
      {
        id: "guzhang-politics-030-g",
        text: "媒體農場是不是專門種假新聞的田？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講解怎麼分辨）",
      },
      {
        id: "guzhang-politics-030-h",
        text: "姑丈自己傳的那些也都假新聞啦。",
        archetype: "landmine",
        retort: "……你這樣講讓我很受傷耶。",
      },
    ],
  },
  {
    id: "guzhang-politics-031",
    text: "出國機票貴成這樣，是不是通膨害的。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-031-a",
        text: "有可能，好，我回去查一下票價趨勢。",
        archetype: "perfect",
        retort: "查一下，你會發現趨勢很明顯。",
      },
      {
        id: "guzhang-politics-031-b",
        text: "姑丈退休後出國玩很多次了吧。",
        archetype: "deflect",
        retort: "那當然，就是要趁有體力多玩。",
      },
      {
        id: "guzhang-politics-031-c",
        text: "姑丈教我怎麼買到便宜機票。",
        archetype: "deflect",
        retort: "好，要提早訂，我教你技巧。",
      },
      {
        id: "guzhang-politics-031-d",
        text: "我今年的旅遊計畫可能要延後了……",
        archetype: "meek",
        retort: "延後也好，等票價便宜再去。",
      },
      {
        id: "guzhang-politics-031-e",
        text: "我平常沒特別注意機票價格……",
        archetype: "meek",
        retort: "以後出國前要多比較幾家。",
      },
      {
        id: "guzhang-politics-031-f",
        text: "那我改喝薑黃當作出國替代品好了。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續研究機票網站）",
      },
      {
        id: "guzhang-politics-031-g",
        text: "機票貴是不是因為飛機也要吃薑黃？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂扯）",
      },
      {
        id: "guzhang-politics-031-h",
        text: "反正我也沒錢出國啦，別提了。",
        archetype: "landmine",
        retort: "……我是想找你一起出去玩耶。",
      },
    ],
  },
  {
    id: "guzhang-politics-032",
    text: "里長候選人送毛巾，你要不要拿一條。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-032-a",
        text: "好，我回去查一下他過去的政績。",
        archetype: "perfect",
        retort: "查一下，這樣拿得比較安心。",
      },
      {
        id: "guzhang-politics-032-b",
        text: "姑丈收藏的贈品毛巾一定很多。",
        archetype: "deflect",
        retort: "那當然，一個抽屜都裝不下。",
      },
      {
        id: "guzhang-politics-032-c",
        text: "姑丈最喜歡哪個候選人送的贈品？",
        archetype: "deflect",
        retort: "這條最厚，我最喜歡這個。",
      },
      {
        id: "guzhang-politics-032-d",
        text: "我對這位候選人不太熟……",
        archetype: "meek",
        retort: "不熟就要花時間了解一下。",
      },
      {
        id: "guzhang-politics-032-e",
        text: "我家毛巾已經很多了，用不到……",
        archetype: "meek",
        retort: "用不到也拿著，禮多人不怪。",
      },
      {
        id: "guzhang-politics-032-f",
        text: "毛巾是不是能拿去泡薑黃水擦臉？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個做法）",
      },
      {
        id: "guzhang-politics-032-g",
        text: "送毛巾是不是選舉的固定戲碼？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續介紹候選人）",
      },
      {
        id: "guzhang-politics-032-h",
        text: "這種東西拿了也不會投他啦。",
        archetype: "landmine",
        retort: "……禮貌上收一下也不會怎樣吧。",
      },
    ],
  },
  {
    id: "guzhang-politics-033",
    text: "政府要普發現金了，你查一下怎麼領。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-033-a",
        text: "好，我回去查一下領取的時間點。",
        archetype: "perfect",
        retort: "查一下，別錯過登記時間。",
      },
      {
        id: "guzhang-politics-033-b",
        text: "姑丈打算怎麼運用這筆錢啊？",
        archetype: "deflect",
        retort: "存起來，或買點保健品啦。",
      },
      {
        id: "guzhang-politics-033-c",
        text: "姑丈教我怎麼設定領取方式。",
        archetype: "deflect",
        retort: "好，用網路登記最快，我教你。",
      },
      {
        id: "guzhang-politics-033-d",
        text: "我不太會用網路登記，怕搞錯……",
        archetype: "meek",
        retort: "不會就要學，慢慢跟著步驟做。",
      },
      {
        id: "guzhang-politics-033-e",
        text: "我平常不太關心這種消息……",
        archetype: "meek",
        retort: "這種好康怎麼可以不關心。",
      },
      {
        id: "guzhang-politics-033-f",
        text: "拿到錢是不是要全部拿去買薑黃？",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得是好主意）",
      },
      {
        id: "guzhang-politics-033-g",
        text: "普發現金是不是政府發紅包給我？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講登記步驟）",
      },
      {
        id: "guzhang-politics-033-h",
        text: "這種錢領了也不會改變什麼啦。",
        archetype: "landmine",
        retort: "……有拿到總比沒有好吧。",
      },
    ],
  },
  {
    id: "guzhang-politics-034",
    text: "選前之夜佔了半條街的停車位，煩。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-034-a",
        text: "是啊，好，我回去查一下替代停車場。",
        archetype: "perfect",
        retort: "查一下，這樣以後就不用擔心。",
      },
      {
        id: "guzhang-politics-034-b",
        text: "姑丈找車位的功力一定很厲害。",
        archetype: "deflect",
        retort: "那當然，退休就是要練這個。",
      },
      {
        id: "guzhang-politics-034-c",
        text: "姑丈幫我找一下附近的空位吧。",
        archetype: "deflect",
        retort: "好，那條巷子還有位置，走吧。",
      },
      {
        id: "guzhang-politics-034-d",
        text: "我今天找了半小時都找不到車位……",
        archetype: "meek",
        retort: "半小時算好了，明天更難找。",
      },
      {
        id: "guzhang-politics-034-e",
        text: "我今天乾脆改搭公車來了……",
        archetype: "meek",
        retort: "搭公車也好，省得找車位煩。",
      },
      {
        id: "guzhang-politics-034-f",
        text: "選前之夜是不是也能發薑黃紅茶？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念停車問題）",
      },
      {
        id: "guzhang-politics-034-g",
        text: "佔車位是不是選舉季的固定活動？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在挖苦）",
      },
      {
        id: "guzhang-politics-034-h",
        text: "每次選舉都這樣，真的很自私。",
        archetype: "landmine",
        retort: "……民主活動也是需要空間的。",
      },
    ],
  },
  {
    id: "guzhang-politics-035",
    text: "政論節目又找那幾個熟面孔上節目。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-035-a",
        text: "好，我回去查一下他們的資歷。",
        archetype: "perfect",
        retort: "查一下，你會發現各有專長。",
      },
      {
        id: "guzhang-politics-035-b",
        text: "姑丈是不是每個來賓都認得出來？",
        archetype: "deflect",
        retort: "那當然，看久了跟老朋友一樣。",
      },
      {
        id: "guzhang-politics-035-c",
        text: "姑丈最欣賞哪一位固定班底？",
        archetype: "deflect",
        retort: "這位講話最中肯，我最欣賞他。",
      },
      {
        id: "guzhang-politics-035-d",
        text: "他們講的話我聽起來都差不多……",
        archetype: "meek",
        retort: "差不多也要仔細聽細節啊。",
      },
      {
        id: "guzhang-politics-035-e",
        text: "我沒特別追這個節目的來賓……",
        archetype: "meek",
        retort: "不追怎麼跟上時事，要多看。",
      },
      {
        id: "guzhang-politics-035-f",
        text: "這些來賓是不是也該換薑黃代言了？",
        archetype: "backfire",
        retort: "（姑丈認真思考起這個提議）",
      },
      {
        id: "guzhang-politics-035-g",
        text: "老班底是不是靠臉熟才能上節目？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在唱反調）",
      },
      {
        id: "guzhang-politics-035-h",
        text: "換來換去都同一批人，很無聊耶。",
        archetype: "landmine",
        retort: "……我看得很開心，你何必這樣說。",
      },
    ],
  },
] satisfies Question[];
