import type { Question } from "@/content/types";

// situations: 001 電視轉政論台名嘴發言 / 002 LINE群組轉傳退休金謠言 / 003 抱怨雞蛋物價上漲
// 004 抱怨年輕人不投票 / 005 抱怨少子化現象 / 006 抱怨找嘸零錢通膨
// 007 抱怨股市基金 / 008 抱怨颱風假政策 / 009 抱怨AI搶工作
// 010 廟口跟老友聊政治 / 011 公園健走聊時事 / 012 餐桌聊選舉宣傳車吵鬧
// 013 聊電動車政策 / 014 聊房價囤房稅 / 015 聊退休年齡延後
// 016 聊詐騙集團猖獗 / 017 聊外送零工經濟 / 018 聊減塑政策
// 019 聊超商機器人結帳 / 020 聊政論節目來賓吵架
export default [
  {
    id: "guzhang-politics-001",
    text: "轉政論台，你看這個名嘴講得多準。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-001-a",
        text: "幹，名嘴講得準，你猜大樂透中了嗎？",
        archetype: "perfect",
        retort: "他語塞，臉紅著罵一句幹。",
      },
      {
        id: "guzhang-politics-001-b",
        text: "靠，姑丈看這節目多久了，好專業？",
        archetype: "deflect",
        retort: "十幾年了，我都看熟了。",
      },
      {
        id: "guzhang-politics-001-c",
        text: "姑丈最挺哪個名嘴，跟我分享？",
        archetype: "deflect",
        retort: "這個最中肯，你也該多看。",
      },
      {
        id: "guzhang-politics-001-d",
        text: "幹……喔好，我看一下好了……",
        archetype: "meek",
        retort: "看一下不夠，要認真聽。",
      },
      {
        id: "guzhang-politics-001-e",
        text: "我對政治不太懂，不太敢評論……",
        archetype: "meek",
        retort: "不懂才更要多看，補一下知識。",
      },
      {
        id: "guzhang-politics-001-f",
        text: "靠，名嘴是不是靠嘴巴領薪水？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續轉大聲音）",
      },
      {
        id: "guzhang-politics-001-g",
        text: "去你的，這節目是不是每天在吵架？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你不夠認真看）",
      },
      {
        id: "guzhang-politics-001-h",
        text: "幹，名嘴亂講，你被騙那次也信，死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，收拾東西就走。",
      },
    ],
  },
  {
    id: "guzhang-politics-002",
    text: "LINE群組說退休金要沒了，你看看。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-002-a",
        text: "幹，這消息哪來的，朋友的朋友傳的？",
        archetype: "perfect",
        retort: "他愣住，眉頭皺著罵一句。",
      },
      {
        id: "guzhang-politics-002-b",
        text: "靠，姑丈的退休金規劃一定很完善？",
        archetype: "deflect",
        retort: "那當然，我早就做好功課了。",
      },
      {
        id: "guzhang-politics-002-c",
        text: "姑丈教我怎麼規劃退休金比較好？",
        archetype: "deflect",
        retort: "好，這個要早點準備，我教你。",
      },
      {
        id: "guzhang-politics-002-d",
        text: "幹……那我以後是不是領不到……",
        archetype: "meek",
        retort: "還不確定，但要有心理準備。",
      },
      {
        id: "guzhang-politics-002-e",
        text: "我現在還沒開始存退休金……",
        archetype: "meek",
        retort: "那你要趕快開始存了啦。",
      },
      {
        id: "guzhang-politics-002-f",
        text: "靠，那我以後靠中樂透退休好了。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續轉發文章）",
      },
      {
        id: "guzhang-politics-002-g",
        text: "去死，那我以後也天天傳早安圖騙讚。",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在挖苦他）",
      },
      {
        id: "guzhang-politics-002-h",
        text: "幹，上次騙你的訊息長得跟這篇一樣，老東西。",
        archetype: "landmine",
        retort: "他臉一垮，說明年不用來了。",
      },
    ],
  },
  {
    id: "guzhang-politics-003",
    text: "雞蛋又漲了，這年頭真的不好過。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-003-a",
        text: "幹，漲成這樣，你薑黃是不是也漲了？",
        archetype: "perfect",
        retort: "他語塞，找不到反駁罵一句。",
      },
      {
        id: "guzhang-politics-003-b",
        text: "靠，姑丈買菜的功力一定省很多？",
        archetype: "deflect",
        retort: "那當然，我都貨比三家。",
      },
      {
        id: "guzhang-politics-003-c",
        text: "姑丈平常都去哪買比較便宜？",
        archetype: "deflect",
        retort: "傳統市場最划算，我教你挑。",
      },
      {
        id: "guzhang-politics-003-d",
        text: "幹……對啊，我最近也吃不消……",
        archetype: "meek",
        retort: "年輕人更辛苦，要學會省。",
      },
      {
        id: "guzhang-politics-003-e",
        text: "我平常沒在算物價，沒感覺……",
        archetype: "meek",
        retort: "沒感覺才可怕，要多注意。",
      },
      {
        id: "guzhang-politics-003-f",
        text: "靠，那我改吃薑黃補蛋白質好了。",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得有道理）",
      },
      {
        id: "guzhang-politics-003-g",
        text: "去你的，雞蛋漲價是雞在抗議加班？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念物價）",
      },
      {
        id: "guzhang-politics-003-h",
        text: "幹，雞蛋漲價，你血壓也跟著漲，死老頭。",
        archetype: "landmine",
        retort: "他臉一垮，狠狠瞪你一眼。",
      },
    ],
  },
  {
    id: "guzhang-politics-004",
    text: "現在年輕人都不投票，太不像話了。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-004-a",
        text: "幹，投票很重要，你的群組怎麼靜音？",
        archetype: "perfect",
        retort: "姑姑在旁邊憋笑憋很辛苦。",
      },
      {
        id: "guzhang-politics-004-b",
        text: "靠，姑丈每次都準時去投，真負責？",
        archetype: "deflect",
        retort: "那當然，這是公民的責任。",
      },
      {
        id: "guzhang-politics-004-c",
        text: "姑丈教我怎麼查投票地點？",
        archetype: "deflect",
        retort: "好，網站上查戶籍就有了。",
      },
      {
        id: "guzhang-politics-004-d",
        text: "幹……我平常太忙，常常錯過投票……",
        archetype: "meek",
        retort: "忙也要抽時間，很重要的。",
      },
      {
        id: "guzhang-politics-004-e",
        text: "我對候選人不太熟，不知道投誰……",
        archetype: "meek",
        retort: "那就要花時間去了解啊。",
      },
      {
        id: "guzhang-politics-004-f",
        text: "靠，那投票所是不是也能發早餐？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講投票重要性）",
      },
      {
        id: "guzhang-politics-004-g",
        text: "去死，投票日放假是不是比較重要？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你搞錯重點）",
      },
      {
        id: "guzhang-politics-004-h",
        text: "幹，年輕人不投票，關你退休屁事，老不死。",
        archetype: "landmine",
        retort: "他氣到講台語，轉頭不說話。",
      },
    ],
  },
  {
    id: "guzhang-politics-005",
    text: "現在都不生小孩，以後怎麼辦啊。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-005-a",
        text: "幹，少子化？你退休群組倒是很旺。",
        archetype: "perfect",
        retort: "他愣住，手指抓後腦罵一句。",
      },
      {
        id: "guzhang-politics-005-b",
        text: "靠，姑丈那個年代生小孩比較簡單？",
        archetype: "deflect",
        retort: "那時候辛苦，但養得起就生。",
      },
      {
        id: "guzhang-politics-005-c",
        text: "姑丈覺得現在該怎麼鼓勵生育？",
        archetype: "deflect",
        retort: "要補助多一點，我覺得啦。",
      },
      {
        id: "guzhang-politics-005-d",
        text: "幹……現在養小孩真的壓力很大……",
        archetype: "meek",
        retort: "壓力大也要想辦法克服啊。",
      },
      {
        id: "guzhang-politics-005-e",
        text: "我自己都還沒穩定，不敢想這個……",
        archetype: "meek",
        retort: "那你要趕快穩定下來啊。",
      },
      {
        id: "guzhang-politics-005-f",
        text: "靠，那我幫忙徵才好了，我朋友很多。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講少子化）",
      },
      {
        id: "guzhang-politics-005-g",
        text: "去你的，不生小孩是不是比較環保？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在打岔）",
      },
      {
        id: "guzhang-politics-005-h",
        text: "幹，生不生關你屁事，你很閒嗎，老東西？",
        archetype: "landmine",
        retort: "他臉一垮，別開臉不吭聲。",
      },
    ],
  },
  {
    id: "guzhang-politics-006",
    text: "去超商買東西都找不到零錢，誇張。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-006-a",
        text: "幹，找嘸零錢，你倒是找到不少偏方。",
        archetype: "perfect",
        retort: "他語塞，假裝在看別的地方。",
      },
      {
        id: "guzhang-politics-006-b",
        text: "靠，姑丈現在都用行動支付了嗎？",
        archetype: "deflect",
        retort: "有在學，年輕人教我的。",
      },
      {
        id: "guzhang-politics-006-c",
        text: "姑丈教我怎麼算才不會被找錯錢？",
        archetype: "deflect",
        retort: "好，要仔細看螢幕，我教你。",
      },
      {
        id: "guzhang-politics-006-d",
        text: "幹……對啊，我最近也覺得東西變貴……",
        archetype: "meek",
        retort: "變貴很多，你要多注意開銷。",
      },
      {
        id: "guzhang-politics-006-e",
        text: "我都用手機付款，沒在算零錢……",
        archetype: "meek",
        retort: "那更要注意帳單金額。",
      },
      {
        id: "guzhang-politics-006-f",
        text: "靠，那乾脆以物易物，用薑黃換東西。",
        archetype: "backfire",
        retort: "（姑丈認真思考這個提議）",
      },
      {
        id: "guzhang-politics-006-g",
        text: "去死，找不到零錢是超商偷藏起來？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念物價）",
      },
      {
        id: "guzhang-politics-006-h",
        text: "幹，計較幾塊錢，血壓倒是不計較，死老頭。",
        archetype: "landmine",
        retort: "他吼一句台語，摔門進房。",
      },
    ],
  },
  {
    id: "guzhang-politics-007",
    text: "股市又跌了，我朋友的朋友都套牢。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-007-a",
        text: "幹，朋友的朋友又套牢？是不是編的？",
        archetype: "perfect",
        retort: "他愣住，表情僵了罵一句。",
      },
      {
        id: "guzhang-politics-007-b",
        text: "靠，姑丈自己有沒有在玩股票？",
        archetype: "deflect",
        retort: "有一點，都長期持有比較穩。",
      },
      {
        id: "guzhang-politics-007-c",
        text: "姑丈教我怎麼看盤比較不會慌？",
        archetype: "deflect",
        retort: "好，別天天看，我教你心法。",
      },
      {
        id: "guzhang-politics-007-d",
        text: "幹……我沒什麼錢投資，沒被套到……",
        archetype: "meek",
        retort: "沒被套也要學一下理財。",
      },
      {
        id: "guzhang-politics-007-e",
        text: "股票的事我真的看不懂……",
        archetype: "meek",
        retort: "看不懂就要多學，別當鴕鳥。",
      },
      {
        id: "guzhang-politics-007-f",
        text: "靠，那我朋友的朋友是不是要改吃薑黃？",
        archetype: "backfire",
        retort: "（姑丈認真回應，覺得有幫助）",
      },
      {
        id: "guzhang-politics-007-g",
        text: "去你的，套牢是不是像被綁架？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在裝傻）",
      },
      {
        id: "guzhang-politics-007-h",
        text: "幹，朋友的朋友根本是你編出來的，老番顛。",
        archetype: "landmine",
        retort: "他臉一垮，冷笑一聲不說話。",
      },
    ],
  },
  {
    id: "guzhang-politics-008",
    text: "颱風假放不放，每次都吵成這樣。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-008-a",
        text: "幹，退休了還吵放假，你是很閒？",
        archetype: "perfect",
        retort: "他訕笑，改口說算你厲害。",
      },
      {
        id: "guzhang-politics-008-b",
        text: "靠，姑丈退休後放不放假都無所謂了吧？",
        archetype: "deflect",
        retort: "哈哈說得對，天天都放假。",
      },
      {
        id: "guzhang-politics-008-c",
        text: "姑丈覺得該用什麼標準來判斷？",
        archetype: "deflect",
        retort: "應該看風雨真的多大，我覺得啦。",
      },
      {
        id: "guzhang-politics-008-d",
        text: "幹……我明天要上班，希望能放假……",
        archetype: "meek",
        retort: "希望歸希望，還是要看天氣。",
      },
      {
        id: "guzhang-politics-008-e",
        text: "我都直接聽公司通知，不太關心……",
        archetype: "meek",
        retort: "那你也要學會自己查一下。",
      },
      {
        id: "guzhang-politics-008-f",
        text: "靠，颱風假是不是能改成薑黃假？",
        archetype: "backfire",
        retort: "（姑丈認真思考，沒聽懂玩笑）",
      },
      {
        id: "guzhang-politics-008-g",
        text: "去死，颱風是不是也想放自己一天假？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念政策）",
      },
      {
        id: "guzhang-politics-008-h",
        text: "幹，退休沒事做，才會管這麼多閒事，死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，罵你講話白目。",
      },
    ],
  },
  {
    id: "guzhang-politics-009",
    text: "AI搶了一堆工作，以後怎麼辦啊。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-009-a",
        text: "幹，AI搶工作，搶得走你判斷力嗎？",
        archetype: "perfect",
        retort: "他語塞，講到一半改口罵幹。",
      },
      {
        id: "guzhang-politics-009-b",
        text: "靠，姑丈退得早，躲過這波真幸運？",
        archetype: "deflect",
        retort: "哈哈算我運氣好，你要加油。",
      },
      {
        id: "guzhang-politics-009-c",
        text: "姑丈覺得哪些工作比較安全？",
        archetype: "deflect",
        retort: "要跟人打交道的最安全，我覺得。",
      },
      {
        id: "guzhang-politics-009-d",
        text: "幹……我最近也有點擔心工作……",
        archetype: "meek",
        retort: "擔心就要提早準備轉型啊。",
      },
      {
        id: "guzhang-politics-009-e",
        text: "我對AI不太懂，也不知道怎麼準備……",
        archetype: "meek",
        retort: "那就要開始學，別逃避。",
      },
      {
        id: "guzhang-politics-009-f",
        text: "靠，那我改教AI認識薑黃好了。",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得是好主意）",
      },
      {
        id: "guzhang-politics-009-g",
        text: "去你的，AI是不是也被逼早起傳早安圖？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講AI趨勢）",
      },
      {
        id: "guzhang-politics-009-h",
        text: "幹，AI再厲害也騙不了你這麼容易，老屁股。",
        archetype: "landmine",
        retort: "他臉一垮，起身走去別桌。",
      },
    ],
  },
  {
    id: "guzhang-politics-010",
    text: "廟口那群老朋友都在聊政治，你也聽。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-010-a",
        text: "幹，廟口消息，跟你被騙那通一樣準。",
        archetype: "perfect",
        retort: "他愣住，話卡在喉嚨罵幹。",
      },
      {
        id: "guzhang-politics-010-b",
        text: "靠，姑丈在廟口的人緣真的很好？",
        archetype: "deflect",
        retort: "那當然，退休後要多交朋友。",
      },
      {
        id: "guzhang-politics-010-c",
        text: "那些朋友都聊些什麼，講給我聽？",
        archetype: "deflect",
        retort: "聊很多，物價、政策都有。",
      },
      {
        id: "guzhang-politics-010-d",
        text: "幹……那我在旁邊聽就好……",
        archetype: "meek",
        retort: "光聽不夠，也要說說你的想法。",
      },
      {
        id: "guzhang-politics-010-e",
        text: "廟口人太多，我怕插不上話……",
        archetype: "meek",
        retort: "沒關係，慢慢來，多聽就好。",
      },
      {
        id: "guzhang-politics-010-f",
        text: "靠，廟口聊政治是不是也要擲筊？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續聊得起勁）",
      },
      {
        id: "guzhang-politics-010-g",
        text: "去死，廟口消息是不是比新聞台還快？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在開玩笑）",
      },
      {
        id: "guzhang-politics-010-h",
        text: "幹，廟口那群跟你一樣退休沒事，死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，說你沒大沒小。",
      },
    ],
  },
  {
    id: "guzhang-politics-011",
    text: "健走的時候聊時事，你也發表一下。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-011-a",
        text: "幹，邊走邊聊，走不出一句真話。",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到快岔氣。",
      },
      {
        id: "guzhang-politics-011-b",
        text: "靠，姑丈邊走邊聊，體力真的很好？",
        archetype: "deflect",
        retort: "那當然，退休就是要多鍛鍊。",
      },
      {
        id: "guzhang-politics-011-c",
        text: "姑丈先講你的看法，我在旁邊學？",
        archetype: "deflect",
        retort: "好，那我先說，你聽好了。",
      },
      {
        id: "guzhang-politics-011-d",
        text: "幹……我邊走邊喘，講不太出話來……",
        archetype: "meek",
        retort: "喘一下就好，慢慢講。",
      },
      {
        id: "guzhang-politics-011-e",
        text: "我對這些議題真的沒什麼想法……",
        archetype: "meek",
        retort: "沒想法就要多關心一點啊。",
      },
      {
        id: "guzhang-politics-011-f",
        text: "靠，邊走邊聊時事是不是特殊訓練？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續加快腳步）",
      },
      {
        id: "guzhang-politics-011-g",
        text: "去你的，走這麼快是不是要趕去投票？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍嘴皮）",
      },
      {
        id: "guzhang-politics-011-h",
        text: "幹，你的看法跟謠言一樣沒查證，死老頭。",
        archetype: "landmine",
        retort: "他臉一垮，深吸一口氣不說話。",
      },
    ],
  },
  {
    id: "guzhang-politics-012",
    text: "選舉宣傳車一直繞，吵得我頭都痛了。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-012-a",
        text: "幹，車牌都記得，記不記得上次被騙？",
        archetype: "perfect",
        retort: "他語塞，眼神飄向別處罵幹。",
      },
      {
        id: "guzhang-politics-012-b",
        text: "靠，姑丈記性真好，車牌都能認？",
        archetype: "deflect",
        retort: "那當然，天天聽都聽出感情了。",
      },
      {
        id: "guzhang-politics-012-c",
        text: "姑丈覺得哪個口號印象最深？",
        archetype: "deflect",
        retort: "那句最順口，你也聽過吧。",
      },
      {
        id: "guzhang-politics-012-d",
        text: "幹……真的很吵，我耳塞都戴上了……",
        archetype: "meek",
        retort: "戴耳塞也要聽一下重點啦。",
      },
      {
        id: "guzhang-politics-012-e",
        text: "我在睡覺，都被吵醒好幾次……",
        archetype: "meek",
        retort: "白天睡覺也要體諒選舉季嘛。",
      },
      {
        id: "guzhang-politics-012-f",
        text: "靠，那我把它當成鬧鐘用好了。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念選情）",
      },
      {
        id: "guzhang-politics-012-g",
        text: "去死，宣傳車是不是薑黃業配贊助？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在亂扯）",
      },
      {
        id: "guzhang-politics-012-h",
        text: "幹，選舉很煩，你退休比選舉更閒，死老頭。",
        archetype: "landmine",
        retort: "他吼一句台語，轉頭不理你。",
      },
    ],
  },
  {
    id: "guzhang-politics-013",
    text: "電動車補助政策，你有沒有在關注。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-013-a",
        text: "幹，補助這麼熟，是不是又聽誰說？",
        archetype: "perfect",
        retort: "他愣住，動作僵在原地罵幹。",
      },
      {
        id: "guzhang-politics-013-b",
        text: "靠，姑丈考慮換電動車了嗎？",
        archetype: "deflect",
        retort: "有在看，充電方便就換。",
      },
      {
        id: "guzhang-politics-013-c",
        text: "姑丈幫我分析一下補助划不划算？",
        archetype: "deflect",
        retort: "好，這幾點你要注意，我教你。",
      },
      {
        id: "guzhang-politics-013-d",
        text: "幹……我對這個政策不太清楚……",
        archetype: "meek",
        retort: "不清楚就要多查一下相關資訊。",
      },
      {
        id: "guzhang-politics-013-e",
        text: "我現在的車還能開，先不換……",
        archetype: "meek",
        retort: "那你也可以先了解一下。",
      },
      {
        id: "guzhang-politics-013-f",
        text: "靠，電動車是不是充電就能治百病？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講補助方案）",
      },
      {
        id: "guzhang-politics-013-g",
        text: "去你的，電動車配薑黃是環保新趨勢？",
        archetype: "backfire",
        retort: "（姑丈認真考慮起這個組合）",
      },
      {
        id: "guzhang-politics-013-h",
        text: "幹，這補助跟你偏方一樣聽聽就好，老不死。",
        archetype: "landmine",
        retort: "他臉一垮，甩手不想理你。",
      },
    ],
  },
  {
    id: "guzhang-politics-014",
    text: "囤房稅出來了，房價會不會降一點。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-014-a",
        text: "幹，當年買得便宜，眼光還是嘴巴準？",
        archetype: "perfect",
        retort: "他嘴硬回一句，但沒底氣。",
      },
      {
        id: "guzhang-politics-014-b",
        text: "靠，姑丈當年買房的眼光真準？",
        archetype: "deflect",
        retort: "那當然，那時候夠便宜就買了。",
      },
      {
        id: "guzhang-politics-014-c",
        text: "姑丈覺得房價未來會怎麼走？",
        archetype: "deflect",
        retort: "應該會微降，我猜啦。",
      },
      {
        id: "guzhang-politics-014-d",
        text: "幹……我現在還是買不起，很無奈……",
        archetype: "meek",
        retort: "買不起也要繼續存錢啊。",
      },
      {
        id: "guzhang-politics-014-e",
        text: "我對這些政策不太懂細節……",
        archetype: "meek",
        retort: "不懂就要多花時間了解一下。",
      },
      {
        id: "guzhang-politics-014-f",
        text: "靠，那我用薑黃換一間房好了。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講囤房稅）",
      },
      {
        id: "guzhang-politics-014-g",
        text: "去死，囤房稅是不是能蓋薑黃園？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你答非所問）",
      },
      {
        id: "guzhang-politics-014-h",
        text: "幹，你那間房比你的偏方值錢多了，死老頭。",
        archetype: "landmine",
        retort: "他氣到講台語，冷哼一聲。",
      },
    ],
  },
  {
    id: "guzhang-politics-015",
    text: "退休年齡又要延後了，真的很扯。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-015-a",
        text: "幹，你退得早，是真早還是嘴巴早？",
        archetype: "perfect",
        retort: "他語塞，尷尬地清清喉嚨。",
      },
      {
        id: "guzhang-politics-015-b",
        text: "靠，姑丈退得早，真的很有先見之明？",
        archetype: "deflect",
        retort: "哈哈算是啦，運氣也算好。",
      },
      {
        id: "guzhang-politics-015-c",
        text: "姑丈退休前有沒有什麼準備建議？",
        archetype: "deflect",
        retort: "有喔，早點存錢最重要，我教你。",
      },
      {
        id: "guzhang-politics-015-d",
        text: "幹……那我可能要工作到很老了……",
        archetype: "meek",
        retort: "現實就是這樣，要有心理準備。",
      },
      {
        id: "guzhang-politics-015-e",
        text: "我還沒開始想退休的事……",
        archetype: "meek",
        retort: "那你現在就該開始想了。",
      },
      {
        id: "guzhang-politics-015-f",
        text: "靠，那我改喝薑黃延長工作壽命。",
        archetype: "backfire",
        retort: "（姑丈認真點頭，覺得有道理）",
      },
      {
        id: "guzhang-politics-015-g",
        text: "去你的，延後退休是不是要多發薑黃補貼？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念政策）",
      },
      {
        id: "guzhang-politics-015-h",
        text: "幹，退休這麼閒才會管這麼多閒事，老番顛。",
        archetype: "landmine",
        retort: "他臉一垮，安靜了整整十秒。",
      },
    ],
  },
  {
    id: "guzhang-politics-016",
    text: "詐騙集團真的很猖獗，你要小心。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-016-a",
        text: "幹，你也差點被騙，還敢說機警？",
        archetype: "perfect",
        retort: "他愣住，說不出話罵幹。",
      },
      {
        id: "guzhang-politics-016-b",
        text: "靠，姑丈是不是也差點被騙過？",
        archetype: "deflect",
        retort: "有啦，還好我機警反應快。",
      },
      {
        id: "guzhang-politics-016-c",
        text: "姑丈教我怎麼分辨詐騙電話？",
        archetype: "deflect",
        retort: "好，聽到要匯款就是詐騙，記住。",
      },
      {
        id: "guzhang-politics-016-d",
        text: "幹……我之前也差點被誘騙點連結……",
        archetype: "meek",
        retort: "差點就好，以後要更小心。",
      },
      {
        id: "guzhang-politics-016-e",
        text: "我不太會判斷，怕自己會上當……",
        archetype: "meek",
        retort: "不確定就先問我，我幫你看。",
      },
      {
        id: "guzhang-politics-016-f",
        text: "靠，那我請詐騙集團改推銷薑黃。",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續講詐騙案例）",
      },
      {
        id: "guzhang-politics-016-g",
        text: "去死，詐騙集團是不是比我懂時事？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你在耍寶）",
      },
      {
        id: "guzhang-politics-016-h",
        text: "幹，你上次就被騙了，還敢提醒我，死老頭？",
        archetype: "landmine",
        retort: "他臉一垮，半天說不出話。",
      },
    ],
  },
  {
    id: "guzhang-politics-017",
    text: "現在都去送外送，正職都沒人要做。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-017-a",
        text: "幹，正職不做？退休閒閒才叫不做正事。",
        archetype: "perfect",
        retort: "他語塞，乾笑罵一句幹。",
      },
      {
        id: "guzhang-politics-017-b",
        text: "靠，姑丈覺得外送員最辛苦哪點？",
        archetype: "deflect",
        retort: "應該是風吹日曬吧，很辛苦的。",
      },
      {
        id: "guzhang-politics-017-c",
        text: "姑丈平常有沒有叫外送啊？",
        archetype: "deflect",
        retort: "有喔，方便又省時間。",
      },
      {
        id: "guzhang-politics-017-d",
        text: "幹……我也有朋友在做，收入是不錯……",
        archetype: "meek",
        retort: "不錯歸不錯，但沒保障啊。",
      },
      {
        id: "guzhang-politics-017-e",
        text: "我對這個行業不太了解……",
        archetype: "meek",
        retort: "不了解就要多聽別人分享。",
      },
      {
        id: "guzhang-politics-017-f",
        text: "靠，那我幫忙代言，順便推薦薑黃。",
        archetype: "backfire",
        retort: "（姑丈認真思考這個提議）",
      },
      {
        id: "guzhang-politics-017-g",
        text: "去你的，外送員是不是比政治人物還忙？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念趨勢）",
      },
      {
        id: "guzhang-politics-017-h",
        text: "幹，你退休沒事做，比外送員還閒，老屁股。",
        archetype: "landmine",
        retort: "他氣到講台語，轉身不理你。",
      },
    ],
  },
  {
    id: "guzhang-politics-018",
    text: "減塑政策上路，塑膠袋都要收費了。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-018-a",
        text: "幹，早準備環保袋？跟你偏方一樣多。",
        archetype: "perfect",
        retort: "姑姑在旁邊笑到肩膀抖。",
      },
      {
        id: "guzhang-politics-018-b",
        text: "靠，姑丈是不是早就準備好環保袋了？",
        archetype: "deflect",
        retort: "那當然，我車上放了十個。",
      },
      {
        id: "guzhang-politics-018-c",
        text: "姑丈教我怎麼收納環保袋才方便？",
        archetype: "deflect",
        retort: "好，摺這樣最省空間，我教你。",
      },
      {
        id: "guzhang-politics-018-d",
        text: "幹……我常常忘記帶，都要多花錢……",
        archetype: "meek",
        retort: "多提醒自己，習慣就好了。",
      },
      {
        id: "guzhang-politics-018-e",
        text: "我覺得幾塊錢還好，沒特別在意……",
        archetype: "meek",
        retort: "幾塊錢累積起來也不少。",
      },
      {
        id: "guzhang-politics-018-f",
        text: "靠，那我用薑黃染布做環保袋好了。",
        archetype: "backfire",
        retort: "（姑丈眼睛一亮，認真考慮起來）",
      },
      {
        id: "guzhang-politics-018-g",
        text: "去死，塑膠袋收費是不是要練隨身術？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續碎念環保）",
      },
      {
        id: "guzhang-politics-018-h",
        text: "幹，做做樣子跟你的偏方一樣沒用，死老頭。",
        archetype: "landmine",
        retort: "他臉一垮，要姑姑幫他評評理。",
      },
    ],
  },
  {
    id: "guzhang-politics-019",
    text: "超商都變機器人結帳了，太科技了。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-019-a",
        text: "幹，學得比我快，分辨謠言怎麼慢？",
        archetype: "perfect",
        retort: "他改口說我回去查查看。",
      },
      {
        id: "guzhang-politics-019-b",
        text: "靠，姑丈學這個學得比我快耶？",
        archetype: "deflect",
        retort: "那當然，退休要跟上時代嘛。",
      },
      {
        id: "guzhang-politics-019-c",
        text: "姑丈教我怎麼用機器結帳？",
        archetype: "deflect",
        retort: "好，這個按鈕先按，我教你。",
      },
      {
        id: "guzhang-politics-019-d",
        text: "幹……我還是習慣找店員結帳……",
        archetype: "meek",
        retort: "要學會用機器，以後都這樣。",
      },
      {
        id: "guzhang-politics-019-e",
        text: "我對這些科技產品不太熟……",
        archetype: "meek",
        retort: "不熟就要多練習，別怕。",
      },
      {
        id: "guzhang-politics-019-f",
        text: "靠，機器人是不是也推薦薑黃給我？",
        archetype: "backfire",
        retort: "（姑丈認真思考這個可能性）",
      },
      {
        id: "guzhang-politics-019-g",
        text: "去你的，機器結帳是不是搶了店員工作？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續研究螢幕）",
      },
      {
        id: "guzhang-politics-019-h",
        text: "幹，你連謠言都分不清，還嫌機器，老東西？",
        archetype: "landmine",
        retort: "他吼一句台語，甩門進房間。",
      },
    ],
  },
  {
    id: "guzhang-politics-020",
    text: "政論節目的來賓又吵起來了，你看。",
    topic: "politics",
    bossId: "guzhang",
    options: [
      {
        id: "guzhang-politics-020-a",
        text: "幹，吵成這樣，你猜他們薪水誰付？",
        archetype: "perfect",
        retort: "他訕笑，轉頭找姑姑討救兵。",
      },
      {
        id: "guzhang-politics-020-b",
        text: "靠，姑丈看這節目居然不生氣，佩服？",
        archetype: "deflect",
        retort: "那當然，看習慣了就淡定了。",
      },
      {
        id: "guzhang-politics-020-c",
        text: "姑丈覺得誰講的比較有道理？",
        archetype: "deflect",
        retort: "都有一點道理，你自己聽聽看。",
      },
      {
        id: "guzhang-politics-020-d",
        text: "幹……他們吵成這樣，我聽得有點累……",
        archetype: "meek",
        retort: "累也要聽，這是重要議題。",
      },
      {
        id: "guzhang-politics-020-e",
        text: "我看不太懂他們在吵什麼重點……",
        archetype: "meek",
        retort: "看不懂就要多看幾次，慢慢懂。",
      },
      {
        id: "guzhang-politics-020-f",
        text: "靠，他們吵架是不是也算一種運動？",
        archetype: "backfire",
        retort: "（姑丈沒聽懂，繼續盯著電視）",
      },
      {
        id: "guzhang-politics-020-g",
        text: "去死，這節目是不是薪水按吵架算？",
        archetype: "backfire",
        retort: "（姑丈皺眉，覺得你太誇張）",
      },
      {
        id: "guzhang-politics-020-h",
        text: "幹，看這節目跟你信偏方一樣沒營養，死老頭。",
        archetype: "landmine",
        retort: "他臉一垮，別過頭不看你。",
      },
    ],
  },
] satisfies Question[];
