import type { Question } from "@/content/types";

// situations: 拿你跟表哥比／拿你跟同學比／拿你跟鄰居小孩比／彙整一桌今天聽到的情報做總比較／
// 講她那年代大家條件差不多現在你輸誰／拿你跟你爸媽當年比／說鄰居小孩出國留學／
// 拿你跟弟弟妹妹比／說朋友女兒嫁得好／拿你跟社群網紅朋友比／說朋友孩子樣樣都好問你怎麼辦／
// cross-ref說今天大家都輸給你就看你能不能贏她／拿你跟去年的你比退步論／說堂哥堂姊多厲害／
// 拿你跟她自己年輕時比／說別人小孩才藝很多／拿你跟隔壁老王小孩比／說聚餐大家都在比較看你有什麼／
// 拿你跟同期同事比／說別人都買車了／cross-ref彙整表姊三舅媽阿嬤今天問過的做總評比／
// 說要幫你介紹更優秀的人激你上進
export default [
  {
    id: "sangu-comparison-001",
    text: "你表哥今年升經理了，你呢？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-001-a", text: "他升經理，幹，那換問您女兒近況？", archetype: "perfect", retort: "……這句損，他媽的算你狠。" },
      { id: "sangu-comparison-001-b", text: "靠北，表哥升官，紅包會不會包大一點？", archetype: "deflect", retort: "少扯這個，快說你的規劃。" },
      { id: "sangu-comparison-001-c", text: "表哥厲害，機掰姑姑教育有方啊。", archetype: "deflect", retort: "貧嘴，別光誇人，說自己。" },
      { id: "sangu-comparison-001-d", text: "幹……我還在原職，公司升遷比較慢……", archetype: "meek", retort: "慢就要主動爭取，別乾等著。" },
      { id: "sangu-comparison-001-e", text: "靠……聽了有點壓力，但也替他開心啦……", archetype: "meek", retort: "有壓力就要轉成動力，加油。" },
      { id: "sangu-comparison-001-f", text: "經理而已，去你的我未來志在當老闆。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-comparison-001-g", text: "他升遷靠關係，機掰我靠實力慢慢來。", archetype: "backfire", retort: "……實力慢慢來，慢了幾年了。" },
      { id: "sangu-comparison-001-h", text: "表哥升經理，他媽的總比您女兒沒消息好，老東西。", archetype: "landmine", retort: "（摔筷）你他媽的找死！" },
    ],
  },
  {
    id: "sangu-comparison-002",
    text: "你同學小陳現在都出國深造了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-002-a", text: "他出國深造，他媽的至少他還會想回家。", archetype: "perfect", retort: "呵，這句夠壞，我服氣。" },
      { id: "sangu-comparison-002-b", text: "靠北，他讀哪個學校，姑姑幫我探探行情？", archetype: "deflect", retort: "去查了就知道，快說你打算。" },
      { id: "sangu-comparison-002-c", text: "他出國，機掰我留下來陪您過年，值得吧。", archetype: "deflect", retort: "貧嘴，別拿這個當藉口。" },
      { id: "sangu-comparison-002-d", text: "幹……他家經濟條件比較好，我沒那個本錢……", archetype: "meek", retort: "沒本錢也要想辦法，別放棄機會。" },
      { id: "sangu-comparison-002-e", text: "靠……聽了心裡難免有點羨慕，但也沒辦法……", archetype: "meek", retort: "羨慕就要化成行動，別只是想。" },
      { id: "sangu-comparison-002-f", text: "出國深造，去你的聽起來就是逃避現實。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-002-g", text: "我在國內深造，機掰本土訓練比較扎實。", archetype: "backfire", retort: "……本土訓練，訓練出什麼成果了？" },
      { id: "sangu-comparison-002-h", text: "深造有什麼用，幹，您女兒過年都沒回來吧，老太婆。", archetype: "landmine", retort: "幹，你給我記住！" },
    ],
  },
  {
    id: "sangu-comparison-003",
    text: "你看隔壁老王的兒子，多有出息啊。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-003-a", text: "有出息又怎樣，他媽的您今天還不是靠問這個。", archetype: "perfect", retort: "……好準，我認了。" },
      { id: "sangu-comparison-003-b", text: "靠北，老王家的事，姑姑消息真靈通耶。", archetype: "deflect", retort: "那當然，快跟人家多學學。" },
      { id: "sangu-comparison-003-c", text: "有出息，機掰那紅包會不會包很大？", archetype: "deflect", retort: "貧嘴，快說你自己有什麼打算。" },
      { id: "sangu-comparison-003-d", text: "幹……他真的很優秀，我還差他一大截……", archetype: "meek", retort: "差一大截就要更努力追上去。" },
      { id: "sangu-comparison-003-e", text: "靠……聽了難免有點壓力，但也替他開心……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-comparison-003-f", text: "有出息而已，去你的我未來是要當首富的。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-comparison-003-g", text: "他出息靠家裡，機掰我出息靠自己慢慢來。", archetype: "backfire", retort: "……慢慢來，慢了幾年了呢。" },
      { id: "sangu-comparison-003-h", text: "有出息，幹，總比您一年就這天有存在感好，老東西。", archetype: "landmine", retort: "去死啦你，滾出去！" },
    ],
  },
  {
    id: "sangu-comparison-004",
    text: "三舅媽說表哥四萬，陳太太說你也差不多，比較起來呢？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-004-a", text: "差不多也好，他媽的總比您媳婦跟您差得遠好。", archetype: "perfect", retort: "呵，這句夠毒，算你狠。" },
      { id: "sangu-comparison-004-b", text: "靠北，大家的情報，怎麼在您這邊都對上了？", archetype: "deflect", retort: "我這桌是情報總部，快回答。" },
      { id: "sangu-comparison-004-c", text: "差不多的話，機掰那紅包也差不多包吧。", archetype: "deflect", retort: "貧嘴，快說你認不認同這數字。" },
      { id: "sangu-comparison-004-d", text: "幹……差不多是真的，我們起薪都類似……", archetype: "meek", retort: "起薪類似，那以後呢？要拉開差距。" },
      { id: "sangu-comparison-004-e", text: "靠……聽大家都在講，壓力真的滿大的……", archetype: "meek", retort: "壓力大就要努力，別被比下去。" },
      { id: "sangu-comparison-004-f", text: "數字而已，去你的我的人生格局比較大啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-004-g", text: "薪水低，但我心靈富足，機掰境界更高。", archetype: "backfire", retort: "……境界高，房租繳得出來嗎。" },
      { id: "sangu-comparison-004-h", text: "全桌比較我，幹，怎麼沒人比較您跟媳婦，老太婆。", archetype: "landmine", retort: "（臉色鐵青）你完了。" },
    ],
  },
  {
    id: "sangu-comparison-005",
    text: "我們那年代大家條件差不多，現在你輸誰了？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-005-a", text: "沒輸誰，但您他媽的當年嫁得倉促，我不急。", archetype: "perfect", retort: "……這句我記下來了。" },
      { id: "sangu-comparison-005-b", text: "靠北，那年代條件差不多，姑姑當年贏誰啊？", archetype: "deflect", retort: "我沒輸過，快說你的計畫。" },
      { id: "sangu-comparison-005-c", text: "厲害，機掰姑姑那時候一定很努力。", archetype: "deflect", retort: "那當然，別光說嘴，快去努力。" },
      { id: "sangu-comparison-005-d", text: "幹……現在競爭真的比以前激烈很多……", archetype: "meek", retort: "激烈也要拚，別找藉口放棄。" },
      { id: "sangu-comparison-005-e", text: "靠……我也想追上去，只是速度真的比較慢……", archetype: "meek", retort: "速度慢就要更拚，年輕人加油。" },
      { id: "sangu-comparison-005-f", text: "那年代選項少，去你的比較容易出頭啦。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-comparison-005-g", text: "現在講究的是軟實力，機掰不是硬拚。", archetype: "backfire", retort: "……軟實力，軟到哪去了呢。" },
      { id: "sangu-comparison-005-h", text: "我輸的人裡，幹，不包括嫁得那麼快的您，老東西。", archetype: "landmine", retort: "幹你娘咧，你給我記住這句。" },
    ],
  },
  {
    id: "sangu-comparison-006",
    text: "你爸媽當年像你這年紀，早就成家立業了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-006-a", text: "他們成家立業，他媽的您女兒到現在呢？", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-comparison-006-b", text: "靠北，爸媽當年立業，是姑姑幫忙牽線嗎？", archetype: "deflect", retort: "少扯這個，快說你的想法。" },
      { id: "sangu-comparison-006-c", text: "那個年代房價，機掰姑姑還記得嗎？", archetype: "deflect", retort: "記得，但別轉移話題。" },
      { id: "sangu-comparison-006-d", text: "幹……現在的環境真的比當年難很多……", archetype: "meek", retort: "難也要拚，不能光說環境不好。" },
      { id: "sangu-comparison-006-e", text: "靠……聽了心裡不太舒服，但也沒辦法反駁……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-comparison-006-f", text: "那年代結婚早，去你的是因為選項少而已。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-comparison-006-g", text: "我這代講究品質婚姻，機掰不急著成家。", archetype: "backfire", retort: "……品質婚姻，品質在哪呢？" },
      { id: "sangu-comparison-006-h", text: "成家立業，幹，您女兒都幾歲了還沒嫁，老太婆。", archetype: "landmine", retort: "（拍桌）滾，你他媽的滾！" },
    ],
  },
  {
    id: "sangu-comparison-007",
    text: "鄰居的女兒，聽說要出國留學了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-007-a", text: "留學好，他媽的至少不用年年被自己媽問。", archetype: "perfect", retort: "呵，這句夠壞，我笑了。" },
      { id: "sangu-comparison-007-b", text: "靠北，留學費用，姑姑幫我打聽多少？", archetype: "deflect", retort: "很貴，快跟人家看齊努力。" },
      { id: "sangu-comparison-007-c", text: "出國留學，機掰那紅包一定包很大吧？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-007-d", text: "幹……她家條件比較好，我沒那個本錢……", archetype: "meek", retort: "沒本錢也要想辦法，別放棄。" },
      { id: "sangu-comparison-007-e", text: "靠……每個人條件不同，但心裡難免比較……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-comparison-007-f", text: "留學而已，去你的我心靈自由值千萬學位。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-comparison-007-g", text: "她一定是靠家裡，機掰我這是白手起家。", archetype: "backfire", retort: "……白手起家，起到哪一步了？" },
      { id: "sangu-comparison-007-h", text: "留學，幹，總比您女兒離婚後躲在家好，老東西。", archetype: "landmine", retort: "（全桌安靜）你他媽的說完了？" },
    ],
  },
  {
    id: "sangu-comparison-008",
    text: "你弟弟現在都比你有成就了耶。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-008-a", text: "他有成就，他媽的那您問問媳婦的成就如何？", archetype: "perfect", retort: "……這句我認了。" },
      { id: "sangu-comparison-008-b", text: "靠北，姑姑覺得成就要怎麼定義比較公平？", archetype: "deflect", retort: "看收入跟穩定度，你自己想。" },
      { id: "sangu-comparison-008-c", text: "弟弟優秀，機掰家族基因果然強大。", archetype: "deflect", retort: "貧嘴，說到底你自己怎樣。" },
      { id: "sangu-comparison-008-d", text: "幹……他確實走得比較順，我還在摸索……", archetype: "meek", retort: "摸索太久，會被弟弟追過去喔。" },
      { id: "sangu-comparison-008-e", text: "靠……聽了心裡有點不是滋味，但也沒辦法……", archetype: "meek", retort: "沒辦法就要想辦法，別認命。" },
      { id: "sangu-comparison-008-f", text: "他成就高，去你的是靠我這個哥哥鋪路的。", archetype: "backfire", retort: "（三姑挑眉，弟弟在旁翻白眼）" },
      { id: "sangu-comparison-008-g", text: "我這叫大器晚成，機掰等著看好戲吧。", archetype: "backfire", retort: "……晚成，晚到現在還沒成呢。" },
      { id: "sangu-comparison-008-h", text: "拿弟弟比我，幹，怎麼不提您媳婦比您能幹，老太婆。", archetype: "landmine", retort: "機掰，你找死！" },
    ],
  },
  {
    id: "sangu-comparison-009",
    text: "朋友的女兒嫁得好，你什麼時候輪到？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-009-a", text: "等我先問問您女兒，他媽的是不是也在等。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-comparison-009-b", text: "靠北，她嫁得好，是您牽的線嗎姑姑？", archetype: "deflect", retort: "不是，快說你自己的打算。" },
      { id: "sangu-comparison-009-c", text: "嫁得好的定義，機掰姑姑先說標準嘛。", archetype: "deflect", retort: "貧嘴，人品好家境好就是了。" },
      { id: "sangu-comparison-009-d", text: "幹……還沒有對象，這個問題有點太快了……", archetype: "meek", retort: "太快？那你更要積極一點了。" },
      { id: "sangu-comparison-009-e", text: "靠……聽了心裡有點著急，但真的急不來……", archetype: "meek", retort: "急不來也要有行動，不能空等。" },
      { id: "sangu-comparison-009-f", text: "嫁得好而已，去你的我打算單身嫁給事業。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-comparison-009-g", text: "我這種人才，機掰機會多到挑花眼啦。", archetype: "backfire", retort: "……挑花眼，那怎麼還沒挑到人。" },
      { id: "sangu-comparison-009-h", text: "嫁得好，幹，總比您女兒嫁完又離的好，老東西。", archetype: "landmine", retort: "（笑容凍住）你他媽的繼續啊。" },
    ],
  },
  {
    id: "sangu-comparison-010",
    text: "你那個網紅朋友，最近又出國玩了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-010-a", text: "她曬生活，他媽的我曬您紅包最小包這件事。", archetype: "perfect", retort: "呵，這句夠狠，我服氣。" },
      { id: "sangu-comparison-010-b", text: "靠北，姑姑也有在追蹤她的帳號嗎？", archetype: "deflect", retort: "有，快說你怎麼看這件事。" },
      { id: "sangu-comparison-010-c", text: "她出國玩，機掰紅包會不會分我一點？", archetype: "deflect", retort: "貧嘴，人家是靠自己賺的。" },
      { id: "sangu-comparison-010-d", text: "幹……看她過得那麼精彩，難免有點羨慕……", archetype: "meek", retort: "羨慕就要化成行動，別只是滑手機。" },
      { id: "sangu-comparison-010-e", text: "靠……每個人選擇不同，但心裡還是會比較……", archetype: "meek", retort: "會比較，就要想辦法追上去。" },
      { id: "sangu-comparison-010-f", text: "網紅曬照，去你的都是包裝出來的假象啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-010-g", text: "我這叫低調富有，機掰不需要曬給人看。", archetype: "backfire", retort: "……低調富有，存摺敢拿出來看嗎。" },
      { id: "sangu-comparison-010-h", text: "她出國玩，幹，總比您靠今天刷存在感好，老太婆。", archetype: "landmine", retort: "（聲音一冷）你他媽的以為在跟你開玩笑？" },
    ],
  },
  {
    id: "sangu-comparison-011",
    text: "我朋友的孩子樣樣都好，你要不要學學？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-011-a", text: "學是要學，但他媽的不學您跟媳婦相處方式。", archetype: "perfect", retort: "……這句我記下來了。" },
      { id: "sangu-comparison-011-b", text: "靠北，他樣樣都好，那有沒有樣樣都累啊？", archetype: "deflect", retort: "少貧嘴，快說你要怎麼進步。" },
      { id: "sangu-comparison-011-c", text: "他厲害，機掰姑姑朋友教育有方啊。", archetype: "deflect", retort: "貧嘴，別光誇人，說自己。" },
      { id: "sangu-comparison-011-d", text: "幹……聽了確實有點自愧不如……", archetype: "meek", retort: "自愧不如就要努力追上去，別認輸。" },
      { id: "sangu-comparison-011-e", text: "靠……每個人擅長不同，但也會忍不住比較……", archetype: "meek", retort: "忍不住比較，就要化成動力啊。" },
      { id: "sangu-comparison-011-f", text: "樣樣都好，去你的聽起來就很累人啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-011-g", text: "我這叫術業有專攻，機掰不用樣樣都行。", archetype: "backfire", retort: "……術業有專攻，攻在哪呢？" },
      { id: "sangu-comparison-011-h", text: "樣樣都好，幹，總比您跟媳婦水火不容好，老東西。", archetype: "landmine", retort: "（摔筷）這什麼話，你他媽的收回去。" },
    ],
  },
  {
    id: "sangu-comparison-012",
    text: "今天大家都輸給你嘴，就看我能不能贏。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-012-a", text: "姑姑贏一年就這一天，他媽的我讓您。", archetype: "perfect", retort: "……你這句，夠狠，我服。" },
      { id: "sangu-comparison-012-b", text: "靠北，聽說您這關才是真正的大魔王？", archetype: "deflect", retort: "算你識貨，準備好了嗎。" },
      { id: "sangu-comparison-012-c", text: "先讓我喘口氣，機掰您慢慢來沒關係。", archetype: "deflect", retort: "慢慢來也躲不掉，準備好吧。" },
      { id: "sangu-comparison-012-d", text: "幹……說實話，我今天有點招架不住了……", archetype: "meek", retort: "招架不住？那更要打起精神。" },
      { id: "sangu-comparison-012-e", text: "靠……大家都問過一輪，我真的有點累了……", archetype: "meek", retort: "累也要撐住，這才是最後一關。" },
      { id: "sangu-comparison-012-f", text: "姑姑您年紀大了，去你的嘴皮子可能練不過我。", archetype: "backfire", retort: "（三姑笑意收了，眼神一冷）" },
      { id: "sangu-comparison-012-g", text: "我今天是故意留手，機掰怕您受不了。", archetype: "backfire", retort: "……留手，那你倒是show一個看看。" },
      { id: "sangu-comparison-012-h", text: "您嘴贏全場，幹，可惜贏不回女兒電話，老太婆。", archetype: "landmine", retort: "幹你娘咧，你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-comparison-013",
    text: "你跟去年比，怎麼感覺退步了？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-013-a", text: "退步是假象，他媽的不像您媳婦那樣沒進展。", archetype: "perfect", retort: "呵，這句損，我認了。" },
      { id: "sangu-comparison-013-b", text: "靠北，姑姑覺得退步的標準是什麼啊？", archetype: "deflect", retort: "看你精神跟氣色，都不如以前。" },
      { id: "sangu-comparison-013-c", text: "退步一點，機掰才顯得您進步得快。", archetype: "deflect", retort: "貧嘴，快說到底怎麼了。" },
      { id: "sangu-comparison-013-d", text: "幹……最近確實比較沒精神，狀態不太好……", archetype: "meek", retort: "狀態不好要調整，別放任下去。" },
      { id: "sangu-comparison-013-e", text: "靠……去年那時候比較拚，今年是有點鬆懈……", archetype: "meek", retort: "鬆懈就要收心，別再拖延了。" },
      { id: "sangu-comparison-013-f", text: "退步是因為我在沉澱，去你的這叫戰略。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-013-g", text: "退步只是表面，機掰內在其實突飛猛進。", archetype: "backfire", retort: "……突飛猛進，猛進到哪去了？" },
      { id: "sangu-comparison-013-h", text: "退步，幹，總比您跟媳婦關係退步到冰點好，老東西。", archetype: "landmine", retort: "（冷眼）幹，這桌你今天別坐了。" },
    ],
  },
  {
    id: "sangu-comparison-014",
    text: "堂哥去年考上律師，你聽了什麼感覺？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-014-a", text: "很替他開心，他媽的順便問您女兒工作定了沒。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-comparison-014-b", text: "靠北，他考上律師，姑姑要不要先諮詢一下？", archetype: "deflect", retort: "貧嘴，快說你自己的感覺。" },
      { id: "sangu-comparison-014-c", text: "考上律師，機掰那紅包會不會包大一點？", archetype: "deflect", retort: "少扯這個，正經回答我。" },
      { id: "sangu-comparison-014-d", text: "幹……聽了確實有點壓力，覺得自己落後了……", archetype: "meek", retort: "落後就要追，別只是感嘆。" },
      { id: "sangu-comparison-014-e", text: "靠……替他開心，但心裡也難免比較一下……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-comparison-014-f", text: "律師而已，去你的我未來是要當立法委員。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-014-g", text: "他考律師靠補習，機掰我靠自學比較強。", archetype: "backfire", retort: "……自學比較強，強到哪去了？" },
      { id: "sangu-comparison-014-h", text: "考上律師，幹，總比您女兒感情一直沒著落好，老太婆。", archetype: "landmine", retort: "去死啦你，滾出去！" },
    ],
  },
  {
    id: "sangu-comparison-015",
    text: "我當年像你這歲數，早就闖出一片天了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-015-a", text: "所以我才要跟您學，他媽的怎麼把場面撐起來。", archetype: "perfect", retort: "……好準，這句我認了。" },
      { id: "sangu-comparison-015-b", text: "靠北，姑姑當年闖出的那片天，長什麼樣？", archetype: "deflect", retort: "又大又亮，快跟我多學學。" },
      { id: "sangu-comparison-015-c", text: "闖天下之前，機掰姑姑先教我幾招吧。", archetype: "deflect", retort: "貧嘴，先靠自己努力再說。" },
      { id: "sangu-comparison-015-d", text: "幹……現在的環境真的比當年競爭激烈很多……", archetype: "meek", retort: "激烈也要拚，別找藉口放棄。" },
      { id: "sangu-comparison-015-e", text: "靠……聽了是有點刺耳，但也說不出反駁……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-comparison-015-f", text: "那年代選項少，去你的隨便闖都算闖出來。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-comparison-015-g", text: "我這代講究慢活，機掰不急著闖天下。", archetype: "backfire", retort: "……慢活，慢到現在還沒個影。" },
      { id: "sangu-comparison-015-h", text: "闖出一片天，幹，但您那片天讓媳婦很委屈吧，老東西。", archetype: "landmine", retort: "（拍桌）你他媽的完了！" },
    ],
  },
  {
    id: "sangu-comparison-016",
    text: "人家小孩學鋼琴又學畫畫，樣樣精通。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-016-a", text: "我小時候學的是看您臉色，他媽的也是一技之長。", archetype: "perfect", retort: "呵呵，這句夠壞，我笑了，記下了。" },
      { id: "sangu-comparison-016-b", text: "靠北，他學那麼多才藝，補習費多少啊？", archetype: "deflect", retort: "很多，快跟人家看齊努力。" },
      { id: "sangu-comparison-016-c", text: "樣樣精通，機掰那紅包一定包很大吧？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-016-d", text: "幹……我小時候沒機會學那些，有點羨慕……", archetype: "meek", retort: "羨慕就要現在補回來啊。" },
      { id: "sangu-comparison-016-e", text: "靠……每個人成長環境不同，但也會比較……", archetype: "meek", retort: "會比較，就要化成動力啊。" },
      { id: "sangu-comparison-016-f", text: "才藝多沒用，去你的我這叫大智若愚。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-016-g", text: "我小時候學的是人生哲學，機掰比較深奧。", archetype: "backfire", retort: "……人生哲學，學到什麼結論了？" },
      { id: "sangu-comparison-016-h", text: "樣樣精通，幹，總比您女兒現在什麼都沒精通好，老太婆。", archetype: "landmine", retort: "（笑容不見）明年你他媽的不用來了。" },
    ],
  },
  {
    id: "sangu-comparison-017",
    text: "隔壁老王的小孩，暑假還去實習賺錢。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-017-a", text: "他實習賺錢，他媽的我實習怎麼接您的話。", archetype: "perfect", retort: "……這句我認了，算你機靈。" },
      { id: "sangu-comparison-017-b", text: "靠北，他實習哪間公司，姑姑幫我打聽？", archetype: "deflect", retort: "去查了就知道，快跟人學學。" },
      { id: "sangu-comparison-017-c", text: "暑假實習，機掰那紅包會不會包大一點？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-017-d", text: "幹……我學生時代忙著打工顧生活，沒空實習……", archetype: "meek", retort: "沒空？那你現在更要補上。" },
      { id: "sangu-comparison-017-e", text: "靠……聽了心裡有點慚愧，覺得自己起步晚了……", archetype: "meek", retort: "起步晚就要跑快一點，別認輸。" },
      { id: "sangu-comparison-017-f", text: "實習而已，去你的我大學時就已經在創業了。", archetype: "backfire", retort: "（三姑笑笑，沒人相信這說法）" },
      { id: "sangu-comparison-017-g", text: "他家有資源才實習得到，機掰不能比。", archetype: "backfire", retort: "……不能比，那你現在做了什麼？" },
      { id: "sangu-comparison-017-h", text: "實習賺錢，幹，總比您靠過年這天刷存在感值錢，老東西。", archetype: "landmine", retort: "（笑容凍住）你他媽的繼續啊。" },
    ],
  },
  {
    id: "sangu-comparison-018",
    text: "今天聚餐大家都在比，你有什麼可以說嘴？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-018-a", text: "我說嘴的是全場沒人敢直接嗆您，他媽的。", archetype: "perfect", retort: "……呵，算你狠，我服了。" },
      { id: "sangu-comparison-018-b", text: "靠北，姑姑最想聽哪方面的說嘴內容？", archetype: "deflect", retort: "隨便，你倒是說一個來聽聽。" },
      { id: "sangu-comparison-018-c", text: "我最值得說嘴的，機掰就是有您這樣的姑姑。", archetype: "deflect", retort: "貧嘴，快說點實質的東西。" },
      { id: "sangu-comparison-018-d", text: "幹……說實話，一時之間我還真想不出來……", archetype: "meek", retort: "想不出來？那你要好好反省了。" },
      { id: "sangu-comparison-018-e", text: "靠……沒什麼特別的，就是平凡過日子而已……", archetype: "meek", retort: "平凡不是壞事，但也該有點目標。" },
      { id: "sangu-comparison-018-f", text: "我最值得說嘴的，去你的就是我很會說嘴。", archetype: "backfire", retort: "（三姑無語，全桌安靜）" },
      { id: "sangu-comparison-018-g", text: "我的成就都是內在的，機掰看不出來啦。", archetype: "backfire", retort: "……看不出來，那怎麼證明有？" },
      { id: "sangu-comparison-018-h", text: "說嘴喔，幹，不如比比您媳婦被逼走幾次，老太婆。", archetype: "landmine", retort: "機掰，你找死！" },
    ],
  },
  {
    id: "sangu-comparison-019",
    text: "你同期進公司的同事，都升主管了吧？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-019-a", text: "他們升主管，他媽的我升級成您嘴裡的話題。", archetype: "perfect", retort: "呵，這句我服了。" },
      { id: "sangu-comparison-019-b", text: "靠北，他們升主管，是不是加班比較多啊？", archetype: "deflect", retort: "少貧嘴，快說你自己的進度。" },
      { id: "sangu-comparison-019-c", text: "他們升主管，機掰紅包會不會包大一點？", archetype: "deflect", retort: "貧嘴，快說你怎麼想這件事。" },
      { id: "sangu-comparison-019-d", text: "幹……確實，有幾個同期的已經升上去了……", archetype: "meek", retort: "升上去了？那你更該加緊努力了。" },
      { id: "sangu-comparison-019-e", text: "靠……聽了難免有點壓力，但也替他們開心……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-comparison-019-f", text: "主管而已，去你的我未來是要當創辦人的。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-comparison-019-g", text: "他們升遷靠關係，機掰我靠實力慢慢來。", archetype: "backfire", retort: "……實力慢慢來，慢了幾年了。" },
      { id: "sangu-comparison-019-h", text: "升不升主管，幹，關您什麼事，問問媳婦吧，老東西。", archetype: "landmine", retort: "去死啦你，滾出去！" },
    ],
  },
  {
    id: "sangu-comparison-020",
    text: "你朋友都買車了，你怎麼還在騎機車？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-020-a", text: "機車省油，他媽的夠我年年回來聽您念。", archetype: "perfect", retort: "……嘴皮子隨你媽，我認了。" },
      { id: "sangu-comparison-020-b", text: "靠北，姑姑覺得先買車還是先買房比較好？", archetype: "deflect", retort: "當然先買房，別本末倒置。" },
      { id: "sangu-comparison-020-c", text: "騎機車，機掰才能常常繞去看姑姑。", archetype: "deflect", retort: "貧嘴，快說你的存錢計畫。" },
      { id: "sangu-comparison-020-d", text: "幹……存款真的還不夠買車，只能先騎機車……", archetype: "meek", retort: "不夠就要存，別羨慕別人。" },
      { id: "sangu-comparison-020-e", text: "靠……看朋友一個個買車，心裡難免有點急……", archetype: "meek", retort: "急就要行動，光急沒有用。" },
      { id: "sangu-comparison-020-f", text: "騎機車比較潮，去你的這叫街頭風格啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-020-g", text: "我不買車，是為了減少碳排放救地球，機掰。", archetype: "backfire", retort: "……救地球，那你多久沒存錢了。" },
      { id: "sangu-comparison-020-h", text: "騎機車關您什麼事，幹，先管好您跟媳婦的事，老太婆。", archetype: "landmine", retort: "（摔筷）這種話，你他媽的會後悔。" },
    ],
  },
  {
    id: "sangu-comparison-021",
    text: "表姊、三舅媽、阿嬤今天問的，姑姑都聽說了，一起算算總帳吧。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-021-a", text: "算總帳？他媽的您女兒的帳您先算清楚。", archetype: "perfect", retort: "……好狠，這句我服了。" },
      { id: "sangu-comparison-021-b", text: "靠北，這桌是不是有個家族情報交換群組啊？", archetype: "deflect", retort: "算你聰明，快接受總評比吧。" },
      { id: "sangu-comparison-021-c", text: "算總帳前，機掰先讓我喘口氣吃塊肉。", archetype: "deflect", retort: "吃完就要面對，躲不掉的。" },
      { id: "sangu-comparison-021-d", text: "幹……今天被問了一整輪，真的有點招架不住……", archetype: "meek", retort: "招架不住？那更要打起精神應戰。" },
      { id: "sangu-comparison-021-e", text: "靠……每個問題都戳中痛處，心裡壓力很大……", archetype: "meek", retort: "壓力大就要正面迎戰，別逃避。" },
      { id: "sangu-comparison-021-f", text: "總帳？去你的我今天全勝，沒什麼好算的。", archetype: "backfire", retort: "（三姑笑意收了，眼神一冷）" },
      { id: "sangu-comparison-021-g", text: "我早就把答案都準備好了，機掰不怕算。", archetype: "backfire", retort: "……準備好了？那怎麼還在流汗。" },
      { id: "sangu-comparison-021-h", text: "算總帳，幹，不如算算您這年就這天被記得，老東西。", archetype: "landmine", retort: "（沉默三秒）機掰，你說完了？" },
    ],
  },
  {
    id: "sangu-comparison-022",
    text: "我認識更優秀的人，要不要介紹你認識？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-022-a", text: "介紹可以，但他媽的別跟您女兒現在對象一樣。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-comparison-022-b", text: "靠北，優秀到什麼程度，姑姑先透露一點？", archetype: "deflect", retort: "見面就知道，別問那麼細。" },
      { id: "sangu-comparison-022-c", text: "介紹可以，機掰但姑姑要負責到底喔。", archetype: "deflect", retort: "當然，我看人一向很準。" },
      { id: "sangu-comparison-022-d", text: "幹……好是好，但我怕被比下去更沒自信……", archetype: "meek", retort: "沒自信就要練，別逃避挑戰。" },
      { id: "sangu-comparison-022-e", text: "靠……可以試試看，只是有點緊張……", archetype: "meek", retort: "緊張什麼，認識而已，別想太多。" },
      { id: "sangu-comparison-022-f", text: "優秀的人，去你的通常都眼光更高，我怕怕。", archetype: "backfire", retort: "（三姑笑笑，沒人接話）" },
      { id: "sangu-comparison-022-g", text: "我自己就是那個優秀的人，機掰不用介紹。", archetype: "backfire", retort: "……不用介紹，那你倒是拿出成績。" },
      { id: "sangu-comparison-022-h", text: "介紹對象前，幹，先介紹您跟媳婦和好方法，老太婆。", archetype: "landmine", retort: "幹你娘咧，你這是要翻臉？" },
    ],
  },
] satisfies Question[];
