import type { Question } from "@/content/types";

// situations: 拿你跟表哥比／拿你跟同學比／拿你跟鄰居小孩比／彙整一桌今天聽到的情報做總比較／
// 講她那年代大家條件差不多現在你輸誰／拿你跟你爸媽當年比／說鄰居小孩出國留學／
// 拿你跟弟弟妹妹比／說朋友女兒嫁得好／拿你跟社群網紅朋友比／說朋友孩子樣樣都好問你怎麼辦／
// cross-ref說今天大家都輸給你就看你能不能贏她／拿你跟去年的你比退步論／說堂哥堂姊多厲害／
// 拿你跟她自己年輕時比／說別人小孩才藝很多／拿你跟隔壁老王小孩比／說聚餐大家都在比較看你有什麼／
// 拿你跟同期同事比／說別人都買車了／cross-ref彙整表姊三舅媽阿嬤今天問過的做總評比／
// 說要幫你介紹更優秀的人激你上進
export default [
  {
    id: "sangu-comparison-001",
    text: "你表哥今年升經理了，你呢？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-001-a", text: "他升經理，我升級成更會聊天的自己。", archetype: "perfect", retort: "……好，這句我記下來了。" },
      { id: "sangu-comparison-001-b", text: "表哥升官，紅包會不會包大一點？", archetype: "deflect", retort: "少扯這個，快說你的規劃。" },
      { id: "sangu-comparison-001-c", text: "表哥厲害，姑姑教育有方啊。", archetype: "deflect", retort: "貧嘴，別光誇人，說自己。" },
      { id: "sangu-comparison-001-d", text: "我還在原職，公司升遷比較慢……", archetype: "meek", retort: "慢就要主動爭取，別乾等著。" },
      { id: "sangu-comparison-001-e", text: "聽了有點壓力，但也替他開心啦……", archetype: "meek", retort: "有壓力就要轉成動力，加油。" },
      { id: "sangu-comparison-001-f", text: "經理而已，我未來志在當老闆。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-comparison-001-g", text: "他升遷靠關係，我靠實力慢慢來。", archetype: "backfire", retort: "……實力慢慢來，慢了幾年了。" },
      { id: "sangu-comparison-001-h", text: "表哥升經理是不是靠舅舅安排的？", archetype: "landmine", retort: "（笑意更冷）人家是憑本事的。" },
    ],
  },
  {
    id: "sangu-comparison-002",
    text: "你同學小陳現在都出國深造了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-002-a", text: "他出國深造，我留鄉深耕，各有天地。", archetype: "perfect", retort: "呵，這句有氣勢，我服氣。" },
      { id: "sangu-comparison-002-b", text: "他讀哪個學校，姑姑幫我探探行情？", archetype: "deflect", retort: "去查了就知道，快說你打算。" },
      { id: "sangu-comparison-002-c", text: "他出國，我留下來陪您過年，值得吧。", archetype: "deflect", retort: "貧嘴，別拿這個當藉口。" },
      { id: "sangu-comparison-002-d", text: "他家經濟條件比較好，我沒那個本錢……", archetype: "meek", retort: "沒本錢也要想辦法，別放棄機會。" },
      { id: "sangu-comparison-002-e", text: "聽了心裡難免有點羨慕，但也沒辦法……", archetype: "meek", retort: "羨慕就要化成行動，別只是想。" },
      { id: "sangu-comparison-002-f", text: "出國深造，聽起來就是逃避現實。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-002-g", text: "我在國內深造，本土訓練比較扎實。", archetype: "backfire", retort: "……本土訓練，訓練出什麼成果了？" },
      { id: "sangu-comparison-002-h", text: "拿小陳的事比較，很煩耶姑姑。", archetype: "landmine", retort: "（笑意更冷）我只是舉個例子而已。" },
    ],
  },
  {
    id: "sangu-comparison-003",
    text: "你看隔壁老王的兒子，多有出息啊。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-003-a", text: "有出息，改天請他來教教我怎麼做。", archetype: "perfect", retort: "……好，這句大方又聰明。" },
      { id: "sangu-comparison-003-b", text: "老王家的事，姑姑消息真靈通耶。", archetype: "deflect", retort: "那當然，快跟人家多學學。" },
      { id: "sangu-comparison-003-c", text: "有出息，那紅包會不會包很大？", archetype: "deflect", retort: "貧嘴，快說你自己有什麼打算。" },
      { id: "sangu-comparison-003-d", text: "他真的很優秀，我還差他一大截……", archetype: "meek", retort: "差一大截就要更努力追上去。" },
      { id: "sangu-comparison-003-e", text: "聽了難免有點壓力，但也替他開心……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-comparison-003-f", text: "有出息而已，我未來是要當首富的。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-comparison-003-g", text: "他出息靠家裡，我出息靠自己慢慢來。", archetype: "backfire", retort: "……慢慢來，慢了幾年了呢。" },
      { id: "sangu-comparison-003-h", text: "老王家的事，姑姑打聽得真清楚。", archetype: "landmine", retort: "（笑意更冷）我消息一向靈通。" },
    ],
  },
  {
    id: "sangu-comparison-004",
    text: "三舅媽說表哥四萬，陳太太說你也差不多，比較起來呢？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-004-a", text: "差不多好，代表我跟表哥一樣有前途。", archetype: "perfect", retort: "呵，這句反將一軍，我服氣。" },
      { id: "sangu-comparison-004-b", text: "大家的情報，怎麼在您這邊都對上了？", archetype: "deflect", retort: "我這桌是情報總部，快回答。" },
      { id: "sangu-comparison-004-c", text: "差不多的話，那紅包也差不多包吧。", archetype: "deflect", retort: "貧嘴，快說你認不認同這數字。" },
      { id: "sangu-comparison-004-d", text: "差不多是真的，我們起薪都類似……", archetype: "meek", retort: "起薪類似，那以後呢？要拉開差距。" },
      { id: "sangu-comparison-004-e", text: "聽大家都在講，壓力真的滿大的……", archetype: "meek", retort: "壓力大就要努力，別被比下去。" },
      { id: "sangu-comparison-004-f", text: "數字而已，我的人生格局比較大啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-004-g", text: "薪水低，但我心靈富足，境界更高。", archetype: "backfire", retort: "……境界高，房租繳得出來嗎。" },
      { id: "sangu-comparison-004-h", text: "全桌都在傳我薪水，是不是太over了？", archetype: "landmine", retort: "（笑得更開）大家只是關心你。" },
    ],
  },
  {
    id: "sangu-comparison-005",
    text: "我們那年代大家條件差不多，現在你輸誰了？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-005-a", text: "沒輸誰，只是現在的賽道比較擁擠。", archetype: "perfect", retort: "……好，這句有見識，我認同。" },
      { id: "sangu-comparison-005-b", text: "那年代條件差不多，姑姑當年贏誰啊？", archetype: "deflect", retort: "我沒輸過，快說你的計畫。" },
      { id: "sangu-comparison-005-c", text: "厲害，姑姑那時候一定很努力。", archetype: "deflect", retort: "那當然，別光說嘴，快去努力。" },
      { id: "sangu-comparison-005-d", text: "現在競爭真的比以前激烈很多……", archetype: "meek", retort: "激烈也要拚，別找藉口放棄。" },
      { id: "sangu-comparison-005-e", text: "我也想追上去，只是速度真的比較慢……", archetype: "meek", retort: "速度慢就要更拚，年輕人加油。" },
      { id: "sangu-comparison-005-f", text: "那年代選項少，比較容易出頭啦。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-comparison-005-g", text: "現在講究的是軟實力，不是硬拚。", archetype: "backfire", retort: "……軟實力，軟到哪去了呢。" },
      { id: "sangu-comparison-005-h", text: "那年代選擇少，隨便比都比得贏吧。", archetype: "landmine", retort: "（笑意變冷）你在說我們不努力？" },
    ],
  },
  {
    id: "sangu-comparison-006",
    text: "你爸媽當年像你這年紀，早就成家立業了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-006-a", text: "所以我更該向他們看齊，慢慢努力。", archetype: "perfect", retort: "呵，這句有孝心，我服氣。" },
      { id: "sangu-comparison-006-b", text: "爸媽當年立業，是姑姑幫忙牽線嗎？", archetype: "deflect", retort: "少扯這個，快說你的想法。" },
      { id: "sangu-comparison-006-c", text: "那個年代房價，姑姑還記得嗎？", archetype: "deflect", retort: "記得，但別轉移話題。" },
      { id: "sangu-comparison-006-d", text: "現在的環境真的比當年難很多……", archetype: "meek", retort: "難也要拚，不能光說環境不好。" },
      { id: "sangu-comparison-006-e", text: "聽了心裡不太舒服，但也沒辦法反駁……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-comparison-006-f", text: "那年代結婚早，是因為選項少而已。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-comparison-006-g", text: "我這代講究品質婚姻，不急著成家。", archetype: "backfire", retort: "……品質婚姻，品質在哪呢？" },
      { id: "sangu-comparison-006-h", text: "那年代物價低，成家立業本來就容易。", archetype: "landmine", retort: "（笑意更冷）你在說我們不辛苦？" },
    ],
  },
  {
    id: "sangu-comparison-007",
    text: "鄰居的女兒，聽說要出國留學了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-007-a", text: "厲害，改天請她回來教教我英文。", archetype: "perfect", retort: "……好，這句大方又聰明。" },
      { id: "sangu-comparison-007-b", text: "留學費用，姑姑幫我打聽多少？", archetype: "deflect", retort: "很貴，快跟人家看齊努力。" },
      { id: "sangu-comparison-007-c", text: "出國留學，那紅包一定包很大吧？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-007-d", text: "她家條件比較好，我沒那個本錢……", archetype: "meek", retort: "沒本錢也要想辦法，別放棄。" },
      { id: "sangu-comparison-007-e", text: "每個人條件不同，但心裡難免比較……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-comparison-007-f", text: "留學而已，我心靈自由值千萬學位。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-comparison-007-g", text: "她一定是靠家裡，我這是白手起家。", archetype: "backfire", retort: "……白手起家，起到哪一步了？" },
      { id: "sangu-comparison-007-h", text: "她家的事，姑姑打聽得真清楚耶。", archetype: "landmine", retort: "（笑意更冷）我消息一向靈通。" },
    ],
  },
  {
    id: "sangu-comparison-008",
    text: "你弟弟現在都比你有成就了耶。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-008-a", text: "他有成就，是我這個哥哥教得好。", archetype: "perfect", retort: "呵，這句臉皮厚得可愛，我笑了。" },
      { id: "sangu-comparison-008-b", text: "姑姑覺得成就要怎麼定義比較公平？", archetype: "deflect", retort: "看收入跟穩定度，你自己想。" },
      { id: "sangu-comparison-008-c", text: "弟弟優秀，家族基因果然強大。", archetype: "deflect", retort: "貧嘴，說到底你自己怎樣。" },
      { id: "sangu-comparison-008-d", text: "他確實走得比較順，我還在摸索……", archetype: "meek", retort: "摸索太久，會被弟弟追過去喔。" },
      { id: "sangu-comparison-008-e", text: "聽了心裡有點不是滋味，但也沒辦法……", archetype: "meek", retort: "沒辦法就要想辦法，別認命。" },
      { id: "sangu-comparison-008-f", text: "他成就高，是靠我這個哥哥鋪路的。", archetype: "backfire", retort: "（三姑挑眉，弟弟在旁翻白眼）" },
      { id: "sangu-comparison-008-g", text: "我這叫大器晚成，等著看好戲吧。", archetype: "backfire", retort: "……晚成，晚到現在還沒成呢。" },
      { id: "sangu-comparison-008-h", text: "拿我跟弟弟比，是不是想挑撥我們？", archetype: "landmine", retort: "（笑意更冷）我只是關心進度而已。" },
    ],
  },
  {
    id: "sangu-comparison-009",
    text: "朋友的女兒嫁得好，你什麼時候輪到？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-009-a", text: "等我先把自己活成值得嫁的樣子。", archetype: "perfect", retort: "……好，這句有志氣，我認同。" },
      { id: "sangu-comparison-009-b", text: "她嫁得好，是您牽的線嗎姑姑？", archetype: "deflect", retort: "不是，快說你自己的打算。" },
      { id: "sangu-comparison-009-c", text: "嫁得好的定義，姑姑先說標準嘛。", archetype: "deflect", retort: "貧嘴，人品好家境好就是了。" },
      { id: "sangu-comparison-009-d", text: "還沒有對象，這個問題有點太快了……", archetype: "meek", retort: "太快？那你更要積極一點了。" },
      { id: "sangu-comparison-009-e", text: "聽了心裡有點著急，但真的急不來……", archetype: "meek", retort: "急不來也要有行動，不能空等。" },
      { id: "sangu-comparison-009-f", text: "嫁得好而已，我打算單身嫁給事業。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-comparison-009-g", text: "我這種人才，機會多到挑花眼啦。", archetype: "backfire", retort: "……挑花眼，那怎麼還沒挑到人。" },
      { id: "sangu-comparison-009-h", text: "拿人家嫁得好來比，很傷人耶姑姑。", archetype: "landmine", retort: "（笑意更冷）我只是舉個例子而已。" },
    ],
  },
  {
    id: "sangu-comparison-010",
    text: "你那個網紅朋友，最近又出國玩了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-010-a", text: "她曬的是生活，我留的是存款，各有選擇。", archetype: "perfect", retort: "呵，這句夠犀利，我服氣。" },
      { id: "sangu-comparison-010-b", text: "姑姑也有在追蹤她的帳號嗎？", archetype: "deflect", retort: "有，快說你怎麼看這件事。" },
      { id: "sangu-comparison-010-c", text: "她出國玩，紅包會不會分我一點？", archetype: "deflect", retort: "貧嘴，人家是靠自己賺的。" },
      { id: "sangu-comparison-010-d", text: "看她過得那麼精彩，難免有點羨慕……", archetype: "meek", retort: "羨慕就要化成行動，別只是滑手機。" },
      { id: "sangu-comparison-010-e", text: "每個人選擇不同，但心裡還是會比較……", archetype: "meek", retort: "會比較，就要想辦法追上去。" },
      { id: "sangu-comparison-010-f", text: "網紅曬照，都是包裝出來的假象啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-010-g", text: "我這叫低調富有，不需要曬給人看。", archetype: "backfire", retort: "……低調富有，存摺敢拿出來看嗎。" },
      { id: "sangu-comparison-010-h", text: "整天滑她的帳號，是不是姑姑也羨慕？", archetype: "landmine", retort: "（笑意更冷）我只是關心你而已。" },
    ],
  },
  {
    id: "sangu-comparison-011",
    text: "我朋友的孩子樣樣都好，你要不要學學？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-011-a", text: "學是要學，但我更想活出自己的樣子。", archetype: "perfect", retort: "……好，這句有骨氣，我服氣。" },
      { id: "sangu-comparison-011-b", text: "他樣樣都好，那有沒有樣樣都累啊？", archetype: "deflect", retort: "少貧嘴，快說你要怎麼進步。" },
      { id: "sangu-comparison-011-c", text: "他厲害，姑姑朋友教育有方啊。", archetype: "deflect", retort: "貧嘴，別光誇人，說自己。" },
      { id: "sangu-comparison-011-d", text: "聽了確實有點自愧不如……", archetype: "meek", retort: "自愧不如就要努力追上去，別認輸。" },
      { id: "sangu-comparison-011-e", text: "每個人擅長不同，但也會忍不住比較……", archetype: "meek", retort: "忍不住比較，就要化成動力啊。" },
      { id: "sangu-comparison-011-f", text: "樣樣都好，聽起來就很累人啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-011-g", text: "我這叫術業有專攻，不用樣樣都行。", archetype: "backfire", retort: "……術業有專攻，攻在哪呢？" },
      { id: "sangu-comparison-011-h", text: "拿別人家孩子比較，很無聊耶姑姑。", archetype: "landmine", retort: "（笑意更冷）我只是舉個例子而已。" },
    ],
  },
  {
    id: "sangu-comparison-012",
    text: "今天大家都輸給你嘴，就看我能不能贏。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-012-a", text: "姑姑是總教頭，我今天就等您出招。", archetype: "perfect", retort: "……好，有種，這才是我的姪子。" },
      { id: "sangu-comparison-012-b", text: "聽說您這關才是真正的大魔王？", archetype: "deflect", retort: "算你識貨，準備好了嗎。" },
      { id: "sangu-comparison-012-c", text: "先讓我喘口氣，您慢慢來沒關係。", archetype: "deflect", retort: "慢慢來也躲不掉，準備好吧。" },
      { id: "sangu-comparison-012-d", text: "說實話，我今天有點招架不住了……", archetype: "meek", retort: "招架不住？那更要打起精神。" },
      { id: "sangu-comparison-012-e", text: "大家都問過一輪，我真的有點累了……", archetype: "meek", retort: "累也要撐住，這才是最後一關。" },
      { id: "sangu-comparison-012-f", text: "姑姑您年紀大了，嘴皮子可能練不過我。", archetype: "backfire", retort: "（三姑笑意收了，眼神一冷）" },
      { id: "sangu-comparison-012-g", text: "我今天是故意留手，怕您受不了。", archetype: "backfire", retort: "……留手，那你倒是show一個看看。" },
      { id: "sangu-comparison-012-h", text: "整場都在算計我，是不是早就套好招？", archetype: "landmine", retort: "（笑得更開）算你聰明，看出來了。" },
    ],
  },
  {
    id: "sangu-comparison-013",
    text: "你跟去年比，怎麼感覺退步了？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-013-a", text: "退步是假象，我在蹲下準備跳更高。", archetype: "perfect", retort: "呵，這句有智慧，我服氣。" },
      { id: "sangu-comparison-013-b", text: "姑姑覺得退步的標準是什麼啊？", archetype: "deflect", retort: "看你精神跟氣色，都不如以前。" },
      { id: "sangu-comparison-013-c", text: "退步一點，才顯得您進步得快。", archetype: "deflect", retort: "貧嘴，快說到底怎麼了。" },
      { id: "sangu-comparison-013-d", text: "最近確實比較沒精神，狀態不太好……", archetype: "meek", retort: "狀態不好要調整，別放任下去。" },
      { id: "sangu-comparison-013-e", text: "去年那時候比較拚，今年是有點鬆懈……", archetype: "meek", retort: "鬆懈就要收心，別再拖延了。" },
      { id: "sangu-comparison-013-f", text: "退步是因為我在沉澱，這叫戰略。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-013-g", text: "退步只是表面，內在其實突飛猛進。", archetype: "backfire", retort: "……突飛猛進，猛進到哪去了？" },
      { id: "sangu-comparison-013-h", text: "去年您也這樣講，是不是每年都嫌？", archetype: "landmine", retort: "（笑意更冷）我是每年都在觀察。" },
    ],
  },
  {
    id: "sangu-comparison-014",
    text: "堂哥去年考上律師，你聽了什麼感覺？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-014-a", text: "很替他驕傲，以後打官司找他就好。", archetype: "perfect", retort: "……好，這句有格局，我服氣。" },
      { id: "sangu-comparison-014-b", text: "他考上律師，姑姑要不要先諮詢一下？", archetype: "deflect", retort: "貧嘴，快說你自己的感覺。" },
      { id: "sangu-comparison-014-c", text: "考上律師，那紅包會不會包大一點？", archetype: "deflect", retort: "少扯這個，正經回答我。" },
      { id: "sangu-comparison-014-d", text: "聽了確實有點壓力，覺得自己落後了……", archetype: "meek", retort: "落後就要追，別只是感嘆。" },
      { id: "sangu-comparison-014-e", text: "替他開心，但心裡也難免比較一下……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-comparison-014-f", text: "律師而已，我未來是要當立法委員。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-014-g", text: "他考律師靠補習，我靠自學比較強。", archetype: "backfire", retort: "……自學比較強，強到哪去了？" },
      { id: "sangu-comparison-014-h", text: "堂哥考律師，姑姑消息真是靈通耶。", archetype: "landmine", retort: "（笑意更冷）我消息一向靈通。" },
    ],
  },
  {
    id: "sangu-comparison-015",
    text: "我當年像你這歲數，早就闖出一片天了。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-015-a", text: "所以我這關才排最後，跟您學著點。", archetype: "perfect", retort: "呵，這句真會講，有我當年樣子。" },
      { id: "sangu-comparison-015-b", text: "姑姑當年闖出的那片天，長什麼樣？", archetype: "deflect", retort: "又大又亮，快跟我多學學。" },
      { id: "sangu-comparison-015-c", text: "闖天下之前，姑姑先教我幾招吧。", archetype: "deflect", retort: "貧嘴，先靠自己努力再說。" },
      { id: "sangu-comparison-015-d", text: "現在的環境真的比當年競爭激烈很多……", archetype: "meek", retort: "激烈也要拚，別找藉口放棄。" },
      { id: "sangu-comparison-015-e", text: "聽了心裡不太舒服，但也沒辦法反駁……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-comparison-015-f", text: "那年代選項少，隨便闖都算闖出來。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-comparison-015-g", text: "我這代講究慢活，不急著闖天下。", archetype: "backfire", retort: "……慢活，慢到現在還沒個影。" },
      { id: "sangu-comparison-015-h", text: "那年代選擇少，隨便闖都比較容易吧。", archetype: "landmine", retort: "（笑意變冷）你在說我們不辛苦？" },
    ],
  },
  {
    id: "sangu-comparison-016",
    text: "人家小孩學鋼琴又學畫畫，樣樣精通。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-016-a", text: "我小時候學的是看您臉色，也是一技之長。", archetype: "perfect", retort: "呵呵，這句夠壞，我笑了，記下了。" },
      { id: "sangu-comparison-016-b", text: "他學那麼多才藝，補習費多少啊？", archetype: "deflect", retort: "很多，快跟人家看齊努力。" },
      { id: "sangu-comparison-016-c", text: "樣樣精通，那紅包一定包很大吧？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-016-d", text: "我小時候沒機會學那些，有點羨慕……", archetype: "meek", retort: "羨慕就要現在補回來啊。" },
      { id: "sangu-comparison-016-e", text: "每個人成長環境不同，但也會比較……", archetype: "meek", retort: "會比較，就要化成動力啊。" },
      { id: "sangu-comparison-016-f", text: "才藝多沒用，我這叫大智若愚。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-016-g", text: "我小時候學的是人生哲學，比較深奧。", archetype: "backfire", retort: "……人生哲學，學到什麼結論了？" },
      { id: "sangu-comparison-016-h", text: "拿別人家小孩比較，很無聊耶姑姑。", archetype: "landmine", retort: "（笑意更冷）我只是舉個例子而已。" },
    ],
  },
  {
    id: "sangu-comparison-017",
    text: "隔壁老王的小孩，暑假還去實習賺錢。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-017-a", text: "厲害，改天請他教教我怎麼投履歷。", archetype: "perfect", retort: "……好，這句大方又聰明。" },
      { id: "sangu-comparison-017-b", text: "他實習哪間公司，姑姑幫我打聽？", archetype: "deflect", retort: "去查了就知道，快跟人學學。" },
      { id: "sangu-comparison-017-c", text: "暑假實習，那紅包會不會包大一點？", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-comparison-017-d", text: "我學生時代忙著打工顧生活，沒空實習……", archetype: "meek", retort: "沒空？那你現在更要補上。" },
      { id: "sangu-comparison-017-e", text: "聽了心裡有點慚愧，覺得自己起步晚了……", archetype: "meek", retort: "起步晚就要跑快一點，別認輸。" },
      { id: "sangu-comparison-017-f", text: "實習而已，我大學時就已經在創業了。", archetype: "backfire", retort: "（三姑笑笑，沒人相信這說法）" },
      { id: "sangu-comparison-017-g", text: "他家有資源才實習得到，不能比。", archetype: "backfire", retort: "……不能比，那你現在做了什麼？" },
      { id: "sangu-comparison-017-h", text: "老王家的事，姑姑打聽得真清楚耶。", archetype: "landmine", retort: "（笑意更冷）我消息一向靈通。" },
    ],
  },
  {
    id: "sangu-comparison-018",
    text: "今天聚餐大家都在比，你有什麼可以說嘴？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-018-a", text: "我今天全場沒被問倒，這就是本事。", archetype: "perfect", retort: "……呵，有種，這句我服了。" },
      { id: "sangu-comparison-018-b", text: "姑姑最想聽哪方面的說嘴內容？", archetype: "deflect", retort: "隨便，你倒是說一個來聽聽。" },
      { id: "sangu-comparison-018-c", text: "我最值得說嘴的，就是有您這樣的姑姑。", archetype: "deflect", retort: "貧嘴，快說點實質的東西。" },
      { id: "sangu-comparison-018-d", text: "說實話，一時之間我還真想不出來……", archetype: "meek", retort: "想不出來？那你要好好反省了。" },
      { id: "sangu-comparison-018-e", text: "沒什麼特別的，就是平凡過日子而已……", archetype: "meek", retort: "平凡不是壞事，但也該有點目標。" },
      { id: "sangu-comparison-018-f", text: "我最值得說嘴的，就是我很會說嘴。", archetype: "backfire", retort: "（三姑無語，全桌安靜）" },
      { id: "sangu-comparison-018-g", text: "我的成就都是內在的，看不出來啦。", archetype: "backfire", retort: "……看不出來，那怎麼證明有？" },
      { id: "sangu-comparison-018-h", text: "一直逼人說嘴，很無聊耶這種聚餐。", archetype: "landmine", retort: "（笑意更冷）大家只是圖個熱鬧。" },
    ],
  },
  {
    id: "sangu-comparison-019",
    text: "你同期進公司的同事，都升主管了吧？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-019-a", text: "他們升主管，我先升級成抗壓高手。", archetype: "perfect", retort: "呵，這句自嘲得漂亮，我服氣。" },
      { id: "sangu-comparison-019-b", text: "他們升主管，是不是加班比較多啊？", archetype: "deflect", retort: "少貧嘴，快說你自己的進度。" },
      { id: "sangu-comparison-019-c", text: "他們升主管，紅包會不會包大一點？", archetype: "deflect", retort: "貧嘴，快說你怎麼想這件事。" },
      { id: "sangu-comparison-019-d", text: "確實，有幾個同期的已經升上去了……", archetype: "meek", retort: "升上去了？那你更該加緊努力了。" },
      { id: "sangu-comparison-019-e", text: "聽了難免有點壓力，但也替他們開心……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-comparison-019-f", text: "主管而已，我未來是要當創辦人的。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-comparison-019-g", text: "他們升遷靠關係，我靠實力慢慢來。", archetype: "backfire", retort: "……實力慢慢來，慢了幾年了。" },
      { id: "sangu-comparison-019-h", text: "問這個是不是想拿去跟表哥比較？", archetype: "landmine", retort: "（笑意更冷）表哥的事不用你操心。" },
    ],
  },
  {
    id: "sangu-comparison-020",
    text: "你朋友都買車了，你怎麼還在騎機車？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-020-a", text: "機車省油又環保，是我精算過的選擇。", archetype: "perfect", retort: "……好，這句夠有理財觀念。" },
      { id: "sangu-comparison-020-b", text: "姑姑覺得先買車還是先買房比較好？", archetype: "deflect", retort: "當然先買房，別本末倒置。" },
      { id: "sangu-comparison-020-c", text: "騎機車，才能常常繞去看姑姑。", archetype: "deflect", retort: "貧嘴，快說你的存錢計畫。" },
      { id: "sangu-comparison-020-d", text: "存款真的還不夠買車，只能先騎機車……", archetype: "meek", retort: "不夠就要存，別羨慕別人。" },
      { id: "sangu-comparison-020-e", text: "看朋友一個個買車，心裡難免有點急……", archetype: "meek", retort: "急就要行動，光急沒有用。" },
      { id: "sangu-comparison-020-f", text: "騎機車比較潮，這叫街頭風格啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-comparison-020-g", text: "我不買車，是為了減少碳排放救地球。", archetype: "backfire", retort: "……救地球，那你多久沒存錢了。" },
      { id: "sangu-comparison-020-h", text: "騎機車有什麼不好，管那麼多幹嘛。", archetype: "landmine", retort: "（笑得更開）姑姑只是隨口問問。" },
    ],
  },
  {
    id: "sangu-comparison-021",
    text: "表姊、三舅媽、阿嬤今天問的，姑姑都聽說了，一起算算總帳吧。",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-021-a", text: "算總帳可以，但今年我打算全部翻本。", archetype: "perfect", retort: "……好，有膽識，有我當年的樣子。" },
      { id: "sangu-comparison-021-b", text: "這桌是不是有個家族情報交換群組啊？", archetype: "deflect", retort: "算你聰明，快接受總評比吧。" },
      { id: "sangu-comparison-021-c", text: "算總帳前，先讓我喘口氣吃塊肉。", archetype: "deflect", retort: "吃完就要面對，躲不掉的。" },
      { id: "sangu-comparison-021-d", text: "今天被問了一整輪，真的有點招架不住……", archetype: "meek", retort: "招架不住？那更要打起精神應戰。" },
      { id: "sangu-comparison-021-e", text: "每個問題都戳中痛處，心裡壓力很大……", archetype: "meek", retort: "壓力大就要正面迎戰，別逃避。" },
      { id: "sangu-comparison-021-f", text: "總帳？我今天全勝，沒什麼好算的。", archetype: "backfire", retort: "（三姑笑意收了，眼神一冷）" },
      { id: "sangu-comparison-021-g", text: "我早就把答案都準備好了，不怕算。", archetype: "backfire", retort: "……準備好了？那怎麼還在流汗。" },
      { id: "sangu-comparison-021-h", text: "整個家族都在監控我，會不會太誇張？", archetype: "landmine", retort: "（笑得更開）我們是關心，不是監控。" },
    ],
  },
  {
    id: "sangu-comparison-022",
    text: "我認識更優秀的人，要不要介紹你認識？",
    topic: "comparison",
    bossId: "sangu",
    options: [
      { id: "sangu-comparison-022-a", text: "好啊，跟優秀的人相處，我才會進步。", archetype: "perfect", retort: "呵，這心態夠格，有我年輕的樣子。" },
      { id: "sangu-comparison-022-b", text: "優秀到什麼程度，姑姑先透露一點？", archetype: "deflect", retort: "見面就知道，別問那麼細。" },
      { id: "sangu-comparison-022-c", text: "介紹可以，但姑姑要負責到底喔。", archetype: "deflect", retort: "當然，我看人一向很準。" },
      { id: "sangu-comparison-022-d", text: "好是好，但我怕被比下去更沒自信……", archetype: "meek", retort: "沒自信就要練，別逃避挑戰。" },
      { id: "sangu-comparison-022-e", text: "可以試試看，只是有點緊張……", archetype: "meek", retort: "緊張什麼，認識而已，別想太多。" },
      { id: "sangu-comparison-022-f", text: "優秀的人，通常都眼光更高，我怕怕。", archetype: "backfire", retort: "（三姑笑笑，沒人接話）" },
      { id: "sangu-comparison-022-g", text: "我自己就是那個優秀的人，不用介紹。", archetype: "backfire", retort: "……不用介紹，那你倒是拿出成績。" },
      { id: "sangu-comparison-022-h", text: "又要拿別人激勵我，是不是嫌我不夠好？", archetype: "landmine", retort: "（笑意更甜）姑姑是疼你才安排。" },
    ],
  },
] satisfies Question[];
