import type { Question } from "@/content/types";

// situations: 直接問買房了沒／說要介紹她朋友的房子帶親戚價陷阱／問租屋處位置跟租金／
// cross-ref三舅媽說你還在租房／講她那年代隨便存都買得起房／問頭期款跟爸媽有沒有幫忙／
// 說要借頭期款帶條件／問是不是打算租一輩子／說朋友孩子買第二間房／問租屋處方不方便回家／
// 說要介紹她做房仲的朋友／問有沒有考慮跟對象一起買房／說年輕人不吃苦才買不起房／
// cross-ref陳太太說看到你搬新家／問租屋處是不是很小很偏／說要把老家房子過戶給你帶條件／
// 問室友是誰暗示八卦／說應該先買房再談別的／問貸款利率會不會算／說要陪你去看房順便介紹對象／
// cross-ref阿嬤問租的房子安不安全／說老家透天房間多要你搬回去住
export default [
  {
    id: "sangu-housing-001",
    text: "存款夠了嗎？什麼時候要買房子？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-001-a", text: "等我买房，先問您那間何時要過戶。", archetype: "perfect", retort: "……好準，這句我認了。" },
      { id: "sangu-housing-001-b", text: "姑姑先教我，怎麼跟房仲殺價？", archetype: "deflect", retort: "少扯這個，先存夠錢再說。" },
      { id: "sangu-housing-001-c", text: "買房前，先讓我把姑姑家蹭熟一點。", archetype: "deflect", retort: "貧嘴，快說有沒有存錢計畫。" },
      { id: "sangu-housing-001-d", text: "還差很多，頭期款真的存不到……", archetype: "meek", retort: "存不到？那你要怎麼在這站穩腳？" },
      { id: "sangu-housing-001-e", text: "有在存，但速度真的追不上房價……", archetype: "meek", retort: "追不上就要更省，別亂花錢。" },
      { id: "sangu-housing-001-f", text: "我打算租一輩子，房東比較好聊。", archetype: "backfire", retort: "（三姑不笑，喝了口茶）" },
      { id: "sangu-housing-001-g", text: "買房是舊觀念，我這代崇尚流浪。", archetype: "backfire", retort: "……流浪到幾歲，你自己想過嗎。" },
      { id: "sangu-housing-001-h", text: "買房前，先問您跟媳婦搶房產搶得如何。", archetype: "landmine", retort: "（筷子一放）你媽這樣教你的？" },
    ],
  },
  {
    id: "sangu-housing-002",
    text: "我朋友那間三房，親戚價算你便宜。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-002-a", text: "親戚價我收，但合約我自己看，學您精。", archetype: "perfect", retort: "……這句我認了，算你機靈。" },
      { id: "sangu-housing-002-b", text: "親戚價，是打幾折的親戚價啊？", archetype: "deflect", retort: "去看了就知道，別問那麼多。" },
      { id: "sangu-housing-002-c", text: "姑姑推薦的，我當然要去捧場一下。", archetype: "deflect", retort: "少討好我，先看實際條件。" },
      { id: "sangu-housing-002-d", text: "聽起來不錯，但頭期款我還沒著落……", archetype: "meek", retort: "沒著落，這麼好的機會就浪費了。" },
      { id: "sangu-housing-002-e", text: "可以去看看，只是我還沒心理準備……", archetype: "meek", retort: "心理準備要建多久，機會不等人。" },
      { id: "sangu-housing-002-f", text: "親戚價聽起來，跟親戚借錢差不多意思。", archetype: "backfire", retort: "（三姑臉一沉，氣氛僵了）" },
      { id: "sangu-housing-002-g", text: "我這種人才，房子自然會來找我。", archetype: "backfire", retort: "……房子還沒來，你倒是很篤定。" },
      { id: "sangu-housing-002-h", text: "親戚價，該不會是想拉您女兒回來住？", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-housing-003",
    text: "你現在租哪？一個月多少錢？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-003-a", text: "租金不重要，重要是您紅包夠不夠付。", archetype: "perfect", retort: "呵，這句夠狠，我服氣。" },
      { id: "sangu-housing-003-b", text: "姑姑當年租房子，一個月才多少？", archetype: "deflect", retort: "幾百塊而已，別扯這個。" },
      { id: "sangu-housing-003-c", text: "租金不重要，重要是離您家近不近。", archetype: "deflect", retort: "貧嘴，快說多少錢一個月。" },
      { id: "sangu-housing-003-d", text: "一萬多，扣一扣薪水沒剩多少……", archetype: "meek", retort: "一萬多？那存款怎麼存得下來？" },
      { id: "sangu-housing-003-e", text: "有點貴，但地點方便就將就了……", archetype: "meek", retort: "將就久了，錢都給房東賺去了。" },
      { id: "sangu-housing-003-f", text: "租金是機密，姑姑您不用擔心。", archetype: "backfire", retort: "（三姑挑眉，沒人相信這說法）" },
      { id: "sangu-housing-003-g", text: "我房東人很好，租金已經算佛心了。", archetype: "backfire", retort: "……佛心，那你怎麼還在租呢。" },
      { id: "sangu-housing-003-h", text: "問租金，不如問您跟媳婦誰付孝親費多。", archetype: "landmine", retort: "（放下碗）這話你會後悔。" },
    ],
  },
  {
    id: "sangu-housing-004",
    text: "三舅媽說你到現在還在租房子喔。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-004-a", text: "還在租，總比租不到您女兒消息強。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-housing-004-b", text: "三舅媽的情報網，連租屋處都查？", archetype: "deflect", retort: "她關心你，別這樣說人家。" },
      { id: "sangu-housing-004-c", text: "還在租，是因為在等姑姑的親戚價。", archetype: "deflect", retort: "貧嘴，快說什麼時候要買。" },
      { id: "sangu-housing-004-d", text: "是真的，頭期款一直存不夠……", archetype: "meek", retort: "存不夠？那你更該加緊腳步了。" },
      { id: "sangu-housing-004-e", text: "房價太高，光靠薪水真的買不起……", archetype: "meek", retort: "買不起也要有目標，別放棄。" },
      { id: "sangu-housing-004-f", text: "租房才是新時代的資產配置，懂嗎。", archetype: "backfire", retort: "（三姑無語，喝了口湯）" },
      { id: "sangu-housing-004-g", text: "我在等房價崩盤，時機還沒到而已。", archetype: "backfire", retort: "……等了幾年了，崩了嗎？" },
      { id: "sangu-housing-004-h", text: "三舅媽算房子，怎麼不算您跟媳婦多久沒說話。", archetype: "landmine", retort: "（臉色鐵青）你給我記住這句。" },
    ],
  },
  {
    id: "sangu-housing-005",
    text: "我們那年代，隨便存都存得起一間房。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-005-a", text: "所以我更佩服您，換問您當年怎麼嫁的。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-housing-005-b", text: "那年代一坪多少錢，姑姑還記得嗎？", archetype: "deflect", retort: "幾萬塊而已，別扯這個。" },
      { id: "sangu-housing-005-c", text: "厲害，姑姑那時候一定很拚。", archetype: "deflect", retort: "那當然，別光說嘴，去努力。" },
      { id: "sangu-housing-005-d", text: "現在房價跟薪水真的差太多了……", archetype: "meek", retort: "差很多也要想辦法，別放棄。" },
      { id: "sangu-housing-005-e", text: "我也想存，但存款速度追不上房價……", archetype: "meek", retort: "追不上就要更拚，年輕人。" },
      { id: "sangu-housing-005-f", text: "那年代物價低，比較沒有可比性啦。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-housing-005-g", text: "現在買房要靠投資，不是靠存錢。", archetype: "backfire", retort: "……那你投資到現在，買了嗎。" },
      { id: "sangu-housing-005-h", text: "隨便存都買房，那年代嫁人也隨便嗎？", archetype: "landmine", retort: "（臉色一沉）你這什麼態度！" },
    ],
  },
  {
    id: "sangu-housing-006",
    text: "頭期款準備了嗎？爸媽有幫忙嗎？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-006-a", text: "自己存的，這樣才不欠您人情，像您教的。", archetype: "perfect", retort: "……乖，這句我認了。" },
      { id: "sangu-housing-006-b", text: "姑姑當年買房，是自己存還是借的？", archetype: "deflect", retort: "自己存的，快說你的進度。" },
      { id: "sangu-housing-006-c", text: "爸媽有幫忙的話，第一個要謝的是姑姑。", archetype: "deflect", retort: "貧嘴，先說有沒有存到。" },
      { id: "sangu-housing-006-d", text: "還在存，爸媽也沒有多餘的能幫……", archetype: "meek", retort: "沒人幫，那你要更省點花。" },
      { id: "sangu-housing-006-e", text: "有一點積蓄，但離目標還差一大截……", archetype: "meek", retort: "差一大截，是不是花錢太隨性？" },
      { id: "sangu-housing-006-f", text: "頭期款的事，我自有神秘管道。", archetype: "backfire", retort: "（三姑挑眉，沒人相信這說法）" },
      { id: "sangu-housing-006-g", text: "我打算用信用卡分期買，很聰明吧。", archetype: "backfire", retort: "……聰明，銀行最喜歡這種聰明人。" },
      { id: "sangu-housing-006-h", text: "問我爸媽幫不幫，先問您跟媳婦誰幫誰多。", archetype: "landmine", retort: "（冷眼）這桌，你今天別坐了。" },
    ],
  },
  {
    id: "sangu-housing-007",
    text: "頭期款不夠，姑姑先借你，年底還。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-007-a", text: "謝謝姑姑，但我不想跟您媳婦一樣欠人情。", archetype: "perfect", retort: "……好，這句我認了。" },
      { id: "sangu-housing-007-b", text: "借款的利息，姑姑打算怎麼算啊？", archetype: "deflect", retort: "少貧嘴，我是真心幫你的。" },
      { id: "sangu-housing-007-c", text: "先謝謝姑姑的心意，我再考慮考慮。", archetype: "deflect", retort: "考慮什麼，機會難得知道嗎。" },
      { id: "sangu-housing-007-d", text: "如果真的借，我怕年底真的還不出來……", archetype: "meek", retort: "還不出來？那你更該量力而為。" },
      { id: "sangu-housing-007-e", text: "有點心動，但欠人情感覺壓力很大……", archetype: "meek", retort: "壓力大也要衡量，別衝動決定。" },
      { id: "sangu-housing-007-f", text: "借錢的事，我看緣分，隨緣就好。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-housing-007-g", text: "我這種人才，銀行搶著要借我錢啦。", archetype: "backfire", retort: "……搶著借，那你怎麼還缺頭期款。" },
      { id: "sangu-housing-007-h", text: "借錢？先問問您紅包是不是全場最小包。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-housing-008",
    text: "你是不是打算租一輩子房子啊？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-008-a", text: "租到我想清楚，總比您嫁得急想得清楚。", archetype: "perfect", retort: "呵，這句夠毒，算你贏。" },
      { id: "sangu-housing-008-b", text: "姑姑覺得租一輩子有什麼不好嗎？", archetype: "deflect", retort: "沒有根，心裡不踏實啊。" },
      { id: "sangu-housing-008-c", text: "租一輩子的錢，夠買姑姑家幾間廚房。", archetype: "deflect", retort: "貧嘴，快說有沒有存錢計畫。" },
      { id: "sangu-housing-008-d", text: "說實話，我也不知道自己在等什麼……", archetype: "meek", retort: "不知道在等，就是沒有目標啊。" },
      { id: "sangu-housing-008-e", text: "看現況真的有點像會租一輩子……", archetype: "meek", retort: "有點像？那你要趕快改變啊。" },
      { id: "sangu-housing-008-f", text: "租房是自由，我不想被房貸綁死。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-housing-008-g", text: "租一輩子，才能天天換新環境嘗鮮。", archetype: "backfire", retort: "……嘗鮮，錢包倒是很有經驗。" },
      { id: "sangu-housing-008-h", text: "租一輩子關您什麼事，問問您女兒何時回。", archetype: "landmine", retort: "（笑容不見）明年不用來了。" },
    ],
  },
  {
    id: "sangu-housing-009",
    text: "我朋友的女兒，已經買第二間房了。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-009-a", text: "厲害，改天問問她怎麼跟婆婆處得好。", archetype: "perfect", retort: "……這句我服了。" },
      { id: "sangu-housing-009-b", text: "她做什麼工作，姑姑幫我打聽一下？", archetype: "deflect", retort: "金融業，聽說壓力也很大。" },
      { id: "sangu-housing-009-c", text: "第二間房，那她第一間要不要租我？", archetype: "deflect", retort: "貧嘴，快跟人家看齊努力。" },
      { id: "sangu-housing-009-d", text: "差人家一大截，聽了有點洩氣……", archetype: "meek", retort: "洩氣沒用，要想辦法追上去。" },
      { id: "sangu-housing-009-e", text: "條件真的不一樣，但還是會比較……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-housing-009-f", text: "兩間房而已，我心靈自由值千萬棟。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-housing-009-g", text: "她背後一定有靠山，我是自己拚。", archetype: "backfire", retort: "……白手起家，起到哪一步了？" },
      { id: "sangu-housing-009-h", text: "買第二間房，總比您跟媳婦處不好強。", archetype: "landmine", retort: "（沉聲）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-housing-010",
    text: "你租的地方，過年方不方便回來？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-010-a", text: "再遠也方便，至少我年年都回，不像有人。", archetype: "perfect", retort: "……好，這句聽了讓人心軟。" },
      { id: "sangu-housing-010-b", text: "姑姑家永遠是我的第一站，很方便。", archetype: "deflect", retort: "貧嘴，快說租的地方在哪。" },
      { id: "sangu-housing-010-c", text: "方便啊，坐車聽您的叮嚀都不會膩。", archetype: "deflect", retort: "少討好我，快說實際距離。" },
      { id: "sangu-housing-010-d", text: "有點遠，塞車的話要三個多小時……", archetype: "meek", retort: "三個小時？那你更該搬近一點。" },
      { id: "sangu-housing-010-e", text: "還好，但每次回來都覺得好累……", archetype: "meek", retort: "累就要想辦法，別總是硬撐。" },
      { id: "sangu-housing-010-f", text: "遠是遠，但我有導航，不會迷路。", archetype: "backfire", retort: "（三姑笑笑，沒接這個梗）" },
      { id: "sangu-housing-010-g", text: "距離不是問題，心的距離才是重點。", archetype: "backfire", retort: "……心的距離，你今年初二才到。" },
      { id: "sangu-housing-010-h", text: "方不方便，先問您女兒過年方不方便回。", archetype: "landmine", retort: "（全桌安靜）你剛剛說什麼？" },
    ],
  },
  {
    id: "sangu-housing-011",
    text: "我朋友是房仲，介紹給你認識一下？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-011-a", text: "好啊，能被您推薦，一定比介紹對象準。", archetype: "perfect", retort: "……好，會做人，隨我年輕時。" },
      { id: "sangu-housing-011-b", text: "他手上的物件，有沒有比較便宜的？", archetype: "deflect", retort: "去了就知道，別討價還價。" },
      { id: "sangu-housing-011-c", text: "介紹可以，但要先確認他不會坑我。", archetype: "deflect", retort: "放心，我朋友都很實在。" },
      { id: "sangu-housing-011-d", text: "可以認識，但我現在真的還買不起……", archetype: "meek", retort: "買不起也要先認識，早晚用得到。" },
      { id: "sangu-housing-011-e", text: "好啊，只是我怕自己還沒準備好……", archetype: "meek", retort: "準備好之前，先聽聽也沒差。" },
      { id: "sangu-housing-011-f", text: "房仲而已，我自己上網爬文就懂。", archetype: "backfire", retort: "（三姑笑笑，沒人相信這說法）" },
      { id: "sangu-housing-011-g", text: "我這種人才，房仲應該來找我合作。", archetype: "backfire", retort: "……合作？你連頭期款都沒有。" },
      { id: "sangu-housing-011-h", text: "介紹房仲，不如介紹您跟媳婦和解的方法。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-housing-012",
    text: "有沒有考慮跟對象一起存錢買房？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-012-a", text: "有考慮，但我對象比較不會被人嫌。", archetype: "perfect", retort: "……好準，這句我認了。" },
      { id: "sangu-housing-012-b", text: "姑姑覺得買房前該不該先結婚啊？", archetype: "deflect", retort: "順序看你，但都要快點決定。" },
      { id: "sangu-housing-012-c", text: "等有對象了，第一個報告的就是您。", archetype: "deflect", retort: "貧嘴，快說目前有沒有目標。" },
      { id: "sangu-housing-012-d", text: "說實話，我現在連對象都還沒有……", archetype: "meek", retort: "沒對象？那你更該積極一點了。" },
      { id: "sangu-housing-012-e", text: "有想過，但兩人的財務觀念還沒聊過……", archetype: "meek", retort: "沒聊過就要趕快聊，別拖著。" },
      { id: "sangu-housing-012-f", text: "跟對象買房太危險，我單身比較安全。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-housing-012-g", text: "我打算自己買，不跟別人分權狀。", archetype: "backfire", retort: "……分權狀之前，先分得到房子嗎。" },
      { id: "sangu-housing-012-h", text: "買房前，先問您女兒婚姻穩不穩。", archetype: "landmine", retort: "（筷子一放）你這什麼話！" },
    ],
  },
  {
    id: "sangu-housing-013",
    text: "現在年輕人不吃苦，才買不起房啦。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-013-a", text: "吃苦不同，至少我沒吃過您那年代倉促嫁人的苦。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-housing-013-b", text: "姑姑覺得，吃苦的定義是什麼？", archetype: "deflect", retort: "省吃儉用，不亂花錢就是了。" },
      { id: "sangu-housing-013-c", text: "我吃的苦，都變成臉上的痘痘了。", archetype: "deflect", retort: "貧嘴，快說有沒有在存錢。" },
      { id: "sangu-housing-013-d", text: "確實，我可能是花錢比較不節制……", archetype: "meek", retort: "不節制就要改，不能只是承認。" },
      { id: "sangu-housing-013-e", text: "心裡不太舒服，但一時想不到怎麼回……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-housing-013-f", text: "不吃苦是因為我這代比較有智慧啦。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-housing-013-g", text: "房價高不是我的錯，是大環境的問題。", archetype: "backfire", retort: "……大環境，那你的努力去哪了。" },
      { id: "sangu-housing-013-h", text: "現在房價幾倍高，別拿您那年代嫁人比。", archetype: "landmine", retort: "（臉色一沉）你這是找罵？" },
    ],
  },
  {
    id: "sangu-housing-014",
    text: "陳太太說看到你搬新家了，恭喜啊。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-014-a", text: "是租的，但至少我每年都回來給您看。", archetype: "perfect", retort: "……好，這句聽了讓人心軟。" },
      { id: "sangu-housing-014-b", text: "陳太太連我搬家都知道，太神了吧。", archetype: "deflect", retort: "她關心你，別這樣說人家。" },
      { id: "sangu-housing-014-c", text: "搬新家的紅包，姑姑要不要補一個？", archetype: "deflect", retort: "貧嘴，先說是租的還是買的。" },
      { id: "sangu-housing-014-d", text: "是租的啦，還沒到買房那個階段……", archetype: "meek", retort: "租的？那你要早點朝目標努力。" },
      { id: "sangu-housing-014-e", text: "只是搬到便宜一點的地方而已……", archetype: "meek", retort: "便宜的地方，環境好不好啊？" },
      { id: "sangu-housing-014-f", text: "新家而已，跟買房完全是兩回事啦。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-housing-014-g", text: "搬家次數多，代表我生活很豐富。", archetype: "backfire", retort: "……豐富到都沒有一個定點啊。" },
      { id: "sangu-housing-014-h", text: "陳太太消息真快，怎麼不提您跟媳婦的事？", archetype: "landmine", retort: "（冷眼）這桌，你今天別坐了。" },
    ],
  },
  {
    id: "sangu-housing-015",
    text: "你租的地方，是不是又小又偏啊？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-015-a", text: "小是小，但夠讓我耳根清淨過一年。", archetype: "perfect", retort: "呵，這句夠壞，我笑了。" },
      { id: "sangu-housing-015-b", text: "姑姑覺得多大才算不小啊？", archetype: "deflect", retort: "至少要有客廳吧，別將就。" },
      { id: "sangu-housing-015-c", text: "小歸小，但離公司近，很划算。", archetype: "deflect", retort: "貧嘴，快說有多小多偏。" },
      { id: "sangu-housing-015-d", text: "是滿小的，走路十分鐘才到捷運站……", archetype: "meek", retort: "十分鐘？那你要考慮換一間了。" },
      { id: "sangu-housing-015-e", text: "有點偏，但租金真的比較便宜……", archetype: "meek", retort: "便宜歸便宜，安全要顧啊。" },
      { id: "sangu-housing-015-f", text: "小空間才有極簡生活的美學啦。", archetype: "backfire", retort: "（三姑挑眉，沒人相信這說法）" },
      { id: "sangu-housing-015-g", text: "偏遠一點才安靜，適合修行養性。", archetype: "backfire", retort: "……修行到現在，修出什麼了？" },
      { id: "sangu-housing-015-h", text: "又小又偏，總比您這年就今天有存在感好。", archetype: "landmine", retort: "（沉默三秒）你說完了？" },
    ],
  },
  {
    id: "sangu-housing-016",
    text: "老家那間空房，過戶給你，你要嗎？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-016-a", text: "要，但條件先講清楚，別跟您女兒一樣吃虧。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-housing-016-b", text: "過戶的條件，姑姑要不要先透露？", archetype: "deflect", retort: "簡單，你搬回來住就好啦。" },
      { id: "sangu-housing-016-c", text: "空房送我，那姑姑要常來住嗎？", archetype: "deflect", retort: "貧嘴，快說你要不要。" },
      { id: "sangu-housing-016-d", text: "聽起來很好，但條件我怕接受不了……", archetype: "meek", retort: "接受不了，那房子就是白送了。" },
      { id: "sangu-housing-016-e", text: "很心動，只是怕欠人情還不完……", archetype: "meek", retort: "人情要還，不然房子拿得也不安穩。" },
      { id: "sangu-housing-016-f", text: "空房而已，我自己租的地方也不差。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-housing-016-g", text: "我這種人才，房子自己會生出來啦。", archetype: "backfire", retort: "……生出來，那你等生出來再說。" },
      { id: "sangu-housing-016-h", text: "過戶給我，是不是想彌補對女兒的虧欠？", archetype: "landmine", retort: "（臉色鐵青）你給我記住這句。" },
    ],
  },
  {
    id: "sangu-housing-017",
    text: "你現在跟誰一起租房？男的女的？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-017-a", text: "室友的事，等您先說跟媳婦處得怎樣。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-housing-017-b", text: "姑姑問這個，是要來家庭訪問嗎？", archetype: "deflect", retort: "少貧嘴，快說是男是女。" },
      { id: "sangu-housing-017-c", text: "室友的事，等您來我家坐坐就知道。", archetype: "deflect", retort: "好啊，那我下週就去。" },
      { id: "sangu-housing-017-d", text: "是女生室友啦，但我們真的只是朋友……", archetype: "meek", retort: "只是朋友？住一起還算朋友嗎？" },
      { id: "sangu-housing-017-e", text: "換過幾個室友，最近剛好是男的……", archetype: "meek", retort: "換來換去，是不是住得不安穩？" },
      { id: "sangu-housing-017-f", text: "室友是誰不重要，重要是分攤房租。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-housing-017-g", text: "我室友來自各行各業，人脈廣得很。", archetype: "backfire", retort: "……人脈廣，那你怎麼還沒轉行呢。" },
      { id: "sangu-housing-017-h", text: "查我室友前，先管好自己跟媳婦的房間。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-housing-018",
    text: "先買房，其他事情以後再說吧。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-018-a", text: "順序聽您的，先存錢，像您教我的精明。", archetype: "perfect", retort: "……乖，這句我認了。" },
      { id: "sangu-housing-018-b", text: "姑姑當年是先買房，還是先結婚？", archetype: "deflect", retort: "先買房，快去努力存錢。" },
      { id: "sangu-housing-018-c", text: "先買房，那我姓氏都想先留給姑姑。", archetype: "deflect", retort: "貧嘴，快說有沒有在存錢。" },
      { id: "sangu-housing-018-d", text: "道理我懂，但存款速度真的太慢……", archetype: "meek", retort: "太慢就要更節省，別再拖了。" },
      { id: "sangu-housing-018-e", text: "先買房的壓力，讓我有點喘不過氣……", archetype: "meek", retort: "喘不過氣也要撐，別半途而廢。" },
      { id: "sangu-housing-018-f", text: "順序不重要，重要是心裡有沒有房。", archetype: "backfire", retort: "（三姑翻白眼，沒人接話）" },
      { id: "sangu-housing-018-g", text: "我打算先買車，房子以後再說。", archetype: "backfire", retort: "……車子貶值，房子升值，你想想。" },
      { id: "sangu-housing-018-h", text: "先買房，那您跟媳婦的順序怎麼一直卡著？", archetype: "landmine", retort: "（放下筷子）這話，你會後悔。" },
    ],
  },
  {
    id: "sangu-housing-019",
    text: "現在貸款利率多少，你會不會算？",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-019-a", text: "會算，還順便幫您算紅包該包多少才夠。", archetype: "perfect", retort: "呵，這句有實力，我服氣。" },
      { id: "sangu-housing-019-b", text: "姑姑當年貸款利率是多少啊？", archetype: "deflect", retort: "比現在低多了，快回答我。" },
      { id: "sangu-housing-019-c", text: "利率不重要，重要是本金能不能少一點。", archetype: "deflect", retort: "貧嘴，快說你會不會算。" },
      { id: "sangu-housing-019-d", text: "老實說，這方面我真的不太懂……", archetype: "meek", retort: "不懂？那買房前你要先做功課。" },
      { id: "sangu-housing-019-e", text: "查過一次，但看到數字就頭昏……", archetype: "meek", retort: "頭昏也要弄懂，不然被騙都不知道。" },
      { id: "sangu-housing-019-f", text: "利率的事，我打算讓 AI 幫我算。", archetype: "backfire", retort: "（三姑挑眉，沒人相信這說法）" },
      { id: "sangu-housing-019-g", text: "我對數字不敏感，但對感覺很敏銳。", archetype: "backfire", retort: "……感覺敏銳，銀行才不管你感覺。" },
      { id: "sangu-housing-019-h", text: "利率我會算，您紅包最小包這帳更好算。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-housing-020",
    text: "禮拜天姑姑陪你去看房，順便看人。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-020-a", text: "好啊，看房看人，順便看您怎麼挑姑丈的。", archetype: "perfect", retort: "……好，這句我認了，算你機靈。" },
      { id: "sangu-housing-020-b", text: "姑姑安排的人，條件先透露一點？", archetype: "deflect", retort: "見面就知道，別問那麼細。" },
      { id: "sangu-housing-020-c", text: "看房子可以，看人的事下次再排。", archetype: "deflect", retort: "少貧嘴，一次順便才有效率。" },
      { id: "sangu-housing-020-d", text: "看房是好，但看人的部分我沒準備好……", archetype: "meek", retort: "沒準備好也要試試，別逃避。" },
      { id: "sangu-housing-020-e", text: "禮拜天我其實有點想休息……", archetype: "meek", retort: "休息可以，但機會別放過啊。" },
      { id: "sangu-housing-020-f", text: "看房順便看人，太有效率了，我拒絕。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-housing-020-g", text: "看人的事，交給緣分就好，不用安排。", archetype: "backfire", retort: "……緣分等了這麼久，還沒出現呢。" },
      { id: "sangu-housing-020-h", text: "看房順便相親，不如先看看您自己的婚姻。", archetype: "landmine", retort: "（臉色一沉）你這什麼態度！" },
    ],
  },
  {
    id: "sangu-housing-021",
    text: "阿嬤問你租的房子安不安全，有沒有鎖好。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-021-a", text: "安全，比您跟媳婦的關係還牢靠。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-housing-021-b", text: "阿嬤這麼細心，比保全公司還可靠。", archetype: "deflect", retort: "她疼你才會問，別岔開話題。" },
      { id: "sangu-housing-021-c", text: "安全的，晚上還會傳訊息跟阿嬤報平安。", archetype: "deflect", retort: "貧嘴，快說有沒有裝好門鎖。" },
      { id: "sangu-housing-021-d", text: "還好，就是社區大門有點舊，怕怕的……", archetype: "meek", retort: "舊的大門？那你要多小心一點。" },
      { id: "sangu-housing-021-e", text: "說實話，晚上巷子真的有點暗……", archetype: "meek", retort: "暗？那你晚上要早點回家啊。" },
      { id: "sangu-housing-021-f", text: "安全性我早就用風水羅盤算過了。", archetype: "backfire", retort: "（三姑挑眉，沒人相信這說法）" },
      { id: "sangu-housing-021-g", text: "我房子有裝監視器，堪比國家機密局。", archetype: "backfire", retort: "……機密局，那你怎麼還住得那麼便宜。" },
      { id: "sangu-housing-021-h", text: "問安全，不如問您紅包放安全了沒，那麼小包。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-housing-022",
    text: "老家透天房間多，你搬回來住多好。",
    topic: "housing",
    bossId: "sangu",
    options: [
      { id: "sangu-housing-022-a", text: "等我事業穩了，先搬回來陪您過個好年。", archetype: "perfect", retort: "……好，這句聽了姑姑很欣慰。" },
      { id: "sangu-housing-022-b", text: "搬回來的話，我房間能不能挑最大間？", archetype: "deflect", retort: "當然，只要你肯回來就好。" },
      { id: "sangu-housing-022-c", text: "搬回來以前，先讓我搞定工作再說。", archetype: "deflect", retort: "貧嘴，工作哪裡不能做。" },
      { id: "sangu-housing-022-d", text: "老實說，我怕搬回來會失去獨立空間……", archetype: "meek", retort: "失去獨立？家人相處哪那麼計較。" },
      { id: "sangu-housing-022-e", text: "有考慮過，只是工作在外地比較方便……", archetype: "meek", retort: "方便歸方便，家裡才是根本啊。" },
      { id: "sangu-housing-022-f", text: "透天再大，也大不過我的自由靈魂。", archetype: "backfire", retort: "（三姑翻白眼，沒人接話）" },
      { id: "sangu-housing-022-g", text: "房間多沒用，重點是有沒有網路訊號。", archetype: "backfire", retort: "……網路訊號，你在意的重點很妙。" },
      { id: "sangu-housing-022-h", text: "搬回來？您也就這一天想起要有人陪。", archetype: "landmine", retort: "（笑容不見）明年不用來了。" },
    ],
  },
] satisfies Question[];
