import type { Question } from "@/content/types";

// situations: 直接問何時生小孩／說表姊的小孩都會打招呼了／要幫你算生辰八字挑生子年份／
// cross-ref阿嬤說很期待抱曾孫／講她那年代生好幾個都養得起／問是不是不打算生／
// 說趁年輕生比較好／用紅包催生／問朋友是不是都生了就你還沒／說養小孩沒你想的累／
// 問有沒有跟對象討論過生小孩／說少子化都是年輕人這種想法害的／cross-ref三舅媽說表哥要生第二胎／
// 說朋友女兒歲數不小生得很順暗示你還年輕／問是不是把工作看得比家庭重要／說小孩是最好的投資／
// 問打算生幾個／要送嬰兒用品催促／cross-ref陳太太說你朋友都當媽了／說以後老了誰照顧你／
// 問對象家裡想不想要小孩／說她要幫忙顧小孩你只管生／說看到親戚小孩想到自己想抱孫
export default [
  {
    id: "sangu-kids-001",
    text: "什麼時候要生一個？姑姑等很久了。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-001-a", text: "幹，等對象出現，第一個抱的還有您女兒。", archetype: "perfect", retort: "幹，你這孩子嘴巴怎麼這麼賤。" },
      { id: "sangu-kids-001-b", text: "靠北，姑姑想抱孫子還是孫女啊？", archetype: "deflect", retort: "都好，別靠北，快說計畫。" },
      { id: "sangu-kids-001-c", text: "生小孩前，先讓我把您紅包機掰笑納。", archetype: "deflect", retort: "貧嘴，快講正經的時間表。" },
      { id: "sangu-kids-001-d", text: "幹……還沒有計畫，現在真的還沒準備好……", archetype: "meek", retort: "沒準備好？時間可不等你喔。" },
      { id: "sangu-kids-001-e", text: "有想過，靠……但經濟壓力讓我卻步……", archetype: "meek", retort: "卻步歸卻步，但也不能一直拖。" },
      { id: "sangu-kids-001-f", text: "生小孩是投資，去你的我在等時機。", archetype: "backfire", retort: "（三姑不笑，喝了口茶）" },
      { id: "sangu-kids-001-g", text: "我把姪女當自己養，機掰夠了吧。", archetype: "backfire", retort: "……夠了？那是別人的小孩耶。" },
      { id: "sangu-kids-001-h", text: "幹，催我生，不如先催您離婚的女兒，老東西。", archetype: "landmine", retort: "幹！你這什麼態度！" },
    ],
  },
  {
    id: "sangu-kids-002",
    text: "表姊家老二都會叫人了，你呢？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-002-a", text: "幹，我還沒生，但接您話比誰都快。", archetype: "perfect", retort: "幹你娘咧，這句真會講，我服氣。" },
      { id: "sangu-kids-002-b", text: "靠北，老二叫得比老大清楚？姑姑比較過？", archetype: "deflect", retort: "少扯這個，快說你的進度。" },
      { id: "sangu-kids-002-c", text: "表姊家熱鬧，機掰我來當專職叔叔就好。", archetype: "deflect", retort: "貧嘴，快點想想自己的計畫。" },
      { id: "sangu-kids-002-d", text: "幹……我還沒結婚，這個問題有點太前面……", archetype: "meek", retort: "前面？那更要快點動作啊。" },
      { id: "sangu-kids-002-e", text: "看她幸福，靠，心裡也有點著急……", archetype: "meek", retort: "著急就要行動，光急沒有用。" },
      { id: "sangu-kids-002-f", text: "叫人算什麼，去你的我三十歲才學會走路。", archetype: "backfire", retort: "（三姑無語，換話題聊別的）" },
      { id: "sangu-kids-002-g", text: "小孩發展有快有慢，機掰別緊張。", archetype: "backfire", retort: "……緊張的是你自己吧，別轉移。" },
      { id: "sangu-kids-002-h", text: "幹你娘，叫人？先問問您媳婦多久沒叫您一聲，老太婆。", archetype: "landmine", retort: "幹，你這是要找死？" },
    ],
  },
  {
    id: "sangu-kids-003",
    text: "我幫你算過了，明年生子時機最好。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-003-a", text: "幹，那我先算算您當年是怎麼被算著嫁的。", archetype: "perfect", retort: "……機掰，這句損，算你贏。" },
      { id: "sangu-kids-003-b", text: "靠北，算命的準不準，去年準過幾次啊？", archetype: "deflect", retort: "很準，別懷疑，快跟上進度。" },
      { id: "sangu-kids-003-c", text: "時機好，那我要不要先機掰算個對象？", archetype: "deflect", retort: "先找對象，時機才用得上。" },
      { id: "sangu-kids-003-d", text: "幹……時機好是好，但現實條件還差很多……", archetype: "meek", retort: "差很多，那就要更加努力補上。" },
      { id: "sangu-kids-003-e", text: "靠……聽了有點壓力，也不知道能怎麼辦……", archetype: "meek", retort: "不知道怎麼辦，就先從對象開始。" },
      { id: "sangu-kids-003-f", text: "生子時機不用算，去你的交給緣分就好。", archetype: "backfire", retort: "（三姑翻白眼，沒人接話）" },
      { id: "sangu-kids-003-g", text: "幹，我打算等機器人保母上市再生。", archetype: "backfire", retort: "……上市那天，你都退休了吧。" },
      { id: "sangu-kids-003-h", text: "算命準不準，去算算您媳婦什麼時候他媽的回娘家，老東西。", archetype: "landmine", retort: "幹你娘咧，你給我記住這句。" },
    ],
  },
  {
    id: "sangu-kids-004",
    text: "阿嬤說她最想在走之前抱到曾孫。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-004-a", text: "阿嬤好好活著，比您幹話催生有用多了。", archetype: "perfect", retort: "……乖，這句讓姑姑眼眶熱了。" },
      { id: "sangu-kids-004-b", text: "阿嬤先答應我，靠，要健康活久一點。", archetype: "deflect", retort: "當然，我也希望她長命百歲。" },
      { id: "sangu-kids-004-c", text: "那我先努力找對象，機掰順序不能亂啊。", archetype: "deflect", retort: "對，順序沒錯，快加快腳步。" },
      { id: "sangu-kids-004-d", text: "幹……我會努力的，但真的沒辦法保證時間……", archetype: "meek", retort: "努力就好，但別拖太久喔。" },
      { id: "sangu-kids-004-e", text: "靠……聽到這句我壓力有點大……", archetype: "meek", retort: "壓力是動力，乖，別逃避。" },
      { id: "sangu-kids-004-f", text: "姑姑這是道德勒索，去你的我不接受。", archetype: "backfire", retort: "（三姑臉色一沉，全桌尷尬）" },
      { id: "sangu-kids-004-g", text: "抱曾孫不如乾脆抱我，機掰一樣可愛好嗎。", archetype: "backfire", retort: "……你確定一樣可愛嗎？" },
      { id: "sangu-kids-004-h", text: "幹，拿阿嬤心願消費，是您慣用招數吧，老東西。", archetype: "landmine", retort: "幹！你這什麼態度！" },
    ],
  },
  {
    id: "sangu-kids-005",
    text: "我們那年代，生五六個都養得起。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-005-a", text: "所以我佩服您，他媽的當年怎麼挑的姑丈？", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-kids-005-b", text: "靠北，五六個，姑姑當年是怎麼分身的？", archetype: "deflect", retort: "靠毅力，別扯這個，快說想法。" },
      { id: "sangu-kids-005-c", text: "厲害，姑姑那時候機掰一定很有本事。", archetype: "deflect", retort: "那當然，別光說嘴，快去努力。" },
      { id: "sangu-kids-005-d", text: "幹……現在養一個的成本，就差不多當年五個了……", archetype: "meek", retort: "成本高也要想辦法，別放棄。" },
      { id: "sangu-kids-005-e", text: "靠……我也想多生，但現實真的讓人卻步……", archetype: "meek", retort: "卻步就要更拚，年輕人加油。" },
      { id: "sangu-kids-005-f", text: "那年代養小孩成本低，去你的不能比啦。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-kids-005-g", text: "現在講究精緻教育，機掰不是隨便養啦。", archetype: "backfire", retort: "……精緻教育，你連一個都還沒。" },
      { id: "sangu-kids-005-h", text: "生五六個，總比您他媽的跟媳婦都處不好強，老太婆。", archetype: "landmine", retort: "幹你娘咧，你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-kids-006",
    text: "你們是不是根本不打算生小孩啊？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-006-a", text: "有打算，幹，等找到不像您這樣催的長輩再說。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-kids-006-b", text: "靠北，姑姑覺得不生的人生就不完整嗎？", archetype: "deflect", retort: "不是不完整，是少了點什麼。" },
      { id: "sangu-kids-006-c", text: "打算是有的，機掰先讓我準備好心臟。", archetype: "deflect", retort: "貧嘴，快說到底有沒有計畫。" },
      { id: "sangu-kids-006-d", text: "幹……老實說，我們還沒認真討論過這件事……", archetype: "meek", retort: "沒討論過？那你們在拖什麼？" },
      { id: "sangu-kids-006-e", text: "靠……現在這樣也挺好，暫時沒想那麼多……", archetype: "meek", retort: "暫時暫時，一暫就是好幾年。" },
      { id: "sangu-kids-006-f", text: "我這代生小孩要看颱風假，去你的很科學的。", archetype: "backfire", retort: "（三姑愣住，沒人聽懂在說什麼）" },
      { id: "sangu-kids-006-g", text: "我打算養寵物代替，機掰比較省心啦。", archetype: "backfire", retort: "……省心，那你的人生也太安逸了。" },
      { id: "sangu-kids-006-h", text: "不打算生，總比您他媽的女兒婚姻說沒就沒好，老東西。", archetype: "landmine", retort: "幹，你這是找罵？" },
    ],
  },
  {
    id: "sangu-kids-007",
    text: "要生就趁年輕生，年紀大了會辛苦。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-007-a", text: "有道理，我會記得比您他媽的嫁人時想得更清楚。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-kids-007-b", text: "靠北，姑姑覺得幾歲之前算年輕啊？", archetype: "deflect", retort: "三十出頭吧，你要抓緊時間。" },
      { id: "sangu-kids-007-c", text: "趁年輕，那我先機掰把體力練好。", archetype: "deflect", retort: "貧嘴，體力好也要有對象啊。" },
      { id: "sangu-kids-007-d", text: "幹……道理我懂，但現在真的還沒準備好……", archetype: "meek", retort: "沒準備好，那更要早點開始想。" },
      { id: "sangu-kids-007-e", text: "靠……聽了會焦慮，但真的不知道怎麼加快……", archetype: "meek", retort: "焦慮就要行動，光焦慮沒有用。" },
      { id: "sangu-kids-007-f", text: "辛苦是媽媽的事，去你的我當爸爸應該還好。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-kids-007-g", text: "我打算晚點生，機掰晚生的比較有智慧。", archetype: "backfire", retort: "……智慧歸智慧，體力可不等人。" },
      { id: "sangu-kids-007-h", text: "催生這麼起勁，幹，是想蓋過您女兒的婚事吧，老太婆。", archetype: "landmine", retort: "去死啦你，你完了。" },
    ],
  },
  {
    id: "sangu-kids-008",
    text: "紅包我先包大一點，快去生一個。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-008-a", text: "紅包包這麼小，幹，生小孩還是先等等吧。", archetype: "perfect", retort: "……這句我記下來了。" },
      { id: "sangu-kids-008-b", text: "靠北，包大的是要催生還是要收利息啊？", archetype: "deflect", retort: "少貧嘴，快去努力生一個。" },
      { id: "sangu-kids-008-c", text: "紅包先收，機掰計畫容我再仔細規劃。", archetype: "deflect", retort: "規劃可以，但別拖太久喔。" },
      { id: "sangu-kids-008-d", text: "幹……紅包很感激，但生小孩真的急不來……", archetype: "meek", retort: "急不來也要有目標，不能空等。" },
      { id: "sangu-kids-008-e", text: "靠……壓力更大了，收得心裡有點沉……", archetype: "meek", retort: "有壓力才會動起來啊，乖。" },
      { id: "sangu-kids-008-f", text: "紅包收了，去你的生小孩的事就當沒聽到。", archetype: "backfire", retort: "（三姑臉色一沉，收回紅包）" },
      { id: "sangu-kids-008-g", text: "拿人紅包手軟，機掰但嘴巴不軟啦。", archetype: "backfire", retort: "……嘴硬換不到小孩喔。" },
      { id: "sangu-kids-008-h", text: "拿紅包催生，先問問這是不是全場最小包，老東西。", archetype: "landmine", retort: "幹，你這是找罵？" },
    ],
  },
  {
    id: "sangu-kids-009",
    text: "你朋友是不是都當爸媽了，就你還沒？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-009-a", text: "還沒，但我他媽的至少比您女兒早開始想。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-kids-009-b", text: "靠北，姑姑覺得每個人時區都一樣嗎？", archetype: "deflect", retort: "當然不一樣，但也別拖太久。" },
      { id: "sangu-kids-009-c", text: "他們忙著顧小孩，機掰我先幫他們顧您。", archetype: "deflect", retort: "貧嘴，快說你自己的打算。" },
      { id: "sangu-kids-009-d", text: "幹……確實，看他們發文心裡難免有點著急……", archetype: "meek", retort: "著急就要行動，別只是看著急。" },
      { id: "sangu-kids-009-e", text: "靠……每個人條件不同，但也會忍不住比較……", archetype: "meek", retort: "忍不住比較，就要化成動力啊。" },
      { id: "sangu-kids-009-f", text: "他們早生，我晚生，去你的是策略不一樣。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-kids-009-g", text: "我這叫精心規劃，機掰不是落後好嗎。", archetype: "backfire", retort: "……精心規劃，規劃了幾年了？" },
      { id: "sangu-kids-009-h", text: "當爸媽？幹，先問您女兒什麼時候想通再嫁，老太婆。", archetype: "landmine", retort: "幹！你這什麼態度！" },
    ],
  },
  {
    id: "sangu-kids-010",
    text: "養小孩沒你想的那麼累，別想太多。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-010-a", text: "那我先跟您討教，他媽的怎麼帶大不聽話的女兒。", archetype: "perfect", retort: "呵，這句夠壞，我笑了。" },
      { id: "sangu-kids-010-b", text: "靠北，姑姑當年是怎麼熬過那段時間的？", archetype: "deflect", retort: "靠毅力，快說你在怕什麼。" },
      { id: "sangu-kids-010-c", text: "不累的話，機掰姑姑要不要先幫我試養？", archetype: "deflect", retort: "貧嘴，那是你自己的責任。" },
      { id: "sangu-kids-010-d", text: "幹……聽起來輕鬆，但我還是有點害怕承擔……", archetype: "meek", retort: "害怕承擔？那要練習面對啊。" },
      { id: "sangu-kids-010-e", text: "靠……道理我懂，但心理上真的還沒準備好……", archetype: "meek", retort: "沒準備好，就慢慢練習準備。" },
      { id: "sangu-kids-010-f", text: "不累的話，去你的怎麼大家都說崩潰啊。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-kids-010-g", text: "累不累看緣分，機掰我這種人天生好命。", archetype: "backfire", retort: "……好命，那你先養一個試試看。" },
      { id: "sangu-kids-010-h", text: "不累？幹，那您跟媳婦相處怎麼還是那麼累，老東西。", archetype: "landmine", retort: "（冷眼）這桌，你他媽的今天別坐了。" },
    ],
  },
  {
    id: "sangu-kids-011",
    text: "你們兩個有沒有認真討論過生小孩？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-011-a", text: "討論過，順序比您他媽的當年嫁人時清楚多了。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-kids-011-b", text: "靠北，姑姑覺得討論之前要先幹嘛啊？", archetype: "deflect", retort: "先找對象啊，順序別搞錯。" },
      { id: "sangu-kids-011-c", text: "討論好了機掰一定馬上跟姑姑報告。", archetype: "deflect", retort: "貧嘴，快說目前有沒有目標。" },
      { id: "sangu-kids-011-d", text: "幹……老實說，我們還沒認真聊過這個……", archetype: "meek", retort: "沒對象？那你更該積極一點了。" },
      { id: "sangu-kids-011-e", text: "靠……有想過，但兩人的價值觀還沒對齊過……", archetype: "meek", retort: "沒對齊就要趕快聊，別拖著。" },
      { id: "sangu-kids-011-f", text: "討論小孩太危險，去你的我單身比較安全。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-kids-011-g", text: "生不生順其自然，機掰計畫太多沒意思。", archetype: "backfire", retort: "……順其自然，順了好幾年了。" },
      { id: "sangu-kids-011-h", text: "討論生小孩前，幹，先問您跟媳婦好好談過沒，老太婆。", archetype: "landmine", retort: "（拍桌）機掰，你完了！" },
    ],
  },
  {
    id: "sangu-kids-012",
    text: "少子化都是你們這種想法害的啦。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-012-a", text: "所以我更謹慎，不像有些婚姻他媽的說生就生。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-kids-012-b", text: "靠北，姑姑覺得少子化是誰的責任比較多？", archetype: "deflect", retort: "大家都有，但你要先加油。" },
      { id: "sangu-kids-012-c", text: "那我先為國家生育率努力，機掰多吃點。", archetype: "deflect", retort: "貧嘴，吃多不會直接生小孩。" },
      { id: "sangu-kids-012-d", text: "幹……確實，我也有想過自己的責任……", archetype: "meek", retort: "有想過就要付諸行動啊。" },
      { id: "sangu-kids-012-e", text: "靠……壓力很大，但現實條件真的不允許……", archetype: "meek", retort: "不允許也要想辦法克服，別放棄。" },
      { id: "sangu-kids-012-f", text: "少子化是政府的問題，去你的不是我的錯。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-kids-012-g", text: "我把心力都投資在自我成長上，機掰啦。", archetype: "backfire", retort: "……自我成長，成長到現在還是一個人。" },
      { id: "sangu-kids-012-h", text: "少子化怪我，幹，先問問您女兒婚都不想結，老東西。", archetype: "landmine", retort: "幹你娘咧，你這是找死？" },
    ],
  },
  {
    id: "sangu-kids-013",
    text: "三舅媽說表哥要生第二胎了，你呢？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-013-a", text: "表哥厲害，那換問您女兒的第一步呢，幹。", archetype: "perfect", retort: "……好準，這句我服了。" },
      { id: "sangu-kids-013-b", text: "靠北，三舅媽的情報網，連生產計畫都掌握？", archetype: "deflect", retort: "她關心你，別這樣說人家。" },
      { id: "sangu-kids-013-c", text: "第二胎，機掰那紅包會不會包大一點？", archetype: "deflect", retort: "貧嘴，快說你自己的打算。" },
      { id: "sangu-kids-013-d", text: "幹……他們條件比較好，我還在努力階段……", archetype: "meek", retort: "努力階段？那你更要加緊腳步了。" },
      { id: "sangu-kids-013-e", text: "靠……聽了心裡有點著急，但也沒辦法……", archetype: "meek", retort: "著急就要行動，別光是著急。" },
      { id: "sangu-kids-013-f", text: "第二胎而已，去你的我打算直接跳過第一胎。", archetype: "backfire", retort: "（三姑無語，喝了口湯）" },
      { id: "sangu-kids-013-g", text: "我這種人才，機掰一生就是大工程啦。", archetype: "backfire", retort: "……大工程，動工了嗎？" },
      { id: "sangu-kids-013-h", text: "表哥生第二胎，幹，總比您媳婦話都不跟您說強，老太婆。", archetype: "landmine", retort: "機掰，你不想活了？" },
    ],
  },
  {
    id: "sangu-kids-014",
    text: "我朋友的女兒比你晚婚，都生得很順。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-014-a", text: "那正好，時間還很夠，不像您他媽的當年那麼急。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-kids-014-b", text: "靠北，她結婚多晚，姑姑先透露一下嘛。", archetype: "deflect", retort: "比你晚，去了就知道，別問了。" },
      { id: "sangu-kids-014-c", text: "那我要機掰跟她請教一下時間管理。", archetype: "deflect", retort: "貧嘴，快說你自己怎麼想。" },
      { id: "sangu-kids-014-d", text: "幹……聽了是安心一點，但還是有點壓力……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-kids-014-e", text: "靠……確實比較放心，但也不敢完全鬆懈……", archetype: "meek", retort: "不敢鬆懈就對了，繼續加油。" },
      { id: "sangu-kids-014-f", text: "順不順利，去你的是她的事跟我沒關係啦。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著點頭）" },
      { id: "sangu-kids-014-g", text: "我打算走精品路線，機掰晚點生比較稀有。", archetype: "backfire", retort: "……稀有，那你先找到人再說吧。" },
      { id: "sangu-kids-014-h", text: "生得順，幹，總比您女兒感情一直卡住強，老東西。", archetype: "landmine", retort: "幹你娘咧，你給我記住這句。" },
    ],
  },
  {
    id: "sangu-kids-015",
    text: "是不是把工作看得比家庭還重要？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-015-a", text: "工作重要，但沒您這個家重要，他媽的別多想。", archetype: "perfect", retort: "呵，這句有格局，我服氣。" },
      { id: "sangu-kids-015-b", text: "靠北，姑姑覺得工作跟家庭要怎麼排順序？", archetype: "deflect", retort: "當然家庭優先，你要調整心態。" },
      { id: "sangu-kids-015-c", text: "工作重要，但機掰重要不過您煮的年夜飯。", archetype: "deflect", retort: "貧嘴，先說你真正的想法。" },
      { id: "sangu-kids-015-d", text: "幹……確實，我最近把大部分心力都放工作上……", archetype: "meek", retort: "都放工作上，那家庭誰來顧？" },
      { id: "sangu-kids-015-e", text: "靠……聽了有點難受，但好像也講得對……", archetype: "meek", retort: "沒辦法反駁，就代表說對了。" },
      { id: "sangu-kids-015-f", text: "工作重要是因為我這代要拚經濟，去你的啦。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-kids-015-g", text: "我把工作當家庭，機掰同事就是我的孩子。", archetype: "backfire", retort: "……同事聽到不知道會怎麼想。" },
      { id: "sangu-kids-015-h", text: "家庭重要？幹，先問您跟媳婦算不算一家人，老太婆。", archetype: "landmine", retort: "（冷眼）這桌，你他媽的今天別坐了。" },
    ],
  },
  {
    id: "sangu-kids-016",
    text: "小孩是最好的投資，比買房划算多了。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-016-a", text: "那我先把自己養好，他媽的比您紅包划算。", archetype: "perfect", retort: "……好，這句夠有智慧，我認同。" },
      { id: "sangu-kids-016-b", text: "靠北，姑姑覺得投報率大概多少年回本？", archetype: "deflect", retort: "算不清，感情的事別這樣算。" },
      { id: "sangu-kids-016-c", text: "投資報酬率，機掰那我先問問股神表哥。", archetype: "deflect", retort: "貧嘴，快說你自己的想法。" },
      { id: "sangu-kids-016-d", text: "幹……道理我懂，但現在的成本真的太高……", archetype: "meek", retort: "成本高也要想辦法，別放棄。" },
      { id: "sangu-kids-016-e", text: "靠……聽了有點心動，但風險我還沒評估好……", archetype: "meek", retort: "風險評估久了，機會就沒了。" },
      { id: "sangu-kids-016-f", text: "投資小孩不如投資自己，去你的比較穩啦。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著附和）" },
      { id: "sangu-kids-016-g", text: "我這種人才，機掰養出來的一定是天才。", archetype: "backfire", retort: "……天才？先生出來再說吧。" },
      { id: "sangu-kids-016-h", text: "小孩是投資？幹，您那包紅包投資報酬率是負的，老東西。", archetype: "landmine", retort: "幹，你這是找罵？" },
    ],
  },
  {
    id: "sangu-kids-017",
    text: "打算生幾個？一個太孤單了喔。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-017-a", text: "先生一個，他媽的讓您練習當不催人的長輩。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-kids-017-b", text: "靠北，姑姑覺得幾個才算不孤單啊？", archetype: "deflect", retort: "至少兩個吧，有伴才好。" },
      { id: "sangu-kids-017-c", text: "先讓我生一個，機掰其他的順其自然。", archetype: "deflect", retort: "貧嘴，快說你的真實打算。" },
      { id: "sangu-kids-017-d", text: "幹……老實說，一個對現在的我已經很吃力了……", archetype: "meek", retort: "吃力也要試試，別先預設困難。" },
      { id: "sangu-kids-017-e", text: "靠……有想過生兩個，但經濟壓力讓我猶豫……", archetype: "meek", retort: "猶豫歸猶豫，要有明確方向。" },
      { id: "sangu-kids-017-f", text: "我打算生一打，去你的湊個籃球隊剛好。", archetype: "backfire", retort: "（三姑笑笑，沒人相信這說法）" },
      { id: "sangu-kids-017-g", text: "數量不重要，機掰重要是我這代精品主義。", archetype: "backfire", retort: "……精品，那你先有一個再說吧。" },
      { id: "sangu-kids-017-h", text: "一個太孤單？幹，您女兒一個人不也很孤單，老太婆。", archetype: "landmine", retort: "幹！你這什麼態度！" },
    ],
  },
  {
    id: "sangu-kids-018",
    text: "姑姑先幫你買嬰兒床，你就快點生。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-018-a", text: "嬰兒床先收著，他媽的比您那包紅包實用多了。", archetype: "perfect", retort: "……好，這句聽了姑姑很欣慰。" },
      { id: "sangu-kids-018-b", text: "靠北，嬰兒床什麼牌子，姑姑很有研究喔？", archetype: "deflect", retort: "當然，我可是專業級長輩。" },
      { id: "sangu-kids-018-c", text: "先收下，機掰就當作是給未來的鼓勵。", archetype: "deflect", retort: "貧嘴，快說什麼時候能用上。" },
      { id: "sangu-kids-018-d", text: "幹……謝謝姑姑，但我現在真的還沒對象……", archetype: "meek", retort: "沒對象？那你更該積極一點了。" },
      { id: "sangu-kids-018-e", text: "靠……壓力更大了，收得心裡有點沉重……", archetype: "meek", retort: "有壓力才會動起來啊，乖。" },
      { id: "sangu-kids-018-f", text: "嬰兒床收下，去你的生小孩的事先緩緩。", archetype: "backfire", retort: "（三姑臉色一沉，笑意收一半）" },
      { id: "sangu-kids-018-g", text: "拿人東西手軟，機掰但嘴巴不軟啦。", archetype: "backfire", retort: "……嘴硬換不到小孩喔。" },
      { id: "sangu-kids-018-h", text: "買嬰兒床催生，幹，不如先買和好禮物給媳婦，老東西。", archetype: "landmine", retort: "去你的，你完了。" },
    ],
  },
  {
    id: "sangu-kids-019",
    text: "陳太太說你朋友都當媽了，你緊張嗎？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-019-a", text: "不緊張，他媽的我在等一個不被催的時機。", archetype: "perfect", retort: "呵，這句夠淡定，我服氣。" },
      { id: "sangu-kids-019-b", text: "靠北，陳太太連我朋友圈都摸得這麼清楚？", archetype: "deflect", retort: "她關心你，別這樣說人家。" },
      { id: "sangu-kids-019-c", text: "她們當媽，機掰我先當個稱職的乾姑姑。", archetype: "deflect", retort: "貧嘴，快說你自己的心情。" },
      { id: "sangu-kids-019-d", text: "幹……看她們發文，心裡難免有點著急……", archetype: "meek", retort: "著急就要行動，別只是滑手機。" },
      { id: "sangu-kids-019-e", text: "靠……說真的，聽了心裡也會小小緊張……", archetype: "meek", retort: "忍不住比較，就要化成動力啊。" },
      { id: "sangu-kids-019-f", text: "她們早生，我晚生，去你的是策略不一樣。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-kids-019-g", text: "我這是照自己的時程表，機掰不算落後。", archetype: "backfire", retort: "……精心規劃，規劃了幾年了？" },
      { id: "sangu-kids-019-h", text: "當媽這件事，幹，先問您媳婦當得舒不舒心，老太婆。", archetype: "landmine", retort: "幹你娘咧，你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-kids-020",
    text: "你以後老了，沒小孩誰來照顧你？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-020-a", text: "先把您照顧好，他媽的我就懂怎麼照顧自己。", archetype: "perfect", retort: "……這句我記下來了。" },
      { id: "sangu-kids-020-b", text: "靠北，姑姑覺得養兒防老，成功率高嗎？", archetype: "deflect", retort: "當然高，你要早點準備。" },
      { id: "sangu-kids-020-c", text: "到時候，機掰我就搬去跟姑姑一起住。", archetype: "deflect", retort: "貧嘴，快想想自己的長遠打算。" },
      { id: "sangu-kids-020-d", text: "幹……說實話，這個問題我還真沒想清楚……", archetype: "meek", retort: "沒想清楚？那更要早點規劃。" },
      { id: "sangu-kids-020-e", text: "靠……聽了有點焦慮，未來的事真的很難說……", archetype: "meek", retort: "焦慮就要有計畫，別空想。" },
      { id: "sangu-kids-020-f", text: "有機器人照顧，去你的比小孩還孝順呢。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-kids-020-g", text: "我打算靠自己，機掰不想麻煩下一代。", archetype: "backfire", retort: "……靠自己，存款夠了嗎？" },
      { id: "sangu-kids-020-h", text: "沒人照顧？幹，您這年就今天有人陪，想過沒，老東西。", archetype: "landmine", retort: "（笑容不見）明年他媽的不用來了。" },
    ],
  },
  {
    id: "sangu-kids-021",
    text: "你對象家裡，想不想要小孩啊？",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-021-a", text: "想不想不重要，他媽的先讓對象出現，不像您急嫁。", archetype: "perfect", retort: "……這句損，算你贏。" },
      { id: "sangu-kids-021-b", text: "靠北，姑姑先教我，怎麼問對方家裡的意願？", archetype: "deflect", retort: "直接問就好，別拐彎抹角。" },
      { id: "sangu-kids-021-c", text: "這個問題，機掰我會找對象一起聊聊。", archetype: "deflect", retort: "貧嘴，快說目前有沒有目標。" },
      { id: "sangu-kids-021-d", text: "幹……老實說，對象家裡的想法我不清楚……", archetype: "meek", retort: "沒對象？那你更該積極一點了。" },
      { id: "sangu-kids-021-e", text: "靠……有想過，但這麼深入的話題還沒聊過……", archetype: "meek", retort: "沒聊過就要趕快聊，別拖著。" },
      { id: "sangu-kids-021-f", text: "問對象家裡意願太危險，去你的我單身安全。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-kids-021-g", text: "這種事順其自然，機掰計畫太多沒意思。", archetype: "backfire", retort: "……順其自然，順了好幾年了。" },
      { id: "sangu-kids-021-h", text: "問對象家裡想不想，幹，先問您媳婦娘家想不想，老太婆。", archetype: "landmine", retort: "幹你娘咧，你這是找死？" },
    ],
  },
  {
    id: "sangu-kids-022",
    text: "生了我幫你顧，你只管負責生就好。",
    topic: "kids",
    bossId: "sangu",
    options: [
      { id: "sangu-kids-022-a", text: "有您這句，他媽的我更有信心不像您跟媳婦那樣。", archetype: "perfect", retort: "……好，這句聽了姑姑很開心。" },
      { id: "sangu-kids-022-b", text: "靠北，顧小孩的價碼，姑姑打算怎麼算啊？", archetype: "deflect", retort: "少貧嘴，我是真心幫你的。" },
      { id: "sangu-kids-022-c", text: "謝謝姑姑幫忙顧，機掰我們再討論看看。", archetype: "deflect", retort: "考慮什麼，機會難得知道嗎。" },
      { id: "sangu-kids-022-d", text: "幹……很感激，但我現在真的連對象都沒有……", archetype: "meek", retort: "沒對象？那更要趕緊努力去找。" },
      { id: "sangu-kids-022-e", text: "靠……有點心動，但覺得對您太不好意思了……", archetype: "meek", retort: "不好意思什麼，一家人別客氣。" },
      { id: "sangu-kids-022-f", text: "顧小孩的事，去你的我看緣分，隨緣就好。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-kids-022-g", text: "我這種人才，機掰小孩自己會養得好啦。", archetype: "backfire", retort: "……養得好，那你先生一個試試。" },
      { id: "sangu-kids-022-h", text: "幫忙顧？幹，先問您跟媳婦顧得動彼此的心沒，老東西。", archetype: "landmine", retort: "幹你娘咧，你這是要翻臉？" },
    ],
  },
] satisfies Question[];
