import type { Question } from "@/content/types";

// situations: 主位敬酒問對象／翻IG查曖昧對象／宣布已約好相親／問是否跟前任復合／
// 拿鄰居小孩結婚說嘴／審查對象的家世工作／講她當年相親的次數／說你眼光太高／
// 要辦聯誼把你拖去／問多久沒交往／算命說你今年有姻緘／翻舊帳去年說要帶人回來卻沒帶／
// 介紹朋友女兒／問是否在用交友軟體／催年齡說再拖就晚了／cross-ref三舅媽薪水評對象資格／
// 說想抱曾孫情感勒索／問對象怎麼都沒帶回來吃飯／包大紅包催婚／問是不是只同居不結婚／
// cross-ref陳太太說看到你跟人逛街／說她那年代沒得選也嫁得好
export default [
  {
    id: "sangu-marriage-001",
    text: "來，敬你一杯，有對象了沒？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-001-a", text: "有啊，幹，等您跟媳婦和好我就辦桌。", archetype: "perfect", retort: "（冷笑）幹，這句我記下來了。" },
      { id: "sangu-marriage-001-b", text: "靠，姑姑先說，您當年怎麼挑上姑丈的？", archetype: "deflect", retort: "少來，我福氣好而已啦。" },
      { id: "sangu-marriage-001-c", text: "先乾一杯，笑死，感情明年再報告。", archetype: "deflect", retort: "乖，明年沒報告我可不依。" },
      { id: "sangu-marriage-001-d", text: "幹……還沒有耶，工作太忙沒空認識……", archetype: "meek", retort: "沒空？時間都是擠出來的，乖。" },
      { id: "sangu-marriage-001-e", text: "靠……有在嘗試，就是沒遇到合適的……", archetype: "meek", retort: "合適的標準，是不是太高了？" },
      { id: "sangu-marriage-001-f", text: "姑姑先說您幹嘛沒對象啊（笑）", archetype: "backfire", retort: "（全桌安靜，姑丈舉手：我在）" },
      { id: "sangu-marriage-001-g", text: "感情順其自然，幹，強摘的瓜不甜。", archetype: "backfire", retort: "……這句你去年就講過了。" },
      { id: "sangu-marriage-001-h", text: "幹，問對象前，先問問您跟媳婦誰先低頭。", archetype: "landmine", retort: "你他媽的給我滾出去！" },
    ],
  },
  {
    id: "sangu-marriage-002",
    text: "誰的限動？那個人是不是你男朋友？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-002-a", text: "眼睛真利，幹，改天介紹比您女兒體面。", archetype: "perfect", retort: "呵，算你懂事，機掰，有樣子。" },
      { id: "sangu-marriage-002-b", text: "姑姑追蹤那麼多帳號，靠，眼睛不酸嗎？", archetype: "deflect", retort: "酸也要看，關心你才看的。" },
      { id: "sangu-marriage-002-c", text: "笑死，您先讓我看看年輕時的照片啦。", archetype: "deflect", retort: "沒有，都燒掉了，別轉話題。" },
      { id: "sangu-marriage-002-d", text: "幹……同事而已啦，還沒到那個階段……", archetype: "meek", retort: "同事還一起吃早餐？乖，說實話。" },
      { id: "sangu-marriage-002-e", text: "靠……就是朋友，不太確定算什麼……", archetype: "meek", retort: "連自己是什麼都不確定？" },
      { id: "sangu-marriage-002-f", text: "隱私權，機掰，姑姑您聽過這詞嗎？", archetype: "backfire", retort: "（三姑笑笑，繼續滑手機）" },
      { id: "sangu-marriage-002-g", text: "那是我的分身帳號，幹，不是真的。", archetype: "backfire", retort: "（沒人信，全桌低頭忍笑）" },
      { id: "sangu-marriage-002-h", text: "幹，翻我IG前，先翻翻死老太婆您跟媳婦多久沒說話。", archetype: "landmine", retort: "幹！你媽是這樣教你的？" },
    ],
  },
  {
    id: "sangu-marriage-003",
    text: "禮拜六，我朋友的兒子，你去。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-003-a", text: "好啊，機掰，順便幫您問問，您女兒要不要一起。", archetype: "perfect", retort: "……乖，這才是聰明人的做法。" },
      { id: "sangu-marriage-003-b", text: "他條件這麼好，笑死，怎麼還沒被搶走？", archetype: "deflect", retort: "就等你這種識貨的啊，去去去。" },
      { id: "sangu-marriage-003-c", text: "姑姑辛苦了，靠，紅娘費算多少啊？", archetype: "deflect", retort: "少貧嘴，禮拜六準時到。" },
      { id: "sangu-marriage-003-d", text: "幹……禮拜六，我已經有約了耶……", archetype: "meek", retort: "什麼約比姑姑安排的重要？" },
      { id: "sangu-marriage-003-e", text: "靠……好啦，但我沒有心理準備……", archetype: "meek", retort: "見個面而已，準備什麼？" },
      { id: "sangu-marriage-003-f", text: "姑姑，機掰，我怕他配不上我內在美。", archetype: "backfire", retort: "（三姑挑眉，沒人接話）" },
      { id: "sangu-marriage-003-g", text: "相親太老派了，幹，我們這代不流行。", archetype: "backfire", retort: "……你這代倒是很流行單身。" },
      { id: "sangu-marriage-003-h", text: "幹，介紹相親前，先介紹您怎麼跟媳婦和解。", archetype: "landmine", retort: "明年不用他媽的來了！" },
    ],
  },
  {
    id: "sangu-marriage-004",
    text: "你跟以前那個，是不是又復合了？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-004-a", text: "沒有，幹，姑姑消息比您跟媳婦關係還靈通。", archetype: "perfect", retort: "呵呵，這張嘴，機掰，隨你媽。" },
      { id: "sangu-marriage-004-b", text: "姑姑先說，靠，您年輕時分過幾次手？", archetype: "deflect", retort: "這不能比，我當年比較純情。" },
      { id: "sangu-marriage-004-c", text: "復不復合是機密，笑死，紅包先收下。", archetype: "deflect", retort: "耍寶，紅包不是這樣騙的。" },
      { id: "sangu-marriage-004-d", text: "幹……偶爾還有聯絡，但沒有復合啦……", archetype: "meek", retort: "有聯絡就是有機會，乖，小心。" },
      { id: "sangu-marriage-004-e", text: "靠……分開的原因還在，只是習慣了……", archetype: "meek", retort: "習慣不會讓人幸福喔。" },
      { id: "sangu-marriage-004-f", text: "姑姑您幹嘛也想跟姑丈復合？", archetype: "backfire", retort: "（三姑臉一沉，全桌噤聲）" },
      { id: "sangu-marriage-004-g", text: "復合是成長，機掰，我是情場哲學家。", archetype: "backfire", retort: "……哲學家先把碗端過去。" },
      { id: "sangu-marriage-004-h", text: "人呢？他媽的，先問問老東西您女兒的人怎麼不見了。", archetype: "landmine", retort: "去死啦你，這什麼態度！" },
    ],
  },
  {
    id: "sangu-marriage-005",
    text: "隔壁林太太的女兒，下個月訂婚。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-005-a", text: "恭喜她，幹，希望比您女兒那段婚姻長久。", archetype: "perfect", retort: "……嘴巴甜，機掰，這句夠損。" },
      { id: "sangu-marriage-005-b", text: "林太太訂婚宴，靠，紅包包多少啊？", archetype: "deflect", retort: "問這個做什麼，別想省紅包。" },
      { id: "sangu-marriage-005-c", text: "她女兒真厲害，笑死，姑姑要不要拜師？", archetype: "deflect", retort: "拜什麼師，你才要加油。" },
      { id: "sangu-marriage-005-d", text: "幹……每個人的緣分，時間不一樣啦……", archetype: "meek", retort: "時間也要自己去爭取啊，乖。" },
      { id: "sangu-marriage-005-e", text: "靠……我還沒準備好，進入那個階段……", archetype: "meek", retort: "要準備到什麼時候才夠？" },
      { id: "sangu-marriage-005-f", text: "訂婚而已，幹，我等她離婚再恭喜。", archetype: "backfire", retort: "（三姑臉色變，湯匙放下）" },
      { id: "sangu-marriage-005-g", text: "我這叫慢工出細活，機掰，別急。", archetype: "backfire", retort: "……慢了快十年了吧。" },
      { id: "sangu-marriage-005-h", text: "訂婚而已，幹，總比您女兒那場婚姻收尾難看。", archetype: "landmine", retort: "幹你娘咧，你活得不耐煩？" },
    ],
  },
  {
    id: "sangu-marriage-006",
    text: "那個人家裡做什麼的？有房沒？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-006-a", text: "他人品好，他媽的，房子的事比您嫁得踏實。", archetype: "perfect", retort: "……好，這才叫有志氣，機掰。" },
      { id: "sangu-marriage-006-b", text: "姑姑當年嫁姑丈，靠，也是查房子嗎？", archetype: "deflect", retort: "少來，我是看人不看房。" },
      { id: "sangu-marriage-006-c", text: "他家的事，笑死，等結婚您再慢慢查。", archetype: "deflect", retort: "現在不查，以後被騙怎辦？" },
      { id: "sangu-marriage-006-d", text: "幹……他家開小吃店，房子在租的……", archetype: "meek", retort: "租的？那你們以後要住哪？" },
      { id: "sangu-marriage-006-e", text: "靠……還沒細問到那麼深，啦……", archetype: "meek", retort: "談感情不查底細，太天真了。" },
      { id: "sangu-marriage-006-f", text: "姑姑您機掰，是徵信社還是媒人啊？", archetype: "backfire", retort: "（三姑笑笑，沒人跟著笑）" },
      { id: "sangu-marriage-006-g", text: "愛情無價，幹，房價才是身外物。", archetype: "backfire", retort: "……身外物你住得到嗎？" },
      { id: "sangu-marriage-006-h", text: "幹，查戶口式提問，先查查老不死您跟媳婦誰欠誰。", archetype: "landmine", retort: "（摔筷）你他媽找死是不是！" },
    ],
  },
  {
    id: "sangu-marriage-007",
    text: "我們那個年代，相親十次也正常。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-007-a", text: "那您教教我，幹，第十次是怎麼將就成的。", archetype: "perfect", retort: "呵，這句問到重點了，機掰。" },
      { id: "sangu-marriage-007-b", text: "十次！靠，姑丈是第幾次抽中的？", archetype: "deflect", retort: "第三次，別再八卦了你。" },
      { id: "sangu-marriage-007-c", text: "那個年代跟現在，笑死，真的不能比啦。", archetype: "deflect", retort: "怎麼不能比，人心都一樣。" },
      { id: "sangu-marriage-007-d", text: "幹……我可能，連一次都湊不到十次緣分……", archetype: "meek", retort: "湊不到就是不夠努力，乖。" },
      { id: "sangu-marriage-007-e", text: "靠……現在大家，標準都變高了啦……", archetype: "meek", retort: "標準高就更該多相幾次啊。" },
      { id: "sangu-marriage-007-f", text: "那年代選項少，幹，隨便嫁都嫁了。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-marriage-007-g", text: "我這代講究品質，機掰，不講數量啦。", archetype: "backfire", retort: "……品質呢？我怎麼沒看到。" },
      { id: "sangu-marriage-007-h", text: "幹，十次不算什麼，總比您這樁婚一直將就強。", archetype: "landmine", retort: "機掰，你這什麼狗嘴！" },
    ],
  },
  {
    id: "sangu-marriage-008",
    text: "是不是你自己眼光太高了？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-008-a", text: "眼光高，幹，才不會像您那樣將就一輩子。", archetype: "perfect", retort: "……好嘴，機掰，這句我記下了。" },
      { id: "sangu-marriage-008-b", text: "姑姑覺得，靠，我該降到什麼標準？", archetype: "deflect", retort: "至少要人品好，這不算高吧。" },
      { id: "sangu-marriage-008-c", text: "眼光高是因為，笑死，看過您的示範啊。", archetype: "deflect", retort: "少灌迷湯，快找一個。" },
      { id: "sangu-marriage-008-d", text: "幹……可能吧，我對很多事都比較龜毛……", archetype: "meek", retort: "龜毛也要有分寸，乖，改一改。" },
      { id: "sangu-marriage-008-e", text: "靠……不是眼光高，是一直沒遇到而已……", archetype: "meek", retort: "遇不到，是不是根本沒在找？" },
      { id: "sangu-marriage-008-f", text: "我標準低到，機掰，誰都能配別擔心。", archetype: "backfire", retort: "（三姑笑得尷尬，換話題）" },
      { id: "sangu-marriage-008-g", text: "眼光高是天生的，幹，改不了啦。", archetype: "backfire", retort: "……天生的還是嬌生慣養的？" },
      { id: "sangu-marriage-008-h", text: "去你的，眼光高總比死老太婆您嫁得急過得不順心好。", archetype: "landmine", retort: "老東西是你全家吧，滾！" },
    ],
  },
  {
    id: "sangu-marriage-009",
    text: "禮拜天姑姑辦聯誼，你一定要來。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-009-a", text: "好，去你的，順便幫您物色比姑丈合適的。", archetype: "perfect", retort: "……有我年輕時做媒的天分，機掰。" },
      { id: "sangu-marriage-009-b", text: "聯誼名單，靠，先給我看看有沒有熟人。", archetype: "deflect", retort: "熟不熟到現場自己看。" },
      { id: "sangu-marriage-009-c", text: "那天姑姑親自坐鎮嗎，笑死，我才安心？", archetype: "deflect", retort: "當然，我看人很準的。" },
      { id: "sangu-marriage-009-d", text: "幹……禮拜天我想休息，有點抗拒社交……", archetype: "meek", retort: "抗拒社交要怎麼找對象？" },
      { id: "sangu-marriage-009-e", text: "靠……好啦，但我真的不太會聊天……", archetype: "meek", retort: "不會聊就聽，聽也是一種本事。" },
      { id: "sangu-marriage-009-f", text: "聯誼太刻意，機掰，緣分要靠命運安排。", archetype: "backfire", retort: "（三姑翻白眼）命運就是我安排的。" },
      { id: "sangu-marriage-009-g", text: "我去可以，幹，但我不負責被喜歡。", archetype: "backfire", retort: "……自信過頭，全桌沉默。" },
      { id: "sangu-marriage-009-h", text: "幹，辦聯誼？先算算您跟媳婦哪年才能和好。", archetype: "landmine", retort: "（拍桌）你他媽的翻天了！" },
    ],
  },
  {
    id: "sangu-marriage-010",
    text: "說實話，你多久沒談戀愛了？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-010-a", text: "剛好夠久，去死啦，久到懂真愛不是您那種將就。", archetype: "perfect", retort: "呵，這句夠格當接班人，機掰。" },
      { id: "sangu-marriage-010-b", text: "姑姑先說，靠，姑丈追您追多久？", archetype: "deflect", retort: "三年，別轉移話題，回答。" },
      { id: "sangu-marriage-010-c", text: "說出來怕姑姑心疼，笑死，先跳過。", archetype: "deflect", retort: "跳過什麼，講清楚，乖。" },
      { id: "sangu-marriage-010-d", text: "幹……算一算，大概快三年了……", archetype: "meek", retort: "三年！時間不多了，要積極。" },
      { id: "sangu-marriage-010-e", text: "靠……久到我，快忘記怎麼跟人相處了……", archetype: "meek", retort: "忘記就要重新練習啊，別放棄。" },
      { id: "sangu-marriage-010-f", text: "我一直在談，機掰，只是對象是工作。", archetype: "backfire", retort: "（三姑不笑，看著你搖頭）" },
      { id: "sangu-marriage-010-g", text: "單身是我選的，幹，生活風格很潮。", archetype: "backfire", retort: "……潮到全家只有你一個。" },
      { id: "sangu-marriage-010-h", text: "幹，多久沒戀愛，先問老東西您跟姑丈多久沒說話。", archetype: "landmine", retort: "去你的，明年別來了！" },
    ],
  },
  {
    id: "sangu-marriage-011",
    text: "算命的說你今年犯桃花，要把握。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-011-a", text: "那我把握的第一個，幹，是不像您那麼急嫁。", archetype: "perfect", retort: "……油嘴，但我喜歡，機掰。" },
      { id: "sangu-marriage-011-b", text: "犯桃花是好是壞，靠，姑姑先解釋。", archetype: "deflect", retort: "好事啊，要主動一點知道嗎。" },
      { id: "sangu-marriage-011-c", text: "那算命費算我的，笑死，還是您的紅包？", archetype: "deflect", retort: "少貧嘴，把握機會就對了。" },
      { id: "sangu-marriage-011-d", text: "幹……我對算命，沒什麼信心啦，隨緣……", archetype: "meek", retort: "隨緣就是不積極的藉口。" },
      { id: "sangu-marriage-011-e", text: "靠……希望是真的，我最近也有點期待……", archetype: "meek", retort: "期待就要行動，不然白期待。" },
      { id: "sangu-marriage-011-f", text: "犯桃花聽起來，機掰，像犯罪我拒絕。", archetype: "backfire", retort: "（三姑笑不出來，別過頭）" },
      { id: "sangu-marriage-011-g", text: "我的桃花，幹，去年就已經開過了。", archetype: "backfire", retort: "……開過又謝了，可惜。" },
      { id: "sangu-marriage-011-h", text: "幹，犯桃花？先問問您跟媳婦誰先服軟。", archetype: "landmine", retort: "幹，你這什麼畜生嘴巴！" },
    ],
  },
  {
    id: "sangu-marriage-012",
    text: "你去年不是說要帶人回來？人呢？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-012-a", text: "去年練習，去死啦，今年正式比您女兒穩定。", archetype: "perfect", retort: "……好口才，機掰，就等你交卷。" },
      { id: "sangu-marriage-012-b", text: "姑姑記性真好，靠，紅包也記得包大嗎？", archetype: "deflect", retort: "少扯，先回答人在哪裡。" },
      { id: "sangu-marriage-012-c", text: "帶人回來的規格，笑死，我還在準備。", archetype: "deflect", retort: "準備一年還不夠？加快點。" },
      { id: "sangu-marriage-012-d", text: "幹……去年那個，後來分開了……", archetype: "meek", retort: "分開了？那你今年要加油了。" },
      { id: "sangu-marriage-012-e", text: "靠……說要帶，但一直沒到那個階段……", archetype: "meek", retort: "說出去的話怎麼可以不算數？" },
      { id: "sangu-marriage-012-f", text: "去年那是玩笑話，機掰，姑姑別當真。", archetype: "backfire", retort: "（三姑臉一沉，全場安靜）" },
      { id: "sangu-marriage-012-g", text: "人還在磨合，幹，磨合期比較長。", archetype: "backfire", retort: "……磨合一年，是感情還是修行？" },
      { id: "sangu-marriage-012-h", text: "機掰，記那麼牢，先記得老不死您跟媳婦上次說話是何時。", archetype: "landmine", retort: "你他媽的欠教訓是不是！" },
    ],
  },
  {
    id: "sangu-marriage-013",
    text: "我朋友的女兒條件很好，要認識嗎？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-013-a", text: "好啊，幹，能被您看上總比您女兒眼光準。", archetype: "perfect", retort: "……乖，會看人，機掰，隨我。" },
      { id: "sangu-marriage-013-b", text: "條件好到什麼程度，靠，先透露一點？", archetype: "deflect", retort: "見面就知道了，別問那麼細。" },
      { id: "sangu-marriage-013-c", text: "認識可以，笑死，但姑姑要負責到底喔。", archetype: "deflect", retort: "當然，我做媒從不半途而廢。" },
      { id: "sangu-marriage-013-d", text: "幹……好是好，但我怕自己配不上……", archetype: "meek", retort: "配不上就要努力配得上啊，乖。" },
      { id: "sangu-marriage-013-e", text: "靠……認識是可以啦，但有點怕生……", archetype: "meek", retort: "緊張什麼，見個面而已。" },
      { id: "sangu-marriage-013-f", text: "條件好的通常，機掰，眼光更高我怕怕。", archetype: "backfire", retort: "（三姑笑笑，沒人接話）" },
      { id: "sangu-marriage-013-g", text: "我只跟看過我八字合的人，幹，交往。", archetype: "backfire", retort: "……那你這輩子大概沒機會了。" },
      { id: "sangu-marriage-013-h", text: "幹，介紹對象前，先介紹您怎麼跟媳婦處。", archetype: "landmine", retort: "（翻臉）滾，現在就滾！" },
    ],
  },
  {
    id: "sangu-marriage-014",
    text: "你手機裡是不是有那種交友軟體？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-014-a", text: "有，幹，效率比您那年代相親十次高多了。", archetype: "perfect", retort: "呵，敢這樣說我，機掰，有種。" },
      { id: "sangu-marriage-014-b", text: "姑姑要不要，靠，也下載一個試試看？", archetype: "deflect", retort: "少來，快回答有沒有。" },
      { id: "sangu-marriage-014-c", text: "那個是拿來看新聞的，笑死，真的啦。", archetype: "deflect", retort: "看新聞看到臉紅？別鬧了。" },
      { id: "sangu-marriage-014-d", text: "幹……有一個，但一直配對不到合適的……", archetype: "meek", retort: "配不到就要主動出擊啊，乖。" },
      { id: "sangu-marriage-014-e", text: "靠……偶爾滑一下，成功率不高啦……", archetype: "meek", retort: "成功率低是照片沒拍好吧。" },
      { id: "sangu-marriage-014-f", text: "那是我朋友的帳號，機掰，我幫忙管理。", archetype: "backfire", retort: "（三姑挑眉，沒人相信）" },
      { id: "sangu-marriage-014-g", text: "科技始終來自於，幹，單身的寂寞。", archetype: "backfire", retort: "……金句是有了，對象呢？" },
      { id: "sangu-marriage-014-h", text: "幹，查我手機？先查查死老太婆您跟媳婦的LINE已讀。", archetype: "landmine", retort: "幹恁娘，你敢這樣跟我講！" },
    ],
  },
  {
    id: "sangu-marriage-015",
    text: "再拖下去，好對象都被人挑走了。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-015-a", text: "留到現在的，靠北，才不會像您那樣嫁錯將就。", archetype: "perfect", retort: "……好，這句夠有膽識，機掰。" },
      { id: "sangu-marriage-015-b", text: "姑姑覺得，靠，市場上還有哪些好貨？", archetype: "deflect", retort: "有的，但你要主動去搶啊。" },
      { id: "sangu-marriage-015-c", text: "被挑走也好，笑死，省得我費心。", archetype: "deflect", retort: "省心是好，但也太沒鬥志了。" },
      { id: "sangu-marriage-015-d", text: "幹……我知道，但真的急不來……", archetype: "meek", retort: "急不來也要有點行動啊，乖。" },
      { id: "sangu-marriage-015-e", text: "靠……有時候會焦慮，但更怕將就……", archetype: "meek", retort: "焦慮就對了，代表你還在乎。" },
      { id: "sangu-marriage-015-f", text: "剩的才是精品，機掰，姑姑您懂的。", archetype: "backfire", retort: "（三姑笑得僵，換了話題）" },
      { id: "sangu-marriage-015-g", text: "好對象都是磨出來的，幹，急什麼。", archetype: "backfire", retort: "……磨了幾年了，磨出成果沒？" },
      { id: "sangu-marriage-015-h", text: "幹，挑走了又怎樣，總比您女兒挑錯人強。", archetype: "landmine", retort: "去死一死算了，講這什麼話！" },
    ],
  },
  {
    id: "sangu-marriage-016",
    text: "三舅媽說你才賺四萬多，誰敢嫁？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-016-a", text: "賺得少存得下，幹，總比誰都懂您當年的苦。", archetype: "perfect", retort: "……這句損，機掰，但我認了。" },
      { id: "sangu-marriage-016-b", text: "三舅媽這麼在意，靠，是要幫我加薪嗎？", archetype: "deflect", retort: "她哪有那個本事，別鬧。" },
      { id: "sangu-marriage-016-c", text: "四萬多夠養活愛情，笑死，先這樣啦。", archetype: "deflect", retort: "愛情不能當飯吃，乖，實際點。" },
      { id: "sangu-marriage-016-d", text: "幹……薪水是不高，我也在煩惱這件事……", archetype: "meek", retort: "煩惱就要換工作，不能拖。" },
      { id: "sangu-marriage-016-e", text: "靠……沒有人因為薪水離開我，目前啦……", archetype: "meek", retort: "目前啦？以後可不敢保證喔。" },
      { id: "sangu-marriage-016-f", text: "四萬多是稅前，機掰，稅後更精彩。", archetype: "backfire", retort: "（三姑無語，喝了口茶）" },
      { id: "sangu-marriage-016-g", text: "愛情看的是內在，幹，不是數字啦。", archetype: "backfire", retort: "……內在能付房貸嗎？" },
      { id: "sangu-marriage-016-h", text: "幹，誰敢嫁？先問問老東西您跟媳婦誰後悔嫁進門。", archetype: "landmine", retort: "（甩袖）你他媽的太過分了！" },
    ],
  },
  {
    id: "sangu-marriage-017",
    text: "姑姑最想在走之前抱到你的小孩。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-017-a", text: "那您要先健康活到，幹，比催我更值得。", archetype: "perfect", retort: "……乖，這句讓姑姑眼眶熱，機掰。" },
      { id: "sangu-marriage-017-b", text: "姑姑先答應我，靠，要健康活久一點。", archetype: "deflect", retort: "當然，我還要看你結婚呢。" },
      { id: "sangu-marriage-017-c", text: "那我先找對象，笑死，順序不能亂啊。", archetype: "deflect", retort: "對，先找對象，別本末倒置。" },
      { id: "sangu-marriage-017-d", text: "幹……我會努力的，但真的沒辦法保證……", archetype: "meek", retort: "努力就好，但別拖太久喔。" },
      { id: "sangu-marriage-017-e", text: "靠……聽姑姑這樣說，心裡滿沉重的……", archetype: "meek", retort: "壓力是動力，乖，別逃避。" },
      { id: "sangu-marriage-017-f", text: "姑姑這招情感勒索，機掰，我不吃這套。", archetype: "backfire", retort: "（三姑臉色一沉，全桌尷尬）" },
      { id: "sangu-marriage-017-g", text: "抱曾孫不如抱我，幹，一樣可愛。", archetype: "backfire", retort: "……你確定一樣可愛嗎？" },
      { id: "sangu-marriage-017-h", text: "幹，拿身體健康逼婚，是不是想彌補對女兒的虧欠？", archetype: "landmine", retort: "去死，這桌你別坐了！" },
    ],
  },
  {
    id: "sangu-marriage-018",
    text: "怎麼交往這麼久都不帶回來吃飯？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-018-a", text: "怕他被您問到，幹你娘，先讓他練習膽量。", archetype: "perfect", retort: "呵呵，這孩子懂我，機掰，有意思。" },
      { id: "sangu-marriage-018-b", text: "姑姑先答應不查戶口，靠，我就帶。", archetype: "deflect", retort: "好啦好啦，我盡量收斂。" },
      { id: "sangu-marriage-018-c", text: "等他準備好心理建設，笑死，就帶回來。", archetype: "deflect", retort: "心理建設要建多久，年底夠嗎？" },
      { id: "sangu-marriage-018-d", text: "幹……其實是我，還沒準備好被大家審視……", archetype: "meek", retort: "審視什麼，我們是關心而已。" },
      { id: "sangu-marriage-018-e", text: "靠……怕他被問到嚇跑，一直拖著……", archetype: "meek", retort: "拖著也不是辦法，早晚要面對。" },
      { id: "sangu-marriage-018-f", text: "他很忙，機掰，忙到連我都很少見。", archetype: "backfire", retort: "（三姑瞇眼，全桌互看）" },
      { id: "sangu-marriage-018-g", text: "帶回來怕他，幹，被你們比較走了。", archetype: "backfire", retort: "……比較走？我們有那麼糟嗎。" },
      { id: "sangu-marriage-018-h", text: "幹，不帶回來，總比老不死您跟媳婦坐同桌都尷尬好。", archetype: "landmine", retort: "你他媽的皮在癢是不是！" },
    ],
  },
  {
    id: "sangu-marriage-019",
    text: "紅包我先包大的，你快點結婚。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-019-a", text: "紅包這麼小包，幹，結婚的事不急著配合。", archetype: "perfect", retort: "……這句我記下來了，機掰。" },
      { id: "sangu-marriage-019-b", text: "包大的是要催婚，靠，還是要收利息？", archetype: "deflect", retort: "少貧嘴，快點去找對象。" },
      { id: "sangu-marriage-019-c", text: "紅包先收，笑死，喜帖以後再補給您。", archetype: "deflect", retort: "先收也行，但別拖太久喔。" },
      { id: "sangu-marriage-019-d", text: "幹……紅包很感激，但結婚真的急不來……", archetype: "meek", retort: "急不來也要有目標，不能空等。" },
      { id: "sangu-marriage-019-e", text: "靠……紅包收了，壓力反而更重了……", archetype: "meek", retort: "有壓力才會動起來啊，乖。" },
      { id: "sangu-marriage-019-f", text: "紅包收了，機掰，婚事就當作沒聽到。", archetype: "backfire", retort: "（三姑臉色一沉，收回紅包）" },
      { id: "sangu-marriage-019-g", text: "紅包我收下，幹，婚事再說啦哈哈。", archetype: "backfire", retort: "……嘴硬換不到對象喔。" },
      { id: "sangu-marriage-019-h", text: "幹，包大的？先問問這是不是全場最小包。", archetype: "landmine", retort: "（冷眼）你他媽完了，記住！" },
    ],
  },
  {
    id: "sangu-marriage-020",
    text: "你們是不是只同居，根本沒打算結？",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-020-a", text: "同居是考試，幹，結婚才是您跟媳婦都拿不到的證書。", archetype: "perfect", retort: "呵，比喻得好，機掰，我服氣。" },
      { id: "sangu-marriage-020-b", text: "姑姑對同居的定義，靠，是從哪學的？", archetype: "deflect", retort: "少來，快說有沒有打算結婚。" },
      { id: "sangu-marriage-020-c", text: "打算是有的，笑死，日子還在挑而已。", archetype: "deflect", retort: "日子別挑太久，時間可不等人。" },
      { id: "sangu-marriage-020-d", text: "幹……老實說，我們還沒認真討論過……", archetype: "meek", retort: "沒討論過？那你們在拖什麼？" },
      { id: "sangu-marriage-020-e", text: "靠……現在這樣其實也可以，還沒想那麼遠……", archetype: "meek", retort: "暫時暫時，一暫就是好幾年。" },
      { id: "sangu-marriage-020-f", text: "我們這叫雲婚姻，機掰，主打飄渺浪漫啦。", archetype: "backfire", retort: "（三姑愣住）……你在說相聲？" },
      { id: "sangu-marriage-020-g", text: "一張紙而已，幹，感情比較重要啦。", archetype: "backfire", retort: "……那張紙你爸媽可很在意喔。" },
      { id: "sangu-marriage-020-h", text: "去死啦，沒打算結？總比老太婆您跟姑丈那種婚姻名存實亡好。", archetype: "landmine", retort: "你他媽的，滾，別回來了！" },
    ],
  },
  {
    id: "sangu-marriage-021",
    text: "陳太太說看到你跟一個人逛街喔。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-021-a", text: "眼睛真尖，機掰，改天請她喝喜酒比您女兒早。", archetype: "perfect", retort: "……這句我要記下來了，機掰。" },
      { id: "sangu-marriage-021-b", text: "陳太太一天到晚，靠，在街上巡邏嗎？", archetype: "deflect", retort: "她關心你，別這樣說人家。" },
      { id: "sangu-marriage-021-c", text: "她看到的細節，笑死，比我自己還清楚。", archetype: "deflect", retort: "少貧嘴，快說那個人是誰。" },
      { id: "sangu-marriage-021-d", text: "幹……就是，剛開始接觸的朋友啦……", archetype: "meek", retort: "剛開始？那要好好把握啊。" },
      { id: "sangu-marriage-021-e", text: "靠……被看到了就承認，還在觀察階段……", archetype: "meek", retort: "觀察多久？別觀察到人家跑了。" },
      { id: "sangu-marriage-021-f", text: "陳太太認錯人了，機掰，那是我分身。", archetype: "backfire", retort: "（三姑挑眉，沒人相信）" },
      { id: "sangu-marriage-021-g", text: "逛街而已，幹，情報網也太靈通了吧。", archetype: "backfire", retort: "……你才知道我們有多靈通。" },
      { id: "sangu-marriage-021-h", text: "幹，逛個街也被盯，先問誰在意您跟媳婦的事。", archetype: "landmine", retort: "你他媽的給我滾出去！" },
    ],
  },
  {
    id: "sangu-marriage-022",
    text: "我們那年代沒得選也是嫁得好好的。",
    topic: "marriage",
    bossId: "sangu",
    options: [
      { id: "sangu-marriage-022-a", text: "所以我更該珍惜能選，幹，不像您將就一輩子。", archetype: "perfect", retort: "……好，有我當年的樣子，機掰。" },
      { id: "sangu-marriage-022-b", text: "沒得選還嫁那麼好，靠，姑姑真厲害。", archetype: "deflect", retort: "那當然，我眼光一向精準。" },
      { id: "sangu-marriage-022-c", text: "有得選的話，笑死，姑姑會選誰啊？", archetype: "deflect", retort: "少貧嘴，你才是主角，快找。" },
      { id: "sangu-marriage-022-d", text: "幹……現在選項太多，反而更難決定……", archetype: "meek", retort: "選項多是福氣，別當成困擾。" },
      { id: "sangu-marriage-022-e", text: "靠……我也希望能，像姑姑一樣果斷啦……", archetype: "meek", retort: "果斷是逼出來的，你要學。" },
      { id: "sangu-marriage-022-f", text: "沒得選不叫嫁得好，機掰，叫沒辦法。", archetype: "backfire", retort: "（三姑臉一沉，笑容收了一半）" },
      { id: "sangu-marriage-022-g", text: "條件這麼好，幹，我當然要慢慢挑。", archetype: "backfire", retort: "……挑到現在，挑出結果了嗎。" },
      { id: "sangu-marriage-022-h", text: "幹，嫁得好好的？老東西您跟姑丈現在都不太說話了。", archetype: "landmine", retort: "幹！你媽是這樣教你的？" },
    ],
  },
] satisfies Question[];
