import type { Question } from "@/content/types";

// situations: 直接問月薪／cross-ref三舅媽說你四萬多／說要介紹工作給你／問有沒有年終／
// 講她那年代做工也存到房子／問何時升職／說你換工作太頻繁／問是不是還在接案不穩定／
// 說朋友小孩年薪百萬／問有沒有在存錢／要介紹去她朋友公司但條件苛刻／說你工作很閒／
// cross-ref阿嬤說你最近很累／說你現在工作沒前途／問投資賺多少／包紅包資助轉行帶條件／
// 打聽你老闆跟公司八卦／說同學當上主管／問加班多不多／要介紹去考公家機關鐵飯碗／
// cross-ref大伯說書讀那麼多領這麼少／要介紹去幫朋友孩子當家教
export default [
  {
    id: "sangu-salary_job-001",
    text: "老實說，你現在一個月領多少？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-001-a", text: "夠付孝親費，比您那包紅包更看得出誠意。", archetype: "perfect", retort: "……這句我記下來了。" },
      { id: "sangu-salary_job-001-b", text: "姑姑先說，姑丈當年月薪多少？", archetype: "deflect", retort: "少扯姑丈，快回答我。" },
      { id: "sangu-salary_job-001-c", text: "數字不重要，重要的是您紅包多少。", archetype: "deflect", retort: "貧嘴，快講正經的。" },
      { id: "sangu-salary_job-001-d", text: "四萬出頭，扣一扣沒剩多少……", archetype: "meek", retort: "四萬多？那你打算存到什麼時候？" },
      { id: "sangu-salary_job-001-e", text: "不算高，但夠我自己過生活……", archetype: "meek", retort: "夠自己過，家裡呢？以後呢？" },
      { id: "sangu-salary_job-001-f", text: "我領的是理想，理想是無價的。", archetype: "backfire", retort: "（三姑不笑，喝了口茶）" },
      { id: "sangu-salary_job-001-g", text: "低調領錢，高調花錢，這是哲學。", archetype: "backfire", retort: "……哲學家先把碗端過去洗。" },
      { id: "sangu-salary_job-001-h", text: "領多少關您什麼事，先算算您紅包多小包。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-salary_job-002",
    text: "三舅媽說你才四萬多，是真的嗎？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-002-a", text: "四萬多存得下，總比誰都懂您當年的苦。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-salary_job-002-b", text: "三舅媽的情報網，比國安局還準。", archetype: "deflect", retort: "少貧嘴，她也是關心你。" },
      { id: "sangu-salary_job-002-c", text: "數字她記得比我還熟，厲害吧。", archetype: "deflect", retort: "少扯，快說是不是真的。" },
      { id: "sangu-salary_job-002-d", text: "差不多啦，公司規模比較小……", archetype: "meek", retort: "小公司福利差，你要多留意。" },
      { id: "sangu-salary_job-002-e", text: "是真的，我也在想辦法加薪……", archetype: "meek", retort: "想辦法，是想了多久還沒動？" },
      { id: "sangu-salary_job-002-f", text: "我領的是夢想，舅媽領的是八卦。", archetype: "backfire", retort: "（三姑瞇眼，全桌都沒接話）" },
      { id: "sangu-salary_job-002-g", text: "四萬多是稅前，稅後才是重點。", archetype: "backfire", retort: "……重點是你還是四萬多。" },
      { id: "sangu-salary_job-002-h", text: "三舅媽算薪水，怎麼不算您跟媳婦多久沒說話。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-003",
    text: "我朋友的公司缺人，你要不要來？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-003-a", text: "先問待遇，畢竟您紅包的行情我很清楚。", archetype: "perfect", retort: "……乖，這才叫謹慎，隨我。" },
      { id: "sangu-salary_job-003-b", text: "那間公司福利怎樣？姑姑先說服我。", archetype: "deflect", retort: "福利很好，你去就知道。" },
      { id: "sangu-salary_job-003-c", text: "介紹費算了沒？我怕您吃虧。", archetype: "deflect", retort: "少貧嘴，機會難得知道嗎。" },
      { id: "sangu-salary_job-003-d", text: "聽起來不錯，但我現在的工作也捨不得……", archetype: "meek", retort: "捨不得？機會不等人的。" },
      { id: "sangu-salary_job-003-e", text: "可以考慮，但條件細節還沒問清楚……", archetype: "meek", retort: "沒問清楚就別急著答應。" },
      { id: "sangu-salary_job-003-f", text: "介紹工作，是不是想從中抽成？", archetype: "backfire", retort: "（三姑臉一沉，氣氛冷了）" },
      { id: "sangu-salary_job-003-g", text: "我這種人才，公司搶著要好嗎。", archetype: "backfire", retort: "……搶著要怎麼還沒被搶走？" },
      { id: "sangu-salary_job-003-h", text: "介紹工作？先介紹您跟媳婦怎麼合得來。", archetype: "landmine", retort: "（沉聲）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-004",
    text: "今年年終有多少？夠不夠包紅包？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-004-a", text: "夠包，但您那包永遠是全場最小包。", archetype: "perfect", retort: "呵呵，這句真討喜，我收下了。" },
      { id: "sangu-salary_job-004-b", text: "姑姑先透露，您今年紅包行情多少？", archetype: "deflect", retort: "少來，先講你的年終。" },
      { id: "sangu-salary_job-004-c", text: "年終是機密，紅包才是重點吧。", archetype: "deflect", retort: "貧嘴，快講數字。" },
      { id: "sangu-salary_job-004-d", text: "沒多少，公司今年業績不太好……", archetype: "meek", retort: "業績不好，你也該想想後路。" },
      { id: "sangu-salary_job-004-e", text: "剛好夠付卡費，紅包要省一點包……", archetype: "meek", retort: "付卡費？你是不是花錢太兇了。" },
      { id: "sangu-salary_job-004-f", text: "年終是零，但我心意是無限的。", archetype: "backfire", retort: "（三姑露出尷尬的笑）" },
      { id: "sangu-salary_job-004-g", text: "我把年終都拿去投資自己了。", archetype: "backfire", retort: "……投資自己，回報在哪呢？" },
      { id: "sangu-salary_job-004-h", text: "問紅包夠不夠，先問您那包夠不夠意思。", archetype: "landmine", retort: "（筷子一放）你媽這樣教你的？" },
    ],
  },
  {
    id: "sangu-salary_job-005",
    text: "我們那年代，做工也存得到一間房。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-005-a", text: "姑姑當年真辛苦，比嫁人那決定還拚。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-salary_job-005-b", text: "那年代一坪多少錢，姑姑記得嗎？", archetype: "deflect", retort: "幾萬塊而已，別扯這個。" },
      { id: "sangu-salary_job-005-c", text: "姑姑那個年代真的很有魄力。", archetype: "deflect", retort: "那當然，別光說嘴，去努力。" },
      { id: "sangu-salary_job-005-d", text: "現在薪水追房價真的很吃力……", archetype: "meek", retort: "差很多也要想辦法，別放棄。" },
      { id: "sangu-salary_job-005-e", text: "我也拚命存，但速度真的跟不上……", archetype: "meek", retort: "追不上就要更拚，年輕人。" },
      { id: "sangu-salary_job-005-f", text: "那年代物價低，比較沒有可比性。", archetype: "backfire", retort: "（三姑瞇眼，笑意收了一半）" },
      { id: "sangu-salary_job-005-g", text: "我這代做的是知識工作，不一樣。", archetype: "backfire", retort: "……不一樣，但一樣沒存到房。" },
      { id: "sangu-salary_job-005-h", text: "存得到房，存不到您跟媳婦好好說話的一天。", archetype: "landmine", retort: "（冷眼）這桌，你今天別坐了。" },
    ],
  },
  {
    id: "sangu-salary_job-006",
    text: "進公司這麼多年，什麼時候升職？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-006-a", text: "升職那天，第一個紅包包給您，比您大包。", archetype: "perfect", retort: "……好，這句我收下，等著喔。" },
      { id: "sangu-salary_job-006-b", text: "姑姑覺得我該升到什麼位置？", archetype: "deflect", retort: "至少要當個主管吧，加油。" },
      { id: "sangu-salary_job-006-c", text: "升職前，先讓我請您吃頓飯慶祝。", archetype: "deflect", retort: "少討好我，先把工作做好。" },
      { id: "sangu-salary_job-006-d", text: "公司內部升遷比較慢，還在排隊……", archetype: "meek", retort: "排隊？要主動爭取才有機會。" },
      { id: "sangu-salary_job-006-e", text: "上次考核沒過，還在檢討自己……", archetype: "meek", retort: "沒過就要問清楚原因，別悶著。" },
      { id: "sangu-salary_job-006-f", text: "升職？我早就是幕後真正的老闆。", archetype: "backfire", retort: "（三姑沒接話，看向別處）" },
      { id: "sangu-salary_job-006-g", text: "我不想升職，責任大薪水沒差多少。", archetype: "backfire", retort: "……那你打算原地踏步到幾歲？" },
      { id: "sangu-salary_job-006-h", text: "升職靠關係？先問您媳婦是不是也這麼想您。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-007",
    text: "聽說你這幾年換了好多份工作喔。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-007-a", text: "每一份都是升級，不像您那樁婚姻沒得換。", archetype: "perfect", retort: "呵，這句夠有膽識，我喜歡。" },
      { id: "sangu-salary_job-007-b", text: "姑姑當年換過幾次工作啊？", archetype: "deflect", retort: "一次，別亂比，快說原因。" },
      { id: "sangu-salary_job-007-c", text: "換工作是為了找到能孝順您的那份。", archetype: "deflect", retort: "貧嘴，快點穩定下來。" },
      { id: "sangu-salary_job-007-d", text: "每次都遇到一些狀況，不太順利……", archetype: "meek", retort: "狀況那麼多，是不是自己也有問題？" },
      { id: "sangu-salary_job-007-e", text: "在找適合自己的方向，還在摸索……", archetype: "meek", retort: "摸索太久，履歷會被人質疑喔。" },
      { id: "sangu-salary_job-007-f", text: "我是斜槓青年，多份經歷是資產。", archetype: "backfire", retort: "（三姑笑笑，沒有跟著點頭）" },
      { id: "sangu-salary_job-007-g", text: "換工作代表我很搶手，很正常。", archetype: "backfire", retort: "……搶手怎麼每次都做不久？" },
      { id: "sangu-salary_job-007-h", text: "換工作是我的自由，總比您嫁錯人沒得換好。", archetype: "landmine", retort: "（臉色鐵青）你給我記住這句。" },
    ],
  },
  {
    id: "sangu-salary_job-008",
    text: "接案不穩定，什麼時候找個正職？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-008-a", text: "接案是正職，老闆是自己，不像您嫁人靠別人。", archetype: "perfect", retort: "……好，這句有氣勢，記下了。" },
      { id: "sangu-salary_job-008-b", text: "姑姑覺得正職穩，還是老闆穩？", archetype: "deflect", retort: "少辯，快說什麼時候找正職。" },
      { id: "sangu-salary_job-008-c", text: "接案自由，才能常回來陪您吃飯。", archetype: "deflect", retort: "貧嘴，快點穩定收入才重要。" },
      { id: "sangu-salary_job-008-d", text: "案量不固定，這個月真的比較少……", archetype: "meek", retort: "案量少，是不是該找個備案？" },
      { id: "sangu-salary_job-008-e", text: "有考慮找正職，但還沒下定決心……", archetype: "meek", retort: "下不了決心，時間拖久了更難。" },
      { id: "sangu-salary_job-008-f", text: "接案的世界，你們正職族不懂啦。", archetype: "backfire", retort: "（三姑挑眉，沒人接話）" },
      { id: "sangu-salary_job-008-g", text: "我是自由工作者，聽起來就很潮。", archetype: "backfire", retort: "……潮歸潮，收入穩不穩？" },
      { id: "sangu-salary_job-008-h", text: "不穩定？總比您跟媳婦關係還不穩定好。", archetype: "landmine", retort: "（沉聲）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-009",
    text: "隔壁老王的兒子，年薪破百萬耶。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-009-a", text: "厲害，改天請他教教您怎麼算紅包比例。", archetype: "perfect", retort: "……好，這句大方又聰明。" },
      { id: "sangu-salary_job-009-b", text: "他做什麼行業，姑姑幫我打聽？", archetype: "deflect", retort: "軟體業，聽說壓力也很大。" },
      { id: "sangu-salary_job-009-c", text: "百萬年薪，紅包一定包很大吧？", archetype: "deflect", retort: "少扯這個，快跟人家看齊。" },
      { id: "sangu-salary_job-009-d", text: "差人家好幾倍，聽了有點洩氣……", archetype: "meek", retort: "洩氣沒用，要想辦法追上去。" },
      { id: "sangu-salary_job-009-e", text: "每個人領域不同，但心裡難免比較……", archetype: "meek", retort: "難免比較，就要化成動力啊。" },
      { id: "sangu-salary_job-009-f", text: "百萬而已，我心靈富足值千萬。", archetype: "backfire", retort: "（三姑沒笑，喝了口湯）" },
      { id: "sangu-salary_job-009-g", text: "他那行業辛苦，我這行才是藍海。", archetype: "backfire", retort: "……藍海怎麼薪水這麼少呢。" },
      { id: "sangu-salary_job-009-h", text: "年薪百萬，總比您這年就今天被想起強。", archetype: "landmine", retort: "（笑容不見）明年不用來了。" },
    ],
  },
  {
    id: "sangu-salary_job-010",
    text: "你有在存錢嗎？別當個月光族。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-010-a", text: "有，我的存摺比您那包紅包扎實多了。", archetype: "perfect", retort: "呵，這句真會講，我服氣。" },
      { id: "sangu-salary_job-010-b", text: "姑姑當年的存錢秘訣是什麼？", archetype: "deflect", retort: "先記帳，你有記帳嗎？" },
      { id: "sangu-salary_job-010-c", text: "存錢的事，改天請您來當我的財務長。", archetype: "deflect", retort: "少貧嘴，先自己管好再說。" },
      { id: "sangu-salary_job-010-d", text: "有存，但速度真的不快……", archetype: "meek", retort: "不快就要開源節流，別鬆懈。" },
      { id: "sangu-salary_job-010-e", text: "說實話，這個月又花超過預算了……", archetype: "meek", retort: "又超過？你要好好檢討花費。" },
      { id: "sangu-salary_job-010-f", text: "我把錢都存在朋友的錢包裡。", archetype: "backfire", retort: "（三姑無語，換話題聊別的）" },
      { id: "sangu-salary_job-010-g", text: "月光族聽起來，比較浪漫一點啦。", archetype: "backfire", retort: "……浪漫換不到房子喔。" },
      { id: "sangu-salary_job-010-h", text: "存錢的事，先問您跟媳婦誰的私房錢多。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-011",
    text: "我朋友的公司缺人，薪水少但穩定。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-011-a", text: "穩定重要，先請您幫我探探底，像您嫁人那樣精。", archetype: "perfect", retort: "……這句損，但我認了。" },
      { id: "sangu-salary_job-011-b", text: "薪水少多少，姑姑先透露一下嘛。", archetype: "deflect", retort: "去了就知道，別討價還價。" },
      { id: "sangu-salary_job-011-c", text: "穩定的定義，是不是就是加不了薪？", archetype: "deflect", retort: "少貧嘴，穩定總比動盪好。" },
      { id: "sangu-salary_job-011-d", text: "薪水少，我怕生活會更緊……", archetype: "meek", retort: "緊一點也要撐，先求有再求好。" },
      { id: "sangu-salary_job-011-e", text: "聽起來不錯，但要考慮一下細節……", archetype: "meek", retort: "考慮太久，機會就沒了。" },
      { id: "sangu-salary_job-011-f", text: "薪水少的工作，姑姑自己去做啊。", archetype: "backfire", retort: "（三姑臉一沉，氣氛僵了）" },
      { id: "sangu-salary_job-011-g", text: "我這種人才，怎麼可能領少的。", archetype: "backfire", retort: "……人才怎麼還在找工作呢。" },
      { id: "sangu-salary_job-011-h", text: "薪水少還要我去，先問您紅包少不少意思。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-salary_job-012",
    text: "你們公司是不是很閒？看你都在滑手機。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-012-a", text: "在滑手機，是因為工作比您跟媳婦的話還少。", archetype: "perfect", retort: "……好，這句夠有效率精神。" },
      { id: "sangu-salary_job-012-b", text: "姑姑覺得認真的定義是什麼？", archetype: "deflect", retort: "認真就是別一直滑手機啦。" },
      { id: "sangu-salary_job-012-c", text: "我這叫遠端待命，隨時應戰。", archetype: "deflect", retort: "貧嘴，快說在忙什麼。" },
      { id: "sangu-salary_job-012-d", text: "最近案子比較少，確實比較閒……", archetype: "meek", retort: "閒著也要找點事做，別浪費時間。" },
      { id: "sangu-salary_job-012-e", text: "工作內容比較彈性，看起來像在滑……", archetype: "meek", retort: "看起來像，別人也會誤會啊。" },
      { id: "sangu-salary_job-012-f", text: "滑手機也是一種市場調查，很專業。", archetype: "backfire", retort: "（三姑笑笑，沒人相信）" },
      { id: "sangu-salary_job-012-g", text: "我是用效率換時間，聰明工作啦。", archetype: "backfire", retort: "……聰明到看起來很閒呢。" },
      { id: "sangu-salary_job-012-h", text: "很閒？總比您這年就今天忙著問人強。", archetype: "landmine", retort: "（沉默三秒）你說完了？" },
    ],
  },
  {
    id: "sangu-salary_job-013",
    text: "阿嬤說你最近看起來很累，是壓力大？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-013-a", text: "有點累，但沒您跟媳婦相處那麼累。", archetype: "perfect", retort: "呵，這句聽了讓人放心，記下了。" },
      { id: "sangu-salary_job-013-b", text: "阿嬤觀察力真好，比健檢儀器準。", archetype: "deflect", retort: "她疼你才會注意，別岔開話題。" },
      { id: "sangu-salary_job-013-c", text: "累是累，但看到您就精神了。", archetype: "deflect", retort: "貧嘴，快說到底累不累。" },
      { id: "sangu-salary_job-013-d", text: "最近工作量真的比較大，有點吃不消……", archetype: "meek", retort: "吃不消就要說，別硬撐著。" },
      { id: "sangu-salary_job-013-e", text: "壓力是有，但還在能承受的範圍……", archetype: "meek", retort: "能承受不代表要一直忍，乖。" },
      { id: "sangu-salary_job-013-f", text: "累是因為我太優秀，公司離不開我。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著笑）" },
      { id: "sangu-salary_job-013-g", text: "累一點才有存在感，這樣才踏實。", archetype: "backfire", retort: "……踏實到黑眼圈都出來了。" },
      { id: "sangu-salary_job-013-h", text: "累不累關您什麼事，先問您跟媳婦累不累。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-014",
    text: "老實說，你這份工作有前途嗎？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-014-a", text: "有，前途在自己手上，不像有些婚姻靠忍。", archetype: "perfect", retort: "……好，這句有志氣，我認同。" },
      { id: "sangu-salary_job-014-b", text: "姑姑覺得什麼樣才叫有前途啊？", archetype: "deflect", retort: "至少要有加薪空間吧，加油。" },
      { id: "sangu-salary_job-014-c", text: "前途看不看得到不重要，重要是走得穩。", archetype: "deflect", retort: "貧嘴，快點想清楚方向。" },
      { id: "sangu-salary_job-014-d", text: "老實說，我自己也有點迷惘……", archetype: "meek", retort: "迷惘就要趕快找方向，別耗著。" },
      { id: "sangu-salary_job-014-e", text: "短期看不出來，但我還在努力找答案……", archetype: "meek", retort: "找答案要有期限，別找一輩子。" },
      { id: "sangu-salary_job-014-f", text: "前途？我這行業未來一定爆紅啦。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-salary_job-014-g", text: "我在等時機，時機一到馬上飛黃騰達。", archetype: "backfire", retort: "……等了多久，時機來了沒？" },
      { id: "sangu-salary_job-014-h", text: "有沒有前途，先問您這段婚姻還有沒有。", archetype: "landmine", retort: "（臉色一沉）你這什麼態度！" },
    ],
  },
  {
    id: "sangu-salary_job-015",
    text: "聽說你有在買股票，賺了多少？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-015-a", text: "賺不多，但學到的比您嫁人的智慧多。", archetype: "perfect", retort: "……好，這心態值得肯定，記下了。" },
      { id: "sangu-salary_job-015-b", text: "姑姑也有在玩嗎？可以互相交流。", archetype: "deflect", retort: "我才不碰，快說你賺賠多少。" },
      { id: "sangu-salary_job-015-c", text: "賺賠是機密，紅包才是穩賺不賠。", archetype: "deflect", retort: "貧嘴，快點正經回答。" },
      { id: "sangu-salary_job-015-d", text: "老實說，這波賠了一點……", archetype: "meek", retort: "賠了？那你怎麼還敢繼續投？" },
      { id: "sangu-salary_job-015-e", text: "小賺一點，但不太敢跟家人講金額……", archetype: "meek", retort: "不敢講，是不是心裡有數？" },
      { id: "sangu-salary_job-015-f", text: "我是長期投資者，短期數字不重要。", archetype: "backfire", retort: "（三姑挑眉，明顯不太相信）" },
      { id: "sangu-salary_job-015-g", text: "投資這種事，賺賠都是經驗值。", archetype: "backfire", retort: "……經驗值換不了現金喔。" },
      { id: "sangu-salary_job-015-h", text: "問股票，先問您紅包投資報酬率負多少。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-salary_job-016",
    text: "紅包我先給你，去外面轉個好行業。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-016-a", text: "紅包收下，方向我自己找，比您那包大方。", archetype: "perfect", retort: "……乖，有主見，這才是我教出來的。" },
      { id: "sangu-salary_job-016-b", text: "姑姑心目中的好行業，是哪一種？", archetype: "deflect", retort: "穩定、體面，你自己想想。" },
      { id: "sangu-salary_job-016-c", text: "紅包先收，行業的事讓我慢慢規劃。", archetype: "deflect", retort: "慢慢規劃可以，別拖太久。" },
      { id: "sangu-salary_job-016-d", text: "轉行需要時間跟成本，我還在評估……", archetype: "meek", retort: "評估要有期限，不能一直拖。" },
      { id: "sangu-salary_job-016-e", text: "收了紅包，壓力反而更大了……", archetype: "meek", retort: "有壓力才有動力，別想太多。" },
      { id: "sangu-salary_job-016-f", text: "紅包收下，行業的事我自有分寸。", archetype: "backfire", retort: "（三姑臉一沉，笑意收一半）" },
      { id: "sangu-salary_job-016-g", text: "我現在的行業其實就很好行了。", archetype: "backfire", retort: "……好到還要姑姑資助你？" },
      { id: "sangu-salary_job-016-h", text: "拿紅包逼轉行，先問這是不是全場最小包。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-017",
    text: "你老闆對你好不好？公司福利怎樣？",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-017-a", text: "老闆很好，好到讓我學會怎麼跟您談判。", archetype: "perfect", retort: "呵，這句有智慧，我喜歡。" },
      { id: "sangu-salary_job-017-b", text: "姑姑是不是想幫我談加薪啊？", archetype: "deflect", retort: "少貧嘴，快說老闆怎麼樣。" },
      { id: "sangu-salary_job-017-c", text: "福利普通，但同事都很挺我。", archetype: "deflect", retort: "同事挺你也不能當飯吃啊。" },
      { id: "sangu-salary_job-017-d", text: "老闆還可以，就是常常臨時加班……", archetype: "meek", retort: "臨時加班？那薪水有加嗎？" },
      { id: "sangu-salary_job-017-e", text: "福利不算好，但我也不敢要求太多……", archetype: "meek", retort: "不敢要求，你就是被吃定了。" },
      { id: "sangu-salary_job-017-f", text: "我老闆超好，好到都忘記發獎金了。", archetype: "backfire", retort: "（三姑無語，沒人接話）" },
      { id: "sangu-salary_job-017-g", text: "福利這種東西，看緣分不看合約啦。", archetype: "backfire", retort: "……看緣分，那薪水也看緣分嗎。" },
      { id: "sangu-salary_job-017-h", text: "福利怎樣？先問您跟媳婦的關係福利怎樣。", archetype: "landmine", retort: "（沉聲）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-018",
    text: "你同學小陳，聽說已經當上主管了。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-018-a", text: "他當主管，我當自己人生的主管，不靠嫁。", archetype: "perfect", retort: "……好，這句夠格，我服氣。" },
      { id: "sangu-salary_job-018-b", text: "小陳當主管了？姑姑消息真靈通。", archetype: "deflect", retort: "那當然，快跟人家多學學。" },
      { id: "sangu-salary_job-018-c", text: "他當主管，紅包會不會多包一點？", archetype: "deflect", retort: "貧嘴，快說你自己有什麼打算。" },
      { id: "sangu-salary_job-018-d", text: "小陳真的厲害，我還差得遠……", archetype: "meek", retort: "差一大截就要更努力追上去。" },
      { id: "sangu-salary_job-018-e", text: "多少有點壓力，但真心替他開心……", archetype: "meek", retort: "有壓力就要轉成動力，別光說。" },
      { id: "sangu-salary_job-018-f", text: "主管而已，我未來是要當老闆的。", archetype: "backfire", retort: "（三姑笑笑，沒人附和）" },
      { id: "sangu-salary_job-018-g", text: "他升遷靠關係，我升遷靠實力慢慢來。", archetype: "backfire", retort: "……實力慢慢來，慢了幾年了。" },
      { id: "sangu-salary_job-018-h", text: "當主管靠拍馬屁？先問您跟媳婦誰拍誰。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-019",
    text: "最近加班多不多？看你都沒空回家。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-019-a", text: "加班多，但年前一定排開，比您想我還多。", archetype: "perfect", retort: "呵，這句聽了真窩心，記下了。" },
      { id: "sangu-salary_job-019-b", text: "姑姑當年也常加班到很晚嗎？", archetype: "deflect", retort: "常，別岔開話題，快回答。" },
      { id: "sangu-salary_job-019-c", text: "加班的空檔，都在想您煮的菜。", archetype: "deflect", retort: "貧嘴，快說到底忙不忙。" },
      { id: "sangu-salary_job-019-d", text: "最近真的滿常加班的，快沒力了……", archetype: "meek", retort: "沒力就要跟公司反映，別硬撐。" },
      { id: "sangu-salary_job-019-e", text: "常常加班，家裡的事都顧不太到……", archetype: "meek", retort: "顧不到，時間久了大家會擔心。" },
      { id: "sangu-salary_job-019-f", text: "加班是因為我不可取代，沒辦法。", archetype: "backfire", retort: "（三姑挑眉，沒人跟著點頭）" },
      { id: "sangu-salary_job-019-g", text: "忙才有價值，閒著才讓人擔心啦。", archetype: "backfire", retort: "……忙成這樣，家裡更擔心你。" },
      { id: "sangu-salary_job-019-h", text: "沒空回家？總比您這年就今天想起我強。", archetype: "landmine", retort: "（臉一沉）你這種嘴，明年別來。" },
    ],
  },
  {
    id: "sangu-salary_job-020",
    text: "去考個公家機關，鐵飯碗多穩定。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-020-a", text: "鐵飯碗好，但我先把現在的碗端穩，像您教的精。", archetype: "perfect", retort: "……乖，這句有骨氣，我認同。" },
      { id: "sangu-salary_job-020-b", text: "姑姑想我考哪個單位比較好？", archetype: "deflect", retort: "隨便，穩定就好，快去準備。" },
      { id: "sangu-salary_job-020-c", text: "考上以後，第一件事就是請您吃飯。", archetype: "deflect", retort: "少討好我，先去讀書。" },
      { id: "sangu-salary_job-020-d", text: "考試我不太拿手，怕準備了也考不上……", archetype: "meek", retort: "不拿手就要更努力準備，別放棄。" },
      { id: "sangu-salary_job-020-e", text: "有考慮過，但要離開現在的工作有點怕……", archetype: "meek", retort: "怕歸怕，穩定的機會不多啊。" },
      { id: "sangu-salary_job-020-f", text: "鐵飯碗太無聊，我要當自由的靈魂。", archetype: "backfire", retort: "（三姑翻白眼，沒人接話）" },
      { id: "sangu-salary_job-020-g", text: "考公職？我這種人才進去太浪費了。", archetype: "backfire", retort: "……浪費？你現在也沒特別發光。" },
      { id: "sangu-salary_job-020-h", text: "考公職？先問您跟媳婦誰的鐵飯碗端得穩。", archetype: "landmine", retort: "（冷笑）你這是要翻臉？" },
    ],
  },
  {
    id: "sangu-salary_job-021",
    text: "大伯說你書讀那麼多，領這麼少喔。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-021-a", text: "讀書是為了選擇，不是為了聽這種酸話。", archetype: "perfect", retort: "……好，這句有深度，我記下了。" },
      { id: "sangu-salary_job-021-b", text: "大伯是不是又在轉政論台配這句？", archetype: "deflect", retort: "少提政論台，快回答正題。" },
      { id: "sangu-salary_job-021-c", text: "讀書換來的氣質，可比薪水值錢。", archetype: "deflect", retort: "貧嘴，氣質不能拿去繳房租。" },
      { id: "sangu-salary_job-021-d", text: "確實，學歷跟薪水沒有完全成正比……", archetype: "meek", retort: "沒成正比，那你要調整方向了。" },
      { id: "sangu-salary_job-021-e", text: "聽了心裡有點不是滋味，但也沒辦法反駁……", archetype: "meek", retort: "沒辦法反駁，就代表他說對了。" },
      { id: "sangu-salary_job-021-f", text: "讀書多是為了不用聽這種話啦。", archetype: "backfire", retort: "（三姑笑笑，沒人跟著附和）" },
      { id: "sangu-salary_job-021-g", text: "領少是因為我看淡金錢，境界高。", archetype: "backfire", retort: "……境界高到房租都快繳不出來。" },
      { id: "sangu-salary_job-021-h", text: "大伯酸我？先問問您紅包是不是也酸得小氣。", archetype: "landmine", retort: "（筷子一放）你這是找罵？" },
    ],
  },
  {
    id: "sangu-salary_job-022",
    text: "去幫我朋友的小孩家教，鐘點費不錯。",
    topic: "salary_job",
    bossId: "sangu",
    options: [
      { id: "sangu-salary_job-022-a", text: "好啊，順便讓那孩子見識，比您紅包實在。", archetype: "perfect", retort: "……好，會做人，隨我年輕時。" },
      { id: "sangu-salary_job-022-b", text: "鐘點費多少，姑姑先透露一下嘛。", archetype: "deflect", retort: "去了就知道，別討價還價。" },
      { id: "sangu-salary_job-022-c", text: "教學可以，但要先問是教哪一科。", archetype: "deflect", retort: "數學，你以前不是很行嗎。" },
      { id: "sangu-salary_job-022-d", text: "時間可能會有點卡，我要先確認一下……", archetype: "meek", retort: "確認什麼，賺外快的機會別浪費。" },
      { id: "sangu-salary_job-022-e", text: "可以試試看，只是我教學經驗不多……", archetype: "meek", retort: "經驗不多就要多練習，別怕生疏。" },
      { id: "sangu-salary_job-022-f", text: "家教而已，我大學時就是名師等級。", archetype: "backfire", retort: "（三姑笑笑，沒人相信這說法）" },
      { id: "sangu-salary_job-022-g", text: "鐘點費不錯，代表我的行情很高。", archetype: "backfire", retort: "……行情高，那你正職怎麼還是那樣。" },
      { id: "sangu-salary_job-022-h", text: "介紹家教，是不是想省一筆，跟紅包一樣小氣。", archetype: "landmine", retort: "（冷笑）你這是找罵？" },
    ],
  },
] satisfies Question[];
