import type { Question } from "@/content/types";

// situations: 002 煮湯逼你喝 / 003 塞水果盤 / 004 隔夜菜要你打包 / 005 逼你多吃一碗飯
// 006 圍爐火鍋加肉 / 007 早餐塞蛋餅飯糰 / 008 半夜留消夜 / 009 逼你喝雞精補湯
// 010 硬要餵到你嘴邊 / 011 逼你帶年糕粽子回家 / 012 塞零食糖果餅乾 / 013 說你太瘦要多吃肉
// 014 阻止你吃太少要求光盤 / 015 逼你喝甜湯圓 / 016 準備一堆菜怕你餓 / 017 硬要你外帶滷味菜尾
// 018 量你腰圍說你瘦了 / 019 摸你手臂說沒肉 / 020 逼你吃補品中藥 / 021 半夜起來煮宵夜給你
export default [
  {
    id: "ama-food_push-002",
    text: "喝湯喝湯，燉三小時，快趁熱喝。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-002-a", text: "阿嬤的湯我要喝兩碗，比補習班還補。", archetype: "perfect", retort: "哎唷，兩碗喔？阿嬤明天再燉！" },
      { id: "ama-food_push-002-b", text: "這湯這麼香，是不是加了秘方？", archetype: "deflect", retort: "猜對了，明年教你煮。" },
      { id: "ama-food_push-002-c", text: "阿嬤先喝，顧灶一整天也累了。", archetype: "deflect", retort: "阿嬤不累，你喝就好。" },
      { id: "ama-food_push-002-d", text: "我剛喝過飲料，有點脹……", archetype: "meek", retort: "飲料哪有湯營養，快喝！" },
      { id: "ama-food_push-002-e", text: "湯太燙，我等一下喝……", archetype: "meek", retort: "等什麼等，涼了更難喝！" },
      { id: "ama-food_push-002-f", text: "這湯該不會是青春の泉源吧。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盛湯）" },
      { id: "ama-food_push-002-g", text: "我怕喝太多會變成湯圓。", archetype: "backfire", retort: "（阿嬤皺眉，還是盛給你）" },
      { id: "ama-food_push-002-h", text: "阿嬤不要一直逼我喝好不好。", archetype: "landmine", retort: "……好，阿嬤不逼你了。" },
    ],
  },
  {
    id: "ama-food_push-003",
    text: "吃塊西瓜，阿嬤特地切好等你。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-003-a", text: "阿嬤切的西瓜，比蜜還甜。", archetype: "perfect", retort: "哎唷，甜是因為疼你啦。" },
      { id: "ama-food_push-003-b", text: "阿嬤自己也要吃，不要都給我。", archetype: "deflect", retort: "我吃過了，你多吃點。" },
      { id: "ama-food_push-003-c", text: "阿嬤刀工這麼好，教教我切。", archetype: "deflect", retort: "好啊，明天教你切西瓜。" },
      { id: "ama-food_push-003-d", text: "剛吃飽，肚子真的塞不下……", archetype: "meek", retort: "塞得下啦，水果不算胃！" },
      { id: "ama-food_push-003-e", text: "我不太敢吃冰的水果……", archetype: "meek", retort: "那阿嬤幫你放常溫再吃。" },
      { id: "ama-food_push-003-f", text: "西瓜配湯，我要變成瓜湯人。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續切）" },
      { id: "ama-food_push-003-g", text: "吃水果減肥，阿嬤別擔心我。", archetype: "backfire", retort: "（阿嬤哪有在聽，繼續遞）" },
      { id: "ama-food_push-003-h", text: "一直塞水果很煩，先放著啦。", archetype: "landmine", retort: "……好，阿嬤放著就好。" },
    ],
  },
  {
    id: "ama-food_push-004",
    text: "這些菜幫你打包，帶回去吃。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-004-a", text: "阿嬤的菜，我吃三天都不膩。", archetype: "perfect", retort: "三天喔？阿嬤明天再炒！" },
      { id: "ama-food_push-004-b", text: "阿嬤留一點自己吃，不要都給我。", archetype: "deflect", retort: "我吃不完啦，你拿去。" },
      { id: "ama-food_push-004-c", text: "阿嬤的手藝，外面餐廳比不上。", archetype: "deflect", retort: "哎唷，就是家常菜而已。" },
      { id: "ama-food_push-004-d", text: "我冰箱已經滿了，裝不下……", archetype: "meek", retort: "那擠一擠，總會有地方！" },
      { id: "ama-food_push-004-e", text: "我最近都叫外送，很少開伙……", archetype: "meek", retort: "開什麼外送，這比較省！" },
      { id: "ama-food_push-004-f", text: "我行李箱都是菜，海關會查。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續裝）" },
      { id: "ama-food_push-004-g", text: "我要開一間阿嬤菜快閃店。", archetype: "backfire", retort: "（阿嬤白眼，繼續打包）" },
      { id: "ama-food_push-004-h", text: "不要再打包了，我真的拿不動。", archetype: "landmine", retort: "……好，阿嬤不裝了。" },
    ],
  },
  {
    id: "ama-food_push-005",
    text: "飯再添一碗，配菜還有一大盤。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-005-a", text: "阿嬤煮的飯，我可以吃三碗。", archetype: "perfect", retort: "三碗！阿嬤明天煮更多！" },
      { id: "ama-food_push-005-b", text: "阿嬤自己也要吃飽，先坐下。", archetype: "deflect", retort: "好啦好啦，我也吃一點。" },
      { id: "ama-food_push-005-c", text: "這飯配你炒的菜，剛剛好。", archetype: "deflect", retort: "對嘛，這樣才吃得下。" },
      { id: "ama-food_push-005-d", text: "一碗真的是我的極限了……", archetype: "meek", retort: "極限太低，要多練習！" },
      { id: "ama-food_push-005-e", text: "晚點還要幫忙洗碗，先這樣……", archetype: "meek", retort: "洗碗不急，先吃飽再說！" },
      { id: "ama-food_push-005-f", text: "再吃我要滾著回台北了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續添）" },
      { id: "ama-food_push-005-g", text: "我在練習大胃王比賽。", archetype: "backfire", retort: "（阿嬤半信半疑地看你）" },
      { id: "ama-food_push-005-h", text: "夠了啦，不要一直叫我吃。", archetype: "landmine", retort: "……好，阿嬤不叫了。" },
    ],
  },
  {
    id: "ama-food_push-006",
    text: "火鍋肉再下，多吃一點才夠力。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-006-a", text: "阿嬤下的肉，比火鍋店還大方。", archetype: "perfect", retort: "哎唷，大方是因為疼你！" },
      { id: "ama-food_push-006-b", text: "阿嬤先吃，煮一整天也辛苦了。", archetype: "deflect", retort: "好啦，我也夾一塊。" },
      { id: "ama-food_push-006-c", text: "這肉這麼嫩，哪裡買的？", archetype: "deflect", retort: "老市場那攤，明年帶你去。" },
      { id: "ama-food_push-006-d", text: "我怕火鍋吃太多會脹氣……", archetype: "meek", retort: "脹氣就多喝點湯化一下！" },
      { id: "ama-food_push-006-e", text: "我剛剛已經吃兩盤了……", archetype: "meek", retort: "才兩盤，火鍋要吃五盤！" },
      { id: "ama-food_push-006-f", text: "再吃我要變火鍋料了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續下肉）" },
      { id: "ama-food_push-006-g", text: "阿嬤這是要養我過冬嗎。", archetype: "backfire", retort: "（阿嬤笑而不語，繼續夾）" },
      { id: "ama-food_push-006-h", text: "不要再夾了，我吃不下了啦。", archetype: "landmine", retort: "……好，阿嬤不夾了。" },
    ],
  },
  {
    id: "ama-food_push-007",
    text: "早餐吃這個，蛋餅飯糰都有。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-007-a", text: "阿嬤做的早餐，比早餐店厲害。", archetype: "perfect", retort: "哎唷，早餐店哪有這麼多愛。" },
      { id: "ama-food_push-007-b", text: "阿嬤怎麼這麼早就起來準備？", archetype: "deflect", retort: "疼孫子，幾點起來都甘願。" },
      { id: "ama-food_push-007-c", text: "這蛋餅皮，阿嬤自己桿的吧？", archetype: "deflect", retort: "當然，機器做的哪有這味。" },
      { id: "ama-food_push-007-d", text: "我平常早餐都不太吃……", archetype: "meek", retort: "不吃怎麼行，會傷胃的！" },
      { id: "ama-food_push-007-e", text: "兩種一起吃有點太多了……", archetype: "meek", retort: "都吃才有力氣，快動筷！" },
      { id: "ama-food_push-007-f", text: "我要開分店賣阿嬤早餐。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞）" },
      { id: "ama-food_push-007-g", text: "吃完我要去跑半馬。", archetype: "backfire", retort: "（阿嬤懷疑地看著你）" },
      { id: "ama-food_push-007-h", text: "一大早不要塞這麼多啦。", archetype: "landmine", retort: "……好，阿嬤少準備點。" },
    ],
  },
  {
    id: "ama-food_push-008",
    text: "半夜肚子餓吧，阿嬤留了消夜。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-008-a", text: "阿嬤的消夜，比宵夜街還香。", archetype: "perfect", retort: "哎唷，你嘴巴真的很甜。" },
      { id: "ama-food_push-008-b", text: "阿嬤這麼晚還沒睡，快去休息。", archetype: "deflect", retort: "等你吃完，阿嬤才安心睡。" },
      { id: "ama-food_push-008-c", text: "這麼晚還留菜，阿嬤太寵我了。", archetype: "deflect", retort: "誰叫你是阿嬤的心肝寶貝。" },
      { id: "ama-food_push-008-d", text: "剛剛才吃飽，現在真的吃不下……", archetype: "meek", retort: "消夜跟正餐不一樣，快吃！" },
      { id: "ama-food_push-008-e", text: "我怕吃了睡不著……", archetype: "meek", retort: "吃一點點不會怎樣啦！" },
      { id: "ama-food_push-008-f", text: "消夜配月光，浪漫又發胖。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續端）" },
      { id: "ama-food_push-008-g", text: "我要開始練半夜進食法。", archetype: "backfire", retort: "（阿嬤一臉問號，還是端來）" },
      { id: "ama-food_push-008-h", text: "不要每次都留消夜等我啦。", archetype: "landmine", retort: "……好，以後不留了。" },
    ],
  },
  {
    id: "ama-food_push-009",
    text: "這罐雞精喝一下，補補元氣。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-009-a", text: "阿嬤給的補品，比雞精廣告有效。", archetype: "perfect", retort: "哎唷，你這張嘴真會講。" },
      { id: "ama-food_push-009-b", text: "阿嬤自己也要補，不要都省給我。", archetype: "deflect", retort: "我身體硬朗，你多喝點。" },
      { id: "ama-food_push-009-c", text: "這牌子是不是阿嬤研究很久的？", archetype: "deflect", retort: "當然，貨比三家才買的。" },
      { id: "ama-food_push-009-d", text: "我剛吃過飯，現在喝不下……", archetype: "meek", retort: "喝不下也要喝一點意思一下！" },
      { id: "ama-food_push-009-e", text: "我平常沒有在喝這個習慣……", archetype: "meek", retort: "沒喝過才更要試試看！" },
      { id: "ama-food_push-009-f", text: "喝完我應該能舉起餐桌吧。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞）" },
      { id: "ama-food_push-009-g", text: "這是不是傳說中的補品之王。", archetype: "backfire", retort: "（阿嬤點頭，其實聽不懂）" },
      { id: "ama-food_push-009-h", text: "不用一直補啦，我很健康。", archetype: "landmine", retort: "……好，阿嬤不逼你了。" },
    ],
  },
  {
    id: "ama-food_push-010",
    text: "嘴巴張開，阿嬤餵你吃這口。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-010-a", text: "阿嬤餵的這口，比米其林還珍貴。", archetype: "perfect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-food_push-010-b", text: "阿嬤自己也要吃，換我餵你好嗎？", archetype: "deflect", retort: "不用不用，你張嘴就好。" },
      { id: "ama-food_push-010-c", text: "我都幾歲了，阿嬤還這樣寵。", archetype: "deflect", retort: "在阿嬤心裡你永遠是小孩。" },
      { id: "ama-food_push-010-d", text: "我自己會吃，有點不好意思……", archetype: "meek", retort: "不好意思什麼，張嘴就對了！" },
      { id: "ama-food_push-010-e", text: "我嘴巴裡還有東西沒吞……", archetype: "meek", retort: "那快吞一吞，這口更好吃！" },
      { id: "ama-food_push-010-f", text: "這樣餵我會被說媽寶。", archetype: "backfire", retort: "（阿嬤沒聽懂，直接餵下去）" },
      { id: "ama-food_push-010-g", text: "我要拍照發限動記錄這刻。", archetype: "backfire", retort: "（阿嬤已經把菜塞進你嘴）" },
      { id: "ama-food_push-010-h", text: "我不是小孩了，不用一直餵。", archetype: "landmine", retort: "……好，阿嬤不餵了。" },
    ],
  },
  {
    id: "ama-food_push-011",
    text: "這些年糕帶走，路上肚子餓吃。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-011-a", text: "阿嬤包的年糕，帶著能保平安。", archetype: "perfect", retort: "哎唷，這句話說得阿嬤開心。" },
      { id: "ama-food_push-011-b", text: "阿嬤留一點自己吃，不要都給我。", archetype: "deflect", retort: "我吃不了那麼多，你拿去。" },
      { id: "ama-food_push-011-c", text: "這年糕的味道，跟小時候一樣。", archetype: "deflect", retort: "配方都沒變過，安心吃。" },
      { id: "ama-food_push-011-d", text: "我行李已經很滿了，裝不下……", archetype: "meek", retort: "裝不下就用手提著走！" },
      { id: "ama-food_push-011-e", text: "我不太會吃年糕，怕噎到……", archetype: "meek", retort: "慢慢吃就不會噎，別怕！" },
      { id: "ama-food_push-011-f", text: "我把年糕當啞鈴練二頭肌。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續打包）" },
      { id: "ama-food_push-011-g", text: "年糕吃多會不會變成年獸。", archetype: "backfire", retort: "（阿嬤白眼，還是塞進袋子）" },
      { id: "ama-food_push-011-h", text: "不要再塞了，行李真的滿了。", archetype: "landmine", retort: "……好，阿嬤少裝一點。" },
    ],
  },
  {
    id: "ama-food_push-012",
    text: "口袋裝滿糖果，路上肚子餓吃。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-012-a", text: "阿嬤給的糖，比拜年更甜。", archetype: "perfect", retort: "哎唷，甜嘴巴，再抓一把！" },
      { id: "ama-food_push-012-b", text: "阿嬤自己也留一點吃甜的。", archetype: "deflect", retort: "阿嬤年紀大不能吃太甜。" },
      { id: "ama-food_push-012-c", text: "這糖果罐，是不是每年都換新的？", archetype: "deflect", retort: "當然，過年就是要新的。" },
      { id: "ama-food_push-012-d", text: "口袋已經塞不下了啦……", archetype: "meek", retort: "塞不下就用袋子裝著！" },
      { id: "ama-food_push-012-e", text: "我最近在少吃甜的……", archetype: "meek", retort: "過年不忌口，吃一顆而已！" },
      { id: "ama-food_push-012-f", text: "這樣我糖尿病都要來拜年了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續塞）" },
      { id: "ama-food_push-012-g", text: "我要開一間糖果批發店。", archetype: "backfire", retort: "（阿嬤笑笑，繼續往口袋塞）" },
      { id: "ama-food_push-012-h", text: "夠了啦，不要一直塞東西。", archetype: "landmine", retort: "……好，阿嬤不塞了。" },
    ],
  },
  {
    id: "ama-food_push-013",
    text: "你怎麼瘦成這樣，多吃點肉。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-013-a", text: "阿嬤放心，我這叫精實不是瘦。", archetype: "perfect", retort: "哎唷，精實也要多吃肉補一下。" },
      { id: "ama-food_push-013-b", text: "阿嬤把肉都省給我，自己要吃。", archetype: "deflect", retort: "我吃老了不缺這個，你多吃。" },
      { id: "ama-food_push-013-c", text: "阿嬤煮的肉，吃了才有你的手藝。", archetype: "deflect", retort: "哎唷，就是簡單紅燒而已。" },
      { id: "ama-food_push-013-d", text: "我最近工作太忙，沒好好吃飯……", archetype: "meek", retort: "沒好好吃飯，聽了阿嬤心疼。" },
      { id: "ama-food_push-013-e", text: "我天生就是吃不胖的體質……", archetype: "meek", retort: "那更要多吃，把肉補回來！" },
      { id: "ama-food_push-013-f", text: "瘦是為了在健身房拍照好看。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續夾肉）" },
      { id: "ama-food_push-013-g", text: "我是走仙氣飄飄路線的。", archetype: "backfire", retort: "（阿嬤皺眉，硬是塞了一塊）" },
      { id: "ama-food_push-013-h", text: "我瘦不瘦不用你管好不好。", archetype: "landmine", retort: "……好，阿嬤不說了。" },
    ],
  },
  {
    id: "ama-food_push-014",
    text: "盤子還有菜，怎麼可以不吃完。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-014-a", text: "阿嬤煮的菜，我捨不得留一口。", archetype: "perfect", retort: "哎唷，這句話比菜還好吃。" },
      { id: "ama-food_push-014-b", text: "阿嬤煮太多了，明天再吃一次。", archetype: "deflect", retort: "對嘛，剩菜隔天更入味。" },
      { id: "ama-food_push-014-c", text: "阿嬤先吃完自己那份，我陪你。", archetype: "deflect", retort: "好，阿嬤陪你一起吃完。" },
      { id: "ama-food_push-014-d", text: "我真的已經吃很飽了，塞不下……", archetype: "meek", retort: "塞不下也不能浪費，加油！" },
      { id: "ama-food_push-014-e", text: "這道菜我不太敢吃辣的……", archetype: "meek", retort: "早說嘛，阿嬤幫你挑掉辣的！" },
      { id: "ama-food_push-014-f", text: "光盤行動我要拿獎狀。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續看你盤子）" },
      { id: "ama-food_push-014-g", text: "吃完這盤我要獲頒美食勳章。", archetype: "backfire", retort: "（阿嬤半信半疑地點頭）" },
      { id: "ama-food_push-014-h", text: "吃不完就吃不完，不要逼我。", archetype: "landmine", retort: "……好，阿嬤不逼你了。" },
    ],
  },
  {
    id: "ama-food_push-015",
    text: "湯圓煮好了，甜甜的吃一碗。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-015-a", text: "阿嬤搓的湯圓，比圓仔還圓滿。", archetype: "perfect", retort: "哎唷，圓滿最重要，多吃一顆！" },
      { id: "ama-food_push-015-b", text: "阿嬤搓湯圓的手藝，全村都知道。", archetype: "deflect", retort: "哎唷，過獎過獎，快吃。" },
      { id: "ama-food_push-015-c", text: "阿嬤自己也要吃一碗，別省。", archetype: "deflect", retort: "好啦，阿嬤也吃一顆。" },
      { id: "ama-food_push-015-d", text: "我不太敢吃太甜的東西……", archetype: "meek", retort: "湯圓甜才吉利，吃一點！" },
      { id: "ama-food_push-015-e", text: "剛剛喝了湯，肚子有點滿……", archetype: "meek", retort: "滿也要留位置給湯圓！" },
      { id: "ama-food_push-015-f", text: "吃湯圓會不會越吃越圓。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盛）" },
      { id: "ama-food_push-015-g", text: "我要靠湯圓練成大力士。", archetype: "backfire", retort: "（阿嬤笑笑，多舀一顆）" },
      { id: "ama-food_push-015-h", text: "不要再逼我吃甜的了啦。", archetype: "landmine", retort: "……好，阿嬤不煮了。" },
    ],
  },
  {
    id: "ama-food_push-016",
    text: "怕你餓，阿嬤多煮了五道菜。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-016-a", text: "阿嬤煮的菜，五道都吃得完。", archetype: "perfect", retort: "哎唷，五道都吃光，阿嬤高興！" },
      { id: "ama-food_push-016-b", text: "阿嬤別太累，下次煮少一點。", archetype: "deflect", retort: "不會累，看你吃就開心。" },
      { id: "ama-food_push-016-c", text: "這五道菜，是不是每道都有故事？", archetype: "deflect", retort: "每一道都是阿嬤的拿手菜。" },
      { id: "ama-food_push-016-d", text: "五道菜真的吃不完，太多了……", archetype: "meek", retort: "吃不完打包，總之要吃！" },
      { id: "ama-food_push-016-e", text: "我平常食量沒有很大……", archetype: "meek", retort: "過年不比平常，要多吃！" },
      { id: "ama-food_push-016-f", text: "我要辦一場阿嬤菜品鑑會。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續上菜）" },
      { id: "ama-food_push-016-g", text: "吃完這些我要休息三天。", archetype: "backfire", retort: "（阿嬤笑笑，端出第六道菜）" },
      { id: "ama-food_push-016-h", text: "不用煮這麼多啦，很浪費。", archetype: "landmine", retort: "……好，阿嬤少煮一點。" },
    ],
  },
  {
    id: "ama-food_push-017",
    text: "這鍋菜尾打包，帶去公司吃。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-017-a", text: "阿嬤的菜尾，公司同事都搶著問。", archetype: "perfect", retort: "哎唷，那明年多滷一點給你。" },
      { id: "ama-food_push-017-b", text: "阿嬤留一點自己配飯吃。", archetype: "deflect", retort: "我這老骨頭吃不了那麼多。" },
      { id: "ama-food_push-017-c", text: "這滷味的味道，比店裡還道地。", archetype: "deflect", retort: "那當然，都是老功夫。" },
      { id: "ama-food_push-017-d", text: "公司冰箱位置不夠放……", archetype: "meek", retort: "那你今天先吃一點帶走！" },
      { id: "ama-food_push-017-e", text: "我中午都在外面吃，用不到……", archetype: "meek", retort: "用不到也要嚐嚐阿嬤的手藝！" },
      { id: "ama-food_push-017-f", text: "我要開一台滷味餐車創業。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續裝袋）" },
      { id: "ama-food_push-017-g", text: "同事聞到味道會以為我開店。", archetype: "backfire", retort: "（阿嬤笑笑，多裝了一份）" },
      { id: "ama-food_push-017-h", text: "不要再打包了，帶不動啦。", archetype: "landmine", retort: "……好，阿嬤少裝一點。" },
    ],
  },
  {
    id: "ama-food_push-018",
    text: "來，阿嬤量一下，你腰變細了。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-018-a", text: "阿嬤量的不是腰，是想我的心。", archetype: "perfect", retort: "哎唷，你這張嘴，會讓阿嬤哭。" },
      { id: "ama-food_push-018-b", text: "阿嬤量腰這麼準，可以去開店。", archetype: "deflect", retort: "哎唷，量孫子的腰最準啦。" },
      { id: "ama-food_push-018-c", text: "阿嬤自己身體硬朗最重要。", archetype: "deflect", retort: "阿嬤好得很，不用擔心。" },
      { id: "ama-food_push-018-d", text: "最近工作太忙，吃得比較少……", archetype: "meek", retort: "吃得少怎麼行，要顧身體！" },
      { id: "ama-food_push-018-e", text: "可能是最近運動比較多……", archetype: "meek", retort: "運動歸運動，飯還是要吃！" },
      { id: "ama-food_push-018-f", text: "這叫科學驗證的健身成果。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續量）" },
      { id: "ama-food_push-018-g", text: "我要去報名瘦身比賽了。", archetype: "backfire", retort: "（阿嬤半信半疑地看著你）" },
      { id: "ama-food_push-018-h", text: "不要量了啦，很奇怪耶。", archetype: "landmine", retort: "……好，阿嬤不量了。" },
    ],
  },
  {
    id: "ama-food_push-019",
    text: "摸摸你手臂，怎麼都沒肉了。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-019-a", text: "阿嬤一摸就知道，我是來蓄電的。", archetype: "perfect", retort: "哎唷，蓄什麼電，先吃飯啦！" },
      { id: "ama-food_push-019-b", text: "阿嬤的手，摸起來還是這麼溫暖。", archetype: "deflect", retort: "哎唷，這孩子嘴巴真甜。" },
      { id: "ama-food_push-019-c", text: "阿嬤自己的手也要保重，別太操勞。", archetype: "deflect", retort: "沒事沒事，阿嬤硬朗得很。" },
      { id: "ama-food_push-019-d", text: "最近確實比較少運動吃飯不定時……", archetype: "meek", retort: "不定時怎麼行，快改回來！" },
      { id: "ama-food_push-019-e", text: "工作壓力大，胃口比較差……", archetype: "meek", retort: "壓力大更要吃飽才有力氣！" },
      { id: "ama-food_push-019-f", text: "沒肉才能穿得下去年的褲子。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續捏你手）" },
      { id: "ama-food_push-019-g", text: "我在存肉，準備過年一次長回來。", archetype: "backfire", retort: "（阿嬤笑笑，夾了一塊肉）" },
      { id: "ama-food_push-019-h", text: "不要一直捏啦，很煩耶。", archetype: "landmine", retort: "……好，阿嬤不捏了。" },
    ],
  },
  {
    id: "ama-food_push-020",
    text: "這帖藥燉的，喝了對身體好。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-020-a", text: "阿嬤燉的藥，比健康食品有效。", archetype: "perfect", retort: "哎唷，有效是因為有阿嬤的愛。" },
      { id: "ama-food_push-020-b", text: "阿嬤自己也要喝一碗補一補。", archetype: "deflect", retort: "好啦，阿嬤也陪你喝一口。" },
      { id: "ama-food_push-020-c", text: "這帖藥聞起來，是不是加了紅棗？", archetype: "deflect", retort: "對，紅棗枸杞都加了。" },
      { id: "ama-food_push-020-d", text: "這個味道我實在有點怕……", archetype: "meek", retort: "怕什麼，喝了才知道好喝！" },
      { id: "ama-food_push-020-e", text: "我平常都靠睡覺調養，沒喝這個……", archetype: "meek", retort: "睡覺不夠，還是要靠這帖！" },
      { id: "ama-food_push-020-f", text: "喝完我應該能刀槍不入了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞碗）" },
      { id: "ama-food_push-020-g", text: "這是不是傳說中的還魂湯。", archetype: "backfire", retort: "（阿嬤白眼，硬塞給你）" },
      { id: "ama-food_push-020-h", text: "不用喝這些啦，我很好。", archetype: "landmine", retort: "……好，阿嬤不逼你了。" },
    ],
  },
  {
    id: "ama-food_push-021",
    text: "你剛下班，阿嬤現煮碗麵給你。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-021-a", text: "阿嬤半夜煮的麵，比米其林更用心。", archetype: "perfect", retort: "哎唷，你這孩子最會說話了。" },
      { id: "ama-food_push-021-b", text: "這麼晚阿嬤還沒睡，快去休息。", archetype: "deflect", retort: "看你吃完，阿嬤才能睡好。" },
      { id: "ama-food_push-021-c", text: "阿嬤煮麵的手藝，從沒退步過。", archetype: "deflect", retort: "那當然，這是阿嬤的招牌。" },
      { id: "ama-food_push-021-d", text: "我剛剛在外面吃過消夜了……", archetype: "meek", retort: "吃過也要再吃一點，這是麵！" },
      { id: "ama-food_push-021-e", text: "現在太晚了，吃了怕睡不著……", archetype: "meek", retort: "吃碗麵不會怎樣，快趁熱！" },
      { id: "ama-food_push-021-f", text: "這樣我要變成宵夜界的傳說了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續下麵）" },
      { id: "ama-food_push-021-g", text: "我這是深夜特別加碼行程。", archetype: "backfire", retort: "（阿嬤笑笑，端出麵碗）" },
      { id: "ama-food_push-021-h", text: "不要每次熬夜等我煮東西啦。", archetype: "landmine", retort: "……好，以後不等了。" },
    ],
  },
] satisfies Question[];
