import type { Question } from "@/content/types";

// situations: 022 逼你喝薑母茶驅寒 / 023 拜拜供品分你吃 / 024 大掃除後留一桌菜等你回來
// 025 你剛到家門口就被拉去吃飯 / 026 逼你吃她醃的菜脯菜心 / 027 硬要你吃剩年夜飯當早餐
// 028 逼你吃她包的水餃 / 029 逼你嚐她新學的菜色 / 030 硬塞一大包瓜子花生
// 031 逼你嚐剛炸好的芋頭酥 / 032 逼你喝四物轉骨湯 / 033 你在滑手機她硬塞餅乾
// 034 逼你吃她泡的酸梅蜜餞 / 035 逼你多吃一顆滷蛋 / 036 你要出門她硬塞一顆包子
// 037 你說要走她硬留你多吃一輪水果
export default [
  {
    id: "ama-food_push-022",
    text: "天氣冷，喝碗薑母茶暖暖身。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-022-a", text: "阿嬤煮的薑母茶，比暖爐還暖。", archetype: "perfect", retort: "哎唷，暖爐哪有阿嬤貼心。" },
      { id: "ama-food_push-022-b", text: "阿嬤自己也要喝，別都留給我。", archetype: "deflect", retort: "我不怕冷，你多喝點。" },
      { id: "ama-food_push-022-c", text: "這薑母茶的比例，是不是傳家配方？", archetype: "deflect", retort: "沒錯，這可是祖傳的。" },
      { id: "ama-food_push-022-d", text: "我不太怕冷，可能等一下再喝……", archetype: "meek", retort: "現在喝才有效，快趁熱！" },
      { id: "ama-food_push-022-e", text: "我對薑的味道比較敏感……", archetype: "meek", retort: "加點糖就不辣，喝喝看！" },
      { id: "ama-food_push-022-f", text: "喝完我應該能自體發熱過冬。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續倒）" },
      { id: "ama-food_push-022-g", text: "這是不是武功祕笈裡的內力湯。", archetype: "backfire", retort: "（阿嬤笑笑，遞給你碗）" },
      { id: "ama-food_push-022-h", text: "不用一直逼我喝薑茶啦。", archetype: "landmine", retort: "……好，阿嬤不煮了。" },
    ],
  },
  {
    id: "ama-food_push-023",
    text: "拜拜的水果，分你吃保平安。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-023-a", text: "阿嬤拜的水果，吃了整年都順。", archetype: "perfect", retort: "哎唷，順的是阿嬤的心意。" },
      { id: "ama-food_push-023-b", text: "阿嬤自己也吃一點，神明不介意。", archetype: "deflect", retort: "好啦，阿嬤也吃一顆。" },
      { id: "ama-food_push-023-c", text: "這水果擺得這麼漂亮，捨不得吃。", archetype: "deflect", retort: "擺好看是為了拜，吃了才對。" },
      { id: "ama-food_push-023-d", text: "我剛剛已經吃過水果了……", archetype: "meek", retort: "供品不一樣，要再吃一點！" },
      { id: "ama-food_push-023-e", text: "我對這種蘋果有點不敢吃……", archetype: "meek", retort: "削皮就好，阿嬤幫你削！" },
      { id: "ama-food_push-023-f", text: "吃了供品是不是能加持好運。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續分你）" },
      { id: "ama-food_push-023-g", text: "我要把籽留著種發財樹。", archetype: "backfire", retort: "（阿嬤白眼，塞給你一顆）" },
      { id: "ama-food_push-023-h", text: "供品的東西不用特別給我吃。", archetype: "landmine", retort: "……好，阿嬤自己收了。" },
    ],
  },
  {
    id: "ama-food_push-024",
    text: "掃完全家累了吧，阿嬤留飯菜。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-024-a", text: "阿嬤煮的犒賞飯，比加班費實在。", archetype: "perfect", retort: "哎唷，你這孩子最貼心。" },
      { id: "ama-food_push-024-b", text: "阿嬤才是真的辛苦，先坐下吃。", archetype: "deflect", retort: "坐一下就好，你多吃點。" },
      { id: "ama-food_push-024-c", text: "大掃除的功勞都是阿嬤指揮有方。", archetype: "deflect", retort: "哎唷，我只是動動嘴。" },
      { id: "ama-food_push-024-d", text: "掃完好累，只想先躺一下……", archetype: "meek", retort: "躺什麼躺，吃飽再躺！" },
      { id: "ama-food_push-024-e", text: "手都痠了，拿筷子有點吃力……", archetype: "meek", retort: "那阿嬤餵你，別客氣！" },
      { id: "ama-food_push-024-f", text: "掃地掃到可以出道當清潔專家。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盛飯）" },
      { id: "ama-food_push-024-g", text: "我這雙手已經是職業級抹布手。", archetype: "backfire", retort: "（阿嬤笑笑，端上一碗湯）" },
      { id: "ama-food_push-024-h", text: "不用特地留飯，我不餓啦。", archetype: "landmine", retort: "……好，阿嬤收起來了。" },
    ],
  },
  {
    id: "ama-food_push-025",
    text: "才剛到門口，先進來吃飯再說。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-025-a", text: "阿嬤在等我吃飯，比高鐵準點。", archetype: "perfect", retort: "哎唷，你這張嘴真討喜。" },
      { id: "ama-food_push-025-b", text: "阿嬤等這麼久，辛苦你了。", archetype: "deflect", retort: "等你回來，阿嬤都不累。" },
      { id: "ama-food_push-025-c", text: "這家的味道，一進門就聞到了。", archetype: "deflect", retort: "那當然，這是家的味道。" },
      { id: "ama-food_push-025-d", text: "我行李都還沒放好，等一下……", archetype: "meek", retort: "行李等等放，先吃再說！" },
      { id: "ama-food_push-025-e", text: "我在高鐵上吃過東西了……", archetype: "meek", retort: "高鐵上的哪算吃飯，快坐下！" },
      { id: "ama-food_push-025-f", text: "我這是限時到貨的孫子快遞。", archetype: "backfire", retort: "（阿嬤沒聽懂，拉你坐下）" },
      { id: "ama-food_push-025-g", text: "一進門就開飯，效率驚人。", archetype: "backfire", retort: "（阿嬤笑笑，端出第一道菜）" },
      { id: "ama-food_push-025-h", text: "讓我先喘口氣，不用馬上吃。", archetype: "landmine", retort: "……好，阿嬤等你一下。" },
    ],
  },
  {
    id: "ama-food_push-026",
    text: "這是我醃的菜脯，配粥剛剛好。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-026-a", text: "阿嬤醃的菜脯，比任何名產都香。", archetype: "perfect", retort: "哎唷，這句話比菜脯還甜。" },
      { id: "ama-food_push-026-b", text: "阿嬤醃這罐花了多少功夫啊。", archetype: "deflect", retort: "曬了半個月才醃成的。" },
      { id: "ama-food_push-026-c", text: "這配粥的組合，是阿嬤發明的吧。", archetype: "deflect", retort: "當然，這是阿嬤的獨門搭配。" },
      { id: "ama-food_push-026-d", text: "我平常粥吃得少，怕吃不慣……", archetype: "meek", retort: "吃慣了就會愛上，嚐嚐看！" },
      { id: "ama-food_push-026-e", text: "這個有點鹹，我怕血壓……", archetype: "meek", retort: "一點點不會怎樣，配粥剛好！" },
      { id: "ama-food_push-026-f", text: "吃完我應該能長命百歲了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續夾）" },
      { id: "ama-food_push-026-g", text: "這罐可以拿去申請文化遺產。", archetype: "backfire", retort: "（阿嬤笑笑，多夾一筷）" },
      { id: "ama-food_push-026-h", text: "這個太鹹了，不要一直夾。", archetype: "landmine", retort: "……好，阿嬤不夾了。" },
    ],
  },
  {
    id: "ama-food_push-027",
    text: "早上沒別的，年夜飯剩菜配飯。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-027-a", text: "阿嬤的隔夜菜，比熱炒店還讚。", archetype: "perfect", retort: "哎唷，隔夜也不能亂稱讚喔。" },
      { id: "ama-food_push-027-b", text: "阿嬤自己也吃一點剩菜吧。", archetype: "deflect", retort: "我年紀大吃不了那麼多。" },
      { id: "ama-food_push-027-c", text: "年夜飯隔天吃，是不是更入味？", archetype: "deflect", retort: "沒錯，隔夜的滋味更濃。" },
      { id: "ama-food_push-027-d", text: "早上通常都吃得比較清淡……", archetype: "meek", retort: "清淡哪夠力，多吃一點！" },
      { id: "ama-food_push-027-e", text: "這幾道我昨天已經吃很多了……", archetype: "meek", retort: "剩菜不能浪費，再吃一點！" },
      { id: "ama-food_push-027-f", text: "早餐吃年夜飯，過年感加倍。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盛）" },
      { id: "ama-food_push-027-g", text: "這樣我等於天天都在圍爐。", archetype: "backfire", retort: "（阿嬤笑笑，端出第二盤）" },
      { id: "ama-food_push-027-h", text: "早上不要吃這麼油的東西啦。", archetype: "landmine", retort: "……好，阿嬤煮清淡點。" },
    ],
  },
  {
    id: "ama-food_push-028",
    text: "剛包好的水餃，快來吃幾顆。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-028-a", text: "阿嬤包的水餃，一口氣能吃二十顆。", archetype: "perfect", retort: "二十顆！阿嬤明天多包一點！" },
      { id: "ama-food_push-028-b", text: "阿嬤包水餃的速度，比店家還快。", archetype: "deflect", retort: "哎唷，包了一輩子當然快。" },
      { id: "ama-food_push-028-c", text: "這餡料的比例，是不是家傳的？", archetype: "deflect", retort: "當然，這配方傳了三代。" },
      { id: "ama-food_push-028-d", text: "剛吃了不少，水餃先吃幾顆就好……", archetype: "meek", retort: "幾顆哪夠，多吃幾顆才夠力！" },
      { id: "ama-food_push-028-e", text: "我最近在少吃澱粉……", archetype: "meek", retort: "水餃是團圓的，破例吃一點！" },
      { id: "ama-food_push-028-f", text: "吃完我要開一間水餃連鎖店。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續煮）" },
      { id: "ama-food_push-028-g", text: "我這胃已經升級成水餃倉庫。", archetype: "backfire", retort: "（阿嬤笑笑，又下一鍋）" },
      { id: "ama-food_push-028-h", text: "不要一直煮了，吃不完啦。", archetype: "landmine", retort: "……好，阿嬤先不煮了。" },
    ],
  },
  {
    id: "ama-food_push-029",
    text: "這道新菜，阿嬤跟人學的，嚐嚐。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-029-a", text: "阿嬤學的新菜，直接可以開餐廳。", archetype: "perfect", retort: "哎唷，開什麼餐廳，你嚐就好。" },
      { id: "ama-food_push-029-b", text: "阿嬤還在學新菜，真的太厲害了。", archetype: "deflect", retort: "活到老學到老嘛，多吃點。" },
      { id: "ama-food_push-029-c", text: "這道菜跟誰學的？我也想學。", archetype: "deflect", retort: "跟廟口張阿姨學的，改天教你。" },
      { id: "ama-food_push-029-d", text: "我今天吃得有點多，先吃一小口……", archetype: "meek", retort: "一小口哪夠，多吃幾口試試！" },
      { id: "ama-food_push-029-e", text: "我不太確定自己敢不敢吃新菜……", archetype: "meek", retort: "不試怎麼知道，阿嬤陪你吃！" },
      { id: "ama-food_push-029-f", text: "這道菜我要打五星好評。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續問好不好吃）" },
      { id: "ama-food_push-029-g", text: "我覺得可以拿去參加廚藝大賽。", archetype: "backfire", retort: "（阿嬤有點得意，又夾一口）" },
      { id: "ama-food_push-029-h", text: "新菜就不要一直逼我吃了。", archetype: "landmine", retort: "……好，阿嬤知道了。" },
    ],
  },
  {
    id: "ama-food_push-030",
    text: "電視前配瓜子花生，一起看春晚。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-030-a", text: "阿嬤炒的花生，比電影院爆米花香。", archetype: "perfect", retort: "哎唷，這比喻我愛聽！" },
      { id: "ama-food_push-030-b", text: "阿嬤自己也抓一把，一起看電視。", archetype: "deflect", retort: "好啊，阿嬤也陪你嗑瓜子。" },
      { id: "ama-food_push-030-c", text: "這瓜子好像特別香，加了什麼？", archetype: "deflect", retort: "加了一點鹽跟耐心炒的。" },
      { id: "ama-food_push-030-d", text: "我嗑瓜子技術不好，吃得慢……", archetype: "meek", retort: "慢慢嗑，阿嬤陪你一起嗑！" },
      { id: "ama-food_push-030-e", text: "我吃太多手都黏黏的……", archetype: "meek", retort: "黏黏才好玩，過年就是這樣！" },
      { id: "ama-food_push-030-f", text: "我這嗑瓜子的速度可以比賽了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞）" },
      { id: "ama-food_push-030-g", text: "吃完這包我殼可以蓋一間房子。", archetype: "backfire", retort: "（阿嬤笑笑，又倒一碗）" },
      { id: "ama-food_push-030-h", text: "不要一直抓給我，我自己拿。", archetype: "landmine", retort: "……好，阿嬤放旁邊就好。" },
    ],
  },
  {
    id: "ama-food_push-031",
    text: "剛炸好的芋頭酥，趁熱快來吃。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-031-a", text: "阿嬤炸的芋頭酥，比名店還酥。", archetype: "perfect", retort: "哎唷，比名店還厲害是真的！" },
      { id: "ama-food_push-031-b", text: "阿嬤炸東西這麼久，會不會太累。", archetype: "deflect", retort: "不會累，看你吃才是重點。" },
      { id: "ama-food_push-031-c", text: "這芋頭酥的餡，是不是加了愛心？", archetype: "deflect", retort: "當然，愛心是不外傳的秘方。" },
      { id: "ama-food_push-031-d", text: "剛炸好有點燙，我等一下吃……", archetype: "meek", retort: "燙一下咬開，裡面剛剛好！" },
      { id: "ama-food_push-031-e", text: "我吃甜的比較容易膩……", archetype: "meek", retort: "這個是鹹甜，不會膩，吃吃看！" },
      { id: "ama-food_push-031-f", text: "吃完我應該能空中飛起來。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續炸）" },
      { id: "ama-food_push-031-g", text: "這酥皮讓我想起武俠片輕功。", archetype: "backfire", retort: "（阿嬤笑笑，又端一盤）" },
      { id: "ama-food_push-031-h", text: "不要再炸了啦，油煙很嗆。", archetype: "landmine", retort: "……好，阿嬤先不炸了。" },
    ],
  },
  {
    id: "ama-food_push-032",
    text: "這帖四物燉好了，喝了補氣色。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-032-a", text: "阿嬤燉的四物，比保養品有效。", archetype: "perfect", retort: "哎唷，有效是因為用心燉的。" },
      { id: "ama-food_push-032-b", text: "阿嬤自己氣色也要顧，先喝一碗。", archetype: "deflect", retort: "阿嬤氣色好得很，你多喝。" },
      { id: "ama-food_push-032-c", text: "這帖藥材，是不是特別去配的？", archetype: "deflect", retort: "對，老闆都認得阿嬤了。" },
      { id: "ama-food_push-032-d", text: "這個味道我實在不太敢喝……", archetype: "meek", retort: "加點蜂蜜就不苦，喝喝看！" },
      { id: "ama-food_push-032-e", text: "我最近氣色其實還不錯……", archetype: "meek", retort: "不錯也要保養，喝了更好！" },
      { id: "ama-food_push-032-f", text: "喝完我氣色會不會直接發光。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞碗）" },
      { id: "ama-food_push-032-g", text: "這帖是不是傳說中的美顏丹。", archetype: "backfire", retort: "（阿嬤半信半疑地看你）" },
      { id: "ama-food_push-032-h", text: "不用一直逼我喝這些啦。", archetype: "landmine", retort: "……好，阿嬤不煮了。" },
    ],
  },
  {
    id: "ama-food_push-033",
    text: "滑什麼手機，來，吃塊餅乾。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-033-a", text: "阿嬤的餅乾，比手機更吸引我。", archetype: "perfect", retort: "哎唷，你這孩子真的很會說。" },
      { id: "ama-food_push-033-b", text: "阿嬤自己也吃一塊配茶。", archetype: "deflect", retort: "好啊，阿嬤也來一塊。" },
      { id: "ama-food_push-033-c", text: "這餅乾的口味，是不是新買的？", archetype: "deflect", retort: "對，隔壁新開的餅店買的。" },
      { id: "ama-food_push-033-d", text: "我在回工作訊息，等一下吃……", archetype: "meek", retort: "工作等一下，先吃塊餅乾！" },
      { id: "ama-food_push-033-e", text: "我剛剛吃過點心了……", archetype: "meek", retort: "餅乾不算點心，再吃一塊！" },
      { id: "ama-food_push-033-f", text: "這樣配手機剛好邊滑邊吃。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞）" },
      { id: "ama-food_push-033-g", text: "我要開始經營吃餅乾實況。", archetype: "backfire", retort: "（阿嬤笑笑，又拿出一包）" },
      { id: "ama-food_push-033-h", text: "不要一直打斷我滑手機啦。", archetype: "landmine", retort: "……好，阿嬤不吵你了。" },
    ],
  },
  {
    id: "ama-food_push-034",
    text: "這罐蜜餞是我自己醃的，嚐嚐。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-034-a", text: "阿嬤醃的蜜餞，比進口的還道地。", archetype: "perfect", retort: "哎唷，進口的哪有阿嬤的心意。" },
      { id: "ama-food_push-034-b", text: "阿嬤自己也要吃一顆酸的開胃。", archetype: "deflect", retort: "好啦，阿嬤也吃一顆。" },
      { id: "ama-food_push-034-c", text: "這蜜餞的酸甜比例，剛剛好耶。", archetype: "deflect", retort: "試了很多次才調出這味道。" },
      { id: "ama-food_push-034-d", text: "我對酸的東西比較敏感……", archetype: "meek", retort: "酸酸甜甜開胃，吃一顆看看！" },
      { id: "ama-food_push-034-e", text: "我剛剛已經吃了很多零食……", archetype: "meek", retort: "蜜餞不算零食，再吃一顆！" },
      { id: "ama-food_push-034-f", text: "吃完我的臉應該會皺成一團。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞罐子）" },
      { id: "ama-food_push-034-g", text: "這酸度可以拿來當洗面乳。", archetype: "backfire", retort: "（阿嬤白眼，塞了一顆給你）" },
      { id: "ama-food_push-034-h", text: "不要再塞蜜餞了，我不想吃。", archetype: "landmine", retort: "……好，阿嬤收起來了。" },
    ],
  },
  {
    id: "ama-food_push-035",
    text: "再吃一顆滷蛋，這鍋滷超入味。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-035-a", text: "阿嬤滷的蛋，比茶葉蛋名店更香。", archetype: "perfect", retort: "哎唷，這句話滷蛋都聽開心了。" },
      { id: "ama-food_push-035-b", text: "阿嬤自己也要吃一顆補一補。", archetype: "deflect", retort: "好，阿嬤也拿一顆吃。" },
      { id: "ama-food_push-035-c", text: "這鍋滷汁，是不是滷了很多年？", archetype: "deflect", retort: "對，這老滷傳了好幾代。" },
      { id: "ama-food_push-035-d", text: "我剛剛吃了一顆，有點膩了……", archetype: "meek", retort: "膩什麼膩，再吃一顆才夠！" },
      { id: "ama-food_push-035-e", text: "我想留肚子吃別的菜……", archetype: "meek", retort: "別的都可以吃，蛋也要吃！" },
      { id: "ama-food_push-035-f", text: "吃完我的膽固醇要破表了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續夾）" },
      { id: "ama-food_push-035-g", text: "這顆蛋滷到快變傳家寶了。", archetype: "backfire", retort: "（阿嬤笑笑，又夾一顆）" },
      { id: "ama-food_push-035-h", text: "不要再夾滷蛋了，吃不下。", archetype: "landmine", retort: "……好，阿嬤不夾了。" },
    ],
  },
  {
    id: "ama-food_push-036",
    text: "要出門了，先拿顆包子在手上。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-036-a", text: "阿嬤的包子，比高鐵便當實在。", archetype: "perfect", retort: "哎唷，實在是因為用料實在。" },
      { id: "ama-food_push-036-b", text: "阿嬤這麼早起蒸包子，辛苦了。", archetype: "deflect", retort: "不辛苦，看你出門吃才安心。" },
      { id: "ama-food_push-036-c", text: "這包子的內餡，是不是包了滿滿的愛？", archetype: "deflect", retort: "當然，內餡都是阿嬤的心意。" },
      { id: "ama-food_push-036-d", text: "我等一下高鐵上再吃好了……", archetype: "meek", retort: "現在拿著，路上餓了就吃！" },
      { id: "ama-food_push-036-e", text: "手上東西太多，包子不好拿……", archetype: "meek", retort: "那阿嬤幫你放進包包裡！" },
      { id: "ama-food_push-036-f", text: "這包子夠我撐到下一個過年。", archetype: "backfire", retort: "（阿嬤沒聽懂，又拿一顆）" },
      { id: "ama-food_push-036-g", text: "我要邊走邊吃練習多工處理。", archetype: "backfire", retort: "（阿嬤笑笑，塞進你口袋）" },
      { id: "ama-food_push-036-h", text: "不用硬塞包子給我啦，走了。", archetype: "landmine", retort: "……好，路上小心。" },
    ],
  },
  {
    id: "ama-food_push-037",
    text: "要走了？先吃完這輪水果再走。",
    topic: "food_push",
    bossId: "ama",
    options: [
      { id: "ama-food_push-037-a", text: "阿嬤切的水果，是我離家前的能量。", archetype: "perfect", retort: "哎唷，能量滿滿，慢慢吃。" },
      { id: "ama-food_push-037-b", text: "阿嬤留著自己吃，我在車上吃就好。", archetype: "deflect", retort: "車上哪有新鮮的，快吃完。" },
      { id: "ama-food_push-037-c", text: "這水果切得這麼漂亮，捨不得吃完。", archetype: "deflect", retort: "捨不得也要吃完才能走。" },
      { id: "ama-food_push-037-d", text: "高鐵時間快到了，真的要走了……", archetype: "meek", retort: "等一下，吃完這幾片再走！" },
      { id: "ama-food_push-037-e", text: "我行李箱已經拿在手上了……", archetype: "meek", retort: "放下來，吃完水果再拿！" },
      { id: "ama-food_push-037-f", text: "吃完這輪我要開始跑百米了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續遞水果）" },
      { id: "ama-food_push-037-g", text: "這是我的行前補給儀式吧。", archetype: "backfire", retort: "（阿嬤笑笑，又切了一片）" },
      { id: "ama-food_push-037-h", text: "我真的要走了，不要再留了。", archetype: "landmine", retort: "……好，阿嬤不留你了。" },
    ],
  },
] satisfies Question[];
