import type { Question } from "@/content/types";

// situations: 022 拿舊照片說是你的青梅竹馬 / 023 說鄰居問起你的終身大事 / 024 問你為什麼不趕快定下來
// 025 說她等不到那天怎麼辦 / 026 問對象會不會陪你回來過年 / 027 說結婚年紀不能拖太晚
// 028 問你手機桌布是不是換人了 / 029 說隔壁阿婆的孫女快生了 / 030 拿結婚照片說故事
// 031 問你交往多久還不論及婚嫁 / 032 想在還走得動時看你結婚 / 033 問你是不是根本不想結婚
// 034 說要幫你留一份聘金 / 035 問你跟對象吵架了嗎 / 036 想幫你介紹里長的孩子
// 037 問你有沒有跟對象提過結婚的事
export default [
  {
    id: "ama-marriage-022",
    text: "這張照片，是你跟隔壁小美吧？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-022-a", text: "阿嬤眼睛真利，不過現在只跟你合照，比小美持久。", archetype: "perfect", retort: "哎唷，你這孩子最會討好阿嬤。" },
      { id: "ama-marriage-022-b", text: "阿嬤保存照片保存得真仔細。", archetype: "deflect", retort: "當然，這都是寶貝回憶。" },
      { id: "ama-marriage-022-c", text: "阿嬤還記得這麼多老朋友，真厲害。", archetype: "deflect", retort: "那當然，阿嬤記性好得很。" },
      { id: "ama-marriage-022-d", text: "小美啊，我們早就沒聯絡了……", archetype: "meek", retort: "沒聯絡好可惜，緣分斷了。" },
      { id: "ama-marriage-022-e", text: "那時候只是玩伴，沒有別的……", archetype: "meek", retort: "玩伴也可能變成緣分啊。" },
      { id: "ama-marriage-022-f", text: "那張照片我建議申請文物保存。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻相簿）" },
      { id: "ama-marriage-022-g", text: "小美現在應該是傳說級人物了。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續翻）" },
      { id: "ama-marriage-022-h", text: "不要一直翻舊照片講這些，很煩。", archetype: "landmine", retort: "……好，阿嬤收起來。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-023",
    text: "鄰居問起你終身大事，我都不知怎答。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-023-a", text: "阿嬤就說我正在忙著讓你驕傲，比鄰居的孫子爭氣。", archetype: "perfect", retort: "哎唷，這句話阿嬤肯定拿去說。" },
      { id: "ama-marriage-023-b", text: "阿嬤就說我很好，別的不用多說。", archetype: "deflect", retort: "好，阿嬤就這樣回答她。" },
      { id: "ama-marriage-023-c", text: "鄰居問這麼細，阿嬤辛苦你了。", archetype: "deflect", retort: "沒事，鄰居就是關心而已。" },
      { id: "ama-marriage-023-d", text: "這個真的沒有明確答案可以講……", archetype: "meek", retort: "沒答案，阿嬤要怎麼回她？" },
      { id: "ama-marriage-023-e", text: "阿嬤就說我在忙工作就好……", archetype: "meek", retort: "工作忙也不能一直忙下去啊。" },
      { id: "ama-marriage-023-f", text: "阿嬤就跟她說我在做秘密任務。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續煩惱怎麼回）" },
      { id: "ama-marriage-023-g", text: "就跟鄰居說我還在做市場調查。", archetype: "backfire", retort: "（阿嬤白眼，還是很煩惱）" },
      { id: "ama-marriage-023-h", text: "鄰居的事不用理她，別問我，很煩。", archetype: "landmine", retort: "……阿嬤只是不知道怎麼說。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-024",
    text: "你為什麼不趕快定下來啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-024-a", text: "阿嬤放心，我在等配得上你孫子的人，比三姑挑剔。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤很有面子。" },
      { id: "ama-marriage-024-b", text: "阿嬤覺得定下來最重要的是什麼？", archetype: "deflect", retort: "找到真心對你好的人。" },
      { id: "ama-marriage-024-c", text: "阿嬤這麼關心，是擔心我孤單嗎？", archetype: "deflect", retort: "當然，阿嬤怕你一個人。" },
      { id: "ama-marriage-024-d", text: "我自己也在想，但真的沒遇到……", archetype: "meek", retort: "沒遇到也要積極一點找啊。" },
      { id: "ama-marriage-024-e", text: "感覺自己還沒準備好定下來……", archetype: "meek", retort: "準備好要花多久時間啊？" },
      { id: "ama-marriage-024-f", text: "我打算先完成人生成就再定下來。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-024-g", text: "定下來這件事我排進待辦清單了。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續碎念）" },
      { id: "ama-marriage-024-h", text: "定不定下來不用你一直催，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-025",
    text: "阿嬤要是等不到那天，怎麼辦？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-025-a", text: "阿嬤放心，我會加緊腳步，比三舅媽追業績還拼。", archetype: "perfect", retort: "哎唷，你這孩子最會安慰阿嬤。" },
      { id: "ama-marriage-025-b", text: "阿嬤要健康活著，才能等到那天。", archetype: "deflect", retort: "好，阿嬤會好好照顧自己。" },
      { id: "ama-marriage-025-c", text: "阿嬤別想這些，先陪我吃飯。", archetype: "deflect", retort: "好啦，阿嬤陪你吃飯。" },
      { id: "ama-marriage-025-d", text: "我也不知道會不會太晚……", archetype: "meek", retort: "太晚阿嬤真的會擔心。" },
      { id: "ama-marriage-025-e", text: "這種事真的沒辦法保證時間……", archetype: "meek", retort: "沒保證也要努力朝那走啊。" },
      { id: "ama-marriage-025-f", text: "我立刻去廟裡拜託神明保佑。", archetype: "backfire", retort: "（阿嬤沒聽懂，還是很擔心）" },
      { id: "ama-marriage-025-g", text: "我打算加快人生進度條。", archetype: "backfire", retort: "（阿嬤一臉困惑地看你）" },
      { id: "ama-marriage-025-h", text: "不要講這種話啦，很奇怪，很煩。", archetype: "landmine", retort: "……阿嬤只是說出心裡話。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-026",
    text: "以後對象會不會陪你回來過年？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-026-a", text: "阿嬤放心，我會帶他來吃你煮的菜，比餐廳實在。", archetype: "perfect", retort: "哎唷，那阿嬤要多煮幾道菜！" },
      { id: "ama-marriage-026-b", text: "阿嬤煮的年菜，誰吃過都會想回來。", archetype: "deflect", retort: "那當然，這是阿嬤的手藝。" },
      { id: "ama-marriage-026-c", text: "阿嬤這麼會煮，對象肯定被收服。", archetype: "deflect", retort: "哎唷，這句話說得真好。" },
      { id: "ama-marriage-026-d", text: "這個要看緣分，還沒對象怎麼說……", archetype: "meek", retort: "沒對象也要提早想一下啊。" },
      { id: "ama-marriage-026-e", text: "現在感情狀態還不穩定……", archetype: "meek", retort: "不穩定就要多花心思經營啊。" },
      { id: "ama-marriage-026-f", text: "對象的事我打算用問卷調查。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續期待）" },
      { id: "ama-marriage-026-g", text: "我要先訓練對象吃辣的能力。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續問）" },
      { id: "ama-marriage-026-h", text: "這個還早，不要一直問這些，很煩。", archetype: "landmine", retort: "……阿嬤只是好奇而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-027",
    text: "結婚年紀真的不能拖太晚知道嗎。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-027-a", text: "阿嬤說的都對，我這就加快腳步，超車表姊。", archetype: "perfect", retort: "哎唷，聽話最讓阿嬤安心了。" },
      { id: "ama-marriage-027-b", text: "阿嬤年輕時候結婚會不會很趕？", archetype: "deflect", retort: "還好，那時候大家都早婚。" },
      { id: "ama-marriage-027-c", text: "阿嬤這麼關心，是怕我孤單吧。", archetype: "deflect", retort: "當然，阿嬤最怕你孤單過。" },
      { id: "ama-marriage-027-d", text: "我知道，但真的還沒遇到對的人……", archetype: "meek", retort: "沒遇到也要積極一點找找。" },
      { id: "ama-marriage-027-e", text: "我自己也覺得有點焦慮……", archetype: "meek", retort: "焦慮就要付諸行動啊，孩子。" },
      { id: "ama-marriage-027-f", text: "我打算走大器晚成路線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-027-g", text: "年紀不重要，心態年輕就好。", archetype: "backfire", retort: "（阿嬤白眼，繼續碎念）" },
      { id: "ama-marriage-027-h", text: "年紀是我的事，不用你操心，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-028",
    text: "你手機桌布怎麼換人了，是誰啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-028-a", text: "阿嬤眼睛真尖，換的人比三姑會照顧人。", archetype: "perfect", retort: "哎唷，這句話講得阿嬤好高興。" },
      { id: "ama-marriage-028-b", text: "阿嬤想看照片，我拿給你看風景照。", archetype: "deflect", retort: "哎唷，就想看看而已嘛。" },
      { id: "ama-marriage-028-c", text: "阿嬤觀察力這麼好，可以當偵探。", archetype: "deflect", retort: "哎唷，關心孫子當然仔細。" },
      { id: "ama-marriage-028-d", text: "是朋友啦，還不算什麼特別的……", archetype: "meek", retort: "朋友照片放桌布，特別吧？" },
      { id: "ama-marriage-028-e", text: "那是最近認識的人，還在了解……", archetype: "meek", retort: "了解要快一點，別拖太久！" },
      { id: "ama-marriage-028-f", text: "那個是我新認的乾妹妹啦。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-028-g", text: "桌布是隨機演算法自動換的。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-028-h", text: "桌布是我自己的事，別看啦，很煩。", archetype: "landmine", retort: "……好，阿嬤不看了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-029",
    text: "隔壁阿婆的孫女懷孕了，你呢？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-029-a", text: "阿嬤放心，我的好消息，比隔壁阿婆的孫女值得等。", archetype: "perfect", retort: "哎唷，你這句話最讓阿嬤期待。" },
      { id: "ama-marriage-029-b", text: "懷孕是喜事，記得包紅包祝賀。", archetype: "deflect", retort: "對厚，等一下就去準備。" },
      { id: "ama-marriage-029-c", text: "阿嬤消息真靈通，鄰里都知道。", archetype: "deflect", retort: "當然，這種喜事傳得快。" },
      { id: "ama-marriage-029-d", text: "我這邊真的還早，連對象都沒有……", archetype: "meek", retort: "沒對象要趕快去找啊。" },
      { id: "ama-marriage-029-e", text: "大家的人生時程真的不一樣……", archetype: "meek", retort: "不一樣也不能拖太久啊。" },
      { id: "ama-marriage-029-f", text: "我打算先領養一隻狗練習當爸媽。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨鄰居）" },
      { id: "ama-marriage-029-g", text: "懷孕的事我建議交給科學決定。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續碎念）" },
      { id: "ama-marriage-029-h", text: "不要拿鄰居的事比較我，很煩耶。", archetype: "landmine", retort: "……好，阿嬤不比了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-030",
    text: "這是阿嬤結婚那天，來聽個故事。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-030-a", text: "阿嬤結婚那天，是我們家最美的照片，比婚紗照有故事。", archetype: "perfect", retort: "哎唷，你這孩子嘴巴真甜。" },
      { id: "ama-marriage-030-b", text: "阿嬤講故事最好聽了，快說快說。", archetype: "deflect", retort: "好啊，那阿嬤慢慢說給你聽。" },
      { id: "ama-marriage-030-c", text: "阿嬤那時候穿的衣服，好有味道。", archetype: "deflect", retort: "那時候流行這樣穿，好看吧。" },
      { id: "ama-marriage-030-d", text: "我最近聽故事都容易分心……", archetype: "meek", retort: "分心也要聽阿嬤講完啦。" },
      { id: "ama-marriage-030-e", text: "這個故事我好像聽過幾次了……", archetype: "meek", retort: "聽過也要再聽一次，很重要！" },
      { id: "ama-marriage-030-f", text: "這故事我建議拍成微電影。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續講故事）" },
      { id: "ama-marriage-030-g", text: "阿嬤那時候的造型好復古潮流。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續講）" },
      { id: "ama-marriage-030-h", text: "這故事聽好幾次了，不要再講，很煩。", archetype: "landmine", retort: "……好，阿嬤不講了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-031",
    text: "你們交往這麼久，怎麼還不結婚？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-031-a", text: "阿嬤別急，我們在存錢辦你想看的婚禮，比排場重要。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤很期待。" },
      { id: "ama-marriage-031-b", text: "阿嬤覺得婚禮辦成什麼樣子最好？", archetype: "deflect", retort: "簡單溫馨，家人都在最好。" },
      { id: "ama-marriage-031-c", text: "阿嬤這麼關心，肯定很期待喜酒。", archetype: "deflect", retort: "當然，阿嬤等這天很久了。" },
      { id: "ama-marriage-031-d", text: "我們還在討論，時間點還沒定……", archetype: "meek", retort: "討論太久，時間會等人嗎？" },
      { id: "ama-marriage-031-e", text: "感覺我們兩個都還沒準備好……", archetype: "meek", retort: "準備好要花多久時間呢？" },
      { id: "ama-marriage-031-f", text: "我們打算先辦升級版試婚合約。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-031-g", text: "結婚的事我們排進五年計畫。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-031-h", text: "我們的進度不用你一直催，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-032",
    text: "阿嬤想趁還走得動時看你結婚。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-032-a", text: "阿嬤走得動，我就走得快，比三姑積極讓你看到。", archetype: "perfect", retort: "哎唷，你這孩子講話真暖心。" },
      { id: "ama-marriage-032-b", text: "阿嬤要多運動，才能走得更久。", archetype: "deflect", retort: "好，阿嬤會多出去走走。" },
      { id: "ama-marriage-032-c", text: "阿嬤想看的話，先陪你去公園走走。", archetype: "deflect", retort: "好啊，走走活動活動筋骨。" },
      { id: "ama-marriage-032-d", text: "我也希望能快點，但真的急不來……", archetype: "meek", retort: "急不來也要放在心上努力。" },
      { id: "ama-marriage-032-e", text: "這種事真的沒辦法給時間表……", archetype: "meek", retort: "沒時間表阿嬤會等得辛苦。" },
      { id: "ama-marriage-032-f", text: "阿嬤放心，我幫你辦健走會員卡。", archetype: "backfire", retort: "（阿嬤沒聽懂，還是很期待）" },
      { id: "ama-marriage-032-g", text: "我打算加快人生副本進度。", archetype: "backfire", retort: "（阿嬤一臉困惑地看你）" },
      { id: "ama-marriage-032-h", text: "你很煩耶，別再說這種喪氣話。", archetype: "landmine", retort: "……阿嬤只是說真心話。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-033",
    text: "你是不是根本就不想結婚啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-033-a", text: "我只是還沒遇到，比得上疼我的阿嬤那種人。", archetype: "perfect", retort: "哎唷，這孩子嘴巴真的很甜。" },
      { id: "ama-marriage-033-b", text: "阿嬤覺得結婚最重要的是什麼？", archetype: "deflect", retort: "兩個人能好好過日子最重要。" },
      { id: "ama-marriage-033-c", text: "阿嬤別擔心，我對家庭很嚮往的。", archetype: "deflect", retort: "嚮往就要趕快付諸行動啊。" },
      { id: "ama-marriage-033-d", text: "老實說，我確實有點猶豫……", archetype: "meek", retort: "猶豫什麼，結婚有這麼難嗎？" },
      { id: "ama-marriage-033-e", text: "我覺得一個人也過得不錯……", archetype: "meek", retort: "一個人久了會孤單的，孩子。" },
      { id: "ama-marriage-033-f", text: "我在等元宇宙結婚制度上線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-033-g", text: "我打算先跟工作訂婚就好。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-033-h", text: "想不想結婚是我自己的事，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-034",
    text: "阿嬤存了一份聘金，要留給你。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-034-a", text: "阿嬤存的聘金，我要拿去辦贏過三姑女兒的婚禮。", archetype: "perfect", retort: "哎唷，風光是應該的，去辦吧！" },
      { id: "ama-marriage-034-b", text: "阿嬤自己留著用，別都存給我。", archetype: "deflect", retort: "存起來就是要給你，別客氣。" },
      { id: "ama-marriage-034-c", text: "阿嬤這麼疼我，我都不知怎麼謝。", archetype: "deflect", retort: "謝什麼，你孝順就夠了。" },
      { id: "ama-marriage-034-d", text: "現在真的還用不到，先幫我留著……", archetype: "meek", retort: "留著等你，隨時都能用。" },
      { id: "ama-marriage-034-e", text: "我怕給了以後對象嫌少……", archetype: "meek", retort: "心意到了，少也是多。" },
      { id: "ama-marriage-034-f", text: "我打算拿聘金先去投資股票。", archetype: "backfire", retort: "（阿嬤沒聽懂，把錢收好）" },
      { id: "ama-marriage-034-g", text: "聘金我建議換成虛擬貨幣。", archetype: "backfire", retort: "（阿嬤白眼，把錢收起來）" },
      { id: "ama-marriage-034-h", text: "這些錢不用留給我，我自己賺，很煩。", archetype: "landmine", retort: "……好，阿嬤留著就好。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-035",
    text: "你最近臉臭臭的，跟對象吵架？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-035-a", text: "阿嬤觀察力真好，吵完我們比表姊夫妻更好。", archetype: "perfect", retort: "哎唷，這樣才是真正的感情。" },
      { id: "ama-marriage-035-b", text: "阿嬤這麼會看臉色，太厲害了吧。", archetype: "deflect", retort: "當然，阿嬤最了解你了。" },
      { id: "ama-marriage-035-c", text: "阿嬤別擔心我，先擔心你的血糖。", archetype: "deflect", retort: "哎唷，換你來管阿嬤了。" },
      { id: "ama-marriage-035-d", text: "對，最近確實有點小摩擦……", archetype: "meek", retort: "摩擦要好好溝通，別悶著。" },
      { id: "ama-marriage-035-e", text: "是有一點不愉快，還在冷靜……", archetype: "meek", retort: "冷靜歸冷靜，別拖太久喔。" },
      { id: "ama-marriage-035-f", text: "那只是我們日常的戰略磨合。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-035-g", text: "吵架是感情升級的必要流程。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-035-h", text: "我們的事不用你一直問啦，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-036",
    text: "里長家的孩子不錯，要不要認識？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-036-a", text: "阿嬤介紹的，我一定比相親市場認真去認識。", archetype: "perfect", retort: "哎唷，這麼給面子，阿嬤高興。" },
      { id: "ama-marriage-036-b", text: "阿嬤先幫我探探對方喜歡什麼。", archetype: "deflect", retort: "好，阿嬤明天去問問看。" },
      { id: "ama-marriage-036-c", text: "阿嬤的人脈這麼廣，太厲害了。", archetype: "deflect", retort: "那當然，阿嬤走透透的。" },
      { id: "ama-marriage-036-d", text: "我最近真的沒空認識新朋友……", archetype: "meek", retort: "沒空也要擠個時間出來啊。" },
      { id: "ama-marriage-036-e", text: "這種介紹我還沒心理準備……", archetype: "meek", retort: "準備好要等到什麼時候？" },
      { id: "ama-marriage-036-f", text: "認識前我要先辦一場面試。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續安排）" },
      { id: "ama-marriage-036-g", text: "這算不算相親界的資格考？", archetype: "backfire", retort: "（阿嬤白眼，逕自約時間）" },
      { id: "ama-marriage-036-h", text: "不要隨便幫我安排認識人，很煩耶。", archetype: "landmine", retort: "……好，阿嬤不安排了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-037",
    text: "你有沒有跟對象提過結婚的事？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-037-a", text: "阿嬤放心，我們在等一個比三姑更值得的祝福時機。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好感動。" },
      { id: "ama-marriage-037-b", text: "阿嬤覺得什麼時候提最好？", archetype: "deflect", retort: "感情穩定了就可以提啊。" },
      { id: "ama-marriage-037-c", text: "阿嬤這麼期待，我更有動力去提。", archetype: "deflect", retort: "對嘛，要有動力才會行動。" },
      { id: "ama-marriage-037-d", text: "還沒有，怕提了嚇到對方……", archetype: "meek", retort: "怕嚇到也要找機會溝通啊。" },
      { id: "ama-marriage-037-e", text: "我們感情還在磨合，還沒提到……", archetype: "meek", retort: "磨合久了要記得往前走。" },
      { id: "ama-marriage-037-f", text: "我打算用簡報形式提案求婚。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-037-g", text: "結婚的事我排進行事曆待辦。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-037-h", text: "提不提是我的事，不用你催，很煩。", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
] satisfies Question[];
