import type { Question } from "@/content/types";

// situations: 002 問你有沒有交往對象 / 003 問你什麼時候結婚 / 004 看老照片說阿嬤當年嫁人的年紀
// 005 說要留房間給你以後住 / 006 說鄰居陳太太孫子訂婚了 / 007 拿出戒指要傳給你
// 008 問對方家在哪裡做什麼 / 009 說想在走之前抱曾孫 / 010 問你是不是眼光太高
// 011 說廟口誰家孩子要介紹 / 012 問朋友圈有沒有合適的人 / 013 翻你手機看有沒有交友軟體
// 014 問對方會不會煮飯顧家 / 015 說要拿八字去合一下 / 016 提起小時候玩伴已當爸媽
// 017 問你到底喜歡什麼樣的人 / 018 說要包紅包給未來另一半 / 019 問你是不是分手了才不提
// 020 說想幫你安排相親 / 021 問你們是不是同居了
export default [
  {
    id: "ama-marriage-002",
    text: "現在有沒有在跟誰交往啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-002-a", text: "阿嬤先跟我交往就好，我最愛你。", archetype: "perfect", retort: "哎唷，這孩子最會討阿嬤歡心。" },
      { id: "ama-marriage-002-b", text: "阿嬤先說，你當年怎麼追阿公的？", archetype: "deflect", retort: "那個時候喔，阿公可主動了。" },
      { id: "ama-marriage-002-c", text: "阿嬤這麼關心，是有對象想介紹？", archetype: "deflect", retort: "沒有啦，就是問問而已。" },
      { id: "ama-marriage-002-d", text: "目前沒有耶，工作比較忙……", archetype: "meek", retort: "忙也要留點時間給感情啦。" },
      { id: "ama-marriage-002-e", text: "有在聊天啦，但還沒確定……", archetype: "meek", retort: "聊天要聊到什麼時候才確定？" },
      { id: "ama-marriage-002-f", text: "我現在是走單身貴族路線的。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續夾菜）" },
      { id: "ama-marriage-002-g", text: "緣分這東西，隨緣就好啦。", archetype: "backfire", retort: "（阿嬤沒接話，繼續夾菜）" },
      { id: "ama-marriage-002-h", text: "阿嬤你不要每次都問這個啦。", archetype: "landmine", retort: "……好，阿嬤不問了。" },
    ],
  },
  {
    id: "ama-marriage-003",
    text: "你什麼時候要結婚？阿嬤等著喝喜酒。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-003-a", text: "阿嬤先等我把喜酒錢存夠再說。", archetype: "perfect", retort: "哎唷，這麼實在，阿嬤放心。" },
      { id: "ama-marriage-003-b", text: "阿嬤身體顧好，才能等到那一天。", archetype: "deflect", retort: "放心，阿嬤會等到那一天。" },
      { id: "ama-marriage-003-c", text: "阿嬤想喝喜酒，我先倒一杯給你。", archetype: "deflect", retort: "臭小子，還會反過來哄我。" },
      { id: "ama-marriage-003-d", text: "還沒有計畫，順其自然啦……", archetype: "meek", retort: "順其自然要等到什麼時候？" },
      { id: "ama-marriage-003-e", text: "對象都還沒有，怎麼結婚……", archetype: "meek", retort: "沒對象就快去找一個啊！" },
      { id: "ama-marriage-003-f", text: "喜酒的事，我打算辦流水席。", archetype: "backfire", retort: "（阿嬤聽不懂，繼續問細節）" },
      { id: "ama-marriage-003-g", text: "我在等一個良辰吉時降臨。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續夾菜）" },
      { id: "ama-marriage-003-h", text: "結婚的事不要每次都提啦。", archetype: "landmine", retort: "……好，阿嬤不提了。" },
    ],
  },
  {
    id: "ama-marriage-004",
    text: "你看，阿嬤這年紀就嫁給你阿公了。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-004-a", text: "阿嬤當年真美，難怪阿公捨不得。", archetype: "perfect", retort: "哎唷，你這孩子嘴巴真甜。" },
      { id: "ama-marriage-004-b", text: "阿嬤這張照片，可以裱框起來。", archetype: "deflect", retort: "好啊，改天真的裱起來。" },
      { id: "ama-marriage-004-c", text: "阿嬤跟阿公的故事，講給我聽好嗎？", archetype: "deflect", retort: "好啊，改天慢慢跟你講。" },
      { id: "ama-marriage-004-d", text: "現在時代不一樣了，比較晚……", archetype: "meek", retort: "晚是晚，但也不能太晚啊。" },
      { id: "ama-marriage-004-e", text: "我這年紀身邊很多人都還單身……", archetype: "meek", retort: "單身也要有個目標啊，孩子。" },
      { id: "ama-marriage-004-f", text: "那時候結婚應該比較划算吧。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻相簿）" },
      { id: "ama-marriage-004-g", text: "我要研究一下當年的行情。", archetype: "backfire", retort: "（阿嬤白眼，翻下一頁）" },
      { id: "ama-marriage-004-h", text: "時代不一樣了，不要拿來比。", archetype: "landmine", retort: "……好，阿嬤不比了。" },
    ],
  },
  {
    id: "ama-marriage-005",
    text: "這房間留給你，以後帶對象住。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-005-a", text: "阿嬤留的房間，我要住到你煩為止。", archetype: "perfect", retort: "哎唷，住多久阿嬤都歡迎。" },
      { id: "ama-marriage-005-b", text: "阿嬤自己也要留個好房間養生。", archetype: "deflect", retort: "阿嬤這間住習慣了，不換。" },
      { id: "ama-marriage-005-c", text: "這房間布置得真溫馨，謝謝阿嬤。", archetype: "deflect", retort: "喜歡就好，隨時回來住。" },
      { id: "ama-marriage-005-d", text: "我目前一個人住習慣了……", archetype: "meek", retort: "一個人住太孤單了啦。" },
      { id: "ama-marriage-005-e", text: "對象的事真的還沒有著落……", archetype: "meek", retort: "著落要自己去找，別等天上掉！" },
      { id: "ama-marriage-005-f", text: "那我要把房間改成錄音室。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續說房間規劃）" },
      { id: "ama-marriage-005-g", text: "我打算把房間出租收房租。", archetype: "backfire", retort: "（阿嬤瞪你一眼，沒再說話）" },
      { id: "ama-marriage-005-h", text: "房間的事先不要想那麼遠啦。", archetype: "landmine", retort: "……好，阿嬤不想了。" },
    ],
  },
  {
    id: "ama-marriage-006",
    text: "隔壁陳太太孫子都訂婚了，你呢？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-006-a", text: "阿嬤放心，我的喜事一定比訂婚精彩。", archetype: "perfect", retort: "哎唷，你這孩子最會安慰人。" },
      { id: "ama-marriage-006-b", text: "陳太太孫子訂婚，記得包紅包道賀。", archetype: "deflect", retort: "對厚，等一下就去包。" },
      { id: "ama-marriage-006-c", text: "阿嬤消息真靈通，跟誰打聽的？", archetype: "deflect", retort: "當然是陳太太親口說的。" },
      { id: "ama-marriage-006-d", text: "我這邊真的還沒有消息……", archetype: "meek", retort: "沒消息要自己去努力找啊。" },
      { id: "ama-marriage-006-e", text: "大家步調不一樣，我還在忙工作……", archetype: "meek", retort: "工作忙也要顧感情才行啊。" },
      { id: "ama-marriage-006-f", text: "訂婚而已，我要直接結婚超車。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨陳太太）" },
      { id: "ama-marriage-006-g", text: "我在等一個更浪漫的求婚方案。", archetype: "backfire", retort: "（阿嬤半信半疑地點頭）" },
      { id: "ama-marriage-006-h", text: "不要拿我跟陳太太的孫子比啦。", archetype: "landmine", retort: "……好，阿嬤不比了。" },
    ],
  },
  {
    id: "ama-marriage-007",
    text: "這只戒指，阿嬤想留給你以後用。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-007-a", text: "阿嬤的戒指，我會好好收著等那天。", archetype: "perfect", retort: "哎唷，你這孩子最懂阿嬤的心。" },
      { id: "ama-marriage-007-b", text: "阿嬤這麼珍貴的東西，自己留著戴。", archetype: "deflect", retort: "戴著也是想著要傳給你。" },
      { id: "ama-marriage-007-c", text: "這戒指有故事嗎？講給我聽。", archetype: "deflect", retort: "這是阿公當年送的，有故事。" },
      { id: "ama-marriage-007-d", text: "我怕弄丟，還是先讓阿嬤保管……", archetype: "meek", retort: "那就先放阿嬤這裡，別急。" },
      { id: "ama-marriage-007-e", text: "我現在真的還用不上這個……", archetype: "meek", retort: "用不上也要收好，以後會用到。" },
      { id: "ama-marriage-007-f", text: "我要拿去鑑定節目估價看看。", archetype: "backfire", retort: "（阿嬤沒聽懂，把戒指收起來）" },
      { id: "ama-marriage-007-g", text: "這戒指感覺可以當傳家寶賣。", archetype: "backfire", retort: "（阿嬤白眼，把戒指收好）" },
      { id: "ama-marriage-007-h", text: "這種東西先不要拿出來講啦。", archetype: "landmine", retort: "……好，阿嬤收起來了。" },
    ],
  },
  {
    id: "ama-marriage-008",
    text: "那個人是做什麼的？家住哪裡？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-008-a", text: "阿嬤放心，人品比職業地址重要。", archetype: "perfect", retort: "哎唷，這句話講到阿嬤心坎裡。" },
      { id: "ama-marriage-008-b", text: "阿嬤想知道，是不是要幫我把關？", archetype: "deflect", retort: "當然，阿嬤的眼光最準。" },
      { id: "ama-marriage-008-c", text: "等確定了，第一個帶來給阿嬤看。", archetype: "deflect", retort: "好，阿嬤等你這句話。" },
      { id: "ama-marriage-008-d", text: "都還沒到那個階段，不好意思問……", archetype: "meek", retort: "不問怎麼知道人品好不好？" },
      { id: "ama-marriage-008-e", text: "這個真的還沒問清楚……", archetype: "meek", retort: "沒問清楚怎麼放心交往？" },
      { id: "ama-marriage-008-f", text: "職業家世我打算用抽籤決定。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-008-g", text: "這是身家調查嗎？我要請律師。", archetype: "backfire", retort: "（阿嬤白眼，繼續追問細節）" },
      { id: "ama-marriage-008-h", text: "這些不用你查戶口啦，阿嬤。", archetype: "landmine", retort: "……好，阿嬤不問了。" },
    ],
  },
  {
    id: "ama-marriage-009",
    text: "阿嬤想在走之前抱到你的小孩。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-009-a", text: "阿嬤要活到抱曾孫上大學才行。", archetype: "perfect", retort: "哎唷，你這孩子講話真好聽。" },
      { id: "ama-marriage-009-b", text: "阿嬤先把身體養好，我們才有希望。", archetype: "deflect", retort: "好，阿嬤會好好照顧自己。" },
      { id: "ama-marriage-009-c", text: "阿嬤想抱曾孫，先抱抱我這個孫子。", archetype: "deflect", retort: "好啦好啦，過來讓阿嬤抱。" },
      { id: "ama-marriage-009-d", text: "這個真的還早，我自己都還沒穩定……", archetype: "meek", retort: "穩定了才要快點加油啊。" },
      { id: "ama-marriage-009-e", text: "這種事沒辦法用等的，急不來……", archetype: "meek", retort: "急不來也要往那方向努力啊。" },
      { id: "ama-marriage-009-f", text: "曾孫的事我先預約一個名額。", archetype: "backfire", retort: "（阿嬤沒聽懂，還是很期待）" },
      { id: "ama-marriage-009-g", text: "我打算先養隻貓練習當爸媽。", archetype: "backfire", retort: "（阿嬤一臉不解，繼續念）" },
      { id: "ama-marriage-009-h", text: "這種話不要一直拿來壓我啦。", archetype: "landmine", retort: "……阿嬤只是想看到而已。" },
    ],
  },
  {
    id: "ama-marriage-010",
    text: "是不是你眼光太高才沒對象？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-010-a", text: "阿嬤把我教得太好，眼光自然高。", archetype: "perfect", retort: "哎唷，這是誇阿嬤還是誇你自己。" },
      { id: "ama-marriage-010-b", text: "阿嬤覺得什麼樣的人才配得上我？", archetype: "deflect", retort: "當然是要對你好的人才行。" },
      { id: "ama-marriage-010-c", text: "阿嬤眼光那麼好，幫我掌掌眼吧。", archetype: "deflect", retort: "好啊，改天阿嬤幫你看看。" },
      { id: "ama-marriage-010-d", text: "也許吧，可能真的比較挑……", archetype: "meek", retort: "挑是可以，但也別太挑了。" },
      { id: "ama-marriage-010-e", text: "我覺得應該是緣分還沒到……", archetype: "meek", retort: "緣分不會自己來，要主動一點！" },
      { id: "ama-marriage-010-f", text: "我這叫寧缺勿濫的高級單身。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-010-g", text: "我是在等對的人出現的貴族。", archetype: "backfire", retort: "（阿嬤白眼，繼續碎念）" },
      { id: "ama-marriage-010-h", text: "不是眼光高，是你們太急了。", archetype: "landmine", retort: "……阿嬤只是希望你幸福。" },
    ],
  },
  {
    id: "ama-marriage-011",
    text: "廟口張阿姨的孫女不錯，見一面？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-011-a", text: "阿嬤介紹的，我一定慎重考慮。", archetype: "perfect", retort: "哎唷，慎重是對的，阿嬤陪你去。" },
      { id: "ama-marriage-011-b", text: "阿嬤先幫我探探對方喜歡吃什麼。", archetype: "deflect", retort: "好，阿嬤明天就去問。" },
      { id: "ama-marriage-011-c", text: "阿嬤的眼光這麼準，我很期待。", archetype: "deflect", retort: "那當然，阿嬤看人很準。" },
      { id: "ama-marriage-011-d", text: "我最近真的沒空約會……", archetype: "meek", retort: "沒空也要抽個時間見一面。" },
      { id: "ama-marriage-011-e", text: "相親這種事，我還沒準備好……", archetype: "meek", retort: "準備好要等到什麼時候？" },
      { id: "ama-marriage-011-f", text: "我要先做一份簡報自我介紹。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續安排時間）" },
      { id: "ama-marriage-011-g", text: "這算不算相親界的面試？", archetype: "backfire", retort: "（阿嬤白眼，逕自約時間）" },
      { id: "ama-marriage-011-h", text: "不要隨便幫我安排相親啦。", archetype: "landmine", retort: "……好，阿嬤不安排了。" },
    ],
  },
  {
    id: "ama-marriage-012",
    text: "你朋友那麼多，沒有一個合適的？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-012-a", text: "朋友圈裡最合適的，是常回家看你的我。", archetype: "perfect", retort: "哎唷，你這孩子真的很會講。" },
      { id: "ama-marriage-012-b", text: "阿嬤覺得什麼樣的朋友算合適？", archetype: "deflect", retort: "孝順、顧家的最合適。" },
      { id: "ama-marriage-012-c", text: "阿嬤這麼關心，要不要幫我物色？", archetype: "deflect", retort: "好啊，阿嬤幫你留意留意。" },
      { id: "ama-marriage-012-d", text: "朋友是朋友，感情真的沒那麼順利……", archetype: "meek", retort: "沒那麼順利也要多試試看。" },
      { id: "ama-marriage-012-e", text: "大家好像都比較晚定下來……", archetype: "meek", retort: "晚也要有個譜，別拖太久。" },
      { id: "ama-marriage-012-f", text: "我朋友圈都走生涯發展路線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-012-g", text: "我在朋友圈搞地下配對事業。", archetype: "backfire", retort: "（阿嬤半信半疑地看你）" },
      { id: "ama-marriage-012-h", text: "我朋友的事不要一直問啦。", archetype: "landmine", retort: "……好，阿嬤不問了。" },
    ],
  },
  {
    id: "ama-marriage-013",
    text: "你手機裡是不是有交友軟體？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-013-a", text: "阿嬤，我手機最重要的是你的照片。", archetype: "perfect", retort: "哎唷，你這孩子最會哄阿嬤。" },
      { id: "ama-marriage-013-b", text: "阿嬤想看我手機，是想看照片吧。", archetype: "deflect", retort: "對啊，想看你最近過得好不好。" },
      { id: "ama-marriage-013-c", text: "阿嬤自己有沒有想學用手機交朋友？", archetype: "deflect", retort: "我這把年紀，不用學那個了。" },
      { id: "ama-marriage-013-d", text: "有下載啦，但一直沒認真用……", archetype: "meek", retort: "下載了就要認真用啊！" },
      { id: "ama-marriage-013-e", text: "是有一兩個沒錯，還在觀望……", archetype: "meek", retort: "觀望什麼，主動一點才行！" },
      { id: "ama-marriage-013-f", text: "那個只是用來練習聊天技巧的。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-013-g", text: "我下載是為了研究市場趨勢。", archetype: "backfire", retort: "（阿嬤白眼，伸手要看手機）" },
      { id: "ama-marriage-013-h", text: "不要翻我手機，這是隱私。", archetype: "landmine", retort: "……好，阿嬤不翻了。" },
    ],
  },
  {
    id: "ama-marriage-014",
    text: "那個人會不會煮飯？顧不顧家？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-014-a", text: "阿嬤放心，煮飯的手藝我跟你學的。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好驕傲。" },
      { id: "ama-marriage-014-b", text: "阿嬤煮飯這麼厲害，要不要開課？", archetype: "deflect", retort: "哎唷，開課我可不敢。" },
      { id: "ama-marriage-014-c", text: "阿嬤覺得顧家最重要的是什麼？", archetype: "deflect", retort: "是願不願意為家人多想一點。" },
      { id: "ama-marriage-014-d", text: "這個我還真的沒特別問……", archetype: "meek", retort: "這麼重要的事怎麼能不問？" },
      { id: "ama-marriage-014-e", text: "感覺對方比較不擅長做家事……", archetype: "meek", retort: "不擅長可以學，重點是有心。" },
      { id: "ama-marriage-014-f", text: "煮飯的事我打算外包給我。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-014-g", text: "顧家這件事我覺得AI比較行。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續問）" },
      { id: "ama-marriage-014-h", text: "這些事不用你操心啦，阿嬤。", archetype: "landmine", retort: "……阿嬤只是關心而已。" },
    ],
  },
  {
    id: "ama-marriage-015",
    text: "要不要拿你們的八字去合一下？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-015-a", text: "阿嬤幫忙看的八字，一定比老師準。", archetype: "perfect", retort: "哎唷，你這句話講得阿嬤開心。" },
      { id: "ama-marriage-015-b", text: "阿嬤懂八字，改天教教我基礎。", archetype: "deflect", retort: "好啊，改天教你怎麼看。" },
      { id: "ama-marriage-015-c", text: "阿嬤覺得我跟阿嬤八字合不合？", archetype: "deflect", retort: "我們祖孫這麼合，當然合。" },
      { id: "ama-marriage-015-d", text: "對方好像不太相信這個……", archetype: "meek", retort: "不信也可以私下幫他看看。" },
      { id: "ama-marriage-015-e", text: "這個我還沒有想到那麼遠……", archetype: "meek", retort: "該想的時候要提早想啊。" },
      { id: "ama-marriage-015-f", text: "我打算用星座取代八字。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻農民曆）" },
      { id: "ama-marriage-015-g", text: "合八字我建議加做心理測驗。", archetype: "backfire", retort: "（阿嬤白眼，繼續翻農民曆）" },
      { id: "ama-marriage-015-h", text: "這種老東西不用信啦，阿嬤。", archetype: "landmine", retort: "……好，阿嬤不提了。" },
    ],
  },
  {
    id: "ama-marriage-016",
    text: "你小時候玩伴，小孩都上小學了。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-016-a", text: "阿嬤放心，我在準備給孩子一個好阿嬤。", archetype: "perfect", retort: "哎唷，你這孩子最貼心了。" },
      { id: "ama-marriage-016-b", text: "玩伴的小孩，改天帶來給阿嬤看看。", archetype: "deflect", retort: "好啊，阿嬤最喜歡看小孩。" },
      { id: "ama-marriage-016-c", text: "阿嬤帶大的孩子，步調本來就特別。", archetype: "deflect", retort: "哎唷，這句話說得真好聽。" },
      { id: "ama-marriage-016-d", text: "大家的步調真的都不一樣……", archetype: "meek", retort: "步調不一樣，但也別太晚了。" },
      { id: "ama-marriage-016-e", text: "我還沒準備好要當爸媽……", archetype: "meek", retort: "準備好要花多久時間呢？" },
      { id: "ama-marriage-016-f", text: "我打算走晚熟型父母路線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨玩伴）" },
      { id: "ama-marriage-016-g", text: "我還在等系統更新到適婚版本。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續碎念）" },
      { id: "ama-marriage-016-h", text: "不要拿別人小孩來比我好嗎。", archetype: "landmine", retort: "……好，阿嬤不比了。" },
    ],
  },
  {
    id: "ama-marriage-017",
    text: "你到底喜歡什麼樣的人啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-017-a", text: "我喜歡阿嬤這種會做飯又疼人的。", archetype: "perfect", retort: "哎唷，那你要去哪裡找第二個阿嬤。" },
      { id: "ama-marriage-017-b", text: "阿嬤覺得什麼樣的人適合我？", archetype: "deflect", retort: "善良、顧家的最適合你。" },
      { id: "ama-marriage-017-c", text: "阿嬤當年怎麼看上阿公的？", archetype: "deflect", retort: "他那時候老實又肯做事。" },
      { id: "ama-marriage-017-d", text: "其實我自己也還在摸索……", archetype: "meek", retort: "摸索也要有個方向啊，孩子。" },
      { id: "ama-marriage-017-e", text: "感覺條件講出來很難達成……", archetype: "meek", retort: "條件不用太多，合得來最重要。" },
      { id: "ama-marriage-017-f", text: "我喜歡個性像貓一樣的人。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續問細節）" },
      { id: "ama-marriage-017-g", text: "我在找一個能跟我打電動的人。", archetype: "backfire", retort: "（阿嬤一臉困惑地看你）" },
      { id: "ama-marriage-017-h", text: "喜歡什麼樣的人不用你決定。", archetype: "landmine", retort: "……阿嬤只是隨口問問。" },
    ],
  },
  {
    id: "ama-marriage-018",
    text: "帶對象回來，阿嬤包紅包給他。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-018-a", text: "阿嬤的紅包，會讓對方更愛我們家。", archetype: "perfect", retort: "哎唷，那我要包大一點才行。" },
      { id: "ama-marriage-018-b", text: "阿嬤別急著包，先讓我把人追到手。", archetype: "deflect", retort: "好啦，阿嬤等你把人追到。" },
      { id: "ama-marriage-018-c", text: "阿嬤的心意，比紅包更讓人感動。", archetype: "deflect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-marriage-018-d", text: "現在連對象都還沒有，太早了……", archetype: "meek", retort: "太早也要先準備起來啊。" },
      { id: "ama-marriage-018-e", text: "這個真的還很遙遠，別太期待……", archetype: "meek", retort: "期待一下也不行嗎，孩子。" },
      { id: "ama-marriage-018-f", text: "紅包的事我建議改發虛擬貨幣。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盤算金額）" },
      { id: "ama-marriage-018-g", text: "未來的對象我打算用抽獎決定。", archetype: "backfire", retort: "（阿嬤白眼，繼續盤算紅包）" },
      { id: "ama-marriage-018-h", text: "對象的事還沒有，不要先想這些。", archetype: "landmine", retort: "……好，阿嬤先不想了。" },
    ],
  },
  {
    id: "ama-marriage-019",
    text: "是不是分手了，才都不提對象？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-019-a", text: "阿嬤好敏銳，不過我是在單身充電。", archetype: "perfect", retort: "哎唷，充電充久一點也沒關係。" },
      { id: "ama-marriage-019-b", text: "阿嬤怎麼猜到的，太厲害了吧。", archetype: "deflect", retort: "阿嬤這雙眼睛，什麼都看得出。" },
      { id: "ama-marriage-019-c", text: "阿嬤別擔心我，先擔心你的血壓。", archetype: "deflect", retort: "哎唷，換你來管阿嬤了。" },
      { id: "ama-marriage-019-d", text: "對，最近真的分開了……", archetype: "meek", retort: "怎麼沒早點跟阿嬤說呢？" },
      { id: "ama-marriage-019-e", text: "是有一些狀況，還在調適……", archetype: "meek", retort: "調適的時候要多回來吃飯。" },
      { id: "ama-marriage-019-f", text: "我這叫策略性單身，不是分手。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-019-g", text: "分手是為了給彼此升級空間。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-019-h", text: "分不分手不用你一直問啦。", archetype: "landmine", retort: "……好，阿嬤不問了。" },
    ],
  },
  {
    id: "ama-marriage-020",
    text: "阿嬤幫你安排一場相親，好不好？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-020-a", text: "阿嬤安排的，我保證準時盛裝出席。", archetype: "perfect", retort: "哎唷，這麼給面子，阿嬤開心。" },
      { id: "ama-marriage-020-b", text: "阿嬤先跟我說說，對方是什麼樣的人？", archetype: "deflect", retort: "是隔壁李桑的孫女，很乖。" },
      { id: "ama-marriage-020-c", text: "阿嬤的眼光，我一直都很信任。", archetype: "deflect", retort: "那當然，阿嬤看人很準。" },
      { id: "ama-marriage-020-d", text: "相親這件事，我還沒心理準備……", archetype: "meek", retort: "準備好要等到什麼時候啊？" },
      { id: "ama-marriage-020-e", text: "最近工作真的太忙，抽不出時間……", archetype: "meek", retort: "忙也要抽個一小時見一面。" },
      { id: "ama-marriage-020-f", text: "相親前我要先請造型師來一趟。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續安排時間）" },
      { id: "ama-marriage-020-g", text: "這場相親我要準備開場才藝。", archetype: "backfire", retort: "（阿嬤白眼，逕自訂好餐廳）" },
      { id: "ama-marriage-020-h", text: "不要隨便幫我安排相親啦。", archetype: "landmine", retort: "……好，阿嬤不安排了。" },
    ],
  },
  {
    id: "ama-marriage-021",
    text: "你們是不是已經住在一起了？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-021-a", text: "阿嬤真敏銳，不過我最想同居的是你。", archetype: "perfect", retort: "哎唷，你這孩子最會撒嬌。" },
      { id: "ama-marriage-021-b", text: "阿嬤關心這個，是想幫忙布置新家？", archetype: "deflect", retort: "當然，我最會布置了。" },
      { id: "ama-marriage-021-c", text: "阿嬤當年跟阿公也是先住一起吧？", archetype: "deflect", retort: "我們那時候規矩多，不一樣。" },
      { id: "ama-marriage-021-d", text: "對，最近確實住一起了……", archetype: "meek", retort: "怎麼都沒跟阿嬤說一聲呢？" },
      { id: "ama-marriage-021-e", text: "有時候會過夜，還沒完全搬過去……", archetype: "meek", retort: "這種事要跟阿嬤講清楚啊。" },
      { id: "ama-marriage-021-f", text: "那個只是室友式的同居而已。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-021-g", text: "同居是為了測試生活默契。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-021-h", text: "住哪裡不用你管好不好。", archetype: "landmine", retort: "……阿嬤只是關心而已。" },
    ],
  },
] satisfies Question[];
