import type { Question } from "@/content/types";

// situations: 002 問你有沒有交往對象 / 003 問你什麼時候結婚 / 004 看老照片說阿嬤當年嫁人的年紀
// 005 說要留房間給你以後住 / 006 說鄰居陳太太孫子訂婚了 / 007 拿出戒指要傳給你
// 008 問對方家在哪裡做什麼 / 009 說想在走之前抱曾孫 / 010 問你是不是眼光太高
// 011 說廟口誰家孩子要介紹 / 012 問朋友圈有沒有合適的人 / 013 翻你手機看有沒有交友軟體
// 014 問對方會不會煮飯顧家 / 015 說要拿八字去合一下 / 016 提起小時候玩伴已當爸媽
// 017 問你到底喜歡什麼樣的人 / 018 說要包紅包給未來另一半 / 019 問你是不是分手了才不提
// 020 說想幫你安排相親 / 021 問你們是不是同居了
export default [
  {
    id: "ama-marriage-002",
    text: "現在有沒有在跟誰交往啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-002-a", text: "幹，三姑愛管，阿嬤問我才想老實講。", archetype: "perfect", retort: "哎唷，阿嬤最愛聽你這樣講。" },
      { id: "ama-marriage-002-b", text: "阿嬤想幫我介紹厚？靠，先說條件。", archetype: "deflect", retort: "喔，那要找孝順顧家的才行。" },
      { id: "ama-marriage-002-c", text: "阿嬤先講，你當年怎麼追阿公的？", archetype: "deflect", retort: "那個時候喔，阿公可主動了。" },
      { id: "ama-marriage-002-d", text: "還沒有啦，幹，工作真的太忙了……", archetype: "meek", retort: "忙也要留點時間給感情啦。" },
      { id: "ama-marriage-002-e", text: "有在聊天啦，靠，但還沒確定……", archetype: "meek", retort: "聊天要聊到什麼時候才確定？" },
      { id: "ama-marriage-002-f", text: "我現在是走，去你的單身貴族路線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續夾菜）" },
      { id: "ama-marriage-002-g", text: "緣分這東西，機掰隨緣就好啦。", archetype: "backfire", retort: "（阿嬤沒接話，繼續夾菜）" },
      { id: "ama-marriage-002-h", text: "幹，很煩耶，別再問感情的事了！", archetype: "landmine", retort: "……好，阿嬤不問了。（安靜夾菜）" },
    ],
  },
  {
    id: "ama-marriage-003",
    text: "你什麼時候要結婚？阿嬤等著喝喜酒。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-003-a", text: "幹，喜酒我請客，比三姑包的大碗。", archetype: "perfect", retort: "哎唷，這麼實在，阿嬤放心了。" },
      { id: "ama-marriage-003-b", text: "阿嬤身體顧好，靠，才能等到那天。", archetype: "deflect", retort: "放心，阿嬤會等到那一天。" },
      { id: "ama-marriage-003-c", text: "先倒一杯給阿嬤，練習當主婚人。", archetype: "deflect", retort: "臭小子，還會反過來哄我。" },
      { id: "ama-marriage-003-d", text: "還沒計畫啦，幹，順其自然……", archetype: "meek", retort: "順其自然要等到什麼時候？" },
      { id: "ama-marriage-003-e", text: "對象都沒有，靠，怎麼結婚……", archetype: "meek", retort: "沒對象就快去找一個啊！" },
      { id: "ama-marriage-003-f", text: "我打算辦流水席，去你的公證。", archetype: "backfire", retort: "（阿嬤聽不懂，繼續問細節）" },
      { id: "ama-marriage-003-g", text: "我在等良辰吉時，機掰運勢降臨。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續夾菜）" },
      { id: "ama-marriage-003-h", text: "他媽的，老太婆別催我結婚，很煩！", archetype: "landmine", retort: "……好，阿嬤不提了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-004",
    text: "你看，阿嬤這年紀就嫁給你阿公了。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-004-a", text: "幹，阿公沒眼光哪比得上妳，比大伯強。", archetype: "perfect", retort: "哎唷，你這孩子嘴巴真甜。" },
      { id: "ama-marriage-004-b", text: "這張照片，靠，可以拿去裱框了。", archetype: "deflect", retort: "好啊，改天真的裱起來。" },
      { id: "ama-marriage-004-c", text: "阿嬤跟阿公的故事，講給我聽好嗎？", archetype: "deflect", retort: "好啊，改天慢慢跟你講。" },
      { id: "ama-marriage-004-d", text: "時代不一樣了，幹，比較晚啦……", archetype: "meek", retort: "晚是晚，但也不能太晚啊。" },
      { id: "ama-marriage-004-e", text: "身邊很多人都還單身，靠，正常……", archetype: "meek", retort: "單身也要有個目標啊，孩子。" },
      { id: "ama-marriage-004-f", text: "那時候結婚，去你的通膨比較划算。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻相簿）" },
      { id: "ama-marriage-004-g", text: "我要研究一下當年行情，機掰穿越。", archetype: "backfire", retort: "（阿嬤白眼，翻下一頁）" },
      { id: "ama-marriage-004-h", text: "去你的，別拿以前跟現在比，很煩！", archetype: "landmine", retort: "……好，阿嬤不比了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-005",
    text: "這房間留給你，以後帶對象住。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-005-a", text: "幹，這房間比三舅媽存的頭期款值錢。", archetype: "perfect", retort: "哎唷，住多久阿嬤都歡迎。" },
      { id: "ama-marriage-005-b", text: "阿嬤自己也留個好房間，靠，養生。", archetype: "deflect", retort: "阿嬤這間住習慣了，不換。" },
      { id: "ama-marriage-005-c", text: "這房間布置得真溫馨，謝謝阿嬤。", archetype: "deflect", retort: "喜歡就好，隨時回來住。" },
      { id: "ama-marriage-005-d", text: "一個人住習慣了，幹，是有點孤單……", archetype: "meek", retort: "一個人住太孤單了啦。" },
      { id: "ama-marriage-005-e", text: "對象的事，靠，真的還沒著落……", archetype: "meek", retort: "著落要自己去找，別等天上掉！" },
      { id: "ama-marriage-005-f", text: "我要把房間改錄音室，去你的家具。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續說房間規劃）" },
      { id: "ama-marriage-005-g", text: "我打算把房間出租，機掰包租公。", archetype: "backfire", retort: "（阿嬤瞪你一眼，沒再說話）" },
      { id: "ama-marriage-005-h", text: "機掰，房間的事先別想那麼遠，很煩！", archetype: "landmine", retort: "……好，阿嬤不想了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-006",
    text: "隔壁陳太太孫子都訂婚了，你呢？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-006-a", text: "幹，我的喜事比陳太太的八卦精彩。", archetype: "perfect", retort: "哎唷，你這孩子最會安慰人。" },
      { id: "ama-marriage-006-b", text: "訂婚要包紅包，靠，記得等一下去。", archetype: "deflect", retort: "對厚，等一下就去包。" },
      { id: "ama-marriage-006-c", text: "阿嬤消息真靈通，跟誰打聽的？", archetype: "deflect", retort: "當然是陳太太親口說的。" },
      { id: "ama-marriage-006-d", text: "我這邊真的沒消息，幹，還沒著落……", archetype: "meek", retort: "沒消息要自己去努力找啊。" },
      { id: "ama-marriage-006-e", text: "大家步調不一樣，靠，我還在忙工作……", archetype: "meek", retort: "工作忙也要顧感情才行啊。" },
      { id: "ama-marriage-006-f", text: "訂婚而已，我要去你的直接結婚超車。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨陳太太）" },
      { id: "ama-marriage-006-g", text: "我在等一個更浪漫的機掰求婚方案。", archetype: "backfire", retort: "（阿嬤半信半疑地點頭）" },
      { id: "ama-marriage-006-h", text: "去你的，老東西別拿孫子比較，很煩！", archetype: "landmine", retort: "……好，阿嬤不比了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-007",
    text: "這只戒指，阿嬤想留給你以後用。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-007-a", text: "幹，這戒指我收好，比三姑的嘴巴牢。", archetype: "perfect", retort: "哎唷，你這孩子最懂阿嬤的心。" },
      { id: "ama-marriage-007-b", text: "這麼珍貴的東西，靠，自己留著戴。", archetype: "deflect", retort: "戴著也是想著要傳給你。" },
      { id: "ama-marriage-007-c", text: "這戒指有故事嗎？講給我聽。", archetype: "deflect", retort: "這是阿公當年送的，有故事。" },
      { id: "ama-marriage-007-d", text: "怕弄丟，幹，還是先讓阿嬤保管……", archetype: "meek", retort: "那就先放阿嬤這裡，別急。" },
      { id: "ama-marriage-007-e", text: "現在真的用不上，靠，這個……", archetype: "meek", retort: "用不上也要收好，以後會用到。" },
      { id: "ama-marriage-007-f", text: "我要拿去鑑定節目估價，去你的行情。", archetype: "backfire", retort: "（阿嬤沒聽懂，把戒指收起來）" },
      { id: "ama-marriage-007-g", text: "這戒指感覺可以當傳家寶賣，機掰。", archetype: "backfire", retort: "（阿嬤白眼，把戒指收好）" },
      { id: "ama-marriage-007-h", text: "幹你娘，這種東西先不要提，很煩！", archetype: "landmine", retort: "……好，阿嬤收起來了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-008",
    text: "那個人是做什麼的？家住哪裡？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-008-a", text: "幹，人品比三舅媽在意的職業重要。", archetype: "perfect", retort: "哎唷，這句話講到阿嬤心坎裡。" },
      { id: "ama-marriage-008-b", text: "阿嬤想知道，靠，是不是要幫我把關？", archetype: "deflect", retort: "當然，阿嬤的眼光最準。" },
      { id: "ama-marriage-008-c", text: "等確定了，第一個帶來給阿嬤看。", archetype: "deflect", retort: "好，阿嬤等你這句話。" },
      { id: "ama-marriage-008-d", text: "都還沒到那階段，幹，不好意思問……", archetype: "meek", retort: "不問怎麼知道人品好不好？" },
      { id: "ama-marriage-008-e", text: "這個真的還沒問清楚，靠……", archetype: "meek", retort: "沒問清楚怎麼放心交往？" },
      { id: "ama-marriage-008-f", text: "職業家世我打算抽籤決定，去你的緣分。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-008-g", text: "這是身家調查嗎，機掰我要請律師。", archetype: "backfire", retort: "（阿嬤白眼，繼續追問細節）" },
      { id: "ama-marriage-008-h", text: "去死啦，這些不用妳查戶口，很煩！", archetype: "landmine", retort: "……好，阿嬤不問了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-009",
    text: "阿嬤想在走之前抱到你的小孩。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-009-a", text: "幹，阿嬤要抱曾孫，比三姑活得久精彩。", archetype: "perfect", retort: "哎唷，你這孩子講話真好聽。" },
      { id: "ama-marriage-009-b", text: "阿嬤先把身體養好，靠，我們才有希望。", archetype: "deflect", retort: "好，阿嬤會好好照顧自己。" },
      { id: "ama-marriage-009-c", text: "阿嬤想抱曾孫，先抱抱我這個孫子。", archetype: "deflect", retort: "好啦好啦，過來讓阿嬤抱。" },
      { id: "ama-marriage-009-d", text: "這個真的還早，幹，自己都沒穩定……", archetype: "meek", retort: "穩定了才要快點加油啊。" },
      { id: "ama-marriage-009-e", text: "這種事沒辦法用等的，靠，急不來……", archetype: "meek", retort: "急不來也要往那方向努力啊。" },
      { id: "ama-marriage-009-f", text: "曾孫的事我先預約名額，去你的排隊。", archetype: "backfire", retort: "（阿嬤沒聽懂，還是很期待）" },
      { id: "ama-marriage-009-g", text: "我打算先養隻貓，機掰練習當爸媽。", archetype: "backfire", retort: "（阿嬤一臉不解，繼續念）" },
      { id: "ama-marriage-009-h", text: "幹你娘咧，死老太婆別拿這種話壓我！", archetype: "landmine", retort: "……阿嬤只是想看到而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-010",
    text: "是不是你眼光太高才沒對象？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-010-a", text: "幹，阿嬤把我教太好，眼光比表姊挑。", archetype: "perfect", retort: "哎唷，這是誇阿嬤還是誇你自己。" },
      { id: "ama-marriage-010-b", text: "阿嬤覺得什麼樣的人才配得上我？", archetype: "deflect", retort: "當然是要對你好的人才行。" },
      { id: "ama-marriage-010-c", text: "阿嬤眼光那麼好，靠，幫我掌掌眼吧。", archetype: "deflect", retort: "好啊，改天阿嬤幫你看看。" },
      { id: "ama-marriage-010-d", text: "也許吧，幹，可能真的比較挑……", archetype: "meek", retort: "挑是可以，但也別太挑了。" },
      { id: "ama-marriage-010-e", text: "我覺得應該是緣分還沒到，靠……", archetype: "meek", retort: "緣分不會自己來，要主動一點！" },
      { id: "ama-marriage-010-f", text: "我這叫寧缺勿濫，去你的高級單身。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-010-g", text: "我是在等對的人，機掰貴族路線。", archetype: "backfire", retort: "（阿嬤白眼，繼續碎念）" },
      { id: "ama-marriage-010-h", text: "幹，不是眼光高，是你們太急了！", archetype: "landmine", retort: "……阿嬤只是希望你幸福。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-011",
    text: "廟口張阿姨的孫女不錯，見一面？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-011-a", text: "幹，阿嬤介紹的比相親市場慎重多了。", archetype: "perfect", retort: "哎唷，慎重是對的，阿嬤陪你去。" },
      { id: "ama-marriage-011-b", text: "阿嬤先幫我探探，靠，對方喜歡吃什麼。", archetype: "deflect", retort: "好，阿嬤明天就去問。" },
      { id: "ama-marriage-011-c", text: "阿嬤的眼光這麼準，我很期待。", archetype: "deflect", retort: "那當然，阿嬤看人很準。" },
      { id: "ama-marriage-011-d", text: "我最近真的沒空，幹，約會太累……", archetype: "meek", retort: "沒空也要抽個時間見一面。" },
      { id: "ama-marriage-011-e", text: "相親這種事，靠，我還沒準備好……", archetype: "meek", retort: "準備好要等到什麼時候？" },
      { id: "ama-marriage-011-f", text: "我要先做簡報自我介紹，去你的履歷。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續安排時間）" },
      { id: "ama-marriage-011-g", text: "這算不算相親界的面試，機掰。", archetype: "backfire", retort: "（阿嬤白眼，逕自約時間）" },
      { id: "ama-marriage-011-h", text: "他媽的，不要隨便幫我安排相親！", archetype: "landmine", retort: "……好，阿嬤不安排了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-012",
    text: "你朋友那麼多，沒有一個合適的？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-012-a", text: "幹，最合適的是常回家看妳的我，比三姑孝順。", archetype: "perfect", retort: "哎唷，你這孩子真的很會講。" },
      { id: "ama-marriage-012-b", text: "阿嬤覺得什麼樣的朋友算合適？", archetype: "deflect", retort: "孝順、顧家的最合適。" },
      { id: "ama-marriage-012-c", text: "阿嬤這麼關心，靠，要不要幫我物色？", archetype: "deflect", retort: "好啊，阿嬤幫你留意留意。" },
      { id: "ama-marriage-012-d", text: "朋友是朋友，幹，感情真的沒那麼順……", archetype: "meek", retort: "沒那麼順利也要多試試看。" },
      { id: "ama-marriage-012-e", text: "大家好像都比較晚，靠，定下來……", archetype: "meek", retort: "晚也要有個譜，別拖太久。" },
      { id: "ama-marriage-012-f", text: "我朋友圈都走生涯發展，去你的路線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-marriage-012-g", text: "我在朋友圈搞地下配對，機掰事業。", archetype: "backfire", retort: "（阿嬤半信半疑地看你）" },
      { id: "ama-marriage-012-h", text: "去你的，老太婆別管我朋友的事！", archetype: "landmine", retort: "……好，阿嬤不問了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-013",
    text: "你手機裡是不是有交友軟體？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-013-a", text: "幹，手機最重要的是妳的照片，比軟體實在。", archetype: "perfect", retort: "哎唷，你這孩子最會哄阿嬤。" },
      { id: "ama-marriage-013-b", text: "阿嬤想看我手機，靠，是想看照片吧。", archetype: "deflect", retort: "對啊，想看你最近過得好不好。" },
      { id: "ama-marriage-013-c", text: "阿嬤自己有沒有想學用手機交朋友？", archetype: "deflect", retort: "我這把年紀，不用學那個了。" },
      { id: "ama-marriage-013-d", text: "有下載啦，幹，但一直沒認真用……", archetype: "meek", retort: "下載了就要認真用啊！" },
      { id: "ama-marriage-013-e", text: "是有一兩個，靠，還在觀望……", archetype: "meek", retort: "觀望什麼，主動一點才行！" },
      { id: "ama-marriage-013-f", text: "那個只是練習聊天，去你的技巧課。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-013-g", text: "我下載是為了機掰研究市場趨勢。", archetype: "backfire", retort: "（阿嬤白眼，伸手要看手機）" },
      { id: "ama-marriage-013-h", text: "機掰，不要翻我手機，這是隱私！", archetype: "landmine", retort: "……好，阿嬤不翻了。（放下手機）" },
    ],
  },
  {
    id: "ama-marriage-014",
    text: "那個人會不會煮飯？顧不顧家？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-014-a", text: "幹，煮飯手藝跟妳學，比三舅媽的食譜強。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好驕傲。" },
      { id: "ama-marriage-014-b", text: "阿嬤煮飯這麼厲害，靠，要不要開課？", archetype: "deflect", retort: "哎唷，開課我可不敢。" },
      { id: "ama-marriage-014-c", text: "阿嬤覺得顧家最重要的是什麼？", archetype: "deflect", retort: "是願不願意為家人多想一點。" },
      { id: "ama-marriage-014-d", text: "這個我還真的沒問，幹，忘了問……", archetype: "meek", retort: "這麼重要的事怎麼能不問？" },
      { id: "ama-marriage-014-e", text: "感覺對方比較不擅長，靠，做家事……", archetype: "meek", retort: "不擅長可以學，重點是有心。" },
      { id: "ama-marriage-014-f", text: "煮飯的事我打算外包，去你的Uber Eats。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-014-g", text: "顧家這件事我覺得，機掰AI比較行。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續問）" },
      { id: "ama-marriage-014-h", text: "去你的，這些事不用妳操心啦，很煩！", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-015",
    text: "要不要拿你們的八字去合一下？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-015-a", text: "幹，阿嬤看的八字比命理老師和三姑都準。", archetype: "perfect", retort: "哎唷，你這句話講得阿嬤開心。" },
      { id: "ama-marriage-015-b", text: "阿嬤懂八字，靠，改天教教我基礎。", archetype: "deflect", retort: "好啊，改天教你怎麼看。" },
      { id: "ama-marriage-015-c", text: "阿嬤覺得我跟阿嬤八字合不合？", archetype: "deflect", retort: "我們祖孫這麼合，當然合。" },
      { id: "ama-marriage-015-d", text: "對方好像不太信這個，幹，尷尬……", archetype: "meek", retort: "不信也可以私下幫他看看。" },
      { id: "ama-marriage-015-e", text: "這個我還沒想到那麼遠，靠……", archetype: "meek", retort: "該想的時候要提早想啊。" },
      { id: "ama-marriage-015-f", text: "我打算用星座取代八字，去你的塔羅。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻農民曆）" },
      { id: "ama-marriage-015-g", text: "合八字我建議加做，機掰心理測驗。", archetype: "backfire", retort: "（阿嬤白眼，繼續翻農民曆）" },
      { id: "ama-marriage-015-h", text: "幹你娘，老東西這種八字不用信！", archetype: "landmine", retort: "……好，阿嬤不提了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-016",
    text: "你小時候玩伴，小孩都上小學了。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-016-a", text: "幹，我在準備給孩子好阿嬤，比大伯稱職。", archetype: "perfect", retort: "哎唷，你這孩子最貼心了。" },
      { id: "ama-marriage-016-b", text: "玩伴的小孩，靠，改天帶來給妳看看。", archetype: "deflect", retort: "好啊，阿嬤最喜歡看小孩。" },
      { id: "ama-marriage-016-c", text: "阿嬤帶大的孩子，步調本來就特別。", archetype: "deflect", retort: "哎唷，這句話說得真好聽。" },
      { id: "ama-marriage-016-d", text: "大家的步調真的不一樣，幹，別急……", archetype: "meek", retort: "步調不一樣，但也別太晚了。" },
      { id: "ama-marriage-016-e", text: "我還沒準備好，靠，要當爸媽……", archetype: "meek", retort: "準備好要花多久時間呢？" },
      { id: "ama-marriage-016-f", text: "我打算走晚熟型父母，去你的育兒書。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨玩伴）" },
      { id: "ama-marriage-016-g", text: "我還在等系統更新，機掰適婚版本。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續碎念）" },
      { id: "ama-marriage-016-h", text: "去死啦，不要拿別人小孩比我，很煩！", archetype: "landmine", retort: "……好，阿嬤不比了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-017",
    text: "你到底喜歡什麼樣的人啊？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-017-a", text: "幹，我喜歡妳這種會做飯疼人的，表姊老公比不上。", archetype: "perfect", retort: "哎唷，那你要去哪裡找第二個阿嬤。" },
      { id: "ama-marriage-017-b", text: "阿嬤覺得什麼樣的人適合我？", archetype: "deflect", retort: "善良、顧家的最適合你。" },
      { id: "ama-marriage-017-c", text: "阿嬤當年怎麼看上阿公的？靠，好奇。", archetype: "deflect", retort: "他那時候老實又肯做事。" },
      { id: "ama-marriage-017-d", text: "其實我自己也還在摸索，幹，迷茫……", archetype: "meek", retort: "摸索也要有個方向啊，孩子。" },
      { id: "ama-marriage-017-e", text: "感覺條件講出來很難達成，靠……", archetype: "meek", retort: "條件不用太多，合得來最重要。" },
      { id: "ama-marriage-017-f", text: "我喜歡個性像貓，去你的高冷型。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續問細節）" },
      { id: "ama-marriage-017-g", text: "我在找能跟我打電動，機掰的隊友。", archetype: "backfire", retort: "（阿嬤一臉困惑地看你）" },
      { id: "ama-marriage-017-h", text: "幹你娘咧，喜歡誰不用妳決定！", archetype: "landmine", retort: "……阿嬤只是隨口問問。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-018",
    text: "帶對象回來，阿嬤包紅包給他。",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-018-a", text: "幹，妳的紅包會讓對方比看三姑臉色更愛我家。", archetype: "perfect", retort: "哎唷，那我要包大一點才行。" },
      { id: "ama-marriage-018-b", text: "阿嬤別急著包，靠，先讓我把人追到手。", archetype: "deflect", retort: "好啦，阿嬤等你把人追到。" },
      { id: "ama-marriage-018-c", text: "阿嬤的心意，比紅包更讓人感動。", archetype: "deflect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-marriage-018-d", text: "現在連對象都沒有，幹，太早了……", archetype: "meek", retort: "太早也要先準備起來啊。" },
      { id: "ama-marriage-018-e", text: "這個真的還很遙遠，靠，別太期待……", archetype: "meek", retort: "期待一下也不行嗎，孩子。" },
      { id: "ama-marriage-018-f", text: "紅包的事我建議改發，去你的虛擬貨幣。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續盤算金額）" },
      { id: "ama-marriage-018-g", text: "未來的對象我打算，機掰用抽獎決定。", archetype: "backfire", retort: "（阿嬤白眼，繼續盤算紅包）" },
      { id: "ama-marriage-018-h", text: "幹，老不死的想這麼多幹嘛，很煩！", archetype: "landmine", retort: "……好，阿嬤先不想了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-019",
    text: "是不是分手了，才都不提對象？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-019-a", text: "幹，阿嬤好敏銳，我是單身充電，比表哥久。", archetype: "perfect", retort: "哎唷，充電充久一點也沒關係。" },
      { id: "ama-marriage-019-b", text: "阿嬤怎麼猜到的，靠，太厲害了吧。", archetype: "deflect", retort: "阿嬤這雙眼睛，什麼都看得出。" },
      { id: "ama-marriage-019-c", text: "阿嬤別擔心我，先擔心你的血壓。", archetype: "deflect", retort: "哎唷，換你來管阿嬤了。" },
      { id: "ama-marriage-019-d", text: "對，最近真的分開了，幹，難過……", archetype: "meek", retort: "怎麼沒早點跟阿嬤說呢？" },
      { id: "ama-marriage-019-e", text: "是有一些狀況，靠，還在調適……", archetype: "meek", retort: "調適的時候要多回來吃飯。" },
      { id: "ama-marriage-019-f", text: "我這叫策略性單身，去你的分手論。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-019-g", text: "分手是為了機掰給彼此升級空間。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-019-h", text: "他媽的，分不分手不用妳一直問！", archetype: "landmine", retort: "……好，阿嬤不問了。（安靜）" },
    ],
  },
  {
    id: "ama-marriage-020",
    text: "阿嬤幫你安排一場相親，好不好？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-020-a", text: "幹，阿嬤安排的比相親市場準時盛裝出席。", archetype: "perfect", retort: "哎唷，這麼給面子，阿嬤開心。" },
      { id: "ama-marriage-020-b", text: "阿嬤先跟我說說，靠，對方是什麼樣的人？", archetype: "deflect", retort: "是隔壁李桑的孫女，很乖。" },
      { id: "ama-marriage-020-c", text: "阿嬤的眼光，我一直都很信任。", archetype: "deflect", retort: "那當然，阿嬤看人很準。" },
      { id: "ama-marriage-020-d", text: "相親這件事，幹，我還沒心理準備……", archetype: "meek", retort: "準備好要等到什麼時候啊？" },
      { id: "ama-marriage-020-e", text: "最近工作真的太忙，靠，抽不出時間……", archetype: "meek", retort: "忙也要抽個一小時見一面。" },
      { id: "ama-marriage-020-f", text: "相親前我要先請造型師，去你的整套。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續安排時間）" },
      { id: "ama-marriage-020-g", text: "這場相親我要準備開場，機掰才藝。", archetype: "backfire", retort: "（阿嬤白眼，逕自訂好餐廳）" },
      { id: "ama-marriage-020-h", text: "去你的，老太婆很閒喔，別亂配對！", archetype: "landmine", retort: "……好，阿嬤不安排了。（低頭）" },
    ],
  },
  {
    id: "ama-marriage-021",
    text: "你們是不是已經住在一起了？",
    topic: "marriage",
    bossId: "ama",
    options: [
      { id: "ama-marriage-021-a", text: "幹，阿嬤真敏銳，我最想同居的是妳，比對象黏。", archetype: "perfect", retort: "哎唷，你這孩子最會撒嬌。" },
      { id: "ama-marriage-021-b", text: "阿嬤關心這個，靠，是想幫忙布置新家？", archetype: "deflect", retort: "當然，我最會布置了。" },
      { id: "ama-marriage-021-c", text: "阿嬤當年跟阿公也是先住一起吧？", archetype: "deflect", retort: "我們那時候規矩多，不一樣。" },
      { id: "ama-marriage-021-d", text: "對，最近確實住一起了，幹，緊張……", archetype: "meek", retort: "怎麼都沒跟阿嬤說一聲呢？" },
      { id: "ama-marriage-021-e", text: "有時候會過夜，靠，還沒完全搬過去……", archetype: "meek", retort: "這種事要跟阿嬤講清楚啊。" },
      { id: "ama-marriage-021-f", text: "那個只是室友式的，去你的合租。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續追問）" },
      { id: "ama-marriage-021-g", text: "同居是為了機掰測試生活默契。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續追問）" },
      { id: "ama-marriage-021-h", text: "機掰，老東西別管我住哪裡，很煩！", archetype: "landmine", retort: "……阿嬤只是關心而已。（安靜）" },
    ],
  },
] satisfies Question[];
