import type { Question } from "@/content/types";

// situations: 022 問你要不要陪她去媽祖遶境進香 / 023 帶你去祖先牌位前上香 / 024 說初一十五要記得拜拜
// 025 說要幫你求個姻緣籤詩 / 026 問你要不要跟神明說心事 / 027 說她每天都幫你點香祈福
// 028 拜拜時念你的生辰八字 / 029 問你信不信這些習俗 / 030 教你跟土地公報名字住址
// 031 說要包香油錢幫你添福 / 032 問你怎麼都不跟阿嬤去拜拜 / 033 帶你去阿公牌位前說說話
// 034 說要幫你收驚因為常忘東忘西 / 035 說要幫你安平安符在新家門口 / 036 說廟公說好久不見你長大了
export default [
  {
    id: "ama-religion-022",
    text: "媽祖遶境要開始了，陪阿嬤去進香。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-022-a", text: "阿嬤走多遠，我就陪你走多遠。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好感動。" },
      { id: "ama-religion-022-b", text: "阿嬤腳力這麼好，我都追不上。", archetype: "deflect", retort: "走習慣了，你要多練練。" },
      { id: "ama-religion-022-c", text: "遶境沿路的小吃，是不是很多？", archetype: "deflect", retort: "當然，邊走邊吃才有力氣。" },
      { id: "ama-religion-022-d", text: "我怕自己體力跟不上遶境……", archetype: "meek", retort: "體力不夠就中途休息一下。" },
      { id: "ama-religion-022-e", text: "我這幾天請假比較困難……", archetype: "meek", retort: "困難也要想辦法排一天啊。" },
      { id: "ama-religion-022-f", text: "遶境是不是媽祖版的路跑比賽。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續準備行李）" },
      { id: "ama-religion-022-g", text: "我要順便練馬拉松體能。", archetype: "backfire", retort: "（阿嬤白眼，繼續準備行李）" },
      { id: "ama-religion-022-h", text: "遶境很累，我真的不想去。", archetype: "landmine", retort: "……好，阿嬤自己去。" },
    ],
  },
  {
    id: "ama-religion-023",
    text: "來，跟祖先牌位上個香問好。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-023-a", text: "我跟祖先說，阿嬤把我照顧得很好。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤想哭。" },
      { id: "ama-religion-023-b", text: "阿嬤每天都來上香，真的很孝順。", archetype: "deflect", retort: "這是本分，不算孝順。" },
      { id: "ama-religion-023-c", text: "這些牌位的故事，講給我聽好嗎？", archetype: "deflect", retort: "好啊，慢慢講給你聽。" },
      { id: "ama-religion-023-d", text: "我對這些長輩的故事不太熟悉……", archetype: "meek", retort: "不熟就更要多聽阿嬤講。" },
      { id: "ama-religion-023-e", text: "我上香的順序常常搞不清楚……", archetype: "meek", retort: "順序不對沒關係，心意到就好。" },
      { id: "ama-religion-023-f", text: "上香是不是要先自我介紹一下。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續上香）" },
      { id: "ama-religion-023-g", text: "祖先看到我這樣，應該會笑吧。", archetype: "backfire", retort: "（阿嬤白眼，繼續上香）" },
      { id: "ama-religion-023-h", text: "這些老規矩不用一直做啦。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-024",
    text: "初一十五記得要拜拜，別忘了。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-024-a", text: "阿嬤放心，我把日子都記在心裡了。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好安心。" },
      { id: "ama-religion-024-b", text: "阿嬤每次都記得比我還清楚。", archetype: "deflect", retort: "這是老習慣了，忘不了。" },
      { id: "ama-religion-024-c", text: "初一十五拜拜，是不是有特別意義？", archetype: "deflect", retort: "是感謝神明保佑一整個月。" },
      { id: "ama-religion-024-d", text: "我平常工作忙，常常會忘記……", archetype: "meek", retort: "忘記了要記得補拜一下。" },
      { id: "ama-religion-024-e", text: "我對這個日子沒什麼概念……", archetype: "meek", retort: "沒概念可以看阿嬤的日曆。" },
      { id: "ama-religion-024-f", text: "這個是不是可以設手機提醒。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續碎念）" },
      { id: "ama-religion-024-g", text: "拜拜這件事我建議訂閱通知。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續碎念）" },
      { id: "ama-religion-024-h", text: "這種日子不用特別記啦，麻煩。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-025",
    text: "幫你求了姻緣籤詩，來看看內容。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-025-a", text: "阿嬤求的籤詩，比任何星座運勢準。", archetype: "perfect", retort: "哎唷，這句話說得阿嬤好開心。" },
      { id: "ama-religion-025-b", text: "阿嬤求籤這麼虔誠，一定會靈驗。", archetype: "deflect", retort: "當然，阿嬤誠心誠意求的。" },
      { id: "ama-religion-025-c", text: "這籤詩上面寫的，是什麼意思？", archetype: "deflect", retort: "上面說緣分快到了，等等看。" },
      { id: "ama-religion-025-d", text: "我最近真的沒有戀愛的跡象……", archetype: "meek", retort: "籤詩說快了，再等等看。" },
      { id: "ama-religion-025-e", text: "姻緣籤詩的內容我不是很懂……", archetype: "meek", retort: "信一點，緣分才會靠近。" },
      { id: "ama-religion-025-f", text: "這籤詩是不是可以線上兌換。", archetype: "backfire", retort: "（阿嬤沒聽懂，收好籤詩）" },
      { id: "ama-religion-025-g", text: "姻緣籤是不是有效期限。", archetype: "backfire", retort: "（阿嬤白眼，收好籤詩）" },
      { id: "ama-religion-025-h", text: "這種籤詩都亂寫的，別當真。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-026",
    text: "要不要跟神明說說你的心事？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-026-a", text: "我只想跟神明說，謝謝祂讓我有阿嬤。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤想哭。" },
      { id: "ama-religion-026-b", text: "阿嬤才是我最想說心事的對象。", archetype: "deflect", retort: "哎唷，阿嬤隨時都在聽。" },
      { id: "ama-religion-026-c", text: "神明會不會嫌我心事太多？", archetype: "deflect", retort: "神明才不會嫌，儘管說。" },
      { id: "ama-religion-026-d", text: "其實最近工作壓力真的很大……", archetype: "meek", retort: "壓力大更要跟神明說一說。" },
      { id: "ama-religion-026-e", text: "我不太習慣說出自己的心事……", archetype: "meek", retort: "不習慣沒關係，慢慢說。" },
      { id: "ama-religion-026-f", text: "心事我打算改用匿名信箱投遞。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續等你說）" },
      { id: "ama-religion-026-g", text: "神明的信箱是不是有已讀不回。", archetype: "backfire", retort: "（阿嬤白眼，繼續等你說）" },
      { id: "ama-religion-026-h", text: "這些心事不用跟神明講啦。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-027",
    text: "阿嬤每天都幫你點香祈福喔。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-027-a", text: "阿嬤天天點的香，是我最強的靠山。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好感動。" },
      { id: "ama-religion-027-b", text: "阿嬤自己也要顧好身體才行。", archetype: "deflect", retort: "放心，阿嬤身體硬朗得很。" },
      { id: "ama-religion-027-c", text: "阿嬤每天都這麼虔誠，太厲害了。", archetype: "deflect", retort: "這是阿嬤每天的功課。" },
      { id: "ama-religion-027-d", text: "我都不知道阿嬤這麼用心……", archetype: "meek", retort: "當然，你是阿嬤的心頭肉。" },
      { id: "ama-religion-027-e", text: "我平常都沒特別注意到這件事……", archetype: "meek", retort: "以後要多留意阿嬤的付出。" },
      { id: "ama-religion-027-f", text: "這個是不是可以申請訂閱服務。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續點香）" },
      { id: "ama-religion-027-g", text: "每天點香是不是變成KPI了。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續點香）" },
      { id: "ama-religion-027-h", text: "不用每天特地幫我點香啦。", archetype: "landmine", retort: "……好，阿嬤不點了。" },
    ],
  },
  {
    id: "ama-religion-028",
    text: "拜拜時，阿嬤都會念你的生辰八字。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-028-a", text: "阿嬤把我的生辰記得比我自己還熟。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好窩心。" },
      { id: "ama-religion-028-b", text: "阿嬤的記性這麼好，太厲害了。", archetype: "deflect", retort: "當然，孫子的生日忘不了。" },
      { id: "ama-religion-028-c", text: "念生辰八字，神明才聽得懂吧？", archetype: "deflect", retort: "對，這樣神明才知道是誰。" },
      { id: "ama-religion-028-d", text: "我自己的生辰八字都快忘了……", archetype: "meek", retort: "忘了要問阿嬤，阿嬤都記得。" },
      { id: "ama-religion-028-e", text: "我對這種儀式不太熟悉……", archetype: "meek", retort: "不熟沒關係，阿嬤幫你念。" },
      { id: "ama-religion-028-f", text: "這是不是相當於報身分證字號。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續唸經）" },
      { id: "ama-religion-028-g", text: "念生辰是不是神明界的實名認證。", archetype: "backfire", retort: "（阿嬤白眼，繼續唸經）" },
      { id: "ama-religion-028-h", text: "這些老規矩沒必要一直念啦。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-029",
    text: "你到底信不信這些拜拜習俗？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-029-a", text: "我信阿嬤的心意，比信習俗更多。", archetype: "perfect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-religion-029-b", text: "阿嬤這麼信，我當然跟著一起信。", archetype: "deflect", retort: "信就對了，跟著阿嬤走。" },
      { id: "ama-religion-029-c", text: "阿嬤覺得信仰最重要的是什麼？", archetype: "deflect", retort: "是那份誠心跟感恩的心。" },
      { id: "ama-religion-029-d", text: "老實說，我沒有很篤定……", archetype: "meek", retort: "不篤定也要保持一份尊重。" },
      { id: "ama-religion-029-e", text: "我覺得半信半疑，但也不排斥……", archetype: "meek", retort: "半信半疑也算是有心了。" },
      { id: "ama-religion-029-f", text: "我信科學多一點，習俗少一點。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續拜拜）" },
      { id: "ama-religion-029-g", text: "我覺得信仰可以用數據驗證。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續拜拜）" },
      { id: "ama-religion-029-h", text: "這些習俗都是老一輩的迷信啦。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-030",
    text: "拜土地公要報名字住址，跟著唸。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-030-a", text: "我報名字的時候，特別加了阿嬤的祝福。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好感動。" },
      { id: "ama-religion-030-b", text: "阿嬤報得這麼順，練習很多次吧。", archetype: "deflect", retort: "當然，報了幾十年了。" },
      { id: "ama-religion-030-c", text: "報名字住址，是不是要講台語？", archetype: "deflect", retort: "台語比較道地，跟著唸。" },
      { id: "ama-religion-030-d", text: "我台語不太輪轉，怕唸錯……", archetype: "meek", retort: "唸錯沒關係，慢慢學就好。" },
      { id: "ama-religion-030-e", text: "我常常會忘記自己的地址……", archetype: "meek", retort: "忘記了阿嬤幫你先報一次。" },
      { id: "ama-religion-030-f", text: "這是不是神明版的自我介紹表。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續帶你唸）" },
      { id: "ama-religion-030-g", text: "報地址是不是要順便報星座。", archetype: "backfire", retort: "（阿嬤白眼，繼續帶你唸）" },
      { id: "ama-religion-030-h", text: "這種形式太麻煩了，不想報。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-031",
    text: "幫你包了香油錢，添福添壽。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-031-a", text: "阿嬤包的香油錢，比任何投資都值得。", archetype: "perfect", retort: "哎唷，這句話說得真好聽。" },
      { id: "ama-religion-031-b", text: "阿嬤自己也要留一點用，別都捐了。", archetype: "deflect", retort: "捐出去的福氣會更多。" },
      { id: "ama-religion-031-c", text: "香油錢是不是包多少都有講究？", archetype: "deflect", retort: "心意到了，多少都可以。" },
      { id: "ama-religion-031-d", text: "我覺得添福添壽這種事很難衡量……", archetype: "meek", retort: "難衡量也要有這份心意。" },
      { id: "ama-religion-031-e", text: "我對這種捐獻方式不太了解……", archetype: "meek", retort: "不了解沒關係，阿嬤懂。" },
      { id: "ama-religion-031-f", text: "香油錢是不是可以開發票報稅。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續包錢）" },
      { id: "ama-religion-031-g", text: "添福添壽是不是訂閱制服務。", archetype: "backfire", retort: "（阿嬤白眼，繼續包錢）" },
      { id: "ama-religion-031-h", text: "不用包這些錢啦，浪費而已。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-032",
    text: "你怎麼都不跟阿嬤一起去拜拜？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-032-a", text: "下次一定陪你去，順便牽你的手走。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好期待。" },
      { id: "ama-religion-032-b", text: "阿嬤一個人去，會不會太辛苦？", archetype: "deflect", retort: "不辛苦，走習慣了就好。" },
      { id: "ama-religion-032-c", text: "阿嬤拜拜的虔誠，是我學習的榜樣。", archetype: "deflect", retort: "哎唷，這句話真的很貼心。" },
      { id: "ama-religion-032-d", text: "最近工作時間真的湊不上……", archetype: "meek", retort: "湊不上也要抽個時間陪陪我。" },
      { id: "ama-religion-032-e", text: "我常常週末都在補眠……", archetype: "meek", retort: "補眠也不能忘記陪阿嬤啊。" },
      { id: "ama-religion-032-f", text: "我打算改用視訊陪拜拜。", archetype: "backfire", retort: "（阿嬤沒聽懂，還是很期待）" },
      { id: "ama-religion-032-g", text: "拜拜這件事我可以雲端參與。", archetype: "backfire", retort: "（阿嬤一臉困惑，繼續期待）" },
      { id: "ama-religion-032-h", text: "拜拜的事不用一直找我啦。", archetype: "landmine", retort: "……好，阿嬤自己去。" },
    ],
  },
  {
    id: "ama-religion-033",
    text: "來，去阿公牌位前跟他說說話。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-033-a", text: "阿公，我會替你把阿嬤照顧好。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤紅了眼眶。" },
      { id: "ama-religion-033-b", text: "阿嬤想阿公的時候，都會來這裡吧。", archetype: "deflect", retort: "是啊，每天都會來看看他。" },
      { id: "ama-religion-033-c", text: "阿公當年是什麼樣的人，說給我聽。", archetype: "deflect", retort: "好，阿嬤慢慢說給你聽。" },
      { id: "ama-religion-033-d", text: "我對阿公的印象其實有點模糊……", archetype: "meek", retort: "模糊沒關係，多聽阿嬤說。" },
      { id: "ama-religion-033-e", text: "我不太知道要跟阿公說什麼……", archetype: "meek", retort: "說說近況，阿公會想聽的。" },
      { id: "ama-religion-033-f", text: "跟阿公說話是不是要先連線。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續上香）" },
      { id: "ama-religion-033-g", text: "這算不算陰陽兩界的視訊通話。", archetype: "backfire", retort: "（阿嬤白眼，繼續上香）" },
      { id: "ama-religion-033-h", text: "這種事很奇怪，我不想講話。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
  {
    id: "ama-religion-034",
    text: "你最近常忘東忘西，該去收驚了。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-034-a", text: "忘東忘西是因為滿腦子都是阿嬤煮的菜。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好開心。" },
      { id: "ama-religion-034-b", text: "阿嬤的記性，比我這年輕人還好。", archetype: "deflect", retort: "那當然，阿嬤腦筋清楚得很。" },
      { id: "ama-religion-034-c", text: "收驚是不是也能順便收心？", archetype: "deflect", retort: "對，收一收，做事更專心。" },
      { id: "ama-religion-034-d", text: "最近工作真的太多事要記……", archetype: "meek", retort: "事情多更要去收驚，安個心。" },
      { id: "ama-religion-034-e", text: "我覺得可能只是壓力太大……", archetype: "meek", retort: "壓力大更需要去收驚放鬆。" },
      { id: "ama-religion-034-f", text: "收驚是不是能提升我的記憶體。", archetype: "backfire", retort: "（阿嬤沒聽懂，帶你去收驚）" },
      { id: "ama-religion-034-g", text: "忘東忘西是不是老化前兆啊。", archetype: "backfire", retort: "（阿嬤白眼，帶你去收驚）" },
      { id: "ama-religion-034-h", text: "不用收驚啦，我只是懶而已。", archetype: "landmine", retort: "……好，阿嬤不勉強了。" },
    ],
  },
  {
    id: "ama-religion-035",
    text: "幫你求了符，貼在新家門口保平安。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-035-a", text: "阿嬤貼的符，比裝潢還讓新家有溫度。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好感動。" },
      { id: "ama-religion-035-b", text: "阿嬤這麼細心，連新家都想到了。", archetype: "deflect", retort: "當然，新家也要顧平安。" },
      { id: "ama-religion-035-c", text: "這符貼在門口，會不會太顯眼？", archetype: "deflect", retort: "顯眼才有效，別遮起來。" },
      { id: "ama-religion-035-d", text: "我新家的裝潢比較簡約，怕不搭……", archetype: "meek", retort: "不搭沒關係，平安最重要。" },
      { id: "ama-religion-035-e", text: "我室友可能會覺得奇怪……", archetype: "meek", retort: "跟室友解釋一下就好啦。" },
      { id: "ama-religion-035-f", text: "這符是不是能防房東漲租金。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你貼上）" },
      { id: "ama-religion-035-g", text: "貼符是不是新家的開幕儀式。", archetype: "backfire", retort: "（阿嬤白眼，還是貼上了）" },
      { id: "ama-religion-035-h", text: "新家不要貼這些啦，很土氣。", archetype: "landmine", retort: "……好，阿嬤收回去。" },
    ],
  },
  {
    id: "ama-religion-036",
    text: "廟公說好久不見，你長這麼大了。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-036-a", text: "都是阿嬤每年拜拜時炫耀我長大。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好得意。" },
      { id: "ama-religion-036-b", text: "阿嬤帶我來這麼多年，廟公都認得。", archetype: "deflect", retort: "那當然，我們是老熟人了。" },
      { id: "ama-religion-036-c", text: "廟公還記得我，是不是常聽你提起？", archetype: "deflect", retort: "那當然，逢人就說你的事。" },
      { id: "ama-religion-036-d", text: "我自己都忘記上次來是什麼時候了……", archetype: "meek", retort: "忘記了就要多回來走走啦。" },
      { id: "ama-religion-036-e", text: "我對廟公其實印象不太深……", archetype: "meek", retort: "印象不深也要記得問聲好。" },
      { id: "ama-religion-036-f", text: "長大是不是代表可以自己拜了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續跟廟公聊）" },
      { id: "ama-religion-036-g", text: "廟公是不是廟裡的常駐NPC。", archetype: "backfire", retort: "（阿嬤白眼，繼續跟廟公聊）" },
      { id: "ama-religion-036-h", text: "這種寒暄很煩，我們快走吧。", archetype: "landmine", retort: "你這樣說，阿嬤會難過。" },
    ],
  },
] satisfies Question[];
