import type { Question } from "@/content/types";

// situations: 002 拿平安符要你戴著 / 003 擲筊問你今年運勢 / 004 說要幫你點光明燈
// 005 教你怎麼擺供品 / 006 問你要不要收驚 / 007 說大門口的符要換新的
// 008 說要幫你求姻緣符 / 009 問你出門有沒有拜土地公再走 / 010 說神明保佑你才平安到家
// 011 帶你去廟口拜土地公 / 012 說要幫你求一個香火袋掛車上 / 013 拜拜完要你跟神明鞠躬道謝
// 014 說香爐的香快滿了是好兆頭 / 015 問你有沒有拜拜求工作順利 / 016 說要幫你求平安符放皮夾
// 017 帶你去看農民曆選日子出遠門 / 018 問要不要擲筊問你適不適合搬家
// 019 說廟裡籤詩顯示你今年犯小人 / 020 說要帶你去安太歲因為沖到生肖 / 021 問你為什麼都不拿香拜
export default [
  {
    id: "ama-religion-002",
    text: "這個平安符戴著，出門才安心。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-002-a", text: "幹，阿嬤求的符比三姑的碎念有用多了。", archetype: "perfect", retort: "哎唷，靈不靈啊，看你信不信。" },
      { id: "ama-religion-002-b", text: "阿嬤自己也戴一個，靠，保平安。", archetype: "deflect", retort: "我戴的比你早求的那個。" },
      { id: "ama-religion-002-c", text: "這符是不是廟裡師父特別加持的？", archetype: "deflect", retort: "當然，特別拜託師父的。" },
      { id: "ama-religion-002-d", text: "我怕戴著弄丟，幹，不太敢戴出門……", archetype: "meek", retort: "弄丟就再求一個，別擔心。" },
      { id: "ama-religion-002-e", text: "我平常都戴項鍊，靠，怕會打結……", archetype: "meek", retort: "放皮夾裡也可以，帶著就好。" },
      { id: "ama-religion-002-f", text: "戴這個是不是能，去你的無敵三十天。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你掛上）" },
      { id: "ama-religion-002-g", text: "這符能不能防，機掰我媽念我。", archetype: "backfire", retort: "（阿嬤白眼，還是幫你戴上）" },
      { id: "ama-religion-002-h", text: "幹你娘，不用戴這些啦，我不信！", archetype: "landmine", retort: "……好，阿嬤收起來。（安靜）" },
    ],
  },
  {
    id: "ama-religion-003",
    text: "來，擲筊問神明你今年運勢。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-003-a", text: "幹，阿嬤陪我擲，神明都比三舅媽講話中聽。", archetype: "perfect", retort: "哎唷，你這句話說得真好。" },
      { id: "ama-religion-003-b", text: "阿嬤先擲，靠，妳比較會跟神明溝通。", archetype: "deflect", retort: "好啊，阿嬤先示範一次。" },
      { id: "ama-religion-003-c", text: "擲筊的技巧，是不是有訣竅？", archetype: "deflect", retort: "心誠則靈，沒有訣竅的。" },
      { id: "ama-religion-003-d", text: "我從來沒擲過，幹，怕擲錯……", archetype: "meek", retort: "沒關係，阿嬤教你怎麼擲。" },
      { id: "ama-religion-003-e", text: "我手滑，靠，怕筊杯飛出去……", archetype: "meek", retort: "慢慢來，穩穩地放手心。" },
      { id: "ama-religion-003-f", text: "擲筊是不是類似，去你的擲骰子遊戲。", archetype: "backfire", retort: "（阿嬤沒聽懂，遞給你筊杯）" },
      { id: "ama-religion-003-g", text: "這是不是古代版的，機掰猜拳。", archetype: "backfire", retort: "（阿嬤白眼，示意你專心）" },
      { id: "ama-religion-003-h", text: "去死啦，老太婆這種東西擲了不準！", archetype: "landmine", retort: "……好，阿嬤不勉強你。（安靜）" },
    ],
  },
  {
    id: "ama-religion-004",
    text: "幫你點盞光明燈，照亮今年的路。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-004-a", text: "幹，阿嬤點的燈比大伯的政論台照得遠。", archetype: "perfect", retort: "哎唷，你這句話講得真美。" },
      { id: "ama-religion-004-b", text: "阿嬤自己也要點一盞，靠，保平安。", archetype: "deflect", retort: "放心，阿嬤的燈早就點了。" },
      { id: "ama-religion-004-c", text: "這光明燈，是不是要寫上生日？", archetype: "deflect", retort: "對，寫上生日神明才認得。" },
      { id: "ama-religion-004-d", text: "我這個名字要怎麼寫，幹，不太懂……", archetype: "meek", retort: "阿嬤幫你寫，別擔心。" },
      { id: "ama-religion-004-e", text: "我平常不太懂這些，靠，儀式……", archetype: "meek", retort: "不懂沒關係，跟著做就好。" },
      { id: "ama-religion-004-f", text: "點燈是不是能，去你的加速網路速度。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你登記）" },
      { id: "ama-religion-004-g", text: "這燈能不能順便，機掰照亮我前途。", archetype: "backfire", retort: "（阿嬤白眼，還是幫你點了）" },
      { id: "ama-religion-004-h", text: "幹你娘咧，點這個燈也沒什麼用！", archetype: "landmine", retort: "……好，阿嬤不點了。（安靜）" },
    ],
  },
  {
    id: "ama-religion-005",
    text: "來，供品要這樣擺，你學著點。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-005-a", text: "幹，阿嬤教的擺法比三姑的規矩有道理。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好感動。" },
      { id: "ama-religion-005-b", text: "阿嬤擺供品的規矩，靠，真的很講究。", archetype: "deflect", retort: "這是老祖宗留下的規矩。" },
      { id: "ama-religion-005-c", text: "這些供品，是不是每樣都有意義？", archetype: "deflect", retort: "當然，每樣水果都有意思。" },
      { id: "ama-religion-005-d", text: "我常常搞不清楚順序，幹，怕擺錯……", archetype: "meek", retort: "擺錯沒關係，阿嬤幫你調。" },
      { id: "ama-religion-005-e", text: "這些規矩太多，靠，我記不住……", archetype: "meek", retort: "記不住沒關係，慢慢學。" },
      { id: "ama-religion-005-f", text: "供品擺法是不是有，去你的官方SOP。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續示範）" },
      { id: "ama-religion-005-g", text: "這排列組合可以出，機掰攻略本了。", archetype: "backfire", retort: "（阿嬤白眼，繼續擺供品）" },
      { id: "ama-religion-005-h", text: "幹，老東西這些規矩很煩，不學！", archetype: "landmine", retort: "……好，阿嬤自己擺。（安靜）" },
    ],
  },
  {
    id: "ama-religion-006",
    text: "你臉色不太好，要不要收驚？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-006-a", text: "幹，阿嬤幫我收的驚比看三舅媽的臉色安心。", archetype: "perfect", retort: "哎唷，這句話讓阿嬤好窩心。" },
      { id: "ama-religion-006-b", text: "阿嬤自己氣色也要顧，靠，別太累。", archetype: "deflect", retort: "阿嬤好得很，你別擔心。" },
      { id: "ama-religion-006-c", text: "收驚要念咒語嗎？教教我。", archetype: "deflect", retort: "這個要師父來，阿嬤不會。" },
      { id: "ama-religion-006-d", text: "可能只是最近，幹，沒睡好而已……", archetype: "meek", retort: "沒睡好更要收一收驚啦。" },
      { id: "ama-religion-006-e", text: "我覺得應該只是，靠，太累了……", archetype: "meek", retort: "太累也要順便收個驚，安心。" },
      { id: "ama-religion-006-f", text: "收驚是不是類似，去你的重新開機。", archetype: "backfire", retort: "（阿嬤沒聽懂，帶你去收驚）" },
      { id: "ama-religion-006-g", text: "收完驚我應該會，機掰變得很有精神。", archetype: "backfire", retort: "（阿嬤半信半疑地看你）" },
      { id: "ama-religion-006-h", text: "他媽的，不用收驚啦，我真的沒事！", archetype: "landmine", retort: "……好，阿嬤不勉強了。（安靜）" },
    ],
  },
  {
    id: "ama-religion-007",
    text: "大門口的符舊了，要換一張新的。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-007-a", text: "幹，阿嬤換的符比大伯家的保全還安心。", archetype: "perfect", retort: "哎唷，這句話說得真讓人開心。" },
      { id: "ama-religion-007-b", text: "阿嬤還記得換符，靠，真的很細心。", archetype: "deflect", retort: "當然，這是保護全家的。" },
      { id: "ama-religion-007-c", text: "這符是跟哪間廟求的，這麼靈？", archetype: "deflect", retort: "是廟口那間，很靈驗的。" },
      { id: "ama-religion-007-d", text: "我平常都沒注意，幹，這些細節……", archetype: "meek", retort: "以後要多注意這些事啊。" },
      { id: "ama-religion-007-e", text: "我對這種東西，靠，沒什麼概念……", archetype: "meek", retort: "沒概念沒關係，阿嬤在。" },
      { id: "ama-religion-007-f", text: "換符是不是像，去你的換手機保護貼。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續貼符）" },
      { id: "ama-religion-007-g", text: "這符能不能防，機掰詐騙電話。", archetype: "backfire", retort: "（阿嬤白眼，繼續貼好）" },
      { id: "ama-religion-007-h", text: "去你的，老太婆這種舊習俗不用換！", archetype: "landmine", retort: "……好，阿嬤不換了。（安靜）" },
    ],
  },
  {
    id: "ama-religion-008",
    text: "阿嬤幫你求了姻緣符，帶著。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-008-a", text: "幹，阿嬤求的符比三姑介紹的對象用心。", archetype: "perfect", retort: "哎唷，這句話講到阿嬤心坎裡。" },
      { id: "ama-religion-008-b", text: "阿嬤這麼用心，靠，我一定隨身帶著。", archetype: "deflect", retort: "帶著就對了，會有好結果。" },
      { id: "ama-religion-008-c", text: "這姻緣符，是不是求了很久？", archetype: "deflect", retort: "求了好幾次才求到的。" },
      { id: "ama-religion-008-d", text: "我最近真的沒有，幹，對象的消息……", archetype: "meek", retort: "帶著符，緣分就會來了。" },
      { id: "ama-religion-008-e", text: "我對這種東西，靠，半信半疑……", archetype: "meek", retort: "信則有，帶著總是好的。" },
      { id: "ama-religion-008-f", text: "姻緣符是不是，去你的月老官方認證。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你收好符）" },
      { id: "ama-religion-008-g", text: "這符能不能配對，機掰交友軟體使用。", archetype: "backfire", retort: "（阿嬤一臉困惑，看著你）" },
      { id: "ama-religion-008-h", text: "機掰，這種符不會有用啦，別求了！", archetype: "landmine", retort: "……好，阿嬤不求了。（安靜）" },
    ],
  },
  {
    id: "ama-religion-009",
    text: "出門有沒有先拜一下土地公？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-009-a", text: "幹，我還跟土地公說，別讓三姑太閒。", archetype: "perfect", retort: "哎唷，你這孩子最有孝心。" },
      { id: "ama-religion-009-b", text: "阿嬤每天都拜，靠，我跟著沾光就好。", archetype: "deflect", retort: "沾光也要自己拜才有效。" },
      { id: "ama-religion-009-c", text: "拜土地公要說什麼，我學不太會……", archetype: "deflect", retort: "簡單說保平安就可以了。" },
      { id: "ama-religion-009-d", text: "我出門都太趕，幹，常常忘記拜……", archetype: "meek", retort: "忘記拜就容易諸事不順啊。" },
      { id: "ama-religion-009-e", text: "我對這個習慣，靠，還不太熟悉……", archetype: "meek", retort: "不熟悉可以先跟阿嬤學。" },
      { id: "ama-religion-009-f", text: "拜土地公是不是要，去你的先預約。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續唸經）" },
      { id: "ama-religion-009-g", text: "土地公應該很忙，機掰我不打擾。", archetype: "backfire", retort: "（阿嬤白眼，唸你幾句）" },
      { id: "ama-religion-009-h", text: "去你的，老東西拜這些浪費時間啦！", archetype: "landmine", retort: "你這樣說，阿嬤會擔心。（安靜）" },
    ],
  },
  {
    id: "ama-religion-010",
    text: "神明保佑你，才能平安到家。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-010-a", text: "幹，是因為阿嬤比三姑真心念著我。", archetype: "perfect", retort: "哎唷，你這孩子最貼心了。" },
      { id: "ama-religion-010-b", text: "阿嬤自己也要保重，靠，別太操心。", archetype: "deflect", retort: "操心是應該的，你是我的寶。" },
      { id: "ama-religion-010-c", text: "是不是阿嬤每天都幫我求平安？", archetype: "deflect", retort: "當然，每天都幫你求。" },
      { id: "ama-religion-010-d", text: "路上其實有點塞車，幹，晚了一點……", archetype: "meek", retort: "塞車也要小心開車啊。" },
      { id: "ama-religion-010-e", text: "我平常開車，靠，比較少注意細節……", archetype: "meek", retort: "以後開車要更小心一點。" },
      { id: "ama-religion-010-f", text: "導航加神明雙重保護，去你的超安全。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續念叨）" },
      { id: "ama-religion-010-g", text: "這樣我等於，機掰買了兩份保險。", archetype: "backfire", retort: "（阿嬤白眼，繼續念叨）" },
      { id: "ama-religion-010-h", text: "幹你娘，平安是我自己小心，不是神明！", archetype: "landmine", retort: "你這樣說，阿嬤會擔心。（安靜）" },
    ],
  },
  {
    id: "ama-religion-011",
    text: "走，帶你去廟口拜拜土地公。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-011-a", text: "幹，我跟土地公說要保佑妳，比三舅媽誠心。", archetype: "perfect", retort: "哎唷，你這孩子最有心了。" },
      { id: "ama-religion-011-b", text: "阿嬤走這條路，靠，走了幾十年了吧。", archetype: "deflect", retort: "走了一輩子，閉眼都會走。" },
      { id: "ama-religion-011-c", text: "這間廟，是不是特別靈驗？", archetype: "deflect", retort: "當然，很多人都來拜這間。" },
      { id: "ama-religion-011-d", text: "我今天穿的鞋，幹，不太好走……", archetype: "meek", retort: "那穿雙好走的鞋再去。" },
      { id: "ama-religion-011-e", text: "我對拜拜的流程，靠，不太熟悉……", archetype: "meek", retort: "不熟沒關係，阿嬤帶你拜。" },
      { id: "ama-religion-011-f", text: "這廟口是不是，去你的本地信仰旗艦店。", archetype: "backfire", retort: "（阿嬤沒聽懂，拉你走進去）" },
      { id: "ama-religion-011-g", text: "拜完可以順便，機掰求個停車位嗎。", archetype: "backfire", retort: "（阿嬤白眼，拉你走進廟）" },
      { id: "ama-religion-011-h", text: "去死啦，老太婆別拉我去廟裡浪費時間！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
  {
    id: "ama-religion-012",
    text: "這個香火袋，掛在你車上保平安。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-012-a", text: "幹，阿嬤求的香火袋比姑丈的長輩圖有用。", archetype: "perfect", retort: "哎唷，這比喻真的很妙。" },
      { id: "ama-religion-012-b", text: "阿嬤這麼細心，靠，連車子都想到了。", archetype: "deflect", retort: "當然，孫子的車也要顧。" },
      { id: "ama-religion-012-c", text: "這香火袋，是不是求了特別加持？", archetype: "deflect", retort: "當然，特別去廟裡求的。" },
      { id: "ama-religion-012-d", text: "我車上已經掛滿吊飾了，幹，怕太多……", archetype: "meek", retort: "掛多一點才夠力保佑你。" },
      { id: "ama-religion-012-e", text: "我平常都停在戶外，靠，怕淋濕……", archetype: "meek", retort: "淋濕沒事，心誠最重要。" },
      { id: "ama-religion-012-f", text: "這香火袋是不是能兼，去你的防盜功能。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你掛上）" },
      { id: "ama-religion-012-g", text: "掛上這個能不能，機掰省一點油錢。", archetype: "backfire", retort: "（阿嬤白眼，還是掛上了）" },
      { id: "ama-religion-012-h", text: "幹你娘咧，車上不要掛這些，很土！", archetype: "landmine", retort: "……好，阿嬤收回去。（安靜）" },
    ],
  },
  {
    id: "ama-religion-013",
    text: "拜完要跟神明鞠躬，說聲謝謝。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-013-a", text: "幹，謝謝神明讓我有比三姑好的阿嬤。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤想哭。" },
      { id: "ama-religion-013-b", text: "阿嬤鞠躬的姿勢，靠，我要跟你學。", archetype: "deflect", retort: "好啊，阿嬤教你怎麼鞠躬。" },
      { id: "ama-religion-013-c", text: "鞠躬要鞠幾次，才算有禮貌？", archetype: "deflect", retort: "三次就好，心誠最重要。" },
      { id: "ama-religion-013-d", text: "我常常忘記鞠躬，幹，有點失禮……", archetype: "meek", retort: "忘記沒關係，下次記得就好。" },
      { id: "ama-religion-013-e", text: "我鞠躬的角度，靠，好像不太標準……", archetype: "meek", retort: "角度不重要，心意才重要。" },
      { id: "ama-religion-013-f", text: "鞠躬完是不是要，去你的打卡簽到。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續拜拜）" },
      { id: "ama-religion-013-g", text: "這算不算跟神明的，機掰商業會面。", archetype: "backfire", retort: "（阿嬤白眼，繼續拜）" },
      { id: "ama-religion-013-h", text: "幹，老東西這種形式主義沒必要！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
  {
    id: "ama-religion-014",
    text: "你看香爐的香都滿了，好兆頭。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-014-a", text: "幹，香滿了是因為阿嬤比大伯虔誠多了。", archetype: "perfect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-religion-014-b", text: "阿嬤每天照顧香爐，靠，辛苦了。", archetype: "deflect", retort: "不辛苦，這是阿嬤的日常。" },
      { id: "ama-religion-014-c", text: "這香爐，是不是傳了很多代？", archetype: "deflect", retort: "是啊，從你阿祖那代傳下來的。" },
      { id: "ama-religion-014-d", text: "我對兆頭這種事，幹，半信半疑……", archetype: "meek", retort: "信一點也不會少一塊肉啦。" },
      { id: "ama-religion-014-e", text: "我平常沒有觀察，靠，這些細節……", archetype: "meek", retort: "以後可以多留意這些事。" },
      { id: "ama-religion-014-f", text: "香滿了是不是代表，去你的存貨要補了。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續添香）" },
      { id: "ama-religion-014-g", text: "這算不算香爐的，機掰滿意度調查。", archetype: "backfire", retort: "（阿嬤白眼，繼續添香）" },
      { id: "ama-religion-014-h", text: "他媽的，這種兆頭的事都是巧合啦！", archetype: "landmine", retort: "你這樣說，阿嬤會擔心。（安靜）" },
    ],
  },
  {
    id: "ama-religion-015",
    text: "有沒有拜拜求今年工作順利？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-015-a", text: "幹，我還幫阿嬤求了，活得比三姑久。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好感動。" },
      { id: "ama-religion-015-b", text: "阿嬤每天都幫我求，靠，我很放心。", archetype: "deflect", retort: "當然，每天都幫你求平安。" },
      { id: "ama-religion-015-c", text: "拜工作順利，要怎麼跟神明說？", archetype: "deflect", retort: "就誠心說出你的心願就好。" },
      { id: "ama-religion-015-d", text: "我最近工作，幹，壓力真的很大……", archetype: "meek", retort: "壓力大更要多拜拜求安心。" },
      { id: "ama-religion-015-e", text: "我對這種事，靠，其實半信半疑……", archetype: "meek", retort: "信一點，心裡也會踏實一點。" },
      { id: "ama-religion-015-f", text: "工作順利我覺得靠加班，去你的比較快。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續唸經）" },
      { id: "ama-religion-015-g", text: "拜拜是不是能取代，機掰績效考核。", archetype: "backfire", retort: "（阿嬤白眼，繼續拜拜）" },
      { id: "ama-religion-015-h", text: "去你的，老太婆工作跟拜拜沒關係！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
  {
    id: "ama-religion-016",
    text: "這張平安符放皮夾，隨身帶著。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-016-a", text: "幹，阿嬤求的符比三舅媽的關心讓我安心。", archetype: "perfect", retort: "哎唷，這比喻真的很妙。" },
      { id: "ama-religion-016-b", text: "阿嬤這麼細心，靠，皮夾都想到了。", archetype: "deflect", retort: "當然，隨身的東西最重要。" },
      { id: "ama-religion-016-c", text: "這符放皮夾，會不會太擠？", archetype: "deflect", retort: "擠一點沒關係，保平安要緊。" },
      { id: "ama-religion-016-d", text: "我皮夾已經塞滿卡片了，幹，滿了……", archetype: "meek", retort: "塞滿也要留位置給平安。" },
      { id: "ama-religion-016-e", text: "我怕弄丟，靠，還是先放家裡好了……", archetype: "meek", retort: "放皮夾才隨身，別放家裡。" },
      { id: "ama-religion-016-f", text: "這符是不是能當，去你的信用卡額度用。", archetype: "backfire", retort: "（阿嬤沒聽懂，幫你塞進皮夾）" },
      { id: "ama-religion-016-g", text: "符放皮夾是不是，機掰防小偷加持版。", archetype: "backfire", retort: "（阿嬤白眼，還是塞進去）" },
      { id: "ama-religion-016-h", text: "機掰，皮夾不要放這些啦，很占空間！", archetype: "landmine", retort: "……好，阿嬤收起來。（安靜）" },
    ],
  },
  {
    id: "ama-religion-017",
    text: "出遠門要看農民曆，選個好日子。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-017-a", text: "幹，阿嬤選的日子比三姑的碎念準時安全。", archetype: "perfect", retort: "哎唷，這句話說得阿嬤好開心。" },
      { id: "ama-religion-017-b", text: "阿嬤這麼會看農民曆，靠，太厲害了。", archetype: "deflect", retort: "看了一輩子，當然厲害。" },
      { id: "ama-religion-017-c", text: "這農民曆，是不是每年都要換新的？", archetype: "deflect", retort: "對，每年都要重新看。" },
      { id: "ama-religion-017-d", text: "我這次時間比較趕，幹，可能來不及……", archetype: "meek", retort: "來不及也要抽空看一下。" },
      { id: "ama-religion-017-e", text: "我對這個沒什麼研究，靠，看不太懂……", archetype: "meek", retort: "看不懂沒關係，阿嬤幫你選。" },
      { id: "ama-religion-017-f", text: "這是不是古代版的，去你的行事曆APP。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續翻農民曆）" },
      { id: "ama-religion-017-g", text: "選日子是不是要先，機掰付訂金。", archetype: "backfire", retort: "（阿嬤白眼，繼續翻農民曆）" },
      { id: "ama-religion-017-h", text: "機掰，老東西這種老規矩不用看啦！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
  {
    id: "ama-religion-018",
    text: "要不要擲筊問神明適不適合搬家？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-018-a", text: "幹，我還要問神明，能不能少讓三姑來煩妳。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好窩心。" },
      { id: "ama-religion-018-b", text: "阿嬤擲筊這麼準，靠，先幫我看看。", archetype: "deflect", retort: "好啊，阿嬤先幫你擲一次。" },
      { id: "ama-religion-018-c", text: "搬家這麼大的事，還是問問阿嬤意見。", archetype: "deflect", retort: "好，阿嬤陪你一起想想。" },
      { id: "ama-religion-018-d", text: "我還在猶豫，幹，要不要搬，沒決定……", archetype: "meek", retort: "猶豫的話問神明最準了。" },
      { id: "ama-religion-018-e", text: "我怕擲出來的結果，靠，不是我要的……", archetype: "meek", retort: "結果不好也可以再擲一次。" },
      { id: "ama-religion-018-f", text: "擲筊是不是搬家公司的，去你的認證流程。", archetype: "backfire", retort: "（阿嬤沒聽懂，遞給你筊杯）" },
      { id: "ama-religion-018-g", text: "這算不算古代版的，機掰丟銅板決定。", archetype: "backfire", retort: "（阿嬤白眼，示意你專心）" },
      { id: "ama-religion-018-h", text: "幹你娘，搬不搬家跟神明沒關係！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
  {
    id: "ama-religion-019",
    text: "廟裡的籤詩說你今年犯小人。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-019-a", text: "幹，有妳保佑，小人比三姑近不了身。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好安心。" },
      { id: "ama-religion-019-b", text: "阿嬤這麼細心，靠，連籤詩都幫我求了。", archetype: "deflect", retort: "當然，這是為你好求的。" },
      { id: "ama-religion-019-c", text: "這籤詩，是不是也有化解的方法？", archetype: "deflect", retort: "有，帶個平安符就能化解。" },
      { id: "ama-religion-019-d", text: "我最近工作上，幹，確實遇到狀況……", archetype: "meek", retort: "難怪，要小心提防身邊的人。" },
      { id: "ama-religion-019-e", text: "我對這種籤詩，靠，其實半信半疑……", archetype: "meek", retort: "信一點，防人之心不可無。" },
      { id: "ama-religion-019-f", text: "小人是不是可以，去你的直接封鎖處理。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續唸籤詩）" },
      { id: "ama-religion-019-g", text: "這籤詩是不是，機掰職場防身指南。", archetype: "backfire", retort: "（阿嬤白眼，繼續唸籤詩）" },
      { id: "ama-religion-019-h", text: "去死啦，老太婆這種籤詩都亂寫別信！", archetype: "landmine", retort: "你這樣說，阿嬤會擔心。（安靜）" },
    ],
  },
  {
    id: "ama-religion-020",
    text: "你今年沖到生肖，要去安太歲。",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-020-a", text: "幹，我陪妳去，順便求妳比三姑長壽。", archetype: "perfect", retort: "哎唷，你這句話讓阿嬤好感動。" },
      { id: "ama-religion-020-b", text: "阿嬤自己的生肖，靠，要不要也安一下？", archetype: "deflect", retort: "阿嬤早就安過了，別擔心。" },
      { id: "ama-religion-020-c", text: "安太歲要準備什麼，我來幫忙。", archetype: "deflect", retort: "準備供品跟紅包就可以了。" },
      { id: "ama-religion-020-d", text: "我最近運氣，幹，是差了一點沒錯……", archetype: "meek", retort: "差就更要快點去安太歲。" },
      { id: "ama-religion-020-e", text: "我對這個習俗，靠，不太了解……", archetype: "meek", retort: "不了解沒關係，阿嬤帶你去。" },
      { id: "ama-religion-020-f", text: "安太歲是不是，去你的年度系統更新。", archetype: "backfire", retort: "（阿嬤沒聽懂，繼續準備）" },
      { id: "ama-religion-020-g", text: "沖太歲是不是，機掰水逆的意思。", archetype: "backfire", retort: "（阿嬤白眼，繼續準備供品）" },
      { id: "ama-religion-020-h", text: "幹你娘咧，這種東西都亂講，不去！", archetype: "landmine", retort: "你這樣說，阿嬤會擔心。（安靜）" },
    ],
  },
  {
    id: "ama-religion-021",
    text: "為什麼每次拜拜你都不拿香？",
    topic: "religion",
    bossId: "ama",
    options: [
      { id: "ama-religion-021-a", text: "幹，我把機會讓給比大伯虔誠的妳。", archetype: "perfect", retort: "哎唷，你這孩子最會說話。" },
      { id: "ama-religion-021-b", text: "阿嬤拿香拜得比較誠心，靠，我在旁邊學。", archetype: "deflect", retort: "好，那阿嬤示範給你看。" },
      { id: "ama-religion-021-c", text: "我怕拿香姿勢不對，失了禮數。", archetype: "deflect", retort: "沒關係，阿嬤教你怎麼拿。" },
      { id: "ama-religion-021-d", text: "我對這些儀式，幹，其實有點生疏……", archetype: "meek", retort: "生疏沒關係，多拜幾次就熟。" },
      { id: "ama-religion-021-e", text: "我手比較笨拙，靠，怕香會倒……", archetype: "meek", retort: "慢慢拿，香倒了再插正就好。" },
      { id: "ama-religion-021-f", text: "我怕拿香會不小心，去你的點燃眉毛。", archetype: "backfire", retort: "（阿嬤沒聽懂，遞香給你）" },
      { id: "ama-religion-021-g", text: "拿香是不是有段位，機掰認證考試。", archetype: "backfire", retort: "（阿嬤白眼，遞香給你）" },
      { id: "ama-religion-021-h", text: "幹，老東西這些形式我沒興趣拿香！", archetype: "landmine", retort: "你這樣說，阿嬤會難過。（安靜）" },
    ],
  },
] satisfies Question[];
