import type { Question } from "@/content/types";

// situations:
// - 新買衣服很醜
// - 染新髮色很浮誇
// - 帽子很醜
// - 沒化妝沒打扮很憔悴
// - 修眉失敗眉毛很怪
// - 髮型分線很怪
// - 衣服口袋破洞
// - 鞋子很舊
// - 指甲剪太短
// - 鬢角沒修
// - 戴口罩看不出胖瘦
// - 頭髮打結像鳥窩
// - 過年穿花襯衫尷尬
// - 手鍊項鍊很俗氣
// - 戴變色片瞳孔顏色很怪

export default [
  {
    id: "xiao-biaodi-appearance-022",
    text: "老師說你這件新衣服的顏色好醜，誰選的？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-022-a",
        text: "幹，醜是我自己選的，你管到穿搭了？",
        archetype: "perfect",
        retort: "……他臉一黑，摸摸鼻子罵幹",
      },
      {
        id: "xiao-biaodi-appearance-022-b",
        text: "靠，你猜這件衣服多少錢，猜對算贏。",
        archetype: "deflect",
        retort: "我猜三百塊！猜對了嗎？",
      },
      {
        id: "xiao-biaodi-appearance-022-c",
        text: "笑死，先吃塊糖比顏色重要吧。",
        archetype: "deflect",
        retort: "先吃糖！糖比較重要！",
      },
      {
        id: "xiao-biaodi-appearance-022-d",
        text: "對啊，幹……我自己選的，眼光不太好……",
        archetype: "meek",
        retort: "眼光不好喔，那下次讓媽媽選。",
      },
      {
        id: "xiao-biaodi-appearance-022-e",
        text: "靠……顏色是有點特別，我自己還好……",
        archetype: "meek",
        retort: "特別？那就是醜的意思吧。",
      },
      {
        id: "xiao-biaodi-appearance-022-f",
        text: "他媽的，這是走大膽撞色路線啦。",
        archetype: "backfire",
        retort: "（他沒聽懂，繼續玩手機）",
      },
      {
        id: "xiao-biaodi-appearance-022-g",
        text: "機掰，醜到極致就是新的美學典範。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續發呆）",
      },
      {
        id: "xiao-biaodi-appearance-022-h",
        text: "去你的，作業本翻開，看誰的字比較醜。",
        archetype: "landmine",
        retort: "嗚——他邊哭邊向媽媽告狀喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-023",
    text: "姑姑說你染的髮色好誇張，是不是想紅？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-023-a",
        text: "靠北，這髮色喜氣，姑姑你懂個屁。",
        archetype: "perfect",
        retort: "……姑姑臉一僵，轉頭説悄悄話",
      },
      {
        id: "xiao-biaodi-appearance-023-b",
        text: "靠，你猜我染的是什麼顏色，形容看看？",
        archetype: "deflect",
        retort: "我猜是亮橘色的！",
      },
      {
        id: "xiao-biaodi-appearance-023-c",
        text: "笑死，先吃塊年糕比髮色重要吧。",
        archetype: "deflect",
        retort: "好，我先吃年糕！",
      },
      {
        id: "xiao-biaodi-appearance-023-d",
        text: "對啊，幹……一時興起就去染了，有點後悔……",
        archetype: "meek",
        retort: "後悔了喔，那趕快染回來。",
      },
      {
        id: "xiao-biaodi-appearance-023-e",
        text: "靠……可能真的染得太誇張，不太適合我……",
        archetype: "meek",
        retort: "不適合？姑姑——他自己承認了——",
      },
      {
        id: "xiao-biaodi-appearance-023-f",
        text: "他媽的，這叫前衛藝術髮色，走尖端。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-appearance-023-g",
        text: "機掰，誇張髮色是自由靈魂的展現。",
        archetype: "backfire",
        retort: "（小表弟一臉茫然，還在看）",
      },
      {
        id: "xiao-biaodi-appearance-023-h",
        text: "去死，告狀之前先想想你考幾分。",
        archetype: "landmine",
        retort: "姑姑護著他，碎念瞪你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-024",
    text: "阿嬤說你戴的帽子好醜，是路邊送的嗎？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-024-a",
        text: "幹，這帽子擋的是我的帥，阿嬤嫉妒了？",
        archetype: "perfect",
        retort: "……阿嬤笑著點頭",
      },
      {
        id: "xiao-biaodi-appearance-024-b",
        text: "靠，阿嬤你猜這頂帽子什麼顏色？",
        archetype: "deflect",
        retort: "我猜是咖啡色的！",
      },
      {
        id: "xiao-biaodi-appearance-024-c",
        text: "笑死，先坐下休息比帽子重要吧。",
        archetype: "deflect",
        retort: "好啦，我先坐一下。",
      },
      {
        id: "xiao-biaodi-appearance-024-d",
        text: "對啊，幹……這頂特價買的，可能真的普通……",
        archetype: "meek",
        retort: "特價買的喔，難怪醜醜的。",
      },
      {
        id: "xiao-biaodi-appearance-024-e",
        text: "靠……可能真的沒有很好看，但很保暖……",
        archetype: "meek",
        retort: "不好看？阿嬤——他自己承認了——",
      },
      {
        id: "xiao-biaodi-appearance-024-f",
        text: "他媽的，這頂帽子是機能派設計啦。",
        archetype: "backfire",
        retort: "……（阿嬤搖搖頭繼續看電視）",
      },
      {
        id: "xiao-biaodi-appearance-024-g",
        text: "機掰，醜帽子才是真正低調的富豪穿搭。",
        archetype: "backfire",
        retort: "（小表弟歪頭，沒聽懂）",
      },
      {
        id: "xiao-biaodi-appearance-024-h",
        text: "去死，先把你成績單交出來再說。",
        archetype: "landmine",
        retort: "阿嬤護著他，碎念瞪你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-025",
    text: "媽媽說你今天完全沒打扮，看起來好憔悴。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-025-a",
        text: "去你的，憔悴是加班熬的，你熬夜追劇？",
        archetype: "perfect",
        retort: "……媽媽臉一黑，偷笑不敢接話",
      },
      {
        id: "xiao-biaodi-appearance-025-b",
        text: "靠，你猜我今天幾點起床的？",
        archetype: "deflect",
        retort: "我猜六點！好早喔！",
      },
      {
        id: "xiao-biaodi-appearance-025-c",
        text: "笑死，先吃早餐比打扮重要吧。",
        archetype: "deflect",
        retort: "對耶！我先去吃早餐！",
      },
      {
        id: "xiao-biaodi-appearance-025-d",
        text: "對啊，幹……今天真的太趕，沒時間打扮……",
        archetype: "meek",
        retort: "沒時間喔，那也太趕了吧。",
      },
      {
        id: "xiao-biaodi-appearance-025-e",
        text: "靠……最近比較累，懶得花心思打扮了……",
        archetype: "meek",
        retort: "懶得打扮？媽媽——他說他懶——",
      },
      {
        id: "xiao-biaodi-appearance-025-f",
        text: "他媽的，素顏是我今年主打的高級感。",
        archetype: "backfire",
        retort: "……（媽媽轉頭去忙別的事）",
      },
      {
        id: "xiao-biaodi-appearance-025-g",
        text: "機掰，不打扮才是真正自信的最高境界。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，眼神呆滯）",
      },
      {
        id: "xiao-biaodi-appearance-025-h",
        text: "去死，Switch都打不贏我，還敢說話？",
        archetype: "landmine",
        retort: "嗚——媽媽你看他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-026",
    text: "姑姑說你眉毛修得好奇怪，是自己修的嗎？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-026-a",
        text: "幹，是我自己修的，姑姑要不要也來一副？",
        archetype: "perfect",
        retort: "……姑姑臉一黑轉頭裝沒事",
      },
      {
        id: "xiao-biaodi-appearance-026-b",
        text: "靠，你猜我用什麼修的，剪刀還刀片？",
        archetype: "deflect",
        retort: "我猜是用剪刀修的！",
      },
      {
        id: "xiao-biaodi-appearance-026-c",
        text: "笑死，先吃顆橘子比眉毛重要吧。",
        archetype: "deflect",
        retort: "好，我先吃橘子！",
      },
      {
        id: "xiao-biaodi-appearance-026-d",
        text: "對啊，幹……第一次自己修，修壞了一邊……",
        archetype: "meek",
        retort: "修壞了喔，那看起來真的怪怪的。",
      },
      {
        id: "xiao-biaodi-appearance-026-e",
        text: "靠……可能真的修得不太對稱啦……",
        archetype: "meek",
        retort: "不對稱？姑姑——他自己承認了——",
      },
      {
        id: "xiao-biaodi-appearance-026-f",
        text: "他媽的，不對稱眉毛是我原創標誌啦。",
        archetype: "backfire",
        retort: "……（姑姑忍笑轉頭跟阿嬤說悄悄話）",
      },
      {
        id: "xiao-biaodi-appearance-026-g",
        text: "機掰，眉毛怪才能讓人一眼記住我。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，嘴巴微張）",
      },
      {
        id: "xiao-biaodi-appearance-026-h",
        text: "去你的，回去問你媽這種事，少囉唆。",
        archetype: "landmine",
        retort: "嗚——姑姑瞪你，罵你三小",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-027",
    text: "老師說你頭髮的分線好奇怪，是不是睡歪了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-027-a",
        text: "去死，這條分線留給人生用的，你懂？",
        archetype: "perfect",
        retort: "……他臉一黑，裝沒聽到",
      },
      {
        id: "xiao-biaodi-appearance-027-b",
        text: "靠，你猜我平常都分哪一邊？",
        archetype: "deflect",
        retort: "我猜是分左邊！",
      },
      {
        id: "xiao-biaodi-appearance-027-c",
        text: "笑死，先梳一下自己的頭比分線重要。",
        archetype: "deflect",
        retort: "好，我去照鏡子梳頭！",
      },
      {
        id: "xiao-biaodi-appearance-027-d",
        text: "對啊，幹……早上真的睡歪了，沒整理好……",
        archetype: "meek",
        retort: "睡歪了喔，那也太隨便了吧。",
      },
      {
        id: "xiao-biaodi-appearance-027-e",
        text: "靠……可能沒梳好，看起來有點亂……",
        archetype: "meek",
        retort: "沒梳好？那快去照鏡子看看。",
      },
      {
        id: "xiao-biaodi-appearance-027-f",
        text: "他媽的，歪分線是黃金比例髮型學啦。",
        archetype: "backfire",
        retort: "（他沒聽懂，繼續玩手機）",
      },
      {
        id: "xiao-biaodi-appearance-027-g",
        text: "機掰，分線歪才是不對稱潮流的最新一季。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，抓抓頭）",
      },
      {
        id: "xiao-biaodi-appearance-027-h",
        text: "去你的，考卷簽名都簽不好，先別說我。",
        archetype: "landmine",
        retort: "他媽媽嚴肅地瞪你，罵幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-028",
    text: "阿嬤說你外套口袋破了一個洞，怎麼不補？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-028-a",
        text: "幹，這個洞留給紅包溜進去，阿嬤懂經濟。",
        archetype: "perfect",
        retort: "……阿嬤笑著拍拍你的手",
      },
      {
        id: "xiao-biaodi-appearance-028-b",
        text: "靠，阿嬤你幫我補，你針線最厲害了。",
        archetype: "deflect",
        retort: "好啊！阿嬤幫你補一下！",
      },
      {
        id: "xiao-biaodi-appearance-028-c",
        text: "笑死，先吃口熱菜比破洞重要吧。",
        archetype: "deflect",
        retort: "好，先吃熱菜暖暖身！",
      },
      {
        id: "xiao-biaodi-appearance-028-d",
        text: "對啊，幹……穿太久了，破了都沒發現……",
        archetype: "meek",
        retort: "沒發現喔，那要多注意一點。",
      },
      {
        id: "xiao-biaodi-appearance-028-e",
        text: "靠……本來想補，一直找不到時間啦……",
        archetype: "meek",
        retort: "找不到時間？那也拖太久了。",
      },
      {
        id: "xiao-biaodi-appearance-028-f",
        text: "他媽的，破洞外套是解構主義穿搭啦。",
        archetype: "backfire",
        retort: "……（阿嬤已經拿出針線盒）",
      },
      {
        id: "xiao-biaodi-appearance-028-g",
        text: "機掰，破洞是透氣孔，冬天很實用。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續戳那個洞）",
      },
      {
        id: "xiao-biaodi-appearance-028-h",
        text: "去你的，連告狀都不會，也敢說我？",
        archetype: "landmine",
        retort: "嗚嗚——他躲進阿嬤懷裡哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-029",
    text: "媽媽說你這雙鞋穿好幾年了，鞋底都快掉了。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-029-a",
        text: "去死，鞋底快掉是走過的路多，你走得少？",
        archetype: "perfect",
        retort: "……媽媽臉一黑，故意咳兩聲",
      },
      {
        id: "xiao-biaodi-appearance-029-b",
        text: "靠，你猜這雙鞋我穿幾年了？",
        archetype: "deflect",
        retort: "我猜五年！好久喔！",
      },
      {
        id: "xiao-biaodi-appearance-029-c",
        text: "笑死，先幫忙擺碗筷比鞋子重要吧。",
        archetype: "deflect",
        retort: "好，我去擺碗筷！",
      },
      {
        id: "xiao-biaodi-appearance-029-d",
        text: "對啊，幹……穿習慣了捨不得換，有點舊了……",
        archetype: "meek",
        retort: "捨不得換喔，那也太念舊了。",
      },
      {
        id: "xiao-biaodi-appearance-029-e",
        text: "靠……鞋底真的快掉了，一直沒空去買新的……",
        archetype: "meek",
        retort: "沒空買？那快掉了怎麼走路？",
      },
      {
        id: "xiao-biaodi-appearance-029-f",
        text: "他媽的，鞋底快掉是限量破損工藝美學。",
        archetype: "backfire",
        retort: "……（媽媽轉頭去忙別的事）",
      },
      {
        id: "xiao-biaodi-appearance-029-g",
        text: "機掰，舊鞋才穿得出真正的態度，你不懂。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看鞋底）",
      },
      {
        id: "xiao-biaodi-appearance-029-h",
        text: "去你的，先把聯絡簿拿出來，再說我的鞋。",
        archetype: "landmine",
        retort: "媽媽衝過來罵：你兇誰啊",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-030",
    text: "姑丈說你指甲剪這麼短，是不是很緊張？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-030-a",
        text: "幹，剪短是效率，姑丈的酒杯倒是剪不完。",
        archetype: "perfect",
        retort: "……姑丈臉一黑假裝滑手機",
      },
      {
        id: "xiao-biaodi-appearance-030-b",
        text: "靠，姑丈你猜我多久剪一次指甲？",
        archetype: "deflect",
        retort: "我猜一個禮拜一次！",
      },
      {
        id: "xiao-biaodi-appearance-030-c",
        text: "笑死，你酒喝夠了沒比指甲重要吧。",
        archetype: "deflect",
        retort: "哎唷，這杯我還要喝呢。",
      },
      {
        id: "xiao-biaodi-appearance-030-d",
        text: "對啊，幹……最近習慣咬指甲，有點緊張……",
        archetype: "meek",
        retort: "咬指甲喔，那要改掉這個習慣。",
      },
      {
        id: "xiao-biaodi-appearance-030-e",
        text: "靠……可能真的剪太短了，有點不舒服……",
        archetype: "meek",
        retort: "不舒服？那幹嘛剪這麼短。",
      },
      {
        id: "xiao-biaodi-appearance-030-f",
        text: "他媽的，短指甲是鋼琴家的標準配備。",
        archetype: "backfire",
        retort: "……（姑丈搖搖頭繼續喝酒）",
      },
      {
        id: "xiao-biaodi-appearance-030-g",
        text: "機掰，剪這麼短代表我人生極度自律。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，傻笑看著）",
      },
      {
        id: "xiao-biaodi-appearance-030-h",
        text: "去死，緊張的明明是你考試，別裝了。",
        archetype: "landmine",
        retort: "嗚嗚——他躲姑丈身後哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-031",
    text: "老師說你鬢角長得亂七八糟，怎麼不修一下？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-031-a",
        text: "靠北，鬢角亂是自在，你連下課都要管？",
        archetype: "perfect",
        retort: "……他臉一黑，跑走了",
      },
      {
        id: "xiao-biaodi-appearance-031-b",
        text: "靠，你猜我上次剪頭髮是什麼時候？",
        archetype: "deflect",
        retort: "我猜是上個月！",
      },
      {
        id: "xiao-biaodi-appearance-031-c",
        text: "笑死，先吃塊蛋糕比鬢角重要吧。",
        archetype: "deflect",
        retort: "好，我先吃蛋糕！",
      },
      {
        id: "xiao-biaodi-appearance-031-d",
        text: "對啊，幹……最近懶得去剪，就一直長了……",
        archetype: "meek",
        retort: "懶得剪喔，那也太隨便了。",
      },
      {
        id: "xiao-biaodi-appearance-031-e",
        text: "靠……本來想修，找不到理髮店開門啦……",
        archetype: "meek",
        retort: "找不到？那也拖太久了吧。",
      },
      {
        id: "xiao-biaodi-appearance-031-f",
        text: "他媽的，鬢角亂是野性魅力的展現啦。",
        archetype: "backfire",
        retort: "（他沒聽懂，繼續玩手機）",
      },
      {
        id: "xiao-biaodi-appearance-031-g",
        text: "機掰，不修鬢角才是真正的隨性自由派。",
        archetype: "backfire",
        retort: "（小表弟一臉問號，繼續看）",
      },
      {
        id: "xiao-biaodi-appearance-031-h",
        text: "去死，Switch連新手教學都過不了，別說我。",
        archetype: "landmine",
        retort: "嗚嗚——他躲媽媽背後哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-032",
    text: "阿嬤說你戴著口罩看不出臉圓不圓，拿下來看看？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-032-a",
        text: "幹，拿下來也是圓的，阿嬤的嘴才停不下來。",
        archetype: "perfect",
        retort: "……阿嬤笑開懷",
      },
      {
        id: "xiao-biaodi-appearance-032-b",
        text: "靠，阿嬤你猜我口罩下面是什麼表情？",
        archetype: "deflect",
        retort: "我猜是在笑！",
      },
      {
        id: "xiao-biaodi-appearance-032-c",
        text: "笑死，先吃塊餅乾比臉圓重要吧。",
        archetype: "deflect",
        retort: "好，我先吃餅乾！",
      },
      {
        id: "xiao-biaodi-appearance-032-d",
        text: "對啊，幹……拿下來可能真的比較圓一點啦……",
        archetype: "meek",
        retort: "比較圓喔，那要少吃一點了。",
      },
      {
        id: "xiao-biaodi-appearance-032-e",
        text: "靠……戴口罩比較沒安全感，還是戴著好了……",
        archetype: "meek",
        retort: "沒安全感？那也太誇張了吧。",
      },
      {
        id: "xiao-biaodi-appearance-032-f",
        text: "他媽的，口罩下面藏我不外露的神秘感。",
        archetype: "backfire",
        retort: "……（阿嬤伸手想拉下他的口罩）",
      },
      {
        id: "xiao-biaodi-appearance-032-g",
        text: "機掰，戴口罩是我保護隱私的高級策略。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，眨眨眼）",
      },
      {
        id: "xiao-biaodi-appearance-032-h",
        text: "去你的，拿下來就知道你多會告狀，何必裝。",
        archetype: "landmine",
        retort: "嗚——阿嬤瞪你，碎念一句",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-033",
    text: "媽媽說你後腦勺的頭髮打結像鳥窩一樣。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-033-a",
        text: "去死，打結是鳥窩，你要不要進來認養一隻。",
        archetype: "perfect",
        retort: "……媽媽臉一黑轉頭罵幹",
      },
      {
        id: "xiao-biaodi-appearance-033-b",
        text: "靠，你幫我梳開，你比較細心。",
        archetype: "deflect",
        retort: "好啊！我來幫你梳梳看！",
      },
      {
        id: "xiao-biaodi-appearance-033-c",
        text: "笑死，先梳自己的頭比打結重要吧。",
        archetype: "deflect",
        retort: "對耶！我先照鏡子！",
      },
      {
        id: "xiao-biaodi-appearance-033-d",
        text: "對啊，幹……早上沒時間梳，就打結了……",
        archetype: "meek",
        retort: "沒時間梳喔，那也太趕了吧。",
      },
      {
        id: "xiao-biaodi-appearance-033-e",
        text: "靠……可能睡覺翻來翻去，纏在一起了……",
        archetype: "meek",
        retort: "纏在一起？那快去梳開啊。",
      },
      {
        id: "xiao-biaodi-appearance-033-f",
        text: "他媽的，打結頭髮是我今年野性風格啦。",
        archetype: "backfire",
        retort: "……（媽媽已經拿出梳子）",
      },
      {
        id: "xiao-biaodi-appearance-033-g",
        text: "機掰，鳥窩造型才是今年最前衛的宣言。",
        archetype: "backfire",
        retort: "（小表弟愣住，沒聽懂）",
      },
      {
        id: "xiao-biaodi-appearance-033-h",
        text: "去你的，先把考卷拿出來，再說我的頭。",
        archetype: "landmine",
        retort: "全場安靜，你媽罵你欠揍",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-034",
    text: "姑姑說阿嬤買的花襯衫給你穿，好不好看？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-034-a",
        text: "幹，好看，穿上它我是全場最喜氣的人。",
        archetype: "perfect",
        retort: "……姑姑臉一僵，假笑帶過",
      },
      {
        id: "xiao-biaodi-appearance-034-b",
        text: "靠，姑姑你也穿一件，我們搭配一下？",
        archetype: "deflect",
        retort: "哎唷，我才不要穿花襯衫呢！",
      },
      {
        id: "xiao-biaodi-appearance-034-c",
        text: "笑死，阿嬤開不開心比好不好看重要。",
        archetype: "deflect",
        retort: "阿嬤開心比較重要啦！",
      },
      {
        id: "xiao-biaodi-appearance-034-d",
        text: "老實說有點花，幹……但我還是穿了……",
        archetype: "meek",
        retort: "有點花？姑姑——他嫌花——",
      },
      {
        id: "xiao-biaodi-appearance-034-e",
        text: "靠……花色是誇張了點，不好意思拒絕……",
        archetype: "meek",
        retort: "不好意思拒絕？那你很勉強嘛。",
      },
      {
        id: "xiao-biaodi-appearance-034-f",
        text: "他媽的，花襯衫是我今年最大膽的宣言。",
        archetype: "backfire",
        retort: "……（姑姑忍笑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-appearance-034-g",
        text: "機掰，越花越潮，這是我獨創的美學。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看那件襯衫）",
      },
      {
        id: "xiao-biaodi-appearance-034-h",
        text: "去死，阿嬤買的你嫌，先問過你媽敢不敢講。",
        archetype: "landmine",
        retort: "嗚嗚——他哭著找姑姑告狀喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-035",
    text: "老師說你戴的項鍊好俗氣，是夜市買的嗎？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-035-a",
        text: "去你的，俗氣才親民，你買的還更俗。",
        archetype: "perfect",
        retort: "……他臉一黑，說不出話",
      },
      {
        id: "xiao-biaodi-appearance-035-b",
        text: "靠，你猜這條項鍊多少錢買的？",
        archetype: "deflect",
        retort: "我猜一百塊！猜對了嗎？",
      },
      {
        id: "xiao-biaodi-appearance-035-c",
        text: "笑死，先吃塊糖比項鍊重要吧。",
        archetype: "deflect",
        retort: "先吃糖！糖比較重要！",
      },
      {
        id: "xiao-biaodi-appearance-035-d",
        text: "對啊，幹……是夜市買的，可能真的有點俗……",
        archetype: "meek",
        retort: "有點俗喔，那你自己也知道嘛。",
      },
      {
        id: "xiao-biaodi-appearance-035-e",
        text: "靠……喜歡就買了，沒想那麼多啦……",
        archetype: "meek",
        retort: "沒想那麼多？那眼光要練一下了。",
      },
      {
        id: "xiao-biaodi-appearance-035-f",
        text: "他媽的，俗氣是假的，這叫復古草根風。",
        archetype: "backfire",
        retort: "（他沒聽懂，繼續玩手機）",
      },
      {
        id: "xiao-biaodi-appearance-035-g",
        text: "機掰，夜市貨才是真正懂生活的人在戴。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看那條項鍊）",
      },
      {
        id: "xiao-biaodi-appearance-035-h",
        text: "去死，先把功課寫完，再挑剔我的項鍊。",
        archetype: "landmine",
        retort: "嗚——他跑去找媽媽告狀喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-036",
    text: "姑姑說你今天眼睛顏色怪怪的，是戴變色片嗎？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-036-a",
        text: "幹，對，這是限定版，讓你們多看新花樣。",
        archetype: "perfect",
        retort: "……姑姑臉一僵，轉頭跟阿嬤聊別的",
      },
      {
        id: "xiao-biaodi-appearance-036-b",
        text: "靠，你猜是什麼顏色，形容看看？",
        archetype: "deflect",
        retort: "我猜是灰色的！",
      },
      {
        id: "xiao-biaodi-appearance-036-c",
        text: "笑死，先吃塊蘋果比顏色重要吧。",
        archetype: "deflect",
        retort: "好，我先吃蘋果！",
      },
      {
        id: "xiao-biaodi-appearance-036-d",
        text: "對啊，幹……一時興起買來戴戴看，有點怪……",
        archetype: "meek",
        retort: "有點怪喔，那要不要拿下來。",
      },
      {
        id: "xiao-biaodi-appearance-036-e",
        text: "靠……可能真的不太適合我，戴起來怪怪的……",
        archetype: "meek",
        retort: "不適合？姑姑——他自己承認了——",
      },
      {
        id: "xiao-biaodi-appearance-036-f",
        text: "他媽的，特殊瞳色是我今年的品牌識別色。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-appearance-036-g",
        text: "機掰，變色片是靈魂之窗的高級濾鏡。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看他的眼睛）",
      },
      {
        id: "xiao-biaodi-appearance-036-h",
        text: "去你的，回去問你媽這什麼問題，少插嘴。",
        archetype: "landmine",
        retort: "姑姑臉一沉，幹譙一聲瞪你",
      },
    ],
  },
] satisfies Question[];
