import type { Question } from "@/content/types";

// situations:
// - 皺紋變多說變老了
// - 頭頂頭髮變少
// - 眼鏡度數變深
// - 衣服退流行太土
// - 長痘痘
// - 曬黑了
// - 頭髮亂糟糟像剛起床
// - 鬍子沒刮乾淨
// - 肚子變大身材走樣
// - 黑眼圈很重
// - 穿拖鞋邋遢造型
// - 指甲很長沒剪
// - 髮型剪壞很好笑
// - 衣服穿反扣子扣錯
// - 嘴巴周圍有鬍渣
// - 髮型是不是自己剪的
// - 牙齒變黃
// - 眼鏡痕跡讓眼睛變小
// - 穿西裝不習慣
// - 手很粗糙長繭

export default [
  {
    id: "xiao-biaodi-appearance-002",
    text: "媽媽說你眼角有皺紋了，是不是變老了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-002-a",
        text: "皺紋是媽媽自己講的，你才幾歲懂老？",
        archetype: "perfect",
        retort: "……媽媽尷尬笑了兩聲",
      },
      {
        id: "xiao-biaodi-appearance-002-b",
        text: "你要不要幫我數數看有幾條，順便許願？",
        archetype: "deflect",
        retort: "好啊！我來數，一條、兩條！",
      },
      {
        id: "xiao-biaodi-appearance-002-c",
        text: "皺紋重要，還是你要不要先去洗手吃飯？",
        archetype: "deflect",
        retort: "對耶！我先去洗手！",
      },
      {
        id: "xiao-biaodi-appearance-002-d",
        text: "對啊……最近熬夜比較多，老得快……",
        archetype: "meek",
        retort: "老得快喔，那要早點睡了。",
      },
      {
        id: "xiao-biaodi-appearance-002-e",
        text: "可能真的有一點點吧，不太敢照鏡子……",
        archetype: "meek",
        retort: "不敢照？那一定很多條。",
      },
      {
        id: "xiao-biaodi-appearance-002-f",
        text: "皺紋是歲月給的勳章，年輕人不懂。",
        archetype: "backfire",
        retort: "……（媽媽已經轉頭去忙別的事）",
      },
      {
        id: "xiao-biaodi-appearance-002-g",
        text: "這叫做熟成，跟紅酒一樣越陳越香。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-002-h",
        text: "你數學才考幾分，先別說我老。",
        archetype: "landmine",
        retort: "嗚——媽媽他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-003",
    text: "姑姑說你頭頂的頭髮好像變少了耶。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-003-a",
        text: "頭髮少不是我的錯，是遺傳，你問阿公。",
        archetype: "perfect",
        retort: "……姑姑愣住，假笑帶過",
      },
      {
        id: "xiao-biaodi-appearance-003-b",
        text: "你頭髮這麼多，會不會很熱？借我摸一下。",
        archetype: "deflect",
        retort: "好啊！你摸摸看，超軟的！",
      },
      {
        id: "xiao-biaodi-appearance-003-c",
        text: "少了重要，還是你今天有沒有吃年糕重要？",
        archetype: "deflect",
        retort: "吃了！超好吃的！",
      },
      {
        id: "xiao-biaodi-appearance-003-d",
        text: "對啊……最近壓力大，掉了不少……",
        archetype: "meek",
        retort: "掉不少喔，那要多休息了。",
      },
      {
        id: "xiao-biaodi-appearance-003-e",
        text: "可能真的有變少一點點吧……",
        archetype: "meek",
        retort: "變少一點點？姑姑——他承認了——",
      },
      {
        id: "xiao-biaodi-appearance-003-f",
        text: "頭髮少是為了讓陽光更容易照到大腦。",
        archetype: "backfire",
        retort: "……（姑姑忍笑轉頭跟阿嬤說話）",
      },
      {
        id: "xiao-biaodi-appearance-003-g",
        text: "這是我特意打造的智慧型髮量管理。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-003-h",
        text: "Switch都破不了關，先別管我的頭。",
        archetype: "landmine",
        retort: "嗚嗚——他哭著找姑姑告狀",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-004",
    text: "老師說你眼鏡的鏡片變好厚，度數是不是加深了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-004-a",
        text: "度數深是讀書換來的，你老師讀幾冊？",
        archetype: "perfect",
        retort: "……老師説不出話",
      },
      {
        id: "xiao-biaodi-appearance-004-b",
        text: "你猜猜看我度數多少，猜對算你厲害。",
        archetype: "deflect",
        retort: "我猜五百度！很準吧！",
      },
      {
        id: "xiao-biaodi-appearance-004-c",
        text: "度數重要，還是你要不要先幫我倒杯水？",
        archetype: "deflect",
        retort: "好，我去倒水給你！",
      },
      {
        id: "xiao-biaodi-appearance-004-d",
        text: "對啊……最近手機看太多，加深了……",
        archetype: "meek",
        retort: "看太多喔，那要少滑手機了。",
      },
      {
        id: "xiao-biaodi-appearance-004-e",
        text: "應該有加深一點點，不太確定……",
        archetype: "meek",
        retort: "不確定？那快去驗光。",
      },
      {
        id: "xiao-biaodi-appearance-004-f",
        text: "厚鏡片是知識份子的標準配備，懂嗎。",
        archetype: "backfire",
        retort: "……（小表弟已經在玩他的鏡片反光）",
      },
      {
        id: "xiao-biaodi-appearance-004-g",
        text: "度數深才看得到別人看不到的細節。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續玩眼鏡）",
      },
      {
        id: "xiao-biaodi-appearance-004-h",
        text: "你連注音都拼不好，先閉嘴。",
        archetype: "landmine",
        retort: "嗚——他跑去找老師告狀",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-005",
    text: "阿嬤說你這件衣服穿好幾年了，是不是退流行了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-005-a",
        text: "這件是阿嬤買的，你嫌阿嬤沒眼光？",
        archetype: "perfect",
        retort: "……阿嬤笑開懷",
      },
      {
        id: "xiao-biaodi-appearance-005-b",
        text: "阿嬤你身上這件是不是也穿很多年了？",
        archetype: "deflect",
        retort: "哎唷，這件是我的傳家寶啦！",
      },
      {
        id: "xiao-biaodi-appearance-005-c",
        text: "流行重要，還是你要不要先吃塊糖？",
        archetype: "deflect",
        retort: "先吃糖！糖比較重要！",
      },
      {
        id: "xiao-biaodi-appearance-005-d",
        text: "對啊……最近比較沒空買新衣服……",
        archetype: "meek",
        retort: "沒空買喔，那也太克難了。",
      },
      {
        id: "xiao-biaodi-appearance-005-e",
        text: "應該是有點舊了啦，但還很好穿……",
        archetype: "meek",
        retort: "還很好穿？阿嬤——他自己承認舊了——",
      },
      {
        id: "xiao-biaodi-appearance-005-f",
        text: "復古風是設計師都在追的頂尖美學。",
        archetype: "backfire",
        retort: "……（阿嬤搖搖頭繼續織毛衣）",
      },
      {
        id: "xiao-biaodi-appearance-005-g",
        text: "衣服舊了才有故事感，你不懂時尚。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續摸他的衣服）",
      },
      {
        id: "xiao-biaodi-appearance-005-h",
        text: "作業寫完沒，先別管我穿什麼。",
        archetype: "landmine",
        retort: "嗚——阿嬤瞪你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-006",
    text: "姑丈說你臉上長了好幾顆痘痘，是不是壓力大？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-006-a",
        text: "痘痘不是壓力，是姑丈勸酒勸出來的。",
        archetype: "perfect",
        retort: "……姑丈尷尬喝了口酒",
      },
      {
        id: "xiao-biaodi-appearance-006-b",
        text: "你猜猜看我最近都吃什麼，才會長痘痘？",
        archetype: "deflect",
        retort: "我猜是吃太多炸的！",
      },
      {
        id: "xiao-biaodi-appearance-006-c",
        text: "痘痘重要，還是你要不要先喝口湯？",
        archetype: "deflect",
        retort: "好，我先喝湯！",
      },
      {
        id: "xiao-biaodi-appearance-006-d",
        text: "對啊……最近工作壓力真的滿大的……",
        archetype: "meek",
        retort: "壓力大喔，那要多休息了。",
      },
      {
        id: "xiao-biaodi-appearance-006-e",
        text: "可能熬夜熬多了，皮膚變差了……",
        archetype: "meek",
        retort: "熬夜熬多了？那要早點睡。",
      },
      {
        id: "xiao-biaodi-appearance-006-f",
        text: "痘痘是青春期延長賽的證明，懂嗎。",
        archetype: "backfire",
        retort: "……（姑丈聽不懂，繼續喝他的酒）",
      },
      {
        id: "xiao-biaodi-appearance-006-g",
        text: "長痘痘代表我還很年輕，你要羨慕我。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-006-h",
        text: "鞭炮都不敢點，先閉嘴啦。",
        archetype: "landmine",
        retort: "嗚——他哭著找姑丈告狀",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-007",
    text: "媽媽說你曬得好黑，最近都在外面做什麼？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-007-a",
        text: "曬黑是認真上班，媽媽在家比較閒？",
        archetype: "perfect",
        retort: "……媽媽尷尬轉頭",
      },
      {
        id: "xiao-biaodi-appearance-007-b",
        text: "你猜猜看我最近去哪裡玩，曬這麼黑？",
        archetype: "deflect",
        retort: "我猜是去海邊玩！",
      },
      {
        id: "xiao-biaodi-appearance-007-c",
        text: "曬黑重要，還是你要不要先擦點防曬？",
        archetype: "deflect",
        retort: "好，我去拿防曬乳！",
      },
      {
        id: "xiao-biaodi-appearance-007-d",
        text: "對啊……最近工作常常要跑外面……",
        archetype: "meek",
        retort: "跑外面喔，那很辛苦耶。",
      },
      {
        id: "xiao-biaodi-appearance-007-e",
        text: "可能忘記擦防曬了，曬得有點誇張……",
        archetype: "meek",
        retort: "忘記擦？那不會很痛嗎？",
      },
      {
        id: "xiao-biaodi-appearance-007-f",
        text: "曬黑是我今年最成功的自然美黑計畫。",
        archetype: "backfire",
        retort: "……（媽媽轉頭去忙別的事）",
      },
      {
        id: "xiao-biaodi-appearance-007-g",
        text: "黝黑的膚色是熱帶度假風，很潮的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-007-h",
        text: "功課都不會寫，先別說我皮膚。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭跑走",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-008",
    text: "老師說你頭髮亂糟糟的，是不是剛睡醒就出門？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-008-a",
        text: "亂是熬夜工作，你老師管很寬耶。",
        archetype: "perfect",
        retort: "……老師也不知道怎麼接",
      },
      {
        id: "xiao-biaodi-appearance-008-b",
        text: "你要不要幫我整理一下，你比較會弄頭髮。",
        archetype: "deflect",
        retort: "好啊！我幫你抓一下！",
      },
      {
        id: "xiao-biaodi-appearance-008-c",
        text: "頭髮重要，還是你要不要先吃早餐？",
        archetype: "deflect",
        retort: "對耶！我先去吃早餐！",
      },
      {
        id: "xiao-biaodi-appearance-008-d",
        text: "對啊……來的路上真的剛睡醒而已……",
        archetype: "meek",
        retort: "剛睡醒喔，那也太隨便了吧。",
      },
      {
        id: "xiao-biaodi-appearance-008-e",
        text: "沒時間整理啦，出門有點趕……",
        archetype: "meek",
        retort: "沒時間？那早點起床啊。",
      },
      {
        id: "xiao-biaodi-appearance-008-f",
        text: "亂中有序才是頂尖髮型師的高級手法。",
        archetype: "backfire",
        retort: "……（老師忍笑轉頭去忙別的）",
      },
      {
        id: "xiao-biaodi-appearance-008-g",
        text: "這是我今年主打的頹廢風造型。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-008-h",
        text: "書包都收不好，先管好自己。",
        archetype: "landmine",
        retort: "老師皺眉瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-009",
    text: "阿嬤說你下巴的鬍子沒刮乾淨，看起來髒髒的。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-009-a",
        text: "鬍子沒刮，阿嬤是要幫我刮還是嫌？",
        archetype: "perfect",
        retort: "……阿嬤笑而不答",
      },
      {
        id: "xiao-biaodi-appearance-009-b",
        text: "阿嬤你猜我幾天沒刮鬍子了？",
        archetype: "deflect",
        retort: "我猜三天！猜對了嗎？",
      },
      {
        id: "xiao-biaodi-appearance-009-c",
        text: "刮鬍子重要，還是你要不要先坐好吃飯？",
        archetype: "deflect",
        retort: "好啦，我先坐好。",
      },
      {
        id: "xiao-biaodi-appearance-009-d",
        text: "對啊……早上出門太趕忘記刮了……",
        archetype: "meek",
        retort: "忘記刮喔，那也太趕了吧。",
      },
      {
        id: "xiao-biaodi-appearance-009-e",
        text: "最近懶得刮，就留一點點啦……",
        archetype: "meek",
        retort: "懶得刮？阿嬤——他說他懶——",
      },
      {
        id: "xiao-biaodi-appearance-009-f",
        text: "鬍渣是成熟男人的天然配件，很時尚的。",
        archetype: "backfire",
        retort: "……（阿嬤搖搖頭拿出刮鬍刀）",
      },
      {
        id: "xiao-biaodi-appearance-009-g",
        text: "半刮半留是今年最新的型男流行趨勢。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-009-h",
        text: "臉都洗不乾淨，先閉嘴啦。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭抱住阿嬤",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-010",
    text: "姑姑說你肚子變大了，是不是啤酒喝太多？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-010-a",
        text: "肚子大是我認真吃飯，姑姑的嘴比較大。",
        archetype: "perfect",
        retort: "……姑姑轉頭跟阿嬤聊別的",
      },
      {
        id: "xiao-biaodi-appearance-010-b",
        text: "姑姑你猜我今年吃了幾碗年菜？",
        archetype: "deflect",
        retort: "我猜三碗！你很會吃耶！",
      },
      {
        id: "xiao-biaodi-appearance-010-c",
        text: "肚子重要，還是這道菜要不要趁熱吃重要？",
        archetype: "deflect",
        retort: "趁熱吃比較重要啦！",
      },
      {
        id: "xiao-biaodi-appearance-010-d",
        text: "對啊……最近應酬多，肚子真的大了……",
        archetype: "meek",
        retort: "應酬多喔，那要控制一下了。",
      },
      {
        id: "xiao-biaodi-appearance-010-e",
        text: "可能是年菜吃太多，一時圓潤了……",
        archetype: "meek",
        retort: "圓潤？姑姑——他自己承認胖了——",
      },
      {
        id: "xiao-biaodi-appearance-010-f",
        text: "這是我特意練出來的福氣型身材。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-appearance-010-g",
        text: "肚子大代表器官保護層比較厚，很科學的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續戳他的肚子）",
      },
      {
        id: "xiao-biaodi-appearance-010-h",
        text: "數學都考不好，先別說我肚子。",
        archetype: "landmine",
        retort: "姑姑臉一沉瞪著你",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-011",
    text: "媽媽說你黑眼圈好重，是不是都沒睡覺？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-011-a",
        text: "黑眼圈是加班換的，媽媽白天在忙什麼？",
        archetype: "perfect",
        retort: "……媽媽假裝滑手機",
      },
      {
        id: "xiao-biaodi-appearance-011-b",
        text: "你猜猜看我昨天幾點睡的？",
        archetype: "deflect",
        retort: "我猜凌晨三點！",
      },
      {
        id: "xiao-biaodi-appearance-011-c",
        text: "黑眼圈重要，還是你要不要先吃塊水果？",
        archetype: "deflect",
        retort: "好，我先吃水果！",
      },
      {
        id: "xiao-biaodi-appearance-011-d",
        text: "對啊……最近工作忙，都睡不好……",
        archetype: "meek",
        retort: "睡不好喔，那要多休息了。",
      },
      {
        id: "xiao-biaodi-appearance-011-e",
        text: "可能熬夜追劇追太晚了啦……",
        archetype: "meek",
        retort: "追劇？那也太不自律了吧。",
      },
      {
        id: "xiao-biaodi-appearance-011-f",
        text: "黑眼圈是我特意畫的煙燻妝，很時尚。",
        archetype: "backfire",
        retort: "……（媽媽拿鏡子照給他看）",
      },
      {
        id: "xiao-biaodi-appearance-011-g",
        text: "熊貓眼是今年最流行的野生系穿搭。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-011-h",
        text: "作業拖到十點，先管好自己。",
        archetype: "landmine",
        retort: "媽媽狠狠瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-012",
    text: "老師說你穿拖鞋來拜年，會不會太邋遢了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-012-a",
        text: "拖鞋舒服，你老師管的也太寬了吧。",
        archetype: "perfect",
        retort: "……老師忍笑轉頭去忙別的",
      },
      {
        id: "xiao-biaodi-appearance-012-b",
        text: "你猜猜看我拖鞋是什麼顏色的？",
        archetype: "deflect",
        retort: "我猜是藍色的！",
      },
      {
        id: "xiao-biaodi-appearance-012-c",
        text: "邋遢重要，還是你要不要先去洗手？",
        archetype: "deflect",
        retort: "好，我先去洗手！",
      },
      {
        id: "xiao-biaodi-appearance-012-d",
        text: "對啊……皮鞋穿一整天腳會很痛……",
        archetype: "meek",
        retort: "會痛喔，那也太不耐操了吧。",
      },
      {
        id: "xiao-biaodi-appearance-012-e",
        text: "本來想穿正式一點，來不及換……",
        archetype: "meek",
        retort: "來不及換？那也太懶了。",
      },
      {
        id: "xiao-biaodi-appearance-012-f",
        text: "拖鞋自由是我今年爭取到的人權。",
        archetype: "backfire",
        retort: "……（老師轉頭跟其他人聊天）",
      },
      {
        id: "xiao-biaodi-appearance-012-g",
        text: "赤腳美學才是今年的居家時尚指標。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看他的拖鞋）",
      },
      {
        id: "xiao-biaodi-appearance-012-h",
        text: "鞋帶都不會綁，先閉嘴啦。",
        archetype: "landmine",
        retort: "全場安靜，老師臉沉了",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-013",
    text: "阿嬤說你指甲長這麼長，是不是很久沒剪了？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-013-a",
        text: "留長是要幫阿嬤剝橘子，別嫌。",
        archetype: "perfect",
        retort: "……阿嬤笑了，招手要橘子",
      },
      {
        id: "xiao-biaodi-appearance-013-b",
        text: "阿嬤你猜我指甲有多長，量量看？",
        archetype: "deflect",
        retort: "來，我幫你量！",
      },
      {
        id: "xiao-biaodi-appearance-013-c",
        text: "指甲重要，還是你要不要先吃塊瓜子？",
        archetype: "deflect",
        retort: "好，我先吃瓜子！",
      },
      {
        id: "xiao-biaodi-appearance-013-d",
        text: "對啊……最近真的太忙，忘記剪了……",
        archetype: "meek",
        retort: "忘記剪喔，那看起來很怪耶。",
      },
      {
        id: "xiao-biaodi-appearance-013-e",
        text: "有點長沒錯，等一下就去剪……",
        archetype: "meek",
        retort: "等一下？阿嬤——他說他會去剪——",
      },
      {
        id: "xiao-biaodi-appearance-013-f",
        text: "長指甲是我彈鋼琴的秘密武器，很專業。",
        archetype: "backfire",
        retort: "……（阿嬤已經拿出指甲刀）",
      },
      {
        id: "xiao-biaodi-appearance-013-g",
        text: "指甲長是為了展現我的耐心，懂修養嗎。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看他的指甲）",
      },
      {
        id: "xiao-biaodi-appearance-013-h",
        text: "指甲咬到禿，先別說我的。",
        archetype: "landmine",
        retort: "阿嬤心疼地瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-014",
    text: "姑姑說你這次剪的髮型好好笑，是誰剪的？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-014-a",
        text: "剪壞省下的錢，夠包姑姑的紅包了。",
        archetype: "perfect",
        retort: "……姑姑忍笑轉頭去找阿嬤",
      },
      {
        id: "xiao-biaodi-appearance-014-b",
        text: "你猜猜看是哪一家理髮店剪的？",
        archetype: "deflect",
        retort: "我猜是巷口那家！",
      },
      {
        id: "xiao-biaodi-appearance-014-c",
        text: "髮型重要，還是你要不要先吃塊蛋糕？",
        archetype: "deflect",
        retort: "好，我先吃蛋糕！",
      },
      {
        id: "xiao-biaodi-appearance-014-d",
        text: "對啊……去了一家新的理髮店，剪壞了……",
        archetype: "meek",
        retort: "剪壞了喔，那也太倒楣了吧。",
      },
      {
        id: "xiao-biaodi-appearance-014-e",
        text: "本來想換個新造型，結果失敗了……",
        archetype: "meek",
        retort: "失敗了？姑姑——他自己承認失敗——",
      },
      {
        id: "xiao-biaodi-appearance-014-f",
        text: "這是走前衛藝術路線，你們還不懂欣賞。",
        archetype: "backfire",
        retort: "……（姑姑忍笑轉頭跟阿嬤說悄悄話）",
      },
      {
        id: "xiao-biaodi-appearance-014-g",
        text: "髮型不對稱才是今年最潮的設計理念。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-014-h",
        text: "Switch打輸我，先閉嘴啦。",
        archetype: "landmine",
        retort: "嗚——姑姑你看他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-015",
    text: "老師說你扣子扣錯格了，是不是很趕才出門？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-015-a",
        text: "扣錯格關你老師什麼事，她很閒喔？",
        archetype: "perfect",
        retort: "……老師尷尬清了清喉嚨",
      },
      {
        id: "xiao-biaodi-appearance-015-b",
        text: "你幫我看看還有沒有扣錯的地方？",
        archetype: "deflect",
        retort: "好，我幫你檢查一下！",
      },
      {
        id: "xiao-biaodi-appearance-015-c",
        text: "扣子重要，還是你要不要先繫好鞋帶？",
        archetype: "deflect",
        retort: "對耶！我先繫鞋帶！",
      },
      {
        id: "xiao-biaodi-appearance-015-d",
        text: "對啊……出門真的太趕，沒注意到……",
        archetype: "meek",
        retort: "沒注意到喔，那也太粗心了。",
      },
      {
        id: "xiao-biaodi-appearance-015-e",
        text: "可能起床晚了，隨便套一下就出門……",
        archetype: "meek",
        retort: "隨便套？那也太邋遢了吧。",
      },
      {
        id: "xiao-biaodi-appearance-015-f",
        text: "扣錯格是我今年的品牌識別，記得起來。",
        archetype: "backfire",
        retort: "……（老師已經幫他重新扣好）",
      },
      {
        id: "xiao-biaodi-appearance-015-g",
        text: "錯位美學才是設計師的最高境界。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-015-h",
        text: "拉鍊都拉不好，先管好自己。",
        archetype: "landmine",
        retort: "嗚嗚——他哭著找老師評理",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-016",
    text: "阿嬤說你嘴巴旁邊都是鬍渣，扎不扎人？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-016-a",
        text: "扎不扎人試試看就知道，阿嬤你敢嗎？",
        archetype: "perfect",
        retort: "……阿嬤笑了，摸摸口袋",
      },
      {
        id: "xiao-biaodi-appearance-016-b",
        text: "阿嬤你要不要親一下試試看扎不扎？",
        archetype: "deflect",
        retort: "哎唷才不要，你自己試！",
      },
      {
        id: "xiao-biaodi-appearance-016-c",
        text: "鬍渣重要，還是你要不要先喝口熱湯？",
        archetype: "deflect",
        retort: "好，先喝熱湯暖暖身！",
      },
      {
        id: "xiao-biaodi-appearance-016-d",
        text: "對啊……最近懶得刮，扎扎的……",
        archetype: "meek",
        retort: "扎扎的喔，那也太懶了吧。",
      },
      {
        id: "xiao-biaodi-appearance-016-e",
        text: "可能真的有點扎人，不好意思……",
        archetype: "meek",
        retort: "扎人？那快去刮一刮。",
      },
      {
        id: "xiao-biaodi-appearance-016-f",
        text: "鬍渣是天然的按摩工具，很養生的。",
        archetype: "backfire",
        retort: "……（阿嬤搖搖頭去拿刮鬍刀）",
      },
      {
        id: "xiao-biaodi-appearance-016-g",
        text: "扎人才代表男子氣概，你不懂啦。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-016-h",
        text: "回去問你媽這種事，別在這鬧。",
        archetype: "landmine",
        retort: "嗚——阿嬤你看他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-017",
    text: "姑丈說你這個髮型看起來是自己剪的？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-017-a",
        text: "是我自己剪的，姑丈你也想試試看？",
        archetype: "perfect",
        retort: "……姑丈尷尬乾笑兩聲",
      },
      {
        id: "xiao-biaodi-appearance-017-b",
        text: "你猜猜看我用什麼工具剪的？",
        archetype: "deflect",
        retort: "我猜是廚房的剪刀！",
      },
      {
        id: "xiao-biaodi-appearance-017-c",
        text: "自己剪重要，還是你的酒喝夠了重要？",
        archetype: "deflect",
        retort: "哎唷，這杯我還要喝呢。",
      },
      {
        id: "xiao-biaodi-appearance-017-d",
        text: "對啊……疫情期間學會自己剪，就一直剪了……",
        archetype: "meek",
        retort: "自己剪喔，難怪長這樣。",
      },
      {
        id: "xiao-biaodi-appearance-017-e",
        text: "省錢自己剪，效果沒有很好啦……",
        archetype: "meek",
        retort: "沒有很好？那快去找師傅。",
      },
      {
        id: "xiao-biaodi-appearance-017-f",
        text: "自己剪是一種極簡風格的宣言，很潮的。",
        archetype: "backfire",
        retort: "……（姑丈搖搖頭繼續喝酒）",
      },
      {
        id: "xiao-biaodi-appearance-017-g",
        text: "手殘剪髮才是真正的行為藝術先驅。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-017-h",
        text: "告狀之前先想想你自己愛哭。",
        archetype: "landmine",
        retort: "姑丈臉一沉瞪著你",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-018",
    text: "媽媽說你牙齒變黃了，是不是咖啡喝太多？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-018-a",
        text: "咖啡因是加班換的，媽媽你退休真好。",
        archetype: "perfect",
        retort: "……媽媽憋笑轉頭喝水",
      },
      {
        id: "xiao-biaodi-appearance-018-b",
        text: "你猜猜看我一天喝幾杯咖啡？",
        archetype: "deflect",
        retort: "我猜三杯！你很會喝耶！",
      },
      {
        id: "xiao-biaodi-appearance-018-c",
        text: "牙齒重要，還是你要不要先漱漱口？",
        archetype: "deflect",
        retort: "好，我先去漱口！",
      },
      {
        id: "xiao-biaodi-appearance-018-d",
        text: "對啊……工作太累，都靠咖啡撐著……",
        archetype: "meek",
        retort: "靠咖啡撐？那要少喝一點了。",
      },
      {
        id: "xiao-biaodi-appearance-018-e",
        text: "可能真的喝太多了，牙齒有點黃……",
        archetype: "meek",
        retort: "有點黃？媽媽——他自己承認了——",
      },
      {
        id: "xiao-biaodi-appearance-018-f",
        text: "黃牙是我特意染的復古美齒，很時尚。",
        archetype: "backfire",
        retort: "……（媽媽轉頭去忙別的事）",
      },
      {
        id: "xiao-biaodi-appearance-018-g",
        text: "牙齒黃代表閱歷豐富，你不懂。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-018-h",
        text: "成績單要不要也拿出來比一比。",
        archetype: "landmine",
        retort: "嗚——他哭著找媽媽",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-019",
    text: "老師說你戴眼鏡的痕跡好深，眼睛都變小了。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-019-a",
        text: "眼睛小是認真備考，你老師教出來的？",
        archetype: "perfect",
        retort: "……老師假裝在看課本",
      },
      {
        id: "xiao-biaodi-appearance-019-b",
        text: "你要不要試戴我的眼鏡，看看有什麼感覺？",
        archetype: "deflect",
        retort: "好啊！我來試戴看看！",
      },
      {
        id: "xiao-biaodi-appearance-019-c",
        text: "眼睛重要，還是你要不要先休息一下眼睛？",
        archetype: "deflect",
        retort: "對耶，我先閉眼休息！",
      },
      {
        id: "xiao-biaodi-appearance-019-d",
        text: "對啊……戴太久，鼻樑跟眼睛都痕跡很深……",
        archetype: "meek",
        retort: "痕跡很深喔，那要拿下來透氣。",
      },
      {
        id: "xiao-biaodi-appearance-019-e",
        text: "可能真的看起來小了一點吧……",
        archetype: "meek",
        retort: "小了一點？那你敢拿下眼鏡嗎？",
      },
      {
        id: "xiao-biaodi-appearance-019-f",
        text: "眼睛小是為了聚焦人生重點，懂哲學嗎。",
        archetype: "backfire",
        retort: "……（老師忍笑轉頭去忙別的）",
      },
      {
        id: "xiao-biaodi-appearance-019-g",
        text: "瞇瞇眼是今年最潮的知性風格。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-019-h",
        text: "考卷都不敢拿出來，先閉嘴。",
        archetype: "landmine",
        retort: "老師立刻過來拉開你們",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-020",
    text: "阿嬤說你穿西裝好不習慣，走路怪怪的。",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-020-a",
        text: "走路怪是在練大人的沉穩，阿嬤別笑。",
        archetype: "perfect",
        retort: "……阿嬤笑到合不攏嘴",
      },
      {
        id: "xiao-biaodi-appearance-020-b",
        text: "阿嬤你猜這件西裝是租的還是買的？",
        archetype: "deflect",
        retort: "我猜是租的！",
      },
      {
        id: "xiao-biaodi-appearance-020-c",
        text: "西裝重要，還是你要不要先坐下休息？",
        archetype: "deflect",
        retort: "好啦，我先坐一下。",
      },
      {
        id: "xiao-biaodi-appearance-020-d",
        text: "對啊……很少穿，走路真的卡卡的……",
        archetype: "meek",
        retort: "卡卡的喔，那也太不習慣了。",
      },
      {
        id: "xiao-biaodi-appearance-020-e",
        text: "領帶勒得有點緊，不太自在……",
        archetype: "meek",
        retort: "不自在？那你幹嘛穿啊。",
      },
      {
        id: "xiao-biaodi-appearance-020-f",
        text: "這是我特意練的機器人風格走路，很潮。",
        archetype: "backfire",
        retort: "……（阿嬤搖搖頭繼續看電視）",
      },
      {
        id: "xiao-biaodi-appearance-020-g",
        text: "西裝走路卡才是有錢人的日常步伐。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-appearance-020-h",
        text: "Switch連新手村都過不去，別說我。",
        archetype: "landmine",
        retort: "全場安靜，阿嬤臉垮了",
      },
    ],
  },
  {
    id: "xiao-biaodi-appearance-021",
    text: "姑姑說你的手好粗，是不是工作很辛苦？",
    topic: "appearance",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-appearance-021-a",
        text: "手粗是工作辛苦，姑姑的嘴倒是很閒。",
        archetype: "perfect",
        retort: "……姑姑乾笑兩聲閃人",
      },
      {
        id: "xiao-biaodi-appearance-021-b",
        text: "你摸摸看，猜猜看是哪裡長的繭？",
        archetype: "deflect",
        retort: "我猜是打電腦長的！",
      },
      {
        id: "xiao-biaodi-appearance-021-c",
        text: "手粗重要，還是你要不要先吃塊點心？",
        archetype: "deflect",
        retort: "好，我先吃點心！",
      },
      {
        id: "xiao-biaodi-appearance-021-d",
        text: "對啊……工作真的滿辛苦的，手都變粗了……",
        archetype: "meek",
        retort: "變粗了喔，那要好好保養。",
      },
      {
        id: "xiao-biaodi-appearance-021-e",
        text: "可能是常常搬東西，長了一點繭……",
        archetype: "meek",
        retort: "長繭了？姑姑——他手都是繭——",
      },
      {
        id: "xiao-biaodi-appearance-021-f",
        text: "粗糙的手掌是我努力生活的紋路藝術。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-appearance-021-g",
        text: "繭是天然的防護甲，很實用的裝備。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續摸他的手）",
      },
      {
        id: "xiao-biaodi-appearance-021-h",
        text: "先去把功課寫完，再管我的手。",
        archetype: "landmine",
        retort: "全場安靜，姑姑臉綠了",
      },
    ],
  },
] satisfies Question[];
