import type { Question } from "@/content/types";

// situations:
// - 搶遙控器比薪水
// - 玩Switch輸了說人生輸贏
// - 門框刻度比身高長高幅度
// - 翻手機相簿問感情進度
// - 餐桌下踢腳比薪水差距
// - 放鞭炮比膽量
// - 鄰居小孩考第一名比成績
// - 學大人碰杯談升官發財
// - 塞車車上比有沒有車
// - 客廳拼樂高比做事快慢
// - 翻舊照片比小時候身高
// - 分糖果數量比誰得寵
// - 貼春聯貼歪比做事能力
// - 旁觀打麻將比誰有本事
// - 猜謎搶答輸比反應快慢
// - 紅包袋圖案比誰的潮
// - 排隊等發紅包比誰嘴甜
// - 全家福站角落比幸福
// - 端菜灑出來比做事能力
// - 打陀螺比賽比恆心

export default [
  {
    id: "xiao-biaodi-comparison-002",
    text: "媽媽說你月薪輸表哥，遙控器讓給他啦！",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-002-a",
        text: "遙控器讓你，我掌控的是媽媽的臉色。",
        archetype: "perfect",
        retort: "……媽媽尷尬轉頭",
      },
      {
        id: "xiao-biaodi-comparison-002-b",
        text: "好啊，那你也讓我看一集你最愛的卡通。",
        archetype: "deflect",
        retort: "好啊！那你要看嗎？",
      },
      {
        id: "xiao-biaodi-comparison-002-c",
        text: "先說說看，表哥最近是不是也在找新工作？",
        archetype: "deflect",
        retort: "我不知道，我只知道電視。",
      },
      {
        id: "xiao-biaodi-comparison-002-d",
        text: "喔……好，你轉吧……",
        archetype: "meek",
        retort: "你薪水真的比較少喔？",
      },
      {
        id: "xiao-biaodi-comparison-002-e",
        text: "是比較少啦，但夠用……",
        archetype: "meek",
        retort: "夠用是多少啦？",
      },
      {
        id: "xiao-biaodi-comparison-002-f",
        text: "薪水少但快樂指數破表，懂嗎小朋友。",
        archetype: "backfire",
        retort: "……（小表弟已經在轉台了）",
      },
      {
        id: "xiao-biaodi-comparison-002-g",
        text: "哥哥走的是財富自由後期路線。",
        archetype: "backfire",
        retort: "（小表弟沒在聽，轉到卡通台）",
      },
      {
        id: "xiao-biaodi-comparison-002-h",
        text: "遙控器搶輸我，先去看你的成績單。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭跑走",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-003",
    text: "老師說遊戲打輸不能哭，你剛剛哭了吼？",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-003-a",
        text: "我沒哭，是感動你連遊戲都要作弊贏。",
        archetype: "perfect",
        retort: "……他呆住，不知道怎麼接",
      },
      {
        id: "xiao-biaodi-comparison-003-b",
        text: "厲害捏，要不要教教我怎麼連招？",
        archetype: "deflect",
        retort: "好啊！我教你，坐好聽課！",
      },
      {
        id: "xiao-biaodi-comparison-003-c",
        text: "分數這麼會算，數學作業寫完了嗎？",
        archetype: "deflect",
        retort: "……作業還沒寫啦。",
      },
      {
        id: "xiao-biaodi-comparison-003-d",
        text: "好啦，我輸了，有一點不甘心……",
        archetype: "meek",
        retort: "哈哈哈輸了輸了！",
      },
      {
        id: "xiao-biaodi-comparison-003-e",
        text: "眼睛進沙子而已啦……",
        archetype: "meek",
        retort: "進沙子還一直擦眼睛？",
      },
      {
        id: "xiao-biaodi-comparison-003-f",
        text: "那是戰術性流淚，懂嗎。",
        archetype: "backfire",
        retort: "……（小表弟一臉問號）",
      },
      {
        id: "xiao-biaodi-comparison-003-g",
        text: "大人輸了要保留最後的尊嚴。",
        archetype: "backfire",
        retort: "（小表弟已經在選下一關）",
      },
      {
        id: "xiao-biaodi-comparison-003-h",
        text: "輸了就哭，先去練Switch再說。",
        archetype: "landmine",
        retort: "他媽媽皺眉瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-004",
    text: "阿嬤說我今年長高五公分，你呢？",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-004-a",
        text: "我橫向發展，體積比你長高划算多了。",
        archetype: "perfect",
        retort: "……阿嬤笑而不答",
      },
      {
        id: "xiao-biaodi-comparison-004-b",
        text: "厲害！那你猜猜看我現在幾公分？",
        archetype: "deflect",
        retort: "我猜……跟電視一樣高！",
      },
      {
        id: "xiao-biaodi-comparison-004-c",
        text: "長高要多喝湯，你今天喝了嗎？",
        archetype: "deflect",
        retort: "喝了！阿嬤煮的最好喝！",
      },
      {
        id: "xiao-biaodi-comparison-004-d",
        text: "我今年好像沒有長高……",
        archetype: "meek",
        retort: "都沒長高？阿嬤——他沒長高——",
      },
      {
        id: "xiao-biaodi-comparison-004-e",
        text: "可能一兩公分吧，不確定……",
        archetype: "meek",
        retort: "才一兩公分，很慢耶。",
      },
      {
        id: "xiao-biaodi-comparison-004-f",
        text: "我把身高都拿去長智慧了。",
        archetype: "backfire",
        retort: "……（小表弟量完自己的又跑走了）",
      },
      {
        id: "xiao-biaodi-comparison-004-g",
        text: "重點是氣場高，不是身高。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續畫刻度）",
      },
      {
        id: "xiao-biaodi-comparison-004-h",
        text: "量身高很無聊，先量你考幾分。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭抱住阿嬤",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-005",
    text: "媽媽說你手機裡都沒有女朋友的照片。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-005-a",
        text: "滿滿都是我自己，這叫媽媽也管不到的隱私。",
        archetype: "perfect",
        retort: "……媽媽假裝滑手機",
      },
      {
        id: "xiao-biaodi-comparison-005-b",
        text: "要不要看我手機裡的遊戲，比你的卡通酷。",
        archetype: "deflect",
        retort: "真的假的，給我玩一下！",
      },
      {
        id: "xiao-biaodi-comparison-005-c",
        text: "先說，你手機裡都存什麼，交換一下？",
        archetype: "deflect",
        retort: "我才不要給你看！",
      },
      {
        id: "xiao-biaodi-comparison-005-d",
        text: "對啊……最近沒有交往的對象……",
        archetype: "meek",
        retort: "沒有喔！媽媽——他真的沒有——",
      },
      {
        id: "xiao-biaodi-comparison-005-e",
        text: "有幾張朋友的照片而已啦……",
        archetype: "meek",
        retort: "只有朋友喔？沒有女朋友？",
      },
      {
        id: "xiao-biaodi-comparison-005-f",
        text: "我的手機是走極簡風，懂設計嗎。",
        archetype: "backfire",
        retort: "……（小表弟已經去滑他自己的手機）",
      },
      {
        id: "xiao-biaodi-comparison-005-g",
        text: "哥哥現在專注在自我提升期。",
        archetype: "backfire",
        retort: "（小表弟聽不懂，繼續滑）",
      },
      {
        id: "xiao-biaodi-comparison-005-h",
        text: "翻大人手機之前，先交出你的成績單。",
        archetype: "landmine",
        retort: "媽媽狠狠瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-006",
    text: "姑姑說你薪水比表哥少一大截。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-006-a",
        text: "少一截沒關係，我沒有一個表哥要天天比。",
        archetype: "perfect",
        retort: "……姑姑忍笑轉頭去找阿嬤",
      },
      {
        id: "xiao-biaodi-comparison-006-b",
        text: "姑姑你要不要先吃菜，菜要涼了。",
        archetype: "deflect",
        retort: "好啦好啦，先吃菜。",
      },
      {
        id: "xiao-biaodi-comparison-006-c",
        text: "那姑姑，你猜表哥一個月存多少？",
        archetype: "deflect",
        retort: "這……我也不知道欸。",
      },
      {
        id: "xiao-biaodi-comparison-006-d",
        text: "是啦……我這行本來就比較少……",
        archetype: "meek",
        retort: "比較少喔，那怎麼辦？",
      },
      {
        id: "xiao-biaodi-comparison-006-e",
        text: "還好啦，夠生活就好……",
        archetype: "meek",
        retort: "夠生活？那存錢呢？",
      },
      {
        id: "xiao-biaodi-comparison-006-f",
        text: "我在存的是人生經驗值，無價的。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-comparison-006-g",
        text: "少錢多快樂，這叫財富自由的反面。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，踢桌腳踢更用力）",
      },
      {
        id: "xiao-biaodi-comparison-006-h",
        text: "踢我的腳之前，先想想誰月考沒過。",
        archetype: "landmine",
        retort: "嗚——姑姑你看他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-007",
    text: "老師說膽小的人才不敢點鞭炮，你敢嗎？",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-007-a",
        text: "怕的是你老師吧，她敢自己點一支？",
        archetype: "perfect",
        retort: "……他忍笑，轉頭裝沒聽到",
      },
      {
        id: "xiao-biaodi-comparison-007-b",
        text: "你先點一個給我看看怎麼點。",
        archetype: "deflect",
        retort: "看好囉！我最會點鞭炮了！",
      },
      {
        id: "xiao-biaodi-comparison-007-c",
        text: "膽小跟聰明才是兩回事，你說是不是？",
        archetype: "deflect",
        retort: "呃……好像也對。",
      },
      {
        id: "xiao-biaodi-comparison-007-d",
        text: "老實說我有點怕鞭炮聲……",
        archetype: "meek",
        retort: "怕喔！膽小鬼——",
      },
      {
        id: "xiao-biaodi-comparison-007-e",
        text: "我可以點，但要離遠一點……",
        archetype: "meek",
        retort: "離遠一點還敢說自己不怕？",
      },
      {
        id: "xiao-biaodi-comparison-007-f",
        text: "我是把恐懼昇華成美學欣賞。",
        archetype: "backfire",
        retort: "……（小表弟已經跑去點下一串）",
      },
      {
        id: "xiao-biaodi-comparison-007-g",
        text: "真正的勇者是懂得敬畏危險。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，自己點去了）",
      },
      {
        id: "xiao-biaodi-comparison-007-h",
        text: "膽小的是你，連鞭炮都要人陪。",
        archetype: "landmine",
        retort: "全場安靜，他臉沉了",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-008",
    text: "阿嬤說隔壁小美這次考試考第一名耶。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-008-a",
        text: "厲害，那你要不要先把自己考卷拿出來？",
        archetype: "perfect",
        retort: "……阿嬤笑了，招手要橘子",
      },
      {
        id: "xiao-biaodi-comparison-008-b",
        text: "那我們來比賽疊碗盤，看誰比較厲害。",
        archetype: "deflect",
        retort: "好啊！我先來！",
      },
      {
        id: "xiao-biaodi-comparison-008-c",
        text: "小美是不是很兇，都不跟你玩？",
        archetype: "deflect",
        retort: "還好啦，她人不錯。",
      },
      {
        id: "xiao-biaodi-comparison-008-d",
        text: "我這次考得不太好……",
        archetype: "meek",
        retort: "考不好喔，那要加油了。",
      },
      {
        id: "xiao-biaodi-comparison-008-e",
        text: "我沒有考第一名，考中間而已……",
        archetype: "meek",
        retort: "中間喔，那要多讀書。",
      },
      {
        id: "xiao-biaodi-comparison-008-f",
        text: "第一名的壓力，你懂嗎小朋友。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊搖頭）",
      },
      {
        id: "xiao-biaodi-comparison-008-g",
        text: "我小時候也是深藏不露的類型。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問阿嬤什麼意思）",
      },
      {
        id: "xiao-biaodi-comparison-008-h",
        text: "考第一名有什麼了不起，別學小美告狀。",
        archetype: "landmine",
        retort: "阿嬤心疼地瞪了你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-009",
    text: "姑丈說今年要跟表哥一樣升官發財。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-009-a",
        text: "祝姑丈先戒酒，我們才有紅包能領。",
        archetype: "perfect",
        retort: "……姑丈灌了口茶不説話",
      },
      {
        id: "xiao-biaodi-comparison-009-b",
        text: "那你今年紅包要包多一點才吉利喔。",
        archetype: "deflect",
        retort: "這個……再看看啦。",
      },
      {
        id: "xiao-biaodi-comparison-009-c",
        text: "先說你的新年新希望是什麼？",
        archetype: "deflect",
        retort: "我要打贏所有Switch遊戲！",
      },
      {
        id: "xiao-biaodi-comparison-009-d",
        text: "升官這種事情要看緣分啦……",
        archetype: "meek",
        retort: "看緣分？那你今年有機會嗎？",
      },
      {
        id: "xiao-biaodi-comparison-009-e",
        text: "我今年目標是不要被裁員……",
        archetype: "meek",
        retort: "裁員！這麼慘喔！",
      },
      {
        id: "xiao-biaodi-comparison-009-f",
        text: "我走的是低調致富路線。",
        archetype: "backfire",
        retort: "……（小表弟一臉茫然舉杯）",
      },
      {
        id: "xiao-biaodi-comparison-009-g",
        text: "發財要順其自然，強求會漏財。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續碰杯）",
      },
      {
        id: "xiao-biaodi-comparison-009-h",
        text: "小孩子喝什麼碰杯，先寫你的作業。",
        archetype: "landmine",
        retort: "全場安靜，姑丈臉綠了",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-010",
    text: "媽媽說你連一台車都沒有，好可憐。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-010-a",
        text: "沒車不可憐，可憐的是塞車的媽媽。",
        archetype: "perfect",
        retort: "……媽媽憋笑轉頭喝水",
      },
      {
        id: "xiao-biaodi-comparison-010-b",
        text: "要不要玩車牌遊戲，看誰先湊到數字？",
        archetype: "deflect",
        retort: "好啊！我最會玩這個了！",
      },
      {
        id: "xiao-biaodi-comparison-010-c",
        text: "你比較想坐我的車還是坐高鐵？",
        archetype: "deflect",
        retort: "高鐵！比較快！",
      },
      {
        id: "xiao-biaodi-comparison-010-d",
        text: "對啊……還沒存到錢買車……",
        archetype: "meek",
        retort: "沒存到錢喔，好可憐。",
      },
      {
        id: "xiao-biaodi-comparison-010-e",
        text: "有在考慮啦，但車貸有點貴……",
        archetype: "meek",
        retort: "車貸貴喔，那要努力賺錢了。",
      },
      {
        id: "xiao-biaodi-comparison-010-f",
        text: "騎風火輪比開車環保又拉風。",
        archetype: "backfire",
        retort: "……（小表弟繼續玩他的車牌遊戲）",
      },
      {
        id: "xiao-biaodi-comparison-010-g",
        text: "共享單車才是未來的趨勢，你不懂。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，看向窗外）",
      },
      {
        id: "xiao-biaodi-comparison-010-h",
        text: "塞車關你什麼事，先管好你的成績。",
        archetype: "landmine",
        retort: "嗚——他哭著找媽媽",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-011",
    text: "老師說做事拖拖拉拉的人以後沒出息。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-011-a",
        text: "你老師改作業也拖三天，先說她。",
        archetype: "perfect",
        retort: "……他尷尬地清了清喉嚨",
      },
      {
        id: "xiao-biaodi-comparison-011-b",
        text: "來，我們來比賽拼樂高，輸的人洗碗。",
        archetype: "deflect",
        retort: "好啊！我一定贏！",
      },
      {
        id: "xiao-biaodi-comparison-011-c",
        text: "你的樂高要不要借我幾塊？",
        archetype: "deflect",
        retort: "可以，但要還我喔！",
      },
      {
        id: "xiao-biaodi-comparison-011-d",
        text: "我做事真的比較慢……在改進了……",
        archetype: "meek",
        retort: "慢喔，那要加快一點。",
      },
      {
        id: "xiao-biaodi-comparison-011-e",
        text: "是有點拖啦，但最後都有做完……",
        archetype: "meek",
        retort: "做完就好？拖到最後才做完？",
      },
      {
        id: "xiao-biaodi-comparison-011-f",
        text: "天才都是最後一刻才交出成果的。",
        archetype: "backfire",
        retort: "……（小表弟繼續拼他的樂高）",
      },
      {
        id: "xiao-biaodi-comparison-011-g",
        text: "拖延症其實是一種創作節奏。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續玩）",
      },
      {
        id: "xiao-biaodi-comparison-011-h",
        text: "拖拉的是你的月考卷，說我？",
        archetype: "landmine",
        retort: "嗚嗚——他哭著找媽媽評理",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-012",
    text: "姑姑說這張你比表哥矮，現在他贏過你了。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-012-a",
        text: "舊照片而已，姑姑你當年腰圍呢？",
        archetype: "perfect",
        retort: "……姑姑乾笑兩聲閃人",
      },
      {
        id: "xiao-biaodi-comparison-012-b",
        text: "這張你笑得好可愛，還有沒有別張？",
        archetype: "deflect",
        retort: "有！我拿相簿給你看！",
      },
      {
        id: "xiao-biaodi-comparison-012-c",
        text: "這張表哥牙齒掉了，好好笑喔。",
        archetype: "deflect",
        retort: "對啊哈哈他那時候好醜！",
      },
      {
        id: "xiao-biaodi-comparison-012-d",
        text: "對啊……我後來長得比較慢……",
        archetype: "meek",
        retort: "比較慢喔，那現在追得上嗎？",
      },
      {
        id: "xiao-biaodi-comparison-012-e",
        text: "現在應該還是矮一點點吧……",
        archetype: "meek",
        retort: "矮一點點？姑姑——他承認了——",
      },
      {
        id: "xiao-biaodi-comparison-012-f",
        text: "身高是假的，氣勢才是真的贏家。",
        archetype: "backfire",
        retort: "……（姑姑翻下一張照片沒理他）",
      },
      {
        id: "xiao-biaodi-comparison-012-g",
        text: "矮個子才是未來的潛力股。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續翻相簿）",
      },
      {
        id: "xiao-biaodi-comparison-012-h",
        text: "舊照片而已，先把你的考卷收好。",
        archetype: "landmine",
        retort: "全場安靜，姑姑臉綠了",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-013",
    text: "阿嬤說表哥拿到的糖果比你多兩顆。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-013-a",
        text: "兩顆糖也要比，阿嬤你偏心幾次？",
        archetype: "perfect",
        retort: "……阿嬤笑了，摸摸口袋",
      },
      {
        id: "xiao-biaodi-comparison-013-b",
        text: "阿嬤你袋子裡是不是還有藏其他口味？",
        archetype: "deflect",
        retort: "哎唷，被你發現了！",
      },
      {
        id: "xiao-biaodi-comparison-013-c",
        text: "那我們來交換糖果，你要哪一種？",
        archetype: "deflect",
        retort: "我要草莓的！謝謝！",
      },
      {
        id: "xiao-biaodi-comparison-013-d",
        text: "對啊……阿嬤比較疼表哥吧……",
        archetype: "meek",
        retort: "疼表哥？阿嬤——他這樣說——",
      },
      {
        id: "xiao-biaodi-comparison-013-e",
        text: "應該是剛好而已，不是故意的……",
        archetype: "meek",
        retort: "剛好？那你數過了嗎？",
      },
      {
        id: "xiao-biaodi-comparison-013-f",
        text: "我在減糖，少吃兩顆是為身體好。",
        archetype: "backfire",
        retort: "……（小表弟自己吃掉一整包）",
      },
      {
        id: "xiao-biaodi-comparison-013-g",
        text: "糖果的價值不在數量，在心意。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續數自己的糖果）",
      },
      {
        id: "xiao-biaodi-comparison-013-h",
        text: "阿嬤疼表哥關你屁事，你顧好你的作業。",
        archetype: "landmine",
        retort: "嗚——阿嬤你看他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-014",
    text: "媽媽說你做什麼事都輸表哥，連春聯都貼歪。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-014-a",
        text: "歪的是春聯，偏心的是媽媽的心。",
        archetype: "perfect",
        retort: "……媽媽偷笑不敢接話",
      },
      {
        id: "xiao-biaodi-comparison-014-b",
        text: "要不要比賽誰先貼完這一副？",
        archetype: "deflect",
        retort: "好啊！我一定比你快！",
      },
      {
        id: "xiao-biaodi-comparison-014-c",
        text: "表哥貼得正，但他有沒有陪你玩？",
        archetype: "deflect",
        retort: "沒有耶，他都在滑手機。",
      },
      {
        id: "xiao-biaodi-comparison-014-d",
        text: "對啦，我手比較笨拙一點……",
        archetype: "meek",
        retort: "笨拙喔，那要多練習。",
      },
      {
        id: "xiao-biaodi-comparison-014-e",
        text: "可能量得不夠準吧，下次改進……",
        archetype: "meek",
        retort: "下次？現在就歪了啊。",
      },
      {
        id: "xiao-biaodi-comparison-014-f",
        text: "這叫做前衛藝術風格，你不懂。",
        archetype: "backfire",
        retort: "……（媽媽把春聯重新貼正）",
      },
      {
        id: "xiao-biaodi-comparison-014-g",
        text: "歪一點才符合黃金比例，懂嗎。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去玩）",
      },
      {
        id: "xiao-biaodi-comparison-014-h",
        text: "煩的是你成績單吧，先別說我。",
        archetype: "landmine",
        retort: "嗚——媽媽你看他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-015",
    text: "姑丈說會打牌才是真本事，你會嗎？",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-015-a",
        text: "真本事是姑丈輸錢還敢說大話。",
        archetype: "perfect",
        retort: "……姑丈轉頭裝忙",
      },
      {
        id: "xiao-biaodi-comparison-015-b",
        text: "教教我嘛，姑丈你是不是全場最厲害？",
        archetype: "deflect",
        retort: "那當然！看我這手！",
      },
      {
        id: "xiao-biaodi-comparison-015-c",
        text: "你要不要也學，長大就會了。",
        archetype: "deflect",
        retort: "我現在就想學啦！",
      },
      {
        id: "xiao-biaodi-comparison-015-d",
        text: "我不太會打牌耶……沒學過……",
        archetype: "meek",
        retort: "沒學過？那以後怎麼辦？",
      },
      {
        id: "xiao-biaodi-comparison-015-e",
        text: "會一點點，但常常記錯規則……",
        archetype: "meek",
        retort: "記錯規則怎麼贏錢啦？",
      },
      {
        id: "xiao-biaodi-comparison-015-f",
        text: "我玩的是心理戰，不靠牌技。",
        archetype: "backfire",
        retort: "……（姑丈繼續看自己的牌，沒理他）",
      },
      {
        id: "xiao-biaodi-comparison-015-g",
        text: "真正的高手都是深藏不露的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，去看別人打牌）",
      },
      {
        id: "xiao-biaodi-comparison-015-h",
        text: "打牌而已你敢玩？先寫完作業再說。",
        archetype: "landmine",
        retort: "姑丈立刻過來護著他",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-016",
    text: "老師說反應快的人才聰明，你剛剛好慢。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-016-a",
        text: "慢的是我，愛比的是你的成績單。",
        archetype: "perfect",
        retort: "……他假裝在滑手機",
      },
      {
        id: "xiao-biaodi-comparison-016-b",
        text: "換你出題，我來當裁判好不好？",
        archetype: "deflect",
        retort: "好！我出一題超難的！",
      },
      {
        id: "xiao-biaodi-comparison-016-c",
        text: "你剛剛那題答案是什麼，教教我。",
        archetype: "deflect",
        retort: "我教你！其實很簡單！",
      },
      {
        id: "xiao-biaodi-comparison-016-d",
        text: "對啊，我反應真的比較慢……",
        archetype: "meek",
        retort: "比較慢喔，那要多練習。",
      },
      {
        id: "xiao-biaodi-comparison-016-e",
        text: "可能剛剛在想別的事情啦……",
        archetype: "meek",
        retort: "想別的事？那就是不專心啊。",
      },
      {
        id: "xiao-biaodi-comparison-016-f",
        text: "我是深思熟慮型，不是反應型。",
        archetype: "backfire",
        retort: "……（小表弟已經出下一題了）",
      },
      {
        id: "xiao-biaodi-comparison-016-g",
        text: "慢工出細活，快答案不一定對。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續搶答）",
      },
      {
        id: "xiao-biaodi-comparison-016-h",
        text: "慢的是你腦子吧，先去看成績單。",
        archetype: "landmine",
        retort: "他媽媽立刻過來拉開你們",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-017",
    text: "姑姑說我的紅包袋是龍的，比你的潮。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-017-a",
        text: "紅包袋而已，姑姑你的審美才該檢討。",
        archetype: "perfect",
        retort: "……姑姑忍笑轉頭説悄悄話",
      },
      {
        id: "xiao-biaodi-comparison-017-b",
        text: "你的紅包袋圖案，是不是自己選的？",
        archetype: "deflect",
        retort: "對啊！我自己選的！",
      },
      {
        id: "xiao-biaodi-comparison-017-c",
        text: "那你要不要跟我交換紅包袋收藏？",
        archetype: "deflect",
        retort: "好啊！但要換一樣潮的！",
      },
      {
        id: "xiao-biaodi-comparison-017-d",
        text: "我的圖案是媽媽隨便挑的……",
        archetype: "meek",
        retort: "隨便挑喔，難怪沒你的潮。",
      },
      {
        id: "xiao-biaodi-comparison-017-e",
        text: "其實我沒有很在意圖案啦……",
        archetype: "meek",
        retort: "不在意？那你輸了都不生氣？",
      },
      {
        id: "xiao-biaodi-comparison-017-f",
        text: "低調的圖案才是真正的潮，你不懂。",
        archetype: "backfire",
        retort: "……（小表弟繼續欣賞自己的紅包袋）",
      },
      {
        id: "xiao-biaodi-comparison-017-g",
        text: "極簡風格才是設計界的最高境界。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，收起紅包袋）",
      },
      {
        id: "xiao-biaodi-comparison-017-h",
        text: "紅包袋醜不醜，關你什麼事啦。",
        archetype: "landmine",
        retort: "姑姑立刻過來護著他",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-018",
    text: "阿嬤說先叫阿嬤的人才有紅包，你都不叫。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-018-a",
        text: "先叫的是我，阿嬤疼不疼看紅包後面。",
        archetype: "perfect",
        retort: "……阿嬤笑到合不攏嘴",
      },
      {
        id: "xiao-biaodi-comparison-018-b",
        text: "阿嬤你今天氣色特別好，是不是擦口紅？",
        archetype: "deflect",
        retort: "哎唷被你發現了！",
      },
      {
        id: "xiao-biaodi-comparison-018-c",
        text: "那你先叫，示範給我看怎麼叫比較好聽。",
        archetype: "deflect",
        retort: "阿嬤——！這樣！",
      },
      {
        id: "xiao-biaodi-comparison-018-d",
        text: "我剛剛在忙別的事情，沒注意到……",
        archetype: "meek",
        retort: "沒注意到，那紅包怎麼辦？",
      },
      {
        id: "xiao-biaodi-comparison-018-e",
        text: "我會叫啦，只是比較害羞……",
        archetype: "meek",
        retort: "害羞就沒紅包了喔。",
      },
      {
        id: "xiao-biaodi-comparison-018-f",
        text: "沉默是最高級的問候方式。",
        archetype: "backfire",
        retort: "……（阿嬤已經去發別人的紅包了）",
      },
      {
        id: "xiao-biaodi-comparison-018-g",
        text: "真正的孝順不需要用嘴巴表達。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續排隊）",
      },
      {
        id: "xiao-biaodi-comparison-018-h",
        text: "叫阿嬤尷尬，你連叫都不敢叫。",
        archetype: "landmine",
        retort: "全場安靜，阿嬤臉垮了",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-019",
    text: "媽媽說你單身站角落，表哥站中間好幸福。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-019-a",
        text: "站中間的是表哥，逼婚的是媽媽。",
        archetype: "perfect",
        retort: "……媽媽故意咳兩聲",
      },
      {
        id: "xiao-biaodi-comparison-019-b",
        text: "那我們來比賽誰的表情比較上相。",
        archetype: "deflect",
        retort: "好啊！我最會擺表情了！",
      },
      {
        id: "xiao-biaodi-comparison-019-c",
        text: "站中間是不是比較累，要一直被拍？",
        archetype: "deflect",
        retort: "對啊，一直要笑好累喔。",
      },
      {
        id: "xiao-biaodi-comparison-019-d",
        text: "對啊……我這次又是自己一個人……",
        archetype: "meek",
        retort: "自己一個人喔，好孤單。",
      },
      {
        id: "xiao-biaodi-comparison-019-e",
        text: "站哪裡都可以啦，沒差……",
        archetype: "meek",
        retort: "沒差？那你怎麼老是角落？",
      },
      {
        id: "xiao-biaodi-comparison-019-f",
        text: "單身是我選的極簡人生風格。",
        archetype: "backfire",
        retort: "……（媽媽在旁邊喊快拍好了）",
      },
      {
        id: "xiao-biaodi-comparison-019-g",
        text: "角落才是真正的黃金比例位置。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續站中間）",
      },
      {
        id: "xiao-biaodi-comparison-019-h",
        text: "不想拍照就去寫作業，別在這鬧。",
        archetype: "landmine",
        retort: "媽媽立刻衝過來罵你",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-020",
    text: "阿嬤說表哥端菜都不會灑，你怎麼灑成這樣。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-020-a",
        text: "端菜灑了，阿嬤偏心灑得更明顯。",
        archetype: "perfect",
        retort: "……阿嬤笑著點頭",
      },
      {
        id: "xiao-biaodi-comparison-020-b",
        text: "阿嬤這道菜好香，是不是加了新食材？",
        archetype: "deflect",
        retort: "對啊！我今年加了一味！",
      },
      {
        id: "xiao-biaodi-comparison-020-c",
        text: "那我幫忙拖地，表哥負責端下一道好嗎？",
        archetype: "deflect",
        retort: "好啊！這樣才公平！",
      },
      {
        id: "xiao-biaodi-comparison-020-d",
        text: "對啊……我端東西真的比較不穩……",
        archetype: "meek",
        retort: "不穩喔，那以後不要端了。",
      },
      {
        id: "xiao-biaodi-comparison-020-e",
        text: "手滑了一下，下次會小心……",
        archetype: "meek",
        retort: "下次？菜都灑了才說下次。",
      },
      {
        id: "xiao-biaodi-comparison-020-f",
        text: "這是我獨創的桌邊擺盤藝術。",
        archetype: "backfire",
        retort: "……（阿嬤已經在擦地板了）",
      },
      {
        id: "xiao-biaodi-comparison-020-g",
        text: "灑出來的部分是要獻給地基主的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續端下一盤）",
      },
      {
        id: "xiao-biaodi-comparison-020-h",
        text: "端菜是有多難，先把碗端穩再說我。",
        archetype: "landmine",
        retort: "阿嬤立刻過來護著他",
      },
    ],
  },
  {
    id: "xiao-biaodi-comparison-021",
    text: "老師說做事要有恆心，你陀螺轉輸就哭。",
    topic: "comparison",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-comparison-021-a",
        text: "哭的是你，輸不起的是老師的臉。",
        archetype: "perfect",
        retort: "……他憋笑，摸摸鼻子",
      },
      {
        id: "xiao-biaodi-comparison-021-b",
        text: "要不要我教你怎麼纏線轉得更久？",
        archetype: "deflect",
        retort: "好啊！教我教我！",
      },
      {
        id: "xiao-biaodi-comparison-021-c",
        text: "你剛剛那盤菜還有沒有，我肚子餓了。",
        archetype: "deflect",
        retort: "有喔！我去幫你拿！",
      },
      {
        id: "xiao-biaodi-comparison-021-d",
        text: "好啦，我輸了心情有點差……",
        archetype: "meek",
        retort: "心情差還在這邊嘟嘴。",
      },
      {
        id: "xiao-biaodi-comparison-021-e",
        text: "陀螺技巧真的沒有你好……",
        archetype: "meek",
        retort: "沒有我好？那要多練習啊。",
      },
      {
        id: "xiao-biaodi-comparison-021-f",
        text: "我轉的是內心的陀螺，恆久不衰。",
        archetype: "backfire",
        retort: "……（小表弟已經去撿他的陀螺了）",
      },
      {
        id: "xiao-biaodi-comparison-021-g",
        text: "輸贏不重要，姿勢帥最重要。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續玩陀螺）",
      },
      {
        id: "xiao-biaodi-comparison-021-h",
        text: "陀螺而已你才愛計較，先寫作業。",
        archetype: "landmine",
        retort: "嗚——他邊哭邊向媽媽告狀",
      },
    ],
  },
] satisfies Question[];
