import type { Question } from "@/content/types";

// situations:
// - 紅包會不會拿去當孝親費退回長輩
// - 紅包有沒有先偷看金額才包
// - 有沒有紅包漏包忘記包給他
// - 紅包是不是要包雙數才吉利
// - 紅包袋上金額欄位有沒有填
// - 可不可以用舊紅包袋重複用
// - 紅包裡是不是被掉包成假鈔開玩笑
// - 問要不要包紅包給交往對象
// - 其他房親戚給的紅包比你多還是少
// - 紅包摸起來軟軟的是不是小額鈔
// - 紅包要當場拆還是回家拆
// - 長大了紅包會不會變少
// - 可不可以代領阿公阿嬤的紅包
// - 紅包裡有沒有藏刮刮樂
// - 過年要不要包紅包給家裡的狗貓
// - 紅包太少可不可以直接嫌少

export default [
  {
    id: "xiao-biaodi-red_envelope-022",
    text: "阿嬤說你賺錢了，紅包是不是要退回來當孝親費？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-022-a",
        text: "幹，孝親費，阿嬤你兒子包了嗎。",
        archetype: "perfect",
        retort: "……阿嬤笑著拍拍你的手",
      },
      {
        id: "xiao-biaodi-red_envelope-022-b",
        text: "靠，阿嬤想要紅包還是想我常回來？",
        archetype: "deflect",
        retort: "當然是你常回來啊！",
      },
      {
        id: "xiao-biaodi-red_envelope-022-c",
        text: "笑死，阿嬤先坐下休息比較重要吧。",
        archetype: "deflect",
        retort: "好啦好啦，我先坐一下。",
      },
      {
        id: "xiao-biaodi-red_envelope-022-d",
        text: "幹……紅包我還是想留著自己花……",
        archetype: "meek",
        retort: "留著喔，那孝親費呢？",
      },
      {
        id: "xiao-biaodi-red_envelope-022-e",
        text: "靠……應該不用退，我沒賺很多啦……",
        archetype: "meek",
        retort: "沒賺很多？阿嬤——他這樣說——",
      },
      {
        id: "xiao-biaodi-red_envelope-022-f",
        text: "機掰，孝親費是舊觀念，我走現代孝道。",
        archetype: "backfire",
        retort: "……（阿嬤聽不懂，繼續織毛衣）",
      },
      {
        id: "xiao-biaodi-red_envelope-022-g",
        text: "他媽的，陪伴才是最高等級的孝親費。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問阿嬤什麼是孝道）",
      },
      {
        id: "xiao-biaodi-red_envelope-022-h",
        text: "去你的，退什麼退，紅包是我的。",
        archetype: "landmine",
        retort: "嗚嗚——他躲阿嬤懷裡哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-023",
    text: "老師說包紅包前要先偷算好金額，你有算嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-023-a",
        text: "去死，算金額，老師算過我薪水嗎。",
        archetype: "perfect",
        retort: "……他呆住，臉一黑接不上話",
      },
      {
        id: "xiao-biaodi-red_envelope-023-b",
        text: "靠，你先說今年最乖的一件事？",
        archetype: "deflect",
        retort: "我今年都自己收玩具耶！",
      },
      {
        id: "xiao-biaodi-red_envelope-023-c",
        text: "笑死，先算算你考幾分比較重要。",
        archetype: "deflect",
        retort: "呃……這個先跳過。",
      },
      {
        id: "xiao-biaodi-red_envelope-023-d",
        text: "幹……我沒先算，包多少媽媽決定……",
        archetype: "meek",
        retort: "媽媽決定的？那你都不知道。",
      },
      {
        id: "xiao-biaodi-red_envelope-023-e",
        text: "靠……有稍微估一下，不算精準啦……",
        archetype: "meek",
        retort: "不精準？那到底多少嘛。",
      },
      {
        id: "xiao-biaodi-red_envelope-023-f",
        text: "他媽的，算金額俗氣，我用直覺。",
        archetype: "backfire",
        retort: "……（小表弟已經在旁邊猜數字）",
      },
      {
        id: "xiao-biaodi-red_envelope-023-g",
        text: "機掰，精準計算不如隨緣，這是哲學。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續猜）",
      },
      {
        id: "xiao-biaodi-red_envelope-023-h",
        text: "去你的，算這麼細，算你及不及格。",
        archetype: "landmine",
        retort: "他媽媽皺眉，幹譙一聲瞪你",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-024",
    text: "姑姑說你去年好像忘記包紅包給我，是不是？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-024-a",
        text: "幹，去年的事，姑姑欠我的作業本呢。",
        archetype: "perfect",
        retort: "……姑姑臉一僵，轉頭説悄悄話",
      },
      {
        id: "xiao-biaodi-red_envelope-024-b",
        text: "靠，你記性這麼好，數學考幾分還記得？",
        archetype: "deflect",
        retort: "呃……我不記得了！",
      },
      {
        id: "xiao-biaodi-red_envelope-024-c",
        text: "笑死，今年的紅包比去年重要吧。",
        archetype: "deflect",
        retort: "今年的比較重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-024-d",
        text: "對不起，幹……去年真的可能忘記了……",
        archetype: "meek",
        retort: "忘記了！姑姑——他真的忘記——",
      },
      {
        id: "xiao-biaodi-red_envelope-024-e",
        text: "靠……可能順序漏掉你了，不是故意的……",
        archetype: "meek",
        retort: "漏掉？那我今年要盯緊一點。",
      },
      {
        id: "xiao-biaodi-red_envelope-024-f",
        text: "他媽的，去年紅包升值成回憶了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-red_envelope-024-g",
        text: "機掰，忘記包才是最深的紀念。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，一臉困惑）",
      },
      {
        id: "xiao-biaodi-red_envelope-024-h",
        text: "去死，翻舊帳，你成績也沒進步。",
        archetype: "landmine",
        retort: "姑姑護著他，罵你欠罵了",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-025",
    text: "阿嬤說紅包要包雙數金額才吉利，你懂嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-025-a",
        text: "靠北，雙數，阿嬤結婚年紀是雙數嗎。",
        archetype: "perfect",
        retort: "……阿嬤笑開懷",
      },
      {
        id: "xiao-biaodi-red_envelope-025-b",
        text: "靠，阿嬤最喜歡的雙數是幾號？",
        archetype: "deflect",
        retort: "阿嬤最喜歡六跟八！",
      },
      {
        id: "xiao-biaodi-red_envelope-025-c",
        text: "笑死，吃兩碗飯比雙數重要吧。",
        archetype: "deflect",
        retort: "吃兩碗了！超飽的！",
      },
      {
        id: "xiao-biaodi-red_envelope-025-d",
        text: "幹……我不懂這規矩，隨便包的……",
        archetype: "meek",
        retort: "隨便包喔，那沒有誠意耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-025-e",
        text: "靠……應該有注意，但不確定算對……",
        archetype: "meek",
        retort: "不確定？那要重新算一次。",
      },
      {
        id: "xiao-biaodi-red_envelope-025-f",
        text: "他媽的，數字規矩舊了，我信磁場。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊搖搖頭）",
      },
      {
        id: "xiao-biaodi-red_envelope-025-g",
        text: "機掰，單數才是我獨創的幸運公式。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續數自己的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-025-h",
        text: "去你的，雙數單數無聊，算你考幾分。",
        archetype: "landmine",
        retort: "嗚——阿嬤瞪你，碎念一句",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-026",
    text: "老師說紅包袋上要寫金額才不會搞混，你寫了嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-026-a",
        text: "去死，寫金額？老師分數也寫錯過。",
        archetype: "perfect",
        retort: "……他臉一黑，裝沒聽到",
      },
      {
        id: "xiao-biaodi-red_envelope-026-b",
        text: "靠，你紅包袋欄位都寫些什麼字？",
        archetype: "deflect",
        retort: "我寫了恭喜發財四個字！",
      },
      {
        id: "xiao-biaodi-red_envelope-026-c",
        text: "笑死，圖案比寫金額重要吧。",
        archetype: "deflect",
        retort: "圖案比較重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-026-d",
        text: "幹……沒有寫，怕寫錯數字尷尬……",
        archetype: "meek",
        retort: "怕寫錯喔，那乾脆別寫了。",
      },
      {
        id: "xiao-biaodi-red_envelope-026-e",
        text: "靠……本來想寫，後來忘記了啦……",
        archetype: "meek",
        retort: "忘記了？那你很粗心耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-026-f",
        text: "他媽的，空白欄位是命運的驚喜。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續翻紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-026-g",
        text: "機掰，填數字太俗，我走神秘主義。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，一臉茫然）",
      },
      {
        id: "xiao-biaodi-red_envelope-026-h",
        text: "去你的，要不要填，先寫完作業。",
        archetype: "landmine",
        retort: "全場安靜，他臉沉了罵幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-027",
    text: "姑丈說你是不是拿舊紅包袋重複裝，太省了吧？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-027-a",
        text: "幹，省而已，姑丈酒錢怎麼不省。",
        archetype: "perfect",
        retort: "……姑丈灌口茶不説話罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-027-b",
        text: "靠，你猜這紅包袋是哪一年的？",
        archetype: "deflect",
        retort: "這個……看起來有點舊耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-027-c",
        text: "笑死，你紅酒喝夠了沒比較重要。",
        archetype: "deflect",
        retort: "哎唷，這杯我還要喝呢。",
      },
      {
        id: "xiao-biaodi-red_envelope-027-d",
        text: "對啊，幹……新紅包袋剛好用完了……",
        archetype: "meek",
        retort: "用完了？那也太克難了吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-027-e",
        text: "靠……是有點舊，但裡面東西是新的……",
        archetype: "meek",
        retort: "裡面新的？那外面幹嘛不換？",
      },
      {
        id: "xiao-biaodi-red_envelope-027-f",
        text: "他媽的，舊紅包袋是限量絕版。",
        archetype: "backfire",
        retort: "……（姑丈搖搖頭繼續喝酒）",
      },
      {
        id: "xiao-biaodi-red_envelope-027-g",
        text: "機掰，復古風是今年最潮的美學。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續看紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-027-h",
        text: "去死，舊的怎麼了，你舊考卷更該檢討。",
        archetype: "landmine",
        retort: "全場安靜，姑丈罵你三小",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-028",
    text: "媽媽說紅包裡搞不好被掉包成假鈔了，你檢查了嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-028-a",
        text: "去你的，假鈔，媽媽保養品是真的嗎。",
        archetype: "perfect",
        retort: "……媽媽臉一黑轉頭罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-028-b",
        text: "靠，你幫我檢查，你比較會看鈔票。",
        archetype: "deflect",
        retort: "好啊！我最會看鈔票了！",
      },
      {
        id: "xiao-biaodi-red_envelope-028-c",
        text: "笑死，先喝口湯暖暖身比較重要。",
        archetype: "deflect",
        retort: "好啊，先喝湯比較重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-028-d",
        text: "幹……我沒檢查，希望不是假的……",
        archetype: "meek",
        retort: "希望而已喔，那有點危險耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-028-e",
        text: "靠……看起來是真的，但不太確定……",
        archetype: "meek",
        retort: "不確定？那你敢花嗎？",
      },
      {
        id: "xiao-biaodi-red_envelope-028-f",
        text: "他媽的，真假鈔票我都收，包容主義。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-028-g",
        text: "機掰，假鈔比較有紀念價值，懂收藏？",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究鈔票）",
      },
      {
        id: "xiao-biaodi-red_envelope-028-h",
        text: "去死，假的就假的，大驚小怪的是你成績。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭跑走喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-029",
    text: "姑姑說你有對象的話也要包紅包給他喔。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-029-a",
        text: "幹，有對象再說，姑姑你對象呢，先包。",
        archetype: "perfect",
        retort: "……姑姑轉頭裝沒事罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-029-b",
        text: "靠，你覺得包多少才叫有誠意？",
        archetype: "deflect",
        retort: "我覺得要包很多才有誠意！",
      },
      {
        id: "xiao-biaodi-red_envelope-029-c",
        text: "笑死，糖果吃夠了沒比較重要。",
        archetype: "deflect",
        retort: "糖果吃夠了！超甜的！",
      },
      {
        id: "xiao-biaodi-red_envelope-029-d",
        text: "還沒有對象啦，幹……等有了再說……",
        archetype: "meek",
        retort: "還沒有喔！姑姑——他真的沒有——",
      },
      {
        id: "xiao-biaodi-red_envelope-029-e",
        text: "靠……應該會包一點意思意思吧……",
        archetype: "meek",
        retort: "意思意思？那對方會不會生氣？",
      },
      {
        id: "xiao-biaodi-red_envelope-029-f",
        text: "他媽的，感情不能用金額衡量啦。",
        archetype: "backfire",
        retort: "……（姑姑轉頭跟阿嬤聊別的）",
      },
      {
        id: "xiao-biaodi-red_envelope-029-g",
        text: "機掰，單身不用包紅包，這叫節流。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續問對象是什麼意思）",
      },
      {
        id: "xiao-biaodi-red_envelope-029-h",
        text: "去你的，有沒有對象，先寫完作業。",
        archetype: "landmine",
        retort: "嗚——姑姑瞪你，罵你三小",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-030",
    text: "阿嬤說二伯給我的紅包比你的厚，你會不會輸了？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-030-a",
        text: "靠北，厚薄，阿嬤疼孫也分厚薄嗎。",
        archetype: "perfect",
        retort: "……阿嬤笑而不答",
      },
      {
        id: "xiao-biaodi-red_envelope-030-b",
        text: "靠，二伯給你的紅包上寫了什麼字？",
        archetype: "deflect",
        retort: "他寫的是身體健康！",
      },
      {
        id: "xiao-biaodi-red_envelope-030-c",
        text: "笑死，先幫我倒杯水比輸贏重要。",
        archetype: "deflect",
        retort: "好！我去倒水給你！",
      },
      {
        id: "xiao-biaodi-red_envelope-030-d",
        text: "幹……可能真的比較薄，最近比較忙……",
        archetype: "meek",
        retort: "比較薄喔，那你要加油了。",
      },
      {
        id: "xiao-biaodi-red_envelope-030-e",
        text: "靠……應該差不多，我沒特別比較……",
        archetype: "meek",
        retort: "沒比較？那怎麼知道輸贏？",
      },
      {
        id: "xiao-biaodi-red_envelope-030-f",
        text: "他媽的，紅包比賽是低級趣味啦。",
        archetype: "backfire",
        retort: "……（小表弟已經在比較兩包的厚度）",
      },
      {
        id: "xiao-biaodi-red_envelope-030-g",
        text: "機掰，厚度是幻覺，真贏家看氣勢。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續比較）",
      },
      {
        id: "xiao-biaodi-red_envelope-030-h",
        text: "去死，輸就輸，愛比較的是你月考排名。",
        archetype: "landmine",
        retort: "嗚嗚——他大哭抱阿嬤喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-031",
    text: "老師說摸起來軟軟的，裡面一定都是小鈔對不對？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-031-a",
        text: "去死，軟軟的，老師薪水單也很軟嗎。",
        archetype: "perfect",
        retort: "……他臉一黑，清了清喉嚨",
      },
      {
        id: "xiao-biaodi-red_envelope-031-b",
        text: "靠，你摸摸看自己的，軟的硬的？",
        archetype: "deflect",
        retort: "我的是……軟軟的耶！",
      },
      {
        id: "xiao-biaodi-red_envelope-031-c",
        text: "笑死，先幫忙擦桌子比軟硬重要。",
        archetype: "deflect",
        retort: "好，我去擦桌子！",
      },
      {
        id: "xiao-biaodi-red_envelope-031-d",
        text: "幹……可能真的是小鈔疊起來的啦……",
        archetype: "meek",
        retort: "小鈔喔，那也太多張了吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-031-e",
        text: "靠……摸起來軟軟的，我也不確定……",
        archetype: "meek",
        retort: "不確定？那你敢打開看嗎？",
      },
      {
        id: "xiao-biaodi-red_envelope-031-f",
        text: "他媽的，軟的是高級絲絨包裝啦。",
        archetype: "backfire",
        retort: "……（小表弟繼續捏他的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-031-g",
        text: "機掰，軟硬觸感學是我自創學問。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續捏來捏去）",
      },
      {
        id: "xiao-biaodi-red_envelope-031-h",
        text: "去你的，一直捏沒禮貌，考試也不懂規矩。",
        archetype: "landmine",
        retort: "嗚嗚——他哭著找媽媽喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-032",
    text: "姑丈說紅包要當場拆才夠爽快，你敢嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-032-a",
        text: "幹，爽快而已，姑丈欠的錢也當場還？",
        archetype: "perfect",
        retort: "……姑丈轉頭裝忙罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-032-b",
        text: "靠，姑丈你先示範一次怎麼拆？",
        archetype: "deflect",
        retort: "看我的，唰一下就拆好！",
      },
      {
        id: "xiao-biaodi-red_envelope-032-c",
        text: "笑死，趁熱吃比當場拆重要吧。",
        archetype: "deflect",
        retort: "趁熱吃比較重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-032-d",
        text: "我想帶回家再拆，幹……比較有隱私……",
        archetype: "meek",
        retort: "隱私？拆個紅包哪來隱私。",
      },
      {
        id: "xiao-biaodi-red_envelope-032-e",
        text: "靠……當場拆有點害羞，回家拆好了……",
        archetype: "meek",
        retort: "害羞什麼，拆個紅包而已。",
      },
      {
        id: "xiao-biaodi-red_envelope-032-f",
        text: "他媽的，延遲拆封是期待值管理啦。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，直接當場拆了）",
      },
      {
        id: "xiao-biaodi-red_envelope-032-g",
        text: "機掰，不拆才是最大的尊重，懂儀式感？",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，自己拆得很開心）",
      },
      {
        id: "xiao-biaodi-red_envelope-032-h",
        text: "去你的，當場拆俗氣，愛看熱鬧不寫作業。",
        archetype: "landmine",
        retort: "姑丈護著他，碎念瞪你",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-033",
    text: "媽媽說你長大了，以後紅包會越包越少喔。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-033-a",
        text: "去死，越少越好，媽媽零用錢也該少了。",
        archetype: "perfect",
        retort: "……媽媽假裝滑手機罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-033-b",
        text: "靠，你長大以後紅包換你包給我？",
        archetype: "deflect",
        retort: "會啊！我以後包給你！",
      },
      {
        id: "xiao-biaodi-red_envelope-033-c",
        text: "笑死，你有沒有吃飽比紅包重要。",
        archetype: "deflect",
        retort: "吃飽了！超級飽的！",
      },
      {
        id: "xiao-biaodi-red_envelope-033-d",
        text: "對啊，幹……感覺以後會慢慢變少了……",
        archetype: "meek",
        retort: "變少喔，那你會不會捨不得？",
      },
      {
        id: "xiao-biaodi-red_envelope-033-e",
        text: "靠……有點失落，但也是沒辦法的事……",
        archetype: "meek",
        retort: "失落喔，那要不要再抱一下？",
      },
      {
        id: "xiao-biaodi-red_envelope-033-f",
        text: "他媽的，紅包變少證明財富自由升級。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-033-g",
        text: "機掰，長大就要把紅包讓給更小的孩子。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，一臉茫然）",
      },
      {
        id: "xiao-biaodi-red_envelope-033-h",
        text: "去你的，紅包多少，成績別再退步比較實在。",
        archetype: "landmine",
        retort: "媽媽狠狠瞪你，罵你三小",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-034",
    text: "老師說我可以幫阿嬤代領紅包給你，好不好？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-034-a",
        text: "幹，代領而已，老師先幫我代寫作業。",
        archetype: "perfect",
        retort: "……阿嬤笑了，招手要橘子",
      },
      {
        id: "xiao-biaodi-red_envelope-034-b",
        text: "靠，你想不想學怎麼包紅包給阿嬤？",
        archetype: "deflect",
        retort: "想！我要學怎麼包！",
      },
      {
        id: "xiao-biaodi-red_envelope-034-c",
        text: "笑死，先問阿嬤累不累比代領重要。",
        archetype: "deflect",
        retort: "對耶！我去問阿嬤！",
      },
      {
        id: "xiao-biaodi-red_envelope-034-d",
        text: "好啊，幹……那你要記得全部拿給我……",
        archetype: "meek",
        retort: "全部拿給你？那我怎麼知道你有沒有算對。",
      },
      {
        id: "xiao-biaodi-red_envelope-034-e",
        text: "靠……可以是可以，但我會忍不住偷看……",
        archetype: "meek",
        retort: "偷看？那還算代領嗎？",
      },
      {
        id: "xiao-biaodi-red_envelope-034-f",
        text: "他媽的，代領是信任的最高表現啦。",
        archetype: "backfire",
        retort: "……（小表弟已經跑去找阿嬤了）",
      },
      {
        id: "xiao-biaodi-red_envelope-034-g",
        text: "機掰，我當代理人要收手續費，合理的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盧著要當代理人）",
      },
      {
        id: "xiao-biaodi-red_envelope-034-h",
        text: "去你的，代領什麼代領，先代寫完作業。",
        archetype: "landmine",
        retort: "阿嬤心疼瞪你，碎念一句",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-035",
    text: "姑丈說有些紅包會藏刮刮樂，你的有藏嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-035-a",
        text: "靠北，刮刮樂，姑丈簽注中了沒。",
        archetype: "perfect",
        retort: "……姑丈臉一黑喝了口酒",
      },
      {
        id: "xiao-biaodi-red_envelope-035-b",
        text: "靠，姑丈你今年刮中什麼，分享？",
        archetype: "deflect",
        retort: "我刮中兩百塊，運氣不錯！",
      },
      {
        id: "xiao-biaodi-red_envelope-035-c",
        text: "笑死，紅包厚度比刮刮樂重要吧。",
        archetype: "deflect",
        retort: "厚度比較重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-035-d",
        text: "沒有耶，幹……我沒放那個進去……",
        archetype: "meek",
        retort: "沒放喔，那沒有驚喜了。",
      },
      {
        id: "xiao-biaodi-red_envelope-035-e",
        text: "靠……本來想放，後來忘記買了……",
        archetype: "meek",
        retort: "忘記買？那你太隨便了吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-035-f",
        text: "他媽的，我的紅包本身就是刮刮樂。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續翻紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-035-g",
        text: "機掰，運氣是可以計算的，我有公式。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，一臉茫然）",
      },
      {
        id: "xiao-biaodi-red_envelope-035-h",
        text: "去死，刮刮樂幼稚，刮開你考卷看幾分。",
        archetype: "landmine",
        retort: "嗚——他哭著找姑丈告狀喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-036",
    text: "阿嬤說今年連家裡的狗都要包紅包，你包了嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-036-a",
        text: "幹，狗都包了，阿嬤偏心名單排第幾。",
        archetype: "perfect",
        retort: "……阿嬤笑了，摸摸口袋",
      },
      {
        id: "xiao-biaodi-red_envelope-036-b",
        text: "靠，你猜狗狗最想要什麼樣的紅包？",
        archetype: "deflect",
        retort: "牠應該想要骨頭形狀的！",
      },
      {
        id: "xiao-biaodi-red_envelope-036-c",
        text: "笑死，帶牠去散步比包紅包重要吧。",
        archetype: "deflect",
        retort: "對耶！我先帶牠去玩！",
      },
      {
        id: "xiao-biaodi-red_envelope-036-d",
        text: "我沒想到要包給牠，幹……不好意思……",
        archetype: "meek",
        retort: "沒包喔！阿嬤——他沒包給狗狗——",
      },
      {
        id: "xiao-biaodi-red_envelope-036-e",
        text: "靠……本來想包，但不知道狗會不會拆……",
        archetype: "meek",
        retort: "不會拆？那你也太多慮了。",
      },
      {
        id: "xiao-biaodi-red_envelope-036-f",
        text: "他媽的，狗狗的紅包是精神股份啦。",
        archetype: "backfire",
        retort: "……（狗狗在旁邊搖尾巴聽不懂）",
      },
      {
        id: "xiao-biaodi-red_envelope-036-g",
        text: "機掰，毛小孩財富要用飼料計價。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續逗狗）",
      },
      {
        id: "xiao-biaodi-red_envelope-036-h",
        text: "去你的，狗而已包什麼，你連狗都比不上乖。",
        archetype: "landmine",
        retort: "嗚——阿嬤你看他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-037",
    text: "老師說覺得紅包太少可以直接講出來，對不對？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-037-a",
        text: "去死，太少直接講，老師加薪直接講了嗎。",
        archetype: "perfect",
        retort: "……他臉一黑，裝滑手機",
      },
      {
        id: "xiao-biaodi-red_envelope-037-b",
        text: "靠，你覺得多少才算多，說來聽聽？",
        archetype: "deflect",
        retort: "我覺得要比表姊包的多！",
      },
      {
        id: "xiao-biaodi-red_envelope-037-c",
        text: "笑死，先幫忙擺碗筷比嫌少重要。",
        archetype: "deflect",
        retort: "好，我去擺碗筷！",
      },
      {
        id: "xiao-biaodi-red_envelope-037-d",
        text: "老實說，幹……是有點少啦，不好意思講……",
        archetype: "meek",
        retort: "有點少喔！媽媽——他嫌少——",
      },
      {
        id: "xiao-biaodi-red_envelope-037-e",
        text: "靠……我沒有很在意，有拿到就好……",
        archetype: "meek",
        retort: "有拿到就好？那你都不會生氣？",
      },
      {
        id: "xiao-biaodi-red_envelope-037-f",
        text: "他媽的，嫌少俗氣，我走感恩路線。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-037-g",
        text: "機掰，金額多寡是幻覺，重點是顏值。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-037-h",
        text: "去你的，嫌紅包少沒禮貌，你考卷嫌少過嗎。",
        archetype: "landmine",
        retort: "他媽媽立刻衝過來拉開你們",
      },
    ],
  },
] satisfies Question[];
