import type { Question } from "@/content/types";

// situations:
// - 捏紅包猜厚度
// - 問紅包是新鈔還舊鈔
// - 問紅包裡有沒有夾遊戲點數卡
// - 當場拆紅包數金額
// - 紅包會不會被媽媽充公保管
// - 行動支付轉帳代替紙本紅包
// - 問紅包金額尾數吉不吉利
// - 今年紅包有沒有比去年多
// - 紅包要不要平分給弟弟妹妹
// - 問可不可以先預支明年紅包
// - 問紅包袋有沒有寫吉祥話才有心意
// - 問紅包裡是硬幣還是鈔票
// - 問紅包有沒有先被收走繳學費
// - 問能不能吃飯前先領紅包
// - 問阿嬤紅包是不是變少因為退休
// - 排隊領紅包被插隊
// - 問紅包裡的鈔票是不是最大張
// - 紅包金額換算遊戲點數卡
// - 紅包要不要拿去投資理財
// - 問今年薪水漲了紅包會不會跟著漲

export default [
  {
    id: "xiao-biaodi-red_envelope-002",
    text: "讓我捏一下，媽媽說厚的才是誠意十足。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-002-a",
        text: "誠意在心裡，不在你的手指頭上，鬆手。",
        archetype: "perfect",
        retort: "哈哈哈好啦好啦，我鬆手！",
      },
      {
        id: "xiao-biaodi-red_envelope-002-b",
        text: "先讓我看看你手指頭乾不乾淨。",
        archetype: "deflect",
        retort: "很乾淨啦！我剛洗手！",
      },
      {
        id: "xiao-biaodi-red_envelope-002-c",
        text: "你猜猜看厚度，猜對了才給你看。",
        archetype: "deflect",
        retort: "我猜……很厚！對不對！",
      },
      {
        id: "xiao-biaodi-red_envelope-002-d",
        text: "呃……其實沒有很厚啦……",
        archetype: "meek",
        retort: "沒有很厚喔！媽媽——他包很薄——",
      },
      {
        id: "xiao-biaodi-red_envelope-002-e",
        text: "普通厚度而已，不算多……",
        archetype: "meek",
        retort: "不算多？那到底多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-002-f",
        text: "厚度是假的，我的心意是立體的。",
        archetype: "backfire",
        retort: "……（小表弟已經伸手要摸）",
      },
      {
        id: "xiao-biaodi-red_envelope-002-g",
        text: "薄的紅包才是輕功高手的裝備。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續捏）",
      },
      {
        id: "xiao-biaodi-red_envelope-002-h",
        text: "小孩子手不要亂摸，很沒禮貌。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-003",
    text: "老師說新鈔才吉利，你的是新的還舊的？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-003-a",
        text: "是新的，新到你數的時候會割到手，小心。",
        archetype: "perfect",
        retort: "哇！這麼新喔！小心翼翼拆開。",
      },
      {
        id: "xiao-biaodi-red_envelope-003-b",
        text: "你猜猜看，猜對了我就給你看一眼。",
        archetype: "deflect",
        retort: "我猜是新的！一定是新的！",
      },
      {
        id: "xiao-biaodi-red_envelope-003-c",
        text: "新鈔跟舊鈔用起來還不是一樣能買糖果。",
        archetype: "deflect",
        retort: "對耶，糖果最重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-003-d",
        text: "應該是舊鈔啦，銀行換新鈔要排隊……",
        archetype: "meek",
        retort: "舊鈔喔！媽媽——他包舊鈔——",
      },
      {
        id: "xiao-biaodi-red_envelope-003-e",
        text: "不確定耶，沒特別去換……",
        archetype: "meek",
        retort: "沒去換？那誠意不夠喔。",
      },
      {
        id: "xiao-biaodi-red_envelope-003-f",
        text: "鈔票新舊是假議題，重點是磁場。",
        archetype: "backfire",
        retort: "……（小表弟已經想伸手拆開）",
      },
      {
        id: "xiao-biaodi-red_envelope-003-g",
        text: "舊鈔比較有歷史感，懂收藏嗎。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著看）",
      },
      {
        id: "xiao-biaodi-red_envelope-003-h",
        text: "問這麼細幹嘛，很煩耶小孩子。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-004",
    text: "姑姑說紅包裡有時候會夾點數卡，你的有嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-004-a",
        text: "有啊，夾的是讓你自己去努力的點數。",
        archetype: "perfect",
        retort: "哈哈哈這是什麼點數啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-004-b",
        text: "你想要哪一種點數卡，我幫你許願？",
        archetype: "deflect",
        retort: "我要遊戲點數卡！拜託拜託！",
      },
      {
        id: "xiao-biaodi-red_envelope-004-c",
        text: "你先跟我說你最想玩哪個遊戲。",
        archetype: "deflect",
        retort: "我要玩最新那款賽車遊戲！",
      },
      {
        id: "xiao-biaodi-red_envelope-004-d",
        text: "沒有耶，就只有現金而已……",
        archetype: "meek",
        retort: "只有現金喔，好無聊。",
      },
      {
        id: "xiao-biaodi-red_envelope-004-e",
        text: "可能沒想到要夾點數卡啦……",
        archetype: "meek",
        retort: "沒想到？那我要提醒你。",
      },
      {
        id: "xiao-biaodi-red_envelope-004-f",
        text: "現金才是萬用點數卡，懂經濟學嗎。",
        archetype: "backfire",
        retort: "……（小表弟已經在翻紅包找卡片）",
      },
      {
        id: "xiao-biaodi-red_envelope-004-g",
        text: "紙本點數卡已經過時了，我走數位路線。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續翻找）",
      },
      {
        id: "xiao-biaodi-red_envelope-004-h",
        text: "你很貪心耶，紅包還敢要求夾東西。",
        archetype: "landmine",
        retort: "嗚……姑姑——他說我貪心——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-005",
    text: "阿嬤說當場拆開數清楚，才知道有沒有誠意。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-005-a",
        text: "誠意不用數，是用感受的，你感受一下。",
        archetype: "perfect",
        retort: "哈哈哈感受到了，很多的感覺！",
      },
      {
        id: "xiao-biaodi-red_envelope-005-b",
        text: "阿嬤你先拆你的，我們互相觀摩。",
        archetype: "deflect",
        retort: "哎唷，阿嬤才不拆呢！",
      },
      {
        id: "xiao-biaodi-red_envelope-005-c",
        text: "先讓我看看你數學厲不厲害，算算看。",
        archetype: "deflect",
        retort: "我最會算數學了！等我！",
      },
      {
        id: "xiao-biaodi-red_envelope-005-d",
        text: "我還沒拆耶，怕拆開紅包袋會破掉……",
        archetype: "meek",
        retort: "怕破掉？那到底多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-005-e",
        text: "數字不重要啦，我等一下再拆……",
        archetype: "meek",
        retort: "不重要？那你幹嘛不敢拆？",
      },
      {
        id: "xiao-biaodi-red_envelope-005-f",
        text: "數字是虛的，紅包的溫度才是真的。",
        archetype: "backfire",
        retort: "……（小表弟已經伸手要拆）",
      },
      {
        id: "xiao-biaodi-red_envelope-005-g",
        text: "不拆才是對長輩最高的信任表現。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-005-h",
        text: "小孩子不要一直盯著紅包看，沒禮貌。",
        archetype: "landmine",
        retort: "嗚……阿嬤——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-006",
    text: "媽媽說紅包等一下要充公，你的也是嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-006-a",
        text: "充公也好，這樣我就不用自己記帳了。",
        archetype: "perfect",
        retort: "哈哈哈這樣想也太阿Q了！",
      },
      {
        id: "xiao-biaodi-red_envelope-006-b",
        text: "你要不要也把糖果充公，我幫你保管？",
        archetype: "deflect",
        retort: "才不要，糖果是我的！",
      },
      {
        id: "xiao-biaodi-red_envelope-006-c",
        text: "你媽媽保管的錢，都拿去做什麼？",
        archetype: "deflect",
        retort: "我也不知道，都不見了。",
      },
      {
        id: "xiao-biaodi-red_envelope-006-d",
        text: "對啊，我的也是被收走保管……",
        archetype: "meek",
        retort: "收走喔，那你自己一毛都沒有？",
      },
      {
        id: "xiao-biaodi-red_envelope-006-e",
        text: "應該也會被收走一部分啦……",
        archetype: "meek",
        retort: "一部分？那剩下多少？",
      },
      {
        id: "xiao-biaodi-red_envelope-006-f",
        text: "我的紅包已經升級成投資組合了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數自己的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-006-g",
        text: "被保管才是財富自由的第一步。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽）",
      },
      {
        id: "xiao-biaodi-red_envelope-006-h",
        text: "你管我紅包被誰收走幹嘛，很煩。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-007",
    text: "老師說現在都用手機轉帳了，你還包紙本喔？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-007-a",
        text: "紙本才有溫度，手機轉帳你摸不到年味。",
        archetype: "perfect",
        retort: "哇！年味這句好有感覺！",
      },
      {
        id: "xiao-biaodi-red_envelope-007-b",
        text: "你有沒有自己的收款帳號，教教我怎麼弄？",
        archetype: "deflect",
        retort: "我還沒有帳號啦，要問媽媽！",
      },
      {
        id: "xiao-biaodi-red_envelope-007-c",
        text: "手機轉帳快，但你的紅包袋是不是很無聊？",
        archetype: "deflect",
        retort: "才不會，我選的圖案超酷！",
      },
      {
        id: "xiao-biaodi-red_envelope-007-d",
        text: "我還沒學會怎麼轉帳，就用紙本了……",
        archetype: "meek",
        retort: "不會轉帳喔，落伍了吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-007-e",
        text: "轉帳感覺比較沒有拆的樂趣啦……",
        archetype: "meek",
        retort: "沒樂趣？那你怎麼不學？",
      },
      {
        id: "xiao-biaodi-red_envelope-007-f",
        text: "我走的是復古紙本收藏派，很潮。",
        archetype: "backfire",
        retort: "……（小表弟已經去研究媽媽的手機）",
      },
      {
        id: "xiao-biaodi-red_envelope-007-g",
        text: "電子支付是給不懂儀式感的人用的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究手機）",
      },
      {
        id: "xiao-biaodi-red_envelope-007-h",
        text: "轉帳關你什麼事，紙本比較好啦。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-008",
    text: "阿嬤說尾數是四不吉利，你有沒有算過？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-008-a",
        text: "我的紅包尾數是八，八到讓你數不完。",
        archetype: "perfect",
        retort: "哈哈哈八到數不完，這孩子真會講！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-b",
        text: "阿嬤你包的尾數是幾號，我猜猜看。",
        archetype: "deflect",
        retort: "哎唷，你猜猜看嘛！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-c",
        text: "數字重要，還是你今天有沒有吃飽比較重要？",
        archetype: "deflect",
        retort: "吃飽了！年菜好好吃！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-d",
        text: "我還沒算耶，等一下算給你聽……",
        archetype: "meek",
        retort: "還沒算喔，那快去算！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-e",
        text: "可能剛好卡到不吉利的數字吧……",
        archetype: "meek",
        retort: "卡到喔！阿嬤——他包到四——",
      },
      {
        id: "xiao-biaodi-red_envelope-008-f",
        text: "數字迷信是舊時代產物，我不信這個。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊念念有詞）",
      },
      {
        id: "xiao-biaodi-red_envelope-008-g",
        text: "我信的是我自己的幸運數字，不是傳統。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續算自己的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-008-h",
        text: "迷信而已你很無聊耶，不要一直算。",
        archetype: "landmine",
        retort: "嗚……阿嬤——他說迷信無聊——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-009",
    text: "姑姑說物價都漲了，你今年紅包有跟著漲嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-009-a",
        text: "有啊，漲的幅度跟你長高的速度一樣快。",
        archetype: "perfect",
        retort: "哈哈哈這個比喻也太妙了！",
      },
      {
        id: "xiao-biaodi-red_envelope-009-b",
        text: "那姑姑你今年薪水有沒有跟著物價漲？",
        archetype: "deflect",
        retort: "這個……我們再說。",
      },
      {
        id: "xiao-biaodi-red_envelope-009-c",
        text: "你覺得漲多少才算有誠意？我參考一下。",
        archetype: "deflect",
        retort: "我覺得要漲一倍才夠！",
      },
      {
        id: "xiao-biaodi-red_envelope-009-d",
        text: "應該差不多，沒有特別漲……",
        archetype: "meek",
        retort: "沒漲喔，那物價都白漲了。",
      },
      {
        id: "xiao-biaodi-red_envelope-009-e",
        text: "可能還小幅縮水了一點點……",
        archetype: "meek",
        retort: "縮水！姑姑——他今年變少——",
      },
      {
        id: "xiao-biaodi-red_envelope-009-f",
        text: "紅包金額要跟通膨脫鉤，這是我的原則。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-009-g",
        text: "我包的是穩定幣，不受物價影響。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽什麼是穩定幣）",
      },
      {
        id: "xiao-biaodi-red_envelope-009-h",
        text: "物價漲關你什麼事，紅包是我包的。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-010",
    text: "媽媽說紅包要平分給弟弟，你的也要分嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-010-a",
        text: "分著花才有過年的感覺，我來分給大家。",
        archetype: "perfect",
        retort: "哇！這樣講超暖的！",
      },
      {
        id: "xiao-biaodi-red_envelope-010-b",
        text: "那你要不要也分一點糖果給大家？",
        archetype: "deflect",
        retort: "好啊！我分糖果給大家！",
      },
      {
        id: "xiao-biaodi-red_envelope-010-c",
        text: "你弟弟今年有沒有比較乖，值得多分一點？",
        archetype: "deflect",
        retort: "他還好啦，普普通通。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-d",
        text: "應該不用分吧，我這份是我自己的……",
        archetype: "meek",
        retort: "不分喔，那弟弟會難過耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-e",
        text: "可能要分一點點給他意思一下……",
        archetype: "meek",
        retort: "一點點？那不夠意思吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-f",
        text: "分享是弱者的行為，我走囤積路線。",
        archetype: "backfire",
        retort: "……（媽媽已經在旁邊皺眉）",
      },
      {
        id: "xiao-biaodi-red_envelope-010-g",
        text: "我的錢是要拿去投資未來，不能分。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續數自己的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-010-h",
        text: "分紅包關你屁事，你的紅包才要分。",
        archetype: "landmine",
        retort: "嗚……媽媽——他罵我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-011",
    text: "老師說借錢要還，你可以先借我明年的紅包嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-011-a",
        text: "明年的紅包要明年才有，這叫延遲享樂。",
        archetype: "perfect",
        retort: "哇！延遲享樂！我學到了！",
      },
      {
        id: "xiao-biaodi-red_envelope-011-b",
        text: "你要借多少，先說說看你的計畫？",
        archetype: "deflect",
        retort: "我要買新的遊戲片！",
      },
      {
        id: "xiao-biaodi-red_envelope-011-c",
        text: "借錢是要付利息的，你付得起嗎？",
        archetype: "deflect",
        retort: "利息是什麼？聽起來很可怕。",
      },
      {
        id: "xiao-biaodi-red_envelope-011-d",
        text: "我自己都不夠用了，沒辦法借你……",
        archetype: "meek",
        retort: "不夠用喔，那你也很窮耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-011-e",
        text: "可以借一點點啦，但要記得還……",
        archetype: "meek",
        retort: "好！我記下來了，你借我的！",
      },
      {
        id: "xiao-biaodi-red_envelope-011-f",
        text: "我的紅包已經全部投入期貨市場了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續盧著要借）",
      },
      {
        id: "xiao-biaodi-red_envelope-011-g",
        text: "借貸關係會破壞感情，我拒絕。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續纏著問）",
      },
      {
        id: "xiao-biaodi-red_envelope-011-h",
        text: "小孩子不要一直討錢，很沒禮貌。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-012",
    text: "阿嬤說紅包袋上要寫吉祥話才有心意，你有寫嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-012-a",
        text: "我寫的吉祥話是：祝你長高比我快。",
        archetype: "perfect",
        retort: "哈哈哈這句話也太可愛了！",
      },
      {
        id: "xiao-biaodi-red_envelope-012-b",
        text: "你紅包袋上寫了什麼，唸給我聽？",
        archetype: "deflect",
        retort: "我寫的是恭喜發財！",
      },
      {
        id: "xiao-biaodi-red_envelope-012-c",
        text: "你猜猜看我寫了什麼字，猜對算你贏。",
        archetype: "deflect",
        retort: "我猜……新年快樂！",
      },
      {
        id: "xiao-biaodi-red_envelope-012-d",
        text: "我沒有寫耶，紅包袋是買現成的……",
        archetype: "meek",
        retort: "沒寫喔，那沒誠意耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-012-e",
        text: "有寫一點點，但字有點醜……",
        archetype: "meek",
        retort: "字醜？阿嬤——他寫得很醜——",
      },
      {
        id: "xiao-biaodi-red_envelope-012-f",
        text: "吉祥話寫在心裡，不用寫在紙上。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊搖搖頭）",
      },
      {
        id: "xiao-biaodi-red_envelope-012-g",
        text: "空白的紅包袋才是最高境界的祝福。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-012-h",
        text: "寫什麼吉祥話，很無聊耶不要問了。",
        archetype: "landmine",
        retort: "嗚……阿嬤——他說我無聊——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-013",
    text: "姑丈說裡面是硬幣才好玩，你的是硬幣嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-013-a",
        text: "是硬幣，晃起來的聲音比鈔票熱鬧多了。",
        archetype: "perfect",
        retort: "哈哈哈熱鬧！這句話真會講！",
      },
      {
        id: "xiao-biaodi-red_envelope-013-b",
        text: "你搖搖看你的，聽聲音猜猜看幾個硬幣。",
        archetype: "deflect",
        retort: "我搖搖看！叮叮噹噹的！",
      },
      {
        id: "xiao-biaodi-red_envelope-013-c",
        text: "硬幣比較重，你拿得動嗎？",
        archetype: "deflect",
        retort: "拿得動！我力氣很大的！",
      },
      {
        id: "xiao-biaodi-red_envelope-013-d",
        text: "是鈔票啦，摸起來平平的……",
        archetype: "meek",
        retort: "鈔票喔，那沒有硬幣好玩。",
      },
      {
        id: "xiao-biaodi-red_envelope-013-e",
        text: "應該是鈔票，感覺不出來是硬幣……",
        archetype: "meek",
        retort: "感覺不出來？那你摸過嗎？",
      },
      {
        id: "xiao-biaodi-red_envelope-013-f",
        text: "鈔票是進階版硬幣，懂經濟演化嗎。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續搖他的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-013-g",
        text: "我收的是紀念幣等級的硬幣，很珍貴。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續搖晃）",
      },
      {
        id: "xiao-biaodi-red_envelope-013-h",
        text: "搖來搖去很吵耶，可以不要搖嗎。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-014",
    text: "媽媽說你的紅包是不是都拿去繳帳單了？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-014-a",
        text: "繳帳單也是一種過年儀式，叫做成年禮。",
        archetype: "perfect",
        retort: "哈哈哈成年禮這個講法太狂了！",
      },
      {
        id: "xiao-biaodi-red_envelope-014-b",
        text: "你的紅包會不會也被拿去繳補習費？",
        archetype: "deflect",
        retort: "會啊！我媽都拿去繳補習費！",
      },
      {
        id: "xiao-biaodi-red_envelope-014-c",
        text: "帳單重要，還是你要不要先吃塊糖？",
        archetype: "deflect",
        retort: "先吃糖！糖比較重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-014-d",
        text: "對啊……大部分都拿去繳帳單了……",
        archetype: "meek",
        retort: "繳帳單喔，那都沒剩下了。",
      },
      {
        id: "xiao-biaodi-red_envelope-014-e",
        text: "留一點自己花，其他都拿去繳費了……",
        archetype: "meek",
        retort: "留一點？那剩多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-014-f",
        text: "帳單是我人生的另一種紅包，換個角度看。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續玩自己的）",
      },
      {
        id: "xiao-biaodi-red_envelope-014-g",
        text: "繳帳單是大人的隱藏版遊戲關卡。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽帳單是什麼）",
      },
      {
        id: "xiao-biaodi-red_envelope-014-h",
        text: "帳單關你什麼事，小孩子問這麼多幹嘛。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-015",
    text: "老師說先領紅包才有動力吃飯，可以先給我嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-015-a",
        text: "動力要靠自己找，紅包等吃完飯才有加成。",
        archetype: "perfect",
        retort: "哈哈哈加成這個詞用得好！",
      },
      {
        id: "xiao-biaodi-red_envelope-015-b",
        text: "你先吃三口菜，我就先給你一個提示。",
        archetype: "deflect",
        retort: "好！我吃三口！給我提示！",
      },
      {
        id: "xiao-biaodi-red_envelope-015-c",
        text: "你猜猜看飯後紅包跟飯前紅包哪個比較大包？",
        archetype: "deflect",
        retort: "飯後的比較大包吧！",
      },
      {
        id: "xiao-biaodi-red_envelope-015-d",
        text: "可以先給一點點嗎，我肚子不餓……",
        archetype: "meek",
        retort: "不餓喔，那更要先吃飯了。",
      },
      {
        id: "xiao-biaodi-red_envelope-015-e",
        text: "我等一下再吃啦，先看一下紅包……",
        archetype: "meek",
        retort: "先看紅包？那飯菜怎麼辦？",
      },
      {
        id: "xiao-biaodi-red_envelope-015-f",
        text: "紅包的能量本來就要吃飯後才會啟動。",
        archetype: "backfire",
        retort: "……（小表弟已經跑去夾菜了）",
      },
      {
        id: "xiao-biaodi-red_envelope-015-g",
        text: "飢餓感才是最好的開胃菜，等等就對了。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續等紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-015-h",
        text: "吵著要紅包很沒禮貌，去旁邊等。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-016",
    text: "姑姑說阿嬤退休沒收入，紅包會不會變少？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-016-a",
        text: "阿嬤的紅包從來不是用錢算的，是用愛算的。",
        archetype: "perfect",
        retort: "哎唷～這孩子講到阿嬤心坎裡了！",
      },
      {
        id: "xiao-biaodi-red_envelope-016-b",
        text: "阿嬤退休後最愛做什麼，你知道嗎？",
        archetype: "deflect",
        retort: "阿嬤最愛種菜跟看歌仔戲！",
      },
      {
        id: "xiao-biaodi-red_envelope-016-c",
        text: "退休生活比較重要，還是紅包金額重要？",
        archetype: "deflect",
        retort: "退休生活重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-016-d",
        text: "可能真的會變少一點點……",
        archetype: "meek",
        retort: "變少喔！阿嬤——他這樣說——",
      },
      {
        id: "xiao-biaodi-red_envelope-016-e",
        text: "應該還好啦，阿嬤有存退休金……",
        archetype: "meek",
        retort: "有存喔，那應該不會太少。",
      },
      {
        id: "xiao-biaodi-red_envelope-016-f",
        text: "阿嬤的紅包是精神股份，不會貶值。",
        archetype: "backfire",
        retort: "……（阿嬤聽不懂，繼續織毛衣）",
      },
      {
        id: "xiao-biaodi-red_envelope-016-g",
        text: "退休金融資產配置這種事，你不懂。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問阿嬤什麼是配置）",
      },
      {
        id: "xiao-biaodi-red_envelope-016-h",
        text: "退休就退休，紅包當然會變少啊。",
        archetype: "landmine",
        retort: "嗚……阿嬤——他說你變少了——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-017",
    text: "阿嬤說要照順序領紅包，你插我隊做什麼？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-017-a",
        text: "我幫你排隊，這樣你就不用等，感謝我吧。",
        archetype: "perfect",
        retort: "哈哈哈這樣講也可以喔，謝謝你！",
      },
      {
        id: "xiao-biaodi-red_envelope-017-b",
        text: "你先跟阿嬤說一句拜年吉祥話，換你先領。",
        archetype: "deflect",
        retort: "阿嬤新年快樂！我先領！",
      },
      {
        id: "xiao-biaodi-red_envelope-017-c",
        text: "我們來剪刀石頭布，贏的人先領。",
        archetype: "deflect",
        retort: "好啊！剪刀石頭布！",
      },
      {
        id: "xiao-biaodi-red_envelope-017-d",
        text: "對不起，我太想先看紅包了……",
        archetype: "meek",
        retort: "太想看喔，那大家都想看啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-017-e",
        text: "我只是想快一點，沒有惡意啦……",
        archetype: "meek",
        retort: "沒惡意？那也要排隊啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-017-f",
        text: "先到先得是叢林法則，我懂生存之道。",
        archetype: "backfire",
        retort: "……（阿嬤已經叫下一個人）",
      },
      {
        id: "xiao-biaodi-red_envelope-017-g",
        text: "插隊是一種積極主動的人生態度。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續排在原地）",
      },
      {
        id: "xiao-biaodi-red_envelope-017-h",
        text: "插我的隊很沒禮貌耶，你懂不懂規矩。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-018",
    text: "老師說裡面是千元大鈔才叫誠意，你的是嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-018-a",
        text: "誠意的重點是張數少但份量重，你自己感受。",
        archetype: "perfect",
        retort: "哈哈哈份量重這句真的很會講！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-b",
        text: "你怎麼分辨鈔票大小張，教教我？",
        archetype: "deflect",
        retort: "看數字就知道了啊！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-c",
        text: "大鈔跟小鈔加起來，其實都一樣能吃糖果。",
        archetype: "deflect",
        retort: "對耶，糖果最重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-d",
        text: "應該是比較小張的那種啦……",
        archetype: "meek",
        retort: "小張的喔！誠意不夠——",
      },
      {
        id: "xiao-biaodi-red_envelope-018-e",
        text: "不太確定耶，還沒仔細看清楚……",
        archetype: "meek",
        retort: "沒看清楚？那快去看！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-f",
        text: "鈔票大小是外在的，內在價值才重要。",
        archetype: "backfire",
        retort: "……（小表弟已經想伸手翻看）",
      },
      {
        id: "xiao-biaodi-red_envelope-018-g",
        text: "小張鈔票才是低調有實力的象徵。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-018-h",
        text: "問這麼細很沒禮貌，去旁邊玩啦。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-019",
    text: "媽媽說你紅包夠買幾張遊戲點數卡，算給我聽。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-019-a",
        text: "算給你聽不如直接買一張給你，我請客。",
        archetype: "perfect",
        retort: "哇！真的假的！謝謝哥／姊！",
      },
      {
        id: "xiao-biaodi-red_envelope-019-b",
        text: "你想玩的遊戲要多少點數，先說說看？",
        archetype: "deflect",
        retort: "我想玩的要五百點！",
      },
      {
        id: "xiao-biaodi-red_envelope-019-c",
        text: "點數卡重要，還是你數學作業寫完重要？",
        archetype: "deflect",
        retort: "……作業還沒寫啦。",
      },
      {
        id: "xiao-biaodi-red_envelope-019-d",
        text: "算一算好像只夠買一張而已……",
        archetype: "meek",
        retort: "只夠一張喔，那也太少了。",
      },
      {
        id: "xiao-biaodi-red_envelope-019-e",
        text: "換算完發現沒剩多少可以買了……",
        archetype: "meek",
        retort: "沒剩多少？紅包都花去哪了？",
      },
      {
        id: "xiao-biaodi-red_envelope-019-f",
        text: "點數卡是虛擬資產，我在等它升值。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續算他的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-019-g",
        text: "我把紅包換算成人生經驗值，不是點數。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽）",
      },
      {
        id: "xiao-biaodi-red_envelope-019-h",
        text: "算這個很煩耶，你自己算不會喔。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-020",
    text: "姑丈說紅包要拿去投資才會變多，你懂投資嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-020-a",
        text: "我投資的是你，這樣明年紅包才會變多包給我。",
        archetype: "perfect",
        retort: "哈哈哈這個投資邏輯太狂了！",
      },
      {
        id: "xiao-biaodi-red_envelope-020-b",
        text: "姑丈你都投資什麼，教教我基本概念？",
        archetype: "deflect",
        retort: "這個說來話長，改天教你！",
      },
      {
        id: "xiao-biaodi-red_envelope-020-c",
        text: "投資重要，還是你的酒喝夠了沒重要？",
        archetype: "deflect",
        retort: "哎唷，這杯我還沒喝完呢。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-d",
        text: "我不太懂投資，錢都放撲滿裡……",
        archetype: "meek",
        retort: "放撲滿喔，那不會變多啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-e",
        text: "有聽過但不太懂，怕虧錢不敢弄……",
        archetype: "meek",
        retort: "怕虧錢？那你太保守了。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-f",
        text: "我的投資策略是長期持有糖果期貨。",
        archetype: "backfire",
        retort: "……（姑丈聽不懂，繼續喝他的酒）",
      },
      {
        id: "xiao-biaodi-red_envelope-020-g",
        text: "撲滿定存才是穩健的財富自由之道。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續存錢）",
      },
      {
        id: "xiao-biaodi-red_envelope-020-h",
        text: "投資很無聊，你講這個很煩耶。",
        archetype: "landmine",
        retort: "嗚……媽媽——他說我無聊——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-021",
    text: "三舅媽說你今年加薪了，紅包會不會多包一點？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-021-a",
        text: "加薪的部分我拿來加碼給你，這叫回饋股東。",
        archetype: "perfect",
        retort: "哈哈哈回饋股東！我是股東！",
      },
      {
        id: "xiao-biaodi-red_envelope-021-b",
        text: "加薪重要，還是你要不要先幫我拜個年？",
        archetype: "deflect",
        retort: "新年快樂！恭喜發財！",
      },
      {
        id: "xiao-biaodi-red_envelope-021-c",
        text: "你猜猜看我加薪多少，猜對算你贏。",
        archetype: "deflect",
        retort: "我猜加了一千塊！",
      },
      {
        id: "xiao-biaodi-red_envelope-021-d",
        text: "加薪是有啦，但沒有很多……",
        archetype: "meek",
        retort: "沒有很多？那紅包也不會多了。",
      },
      {
        id: "xiao-biaodi-red_envelope-021-e",
        text: "加一點點而已，物價漲更快……",
        archetype: "meek",
        retort: "漲更快？那不就等於沒加？",
      },
      {
        id: "xiao-biaodi-red_envelope-021-f",
        text: "加薪的錢已經拿去投資我的夢想了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續等紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-021-g",
        text: "薪水漲跌是浮動的，紅包永遠是固定的。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽浮動是什麼）",
      },
      {
        id: "xiao-biaodi-red_envelope-021-h",
        text: "加薪關你什麼事，小孩子問這麼多幹嘛。",
        archetype: "landmine",
        retort: "嗚……媽媽——他兇我——",
      },
    ],
  },
] satisfies Question[];
