import type { Question } from "@/content/types";

// situations:
// - 捏紅包猜厚度
// - 問紅包是新鈔還舊鈔
// - 問紅包裡有沒有夾遊戲點數卡
// - 當場拆紅包數金額
// - 紅包會不會被媽媽充公保管
// - 行動支付轉帳代替紙本紅包
// - 問紅包金額尾數吉不吉利
// - 今年紅包有沒有比去年多
// - 紅包要不要平分給弟弟妹妹
// - 問可不可以先預支明年紅包
// - 問紅包袋有沒有寫吉祥話才有心意
// - 問紅包裡是硬幣還是鈔票
// - 問紅包有沒有先被收走繳學費
// - 問能不能吃飯前先領紅包
// - 問阿嬤紅包是不是變少因為退休
// - 排隊領紅包被插隊
// - 問紅包裡的鈔票是不是最大張
// - 紅包金額換算遊戲點數卡
// - 紅包要不要拿去投資理財
// - 問今年薪水漲了紅包會不會跟著漲

export default [
  {
    id: "xiao-biaodi-red_envelope-002",
    text: "讓我捏一下，媽媽說厚的才是誠意十足。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-002-a",
        text: "幹，誠意用捏的？媽媽你婚戒捏得出來嗎。",
        archetype: "perfect",
        retort: "……媽媽噴笑，幹了一聲轉頭",
      },
      {
        id: "xiao-biaodi-red_envelope-002-b",
        text: "靠，先讓我看你手指乾不乾淨。",
        archetype: "deflect",
        retort: "很乾淨啦！我剛洗手！",
      },
      {
        id: "xiao-biaodi-red_envelope-002-c",
        text: "笑死，你猜猜厚度，猜對才給看。",
        archetype: "deflect",
        retort: "我猜……很厚！對不對！",
      },
      {
        id: "xiao-biaodi-red_envelope-002-d",
        text: "呃，幹……其實沒有很厚啦……",
        archetype: "meek",
        retort: "沒有很厚喔！媽媽——他包很薄——",
      },
      {
        id: "xiao-biaodi-red_envelope-002-e",
        text: "普通厚度而已，靠……不算多……",
        archetype: "meek",
        retort: "不算多？那到底多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-002-f",
        text: "厚度是假的，機掰，心意才立體。",
        archetype: "backfire",
        retort: "……（小表弟已經伸手要摸）",
      },
      {
        id: "xiao-biaodi-red_envelope-002-g",
        text: "他媽的，薄紅包才是輕功裝備。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續捏）",
      },
      {
        id: "xiao-biaodi-red_envelope-002-h",
        text: "去你的，別亂摸，叫你媽自己來摸。",
        archetype: "landmine",
        retort: "他媽衝過來吼：你三小啦",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-003",
    text: "老師說新鈔才吉利，你的是新的還舊的？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-003-a",
        text: "去死，新舊而已，老師薪水單新嗎。",
        archetype: "perfect",
        retort: "……他臉一黑，裝滑手機",
      },
      {
        id: "xiao-biaodi-red_envelope-003-b",
        text: "靠，你猜猜看，猜對我就給你看。",
        archetype: "deflect",
        retort: "我猜是新的！一定是新的！",
      },
      {
        id: "xiao-biaodi-red_envelope-003-c",
        text: "笑死，新舊還不是一樣能買糖果。",
        archetype: "deflect",
        retort: "對耶，糖果最重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-003-d",
        text: "應該是舊鈔啦，幹……銀行要排隊……",
        archetype: "meek",
        retort: "舊鈔喔！媽媽——他包舊鈔——",
      },
      {
        id: "xiao-biaodi-red_envelope-003-e",
        text: "靠……不確定耶，沒特別去換……",
        archetype: "meek",
        retort: "沒去換？那誠意不夠喔。",
      },
      {
        id: "xiao-biaodi-red_envelope-003-f",
        text: "機掰，重點是磁場，不是新舊。",
        archetype: "backfire",
        retort: "……（小表弟已經想伸手拆開）",
      },
      {
        id: "xiao-biaodi-red_envelope-003-g",
        text: "他媽的，懂收藏才知道舊鈔好。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，愣愣地看）",
      },
      {
        id: "xiao-biaodi-red_envelope-003-h",
        text: "去你的，問這麼細，先交成績單。",
        archetype: "landmine",
        retort: "他媽媽立刻衝過來拉開你們",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-004",
    text: "姑姑說紅包裡有時候會夾點數卡，你的有嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-004-a",
        text: "幹，夾點數卡，姑姑嫁妝夾現金？",
        archetype: "perfect",
        retort: "……姑姑臉一僵，轉頭聊別的",
      },
      {
        id: "xiao-biaodi-red_envelope-004-b",
        text: "靠，你想要哪種點數卡，我許願？",
        archetype: "deflect",
        retort: "我要遊戲點數卡！拜託拜託！",
      },
      {
        id: "xiao-biaodi-red_envelope-004-c",
        text: "笑死，你先說你最想玩哪個遊戲。",
        archetype: "deflect",
        retort: "我要玩最新那款賽車遊戲！",
      },
      {
        id: "xiao-biaodi-red_envelope-004-d",
        text: "沒有耶，幹……就只有現金而已……",
        archetype: "meek",
        retort: "只有現金喔，好無聊。",
      },
      {
        id: "xiao-biaodi-red_envelope-004-e",
        text: "靠……可能沒想到夾點數卡啦……",
        archetype: "meek",
        retort: "沒想到？那我要提醒你。",
      },
      {
        id: "xiao-biaodi-red_envelope-004-f",
        text: "他媽的，現金才是萬用點數卡。",
        archetype: "backfire",
        retort: "……（小表弟已經在翻紅包找卡片）",
      },
      {
        id: "xiao-biaodi-red_envelope-004-g",
        text: "機掰，紙本點數卡早就過時了。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續翻找）",
      },
      {
        id: "xiao-biaodi-red_envelope-004-h",
        text: "去死，貪心是你，先拿考卷出來。",
        archetype: "landmine",
        retort: "姑姑臉一沉，幹譙一句瞪你",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-005",
    text: "阿嬤說當場拆開數清楚，才知道有沒有誠意。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-005-a",
        text: "靠北，數清楚？阿嬤聘金數過幾次。",
        archetype: "perfect",
        retort: "……阿嬤笑了，招手要橘子",
      },
      {
        id: "xiao-biaodi-red_envelope-005-b",
        text: "靠，阿嬤你先拆你的，互相觀摩。",
        archetype: "deflect",
        retort: "哎唷，阿嬤才不拆呢！",
      },
      {
        id: "xiao-biaodi-red_envelope-005-c",
        text: "笑死，先讓我看你數學厲不厲害。",
        archetype: "deflect",
        retort: "我最會算數學了！等我！",
      },
      {
        id: "xiao-biaodi-red_envelope-005-d",
        text: "幹……我還沒拆，怕紅包袋破掉……",
        archetype: "meek",
        retort: "怕破掉？那到底多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-005-e",
        text: "靠……數字不重要，等一下再拆……",
        archetype: "meek",
        retort: "不重要？那你幹嘛不敢拆？",
      },
      {
        id: "xiao-biaodi-red_envelope-005-f",
        text: "機掰，數字是虛的，溫度才是真的。",
        archetype: "backfire",
        retort: "……（小表弟已經伸手要拆）",
      },
      {
        id: "xiao-biaodi-red_envelope-005-g",
        text: "他媽的，不拆才是對長輩的信任。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-005-h",
        text: "去你的，先盯著你自己的作業啦。",
        archetype: "landmine",
        retort: "阿嬤心疼瞪你，碎念一句",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-006",
    text: "媽媽說紅包等一下要充公，你的也是嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-006-a",
        text: "幹你娘，充公沒差，你薪水充公？",
        archetype: "perfect",
        retort: "……媽媽噴笑，幹譙一聲別鬧",
      },
      {
        id: "xiao-biaodi-red_envelope-006-b",
        text: "靠，你要不要也把糖果充公？",
        archetype: "deflect",
        retort: "才不要，糖果是我的！",
      },
      {
        id: "xiao-biaodi-red_envelope-006-c",
        text: "笑死，你收走的錢都拿去哪？",
        archetype: "deflect",
        retort: "我也不知道，都不見了。",
      },
      {
        id: "xiao-biaodi-red_envelope-006-d",
        text: "對啊，幹……我的也是被收走了……",
        archetype: "meek",
        retort: "收走喔，那你自己一毛都沒有？",
      },
      {
        id: "xiao-biaodi-red_envelope-006-e",
        text: "靠……應該也會被收走一部分……",
        archetype: "meek",
        retort: "一部分？那剩下多少？",
      },
      {
        id: "xiao-biaodi-red_envelope-006-f",
        text: "他媽的，紅包已經升級成投資組合。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-006-g",
        text: "機掰，被保管才是財富自由第一步。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽）",
      },
      {
        id: "xiao-biaodi-red_envelope-006-h",
        text: "去你的，管我紅包，先管你成績。",
        archetype: "landmine",
        retort: "嗚——媽媽你看他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-007",
    text: "老師說現在都用手機轉帳了，你還包紙本喔？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-007-a",
        text: "去死，紙本有溫度，你沒資格用手機。",
        archetype: "perfect",
        retort: "……他臉一黑，摸鼻子罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-007-b",
        text: "靠，你有自己的收款帳號？教我。",
        archetype: "deflect",
        retort: "我還沒有帳號啦，要問媽媽！",
      },
      {
        id: "xiao-biaodi-red_envelope-007-c",
        text: "笑死，你紅包袋是不是很無聊？",
        archetype: "deflect",
        retort: "才不會，我選的圖案超酷！",
      },
      {
        id: "xiao-biaodi-red_envelope-007-d",
        text: "幹……我還沒學會轉帳，就用紙本……",
        archetype: "meek",
        retort: "不會轉帳喔，落伍了吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-007-e",
        text: "靠……轉帳感覺沒有拆的樂趣啦……",
        archetype: "meek",
        retort: "沒樂趣？那你怎麼不學？",
      },
      {
        id: "xiao-biaodi-red_envelope-007-f",
        text: "機掰，我走復古紙本收藏派，很潮。",
        archetype: "backfire",
        retort: "……（小表弟已經去研究媽媽的手機）",
      },
      {
        id: "xiao-biaodi-red_envelope-007-g",
        text: "他媽的，電子支付沒有儀式感。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究手機）",
      },
      {
        id: "xiao-biaodi-red_envelope-007-h",
        text: "去你的，轉帳關你屁事，寫作業去。",
        archetype: "landmine",
        retort: "嗚——他邊哭邊喊：你兇我",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-008",
    text: "阿嬤說尾數是四不吉利，你有沒有算過？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-008-a",
        text: "靠北，迷信而已，阿嬤幾號結婚的。",
        archetype: "perfect",
        retort: "……阿嬤笑了，摸摸口袋",
      },
      {
        id: "xiao-biaodi-red_envelope-008-b",
        text: "靠，阿嬤你包的尾數是幾號？",
        archetype: "deflect",
        retort: "哎唷，你猜猜看嘛！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-c",
        text: "笑死，吃飽比較重要吧，數字而已。",
        archetype: "deflect",
        retort: "吃飽了！年菜好好吃！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-d",
        text: "幹……我還沒算，等一下算給你聽……",
        archetype: "meek",
        retort: "還沒算喔，那快去算！",
      },
      {
        id: "xiao-biaodi-red_envelope-008-e",
        text: "靠……可能剛好卡到不吉利數字……",
        archetype: "meek",
        retort: "卡到喔！阿嬤——他包到四——",
      },
      {
        id: "xiao-biaodi-red_envelope-008-f",
        text: "機掰，數字迷信是舊時代產物。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊念念有詞）",
      },
      {
        id: "xiao-biaodi-red_envelope-008-g",
        text: "他媽的，我信自己的幸運數字。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續算自己的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-008-h",
        text: "去你的，迷信而已，算算你考幾分。",
        archetype: "landmine",
        retort: "嗚——阿嬤你看他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-009",
    text: "姑姑說物價都漲了，你今年紅包有跟著漲嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-009-a",
        text: "幹，物價漲，姑姑你薪水漲了嗎。",
        archetype: "perfect",
        retort: "……姑姑臉一僵，轉頭找阿嬤",
      },
      {
        id: "xiao-biaodi-red_envelope-009-b",
        text: "靠，那你薪水有沒有跟著物價漲？",
        archetype: "deflect",
        retort: "這個……我們再說。",
      },
      {
        id: "xiao-biaodi-red_envelope-009-c",
        text: "笑死，你覺得漲多少才算有誠意？",
        archetype: "deflect",
        retort: "我覺得要漲一倍才夠！",
      },
      {
        id: "xiao-biaodi-red_envelope-009-d",
        text: "應該差不多，幹……沒特別漲……",
        archetype: "meek",
        retort: "沒漲喔，那物價都白漲了。",
      },
      {
        id: "xiao-biaodi-red_envelope-009-e",
        text: "靠……可能還小幅縮水了一點……",
        archetype: "meek",
        retort: "縮水！姑姑——他今年變少——",
      },
      {
        id: "xiao-biaodi-red_envelope-009-f",
        text: "他媽的，金額要跟通膨脫鉤啦。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續數紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-009-g",
        text: "機掰，我包的是穩定幣，不受影響。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽什麼是穩定幣）",
      },
      {
        id: "xiao-biaodi-red_envelope-009-h",
        text: "去死，物價漲關你屁事，寫功課。",
        archetype: "landmine",
        retort: "嗚——姑姑你看他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-010",
    text: "媽媽說紅包要平分給弟弟，你的也要分嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-010-a",
        text: "去你的，平分？媽媽遺產平分了嗎。",
        archetype: "perfect",
        retort: "……媽媽故意咳兩聲罵幹",
      },
      {
        id: "xiao-biaodi-red_envelope-010-b",
        text: "靠，你要不要也分點糖果給大家？",
        archetype: "deflect",
        retort: "好啊！我分糖果給大家！",
      },
      {
        id: "xiao-biaodi-red_envelope-010-c",
        text: "笑死，你弟弟乖不乖，值得多分？",
        archetype: "deflect",
        retort: "他還好啦，普普通通。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-d",
        text: "應該不用分，幹……這份我自己的……",
        archetype: "meek",
        retort: "不分喔，那弟弟會難過耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-e",
        text: "靠……可能要分一點意思一下……",
        archetype: "meek",
        retort: "一點點？那不夠意思吧。",
      },
      {
        id: "xiao-biaodi-red_envelope-010-f",
        text: "機掰，分享是弱者行為，我囤積。",
        archetype: "backfire",
        retort: "……（媽媽已經在旁邊皺眉）",
      },
      {
        id: "xiao-biaodi-red_envelope-010-g",
        text: "他媽的，分紅包是社會主義啦。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，以為在講功課）",
      },
      {
        id: "xiao-biaodi-red_envelope-010-h",
        text: "去死，分紅包關你屁事，分成績單。",
        archetype: "landmine",
        retort: "媽媽衝過來罵：你兇誰啊",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-011",
    text: "老師說借錢要還，你可以先借我明年的紅包嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-011-a",
        text: "幹，借錢要還，老師學貸還完沒。",
        archetype: "perfect",
        retort: "……他臉一黑，裝沒聽到",
      },
      {
        id: "xiao-biaodi-red_envelope-011-b",
        text: "靠，你要借多少，先說你的計畫？",
        archetype: "deflect",
        retort: "我要買新的遊戲片！",
      },
      {
        id: "xiao-biaodi-red_envelope-011-c",
        text: "笑死，借錢要付利息，你付得起？",
        archetype: "deflect",
        retort: "利息是什麼？聽起來很可怕。",
      },
      {
        id: "xiao-biaodi-red_envelope-011-d",
        text: "我自己都不夠，幹……沒辦法借你……",
        archetype: "meek",
        retort: "不夠用喔，那你也很窮耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-011-e",
        text: "靠……可以借一點，但要記得還……",
        archetype: "meek",
        retort: "好！我記下來了，你借我的！",
      },
      {
        id: "xiao-biaodi-red_envelope-011-f",
        text: "他媽的，紅包全投入期貨市場了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續盧著要借）",
      },
      {
        id: "xiao-biaodi-red_envelope-011-g",
        text: "機掰，免利息我都不借，這是原則。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，還在算利息是什麼）",
      },
      {
        id: "xiao-biaodi-red_envelope-011-h",
        text: "去你的，討錢沒禮貌，敢跟老師借？",
        archetype: "landmine",
        retort: "他媽媽瞪你，罵你欠罵了",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-012",
    text: "阿嬤說紅包袋上要寫吉祥話才有心意，你有寫嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-012-a",
        text: "靠北，吉祥話，阿嬤嫁阿公時寫了？",
        archetype: "perfect",
        retort: "……阿嬤笑到合不攏嘴",
      },
      {
        id: "xiao-biaodi-red_envelope-012-b",
        text: "靠，你紅包袋上寫了什麼，唸來聽？",
        archetype: "deflect",
        retort: "我寫的是恭喜發財！",
      },
      {
        id: "xiao-biaodi-red_envelope-012-c",
        text: "笑死，你猜猜我寫了什麼字？",
        archetype: "deflect",
        retort: "我猜……新年快樂！",
      },
      {
        id: "xiao-biaodi-red_envelope-012-d",
        text: "我沒有寫，幹……紅包袋是買現成的……",
        archetype: "meek",
        retort: "沒寫喔，那沒誠意耶。",
      },
      {
        id: "xiao-biaodi-red_envelope-012-e",
        text: "靠……有寫一點點，但字有點醜……",
        archetype: "meek",
        retort: "字醜？阿嬤——他寫得很醜——",
      },
      {
        id: "xiao-biaodi-red_envelope-012-f",
        text: "機掰，吉祥話寫在心裡就好。",
        archetype: "backfire",
        retort: "……（阿嬤在旁邊搖搖頭）",
      },
      {
        id: "xiao-biaodi-red_envelope-012-g",
        text: "他媽的，空白紅包袋才是最高境界。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續研究紅包袋）",
      },
      {
        id: "xiao-biaodi-red_envelope-012-h",
        text: "去死，寫吉祥話很無聊，寫作業去。",
        archetype: "landmine",
        retort: "全場安靜，阿嬤臉垮罵一句",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-013",
    text: "姑丈說裡面是硬幣才好玩，你的是硬幣嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-013-a",
        text: "幹，硬幣好玩，姑丈酒錢也硬幣付？",
        archetype: "perfect",
        retort: "……姑丈臉一黑乾笑兩聲",
      },
      {
        id: "xiao-biaodi-red_envelope-013-b",
        text: "靠，你搖搖看，猜猜幾個硬幣？",
        archetype: "deflect",
        retort: "我搖搖看！叮叮噹噹的！",
      },
      {
        id: "xiao-biaodi-red_envelope-013-c",
        text: "笑死，硬幣比較重，你拿得動？",
        archetype: "deflect",
        retort: "拿得動！我力氣很大的！",
      },
      {
        id: "xiao-biaodi-red_envelope-013-d",
        text: "是鈔票啦，幹……摸起來平平的……",
        archetype: "meek",
        retort: "鈔票喔，那沒有硬幣好玩。",
      },
      {
        id: "xiao-biaodi-red_envelope-013-e",
        text: "靠……應該是鈔票，感覺不出來……",
        archetype: "meek",
        retort: "感覺不出來？那你摸過嗎？",
      },
      {
        id: "xiao-biaodi-red_envelope-013-f",
        text: "他媽的，鈔票是進階版硬幣啦。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續搖他的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-013-g",
        text: "機掰，我收的是紀念幣，很珍貴。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續搖晃）",
      },
      {
        id: "xiao-biaodi-red_envelope-013-h",
        text: "去你的，搖來搖去很吵，寫作業去。",
        archetype: "landmine",
        retort: "姑丈臉一沉，幹譙一聲瞪你",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-014",
    text: "媽媽說你的紅包是不是都拿去繳帳單了？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-014-a",
        text: "去死，帳單？媽媽信用卡繳了沒。",
        archetype: "perfect",
        retort: "……媽媽轉頭裝忙，碎念幹",
      },
      {
        id: "xiao-biaodi-red_envelope-014-b",
        text: "靠，你的紅包會不會也繳補習費？",
        archetype: "deflect",
        retort: "會啊！我媽都拿去繳補習費！",
      },
      {
        id: "xiao-biaodi-red_envelope-014-c",
        text: "笑死，先吃塊糖，帳單哪有糖重要。",
        archetype: "deflect",
        retort: "先吃糖！糖比較重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-014-d",
        text: "對啊，幹……大部分都拿去繳帳單……",
        archetype: "meek",
        retort: "繳帳單喔，那都沒剩下了。",
      },
      {
        id: "xiao-biaodi-red_envelope-014-e",
        text: "靠……留一點自己花，其他繳費……",
        archetype: "meek",
        retort: "留一點？那剩多少啦？",
      },
      {
        id: "xiao-biaodi-red_envelope-014-f",
        text: "他媽的，帳單是我人生另一種紅包。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續玩自己的）",
      },
      {
        id: "xiao-biaodi-red_envelope-014-g",
        text: "機掰，繳帳單是大人的隱藏關卡。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽帳單是什麼）",
      },
      {
        id: "xiao-biaodi-red_envelope-014-h",
        text: "去你的，帳單關你屁事，管你成績。",
        archetype: "landmine",
        retort: "全場安靜，你媽罵你欠揍",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-015",
    text: "老師說先領紅包才有動力吃飯，可以先給我嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-015-a",
        text: "幹，動力而已，老師薪水先發才教？",
        archetype: "perfect",
        retort: "……他臉一黑，罵幹跑走了",
      },
      {
        id: "xiao-biaodi-red_envelope-015-b",
        text: "靠，你先吃三口菜，我給你提示。",
        archetype: "deflect",
        retort: "好！我吃三口！給我提示！",
      },
      {
        id: "xiao-biaodi-red_envelope-015-c",
        text: "笑死，你猜飯後跟飯前哪個大包？",
        archetype: "deflect",
        retort: "飯後的比較大包吧！",
      },
      {
        id: "xiao-biaodi-red_envelope-015-d",
        text: "可以先給一點嗎，幹……我不餓……",
        archetype: "meek",
        retort: "不餓喔，那更要先吃飯了。",
      },
      {
        id: "xiao-biaodi-red_envelope-015-e",
        text: "靠……我等一下再吃，先看紅包……",
        archetype: "meek",
        retort: "先看紅包？那飯菜怎麼辦？",
      },
      {
        id: "xiao-biaodi-red_envelope-015-f",
        text: "他媽的，紅包要吃飯後才會啟動。",
        archetype: "backfire",
        retort: "……（小表弟已經跑去夾菜了）",
      },
      {
        id: "xiao-biaodi-red_envelope-015-g",
        text: "機掰，飢餓感才是最好的開胃菜。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續等紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-015-h",
        text: "去死，吵著要紅包沒禮貌，寫功課。",
        archetype: "landmine",
        retort: "嗚嗚——他躲媽媽背後哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-016",
    text: "姑姑說阿嬤退休沒收入，紅包會不會變少？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-016-a",
        text: "靠北，阿嬤退休，姑姑孝親費包多少。",
        archetype: "perfect",
        retort: "……姑姑臉一僵乾笑閃人",
      },
      {
        id: "xiao-biaodi-red_envelope-016-b",
        text: "靠，阿嬤退休後最愛做什麼？",
        archetype: "deflect",
        retort: "阿嬤最愛種菜跟看歌仔戲！",
      },
      {
        id: "xiao-biaodi-red_envelope-016-c",
        text: "笑死，退休生活比紅包金額重要吧。",
        archetype: "deflect",
        retort: "退休生活重要啦！",
      },
      {
        id: "xiao-biaodi-red_envelope-016-d",
        text: "可能真的會，幹……變少一點點……",
        archetype: "meek",
        retort: "變少喔！阿嬤——他這樣說——",
      },
      {
        id: "xiao-biaodi-red_envelope-016-e",
        text: "靠……應該還好，阿嬤有存退休金……",
        archetype: "meek",
        retort: "有存喔，那應該不會太少。",
      },
      {
        id: "xiao-biaodi-red_envelope-016-f",
        text: "他媽的，阿嬤的紅包不會貶值啦。",
        archetype: "backfire",
        retort: "……（阿嬤聽不懂，繼續織毛衣）",
      },
      {
        id: "xiao-biaodi-red_envelope-016-g",
        text: "機掰，退休資產配置這種事你不懂。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問阿嬤什麼是配置）",
      },
      {
        id: "xiao-biaodi-red_envelope-016-h",
        text: "去你的，退休關你屁事，顧好自己。",
        archetype: "landmine",
        retort: "全場安靜，姑姑罵你三小",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-017",
    text: "阿嬤說要照順序領紅包，你插我隊做什麼？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-017-a",
        text: "幹，插隊而已，阿嬤偏心插過幾次。",
        archetype: "perfect",
        retort: "……阿嬤笑著點頭",
      },
      {
        id: "xiao-biaodi-red_envelope-017-b",
        text: "靠，你先跟阿嬤說吉祥話，換你先領。",
        archetype: "deflect",
        retort: "阿嬤新年快樂！我先領！",
      },
      {
        id: "xiao-biaodi-red_envelope-017-c",
        text: "笑死，剪刀石頭布，贏的先領。",
        archetype: "deflect",
        retort: "好啊！剪刀石頭布！",
      },
      {
        id: "xiao-biaodi-red_envelope-017-d",
        text: "對不起，幹……我太想先看紅包了……",
        archetype: "meek",
        retort: "太想看喔，那大家都想看啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-017-e",
        text: "靠……我只是想快一點，沒惡意……",
        archetype: "meek",
        retort: "沒惡意？那也要排隊啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-017-f",
        text: "他媽的，先到先得是叢林法則啦。",
        archetype: "backfire",
        retort: "……（阿嬤已經叫下一個人）",
      },
      {
        id: "xiao-biaodi-red_envelope-017-g",
        text: "機掰，插隊是積極主動的人生態度。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續排在原地）",
      },
      {
        id: "xiao-biaodi-red_envelope-017-h",
        text: "去你的，插隊沒禮貌，考試插隊過？",
        archetype: "landmine",
        retort: "阿嬤護著他，碎念瞪你一眼",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-018",
    text: "老師說裡面是千元大鈔才叫誠意，你的是嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-018-a",
        text: "去死，大鈔而已，老師月薪是大鈔？",
        archetype: "perfect",
        retort: "……他愣住，臉一黑說不出話",
      },
      {
        id: "xiao-biaodi-red_envelope-018-b",
        text: "靠，你怎麼分辨鈔票大小張？",
        archetype: "deflect",
        retort: "看數字就知道了啊！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-c",
        text: "笑死，大鈔小鈔都一樣能買糖果。",
        archetype: "deflect",
        retort: "對耶，糖果最重要！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-d",
        text: "應該是小張的，幹……誠意不夠……",
        archetype: "meek",
        retort: "小張的喔！誠意不夠——",
      },
      {
        id: "xiao-biaodi-red_envelope-018-e",
        text: "靠……不太確定，還沒仔細看……",
        archetype: "meek",
        retort: "沒看清楚？那快去看！",
      },
      {
        id: "xiao-biaodi-red_envelope-018-f",
        text: "他媽的，鈔票大小是外在的而已。",
        archetype: "backfire",
        retort: "……（小表弟已經想伸手翻看）",
      },
      {
        id: "xiao-biaodi-red_envelope-018-g",
        text: "機掰，小張鈔票才是低調有實力。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續盯著紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-018-h",
        text: "去你的，問這麼細，收好你的考卷。",
        archetype: "landmine",
        retort: "嗚——他跑去找媽媽哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-019",
    text: "媽媽說你紅包夠買幾張遊戲點數卡，算給我聽。",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-019-a",
        text: "幹，算這麼細，媽媽薪水算過嗎。",
        archetype: "perfect",
        retort: "……媽媽臉一僵，尷尬笑兩聲",
      },
      {
        id: "xiao-biaodi-red_envelope-019-b",
        text: "靠，你想玩的遊戲要多少點數？",
        archetype: "deflect",
        retort: "我想玩的要五百點！",
      },
      {
        id: "xiao-biaodi-red_envelope-019-c",
        text: "笑死，點數卡重要，還是作業重要？",
        archetype: "deflect",
        retort: "……作業還沒寫啦。",
      },
      {
        id: "xiao-biaodi-red_envelope-019-d",
        text: "算一算，幹……好像只夠買一張……",
        archetype: "meek",
        retort: "只夠一張喔，那也太少了。",
      },
      {
        id: "xiao-biaodi-red_envelope-019-e",
        text: "靠……換算完發現沒剩多少了……",
        archetype: "meek",
        retort: "沒剩多少？紅包都花去哪了？",
      },
      {
        id: "xiao-biaodi-red_envelope-019-f",
        text: "他媽的，點數卡是虛擬資產啦。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續算他的紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-019-g",
        text: "機掰，我把紅包換算成經驗值。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽）",
      },
      {
        id: "xiao-biaodi-red_envelope-019-h",
        text: "去死，算這個很煩，算你考幾分。",
        archetype: "landmine",
        retort: "嗚——媽媽他兇我幹——",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-020",
    text: "姑丈說紅包要拿去投資才會變多，你懂投資嗎？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-020-a",
        text: "靠北，投資而已，姑丈股票賺了嗎。",
        archetype: "perfect",
        retort: "……姑丈臉一黑假裝滑手機",
      },
      {
        id: "xiao-biaodi-red_envelope-020-b",
        text: "靠，姑丈你都投資什麼，教我？",
        archetype: "deflect",
        retort: "這個說來話長，改天教你！",
      },
      {
        id: "xiao-biaodi-red_envelope-020-c",
        text: "笑死，你酒喝夠了沒比較重要吧。",
        archetype: "deflect",
        retort: "哎唷，這杯我還沒喝完呢。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-d",
        text: "我不太懂，幹……錢都放撲滿裡……",
        archetype: "meek",
        retort: "放撲滿喔，那不會變多啊。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-e",
        text: "靠……有聽過但不懂，怕虧錢……",
        archetype: "meek",
        retort: "怕虧錢？那你太保守了。",
      },
      {
        id: "xiao-biaodi-red_envelope-020-f",
        text: "他媽的，長期持有糖果期貨啦。",
        archetype: "backfire",
        retort: "……（姑丈聽不懂，繼續喝他的酒）",
      },
      {
        id: "xiao-biaodi-red_envelope-020-g",
        text: "機掰，撲滿定存才是財富自由之道。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，繼續存錢）",
      },
      {
        id: "xiao-biaodi-red_envelope-020-h",
        text: "去你的，投資無聊，作業投資完再說。",
        archetype: "landmine",
        retort: "嗚嗚——他躲姑丈身後哭喊幹",
      },
    ],
  },
  {
    id: "xiao-biaodi-red_envelope-021",
    text: "三舅媽說你今年加薪了，紅包會不會多包一點？",
    topic: "red_envelope",
    bossId: "xiao-biaodi",
    options: [
      {
        id: "xiao-biaodi-red_envelope-021-a",
        text: "去死，加薪，三舅媽先問表哥加了沒。",
        archetype: "perfect",
        retort: "……三舅媽臉一僵笑兩聲",
      },
      {
        id: "xiao-biaodi-red_envelope-021-b",
        text: "靠，你要不要先幫我拜個年？",
        archetype: "deflect",
        retort: "新年快樂！恭喜發財！",
      },
      {
        id: "xiao-biaodi-red_envelope-021-c",
        text: "笑死，你猜猜我加薪多少？",
        archetype: "deflect",
        retort: "我猜加了一千塊！",
      },
      {
        id: "xiao-biaodi-red_envelope-021-d",
        text: "加薪是有，幹……但沒有很多……",
        archetype: "meek",
        retort: "沒有很多？那紅包也不會多了。",
      },
      {
        id: "xiao-biaodi-red_envelope-021-e",
        text: "靠……加一點點，物價漲更快……",
        archetype: "meek",
        retort: "漲更快？那不就等於沒加？",
      },
      {
        id: "xiao-biaodi-red_envelope-021-f",
        text: "他媽的，加薪的錢投資夢想了。",
        archetype: "backfire",
        retort: "……（小表弟聽不懂，繼續等紅包）",
      },
      {
        id: "xiao-biaodi-red_envelope-021-g",
        text: "機掰，薪水浮動，紅包永遠固定。",
        archetype: "backfire",
        retort: "（小表弟沒聽懂，跑去問媽媽浮動是什麼）",
      },
      {
        id: "xiao-biaodi-red_envelope-021-h",
        text: "去你的，加薪的事，月考幾分再說。",
        archetype: "landmine",
        retort: "嗚——三舅媽瞪你，罵你欠罵",
      },
    ],
  },
] satisfies Question[];
