// situations: 021 巷口鹹酥雞攤, 022 社區警衛室簽收包裹, 023 陽台種菜, 024 巷口寵物店,
// 025 社區運動器材區, 026 倒垃圾撞見她也倒垃圾, 027 巷口會車讓路,
// 028 社區公用洗衣機前, 029 搬新家具進門, 030 巷口麵線攤, 031 社區交換禮物活動,
// 032 倒回收保特瓶, 033 巷口青草茶攤, 034 社區管理費繳費單前, 035 巷口水餃店,
// 036 社區歲末大掃除分工表
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-comparison-021",
    text: "隔壁小孩很會下廚，你只會叫外送吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-021-a", text: "我不下廚，因為我付得起外送費。", archetype: "perfect", retort: "……她包著鹹酥雞，被將了一軍。" },
      { id: "neighbor-chen-comparison-021-b", text: "下廚的事先別提，鹹酥雞今天特別酥。", archetype: "deflect", retort: "對啊，老闆火候抓得好。" },
      { id: "neighbor-chen-comparison-021-c", text: "確實不太會煮，都靠外食……", archetype: "meek", retort: "外食？那要不要學幾道菜？" },
      { id: "neighbor-chen-comparison-021-d", text: "我下廚的專長是把水燒開啦哈哈。", archetype: "backfire", retort: "……（她包著鹹酥雞，沒理我）" },
      { id: "neighbor-chen-comparison-021-e", text: "妳連我叫不叫外送都算，很閒吧？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-021-f", text: "廚藝的事先保密，這攤還有賣什麼？", archetype: "deflect", retort: "有雞排跟甜不辣啦。" },
      { id: "neighbor-chen-comparison-021-g", text: "確實不太擅長，只會煎蛋而已……", archetype: "meek", retort: "只會煎蛋？那要不要多學幾道？" },
      { id: "neighbor-chen-comparison-021-h", text: "我的廚藝是點外送的手速超快啦。", archetype: "backfire", retort: "（她沒聽懂，繼續炸東西）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-022",
    text: "隔壁小孩投資賺很多，你有在理財嗎？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-022-a", text: "投資的事先別提，警衛伯伯今天辛苦了。", archetype: "deflect", retort: "應該的啦，包裹越來越多。" },
      { id: "neighbor-chen-comparison-022-b", text: "賺多少是隱私，我的錢不用妳審計。", archetype: "perfect", retort: "……她簽著收據，臉有點僵。" },
      { id: "neighbor-chen-comparison-022-c", text: "我投資的是自己，報酬率看不見但很高。", archetype: "backfire", retort: "……（她簽著收據，沒理我）" },
      { id: "neighbor-chen-comparison-022-d", text: "確實比較少投資，怕風險太高……", archetype: "meek", retort: "怕風險？那要不要學一點基礎知識？" },
      { id: "neighbor-chen-comparison-022-e", text: "投資的事先保密，包裹是孫子網購的？", archetype: "deflect", retort: "對啊，年輕人都愛網購。" },
      { id: "neighbor-chen-comparison-022-f", text: "妳這麼會打聽投資，是想跟會嗎？", archetype: "landmine", retort: "你這孩子欠教訓，沒大沒小！" },
      { id: "neighbor-chen-comparison-022-g", text: "我的投資策略是佛系存錢啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續簽收）" },
      { id: "neighbor-chen-comparison-022-h", text: "確實不太懂投資，還在學習……", archetype: "meek", retort: "還在學？那要快點開始喔。" },
    ],
  },
  {
    id: "neighbor-chen-comparison-023",
    text: "隔壁小孩真的很有出息，你要加油喔。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-023-a", text: "會啦，我還在努力找自己的方向……", archetype: "meek", retort: "找方向？那要找到什麼時候？" },
      { id: "neighbor-chen-comparison-023-b", text: "我雖然還沒出息，但種的菜很有生機啦。", archetype: "backfire", retort: "……（她澆著菜，沒理我）" },
      { id: "neighbor-chen-comparison-023-c", text: "出息的定義很多種，妳的標準不是唯一。", archetype: "perfect", retort: "……她澆著菜，沒接話。" },
      { id: "neighbor-chen-comparison-023-d", text: "出息的事先別提，這盆菜種得真翠綠。", archetype: "deflect", retort: "對啊，過年自己種的蔥最新鮮。" },
      { id: "neighbor-chen-comparison-023-e", text: "確實還在努力，還沒有明顯成績……", archetype: "meek", retort: "沒成績？那要不要設定目標？" },
      { id: "neighbor-chen-comparison-023-f", text: "妳這麼愛比出息，妳兒子出息了嗎？", archetype: "landmine", retort: "……她臉一沉，轉身進屋。" },
      { id: "neighbor-chen-comparison-023-g", text: "出息的事先保密，這菜是自己種的嗎？", archetype: "deflect", retort: "對啊，陽台種了好幾種。" },
      { id: "neighbor-chen-comparison-023-h", text: "我雖然還沒出息，但我很會澆花啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續種菜）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-024",
    text: "隔壁小孩很顧家，你都在忙自己的事。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-024-a", text: "我顧家的方式是遠端遙控式關心啦。", archetype: "backfire", retort: "……（她挑著飼料，沒理我）" },
      { id: "neighbor-chen-comparison-024-b", text: "確實比較少關心家裡，工作太忙……", archetype: "meek", retort: "太忙？那要不要抽空多陪陪家人？" },
      { id: "neighbor-chen-comparison-024-c", text: "顧家的事先別提，這隻小狗好可愛。", archetype: "deflect", retort: "對啊，剛進來的新品種。" },
      { id: "neighbor-chen-comparison-024-d", text: "顧家方式不同，我用行動不是嘴巴。", archetype: "perfect", retort: "喔、喔……那先這樣好了。" },
      { id: "neighbor-chen-comparison-024-e", text: "我顧家是心靈上的陪伴，比較抽象啦。", archetype: "backfire", retort: "（她沒聽懂，繼續逛寵物店）" },
      { id: "neighbor-chen-comparison-024-f", text: "顧家的事先保密，這隻貓幾個月大了？", archetype: "deflect", retort: "才三個月而已，很皮。" },
      { id: "neighbor-chen-comparison-024-g", text: "妳連我顧不顧家都要管，妳很閒？", archetype: "landmine", retort: "你這什麼話，虧我平常疼你！" },
      { id: "neighbor-chen-comparison-024-h", text: "確實顧家顧得不夠，該多花點心思……", archetype: "meek", retort: "多花心思？那要不要常回家？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-025",
    text: "隔壁小孩比賽得獎，你有什麼才藝？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-025-a", text: "才藝不用比賽證明，我開心就好。", archetype: "perfect", retort: "……她做著運動，沒接話。" },
      { id: "neighbor-chen-comparison-025-b", text: "才藝的事先別提，運動器材您用得真熟。", archetype: "deflect", retort: "每天都來運動一下啦。" },
      { id: "neighbor-chen-comparison-025-c", text: "我沒什麼特別才藝，比較平凡……", archetype: "meek", retort: "平凡？那要不要培養個興趣？" },
      { id: "neighbor-chen-comparison-025-d", text: "我的才藝是睡覺睡得特別香啦哈哈。", archetype: "backfire", retort: "……（她做著運動，沒理我）" },
      { id: "neighbor-chen-comparison-025-e", text: "妳這麼愛比才藝，妳自己會什麼？", archetype: "landmine", retort: "你這孩子皮在癢是不是！" },
      { id: "neighbor-chen-comparison-025-f", text: "才藝的事先保密，器材是新添購的嗎？", archetype: "deflect", retort: "對啊，上個月才裝的。" },
      { id: "neighbor-chen-comparison-025-g", text: "確實沒什麼拿得出手的才藝……", archetype: "meek", retort: "那要不要去學一項？" },
      { id: "neighbor-chen-comparison-025-h", text: "我的才藝是滑手機滑得特別快啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續運動）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-026",
    text: "隔壁小孩自己在外生活得很好，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-026-a", text: "獨立的事先別提，您也來倒垃圾喔。", archetype: "deflect", retort: "對啊，天天都要倒。" },
      { id: "neighbor-chen-comparison-026-b", text: "我也過得很好，只是不用向妳報告。", archetype: "perfect", retort: "……她拎著垃圾袋，語塞。" },
      { id: "neighbor-chen-comparison-026-c", text: "我獨立生活的證明是冰箱永遠是空的。", archetype: "backfire", retort: "……（她拎著垃圾袋，沒理我）" },
      { id: "neighbor-chen-comparison-026-d", text: "老實說有時候還是需要家裡幫忙……", archetype: "meek", retort: "需要幫忙？那要不要多學著獨立？" },
      { id: "neighbor-chen-comparison-026-e", text: "生活的事先保密，垃圾車今天比較晚？", archetype: "deflect", retort: "對啊，可能路上塞車。" },
      { id: "neighbor-chen-comparison-026-f", text: "妳整天站門口，是巡邏還是打探？", archetype: "landmine", retort: "你這什麼意思，講給你媽聽！" },
      { id: "neighbor-chen-comparison-026-g", text: "我獨立生活獨立到忘記自己會做飯啦。", archetype: "backfire", retort: "（她沒聽懂，倒完垃圾就走）" },
      { id: "neighbor-chen-comparison-026-h", text: "確實還在學習獨立，偶爾會想家……", archetype: "meek", retort: "想家？那要不要常打電話回去？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-027",
    text: "隔壁小孩存錢買新車了，你的車呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-027-a", text: "還在存，我的車還可以再撐一陣子……", archetype: "meek", retort: "再撐？那安全嗎？" },
      { id: "neighbor-chen-comparison-027-b", text: "我的車雖然舊，但很有故事性啦哈哈。", archetype: "backfire", retort: "……（她讓車經過，沒理我）" },
      { id: "neighbor-chen-comparison-027-c", text: "車舊代步就好，錢我花在刀口上。", archetype: "perfect", retort: "……她讓車經過，臉色僵住。" },
      { id: "neighbor-chen-comparison-027-d", text: "買車的事先別提，您這邊會車技術真好。", archetype: "deflect", retort: "開了幾十年，習慣了。" },
      { id: "neighbor-chen-comparison-027-e", text: "確實還沒存夠，車子將就著開……", archetype: "meek", retort: "將就？那安全上要多注意喔。" },
      { id: "neighbor-chen-comparison-027-f", text: "妳連我開什麼車都算，是想搭便車？", archetype: "landmine", retort: "好，你行，明年別叫我開車載你！" },
      { id: "neighbor-chen-comparison-027-g", text: "車的事先保密，這巷子會車真的要小心。", archetype: "deflect", retort: "對啊，路太窄了。" },
      { id: "neighbor-chen-comparison-027-h", text: "我的車雖然舊，但省油得像傳說一樣。", archetype: "backfire", retort: "（她沒聽懂，繼續往前走）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-028",
    text: "隔壁小孩常送禮物回家，你有嗎？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-028-a", text: "我送的禮物是滿滿的愛，看不到但很多。", archetype: "backfire", retort: "……（她拿著衣服，沒理我）" },
      { id: "neighbor-chen-comparison-028-b", text: "確實比較少送東西，比較忙沒想到……", archetype: "meek", retort: "沒想到？那下次要記得喔。" },
      { id: "neighbor-chen-comparison-028-c", text: "送禮的事先別提，這洗衣機轉得真快。", archetype: "deflect", retort: "對啊，新機種比較省時間。" },
      { id: "neighbor-chen-comparison-028-d", text: "陪爸媽聊天，比禮物更值錢。", archetype: "perfect", retort: "……她拿著衣服，被說中了。" },
      { id: "neighbor-chen-comparison-028-e", text: "我送的禮物都是精神層面的，比較高級。", archetype: "backfire", retort: "（她沒聽懂，繼續等洗衣機）" },
      { id: "neighbor-chen-comparison-028-f", text: "送禮的事先保密，這台洗衣機好用嗎？", archetype: "deflect", retort: "很好用，洗得很乾淨。" },
      { id: "neighbor-chen-comparison-028-g", text: "妳連我送不送禮都要管，很閒厚？", archetype: "landmine", retort: "你這什麼態度，欠罵是不是！" },
      { id: "neighbor-chen-comparison-028-h", text: "確實應該多送一點心意，我會改進……", archetype: "meek", retort: "改進？那下次過年記得包厚一點。" },
    ],
  },
  {
    id: "neighbor-chen-comparison-029",
    text: "隔壁小孩換新家具了，你家還是舊的。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-029-a", text: "家具是舊的，我的品味可沒退流行。", archetype: "perfect", retort: "……她扶著搬家的箱子，語塞。" },
      { id: "neighbor-chen-comparison-029-b", text: "家具的事先別提，謝謝您留意搬家動靜。", archetype: "deflect", retort: "不客氣，鄰居互相照應。" },
      { id: "neighbor-chen-comparison-029-c", text: "確實還沒換新的，預算還沒到位……", archetype: "meek", retort: "沒到位？那要不要慢慢存？" },
      { id: "neighbor-chen-comparison-029-d", text: "我的舊家具是復古風，越舊越有價值啦。", archetype: "backfire", retort: "……（她看著搬家，沒理我）" },
      { id: "neighbor-chen-comparison-029-e", text: "妳連我家具新舊都管，很閒是吧？", archetype: "landmine", retort: "你這孩子沒大沒小，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-029-f", text: "家具的事先保密，這是誰家在搬家具？", archetype: "deflect", retort: "是三樓那戶啦。" },
      { id: "neighbor-chen-comparison-029-g", text: "確實想換，但錢還是要花在刀口上……", archetype: "meek", retort: "刀口上？那要優先換什麼？" },
      { id: "neighbor-chen-comparison-029-h", text: "我的家具舊到自帶懷舊濾鏡啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續看熱鬧）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-030",
    text: "隔壁小孩做事超積極，你都慢半拍。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-030-a", text: "積極的事先別提，這攤麵線今天賣得快。", archetype: "deflect", retort: "對啊，天冷生意就是好。" },
      { id: "neighbor-chen-comparison-030-b", text: "慢有慢的道理，我求穩不求妳滿意。", archetype: "perfect", retort: "……她端著麵線，被嗆到。" },
      { id: "neighbor-chen-comparison-030-c", text: "我反應慢是因為在深度思考啦哈哈。", archetype: "backfire", retort: "……（她端著麵線，沒理我）" },
      { id: "neighbor-chen-comparison-030-d", text: "確實比較慢熱，做事需要多一點時間……", archetype: "meek", retort: "多一點時間？那要不要練習快一點？" },
      { id: "neighbor-chen-comparison-030-e", text: "積極的事先保密，這碗加大腸好香。", archetype: "deflect", retort: "對啊，我們家料放得多。" },
      { id: "neighbor-chen-comparison-030-f", text: "妳連我快不快都要管，是很閒嗎？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-030-g", text: "我做事慢，但品質保證慢工出細活。", archetype: "backfire", retort: "（她沒聽懂，繼續盛麵線）" },
      { id: "neighbor-chen-comparison-030-h", text: "確實比較慢，還在調整步調……", archetype: "meek", retort: "調整步調？那要不要多練習？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-031",
    text: "隔壁小孩人緣超好，朋友一大票。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-031-a", text: "我朋友是比較少，但都是知心的……", archetype: "meek", retort: "少？那會不會太孤單？" },
      { id: "neighbor-chen-comparison-031-b", text: "我人緣好到朋友都藏起來不讓人知道。", archetype: "backfire", retort: "……（她整理著禮物，沒理我）" },
      { id: "neighbor-chen-comparison-031-c", text: "朋友不用多，交心的比較重要。", archetype: "perfect", retort: "……她整理著禮物，語塞。" },
      { id: "neighbor-chen-comparison-031-d", text: "人緣的事先別提，這禮物我要抽哪個？", archetype: "deflect", retort: "隨便抽都好，都很不錯。" },
      { id: "neighbor-chen-comparison-031-e", text: "確實朋友不算多，比較內向……", archetype: "meek", retort: "內向？那要不要多參加活動？" },
      { id: "neighbor-chen-comparison-031-f", text: "妳連我朋友多不多都算，很閒喔？", archetype: "landmine", retort: "你這孩子欠教訓，沒禮貌！" },
      { id: "neighbor-chen-comparison-031-g", text: "人緣的事先保密，這活動什麼時候抽獎？", archetype: "deflect", retort: "等一下就要開始了。" },
      { id: "neighbor-chen-comparison-031-h", text: "我朋友都是網路上的，人緣好到看不見。", archetype: "backfire", retort: "（她沒聽懂，繼續整理禮物）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-032",
    text: "隔壁小孩很會照顧阿公阿嬤，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-032-a", text: "我照顧長輩的方式是傳長輩圖問候啦。", archetype: "backfire", retort: "……（她壓著保特瓶，沒理我）" },
      { id: "neighbor-chen-comparison-032-b", text: "確實比較少陪長輩，工作太忙了……", archetype: "meek", retort: "太忙？那要不要多回去看看？" },
      { id: "neighbor-chen-comparison-032-c", text: "照顧長輩的事先別提，瓶子要壓扁再丟嗎？", archetype: "deflect", retort: "對啊，比較省空間。" },
      { id: "neighbor-chen-comparison-032-d", text: "陪伴方式不同，我常打電話關心。", archetype: "perfect", retort: "……她壓著保特瓶，沒接話。" },
      { id: "neighbor-chen-comparison-032-e", text: "我照顧長輩的方式是遠端精神鼓勵啦。", archetype: "backfire", retort: "（她沒聽懂，繼續分類回收）" },
      { id: "neighbor-chen-comparison-032-f", text: "照顧的事先保密，這些瓶子要拿去換錢？", archetype: "deflect", retort: "對啊，換一點零用錢。" },
      { id: "neighbor-chen-comparison-032-g", text: "妳連我孝不孝順都要管，關妳什麼事？", archetype: "landmine", retort: "……她臉色一沉，轉身就走。" },
      { id: "neighbor-chen-comparison-032-h", text: "確實應該多花時間陪伴，會檢討……", archetype: "meek", retort: "檢討？那要不要這禮拜就回去看看？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-033",
    text: "隔壁小孩人生規劃得清清楚楚，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-033-a", text: "規劃因人而異，我走一步也踏實。", archetype: "perfect", retort: "……她倒著青草茶，語塞。" },
      { id: "neighbor-chen-comparison-033-b", text: "規劃的事先別提，這杯青草茶好消暑。", archetype: "deflect", retort: "對啊，天熱就是要喝這個。" },
      { id: "neighbor-chen-comparison-033-c", text: "確實沒什麼明確規劃，比較隨性……", archetype: "meek", retort: "隨性？那不會沒有方向嗎？" },
      { id: "neighbor-chen-comparison-033-d", text: "我的人生規劃是隨機應變版的啦哈哈。", archetype: "backfire", retort: "……（她倒著青草茶，沒理我）" },
      { id: "neighbor-chen-comparison-033-e", text: "妳連我人生規劃都要管，很閒吧？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-033-f", text: "規劃的事先保密，這攤青草茶開多久了？", archetype: "deflect", retort: "開快二十年了啦。" },
      { id: "neighbor-chen-comparison-033-g", text: "確實比較沒方向，還在摸索……", archetype: "meek", retort: "摸索？那要不要定個短期目標？" },
      { id: "neighbor-chen-comparison-033-h", text: "我的人生規劃寫在風裡，隨風飄啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續倒茶）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-034",
    text: "隔壁小孩已經在規劃退休金，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-034-a", text: "退休金的事先別提，繳費單好大張。", archetype: "deflect", retort: "對啊，每個月都要繳。" },
      { id: "neighbor-chen-comparison-034-b", text: "退休規劃我有，只是不會跟妳報告。", archetype: "perfect", retort: "……她看著繳費單，語塞。" },
      { id: "neighbor-chen-comparison-034-c", text: "我的退休計畫是中樂透啦哈哈。", archetype: "backfire", retort: "……（她看著繳費單，沒理我）" },
      { id: "neighbor-chen-comparison-034-d", text: "確實還沒開始規劃，有點來不及的感覺……", archetype: "meek", retort: "來不及？那要趕快開始存喔。" },
      { id: "neighbor-chen-comparison-034-e", text: "退休金的事先保密，繳費單是不是漲價？", archetype: "deflect", retort: "對啊，這個月多收一點。" },
      { id: "neighbor-chen-comparison-034-f", text: "妳連我退休金都要管，妳退休金多少？", archetype: "landmine", retort: "你問這什麼話，沒大沒小！" },
      { id: "neighbor-chen-comparison-034-g", text: "我的退休金計畫是靠緣分啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續看繳費單）" },
      { id: "neighbor-chen-comparison-034-h", text: "確實應該開始規劃了，會認真考慮……", archetype: "meek", retort: "考慮？那要不要現在就開始存？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-035",
    text: "隔壁小孩留學回來，學歷比你高好多。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-035-a", text: "確實學歷比較普通，沒出國唸書……", archetype: "meek", retort: "普通？那要不要考慮進修？" },
      { id: "neighbor-chen-comparison-035-b", text: "我雖然沒留學，但我很會吃異國料理啦。", archetype: "backfire", retort: "……（她包著水餃，沒理我）" },
      { id: "neighbor-chen-comparison-035-c", text: "學歷不是唯一標準，實力才是真本事。", archetype: "perfect", retort: "……她包著水餃，語塞。" },
      { id: "neighbor-chen-comparison-035-d", text: "學歷的事先別提，這攤水餃現包的真好吃。", archetype: "deflect", retort: "對啊，皮薄餡多。" },
      { id: "neighbor-chen-comparison-035-e", text: "確實學歷普通，還在累積經驗……", archetype: "meek", retort: "累積經驗？那要不要考慮進修學位？" },
      { id: "neighbor-chen-comparison-035-f", text: "妳連我學歷都要嫌，妳讀到哪？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-035-g", text: "學歷的事先保密，這水餃一顆多少錢？", archetype: "deflect", retort: "一顆三塊半啦。" },
      { id: "neighbor-chen-comparison-035-h", text: "我雖然沒留學，但我很會查翻譯軟體啦。", archetype: "backfire", retort: "（她沒聽懂，繼續包水餃）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-036",
    text: "說了這麼多，你到底哪裡贏人家啊？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-036-a", text: "我贏在心態好，其他都可以之後再說。", archetype: "backfire", retort: "……（她看著分工表，沒接話）" },
      { id: "neighbor-chen-comparison-036-b", text: "老實說好像真的沒有特別贏的地方……", archetype: "meek", retort: "沒有？那要不要找找自己的優點？" },
      { id: "neighbor-chen-comparison-036-c", text: "輸贏的事先別提，這分工表排得真公平。", archetype: "deflect", retort: "對啊，大家輪流分擔。" },
      { id: "neighbor-chen-comparison-036-d", text: "人生不是比賽，我贏在做自己自在。", archetype: "perfect", retort: "……她看著分工表，語塞。" },
      { id: "neighbor-chen-comparison-036-e", text: "我贏在潛力無窮，還沒開發完啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續看分工表）" },
      { id: "neighbor-chen-comparison-036-f", text: "比較的事先保密，這次大掃除我排哪區？", archetype: "deflect", retort: "排你負責樓梯間好了。" },
      { id: "neighbor-chen-comparison-036-g", text: "妳一直拿我跟別人比，是很閒嗎？", archetype: "landmine", retort: "……她臉色一沉，甩頭就走。" },
      { id: "neighbor-chen-comparison-036-h", text: "確實想不出來贏在哪，會再想想……", archetype: "meek", retort: "再想想？那要不要找個目標努力？" },
    ],
  },
] satisfies Question[];
