// situations: 021 巷口鹹酥雞攤, 022 社區警衛室簽收包裹, 023 陽台種菜, 024 巷口寵物店,
// 025 社區運動器材區, 026 倒垃圾撞見她也倒垃圾, 027 巷口會車讓路,
// 028 社區公用洗衣機前, 029 搬新家具進門, 030 巷口麵線攤, 031 社區交換禮物活動,
// 032 倒回收保特瓶, 033 巷口青草茶攤, 034 社區管理費繳費單前, 035 巷口水餃店,
// 036 社區歲末大掃除分工表
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-comparison-021",
    text: "隔壁小孩很會下廚，你只會叫外送吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-021-a", text: "靠，我不下廚，因為我付得起外送費。", archetype: "perfect", retort: "……她包著鹹酥雞，靠，被將一軍！" },
      { id: "neighbor-chen-comparison-021-b", text: "下廚先別提，笑死，鹹酥雞今天特別酥。", archetype: "deflect", retort: "對啊，老闆火候抓得好。" },
      { id: "neighbor-chen-comparison-021-c", text: "確實不太會煮，幹……都靠外食……", archetype: "meek", retort: "外食？那要不要學幾道菜？" },
      { id: "neighbor-chen-comparison-021-d", text: "我下廚的專長是把水燒開，哭爸厲害。", archetype: "backfire", retort: "……（她包著鹹酥雞，沒理我）" },
      { id: "neighbor-chen-comparison-021-e", text: "機掰，老屁股，妳連我叫不叫外送都算，很閒吧？", archetype: "landmine", retort: "你他媽的講話這麼衝，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-021-f", text: "廚藝先保密，靠，這攤還有賣什麼？", archetype: "deflect", retort: "有雞排跟甜不辣啦。" },
      { id: "neighbor-chen-comparison-021-g", text: "確實不太擅長，靠……只會煎蛋而已……", archetype: "meek", retort: "只會煎蛋？那要不要多學幾道？" },
      { id: "neighbor-chen-comparison-021-h", text: "我的廚藝是點外送的手速超快，幹恁娘快。", archetype: "backfire", retort: "（她沒聽懂，繼續炸東西）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-022",
    text: "隔壁小孩投資賺很多，你有在理財嗎？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-022-a", text: "投資先別提，笑死，警衛伯伯今天辛苦了。", archetype: "deflect", retort: "應該的啦，包裹越來越多。" },
      { id: "neighbor-chen-comparison-022-b", text: "哭爸，賺多少是隱私，我的錢不用妳審計。", archetype: "perfect", retort: "……她簽著收據，哭爸，臉有點僵！" },
      { id: "neighbor-chen-comparison-022-c", text: "我投資的是自己，報酬率看不見但很高，靠北猛。", archetype: "backfire", retort: "……（她簽著收據，沒理我）" },
      { id: "neighbor-chen-comparison-022-d", text: "確實比較少投資，幹……怕風險太高……", archetype: "meek", retort: "怕風險？那要不要學一點基礎知識？" },
      { id: "neighbor-chen-comparison-022-e", text: "投資先保密，靠，包裹是孫子網購的？", archetype: "deflect", retort: "對啊，年輕人都愛網購。" },
      { id: "neighbor-chen-comparison-022-f", text: "幹你娘，老番顛，妳這麼會打聽投資，想跟會嗎？", archetype: "landmine", retort: "去你的，你這孩子欠教訓，沒大沒小！" },
      { id: "neighbor-chen-comparison-022-g", text: "我的投資策略是佛系存錢，機掰穩。", archetype: "backfire", retort: "（她沒聽懂，繼續簽收）" },
      { id: "neighbor-chen-comparison-022-h", text: "確實不太懂投資，靠……還在學習……", archetype: "meek", retort: "還在學？那要快點開始喔。" },
    ],
  },
  {
    id: "neighbor-chen-comparison-023",
    text: "隔壁小孩真的很有出息，你要加油喔。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-023-a", text: "我雖然還沒出息，但種的菜很有生機，去你的猛。", archetype: "backfire", retort: "……（她澆著菜，沒理我）" },
      { id: "neighbor-chen-comparison-023-b", text: "會啦，幹……我還在努力找自己的方向……", archetype: "meek", retort: "找方向？那要找到什麼時候？" },
      { id: "neighbor-chen-comparison-023-c", text: "幹恁娘，出息的定義很多種，妳的標準不是唯一。", archetype: "perfect", retort: "……她澆著菜，幹恁娘，沒接話！" },
      { id: "neighbor-chen-comparison-023-d", text: "出息先別提，笑死，這盆菜種得真翠綠。", archetype: "deflect", retort: "對啊，過年自己種的蔥最新鮮。" },
      { id: "neighbor-chen-comparison-023-e", text: "確實還在努力，靠……還沒有明顯成績……", archetype: "meek", retort: "沒成績？那要不要設定目標？" },
      { id: "neighbor-chen-comparison-023-f", text: "老不死，妳這麼愛比出息，妳兒子出息了嗎，去死啦？", archetype: "landmine", retort: "……她臉一沉，你他媽的轉身進屋！" },
      { id: "neighbor-chen-comparison-023-g", text: "出息先保密，靠，這菜是自己種的嗎？", archetype: "deflect", retort: "對啊，陽台種了好幾種。" },
      { id: "neighbor-chen-comparison-023-h", text: "我雖然還沒出息，但我很會澆花，去死啦浪漫。", archetype: "backfire", retort: "（她沒聽懂，繼續種菜）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-024",
    text: "隔壁小孩很顧家，你都在忙自己的事。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-024-a", text: "我顧家的方式是遠端遙控式關心，靠杯先進。", archetype: "backfire", retort: "……（她挑著飼料，沒理我）" },
      { id: "neighbor-chen-comparison-024-b", text: "確實比較少關心家裡，幹……工作太忙……", archetype: "meek", retort: "太忙？那要不要抽空多陪陪家人？" },
      { id: "neighbor-chen-comparison-024-c", text: "顧家先別提，笑死，這隻小狗好可愛。", archetype: "deflect", retort: "對啊，剛進來的新品種。" },
      { id: "neighbor-chen-comparison-024-d", text: "他媽的，顧家方式不同，我用行動不是嘴巴。", archetype: "perfect", retort: "喔喔，他媽的，那先這樣好了。" },
      { id: "neighbor-chen-comparison-024-e", text: "我顧家是心靈上的陪伴，比較抽象，幹虛。", archetype: "backfire", retort: "（她沒聽懂，繼續逛寵物店）" },
      { id: "neighbor-chen-comparison-024-f", text: "顧家先保密，靠，這隻貓幾個月大了？", archetype: "deflect", retort: "才三個月而已，很皮。" },
      { id: "neighbor-chen-comparison-024-g", text: "幹，死老太婆，妳連我顧不顧家都要管，很閒？", archetype: "landmine", retort: "靠北，你這什麼話，虧我平常疼你！" },
      { id: "neighbor-chen-comparison-024-h", text: "確實顧家顧得不夠，靠……該多花點心思……", archetype: "meek", retort: "多花心思？那要不要常回家？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-025",
    text: "隔壁小孩比賽得獎，你有什麼才藝？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-025-a", text: "去你的，才藝不用比賽證明，我開心就好。", archetype: "perfect", retort: "……她做著運動，去你的，沒接話。" },
      { id: "neighbor-chen-comparison-025-b", text: "才藝先別提，笑死，運動器材您用得真熟。", archetype: "deflect", retort: "每天都來運動一下啦。" },
      { id: "neighbor-chen-comparison-025-c", text: "我沒什麼特別才藝，幹……比較平凡……", archetype: "meek", retort: "平凡？那要不要培養個興趣？" },
      { id: "neighbor-chen-comparison-025-d", text: "我的才藝是睡覺睡得特別香，哭爸強。", archetype: "backfire", retort: "……（她做著運動，沒理我）" },
      { id: "neighbor-chen-comparison-025-e", text: "他媽的，老東西，妳這麼愛比才藝，妳會什麼？", archetype: "landmine", retort: "幹，你這孩子皮在癢是不是！" },
      { id: "neighbor-chen-comparison-025-f", text: "才藝先保密，靠，器材是新添購的嗎？", archetype: "deflect", retort: "對啊，上個月才裝的。" },
      { id: "neighbor-chen-comparison-025-g", text: "確實沒什麼拿得出手的才藝，靠……", archetype: "meek", retort: "那要不要去學一項？" },
      { id: "neighbor-chen-comparison-025-h", text: "我的才藝是滑手機滑得特別快，幹恁娘猛。", archetype: "backfire", retort: "（她沒聽懂，繼續運動）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-026",
    text: "隔壁小孩自己在外生活得很好，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-026-a", text: "獨立先別提，笑死，您也來倒垃圾喔。", archetype: "deflect", retort: "對啊，天天都要倒。" },
      { id: "neighbor-chen-comparison-026-b", text: "靠，我也過得很好，只是不用向妳報告。", archetype: "perfect", retort: "……她拎著垃圾袋，靠，語塞！" },
      { id: "neighbor-chen-comparison-026-c", text: "我獨立生活的證明是冰箱永遠是空的，去死啦猛。", archetype: "backfire", retort: "……（她拎著垃圾袋，沒理我）" },
      { id: "neighbor-chen-comparison-026-d", text: "老實說有時候還是需要家裡幫忙，幹……", archetype: "meek", retort: "需要幫忙？那要不要多學著獨立？" },
      { id: "neighbor-chen-comparison-026-e", text: "生活先保密，靠，垃圾車今天比較晚？", archetype: "deflect", retort: "對啊，可能路上塞車。" },
      { id: "neighbor-chen-comparison-026-f", text: "去你的，老太婆，妳整天站門口，是巡邏還是打探？", archetype: "landmine", retort: "你他媽的講給你媽聽，沒禮貌！" },
      { id: "neighbor-chen-comparison-026-g", text: "我獨立生活獨立到忘記自己會做飯，機掰慘。", archetype: "backfire", retort: "（她沒聽懂，倒完垃圾就走）" },
      { id: "neighbor-chen-comparison-026-h", text: "確實還在學習獨立，靠……偶爾會想家……", archetype: "meek", retort: "想家？那要不要常打電話回去？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-027",
    text: "隔壁小孩存錢買新車了，你的車呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-027-a", text: "還在存，幹……我的車還可以再撐一陣子……", archetype: "meek", retort: "再撐？那安全嗎？" },
      { id: "neighbor-chen-comparison-027-b", text: "我的車雖然舊，但很有故事性，靠杯經典。", archetype: "backfire", retort: "……（她讓車經過，沒理我）" },
      { id: "neighbor-chen-comparison-027-c", text: "去你的，車舊代步就好，錢我花在刀口上。", archetype: "perfect", retort: "……她讓車經過，去你的，臉色僵住！" },
      { id: "neighbor-chen-comparison-027-d", text: "買車先別提，笑死，您這邊會車技術真好。", archetype: "deflect", retort: "開了幾十年，習慣了。" },
      { id: "neighbor-chen-comparison-027-e", text: "確實還沒存夠，靠……車子將就著開……", archetype: "meek", retort: "將就？那安全上要多注意喔。" },
      { id: "neighbor-chen-comparison-027-f", text: "機掰，老屁股，妳連我開什麼車都算，想搭便車？", archetype: "landmine", retort: "好，你行，幹，明年別叫我開車載你！" },
      { id: "neighbor-chen-comparison-027-g", text: "車的事先保密，靠，這巷子會車真的要小心。", archetype: "deflect", retort: "對啊，路太窄了。" },
      { id: "neighbor-chen-comparison-027-h", text: "我的車雖然舊，但省油得像傳說，幹你娘咧誇張。", archetype: "backfire", retort: "（她沒聽懂，繼續往前走）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-028",
    text: "隔壁小孩常送禮物回家，你有嗎？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-028-a", text: "我送的禮物是滿滿的愛，看不到但很多，靠杯浪漫。", archetype: "backfire", retort: "……（她拿著衣服，沒理我）" },
      { id: "neighbor-chen-comparison-028-b", text: "確實比較少送東西，幹……比較忙沒想到……", archetype: "meek", retort: "沒想到？那下次要記得喔。" },
      { id: "neighbor-chen-comparison-028-c", text: "送禮先別提，笑死，這洗衣機轉得真快。", archetype: "deflect", retort: "對啊，新機種比較省時間。" },
      { id: "neighbor-chen-comparison-028-d", text: "哭爸，陪爸媽聊天，比禮物更值錢。", archetype: "perfect", retort: "……她拿著衣服，哭爸，被說中了！" },
      { id: "neighbor-chen-comparison-028-e", text: "我送的禮物都是精神層面的，比較高級，機掰虛。", archetype: "backfire", retort: "（她沒聽懂，繼續等洗衣機）" },
      { id: "neighbor-chen-comparison-028-f", text: "送禮先保密，靠，這台洗衣機好用嗎？", archetype: "deflect", retort: "很好用，洗得很乾淨。" },
      { id: "neighbor-chen-comparison-028-g", text: "幹你娘，老番顛，妳連我送不送禮都要管，很閒？", archetype: "landmine", retort: "你他媽的態度差，欠罵是不是！" },
      { id: "neighbor-chen-comparison-028-h", text: "確實應該多送一點心意，靠……我會改進……", archetype: "meek", retort: "改進？那下次過年記得包厚一點。" },
    ],
  },
  {
    id: "neighbor-chen-comparison-029",
    text: "隔壁小孩換新家具了，你家還是舊的。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-029-a", text: "幹，家具是舊的，我的品味可沒退流行。", archetype: "perfect", retort: "……她扶著搬家的箱子，幹，語塞！" },
      { id: "neighbor-chen-comparison-029-b", text: "家具先別提，笑死，謝謝您留意搬家動靜。", archetype: "deflect", retort: "不客氣，鄰居互相照應。" },
      { id: "neighbor-chen-comparison-029-c", text: "確實還沒換新的，靠……預算還沒到位……", archetype: "meek", retort: "沒到位？那要不要慢慢存？" },
      { id: "neighbor-chen-comparison-029-d", text: "我的舊家具是復古風，越舊越有價值，去你的猛。", archetype: "backfire", retort: "……（她看著搬家，沒理我）" },
      { id: "neighbor-chen-comparison-029-e", text: "老不死，妳連我家具新舊都管，很閒是吧，去死啦？", archetype: "landmine", retort: "靠北，你這孩子沒大沒小，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-029-f", text: "家具先保密，靠，這是誰家在搬家具？", archetype: "deflect", retort: "是三樓那戶啦。" },
      { id: "neighbor-chen-comparison-029-g", text: "確實想換，但錢還是要花在刀口上，幹……", archetype: "meek", retort: "刀口上？那要優先換什麼？" },
      { id: "neighbor-chen-comparison-029-h", text: "我的家具舊到自帶懷舊濾鏡，去死啦潮。", archetype: "backfire", retort: "（她沒聽懂，繼續看熱鬧）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-030",
    text: "隔壁小孩做事超積極，你都慢半拍。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-030-a", text: "積極先別提，笑死，這攤麵線今天賣得快。", archetype: "deflect", retort: "對啊，天冷生意就是好。" },
      { id: "neighbor-chen-comparison-030-b", text: "靠北，慢有慢的道理，我求穩不求妳滿意。", archetype: "perfect", retort: "……她端著麵線，靠北，被嗆到！" },
      { id: "neighbor-chen-comparison-030-c", text: "我反應慢是因為在深度思考，哭爸慢。", archetype: "backfire", retort: "……（她端著麵線，沒理我）" },
      { id: "neighbor-chen-comparison-030-d", text: "確實比較慢熱，幹……做事需要多一點時間……", archetype: "meek", retort: "多一點時間？那要不要練習快一點？" },
      { id: "neighbor-chen-comparison-030-e", text: "積極先保密，靠，這碗加大腸好香。", archetype: "deflect", retort: "對啊，我們家料放得多。" },
      { id: "neighbor-chen-comparison-030-f", text: "幹，死老太婆，妳連我快不快都要管，很閒嗎？", archetype: "landmine", retort: "你他媽的講話這麼衝，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-030-g", text: "我做事慢，但品質保證慢工出細活，機掰讚。", archetype: "backfire", retort: "（她沒聽懂，繼續盛麵線）" },
      { id: "neighbor-chen-comparison-030-h", text: "確實比較慢，靠……還在調整步調……", archetype: "meek", retort: "調整步調？那要不要多練習？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-031",
    text: "隔壁小孩人緣超好，朋友一大票。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-031-a", text: "我朋友是比較少，幹……但都是知心的……", archetype: "meek", retort: "少？那會不會太孤單？" },
      { id: "neighbor-chen-comparison-031-b", text: "我人緣好到朋友都藏起來不讓人知道，靠杯神秘。", archetype: "backfire", retort: "……（她整理著禮物，沒理我）" },
      { id: "neighbor-chen-comparison-031-c", text: "去你的，朋友不用多，交心的比較重要。", archetype: "perfect", retort: "……她整理著禮物，去你的，語塞！" },
      { id: "neighbor-chen-comparison-031-d", text: "人緣先別提，笑死，這禮物我要抽哪個？", archetype: "deflect", retort: "隨便抽都好，都很不錯。" },
      { id: "neighbor-chen-comparison-031-e", text: "確實朋友不算多，靠……比較內向……", archetype: "meek", retort: "內向？那要不要多參加活動？" },
      { id: "neighbor-chen-comparison-031-f", text: "他媽的，老東西，妳連我朋友多不多都算，很閒？", archetype: "landmine", retort: "幹，你這孩子欠教訓，沒禮貌！" },
      { id: "neighbor-chen-comparison-031-g", text: "人緣先保密，靠，這活動什麼時候抽獎？", archetype: "deflect", retort: "等一下就要開始了。" },
      { id: "neighbor-chen-comparison-031-h", text: "我朋友都是網路上的，人緣好到看不見，幹恁娘讚。", archetype: "backfire", retort: "（她沒聽懂，繼續整理禮物）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-032",
    text: "隔壁小孩很會照顧阿公阿嬤，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-032-a", text: "我照顧長輩的方式是傳長輩圖問候，靠杯敷衍。", archetype: "backfire", retort: "……（她壓著保特瓶，沒理我）" },
      { id: "neighbor-chen-comparison-032-b", text: "確實比較少陪長輩，幹……工作太忙了……", archetype: "meek", retort: "太忙？那要不要多回去看看？" },
      { id: "neighbor-chen-comparison-032-c", text: "照顧長輩先別提，笑死，瓶子要壓扁再丟嗎？", archetype: "deflect", retort: "對啊，比較省空間。" },
      { id: "neighbor-chen-comparison-032-d", text: "他媽的，陪伴方式不同，我常打電話關心。", archetype: "perfect", retort: "……她壓著保特瓶，他媽的，沒接話！" },
      { id: "neighbor-chen-comparison-032-e", text: "我照顧長輩的方式是遠端精神鼓勵，機掰虛。", archetype: "backfire", retort: "（她沒聽懂，繼續分類回收）" },
      { id: "neighbor-chen-comparison-032-f", text: "照顧先保密，靠，這些瓶子要拿去換錢？", archetype: "deflect", retort: "對啊，換一點零用錢。" },
      { id: "neighbor-chen-comparison-032-g", text: "去你的，老太婆，妳連我孝不孝順都要管，關妳屁事？", archetype: "landmine", retort: "……她臉色一沉，你他媽的轉身就走！" },
      { id: "neighbor-chen-comparison-032-h", text: "確實應該多花時間陪伴，靠……會檢討……", archetype: "meek", retort: "檢討？那要不要這禮拜就回去看看？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-033",
    text: "隔壁小孩人生規劃得清清楚楚，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-033-a", text: "機掰，規劃因人而異，我走一步也踏實。", archetype: "perfect", retort: "……她倒著青草茶，機掰，語塞！" },
      { id: "neighbor-chen-comparison-033-b", text: "規劃先別提，笑死，這杯青草茶好消暑。", archetype: "deflect", retort: "對啊，天熱就是要喝這個。" },
      { id: "neighbor-chen-comparison-033-c", text: "確實沒什麼明確規劃，幹……比較隨性……", archetype: "meek", retort: "隨性？那不會沒有方向嗎？" },
      { id: "neighbor-chen-comparison-033-d", text: "我的人生規劃是隨機應變版的，靠杯猛。", archetype: "backfire", retort: "……（她倒著青草茶，沒理我）" },
      { id: "neighbor-chen-comparison-033-e", text: "機掰，老屁股，妳連我人生規劃都要管，很閒？", archetype: "landmine", retort: "去你的，你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-033-f", text: "規劃先保密，靠，這攤青草茶開多久了？", archetype: "deflect", retort: "開快二十年了啦。" },
      { id: "neighbor-chen-comparison-033-g", text: "確實比較沒方向，靠……還在摸索……", archetype: "meek", retort: "摸索？那要不要定個短期目標？" },
      { id: "neighbor-chen-comparison-033-h", text: "我的人生規劃寫在風裡，隨風飄，去死啦浪漫。", archetype: "backfire", retort: "（她沒聽懂，繼續倒茶）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-034",
    text: "隔壁小孩已經在規劃退休金，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-034-a", text: "退休金先別提，笑死，繳費單好大張。", archetype: "deflect", retort: "對啊，每個月都要繳。" },
      { id: "neighbor-chen-comparison-034-b", text: "幹，退休規劃我有，只是不會跟妳報告。", archetype: "perfect", retort: "……她看著繳費單，幹，語塞！" },
      { id: "neighbor-chen-comparison-034-c", text: "我的退休計畫是中樂透，哭爸樂觀。", archetype: "backfire", retort: "……（她看著繳費單，沒理我）" },
      { id: "neighbor-chen-comparison-034-d", text: "確實還沒開始規劃，靠……有點來不及的感覺……", archetype: "meek", retort: "來不及？那要趕快開始存喔。" },
      { id: "neighbor-chen-comparison-034-e", text: "退休金先保密，靠，繳費單是不是漲價？", archetype: "deflect", retort: "對啊，這個月多收一點。" },
      { id: "neighbor-chen-comparison-034-f", text: "幹你娘，老番顛，妳連我退休金都要管，妳多少？", archetype: "landmine", retort: "你他媽的問這什麼話，沒大沒小！" },
      { id: "neighbor-chen-comparison-034-g", text: "我的退休金計畫是靠緣分，機掰隨性。", archetype: "backfire", retort: "（她沒聽懂，繼續看繳費單）" },
      { id: "neighbor-chen-comparison-034-h", text: "確實應該開始規劃了，靠……會認真考慮……", archetype: "meek", retort: "考慮？那要不要現在就開始存？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-035",
    text: "隔壁小孩留學回來，學歷比你高好多。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-035-a", text: "確實學歷比較普通，幹……沒出國唸書……", archetype: "meek", retort: "普通？那要不要考慮進修？" },
      { id: "neighbor-chen-comparison-035-b", text: "我雖然沒留學，但我很會吃異國料理，靠杯猛。", archetype: "backfire", retort: "……（她包著水餃，沒理我）" },
      { id: "neighbor-chen-comparison-035-c", text: "去你的，學歷不是唯一標準，實力才是真本事。", archetype: "perfect", retort: "……她包著水餃，去你的，語塞！" },
      { id: "neighbor-chen-comparison-035-d", text: "學歷先別提，笑死，這攤水餃現包的真好吃。", archetype: "deflect", retort: "對啊，皮薄餡多。" },
      { id: "neighbor-chen-comparison-035-e", text: "確實學歷普通，靠……還在累積經驗……", archetype: "meek", retort: "累積經驗？那要不要考慮進修學位？" },
      { id: "neighbor-chen-comparison-035-f", text: "老不死，妳連我學歷都要嫌，妳讀到哪，去死啦？", archetype: "landmine", retort: "你他媽的講話這麼難聽，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-035-g", text: "學歷先保密，靠，這水餃一顆多少錢？", archetype: "deflect", retort: "一顆三塊半啦。" },
      { id: "neighbor-chen-comparison-035-h", text: "我雖然沒留學，但我很會查翻譯軟體，幹恁娘準。", archetype: "backfire", retort: "（她沒聽懂，繼續包水餃）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-036",
    text: "說了這麼多，你到底哪裡贏人家啊？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-036-a", text: "我贏在心態好，其他都可以之後再說，靠杯樂觀。", archetype: "backfire", retort: "……（她看著分工表，沒接話）" },
      { id: "neighbor-chen-comparison-036-b", text: "老實說好像真的沒有特別贏的地方，幹……", archetype: "meek", retort: "沒有？那要不要找找自己的優點？" },
      { id: "neighbor-chen-comparison-036-c", text: "輸贏先別提，笑死，這分工表排得真公平。", archetype: "deflect", retort: "對啊，大家輪流分擔。" },
      { id: "neighbor-chen-comparison-036-d", text: "靠北，人生不是比賽，我贏在做自己自在。", archetype: "perfect", retort: "……她看著分工表，靠北，語塞！" },
      { id: "neighbor-chen-comparison-036-e", text: "我贏在潛力無窮，還沒開發完，機掰猛。", archetype: "backfire", retort: "（她沒聽懂，繼續看分工表）" },
      { id: "neighbor-chen-comparison-036-f", text: "比較先保密，靠，這次大掃除我排哪區？", archetype: "deflect", retort: "排你負責樓梯間好了。" },
      { id: "neighbor-chen-comparison-036-g", text: "幹，死老太婆，妳一直拿我跟別人比，很閒嗎？", archetype: "landmine", retort: "……她臉色一沉，你他媽的甩頭就走！" },
      { id: "neighbor-chen-comparison-036-h", text: "確實想不出來贏在哪，靠……會再想想……", archetype: "meek", retort: "再想想？那要不要找個目標努力？" },
    ],
  },
] satisfies Question[];
