// situations: 001 巷口柑仔店, 002 社區停車場洗車聊天, 003 巷口修改衣服店,
// 004 銀行ATM前, 005 巷口豆漿店, 006 社區大掃除志工日, 007 巷口自助餐店,
// 008 拜年路上巧遇, 009 社區歲末聯歡晚會, 010 巷口賣橘子攤販,
// 011 家門口曬太陽滑手機, 012 巷口機車行, 013 巷口關東煮攤,
// 014 等垃圾車被念滑手機, 015 信箱前欠費通知單, 016 自助洗衣店摺衣服,
// 017 電梯維修公告前, 018 超市排隊結帳, 019 社區地下室資源分類, 020 牽腳踏車出門
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-comparison-001",
    text: "王太太女兒考上公務員了，你怎麼樣？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-001-a", text: "妳把她考幾分都背熟了，很閒喔？", archetype: "perfect", retort: "……她乾笑，轉頭跟別人聊天。" },
      { id: "neighbor-chen-comparison-001-b", text: "她真厲害，這攤糖果賣得真好。", archetype: "deflect", retort: "對啊，過年生意特別好。" },
      { id: "neighbor-chen-comparison-001-c", text: "跟她比是差一點，我還在努力……", archetype: "meek", retort: "差一點？那要不要也去考考看？" },
      { id: "neighbor-chen-comparison-001-d", text: "我雖然沒考上，但我很會考驗自己啦。", archetype: "backfire", retort: "……（她整理著糖果，沒理我）" },
      { id: "neighbor-chen-comparison-001-e", text: "妳兒子呢？怎麼從來沒聽妳提過？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-001-f", text: "比較的事先別提，糖果好懷念。", archetype: "deflect", retort: "對啊，都是老口味。" },
      { id: "neighbor-chen-comparison-001-g", text: "確實比不上，我這條路比較辛苦……", archetype: "meek", retort: "辛苦？那要不要考慮轉考公？" },
      { id: "neighbor-chen-comparison-001-h", text: "我雖然沒考上公職，但很會考驗人生啦。", archetype: "backfire", retort: "（她沒聽懂，繼續整理貨架）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-002",
    text: "張太太女兒嫁醫生耶，住帝寶喔！",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-002-a", text: "她真好命，您這車洗得真乾淨。", archetype: "deflect", retort: "對啊，過年前一定要洗一次。" },
      { id: "neighbor-chen-comparison-002-b", text: "帝寶一坪兩百萬，妳算過沒？", archetype: "perfect", retort: "……她愣了一下，摸摸鼻子。" },
      { id: "neighbor-chen-comparison-002-c", text: "我雖然沒嫁醫生，但我很會照顧自己啦。", archetype: "backfire", retort: "……（她擦著車，沒理我）" },
      { id: "neighbor-chen-comparison-002-d", text: "跟她比是差很多，我這邊比較普通……", archetype: "meek", retort: "普通？那要不要多接觸不同的人？" },
      { id: "neighbor-chen-comparison-002-e", text: "比較的事先保密，這車是新買的嗎？", archetype: "deflect", retort: "不是啦，開十年了。" },
      { id: "neighbor-chen-comparison-002-f", text: "妳不是在洗車，是在打聽情報吧？", archetype: "landmine", retort: "你這什麼意思，講給你媽聽！" },
      { id: "neighbor-chen-comparison-002-g", text: "沒住帝寶沒關係，我家陽台風景也不錯。", archetype: "backfire", retort: "（她沒聽懂，繼續擦車）" },
      { id: "neighbor-chen-comparison-002-h", text: "確實差很多，我還在努力生活……", archetype: "meek", retort: "努力生活？那要不要換個目標？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-003",
    text: "劉先生剛買透天厝，你什麼時候買房？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-003-a", text: "還在存頭期款，差距還很大……", archetype: "meek", retort: "很大？那要存到什麼時候？" },
      { id: "neighbor-chen-comparison-003-b", text: "我雖然沒買透天，但我租的很透氣啦。", archetype: "backfire", retort: "……（她量著衣服，沒理我）" },
      { id: "neighbor-chen-comparison-003-c", text: "買房看緣分，急的話妳先借我頭期？", archetype: "perfect", retort: "……她假笑，說要去忙了。" },
      { id: "neighbor-chen-comparison-003-d", text: "買房的事先別提，這件衣服改得真合身。", archetype: "deflect", retort: "謝謝，我改了三十年手藝。" },
      { id: "neighbor-chen-comparison-003-e", text: "跟他比差很多，還在努力存錢……", archetype: "meek", retort: "努力存？那要不要跟家裡商量？" },
      { id: "neighbor-chen-comparison-003-f", text: "妳這麼愛問房子，是想收仲介費？", archetype: "landmine", retort: "你這孩子欠教訓，沒大沒小！" },
      { id: "neighbor-chen-comparison-003-g", text: "比較的事先保密，這家店開多久了？", archetype: "deflect", retort: "開快四十年了啦。" },
      { id: "neighbor-chen-comparison-003-h", text: "我雖然沒買房，但我很會租房子啦。", archetype: "backfire", retort: "（她沒聽懂，繼續量尺寸）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-004",
    text: "黃小姐都生二胎了，你怎麼還沒動靜？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-004-a", text: "我還在存人生的第一桶金啦哈哈。", archetype: "backfire", retort: "……（她領著錢，沒理我）" },
      { id: "neighbor-chen-comparison-004-b", text: "還沒有計畫，時機還沒到……", archetype: "meek", retort: "沒到？那要不要早點規劃？" },
      { id: "neighbor-chen-comparison-004-c", text: "生小孩的事先別提，這台ATM排隊好長。", archetype: "deflect", retort: "對啊，過年前大家都在領錢。" },
      { id: "neighbor-chen-comparison-004-d", text: "生不生是我的子宮，不是妳的業績。", archetype: "perfect", retort: "妳這孩子，講話越來越犀利。" },
      { id: "neighbor-chen-comparison-004-e", text: "我在忙著存錢，小孩要用金牌保護啦。", archetype: "backfire", retort: "（她沒聽懂，繼續操作機器）" },
      { id: "neighbor-chen-comparison-004-f", text: "這件事先保密，您領錢是要包紅包嗎？", archetype: "deflect", retort: "對啊，準備發紅包用的。" },
      { id: "neighbor-chen-comparison-004-g", text: "妳連生小孩都要管，關妳什麼事？", archetype: "landmine", retort: "……她臉一沉，轉身進電梯。" },
      { id: "neighbor-chen-comparison-004-h", text: "還沒有計畫，順其自然……", archetype: "meek", retort: "順其自然？那不會太晚嗎？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-005",
    text: "郭太太女兒進外商，薪水是你兩倍吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-005-a", text: "外商薪水高，妳查得比人資還細。", archetype: "perfect", retort: "……她乾笑，轉頭跟別人聊天。" },
      { id: "neighbor-chen-comparison-005-b", text: "她真厲害，這豆漿是現磨的嗎？", archetype: "deflect", retort: "對啊，每天早上現磨。" },
      { id: "neighbor-chen-comparison-005-c", text: "跟她比是差很多，我這行薪水普通……", archetype: "meek", retort: "普通？那要不要考慮換工作？" },
      { id: "neighbor-chen-comparison-005-d", text: "我雖然沒進外商，但我很會喝豆漿啦。", archetype: "backfire", retort: "……（她倒著豆漿，沒理我）" },
      { id: "neighbor-chen-comparison-005-e", text: "妳打聽別人薪水，圖利什麼？", archetype: "landmine", retort: "你哪壺不開提哪壺，夭壽喔！" },
      { id: "neighbor-chen-comparison-005-f", text: "薪水的事先保密，燒餅油條看起來好酥。", archetype: "deflect", retort: "對啊，剛炸好的。" },
      { id: "neighbor-chen-comparison-005-g", text: "確實差很多，還在努力提升自己……", archetype: "meek", retort: "提升自己？那要不要進修一下？" },
      { id: "neighbor-chen-comparison-005-h", text: "我雖然不在外商，但我很會外送啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續倒豆漿）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-006",
    text: "蔡太太女兒當老師，穩定又有寒暑假。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-006-a", text: "她真好命，您今天打掃好認真。", archetype: "deflect", retort: "對啊，過年前一定要打掃乾淨。" },
      { id: "neighbor-chen-comparison-006-b", text: "穩定是她的，精彩是我自己的。", archetype: "perfect", retort: "呵呵，妳這孩子，嘴巴真利！" },
      { id: "neighbor-chen-comparison-006-c", text: "我雖然沒寒暑假，但我天天都在放風啦。", archetype: "backfire", retort: "……（她拿著掃把，沒理我）" },
      { id: "neighbor-chen-comparison-006-d", text: "跟她比是差很多，我這行比較辛苦……", archetype: "meek", retort: "辛苦？那要不要考慮考教師？" },
      { id: "neighbor-chen-comparison-006-e", text: "比較的事先保密，這掃把是新買的嗎？", archetype: "deflect", retort: "對啊，舊的壞了。" },
      { id: "neighbor-chen-comparison-006-f", text: "妳羨慕寒暑假，怎麼不自己去考？", archetype: "landmine", retort: "好，你行，明年不用理你！" },
      { id: "neighbor-chen-comparison-006-g", text: "我雖然不是老師，但我很會教訓自己啦。", archetype: "backfire", retort: "（她沒聽懂，繼續打掃）" },
      { id: "neighbor-chen-comparison-006-h", text: "確實比不上，還在努力適應工作……", archetype: "meek", retort: "適應工作？那要不要考慮轉行？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-007",
    text: "許先生自己開公司當老闆，多威風。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-007-a", text: "跟他比是差很多，我還是領薪水的……", archetype: "meek", retort: "領薪水？那要不要考慮創業？" },
      { id: "neighbor-chen-comparison-007-b", text: "我雖然沒開公司，但是自己人生的老闆。", archetype: "backfire", retort: "……（她夾著菜，沒理我）" },
      { id: "neighbor-chen-comparison-007-c", text: "他當老闆有風險，我領薪水很安穩。", archetype: "perfect", retort: "……她轉頭找別人聊，尷尬。" },
      { id: "neighbor-chen-comparison-007-d", text: "創業的事先別提，這家菜色好多。", archetype: "deflect", retort: "對啊，過年加菜。" },
      { id: "neighbor-chen-comparison-007-e", text: "確實差很多，還在累積經驗……", archetype: "meek", retort: "累積經驗？那要累積到什麼時候？" },
      { id: "neighbor-chen-comparison-007-f", text: "妳這麼羨慕，怎麼不叫妳兒子開一間？", archetype: "landmine", retort: "你這什麼話，虧我平常疼你！" },
      { id: "neighbor-chen-comparison-007-g", text: "比較的事先保密，這道菜看起來好吃。", archetype: "deflect", retort: "對啊，老闆手藝不錯。" },
      { id: "neighbor-chen-comparison-007-h", text: "我雖然沒當老闆，但很會自己煮飯啦。", archetype: "backfire", retort: "（她沒聽懂，繼續夾菜）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-008",
    text: "謝先生兒子當醫生了，你們差好多。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-008-a", text: "我雖然不是醫生，但很會照顧健康啦。", archetype: "backfire", retort: "……（她提著禮盒，沒理我）" },
      { id: "neighbor-chen-comparison-008-b", text: "跟他比是差很多，我這行普通……", archetype: "meek", retort: "普通？那要不要考慮進修？" },
      { id: "neighbor-chen-comparison-008-c", text: "醫生的事先別提，恭喜發財新年快樂！", archetype: "deflect", retort: "哎唷，你也是，恭喜發財！" },
      { id: "neighbor-chen-comparison-008-d", text: "職業無貴賤，我的價值不用他認證。", archetype: "perfect", retort: "算了算了，不跟妳計較。" },
      { id: "neighbor-chen-comparison-008-e", text: "我雖然不是醫生，但很會看氣色啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續走路）" },
      { id: "neighbor-chen-comparison-008-f", text: "比較的事先保密，這禮盒是要送誰的？", archetype: "deflect", retort: "送給對面的鄰居啦。" },
      { id: "neighbor-chen-comparison-008-g", text: "謝先生兒子的事，關妳鄰居什麼事？", archetype: "landmine", retort: "……她臉色變了，沒再說話。" },
      { id: "neighbor-chen-comparison-008-h", text: "確實差很多，我還在努力中……", archetype: "meek", retort: "努力中？那要努力到什麼時候？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-009",
    text: "林太太兒子當經理，你事業發展如何？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-009-a", text: "他當經理是他的事，我過我的日子。", archetype: "perfect", retort: "……她臉有點僵，沒接話。" },
      { id: "neighbor-chen-comparison-009-b", text: "事業的事先別提，晚會表演真精彩。", archetype: "deflect", retort: "對啊，社區今年辦得特別用心。" },
      { id: "neighbor-chen-comparison-009-c", text: "跟他比是差一點，還在努力往上爬……", archetype: "meek", retort: "往上爬？那要努力到什麼程度？" },
      { id: "neighbor-chen-comparison-009-d", text: "我雖然沒當經理，但很會管理自己啦。", archetype: "backfire", retort: "……（她看著表演，沒理我）" },
      { id: "neighbor-chen-comparison-009-e", text: "妳這麼會比較，比一下妳自己兒子？", archetype: "landmine", retort: "你這囡仔皮在癢是不是！" },
      { id: "neighbor-chen-comparison-009-f", text: "比較的事先保密，這抽獎有什麼獎品？", archetype: "deflect", retort: "聽說頭獎是腳踏車。" },
      { id: "neighbor-chen-comparison-009-g", text: "確實差一點，還在累積經驗……", archetype: "meek", retort: "累積經驗？那要累積到什麼時候？" },
      { id: "neighbor-chen-comparison-009-h", text: "我雖然沒升官，但升值了心情啦。", archetype: "backfire", retort: "（她沒聽懂，繼續看表演）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-010",
    text: "李太太兒子在竹科，年終領好幾個月。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-010-a", text: "他真厲害，這攤橘子看起來好甜。", archetype: "deflect", retort: "對啊，過年應景，買一點吧。" },
      { id: "neighbor-chen-comparison-010-b", text: "年終是他的，成就感是我自己給的。", archetype: "perfect", retort: "妳喔，真是伶牙俐齒。" },
      { id: "neighbor-chen-comparison-010-c", text: "我雖然沒領那麼多年終，但很會過年啦。", archetype: "backfire", retort: "……（她挑著橘子，沒理我）" },
      { id: "neighbor-chen-comparison-010-d", text: "跟他比是差很多，我這行年終普通……", archetype: "meek", retort: "普通？那要不要考慮轉科技業？" },
      { id: "neighbor-chen-comparison-010-e", text: "年終的事先保密，橘子多少錢一斤？", archetype: "deflect", retort: "一斤五十塊，很甜喔。" },
      { id: "neighbor-chen-comparison-010-f", text: "妳算別人年終，算過自己多閒嗎？", archetype: "landmine", retort: "算了，我不跟你計較，哼。" },
      { id: "neighbor-chen-comparison-010-g", text: "我雖然年終不多，但很會挑橘子啦。", archetype: "backfire", retort: "（她沒聽懂，繼續賣橘子）" },
      { id: "neighbor-chen-comparison-010-h", text: "真的差不少，我還在努力加油……", archetype: "meek", retort: "提升自己？那要不要進修證照？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-011",
    text: "楊太太兒子當律師，收入是你好幾倍吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-011-a", text: "跟他比是差很多，我這行薪水普通……", archetype: "meek", retort: "普通？那要不要考慮轉行？" },
      { id: "neighbor-chen-comparison-011-b", text: "我雖然沒當律師，但很會據理力爭啦。", archetype: "backfire", retort: "……（她曬著太陽，沒理我）" },
      { id: "neighbor-chen-comparison-011-c", text: "收入他賺的，妳的口水是白費的。", archetype: "perfect", retort: "……她乾咳一聲，換話題。" },
      { id: "neighbor-chen-comparison-011-d", text: "律師的事先別提，今天曬太陽真舒服。", archetype: "deflect", retort: "對啊，冬天曬太陽最補。" },
      { id: "neighbor-chen-comparison-011-e", text: "確實差很多，我還在努力累積……", archetype: "meek", retort: "累積？那要努力到什麼時候？" },
      { id: "neighbor-chen-comparison-011-f", text: "妳這麼會算別人收入，很閒厚？", archetype: "landmine", retort: "你這什麼意思，講給你媽聽！" },
      { id: "neighbor-chen-comparison-011-g", text: "比較的事先保密，您今天怎麼有空曬太陽？", archetype: "deflect", retort: "難得有空，出來透透氣。" },
      { id: "neighbor-chen-comparison-011-h", text: "我雖然沒當律師，但很會辯論吃飯選項。", archetype: "backfire", retort: "（她沒聽懂，繼續滑手機）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-012",
    text: "吳太太兒子當機師，出國比你出門還多。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-012-a", text: "我雖然沒常出國，但我很會神遊啦。", archetype: "backfire", retort: "……（老闆修著車，沒理我）" },
      { id: "neighbor-chen-comparison-012-b", text: "跟他比是差很多，我很少有機會出國……", archetype: "meek", retort: "很少？那要不要安排一次旅行？" },
      { id: "neighbor-chen-comparison-012-c", text: "出國的事先別提，這機車行生意真好。", archetype: "deflect", retort: "對啊，過年前大家都來保養。" },
      { id: "neighbor-chen-comparison-012-d", text: "他出國飛的，我的生活也沒停飛。", archetype: "perfect", retort: "呵，妳這張嘴，隨妳講。" },
      { id: "neighbor-chen-comparison-012-e", text: "我雖然沒常出國，但出門買菜也算旅行。", archetype: "backfire", retort: "（她沒聽懂，繼續修車）" },
      { id: "neighbor-chen-comparison-012-f", text: "比較的事先保密，這台機車保養多少錢？", archetype: "deflect", retort: "基本保養八百塊啦。" },
      { id: "neighbor-chen-comparison-012-g", text: "妳這麼羨慕，怎麼不叫妳兒子當機師？", archetype: "landmine", retort: "你欠罵喔，講話這麼衝！" },
      { id: "neighbor-chen-comparison-012-h", text: "確實比較少出國，機會真的不多……", archetype: "meek", retort: "不多？那要不要安排一下假期？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-013",
    text: "隔壁小孩每個禮拜都回家，你呢？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-013-a", text: "回不回家不重要，回去有沒有真心。", archetype: "perfect", retort: "……她乾笑，轉頭跟別人聊天。" },
      { id: "neighbor-chen-comparison-013-b", text: "回家的事先別提，這關東煮湯頭真香。", archetype: "deflect", retort: "對啊，天冷就是要喝這個。" },
      { id: "neighbor-chen-comparison-013-c", text: "確實比較少回家，工作太忙了……", archetype: "meek", retort: "太忙？那要不要多打電話回家？" },
      { id: "neighbor-chen-comparison-013-d", text: "我雖然少回家，但我很會傳貼圖問候啦。", archetype: "backfire", retort: "……（她盛著湯，沒理我）" },
      { id: "neighbor-chen-comparison-013-e", text: "妳每天站門口，是等我還是等八卦？", archetype: "landmine", retort: "……她愣住，狠狠瞪了我一眼。" },
      { id: "neighbor-chen-comparison-013-f", text: "回家的事先保密，這攤黑輪多少錢一支？", archetype: "deflect", retort: "一支十五塊啦。" },
      { id: "neighbor-chen-comparison-013-g", text: "確實比較少，心裡也會愧疚……", archetype: "meek", retort: "愧疚？那要不要安排時間回去？" },
      { id: "neighbor-chen-comparison-013-h", text: "我雖然少回家，但很會視訊陪伴啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續舀湯）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-014",
    text: "隔壁小孩每天運動，你都只滑手機。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-014-a", text: "運動的事先別提，您等垃圾車也辛苦了。", archetype: "deflect", retort: "習慣了啦，天天都要等。" },
      { id: "neighbor-chen-comparison-014-b", text: "滑手機是放鬆，我的運動我自己排。", archetype: "perfect", retort: "呵呵，妳這孩子，嘴巴真利！" },
      { id: "neighbor-chen-comparison-014-c", text: "我運動量是滑手指，一天好幾萬下啦。", archetype: "backfire", retort: "……（她皺眉，沒聽懂）" },
      { id: "neighbor-chen-comparison-014-d", text: "確實比較少運動，最近都比較懶……", archetype: "meek", retort: "懶？那要不要一起去運動？" },
      { id: "neighbor-chen-comparison-014-e", text: "運動的事先保密，垃圾車今天怎麼晚到？", archetype: "deflect", retort: "對啊，可能塞車了。" },
      { id: "neighbor-chen-comparison-014-f", text: "妳連我滑不滑手機都要管，很閒？", archetype: "landmine", retort: "你這什麼態度，白眼狼！" },
      { id: "neighbor-chen-comparison-014-g", text: "我滑手機滑到手指都練出肌肉啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續等垃圾車）" },
      { id: "neighbor-chen-comparison-014-h", text: "確實比較少動，該多注意健康……", archetype: "meek", retort: "注意健康？那要不要開始運動？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-015",
    text: "隔壁小孩很會理財，你的帳單一堆吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-015-a", text: "確實帳單比較多，理財還在學習……", archetype: "meek", retort: "還在學？那要快點學好喔。" },
      { id: "neighbor-chen-comparison-015-b", text: "我理財哲學是先花再說啦哈哈。", archetype: "backfire", retort: "……（她翻著信件，沒理我）" },
      { id: "neighbor-chen-comparison-015-c", text: "帳單多是投資自己，比妳的存摺有趣。", archetype: "perfect", retort: "……她愣了一下，摸摸鼻子。" },
      { id: "neighbor-chen-comparison-015-d", text: "理財的事先別提，信箱塞好多廣告。", archetype: "deflect", retort: "對啊，天天都是傳單。" },
      { id: "neighbor-chen-comparison-015-e", text: "確實不太會理財，還在摸索方法……", archetype: "meek", retort: "摸索？那要不要找書來看？" },
      { id: "neighbor-chen-comparison-015-f", text: "妳連我帳單都看，是想幫我繳嗎？", archetype: "landmine", retort: "好啊你，明年紅包別想拿！" },
      { id: "neighbor-chen-comparison-015-g", text: "帳單的事先保密，這封是社區通知嗎？", archetype: "deflect", retort: "對啊，管理費繳費單。" },
      { id: "neighbor-chen-comparison-015-h", text: "我理財是把錢花在刀口上，刀很多把。", archetype: "backfire", retort: "（她沒聽懂，繼續翻信）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-016",
    text: "隔壁小孩很會做家事，你都靠洗衣店？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-016-a", text: "我是把時間省下來做更重要的事啦。", archetype: "backfire", retort: "……（她摺著衣服，沒理我）" },
      { id: "neighbor-chen-comparison-016-b", text: "確實比較少做家事，工作太忙了……", archetype: "meek", retort: "太忙？那要不要學一點基本的？" },
      { id: "neighbor-chen-comparison-016-c", text: "家事的事先別提，這台烘衣機很好用喔。", archetype: "deflect", retort: "對啊，我也常來用。" },
      { id: "neighbor-chen-comparison-016-d", text: "花錢省時間，效率比家事更值錢。", archetype: "perfect", retort: "喔、喔，是嗎……那先這樣。" },
      { id: "neighbor-chen-comparison-016-e", text: "我把家事外包，這叫善用資源啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續摺衣服）" },
      { id: "neighbor-chen-comparison-016-f", text: "家事的事先保密，這件衣服摺得真整齊。", archetype: "deflect", retort: "這個要練習的啦。" },
      { id: "neighbor-chen-comparison-016-g", text: "妳這麼閒，怎麼不去開洗衣店？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-comparison-016-h", text: "確實不太擅長，還在學習中……", archetype: "meek", retort: "學習中？那要多練習喔。" },
    ],
  },
  {
    id: "neighbor-chen-comparison-017",
    text: "隔壁小孩做事很準時，你常常遲到吧？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-017-a", text: "準時看場合，重要的事我沒遲到過。", archetype: "perfect", retort: "……她假笑，說要去忙了。" },
      { id: "neighbor-chen-comparison-017-b", text: "準時的事先別提，這電梯維修多久好？", archetype: "deflect", retort: "聽說明天就修好了。" },
      { id: "neighbor-chen-comparison-017-c", text: "確實比較常遲到，時間管理不太好……", archetype: "meek", retort: "不好？那要不要早點出門？" },
      { id: "neighbor-chen-comparison-017-d", text: "我遲到是因為在等最佳時機出場啦。", archetype: "backfire", retort: "……（她看著公告，沒理我）" },
      { id: "neighbor-chen-comparison-017-e", text: "妳這麼準時站在這，是打卡喔？", archetype: "landmine", retort: "你這孩子欠教訓，沒大沒小！" },
      { id: "neighbor-chen-comparison-017-f", text: "時間的事先保密，走樓梯也不錯運動。", archetype: "deflect", retort: "對啊，趁機多運動一下。" },
      { id: "neighbor-chen-comparison-017-g", text: "確實常常趕不及，還在改進……", archetype: "meek", retort: "改進？那要不要提早出門？" },
      { id: "neighbor-chen-comparison-017-h", text: "我的準時是遲到界的準時啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續看公告）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-018",
    text: "隔壁小孩口才真好，你怎麼都不太會講？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-018-a", text: "口才的事先別提，您排隊排好久喔。", archetype: "deflect", retort: "對啊，過年前人特別多。" },
      { id: "neighbor-chen-comparison-018-b", text: "話少不代表沒想法，我做的比說的多。", archetype: "perfect", retort: "妳這孩子，講話越來越犀利。" },
      { id: "neighbor-chen-comparison-018-c", text: "我口才是深藏不露，開口會嚇死人啦。", archetype: "backfire", retort: "……（她結帳，沒理我）" },
      { id: "neighbor-chen-comparison-018-d", text: "確實不太會說話，比較內向……", archetype: "meek", retort: "內向？那要不要多練習表達？" },
      { id: "neighbor-chen-comparison-018-e", text: "口才的事先保密，購物車東西好多喔。", archetype: "deflect", retort: "對啊，過年要買齊全。" },
      { id: "neighbor-chen-comparison-018-f", text: "妳這麼會講，怎麼不去選里長？", archetype: "landmine", retort: "你哪壺不開提哪壺，夭壽喔！" },
      { id: "neighbor-chen-comparison-018-g", text: "我口才不好，但我文筆好，可以寫信啦。", archetype: "backfire", retort: "（她沒聽懂，繼續結帳）" },
      { id: "neighbor-chen-comparison-018-h", text: "確實比較不擅長表達，還在練習……", archetype: "meek", retort: "練習？那要不要多跟人聊天？" },
    ],
  },
  {
    id: "neighbor-chen-comparison-019",
    text: "隔壁小孩見人都問好，你怎麼悶不吭聲？",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-019-a", text: "確實比較安靜，不太會主動打招呼……", archetype: "meek", retort: "不主動？那要不要練習開口？" },
      { id: "neighbor-chen-comparison-019-b", text: "我打招呼是用眼神，比較高深啦哈哈。", archetype: "backfire", retort: "……（她分類著回收，沒理我）" },
      { id: "neighbor-chen-comparison-019-c", text: "安靜不是沒禮貌，我心裡尊重大家。", archetype: "perfect", retort: "……她轉頭找別人聊，尷尬。" },
      { id: "neighbor-chen-comparison-019-d", text: "禮貌的事先別提，這資源分類做得真仔細。", archetype: "deflect", retort: "社區規定要分類清楚。" },
      { id: "neighbor-chen-comparison-019-e", text: "確實比較內向，還在練習主動……", archetype: "meek", retort: "練習主動？那要不要試試看？" },
      { id: "neighbor-chen-comparison-019-f", text: "妳每天在這問好，是巡邏還是查勤？", archetype: "landmine", retort: "好，你行，明年不用理你！" },
      { id: "neighbor-chen-comparison-019-g", text: "禮貌的事先保密，這瓶罐要壓扁再丟嗎？", archetype: "deflect", retort: "對啊，比較省空間。" },
      { id: "neighbor-chen-comparison-019-h", text: "我打招呼是心電感應式的啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續分類）" },
    ],
  },
  {
    id: "neighbor-chen-comparison-020",
    text: "隔壁小孩每天健身，你的腳踏車都生鏽了。",
    topic: "comparison",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-comparison-020-a", text: "生鏽是一種復古美學啦哈哈。", archetype: "backfire", retort: "……（她看著腳踏車，沒理我）" },
      { id: "neighbor-chen-comparison-020-b", text: "確實比較少運動，最近都提不起勁……", archetype: "meek", retort: "提不起勁？那要不要找伴一起運動？" },
      { id: "neighbor-chen-comparison-020-c", text: "健身的事先別提，幫我看一下車好嗎？", archetype: "deflect", retort: "好啊，鏈條有點鬆了。" },
      { id: "neighbor-chen-comparison-020-d", text: "健身各有方式，我保持健康不靠妳認證。", archetype: "perfect", retort: "算了算了，不跟妳計較。" },
      { id: "neighbor-chen-comparison-020-e", text: "我的健身是意志力鍛鍊，看不見但很強啦。", archetype: "backfire", retort: "（她沒聽懂，繼續看腳踏車）" },
      { id: "neighbor-chen-comparison-020-f", text: "運動的事先保密，今天天氣真適合騎車。", archetype: "deflect", retort: "對啊，趁機出去走走。" },
      { id: "neighbor-chen-comparison-020-g", text: "妳連我腳踏車生鏽都注意，很閒？", archetype: "landmine", retort: "你這什麼話，虧我平常疼你！" },
      { id: "neighbor-chen-comparison-020-h", text: "確實太少運動了，該多注意健康……", archetype: "meek", retort: "注意健康？那要不要開始騎車？" },
    ],
  },
] satisfies Question[];
