// situations: 021 曬棉被, 022 巷口水果攤, 023 過年前理髮店, 024 郵局排隊巧遇,
// 025 診所候診室, 026 巷口麵包店, 027 騎車經過被叫住, 028 巷口彩券行,
// 029 加油站巧遇, 030 巷口五金行, 031 巷口花店買年花, 032 社區跨年活動,
// 033 除夕前互串門子, 034 初一拜年互訪, 035 社區群組發紅包照片,
// 036 陽台曬臘肉香腸, 037 巷口賣春聯攤子
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-marriage-021",
    text: "聽說你們決定當頂客族，不生小孩？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-021-a", text: "生不生的事先別提，棉被曬得真蓬鬆。", archetype: "deflect", retort: "對啊，太陽好曬起來特別香。" },
      { id: "neighbor-chen-marriage-021-b", text: "生不生我們決定，不用妳來投票。", archetype: "perfect", retort: "……她拍著棉被，語塞。" },
      { id: "neighbor-chen-marriage-021-c", text: "我們決定把小孩換成寵物，好照顧。", archetype: "backfire", retort: "……（她拍著棉被，沒理我）" },
      { id: "neighbor-chen-marriage-021-d", text: "還在討論，還沒有最後決定……", archetype: "meek", retort: "沒決定？那要不要早點想清楚？" },
      { id: "neighbor-chen-marriage-021-e", text: "這件事先保密，棉被套花色好漂亮。", archetype: "deflect", retort: "這是新買的過年款式。" },
      { id: "neighbor-chen-marriage-021-f", text: "妳不是我媽，管我們生不生幹嘛？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-021-g", text: "頂客族生活比追劇還精彩啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續拍打棉被）" },
      { id: "neighbor-chen-marriage-021-h", text: "確實還沒決定，怕做錯選擇……", archetype: "meek", retort: "怕做錯？那要不要多討論？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-022",
    text: "你女朋友比你大好幾歲？處得來嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-022-a", text: "年紀是有差，但相處很自在……", archetype: "meek", retort: "自在？那以後會不會有代溝？" },
      { id: "neighbor-chen-marriage-022-b", text: "姊弟戀讓我感覺被照顧得很好啦。", archetype: "backfire", retort: "……（她挑著水果，沒理我）" },
      { id: "neighbor-chen-marriage-022-c", text: "年紀不是問題，妳的偏見才是問題。", archetype: "perfect", retort: "……她挑著水果，語塞。" },
      { id: "neighbor-chen-marriage-022-d", text: "年紀的事先別提，這攤芭樂好脆喔。", archetype: "deflect", retort: "對啊，早上剛採的。" },
      { id: "neighbor-chen-marriage-022-e", text: "確實有點差距，還在互相適應……", archetype: "meek", retort: "適應？那要不要多溝通觀念？" },
      { id: "neighbor-chen-marriage-022-f", text: "妳連我們年紀差都算，很閒喔？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-022-g", text: "年紀差的事先保密，芭樂多少錢一斤？", archetype: "deflect", retort: "一斤三十塊啦，很划算。" },
      { id: "neighbor-chen-marriage-022-h", text: "姊弟戀讓我覺得自己回到十八歲啦。", archetype: "backfire", retort: "（她沒聽懂，繼續挑水果）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-023",
    text: "聽說你離過一次婚，這次要謹慎點喔。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-023-a", text: "離過婚讓我升級成愛情專家啦哈哈。", archetype: "backfire", retort: "……（理髮師剪到一半，尷尬）" },
      { id: "neighbor-chen-marriage-023-b", text: "是啦，上次不太合適，這次更謹慎……", archetype: "meek", retort: "更謹慎？那有想清楚怎麼選嗎？" },
      { id: "neighbor-chen-marriage-023-c", text: "這件事先別提，這次剪的髮型真好看。", archetype: "deflect", retort: "謝謝，設計師手藝不錯。" },
      { id: "neighbor-chen-marriage-023-d", text: "離過婚是我的事，妳的建議我心領。", archetype: "perfect", retort: "……理髮師剪到一半，尷尬。" },
      { id: "neighbor-chen-marriage-023-e", text: "我把上次的經驗寫成攻略了啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續等剪髮）" },
      { id: "neighbor-chen-marriage-023-f", text: "感情的事先保密，這家理髮店生意真好。", archetype: "deflect", retort: "對啊，過年前大家都來剪。" },
      { id: "neighbor-chen-marriage-023-g", text: "妳連我離婚都要提，很缺話題？", archetype: "landmine", retort: "我關心你才問，講話這麼衝！" },
      { id: "neighbor-chen-marriage-023-h", text: "確實學到很多，這次會更小心……", archetype: "meek", retort: "更小心？那要不要多觀察一陣子？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-024",
    text: "聽說你們要簽婚前協議？這樣不浪漫吧？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-024-a", text: "協議是保障，浪不浪漫妳說了不算。", archetype: "perfect", retort: "……她拿著包裹，語塞。" },
      { id: "neighbor-chen-marriage-024-b", text: "協議的事先別提，您排隊寄的是什麼？", archetype: "deflect", retort: "寄年節禮盒給親戚啦。" },
      { id: "neighbor-chen-marriage-024-c", text: "還在討論條件，有點難達成共識……", archetype: "meek", retort: "難達成？那要不要找律師幫忙？" },
      { id: "neighbor-chen-marriage-024-d", text: "婚前協議我打算用蓋章換蓋章啦。", archetype: "backfire", retort: "……（她拿著包裹，沒理我）" },
      { id: "neighbor-chen-marriage-024-e", text: "妳連我簽什麼協議都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-024-f", text: "協議的事先保密，郵局今天人好多喔。", archetype: "deflect", retort: "對啊，過年前都在寄東西。" },
      { id: "neighbor-chen-marriage-024-g", text: "確實有點複雜，還在溝通中……", archetype: "meek", retort: "溝通中？那要不要找長輩調解？" },
      { id: "neighbor-chen-marriage-024-h", text: "婚前協議我打算寫成情書格式啦。", archetype: "backfire", retort: "（她沒聽懂，繼續排隊）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-025",
    text: "現在結婚一場要花多少？聽說貴得嚇人。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-025-a", text: "花費的事先別提，您來看診沒事吧？", archetype: "deflect", retort: "沒事，例行檢查而已。" },
      { id: "neighbor-chen-marriage-025-b", text: "貴不貴是我的帳，不用妳來審核。", archetype: "perfect", retort: "……她坐著等叫號，語塞。" },
      { id: "neighbor-chen-marriage-025-c", text: "結婚花費高，但我打算信用卡分期。", archetype: "backfire", retort: "……（她坐著等叫號，沒理我）" },
      { id: "neighbor-chen-marriage-025-d", text: "確實很貴，我們預算有點吃緊……", archetype: "meek", retort: "吃緊？那要不要辦簡單一點？" },
      { id: "neighbor-chen-marriage-025-e", text: "預算的事先保密，候診室今天人好多。", archetype: "deflect", retort: "對啊，過年前大家都來看病。" },
      { id: "neighbor-chen-marriage-025-f", text: "妳連我花多少都要算，妳很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-025-g", text: "結婚花費高沒關係，我打算眾籌啦。", archetype: "backfire", retort: "（她沒聽懂，繼續等叫號）" },
      { id: "neighbor-chen-marriage-025-h", text: "真的很貴，還在想辦法省……", archetype: "meek", retort: "省？那要不要簡化流程？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-026",
    text: "你男朋友工作穩定嗎？可以養家嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-026-a", text: "工作還算穩定，只是薪水普通……", archetype: "meek", retort: "普通？那以後生活夠用嗎？" },
      { id: "neighbor-chen-marriage-026-b", text: "他工作不穩，但愛我很穩啦哈哈。", archetype: "backfire", retort: "……（她挑著麵包，沒理我）" },
      { id: "neighbor-chen-marriage-026-c", text: "穩不穩是我倆的事，不是妳的考核。", archetype: "perfect", retort: "……她挑著麵包，語塞。" },
      { id: "neighbor-chen-marriage-026-d", text: "工作的事先別提，新口味麵包真好吃。", archetype: "deflect", retort: "對啊，我也買了兩個。" },
      { id: "neighbor-chen-marriage-026-e", text: "說實話還在打拼，收入不算高……", archetype: "meek", retort: "不高？那要不要一起想辦法？" },
      { id: "neighbor-chen-marriage-026-f", text: "妳連我男朋友工作都要查，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-026-g", text: "工作的事先保密，麵包多少錢一個？", archetype: "deflect", retort: "一個五十塊，不便宜。" },
      { id: "neighbor-chen-marriage-026-h", text: "他工作不穩，但創意超穩啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續挑麵包）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-027",
    text: "聽說你跟同事在一起了？辦公室戀情喔？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-027-a", text: "辦公室戀情讓我上班變度假啦哈哈。", archetype: "backfire", retort: "……（她揮手叫我停車，沒理我）" },
      { id: "neighbor-chen-marriage-027-b", text: "是啦，我們決定低調一點……", archetype: "meek", retort: "低調？那怕被主管知道嗎？" },
      { id: "neighbor-chen-marriage-027-c", text: "感情的事先別提，您叫我做什麼？", archetype: "deflect", retort: "沒事，剛好看到跟你打招呼。" },
      { id: "neighbor-chen-marriage-027-d", text: "同事變情人是緣分，妳消息倒是很快。", archetype: "perfect", retort: "……她笑了一下，語塞。" },
      { id: "neighbor-chen-marriage-027-e", text: "辦公室戀情讓我天天準時打卡見他。", archetype: "backfire", retort: "（她沒聽懂，笑了一下）" },
      { id: "neighbor-chen-marriage-027-f", text: "感情的事先保密，您今天要去哪裡？", archetype: "deflect", retort: "去買點東西而已。" },
      { id: "neighbor-chen-marriage-027-g", text: "妳怎麼連這個都知道，很閒喔？", archetype: "landmine", retort: "社區消息傳得快，你態度差什麼！" },
      { id: "neighbor-chen-marriage-027-h", text: "確實在一起了，還在適應狀況……", archetype: "meek", retort: "適應狀況？那要不要考慮換部門？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-028",
    text: "聽說你相親開的條件很高？挑成這樣？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-028-a", text: "條件高，因為我可不是誰都能將就。", archetype: "perfect", retort: "……她拿著彩券，語塞。" },
      { id: "neighbor-chen-marriage-028-b", text: "條件的事先別提，今天手氣如何？", archetype: "deflect", retort: "還沒開獎，等一下看看。" },
      { id: "neighbor-chen-marriage-028-c", text: "可能真的開太高了，還在調整……", archetype: "meek", retort: "調整？那要不要降低一點？" },
      { id: "neighbor-chen-marriage-028-d", text: "我的條件跟樂透中獎機率差不多啦。", archetype: "backfire", retort: "……（她拿著彩券，沒理我）" },
      { id: "neighbor-chen-marriage-028-e", text: "妳連我開什麼條件都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-028-f", text: "條件的事先保密，這期獎金好高喔。", archetype: "deflect", retort: "對啊，聽說破紀錄了。" },
      { id: "neighbor-chen-marriage-028-g", text: "確實條件開比較高，還在反省……", archetype: "meek", retort: "反省？那要不要重新想想？" },
      { id: "neighbor-chen-marriage-028-h", text: "條件高沒關係，我用刮刮樂式選人啦。", archetype: "backfire", retort: "（她沒聽懂，繼續看彩券）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-029",
    text: "交往這麼久了，怎麼還沒求婚？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-029-a", text: "求婚的事先別提，您車加滿油了嗎？", archetype: "deflect", retort: "快好了，等一下就走。" },
      { id: "neighbor-chen-marriage-029-b", text: "求婚急不得，妳比我男友還心急。", archetype: "perfect", retort: "……她看著油錶，語塞。" },
      { id: "neighbor-chen-marriage-029-c", text: "求婚我打算辦煙火秀，還在存錢啦。", archetype: "backfire", retort: "……（她看著油錶，沒理我）" },
      { id: "neighbor-chen-marriage-029-d", text: "老實說也在等，有點著急……", archetype: "meek", retort: "著急？那要不要主動問問看？" },
      { id: "neighbor-chen-marriage-029-e", text: "求婚的事先保密，油價今天調漲了嗎？", archetype: "deflect", retort: "對啊，漲了一塊多。" },
      { id: "neighbor-chen-marriage-029-f", text: "妳連我們求不求婚都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-029-g", text: "求婚我打算用空拍機拍出來啦。", archetype: "backfire", retort: "（她沒聽懂，繼續加油）" },
      { id: "neighbor-chen-marriage-029-h", text: "真的還沒求婚，我也有點困惑……", archetype: "meek", retort: "困惑？那要不要開口談談？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-030",
    text: "伴娘伴郎找好了嗎？聽說很難選。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-030-a", text: "還在挑選，怕漏掉重要的朋友……", archetype: "meek", retort: "漏掉？那要不要多問問朋友？" },
      { id: "neighbor-chen-marriage-030-b", text: "伴娘伴郎我打算辦選拔賽啦哈哈。", archetype: "backfire", retort: "……（她挑著五金零件，沒理我）" },
      { id: "neighbor-chen-marriage-030-c", text: "人選還沒定，但輪不到妳來選。", archetype: "perfect", retort: "……她挑著五金零件，語塞。" },
      { id: "neighbor-chen-marriage-030-d", text: "伴娘的事先別提，這家工具好齊全。", archetype: "deflect", retort: "對啊，開了二十年了。" },
      { id: "neighbor-chen-marriage-030-e", text: "確實很難決定，怕得罪人……", archetype: "meek", retort: "得罪人？那要不要私下問清楚？" },
      { id: "neighbor-chen-marriage-030-f", text: "妳想當伴娘，是想拿紅包吧？", archetype: "landmine", retort: "你這孩子亂講什麼，沒禮貌！" },
      { id: "neighbor-chen-marriage-030-g", text: "人選的事先保密，螺絲起子多少錢？", archetype: "deflect", retort: "一支五十塊啦。" },
      { id: "neighbor-chen-marriage-030-h", text: "伴娘伴郎我打算用抽籤決定啦。", archetype: "backfire", retort: "（她沒聽懂，繼續逛五金行）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-031",
    text: "什麼時候帶男女朋友回家給爸媽看？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-031-a", text: "帶回家前我要先幫他惡補家規啦。", archetype: "backfire", retort: "……（她挑著年花，沒理我）" },
      { id: "neighbor-chen-marriage-031-b", text: "還在找適合的時機，有點緊張……", archetype: "meek", retort: "緊張？那要不要先讓爸媽有心理準備？" },
      { id: "neighbor-chen-marriage-031-c", text: "介紹的事先別提，這盆蘭花好漂亮。", archetype: "deflect", retort: "對啊，過年就要買這個。" },
      { id: "neighbor-chen-marriage-031-d", text: "時機到了自然帶回家，不用妳排班表。", archetype: "perfect", retort: "……她挑著年花，語塞。" },
      { id: "neighbor-chen-marriage-031-e", text: "帶回家我要先幫他排練台詞啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續挑花）" },
      { id: "neighbor-chen-marriage-031-f", text: "介紹的事先保密，這盆年橘要多少錢？", archetype: "deflect", retort: "這盆算你便宜一點。" },
      { id: "neighbor-chen-marriage-031-g", text: "妳不是我媽，管我帶誰回家幹嘛？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-031-h", text: "還沒準備好，怕爸媽會有意見……", archetype: "meek", retort: "有意見？那要不要先溝通一下？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-032",
    text: "求婚戒指買了沒？聽說要看款式。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-032-a", text: "戒指款式不重要，妳的鑑定我不需要。", archetype: "perfect", retort: "……她看著煙火，語塞。" },
      { id: "neighbor-chen-marriage-032-b", text: "戒指的事先別提，今晚活動好熱鬧。", archetype: "deflect", retort: "對啊，社區辦得越來越用心。" },
      { id: "neighbor-chen-marriage-032-c", text: "還在挑選，預算有點超出範圍……", archetype: "meek", retort: "超出？那要不要換個款式？" },
      { id: "neighbor-chen-marriage-032-d", text: "戒指我打算用資源回收自己做啦。", archetype: "backfire", retort: "……（她看著煙火，沒理我）" },
      { id: "neighbor-chen-marriage-032-e", text: "妳連我戒指買什麼都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-032-f", text: "戒指的事先保密，這場活動有摸彩嗎？", archetype: "deflect", retort: "有啊，等一下就開始。" },
      { id: "neighbor-chen-marriage-032-g", text: "還在猶豫款式，怕她不喜歡……", archetype: "meek", retort: "不喜歡？那要不要先問問她？" },
      { id: "neighbor-chen-marriage-032-h", text: "戒指我打算用扭蛋機抽一個啦。", archetype: "backfire", retort: "（她沒聽懂，繼續看表演）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-033",
    text: "上次介紹的對象你怎麼都不理人家？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-033-a", text: "那件事先別提，您家裝飾得真喜氣。", archetype: "deflect", retort: "謝謝誇獎，我弄了一整天。" },
      { id: "neighbor-chen-marriage-033-b", text: "感覺不對別勉強，妳的面子不歸我管。", archetype: "perfect", retort: "……她一臉狐疑，語塞。" },
      { id: "neighbor-chen-marriage-033-c", text: "我不是不理，是緊張句子講不出來。", archetype: "backfire", retort: "……（她一臉狐疑，沒接話）" },
      { id: "neighbor-chen-marriage-033-d", text: "老實說感覺不太合，不知道怎麼開口……", archetype: "meek", retort: "不合？那要不要再多聊聊看？" },
      { id: "neighbor-chen-marriage-033-e", text: "相親的事先保密，春聯是自己寫的？", archetype: "deflect", retort: "對啊，我孫子寫的。" },
      { id: "neighbor-chen-marriage-033-f", text: "妳這麼失望，是想收介紹費吧？", archetype: "landmine", retort: "你這孩子怎麼講這種話！" },
      { id: "neighbor-chen-marriage-033-g", text: "我不是拒絕，是在醞釀完美的回覆啦。", archetype: "backfire", retort: "（她沒聽懂，轉頭忙別的事）" },
      { id: "neighbor-chen-marriage-033-h", text: "確實沒有感覺，怕辜負您的好意……", archetype: "meek", retort: "辜負？那要不要再給機會？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-034",
    text: "婚禮日期看農民曆了嗎？黃道吉日重要。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-034-a", text: "還沒看，不太懂怎麼挑日子……", archetype: "meek", retort: "不懂？那要不要請人幫忙看？" },
      { id: "neighbor-chen-marriage-034-b", text: "我打算隨便選一天，反正天天吉利。", archetype: "backfire", retort: "……（她倒抽一口氣，沒接話）" },
      { id: "neighbor-chen-marriage-034-c", text: "黃道吉日重要，但天天用心更重要。", archetype: "perfect", retort: "……她倒抽一口氣，語塞。" },
      { id: "neighbor-chen-marriage-034-d", text: "日期的事先別提，新年快樂發大財！", archetype: "deflect", retort: "哎唷，你也是，恭喜發財！" },
      { id: "neighbor-chen-marriage-034-e", text: "還在請人看，怕挑錯日子不吉利……", archetype: "meek", retort: "不吉利？那要慎重一點喔。" },
      { id: "neighbor-chen-marriage-034-f", text: "妳連我哪天結婚都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-034-g", text: "日期的事先保密，紅包準備好了嗎？", archetype: "deflect", retort: "準備好了，等一下就發。" },
      { id: "neighbor-chen-marriage-034-h", text: "我打算選農民曆說不宜嫁娶那天啦。", archetype: "backfire", retort: "（她臉色一沉，沒說話）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-035",
    text: "結婚後要冠夫姓嗎？現在人還會這樣？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-035-a", text: "冠夫姓不夠，我打算連名帶姓合體啦。", archetype: "backfire", retort: "……（群組沒人回應）" },
      { id: "neighbor-chen-marriage-035-b", text: "還沒決定，兩邊都有考慮……", archetype: "meek", retort: "還沒決定？那要不要早點商量？" },
      { id: "neighbor-chen-marriage-035-c", text: "冠姓的事先別提，紅包照片包得好厚。", archetype: "deflect", retort: "哈，過年就是要包厚一點。" },
      { id: "neighbor-chen-marriage-035-d", text: "冠不冠姓我決定，不勞妳來投票。", archetype: "perfect", retort: "……群組沒人回應。" },
      { id: "neighbor-chen-marriage-035-e", text: "我打算兩個姓氏輪流用，比較公平啦。", archetype: "backfire", retort: "（群組已讀無人回應）" },
      { id: "neighbor-chen-marriage-035-f", text: "冠姓的事先保密，這紅包是給誰的？", archetype: "deflect", retort: "是給孫子的啦。" },
      { id: "neighbor-chen-marriage-035-g", text: "妳連我冠不冠姓都要管，很閒？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-035-h", text: "還在考慮，怕長輩會有意見……", archetype: "meek", retort: "有意見？那要不要先問問看？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-036",
    text: "為了男朋友要搬去外縣市？值得嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-036-a", text: "值不值得我自己衡量，不用妳來計算。", archetype: "perfect", retort: "……她翻著香腸，語塞。" },
      { id: "neighbor-chen-marriage-036-b", text: "搬家的事先別提，香腸曬得真香。", archetype: "deflect", retort: "對啊，過年就是要曬臘肉。" },
      { id: "neighbor-chen-marriage-036-c", text: "還在考慮，捨不得離開熟悉的地方……", archetype: "meek", retort: "捨不得？那要不要再想清楚？" },
      { id: "neighbor-chen-marriage-036-d", text: "搬家我打算把房間打包空運過去啦。", archetype: "backfire", retort: "……（她翻著香腸，沒理我）" },
      { id: "neighbor-chen-marriage-036-e", text: "妳連我搬去哪都要管，很閒喔？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼！" },
      { id: "neighbor-chen-marriage-036-f", text: "搬家的事先保密，臘肉是自己灌的嗎？", archetype: "deflect", retort: "對啊，每年都自己灌。" },
      { id: "neighbor-chen-marriage-036-g", text: "確實有點捨不得，但想為感情努力……", archetype: "meek", retort: "努力？那新工作找好了嗎？" },
      { id: "neighbor-chen-marriage-036-h", text: "搬家後我打算把陽台也搬過去啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續翻香腸）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-037",
    text: "要不要參加聯誼？我幫你報名了。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-037-a", text: "聯誼的事先別提，這攤春聯賣得真好。", archetype: "deflect", retort: "對啊，過年生意特別好。" },
      { id: "neighbor-chen-marriage-037-b", text: "謝謝報名，但緣分不是妳能安排的。", archetype: "perfect", retort: "……她愣住，語塞。" },
      { id: "neighbor-chen-marriage-037-c", text: "聯誼我打算穿騎士服去，比較顯眼。", archetype: "backfire", retort: "……（她愣住，沒接話）" },
      { id: "neighbor-chen-marriage-037-d", text: "好啊，但有點緊張不知道怎麼聊天……", archetype: "meek", retort: "緊張？那要不要先練習開場白？" },
      { id: "neighbor-chen-marriage-037-e", text: "聯誼的事先保密，這副春聯是您寫的？", archetype: "deflect", retort: "不是啦，是印的。" },
      { id: "neighbor-chen-marriage-037-f", text: "妳幫我報名，是想收仲介費嗎？", archetype: "landmine", retort: "你這孩子講話怎麼這樣，沒禮貌！" },
      { id: "neighbor-chen-marriage-037-g", text: "聯誼我打算全場發名片自我介紹啦。", archetype: "backfire", retort: "（她沒聽懂，繼續賣春聯）" },
      { id: "neighbor-chen-marriage-037-h", text: "會去看看啦，但期待不會太高……", archetype: "meek", retort: "不會太高？那要不要調整心態？" },
    ],
  },
] satisfies Question[];
