// situations: 021 曬棉被, 022 巷口水果攤, 023 過年前理髮店, 024 郵局排隊巧遇,
// 025 診所候診室, 026 巷口麵包店, 027 騎車經過被叫住, 028 巷口彩券行,
// 029 加油站巧遇, 030 巷口五金行, 031 巷口花店買年花, 032 社區跨年活動,
// 033 除夕前互串門子, 034 初一拜年互訪, 035 社區群組發紅包照片,
// 036 陽台曬臘肉香腸, 037 巷口賣春聯攤子
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-marriage-021",
    text: "聽說你們決定當頂客族，不生小孩？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-021-a", text: "生不生先別提，笑死，棉被曬得真蓬鬆。", archetype: "deflect", retort: "對啊，曬起來特別香啦。" },
      { id: "neighbor-chen-marriage-021-b", text: "幹，生不生我決定，輪不到妳投票。", archetype: "perfect", retort: "……她拍著棉被，幹，你嘴巴真賤！" },
      { id: "neighbor-chen-marriage-021-c", text: "我們決定不生，他媽的省紅包錢。", archetype: "backfire", retort: "……（她拍著棉被，沒理我）" },
      { id: "neighbor-chen-marriage-021-d", text: "還在討論，幹……還沒決定啦……", archetype: "meek", retort: "沒決定？那要不要早點想清楚？" },
      { id: "neighbor-chen-marriage-021-e", text: "這件先保密，棉被套花色好漂亮。", archetype: "deflect", retort: "這是新款式，過年限定的。" },
      { id: "neighbor-chen-marriage-021-f", text: "幹，生不生小孩關妳屁事，老太婆？", archetype: "landmine", retort: "你他媽的給我滾，沒大沒小！" },
      { id: "neighbor-chen-marriage-021-g", text: "頂客族生活比追劇精彩啦，幹好爽。", archetype: "backfire", retort: "……（她沒聽懂，繼續拍棉被）" },
      { id: "neighbor-chen-marriage-021-h", text: "確實還沒決定，靠……怕做錯選擇……", archetype: "meek", retort: "怕做錯？那要不要多討論？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-022",
    text: "你女朋友比你大好幾歲？處得來嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-022-a", text: "年紀是有差，幹……但相處很自在……", archetype: "meek", retort: "自在？那以後會不會有代溝？" },
      { id: "neighbor-chen-marriage-022-b", text: "姊弟戀讓我覺得被照顧，靠北爽。", archetype: "backfire", retort: "……（她挑著水果，沒理我）" },
      { id: "neighbor-chen-marriage-022-c", text: "靠北，年紀不是問題，妳的偏見才是。", archetype: "perfect", retort: "……她挑著水果，幹，你很白目！" },
      { id: "neighbor-chen-marriage-022-d", text: "年紀先別提，笑死，這攤芭樂好脆。", archetype: "deflect", retort: "早上剛採的啦。" },
      { id: "neighbor-chen-marriage-022-e", text: "確實有差距，靠……還在互相適應……", archetype: "meek", retort: "適應？那要不要多溝通？" },
      { id: "neighbor-chen-marriage-022-f", text: "幹，妳連年紀都要算，老東西很閒喔？", archetype: "landmine", retort: "幹，你這什麼態度，欠揍！" },
      { id: "neighbor-chen-marriage-022-g", text: "先保密，芭樂多少錢一斤？笑死。", archetype: "deflect", retort: "一斤三十塊，很划算。" },
      { id: "neighbor-chen-marriage-022-h", text: "姊弟戀讓我覺得自己回到十八歲，機掰讚。", archetype: "backfire", retort: "（她沒聽懂，繼續挑水果）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-023",
    text: "聽說你離過一次婚，這次要謹慎點喔。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-023-a", text: "離過婚讓我升級愛情專家，去你的猛。", archetype: "backfire", retort: "……（理髮師剪到一半，尷尬）" },
      { id: "neighbor-chen-marriage-023-b", text: "是啦，幹……上次不合適，這次謹慎……", archetype: "meek", retort: "更謹慎？那有想清楚嗎？" },
      { id: "neighbor-chen-marriage-023-c", text: "這件先別提，笑死，這髮型真好看。", archetype: "deflect", retort: "謝謝，設計師手藝不錯。" },
      { id: "neighbor-chen-marriage-023-d", text: "他媽的，離過婚是我的事，妳少管。", archetype: "perfect", retort: "……理髮師剪到一半，他媽的，沒禮貌！" },
      { id: "neighbor-chen-marriage-023-e", text: "我把離婚經驗寫成攻略了，去死啦暢銷。", archetype: "backfire", retort: "（她沒聽懂，繼續等剪髮）" },
      { id: "neighbor-chen-marriage-023-f", text: "這件先保密，靠，這家店生意真好。", archetype: "deflect", retort: "過年前大家都來剪啦。" },
      { id: "neighbor-chen-marriage-023-g", text: "他媽的，死老太婆，我離婚關妳屁事？", archetype: "landmine", retort: "去你的，沒大沒小，欠罵！" },
      { id: "neighbor-chen-marriage-023-h", text: "確實學到很多，幹……這次會更小心……", archetype: "meek", retort: "更小心？那要不要多觀察？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-024",
    text: "聽說你們要簽婚前協議？這樣不浪漫吧？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-024-a", text: "機掰，協議是保障，浪不浪漫妳說了不算。", archetype: "perfect", retort: "……她拿著包裹，機掰，你這什麼嘴！" },
      { id: "neighbor-chen-marriage-024-b", text: "這件先別提，笑死，妳排隊寄什麼？", archetype: "deflect", retort: "寄年節禮盒給親戚啦。" },
      { id: "neighbor-chen-marriage-024-c", text: "還在討論條件，幹……有點難達成共識……", archetype: "meek", retort: "難達成？那要不要找律師？" },
      { id: "neighbor-chen-marriage-024-d", text: "婚前協議我打算蓋章換蓋章，靠杯浪漫。", archetype: "backfire", retort: "……（她拿著包裹，沒理我）" },
      { id: "neighbor-chen-marriage-024-e", text: "去你的，老不死，我簽什麼協議關妳屁事？", archetype: "landmine", retort: "靠北，你皮在癢，找罵是不是！" },
      { id: "neighbor-chen-marriage-024-f", text: "這件先保密，靠，郵局今天人好多。", archetype: "deflect", retort: "過年前都在寄東西啦。" },
      { id: "neighbor-chen-marriage-024-g", text: "確實有點複雜，靠……還在溝通中……", archetype: "meek", retort: "溝通中？那要不要找長輩調解？" },
      { id: "neighbor-chen-marriage-024-h", text: "婚前協議我打算寫成情書，幹你娘咧太肉麻。", archetype: "backfire", retort: "（她沒聽懂，繼續排隊）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-025",
    text: "現在結婚一場要花多少？聽說貴得嚇人。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-025-a", text: "花費先別提，笑死，妳來看診沒事吧？", archetype: "deflect", retort: "沒事，例行檢查而已。" },
      { id: "neighbor-chen-marriage-025-b", text: "去你的，貴不貴是我的帳，不用妳審核。", archetype: "perfect", retort: "……她坐著等叫號，去你的，嘴真利！" },
      { id: "neighbor-chen-marriage-025-c", text: "結婚花費高，但我打算刷卡分期，他媽的爽。", archetype: "backfire", retort: "……（她坐著等叫號，沒理我）" },
      { id: "neighbor-chen-marriage-025-d", text: "確實很貴，幹……我們預算有點吃緊……", archetype: "meek", retort: "吃緊？那要不要辦簡單一點？" },
      { id: "neighbor-chen-marriage-025-e", text: "預算先保密，靠，候診室今天人好多。", archetype: "deflect", retort: "過年前大家都來看病啦。" },
      { id: "neighbor-chen-marriage-025-f", text: "幹，妳算我花多少，老太婆很閒？", archetype: "landmine", retort: "你他媽的講話這麼衝，欠罵！" },
      { id: "neighbor-chen-marriage-025-g", text: "結婚花費高沒關係，我打算眾籌，幹好省。", archetype: "backfire", retort: "（她沒聽懂，繼續等叫號）" },
      { id: "neighbor-chen-marriage-025-h", text: "真的很貴，靠……還在想辦法省……", archetype: "meek", retort: "省？那要不要簡化流程？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-026",
    text: "你男朋友工作穩定嗎？可以養家嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-026-a", text: "工作還算穩定，幹……只是薪水普通……", archetype: "meek", retort: "普通？那以後生活夠用嗎？" },
      { id: "neighbor-chen-marriage-026-b", text: "他工作不穩，但愛我很穩，靠北浪漫。", archetype: "backfire", retort: "……（她挑著麵包，沒理我）" },
      { id: "neighbor-chen-marriage-026-c", text: "幹，穩不穩是我倆的事，不是妳的考核。", archetype: "perfect", retort: "……她挑著麵包，幹，你這什麼嘴！" },
      { id: "neighbor-chen-marriage-026-d", text: "工作先別提，笑死，新口味麵包真好吃。", archetype: "deflect", retort: "對啊，我也買了兩個。" },
      { id: "neighbor-chen-marriage-026-e", text: "說實話還在打拼，靠……收入不算高……", archetype: "meek", retort: "不高？那要不要一起想辦法？" },
      { id: "neighbor-chen-marriage-026-f", text: "機掰，老東西，我男友工作關妳屁事？", archetype: "landmine", retort: "你他媽的白眼狼，沒良心！" },
      { id: "neighbor-chen-marriage-026-g", text: "先保密，靠，麵包多少錢一個？", archetype: "deflect", retort: "一個五十塊，不便宜。" },
      { id: "neighbor-chen-marriage-026-h", text: "他工作不穩，但創意超穩，機掰厲害。", archetype: "backfire", retort: "（她沒聽懂，繼續挑麵包）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-027",
    text: "聽說你跟同事在一起了？辦公室戀情喔？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-027-a", text: "辦公室戀情讓我上班變度假，去你的爽。", archetype: "backfire", retort: "……（她揮手叫我停車，沒理我）" },
      { id: "neighbor-chen-marriage-027-b", text: "是啦，幹……我們決定低調一點……", archetype: "meek", retort: "低調？那怕被主管知道嗎？" },
      { id: "neighbor-chen-marriage-027-c", text: "感情先別提，笑死，妳叫我做什麼？", archetype: "deflect", retort: "沒事，剛好看到跟你打招呼。" },
      { id: "neighbor-chen-marriage-027-d", text: "靠北，同事變情人是緣分，妳消息倒是快。", archetype: "perfect", retort: "……她笑了一下，靠北，你敢講！" },
      { id: "neighbor-chen-marriage-027-e", text: "辦公室戀情讓我天天準時打卡，去死啦浪漫。", archetype: "backfire", retort: "（她沒聽懂，笑了一下）" },
      { id: "neighbor-chen-marriage-027-f", text: "感情先保密，靠，妳今天要去哪？", archetype: "deflect", retort: "去買點東西而已。" },
      { id: "neighbor-chen-marriage-027-g", text: "幹你娘，妳這老太婆整天打聽很閒喔？", archetype: "landmine", retort: "去你的，態度差，欠管教！" },
      { id: "neighbor-chen-marriage-027-h", text: "確實在一起了，幹……還在適應狀況……", archetype: "meek", retort: "適應狀況？那要不要考慮換部門？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-028",
    text: "聽說你相親開的條件很高？挑成這樣？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-028-a", text: "他媽的，條件高，因為我可不是誰都能將就。", archetype: "perfect", retort: "……她拿著彩券，他媽的，嘴巴真賤！" },
      { id: "neighbor-chen-marriage-028-b", text: "條件先別提，笑死，今天手氣如何？", archetype: "deflect", retort: "還沒開獎，等一下看看。" },
      { id: "neighbor-chen-marriage-028-c", text: "可能真的開太高了，幹……還在調整……", archetype: "meek", retort: "調整？那要不要降低一點？" },
      { id: "neighbor-chen-marriage-028-d", text: "我的條件跟樂透中獎機率差不多，靠杯準。", archetype: "backfire", retort: "……（她拿著彩券，沒理我）" },
      { id: "neighbor-chen-marriage-028-e", text: "老不死，我開什麼條件關妳屁事，去死啦？", archetype: "landmine", retort: "靠北，你講話這麼衝，欠揍！" },
      { id: "neighbor-chen-marriage-028-f", text: "條件先保密，靠，這期獎金好高喔。", archetype: "deflect", retort: "對啊，聽說破紀錄了。" },
      { id: "neighbor-chen-marriage-028-g", text: "確實條件開比較高，靠……還在反省……", archetype: "meek", retort: "反省？那要不要重新想想？" },
      { id: "neighbor-chen-marriage-028-h", text: "條件高沒關係，我用刮刮樂選人，幹你娘咧隨緣。", archetype: "backfire", retort: "（她沒聽懂，繼續看彩券）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-029",
    text: "交往這麼久了，怎麼還沒求婚？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-029-a", text: "求婚先別提，笑死，妳車加滿油了嗎？", archetype: "deflect", retort: "快好了，等一下就走。" },
      { id: "neighbor-chen-marriage-029-b", text: "機掰，求婚急不得，妳比我男友還心急。", archetype: "perfect", retort: "……她看著油錶，機掰，你這什麼嘴！" },
      { id: "neighbor-chen-marriage-029-c", text: "求婚我打算辦煙火秀，他媽的還在存錢。", archetype: "backfire", retort: "……（她看著油錶，沒理我）" },
      { id: "neighbor-chen-marriage-029-d", text: "老實說也在等，幹……有點著急……", archetype: "meek", retort: "著急？那要不要主動問問看？" },
      { id: "neighbor-chen-marriage-029-e", text: "求婚先保密，靠，油價今天調漲了嗎？", archetype: "deflect", retort: "對啊，漲了一塊多。" },
      { id: "neighbor-chen-marriage-029-f", text: "幹，我們求不求婚，老太婆別管？", archetype: "landmine", retort: "你他媽的沒大沒小，欠罵！" },
      { id: "neighbor-chen-marriage-029-g", text: "求婚我打算用空拍機拍，幹浮誇。", archetype: "backfire", retort: "（她沒聽懂，繼續加油）" },
      { id: "neighbor-chen-marriage-029-h", text: "真的還沒求婚，靠……我也有點困惑……", archetype: "meek", retort: "困惑？那要不要開口談談？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-030",
    text: "伴娘伴郎找好了嗎？聽說很難選。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-030-a", text: "還在挑選，幹……怕漏掉重要的朋友……", archetype: "meek", retort: "漏掉？那要不要多問問朋友？" },
      { id: "neighbor-chen-marriage-030-b", text: "伴娘伴郎我打算辦選拔賽，靠北隆重。", archetype: "backfire", retort: "……（她挑著五金零件，沒理我）" },
      { id: "neighbor-chen-marriage-030-c", text: "去你的，人選還沒定，但輪不到妳來選。", archetype: "perfect", retort: "……她挑著五金零件，去你的，嘴真利！" },
      { id: "neighbor-chen-marriage-030-d", text: "伴娘先別提，笑死，這家工具好齊全。", archetype: "deflect", retort: "開了二十年了啦。" },
      { id: "neighbor-chen-marriage-030-e", text: "確實很難決定，靠……怕得罪人……", archetype: "meek", retort: "得罪人？那要不要私下問清楚？" },
      { id: "neighbor-chen-marriage-030-f", text: "幹，老東西，妳想拿紅包才想當伴娘？", archetype: "landmine", retort: "幹，你講什麼鬼話，沒禮貌！" },
      { id: "neighbor-chen-marriage-030-g", text: "人選先保密，靠，螺絲起子多少錢？", archetype: "deflect", retort: "一支五十塊啦。" },
      { id: "neighbor-chen-marriage-030-h", text: "伴娘伴郎我打算用抽籤決定，機掰公平。", archetype: "backfire", retort: "（她沒聽懂，繼續逛五金行）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-031",
    text: "什麼時候帶男女朋友回家給爸媽看？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-031-a", text: "帶回家前我要先幫他惡補家規，去你的嚴格。", archetype: "backfire", retort: "……（她挑著年花，沒理我）" },
      { id: "neighbor-chen-marriage-031-b", text: "還在找適合的時機，幹……有點緊張……", archetype: "meek", retort: "緊張？那要不要先讓爸媽有心理準備？" },
      { id: "neighbor-chen-marriage-031-c", text: "介紹先別提，笑死，這盆蘭花好漂亮。", archetype: "deflect", retort: "對啊，過年就要買這個。" },
      { id: "neighbor-chen-marriage-031-d", text: "幹，時機到了自然帶回家，不用妳排班表。", archetype: "perfect", retort: "……她挑著年花，幹，你這什麼嘴！" },
      { id: "neighbor-chen-marriage-031-e", text: "帶回家我要先幫他排練台詞，去死啦隆重。", archetype: "backfire", retort: "（她沒聽懂，繼續挑花）" },
      { id: "neighbor-chen-marriage-031-f", text: "介紹先保密，靠，這盆年橘要多少錢？", archetype: "deflect", retort: "這盆算你便宜一點。" },
      { id: "neighbor-chen-marriage-031-g", text: "他媽的，死老太婆，我帶誰回家關妳屁事？", archetype: "landmine", retort: "去你的，白眼狼，講話這麼衝！" },
      { id: "neighbor-chen-marriage-031-h", text: "還沒準備好，靠……怕爸媽會有意見……", archetype: "meek", retort: "有意見？那要不要先溝通一下？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-032",
    text: "求婚戒指買了沒？聽說要看款式。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-032-a", text: "靠北，戒指款式不重要，妳的鑑定我不需要。", archetype: "perfect", retort: "……她看著煙火，靠北，你敢講！" },
      { id: "neighbor-chen-marriage-032-b", text: "戒指先別提，笑死，今晚活動好熱鬧。", archetype: "deflect", retort: "對啊，社區辦得越來越用心。" },
      { id: "neighbor-chen-marriage-032-c", text: "還在挑選，幹……預算有點超出範圍……", archetype: "meek", retort: "超出？那要不要換個款式？" },
      { id: "neighbor-chen-marriage-032-d", text: "戒指我打算用資源回收自己做，靠杯環保。", archetype: "backfire", retort: "……（她看著煙火，沒理我）" },
      { id: "neighbor-chen-marriage-032-e", text: "去你的，老不死，我戒指買什麼關妳屁事？", archetype: "landmine", retort: "靠北，你找罵，講話這麼衝！" },
      { id: "neighbor-chen-marriage-032-f", text: "戒指先保密，靠，這場活動有摸彩嗎？", archetype: "deflect", retort: "有啊，等一下就開始。" },
      { id: "neighbor-chen-marriage-032-g", text: "還在猶豫款式，靠……怕她不喜歡……", archetype: "meek", retort: "不喜歡？那要不要先問問她？" },
      { id: "neighbor-chen-marriage-032-h", text: "戒指我打算用扭蛋機抽一個，幹你娘咧隨緣。", archetype: "backfire", retort: "（她沒聽懂，繼續看表演）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-033",
    text: "上次介紹的對象你怎麼都不理人家？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-033-a", text: "那件先別提，笑死，妳家裝飾得真喜氣。", archetype: "deflect", retort: "謝謝誇獎，我弄了一整天。" },
      { id: "neighbor-chen-marriage-033-b", text: "他媽的，感覺不對別勉強，妳的面子不歸我管。", archetype: "perfect", retort: "……她一臉狐疑，他媽的，嘴巴真賤！" },
      { id: "neighbor-chen-marriage-033-c", text: "我不是不理，是緊張句子講不出來，他媽的。", archetype: "backfire", retort: "……（她一臉狐疑，沒接話）" },
      { id: "neighbor-chen-marriage-033-d", text: "老實說感覺不太合，幹……不知道怎麼開口……", archetype: "meek", retort: "不合？那要不要再多聊聊看？" },
      { id: "neighbor-chen-marriage-033-e", text: "相親先保密，靠，春聯是自己寫的？", archetype: "deflect", retort: "對啊，我孫子寫的。" },
      { id: "neighbor-chen-marriage-033-f", text: "機掰，妳這老太婆，是想收介紹費吧？", archetype: "landmine", retort: "你他媽的講這什麼話，欠教訓！" },
      { id: "neighbor-chen-marriage-033-g", text: "我不是拒絕，是在醞釀完美回覆，幹太慢。", archetype: "backfire", retort: "（她沒聽懂，轉頭忙別的事）" },
      { id: "neighbor-chen-marriage-033-h", text: "確實沒有感覺，靠……怕辜負您的好意……", archetype: "meek", retort: "辜負？那要不要再給機會？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-034",
    text: "婚禮日期看農民曆了嗎？黃道吉日重要。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-034-a", text: "還沒看，幹……不太懂怎麼挑日子……", archetype: "meek", retort: "不懂？那要不要請人幫忙看？" },
      { id: "neighbor-chen-marriage-034-b", text: "我打算隨便選一天反正天天吉利，靠北隨性。", archetype: "backfire", retort: "……（她倒抽一口氣，沒接話）" },
      { id: "neighbor-chen-marriage-034-c", text: "機掰，黃道吉日重要，但天天用心更重要。", archetype: "perfect", retort: "……她倒抽一口氣，機掰，你敢講！" },
      { id: "neighbor-chen-marriage-034-d", text: "日期先別提，笑死，新年快樂發大財！", archetype: "deflect", retort: "哎唷，你也是，恭喜發財！" },
      { id: "neighbor-chen-marriage-034-e", text: "還在請人看，靠……怕挑錯日子不吉利……", archetype: "meek", retort: "不吉利？那要慎重一點喔。" },
      { id: "neighbor-chen-marriage-034-f", text: "幹你娘，老東西，我哪天結婚關妳屁事？", archetype: "landmine", retort: "幹，你沒大沒小，欠罵！" },
      { id: "neighbor-chen-marriage-034-g", text: "日期先保密，靠，紅包準備好了嗎？", archetype: "deflect", retort: "準備好了，等一下就發。" },
      { id: "neighbor-chen-marriage-034-h", text: "我打算選農民曆說不宜嫁娶那天，機掰叛逆。", archetype: "backfire", retort: "（她臉色一沉，沒說話）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-035",
    text: "結婚後要冠夫姓嗎？現在人還會這樣？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-035-a", text: "冠夫姓不夠，我打算連名帶姓合體，去你的浮誇。", archetype: "backfire", retort: "……（群組沒人回應）" },
      { id: "neighbor-chen-marriage-035-b", text: "還沒決定，幹……兩邊都有考慮……", archetype: "meek", retort: "還沒決定？那要不要早點商量？" },
      { id: "neighbor-chen-marriage-035-c", text: "冠姓先別提，笑死，紅包照片包得好厚。", archetype: "deflect", retort: "過年就是要包厚一點啦。" },
      { id: "neighbor-chen-marriage-035-d", text: "去你的，冠不冠姓我決定，不勞妳投票。", archetype: "perfect", retort: "……群組沒人回應，去你的，被將一軍。" },
      { id: "neighbor-chen-marriage-035-e", text: "我打算兩個姓氏輪流用，去死啦公平。", archetype: "backfire", retort: "（群組已讀無人回應）" },
      { id: "neighbor-chen-marriage-035-f", text: "冠姓先保密，靠，這紅包是給誰的？", archetype: "deflect", retort: "是給孫子的啦。" },
      { id: "neighbor-chen-marriage-035-g", text: "死老太婆，我冠不冠姓關妳屁事，去死啦？", archetype: "landmine", retort: "去你的，白眼狼，講話這麼衝！" },
      { id: "neighbor-chen-marriage-035-h", text: "還在考慮，靠……怕長輩會有意見……", archetype: "meek", retort: "有意見？那要不要先問問看？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-036",
    text: "為了男朋友要搬去外縣市？值得嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-036-a", text: "幹，值不值得我自己衡量，不用妳計算。", archetype: "perfect", retort: "……她翻著香腸，幹，你這什麼嘴！" },
      { id: "neighbor-chen-marriage-036-b", text: "搬家先別提，笑死，香腸曬得真香。", archetype: "deflect", retort: "對啊，過年就是要曬臘肉。" },
      { id: "neighbor-chen-marriage-036-c", text: "還在考慮，幹……捨不得離開熟悉的地方……", archetype: "meek", retort: "捨不得？那要不要再想清楚？" },
      { id: "neighbor-chen-marriage-036-d", text: "搬家我打算把房間打包空運，靠杯浮誇。", archetype: "backfire", retort: "……（她翻著香腸，沒理我）" },
      { id: "neighbor-chen-marriage-036-e", text: "幹，老不死，我搬去哪關妳屁事？", archetype: "landmine", retort: "靠北，你欠教訓，沒大沒小！" },
      { id: "neighbor-chen-marriage-036-f", text: "搬家先保密，靠，臘肉是自己灌的嗎？", archetype: "deflect", retort: "對啊，每年都自己灌。" },
      { id: "neighbor-chen-marriage-036-g", text: "確實有點捨不得，靠……但想為感情努力……", archetype: "meek", retort: "努力？那新工作找好了嗎？" },
      { id: "neighbor-chen-marriage-036-h", text: "搬家後我打算把陽台也搬過去，幹你娘咧離譜。", archetype: "backfire", retort: "（她沒聽懂，繼續翻香腸）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-037",
    text: "要不要參加聯誼？我幫你報名了。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-037-a", text: "聯誼先別提，笑死，這攤春聯賣得真好。", archetype: "deflect", retort: "對啊，過年生意特別好。" },
      { id: "neighbor-chen-marriage-037-b", text: "靠北，謝謝報名，但緣分不是妳能安排的。", archetype: "perfect", retort: "……她愣住，靠北，你敢講！" },
      { id: "neighbor-chen-marriage-037-c", text: "聯誼我打算穿騎士服去，他媽的顯眼。", archetype: "backfire", retort: "……（她愣住，沒接話）" },
      { id: "neighbor-chen-marriage-037-d", text: "好啊，幹……但有點緊張不知道怎麼聊天……", archetype: "meek", retort: "緊張？那要不要先練習開場白？" },
      { id: "neighbor-chen-marriage-037-e", text: "聯誼先保密，靠，這副春聯是您寫的？", archetype: "deflect", retort: "不是啦，是印的。" },
      { id: "neighbor-chen-marriage-037-f", text: "他媽的，妳這老太婆，是想收仲介費吧？", archetype: "landmine", retort: "你他媽的講話這麼難聽，沒禮貌！" },
      { id: "neighbor-chen-marriage-037-g", text: "聯誼我打算全場發名片自我介紹，幹浮誇。", archetype: "backfire", retort: "（她沒聽懂，繼續賣春聯）" },
      { id: "neighbor-chen-marriage-037-h", text: "會去看看啦，靠……但期待不會太高……", archetype: "meek", retort: "不會太高？那要不要調整心態？" },
    ],
  },
] satisfies Question[];
