// situations: 001 打掃社區花園, 002 社區守望相助巡邏, 003 傳LINE語音訊息,
// 004 社區群組發投票, 005 大樓管理室聊天, 006 除夕前大掃除, 007 年貨大街巧遇,
// 008 你倒車她在旁邊看, 009 貼春聯她探頭問, 010 陽台對陽台講電話被聽到,
// 011 巷口市場買年貨, 012 社區尾牙餐會, 013 廟會排隊, 014 社區抽獎活動,
// 015 大樓公佈欄貼公告, 016 巷口早餐店外帶, 017 頂樓拜拜, 018 社區停車糾紛協調,
// 019 幫你搬東西上樓, 020 巷口便當店
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-marriage-001",
    text: "有對象了沒？我跟你媽問好幾次了。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-001-a", text: "對象先別提，笑死，妳花種得真美。", archetype: "deflect", retort: "謝謝誇獎，我天天照顧。" },
      { id: "neighbor-chen-marriage-001-b", text: "感情的事，妳他媽都問我媽了還問我？", archetype: "perfect", retort: "幹，你這孩子嘴巴真賤！" },
      { id: "neighbor-chen-marriage-001-c", text: "我對象是我的工作，北七，愛得死去活來。", archetype: "backfire", retort: "……（她剪著花，沒理我）" },
      { id: "neighbor-chen-marriage-001-d", text: "還沒有啦，幹……緣分還沒到……", archetype: "meek", retort: "沒到？那要不要找人介紹？" },
      { id: "neighbor-chen-marriage-001-e", text: "感情先保密，靠，這盆花什麼品種？", archetype: "deflect", retort: "這是新買的杜鵑花啦。" },
      { id: "neighbor-chen-marriage-001-f", text: "妳不是我媽，去你的老太婆，管什麼！", archetype: "landmine", retort: "你這什麼態度，去你的！我要跟你媽講！" },
      { id: "neighbor-chen-marriage-001-g", text: "我單身是因為，機掰，市場太搶手啦。", archetype: "backfire", retort: "（她沒聽懂，繼續澆水）" },
      { id: "neighbor-chen-marriage-001-h", text: "真的還沒有，幹……工作比較忙……", archetype: "meek", retort: "忙？那要不要抽空去聯誼？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-002",
    text: "要不要相親？我認識一個不錯的。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-002-a", text: "再考慮看看啦，幹……還沒準備好……", archetype: "meek", retort: "沒準備好？那要準備到什麼時候？" },
      { id: "neighbor-chen-marriage-002-b", text: "相親我很擅長，他媽的，已經相過八次了。", archetype: "backfire", retort: "……（她愣了一下，沒接話）" },
      { id: "neighbor-chen-marriage-002-c", text: "謝謝關心，緣分沒到，介紹費妳他媽先省。", archetype: "perfect", retort: "幹，你這孩子嘴巴真利！" },
      { id: "neighbor-chen-marriage-002-d", text: "相親再說，笑死，妳巡邏辛苦了。", archetype: "deflect", retort: "應該的啦，社區安全最重要。" },
      { id: "neighbor-chen-marriage-002-e", text: "還在猶豫，幹……怕相親會尷尬……", archetype: "meek", retort: "尷尬？多見幾次就習慣了。" },
      { id: "neighbor-chen-marriage-002-f", text: "妳這麼熱心相親，去死，是想抽紅包吧？", archetype: "landmine", retort: "你他媽的沒大沒小，欠教訓！" },
      { id: "neighbor-chen-marriage-002-g", text: "相親先緩緩，北七，晚上巡邏冷不冷？", archetype: "deflect", retort: "還好啦，穿多一點就好。" },
      { id: "neighbor-chen-marriage-002-h", text: "我相親對象要求太高，機掰，先徵選啦。", archetype: "backfire", retort: "（她沒聽懂，繼續巡邏）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-003",
    text: "傳語音問你，到底什麼時候結婚？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-003-a", text: "結婚日期由月老決定，笑死，我配合演出。", archetype: "backfire", retort: "……（語音沒回，過了半天）" },
      { id: "neighbor-chen-marriage-003-b", text: "還沒有時間表，幹……順其自然……", archetype: "meek", retort: "順其自然？那不會太晚嗎？" },
      { id: "neighbor-chen-marriage-003-c", text: "結婚再說，靠，貼圖好可愛喔。", archetype: "deflect", retort: "哪裡買的我教你。" },
      { id: "neighbor-chen-marriage-003-d", text: "結婚日期，妳他媽比我媽還急著知道？", archetype: "perfect", retort: "靠北，你這孩子嘴巴真利！" },
      { id: "neighbor-chen-marriage-003-e", text: "結婚日期已經算過命，北七，天機不可洩漏。", archetype: "backfire", retort: "（她已讀不回）" },
      { id: "neighbor-chen-marriage-003-f", text: "結婚先保密，笑死，妳怎麼有空傳訊息？", archetype: "deflect", retort: "在家沒事就傳傳。" },
      { id: "neighbor-chen-marriage-003-g", text: "妳這麼閒，去死，一直傳訊息問這個？", archetype: "landmine", retort: "你這孩子講話怎麼這麼衝，去死！" },
      { id: "neighbor-chen-marriage-003-h", text: "真的還沒計畫，幹……順其自然……", archetype: "meek", retort: "順其自然？那要不要主動一點？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-004",
    text: "都幾歲了還單身，是不是太挑？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-004-a", text: "挑一點才不將就，妳他媽當年也挑過吧？", archetype: "perfect", retort: "幹，她愣了一下，沒接話。" },
      { id: "neighbor-chen-marriage-004-b", text: "單身先別提，笑死，這投票投給誰？", archetype: "deflect", retort: "我投社區大掃除那個。" },
      { id: "neighbor-chen-marriage-004-c", text: "是有點挑啦，幹……怕遇到不合適的……", archetype: "meek", retort: "挑？那要不要放寬條件？" },
      { id: "neighbor-chen-marriage-004-d", text: "我不是挑，機掰，是市場沒準備好迎接我。", archetype: "backfire", retort: "……（群組已讀無人回應）" },
      { id: "neighbor-chen-marriage-004-e", text: "妳不是我媽，去你的老東西，管什麼？", archetype: "landmine", retort: "我關心你才問，講話這麼兇，去你的！" },
      { id: "neighbor-chen-marriage-004-f", text: "單身先保密，靠，投票截止日幾號？", archetype: "deflect", retort: "下禮拜三截止喔。" },
      { id: "neighbor-chen-marriage-004-g", text: "確實比較挑，幹……還在等對的人……", archetype: "meek", retort: "等？那要不要多認識新朋友？" },
      { id: "neighbor-chen-marriage-004-h", text: "我單身是因為，他媽的，太完美配不上一般人。", archetype: "backfire", retort: "（群組陷入沉默）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-005",
    text: "聽說你男女朋友在國外，撐得住嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-005-a", text: "遠距離先別提，笑死，管理員好親切。", archetype: "deflect", retort: "哈，他人一直都很好啦。" },
      { id: "neighbor-chen-marriage-005-b", text: "撐不撐得住，先問妳他媽消息哪來的。", archetype: "perfect", retort: "幹，她喝了口茶，語塞。" },
      { id: "neighbor-chen-marriage-005-c", text: "遠距離讓我們的愛情，北七，有時差優勢。", archetype: "backfire", retort: "……（她沒聽懂，喝了口茶）" },
      { id: "neighbor-chen-marriage-005-d", text: "老實說有點辛苦，幹……常常想對方……", archetype: "meek", retort: "辛苦？那要不要考慮誰搬過去？" },
      { id: "neighbor-chen-marriage-005-e", text: "感情先保密，靠，管理室換新設備喔。", archetype: "deflect", retort: "對啊，剛裝的監視器。" },
      { id: "neighbor-chen-marriage-005-f", text: "妳連我對象在哪都知道，去你的老太婆！", archetype: "landmine", retort: "鄰居都在傳，你這什麼態度，去你的！" },
      { id: "neighbor-chen-marriage-005-g", text: "遠距離戀愛讓我，機掰，省了約會錢啦。", archetype: "backfire", retort: "（她沒聽懂，翻看報紙）" },
      { id: "neighbor-chen-marriage-005-h", text: "確實比較累，幹……但還在努力維持……", archetype: "meek", retort: "努力維持？那多久見一次面？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-006",
    text: "聽說你跟男女朋友同居？家裡知道嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-006-a", text: "家裡知道啦，幹……只是還沒正式講……", archetype: "meek", retort: "沒正式講？那要不要找時間說清楚？" },
      { id: "neighbor-chen-marriage-006-b", text: "同居讓我省了，他媽的，一半房租啦。", archetype: "backfire", retort: "……（她拖著地，沒理我）" },
      { id: "neighbor-chen-marriage-006-c", text: "同居是為了更了解，家裡我他媽自己說。", archetype: "perfect", retort: "幹，她拖著地，語塞。" },
      { id: "neighbor-chen-marriage-006-d", text: "同居先別提，笑死，妳大掃除也太認真。", archetype: "deflect", retort: "過年前一定要徹底打掃。" },
      { id: "neighbor-chen-marriage-006-e", text: "還在磨合啦，幹……同居真的不容易……", archetype: "meek", retort: "不容易？那要不要多溝通？" },
      { id: "neighbor-chen-marriage-006-f", text: "妳這麼清楚我同居，去死，是不是常偷看？", archetype: "landmine", retort: "我當然知道，社區誰不知道，去死！" },
      { id: "neighbor-chen-marriage-006-g", text: "同居先保密，靠，這抹布新買的嗎？", archetype: "deflect", retort: "對啊，過年要用新的。" },
      { id: "neighbor-chen-marriage-006-h", text: "同居讓我們感情升溫到，北七，快自燃啦。", archetype: "backfire", retort: "（她沒聽懂，繼續打掃）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-007",
    text: "結婚聘金要準備多少？男方會出嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-007-a", text: "聘金我打算用真心換，機掰，比較划算。", archetype: "backfire", retort: "……（她提著年貨，沒理我）" },
      { id: "neighbor-chen-marriage-007-b", text: "還在討論金額，幹……怕雙方不好開口……", archetype: "meek", retort: "不好開口？那要不要找媒人？" },
      { id: "neighbor-chen-marriage-007-c", text: "聘金再說，笑死，妳買的年貨真豐盛。", archetype: "deflect", retort: "對啊，過年就是要買齊全。" },
      { id: "neighbor-chen-marriage-007-d", text: "聘金心意到就好，不用妳他媽估價。", archetype: "perfect", retort: "幹，她提著年貨，語塞。" },
      { id: "neighbor-chen-marriage-007-e", text: "聘金我打算分期付款，靠北，感情較長久。", archetype: "backfire", retort: "（她沒聽懂，繼續逛攤位）" },
      { id: "neighbor-chen-marriage-007-f", text: "聘金先保密，北七，這攤糖果好特別。", archetype: "deflect", retort: "對啊，我每年都買。" },
      { id: "neighbor-chen-marriage-007-g", text: "妳自己聘金收多少，去死，敢公開嗎？", archetype: "landmine", retort: "你這什麼態度，欠人教訓，去死！" },
      { id: "neighbor-chen-marriage-007-h", text: "還沒討論好，幹……怕金額談不攏……", archetype: "meek", retort: "談不攏？那要不要先降低期待？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-008",
    text: "婚宴要辦幾桌？我跟你媽都在等喜帖。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-008-a", text: "位置一定留，但紅包妳他媽記得包厚。", archetype: "perfect", retort: "幹，她愣住，摸摸口袋。" },
      { id: "neighbor-chen-marriage-008-b", text: "婚宴再說，笑死，幫我看一下車距好嗎？", archetype: "deflect", retort: "沒問題，還有一點空間。" },
      { id: "neighbor-chen-marriage-008-c", text: "還在討論規模，幹……預算有點吃緊……", archetype: "meek", retort: "吃緊？那要不要辦小一點？" },
      { id: "neighbor-chen-marriage-008-d", text: "婚宴我打算辦一百桌，機掰，越多越有排場。", archetype: "backfire", retort: "……（她愣住，沒接話）" },
      { id: "neighbor-chen-marriage-008-e", text: "妳這麼期待喜帖，去你的，是想要紅包吧？", archetype: "landmine", retort: "你這什麼意思，講話那麼衝，去你的！" },
      { id: "neighbor-chen-marriage-008-f", text: "桌數先保密，靠，您停車技術真好。", archetype: "deflect", retort: "開了三十年，習慣了。" },
      { id: "neighbor-chen-marriage-008-g", text: "規模還沒確定，幹……怕人多顧不好……", archetype: "meek", retort: "顧不好？那要不要請婚顧幫忙？" },
      { id: "neighbor-chen-marriage-008-h", text: "婚宴我打算辦流水席，他媽的，越熱鬧越好。", archetype: "backfire", retort: "（她沒聽懂，繼續看我倒車）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-009",
    text: "蜜月要去哪？聽說很多人去日本。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-009-a", text: "蜜月再說，笑死，這副對聯寫得真好。", archetype: "deflect", retort: "哪有，是買現成的啦。" },
      { id: "neighbor-chen-marriage-009-b", text: "蜜月去哪，妳他媽比我媽還想知道行程？", archetype: "perfect", retort: "幹，她扶著春聯，語塞。" },
      { id: "neighbor-chen-marriage-009-c", text: "蜜月我打算去月球，北七，比較特別啦。", archetype: "backfire", retort: "……（她扶著春聯，沒接話）" },
      { id: "neighbor-chen-marriage-009-d", text: "還沒決定，幹……預算要再算一下……", archetype: "meek", retort: "算一下？那要不要先訂機票？" },
      { id: "neighbor-chen-marriage-009-e", text: "旅行先保密，靠，這春聯貼歪了喔。", archetype: "deflect", retort: "對耶，我重貼一下。" },
      { id: "neighbor-chen-marriage-009-f", text: "妳連我蜜月都要問，去死，想跟團喔？", archetype: "landmine", retort: "你這什麼態度，去死！我要跟你媽講！" },
      { id: "neighbor-chen-marriage-009-g", text: "蜜月我要去環遊世界，機掰，一百天啦。", archetype: "backfire", retort: "（她沒聽懂，繼續貼春聯）" },
      { id: "neighbor-chen-marriage-009-h", text: "還在考慮，幹……可能去比較近的地方……", archetype: "meek", retort: "近的地方？那不會不夠特別嗎？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-010",
    text: "聽你講電話在約婚紗，要結婚了？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-010-a", text: "還在規劃啦，幹……日期還沒完全定……", archetype: "meek", retort: "沒定？那婚紗先拍好也不錯。" },
      { id: "neighbor-chen-marriage-010-b", text: "婚紗照我要拍成，他媽的，偶像劇海報啦。", archetype: "backfire", retort: "……（她曬著衣服，沒聽懂）" },
      { id: "neighbor-chen-marriage-010-c", text: "對，要結婚了，紅包妳他媽記得包大包。", archetype: "perfect", retort: "幹，她愣了一下，摸摸口袋。" },
      { id: "neighbor-chen-marriage-010-d", text: "婚紗先保密，笑死，蘭花好漂亮。", archetype: "deflect", retort: "這是新買的蘭花啦。" },
      { id: "neighbor-chen-marriage-010-e", text: "還在考慮拍攝風格，幹……有點猶豫……", archetype: "meek", retort: "猶豫？那要不要找攝影師建議？" },
      { id: "neighbor-chen-marriage-010-f", text: "妳是不是都在陽台偷聽電話，去死？", archetype: "landmine", retort: "你這孩子怎麼這樣說話，去死！" },
      { id: "neighbor-chen-marriage-010-g", text: "婚紗照先別提，靠，陽台真熱鬧。", archetype: "deflect", retort: "對啊，在整理盆栽。" },
      { id: "neighbor-chen-marriage-010-h", text: "婚紗照我要拍一百套造型，機掰，才過癮。", archetype: "backfire", retort: "（她沒聽懂，繼續曬衣服）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-011",
    text: "聽說你們分手了？怎麼回事啊？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-011-a", text: "分手是為了，笑死，給彼此更大的市場。", archetype: "backfire", retort: "……（她挑著菜，沒理我）" },
      { id: "neighbor-chen-marriage-011-b", text: "是分了，幹……個性不太合適……", archetype: "meek", retort: "不合適？那怎麼當初會在一起？" },
      { id: "neighbor-chen-marriage-011-c", text: "感情先別提，靠，這攤橘子好甜。", archetype: "deflect", retort: "對啊，過年應景。" },
      { id: "neighbor-chen-marriage-011-d", text: "分手是我的事，妳他媽比警廣還快。", archetype: "perfect", retort: "幹，她挑著水果，語塞。" },
      { id: "neighbor-chen-marriage-011-e", text: "分手後我升級成，北七，單身貴族啦。", archetype: "backfire", retort: "（她沒聽懂，繼續挑水果）" },
      { id: "neighbor-chen-marriage-011-f", text: "感情先保密，笑死，橘子多少錢一斤？", archetype: "deflect", retort: "一斤四十啦，划算。" },
      { id: "neighbor-chen-marriage-011-g", text: "妳連我分手都知道，去死，是很閒嗎？", archetype: "landmine", retort: "整個巷子都在傳，你態度差什麼，去死！" },
      { id: "neighbor-chen-marriage-011-h", text: "確實分開了，幹……還在調適心情……", archetype: "meek", retort: "調適心情？那要不要多出去走走？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-012",
    text: "單身這麼久，是不是眼光太高了？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-012-a", text: "眼光高沒關係，總比妳他媽亂將就好。", archetype: "perfect", retort: "幹，她夾著菜，語塞。" },
      { id: "neighbor-chen-marriage-012-b", text: "單身先別提，笑死，尾牙菜色好豐盛。", archetype: "deflect", retort: "對啊，餐廳今年換新的。" },
      { id: "neighbor-chen-marriage-012-c", text: "可能真的有點挑，幹……還在調整心態……", archetype: "meek", retort: "調整？那要不要放寬一點？" },
      { id: "neighbor-chen-marriage-012-d", text: "我單身是因為，機掰，在等宇宙的安排啦。", archetype: "backfire", retort: "……（她沒聽懂，繼續夾菜）" },
      { id: "neighbor-chen-marriage-012-e", text: "妳這麼閒，去你的老太婆，管什麼單不單身？", archetype: "landmine", retort: "你這孩子講話怎麼這麼衝，去你的！" },
      { id: "neighbor-chen-marriage-012-f", text: "單身先保密，靠，這桌安排得真好。", archetype: "deflect", retort: "是委員會特別安排的。" },
      { id: "neighbor-chen-marriage-012-g", text: "確實單身有點久，幹……還在等緣分……", archetype: "meek", retort: "等緣分？那要不要主動一點？" },
      { id: "neighbor-chen-marriage-012-h", text: "我單身是限量版，他媽的，物以稀為貴啦。", archetype: "backfire", retort: "（她沒聽懂，轉頭跟別人聊天）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-013",
    text: "現在都用交友軟體喔？靠得住嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-013-a", text: "交友軟體先別提，笑死，廟會人好多喔。", archetype: "deflect", retort: "對啊，每年都這麼熱鬧。" },
      { id: "neighbor-chen-marriage-013-b", text: "軟體是工具，識人的眼光我他媽自己練。", archetype: "perfect", retort: "幹，她沒聽懂，繼續排隊。" },
      { id: "neighbor-chen-marriage-013-c", text: "交友軟體我配對成功率，北七，百分之百。", archetype: "backfire", retort: "……（她沒聽懂，繼續排隊）" },
      { id: "neighbor-chen-marriage-013-d", text: "有在用啦，幹……但遇到的人不太理想……", archetype: "meek", retort: "不理想？那要不要換一個用？" },
      { id: "neighbor-chen-marriage-013-e", text: "交友先保密，靠，要不要一起拜拜？", archetype: "deflect", retort: "好啊，一起求個好姻緣。" },
      { id: "neighbor-chen-marriage-013-f", text: "妳這老太婆，那年代沒交友軟體，去死！", archetype: "landmine", retort: "你這什麼態度，去死！我要跟你媽講！" },
      { id: "neighbor-chen-marriage-013-g", text: "我在軟體上超搶手，機掰，訊息接不完啦。", archetype: "backfire", retort: "（她沒聽懂，往前排隊）" },
      { id: "neighbor-chen-marriage-013-h", text: "有用啦，幹……但效果普通，還在嘗試……", archetype: "meek", retort: "效果普通？那要不要換個方式？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-014",
    text: "聽說你男女朋友小你好幾歲？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-014-a", text: "是啦，幹……年齡差一點，但相處不錯……", archetype: "meek", retort: "不錯？那觀念會不會有差？" },
      { id: "neighbor-chen-marriage-014-b", text: "年齡差讓我們感情，他媽的，更有活力啦。", archetype: "backfire", retort: "……（她抽著獎券，沒理我）" },
      { id: "neighbor-chen-marriage-014-c", text: "年齡不是重點，合得來比妳他媽嘴甜重要。", archetype: "perfect", retort: "幹，她抽著獎券，語塞。" },
      { id: "neighbor-chen-marriage-014-d", text: "年齡先別提，笑死，這抽獎獎品好豐富。", archetype: "deflect", retort: "對啊，頭獎是電鍋呢。" },
      { id: "neighbor-chen-marriage-014-e", text: "確實有差幾歲，幹……還在磨合觀念……", archetype: "meek", retort: "磨合？那要不要多包容一點？" },
      { id: "neighbor-chen-marriage-014-f", text: "妳連我們年齡差都算，去你的，很閒喔？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼，去你的！" },
      { id: "neighbor-chen-marriage-014-g", text: "年齡差先保密，靠，什麼時候開獎？", archetype: "deflect", retort: "等一下就要開了。" },
      { id: "neighbor-chen-marriage-014-h", text: "年齡差讓我感覺自己，機掰，回春了啦。", archetype: "backfire", retort: "（她沒聽懂，繼續抽獎）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-015",
    text: "都到適婚年齡了，還不趕快找對象？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-015-a", text: "適婚年齡是參考用的，笑死，我走自己時區。", archetype: "backfire", retort: "……（她貼著公告，沒理我）" },
      { id: "neighbor-chen-marriage-015-b", text: "有壓力啦，幹……但真的還沒遇到合適的……", archetype: "meek", retort: "沒遇到？那要不要多參加活動？" },
      { id: "neighbor-chen-marriage-015-c", text: "年齡先別提，靠，公告寫的是什麼？", archetype: "deflect", retort: "社區運動會的報名表。" },
      { id: "neighbor-chen-marriage-015-d", text: "適婚年齡是妳他媽定的，不是法律規定。", archetype: "perfect", retort: "幹，她貼著公告，語塞。" },
      { id: "neighbor-chen-marriage-015-e", text: "我打算逆齡結婚，北七，越晚越潮啦。", archetype: "backfire", retort: "（她沒聽懂，繼續貼公告）" },
      { id: "neighbor-chen-marriage-015-f", text: "婚姻先保密，笑死，這活動要報名嗎？", archetype: "deflect", retort: "報名啊，順便交交朋友。" },
      { id: "neighbor-chen-marriage-015-g", text: "妳這老東西，一直站門口管結婚，去死！", archetype: "landmine", retort: "你這孩子講話怎麼這麼衝，去死！" },
      { id: "neighbor-chen-marriage-015-h", text: "確實有點晚了，幹……心裡也會著急……", archetype: "meek", retort: "著急？那要不要多主動一點？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-016",
    text: "以後結婚要跟公婆住嗎？處得來嗎？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-016-a", text: "處不處得來，先問妳他媽跟婆婆處得如何。", archetype: "perfect", retort: "幹，她點著早餐，語塞。" },
      { id: "neighbor-chen-marriage-016-b", text: "同住先別提，笑死，蛋餅特別好吃。", archetype: "deflect", retort: "對啊，老闆換了新食材。" },
      { id: "neighbor-chen-marriage-016-c", text: "還在考慮，幹……怕相處起來會有摩擦……", archetype: "meek", retort: "摩擦？那要不要先講好規矩？" },
      { id: "neighbor-chen-marriage-016-d", text: "跟公婆住，機掰，我打算當家裡的開心果。", archetype: "backfire", retort: "……（她點著早餐，沒理我）" },
      { id: "neighbor-chen-marriage-016-e", text: "妳自己跟婆婆處得好嗎，去你的，敢講？", archetype: "landmine", retort: "你這孩子問這幹嘛，沒禮貌，去你的！" },
      { id: "neighbor-chen-marriage-016-f", text: "同住先保密，靠，早餐店排隊好長。", archetype: "deflect", retort: "對啊，最近變有名了。" },
      { id: "neighbor-chen-marriage-016-g", text: "還沒決定，幹……怕住一起會有壓力……", archetype: "meek", retort: "壓力？那要不要先分開住看看？" },
      { id: "neighbor-chen-marriage-016-h", text: "跟公婆住，他媽的，我打算每天表演孝順秀。", archetype: "backfire", retort: "（她沒聽懂，拿了早餐就走）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-017",
    text: "訂婚儀式準備好了嗎？流程很多喔。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-017-a", text: "訂婚再說，笑死，妳拜拜求什麼？", archetype: "deflect", retort: "求全家平安啦。" },
      { id: "neighbor-chen-marriage-017-b", text: "流程多沒差，心意比排場妳他媽重要多了。", archetype: "perfect", retort: "幹，她合掌拜拜，語塞。" },
      { id: "neighbor-chen-marriage-017-c", text: "訂婚流程我打算，北七，全部自己主持啦。", archetype: "backfire", retort: "……（她合掌拜拜，沒理我）" },
      { id: "neighbor-chen-marriage-017-d", text: "還在準備，幹……有點手忙腳亂……", archetype: "meek", retort: "手忙腳亂？那要不要找人幫忙？" },
      { id: "neighbor-chen-marriage-017-e", text: "流程先保密，靠，頂樓風景今天真好。", archetype: "deflect", retort: "對啊，天氣好看得遠。" },
      { id: "neighbor-chen-marriage-017-f", text: "妳這老太婆，這麼會管流程，去你的自己辦？", archetype: "landmine", retort: "我關心你才問，講話這麼衝，去你的！" },
      { id: "neighbor-chen-marriage-017-g", text: "訂婚流程我打算，機掰，簡化成三分鐘啦。", archetype: "backfire", retort: "（她沒聽懂，繼續拜拜）" },
      { id: "neighbor-chen-marriage-017-h", text: "確實有點複雜，幹……還在學習中……", archetype: "meek", retort: "學習中？那要不要問問長輩？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-018",
    text: "算過八字了嗎？合不合很重要喔。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-018-a", text: "還沒算，幹……怕算出來結果不好……", archetype: "meek", retort: "不好？那要不要提早準備？" },
      { id: "neighbor-chen-marriage-018-b", text: "我們八字不合，他媽的，但個性超合啦。", archetype: "backfire", retort: "……（她忙著協調停車，沒理我）" },
      { id: "neighbor-chen-marriage-018-c", text: "八字合不合，不如我他媽倆合不合拍。", archetype: "perfect", retort: "幹，她忙著協調停車，語塞。" },
      { id: "neighbor-chen-marriage-018-d", text: "八字先別提，笑死，停車糾紛處理真好。", archetype: "deflect", retort: "沒辦法，鄰居間要互相體諒。" },
      { id: "neighbor-chen-marriage-018-e", text: "還沒去算，幹……有點猶豫要不要信……", archetype: "meek", retort: "猶豫？那要不要問問長輩意見？" },
      { id: "neighbor-chen-marriage-018-f", text: "妳連我八字都要管，去死，妳很閒嗎？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼，去死！" },
      { id: "neighbor-chen-marriage-018-g", text: "八字先保密，靠，停車格劃得真整齊。", archetype: "deflect", retort: "是委員會重新劃的。" },
      { id: "neighbor-chen-marriage-018-h", text: "八字不合我打算，機掰，用真愛克服啦。", archetype: "backfire", retort: "（她沒聽懂，繼續處理糾紛）" },
    ],
  },
  {
    id: "neighbor-chen-marriage-019",
    text: "結婚後要住哪？自己買房還是跟家裡？",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-019-a", text: "我打算住帳篷，笑死，比較有戀愛感啦。", archetype: "backfire", retort: "……（她放下東西，沒理我）" },
      { id: "neighbor-chen-marriage-019-b", text: "還在討論，幹……可能先租房子過渡……", archetype: "meek", retort: "過渡？那要租多久？" },
      { id: "neighbor-chen-marriage-019-c", text: "住哪先別提，靠，謝謝妳幫忙搬東西。", archetype: "deflect", retort: "不客氣啦，鄰居互相的。" },
      { id: "neighbor-chen-marriage-019-d", text: "住哪不重要，一起扛才是妳他媽的真本事。", archetype: "perfect", retort: "幹，她放下東西，語塞。" },
      { id: "neighbor-chen-marriage-019-e", text: "我打算搬去環遊世界，北七，到處都是家。", archetype: "backfire", retort: "（她沒聽懂，繼續搬東西）" },
      { id: "neighbor-chen-marriage-019-f", text: "住的事先保密，笑死，這箱子有點重，小心。", archetype: "deflect", retort: "沒問題，我很有力氣。" },
      { id: "neighbor-chen-marriage-019-g", text: "妳連我住哪都要管，去你的，想搬來一起？", archetype: "landmine", retort: "我好心幫忙，講話這麼衝做什麼，去你的！" },
      { id: "neighbor-chen-marriage-019-h", text: "還沒確定，幹……預算是最大的問題……", archetype: "meek", retort: "預算問題？那要不要跟家裡商量？" },
    ],
  },
  {
    id: "neighbor-chen-marriage-020",
    text: "該不會打算不結婚吧？一個人多孤單。",
    topic: "marriage",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-marriage-020-a", text: "孤不孤單看心態，不是看妳他媽的嘴。", archetype: "perfect", retort: "幹，她點著便當，語塞。" },
      { id: "neighbor-chen-marriage-020-b", text: "結不結婚先別提，笑死，便當今天加菜耶。", archetype: "deflect", retort: "對啊，老闆心情好。" },
      { id: "neighbor-chen-marriage-020-c", text: "有考慮過不婚，幹……但還沒完全確定……", archetype: "meek", retort: "沒確定？那要不要多想想？" },
      { id: "neighbor-chen-marriage-020-d", text: "不婚是因為，機掰，我要把自己嫁給事業。", archetype: "backfire", retort: "……（她點著便當，沒理我）" },
      { id: "neighbor-chen-marriage-020-e", text: "妳不是我媽，去你的老東西，管什麼結婚？", archetype: "landmine", retort: "我關心你，講話這麼衝做什麼，去你的！" },
      { id: "neighbor-chen-marriage-020-f", text: "婚姻先保密，靠，這便當多少錢？", archetype: "deflect", retort: "一個八十塊啦，划算。" },
      { id: "neighbor-chen-marriage-020-g", text: "還在考慮，幹……怕一個人老了會孤單……", archetype: "meek", retort: "會孤單？那要不要重新考慮看看？" },
      { id: "neighbor-chen-marriage-020-h", text: "不婚族的生活，他媽的，比偶像劇還精彩啦。", archetype: "backfire", retort: "（她沒聽懂，拿了便當就走）" },
    ],
  },
] satisfies Question[];
