// situations: 021 社區管委會會議, 022 澆花修剪花草, 023 買菜回家路上, 024 巷口掃落葉,
// 025 信箱前, 026 頂樓加蓋曬衣場, 027 巷口小吃攤, 028 貼春聯時, 029 掛燈籠佈置,
// 030 社區群組發問候圖, 031 倒完垃圾聊天, 032 樓梯間巧遇, 033 機車停車格前,
// 034 社區團購取貨, 035 帶孫子在樓下玩, 036 洗車時, 037 自助洗衣店
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-salary_job-021",
    text: "李太太兒子竹科上班，年薪破兩百萬呢。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-021-a", text: "厲害耶，那這頓飯讓他請，剛好。", archetype: "perfect", retort: "哎唷你這孩子，會拗人吃飯！" },
      { id: "neighbor-chen-salary_job-021-b", text: "他真厲害，李太太您教得真好。", archetype: "deflect", retort: "哪有，他自己努力的啦。" },
      { id: "neighbor-chen-salary_job-021-c", text: "跟他比是差很多，我還在加油……", archetype: "meek", retort: "差很多？那要不要更努力？" },
      { id: "neighbor-chen-salary_job-021-d", text: "我雖然沒兩百萬，但我有兩百分魅力。", archetype: "backfire", retort: "……（她沒聽懂，看向別人）" },
      { id: "neighbor-chen-salary_job-021-e", text: "妳這麼羨慕，怎麼不叫妳兒子去考？", archetype: "landmine", retort: "你這什麼意思，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-021-f", text: "薪水先別比，開會通知我都有收到。", archetype: "deflect", retort: "很好，準時最重要。" },
      { id: "neighbor-chen-salary_job-021-g", text: "跟他比真的差很多，我還在努力……", archetype: "meek", retort: "努力？那什麼時候能追上？" },
      { id: "neighbor-chen-salary_job-021-h", text: "我跟他不同賽道，我慢跑他短跑啦。", archetype: "backfire", retort: "（她沒聽懂，翻了會議資料）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-022",
    text: "楊太太兒子當律師，一小時收費好幾千。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-022-a", text: "他真厲害，楊太太您花園種得真漂亮。", archetype: "deflect", retort: "謝謝誇獎，我天天澆水。" },
      { id: "neighbor-chen-salary_job-022-b", text: "收費高是他的價碼，我的時間我定價。", archetype: "perfect", retort: "哎唷，你這孩子有自信！" },
      { id: "neighbor-chen-salary_job-022-c", text: "我的時間比律師還貴，因為稀有啦。", archetype: "backfire", retort: "……（她剪花，沒理我）" },
      { id: "neighbor-chen-salary_job-022-d", text: "跟他比真的差很多，我這行不值錢……", archetype: "meek", retort: "不值錢？那要不要轉行？" },
      { id: "neighbor-chen-salary_job-022-e", text: "收費的事先別比，這盆花是新種的？", archetype: "deflect", retort: "對啊，過年應景。" },
      { id: "neighbor-chen-salary_job-022-f", text: "妳連律師收費都清楚，想告誰嗎？", archetype: "landmine", retort: "你這孩子講話怎麼這樣，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-022-g", text: "我雖然不是律師，但我很會辯論啦。", archetype: "backfire", retort: "（她沒聽懂，繼續修剪）" },
      { id: "neighbor-chen-salary_job-022-h", text: "確實比不上，我這行薪水普通……", archetype: "meek", retort: "普通？那要加把勁了。" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-023",
    text: "聽說你們公司要裁員？你安全嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-023-a", text: "還不確定，心裡有點緊張……", archetype: "meek", retort: "緊張？那要不要先找備案？" },
      { id: "neighbor-chen-salary_job-023-b", text: "裁員名單沒有我，因為我太重要啦。", archetype: "backfire", retort: "……（她提著菜籃，沒接話）" },
      { id: "neighbor-chen-salary_job-023-c", text: "就算被裁，我也不會來跟妳借錢。", archetype: "perfect", retort: "哎唷，你這孩子有志氣！" },
      { id: "neighbor-chen-salary_job-023-d", text: "裁員的事先別提，您買的魚真新鮮。", archetype: "deflect", retort: "對啊，早上剛到的。" },
      { id: "neighbor-chen-salary_job-023-e", text: "老實說有點擔心，還在觀望……", archetype: "meek", retort: "觀望？那要不要先投履歷？" },
      { id: "neighbor-chen-salary_job-023-f", text: "妳連我們公司裁員都知道，很閒喔？", archetype: "landmine", retort: "鄰居都在傳，你態度差什麼！" },
      { id: "neighbor-chen-salary_job-023-g", text: "公司的事先別聊，您今天買好多菜。", archetype: "deflect", retort: "對啊，過年要用的。" },
      { id: "neighbor-chen-salary_job-023-h", text: "裁員也好，剛好讓我放長假啦。", archetype: "backfire", retort: "（她沒聽懂，繼續走）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-024",
    text: "常常看你晚歸，加班費有算嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-024-a", text: "加班費算在我的青春裡啦哈哈。", archetype: "backfire", retort: "……（她掃著落葉，沒接話）" },
      { id: "neighbor-chen-salary_job-024-b", text: "沒有加班費，公司說是責任制……", archetype: "meek", retort: "責任制？那怎麼保障自己？" },
      { id: "neighbor-chen-salary_job-024-c", text: "加班費先別提，落葉掃得真乾淨。", archetype: "deflect", retort: "每天掃習慣了啦。" },
      { id: "neighbor-chen-salary_job-024-d", text: "加班費有沒有算，不勞妳幫我核對。", archetype: "perfect", retort: "哎唷，你這孩子想得真開！" },
      { id: "neighbor-chen-salary_job-024-e", text: "加班費沒有，但加班餐很好吃啦。", archetype: "backfire", retort: "（她沒聽懂，繼續掃地）" },
      { id: "neighbor-chen-salary_job-024-f", text: "加班的事先別聊，您掃落葉好認真。", archetype: "deflect", retort: "哎唷，社區乾淨大家舒服。" },
      { id: "neighbor-chen-salary_job-024-g", text: "妳連我幾點回家都算，是在盯梢？", archetype: "landmine", retort: "你問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-024-h", text: "沒加班費，只能自己認了……", archetype: "meek", retort: "認了？那要不要去申訴？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-025",
    text: "你們公司有幫你保勞健保嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-025-a", text: "有保，比妳的關心還足夠。", archetype: "perfect", retort: "哎唷，那就好，我就放心了。" },
      { id: "neighbor-chen-salary_job-025-b", text: "保險的事先別提，信箱又塞滿廣告。", archetype: "deflect", retort: "對啊，天天都是傳單。" },
      { id: "neighbor-chen-salary_job-025-c", text: "只有最低保障，其他要自己補……", archetype: "meek", retort: "自己補？那負擔不會很重嗎？" },
      { id: "neighbor-chen-salary_job-025-d", text: "我的保障是自己的信心，夠用啦。", archetype: "backfire", retort: "……（她翻著信件，沒理我）" },
      { id: "neighbor-chen-salary_job-025-e", text: "妳連我勞健保都要查，是要幫我報稅？", archetype: "landmine", retort: "你問這幹嘛，講話這麼直！" },
      { id: "neighbor-chen-salary_job-025-f", text: "保險的事先聊，這信是您的帳單嗎？", archetype: "deflect", retort: "對啊，管理費繳費單。" },
      { id: "neighbor-chen-salary_job-025-g", text: "保障普通，還在考慮買保險……", archetype: "meek", retort: "考慮？那要快點決定喔。" },
      { id: "neighbor-chen-salary_job-025-h", text: "我信奉佛系保障，隨緣就好啦。", archetype: "backfire", retort: "（她沒聽懂，拿信轉身走）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-026",
    text: "還在實習喔？實習生也有薪水嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-026-a", text: "實習的事先別提，頂樓風景真不錯。", archetype: "deflect", retort: "對啊，曬衣服都來這裡。" },
      { id: "neighbor-chen-salary_job-026-b", text: "薪水不多，但比妳的碎念有價值。", archetype: "perfect", retort: "哎唷，你這孩子想法正確！" },
      { id: "neighbor-chen-salary_job-026-c", text: "實習生也是人生勝利組，只是還沒上市。", archetype: "backfire", retort: "……（她曬著衣服，沒聽懂）" },
      { id: "neighbor-chen-salary_job-026-d", text: "薪水確實不多，就是打工價……", archetype: "meek", retort: "打工價？那能存到錢嗎？" },
      { id: "neighbor-chen-salary_job-026-e", text: "實習的事先聊，這被單好大件。", archetype: "deflect", retort: "對啊，新年要換新的。" },
      { id: "neighbor-chen-salary_job-026-f", text: "妳連實習薪水都要問，很缺話題？", archetype: "landmine", retort: "你問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-026-g", text: "實習沒薪水沒關係，我有夢想啦。", archetype: "backfire", retort: "（她沒聽懂，繼續晾衣服）" },
      { id: "neighbor-chen-salary_job-026-h", text: "實習薪水少，還在撐著……", archetype: "meek", retort: "撐著？那正職有機會嗎？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-027",
    text: "做了這麼多年，薪水到底調了沒？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-027-a", text: "調是有調，但幅度不大……", archetype: "meek", retort: "不大？那心裡不會不平衡嗎？" },
      { id: "neighbor-chen-salary_job-027-b", text: "調薪幅度小，但我肚量調得很大。", archetype: "backfire", retort: "……（她吃著麵，沒理我）" },
      { id: "neighbor-chen-salary_job-027-c", text: "調多少是機密，漲不漲不用向妳報備。", archetype: "perfect", retort: "哎唷，你這孩子有自信！" },
      { id: "neighbor-chen-salary_job-027-d", text: "調薪的事先別提，這攤滷味真香。", archetype: "deflect", retort: "對啊，我常來吃。" },
      { id: "neighbor-chen-salary_job-027-e", text: "調幅真的不多，追不上物價……", archetype: "meek", retort: "追不上？那要不要提離職？" },
      { id: "neighbor-chen-salary_job-027-f", text: "妳連我薪水調沒調都算，很閒厚？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-027-g", text: "調薪的事先保密，這攤位子要坐嗎？", archetype: "deflect", retort: "好啊，一起吃一碗。" },
      { id: "neighbor-chen-salary_job-027-h", text: "薪水沒調，但我體重倒是調高了啦。", archetype: "backfire", retort: "（她沒聽懂，繼續吃）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-028",
    text: "貼春聯了，今年獎金夠包紅包嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-028-a", text: "獎金夠包，但紅包會薄到透光啦。", archetype: "backfire", retort: "……（她扶著春聯，沒接話）" },
      { id: "neighbor-chen-salary_job-028-b", text: "獎金普通啦，紅包包意思就好……", archetype: "meek", retort: "意思就好？那小孩會失望喔。" },
      { id: "neighbor-chen-salary_job-028-c", text: "獎金的事先別提，這春聯貼得真正。", archetype: "deflect", retort: "對啊，我量了很久才貼正。" },
      { id: "neighbor-chen-salary_job-028-d", text: "獎金多少是機密，紅包薄厚看緣分。", archetype: "perfect", retort: "哎唷，你這孩子講話真甜！" },
      { id: "neighbor-chen-salary_job-028-e", text: "獎金分紅到我可以買半條巷子啦。", archetype: "backfire", retort: "（她沒聽懂，繼續貼春聯）" },
      { id: "neighbor-chen-salary_job-028-f", text: "獎金的事先聊，這對聯字寫得漂亮。", archetype: "deflect", retort: "哎唷，是我孫子寫的。" },
      { id: "neighbor-chen-salary_job-028-g", text: "妳這麼關心紅包，是想多拿一包？", archetype: "landmine", retort: "你問這個幹嘛，沒禮貌！" },
      { id: "neighbor-chen-salary_job-028-h", text: "獎金不多，紅包只能包意思……", archetype: "meek", retort: "意思？那小孩會不會計較？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-029",
    text: "聽說你在做直銷？賺得到錢嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-029-a", text: "賺不賺是我的事，交朋友不缺妳。", archetype: "perfect", retort: "哎唷，你這孩子想得真開！" },
      { id: "neighbor-chen-salary_job-029-b", text: "直銷的事先別提，這燈籠掛得真喜氣。", archetype: "deflect", retort: "對啊，過年就是要熱鬧。" },
      { id: "neighbor-chen-salary_job-029-c", text: "還在學習啦，收入不太穩定……", archetype: "meek", retort: "不穩定？那正職要顧好喔。" },
      { id: "neighbor-chen-salary_job-029-d", text: "我做直銷做到快變傳銷之神啦。", archetype: "backfire", retort: "……（她掛著燈籠，沒理我）" },
      { id: "neighbor-chen-salary_job-029-e", text: "妳這麼關心直銷，是想加入拉業績？", archetype: "landmine", retort: "亂講什麼，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-029-f", text: "直銷的事先保密，燈籠是新買的？", archetype: "deflect", retort: "對啊，去年那個舊了。" },
      { id: "neighbor-chen-salary_job-029-g", text: "收入普通，還在建立客源……", archetype: "meek", retort: "客源？那要不要小心一點？" },
      { id: "neighbor-chen-salary_job-029-h", text: "直銷做到我快變人生導師啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續掛燈籠）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-030",
    text: "吳太太兒子當機師，薪水好幾十萬耶。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-030-a", text: "他真厲害，吳太太您教得真好。", archetype: "deflect", retort: "哪有，他自己考的啦。" },
      { id: "neighbor-chen-salary_job-030-b", text: "機師厲害，但至少我不用天天離家。", archetype: "perfect", retort: "哎唷，你這孩子想得真妙！" },
      { id: "neighbor-chen-salary_job-030-c", text: "我雖然不會飛，但我很會做夢啦。", archetype: "backfire", retort: "……（群組沒人回應）" },
      { id: "neighbor-chen-salary_job-030-d", text: "跟機師比真的差一截，我很普通……", archetype: "meek", retort: "普通？那要不要考慮轉行？" },
      { id: "neighbor-chen-salary_job-030-e", text: "薪水先別比，問候圖是您自己做的？", archetype: "deflect", retort: "對啊，網路上找模板啦。" },
      { id: "neighbor-chen-salary_job-030-f", text: "妳這麼羨慕機師，妳兒子當什麼？", archetype: "landmine", retort: "你問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-030-g", text: "我雖然不是機師，但我很會迷路啦。", archetype: "backfire", retort: "（群組安靜了三分鐘）" },
      { id: "neighbor-chen-salary_job-030-h", text: "跟他差很多，還在努力中……", archetype: "meek", retort: "努力中？那要努力到什麼時候？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-031",
    text: "林太太兒子升經理了，加薪不少喔。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-031-a", text: "恭喜他啦，我這邊還沒有消息……", archetype: "meek", retort: "沒消息？那要不要主動爭取？" },
      { id: "neighbor-chen-salary_job-031-b", text: "我雖然沒升官，但我很會倒垃圾啦。", archetype: "backfire", retort: "……（她拎著垃圾袋，沒理我）" },
      { id: "neighbor-chen-salary_job-031-c", text: "升經理厲害，但我不用看人臉色升。", archetype: "perfect", retort: "哎唷，你這孩子知足常樂！" },
      { id: "neighbor-chen-salary_job-031-d", text: "升遷的事先別提，您倒垃圾好快。", archetype: "deflect", retort: "習慣了，天天都準時。" },
      { id: "neighbor-chen-salary_job-031-e", text: "升遷這種事還輪不到我……", archetype: "meek", retort: "輪不到？那要不要表現積極一點？" },
      { id: "neighbor-chen-salary_job-031-f", text: "妳這麼羨慕升遷，妳兒子升了嗎？", archetype: "landmine", retort: "亂講什麼，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-031-g", text: "升遷的事先保密，垃圾車今天真準時。", archetype: "deflect", retort: "對啊，每天都六點半來。" },
      { id: "neighbor-chen-salary_job-031-h", text: "我雖然沒升官，但我升值了心情啦。", archetype: "backfire", retort: "（她沒聽懂，轉身進門）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-032",
    text: "接案自由業，收入穩定嗎？別餓肚子。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-032-a", text: "餓肚子是為了維持身材啦哈哈。", archetype: "backfire", retort: "……（她走上樓梯，沒回頭）" },
      { id: "neighbor-chen-salary_job-032-b", text: "老實說不太穩定，時好時壞……", archetype: "meek", retort: "時好時壞？那要不要找份正職？" },
      { id: "neighbor-chen-salary_job-032-c", text: "收入的事先別提，您爬樓梯好有活力。", archetype: "deflect", retort: "每天都要運動的啦。" },
      { id: "neighbor-chen-salary_job-032-d", text: "不穩定沒關係，自由比妳的意見值錢。", archetype: "perfect", retort: "哎唷，你這孩子想得真開！" },
      { id: "neighbor-chen-salary_job-032-e", text: "收入不穩，但我心臟很穩啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續往上走）" },
      { id: "neighbor-chen-salary_job-032-f", text: "收入的事先保密，樓梯間今天真乾淨。", archetype: "deflect", retort: "對啊，管理員剛打掃過。" },
      { id: "neighbor-chen-salary_job-032-g", text: "妳覺得自由業不算工作，那妳算什麼？", archetype: "landmine", retort: "你這孩子怎麼這樣講話！" },
      { id: "neighbor-chen-salary_job-032-h", text: "確實不太穩，還在努力接案……", archetype: "meek", retort: "努力接案？那有底薪保障嗎？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-033",
    text: "怎麼不考國營事業？穩定又有保障。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-033-a", text: "穩定固然好，但我不想穩到像妳這麼閒。", archetype: "perfect", retort: "哎唷，你這孩子有想法！" },
      { id: "neighbor-chen-salary_job-033-b", text: "國營的事再想想，機車停得真整齊。", archetype: "deflect", retort: "這個要練習停車技巧的啦。" },
      { id: "neighbor-chen-salary_job-033-c", text: "有想過啦，但考試真的很難……", archetype: "meek", retort: "難？那要不要多補習？" },
      { id: "neighbor-chen-salary_job-033-d", text: "我這算半個公務員啦，很穩der。", archetype: "backfire", retort: "……（她沒聽懂，牽著機車走）" },
      { id: "neighbor-chen-salary_job-033-e", text: "妳連我考不考國營都要管，很閒？", archetype: "landmine", retort: "你這什麼意思，沒禮貌！" },
      { id: "neighbor-chen-salary_job-033-f", text: "考試的事先別提，這機車保養真好。", archetype: "deflect", retort: "哎唷，騎十年還跟新的一樣。" },
      { id: "neighbor-chen-salary_job-033-g", text: "還在猶豫要不要準備考試……", archetype: "meek", retort: "猶豫什麼？早點準備比較好。" },
      { id: "neighbor-chen-salary_job-033-h", text: "我不考國營，因為我要當自己的老闆。", archetype: "backfire", retort: "（她沒聽懂，發動機車走了）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-034",
    text: "公司有給股票選擇權嗎？能發財嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-034-a", text: "選擇權的事先別提，團購真划算。", archetype: "deflect", retort: "對啊，我也團了一箱。" },
      { id: "neighbor-chen-salary_job-034-b", text: "發不發財是我的事，不用妳來算命。", archetype: "perfect", retort: "哎唷，你這孩子想法正面！" },
      { id: "neighbor-chen-salary_job-034-c", text: "選擇權多到可以買下這棟大樓啦。", archetype: "backfire", retort: "……（她拿著箱子，沒理我）" },
      { id: "neighbor-chen-salary_job-034-d", text: "有給一些，但還沒到能發財的地步……", archetype: "meek", retort: "沒到？那要等多久？" },
      { id: "neighbor-chen-salary_job-034-e", text: "股票的事先保密，團購什麼時候到貨？", archetype: "deflect", retort: "下禮拜就到了啦。" },
      { id: "neighbor-chen-salary_job-034-f", text: "妳連我股票選擇權都要查，很閒喔？", archetype: "landmine", retort: "你問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-034-g", text: "選擇權多到讓我懷疑自己是總裁啦。", archetype: "backfire", retort: "（她沒聽懂，繼續搬箱子）" },
      { id: "neighbor-chen-salary_job-034-h", text: "有給一點，但公司股價不太好……", archetype: "meek", retort: "不好？那要不要早點賣掉？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-035",
    text: "聽說你最近沒上班？在家幹嘛？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-035-a", text: "暫時待業啦，在找新機會……", archetype: "meek", retort: "待業？那生活費怎麼辦？" },
      { id: "neighbor-chen-salary_job-035-b", text: "我在家研究怎麼變有錢人啦哈哈。", archetype: "backfire", retort: "……（她抱著孫子，沒理我）" },
      { id: "neighbor-chen-salary_job-035-c", text: "待業是找方向，不是等妳來審查。", archetype: "perfect", retort: "哎唷，你這孩子想得真開！" },
      { id: "neighbor-chen-salary_job-035-d", text: "工作的事先別提，您孫子今天好可愛。", archetype: "deflect", retort: "對啊，越來越皮了。" },
      { id: "neighbor-chen-salary_job-035-e", text: "確實還沒找到，有點著急……", archetype: "meek", retort: "著急？那要不要先接個兼職？" },
      { id: "neighbor-chen-salary_job-035-f", text: "妳覺得我很閒，妳自己更閒吧？", archetype: "landmine", retort: "你這孩子怎麼這樣說話！" },
      { id: "neighbor-chen-salary_job-035-g", text: "工作的事先保密，孫子會叫人了嗎？", archetype: "deflect", retort: "會啊，昨天剛學會。" },
      { id: "neighbor-chen-salary_job-035-h", text: "待業是我人生的長假啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，逗著孫子）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-036",
    text: "跑業務油錢自己出？划算嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-036-a", text: "油錢自己出，緣分自己修啦哈哈。", archetype: "backfire", retort: "……（她繼續刷車，沒理我）" },
      { id: "neighbor-chen-salary_job-036-b", text: "確實不太划算，成本比想像高……", archetype: "meek", retort: "成本高？那有沒有算清楚？" },
      { id: "neighbor-chen-salary_job-036-c", text: "油錢的事先別提，您這車洗得真亮。", archetype: "deflect", retort: "每個禮拜都要洗一次啦。" },
      { id: "neighbor-chen-salary_job-036-d", text: "划不划算是我的帳，不用妳幫我精算。", archetype: "perfect", retort: "哎唷，你這孩子想得真透徹！" },
      { id: "neighbor-chen-salary_job-036-e", text: "油錢是我送給地球的禮物啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續洗車）" },
      { id: "neighbor-chen-salary_job-036-f", text: "工作的事先保密，這車是新買的嗎？", archetype: "deflect", retort: "不是啦，開五年了。" },
      { id: "neighbor-chen-salary_job-036-g", text: "妳連我油錢自己出都要管，很閒？", archetype: "landmine", retort: "你問這個幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-036-h", text: "確實吃緊，但沒辦法……", archetype: "meek", retort: "沒辦法？那要不要換工作？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-037",
    text: "存到財務自由了沒？不然一直洗衣店？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-037-a", text: "還沒自由，但至少不用看妳臉色。", archetype: "perfect", retort: "哎唷，你這孩子講話真幽默！" },
      { id: "neighbor-chen-salary_job-037-b", text: "財務自由再說，這烘衣機很好用喔。", archetype: "deflect", retort: "對啊，我也常用這台。" },
      { id: "neighbor-chen-salary_job-037-c", text: "還差得遠啦，目標很難達成……", archetype: "meek", retort: "很難？那要不要調整目標？" },
      { id: "neighbor-chen-salary_job-037-d", text: "財務自由對我來說是心靈層面的。", archetype: "backfire", retort: "……（她把衣服放進洗衣機，沒理我）" },
      { id: "neighbor-chen-salary_job-037-e", text: "妳連我財務自由沒都要問，妳自由嗎？", archetype: "landmine", retort: "你這孩子問這什麼，沒禮貌！" },
      { id: "neighbor-chen-salary_job-037-f", text: "財務的事先保密，您衣服洗得真香。", archetype: "deflect", retort: "這個牌子的洗衣精不錯。" },
      { id: "neighbor-chen-salary_job-037-g", text: "還在努力存，速度比較慢……", archetype: "meek", retort: "慢？那要不要多兼一份工作？" },
      { id: "neighbor-chen-salary_job-037-h", text: "我財務不自由，但心靈超級自由啦。", archetype: "backfire", retort: "（她沒聽懂，按下洗衣機按鈕）" },
    ],
  },
] satisfies Question[];
