// situations: 001 社區大門口, 002 電梯裡, 003 倒垃圾時垃圾車前, 004 傳統市場買菜,
// 005 社區LINE群組, 006 巷口土地公廟, 007 送年節禮盒到你家, 008 地下停車場,
// 009 看到外送員送到你家, 010 陽台聽你講電話, 011 巷口閒聊, 012 大樓中庭交誼廳,
// 013 早餐店排隊, 014 資源回收日, 015 便利商店結帳, 016 陽台曬衣服,
// 017 幫你代收包裹, 018 巷口等紅綠燈, 019 遛狗巧遇, 020 社區公佈欄前
import type { Question } from "@/content/types";

export default [
  {
    id: "neighbor-chen-salary_job-001",
    text: "薪水到底多少？我跟你媽講你都不說。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-001-a", text: "陳太太您猜對算您贏，紅包加倍。", archetype: "perfect", retort: "哎唷你這孩子，會做人！" },
      { id: "neighbor-chen-salary_job-001-b", text: "還好啦，倒是您孫子這次考怎樣？", archetype: "deflect", retort: "少來，轉移話題喔你。" },
      { id: "neighbor-chen-salary_job-001-c", text: "普普通通啦，夠生活……", archetype: "meek", retort: "普通是多少？我問你媽就知道。" },
      { id: "neighbor-chen-salary_job-001-d", text: "我領的薪水，都拿去交朋友了。", archetype: "backfire", retort: "……（她轉頭跟別人打招呼）" },
      { id: "neighbor-chen-salary_job-001-e", text: "陳太太您退休金領多少？", archetype: "landmine", retort: "你這什麼態度！我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-001-f", text: "薪水的事不重要，您氣色真好。", archetype: "deflect", retort: "喔你就會講好聽話。" },
      { id: "neighbor-chen-salary_job-001-g", text: "最近比較少加班，薪水少一點……", archetype: "meek", retort: "少加班？是不是快被資遣了？" },
      { id: "neighbor-chen-salary_job-001-h", text: "我的薪水是秘密，跟初戀一樣。", archetype: "backfire", retort: "（她愣住，沒接話）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-002",
    text: "聽說公司加薪，你加了多少？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-002-a", text: "加薪不重要，陳太太您氣色真好。", archetype: "deflect", retort: "你喔，就會拍馬屁。" },
      { id: "neighbor-chen-salary_job-002-b", text: "加多少不重要，加班費才是重點。", archetype: "perfect", retort: "哎唷，說得好，有道理！" },
      { id: "neighbor-chen-salary_job-002-c", text: "加了一個銅板，夠買貼紙。", archetype: "backfire", retort: "……（她沒聽懂，按了樓層鈕）" },
      { id: "neighbor-chen-salary_job-002-d", text: "沒加多少啦，公司說不景氣……", archetype: "meek", retort: "不景氣？那你要不要換工作？" },
      { id: "neighbor-chen-salary_job-002-e", text: "加薪的事，改天跟您孫子請教。", archetype: "deflect", retort: "少來，他還在唸書咧。" },
      { id: "neighbor-chen-salary_job-002-f", text: "陳太太您先生退休金加了沒？", archetype: "landmine", retort: "問這什麼，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-002-g", text: "加薪加到心花朵朵開啦。", archetype: "backfire", retort: "（她皺眉，假裝看手機）" },
      { id: "neighbor-chen-salary_job-002-h", text: "加一點點，還不夠付停車費……", archetype: "meek", retort: "那麼少？你要不要去理論？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-003",
    text: "聽說你要跳槽？新工作薪水多少？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-003-a", text: "還在考慮啦，還沒確定……", archetype: "meek", retort: "還沒確定？那你不是在唬爛？" },
      { id: "neighbor-chen-salary_job-003-b", text: "跳槽跳到外太空去啦哈哈。", archetype: "backfire", retort: "……（她拿著垃圾袋愣住）" },
      { id: "neighbor-chen-salary_job-003-c", text: "薪水多少是秘密，福氣可以公開。", archetype: "perfect", retort: "哎唷你這孩子，嘴巴真甜！" },
      { id: "neighbor-chen-salary_job-003-d", text: "還在談，您資源回收分類好厲害。", archetype: "deflect", retort: "這個要練習的啦。" },
      { id: "neighbor-chen-salary_job-003-e", text: "薪水差不多，只是換個環境……", archetype: "meek", retort: "差不多？那換來換去幹嘛？" },
      { id: "neighbor-chen-salary_job-003-f", text: "陳太太您先生當年也換過工作吧？", archetype: "landmine", retort: "你怎麼哪壺不開提哪壺！" },
      { id: "neighbor-chen-salary_job-003-g", text: "薪水先不說，您今天倒垃圾好準時。", archetype: "deflect", retort: "哎唷，這個要習慣的。" },
      { id: "neighbor-chen-salary_job-003-h", text: "新工作薪水，天機不可洩漏啦。", archetype: "backfire", retort: "（她白眼，轉身走了）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-004",
    text: "聽說你買股票，賺了還是賠了？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-004-a", text: "賺賠都是數字，心境才重要啦。", archetype: "backfire", retort: "……（她繼續挑菜，沒理我）" },
      { id: "neighbor-chen-salary_job-004-b", text: "最近賠一點啦，市場不好……", archetype: "meek", retort: "賠多少？是不是很嚴重？" },
      { id: "neighbor-chen-salary_job-004-c", text: "股票先不說，這攤的菜好新鮮喔。", archetype: "deflect", retort: "對啊，我常來買。" },
      { id: "neighbor-chen-salary_job-004-d", text: "賠的錢當繳學費，學到東西最賺。", archetype: "perfect", retort: "哎唷，你這樣想很成熟耶！" },
      { id: "neighbor-chen-salary_job-004-e", text: "我炒股炒到懷疑人生哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續秤重）" },
      { id: "neighbor-chen-salary_job-004-f", text: "投資的事改天請教您，您比較懂。", archetype: "deflect", retort: "我哪懂，我都定存啦。" },
      { id: "neighbor-chen-salary_job-004-g", text: "陳太太您該不會也在玩飆股吧？", archetype: "landmine", retort: "你亂講什麼，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-004-h", text: "小賠一點，還在學習經驗……", archetype: "meek", retort: "學習經驗？那要學到什麼時候？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-005",
    text: "群組看你在接案，賺得比正職多？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-005-a", text: "賺多少不重要，做喜歡的事最好。", archetype: "perfect", retort: "哎唷，說得真好聽！" },
      { id: "neighbor-chen-salary_job-005-b", text: "副業還好啦，您團購的東西好讚。", archetype: "deflect", retort: "對啊，下次找你一起團。" },
      { id: "neighbor-chen-salary_job-005-c", text: "剛起步啦，收入還不太穩定……", archetype: "meek", retort: "不穩定？那正職不能丟喔。" },
      { id: "neighbor-chen-salary_job-005-d", text: "副業做到我快變超人了哈哈。", archetype: "backfire", retort: "（群組沒人回應，一片安靜）" },
      { id: "neighbor-chen-salary_job-005-e", text: "陳太太您女兒不也在做直銷嗎？", archetype: "landmine", retort: "亂講什麼，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-005-f", text: "接案的事先不提，新年快樂啦！", archetype: "deflect", retort: "哎唷，你也是。" },
      { id: "neighbor-chen-salary_job-005-g", text: "賺一點零用錢啦，不算什麼……", archetype: "meek", retort: "零用錢？那正職夠花嗎？" },
      { id: "neighbor-chen-salary_job-005-h", text: "副業做到快變包租公啦哈哈。", archetype: "backfire", retort: "（沒人在群組裡回應）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-006",
    text: "來拜拜求財運喔？今年年薪多少？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-006-a", text: "先求平安啦，陳太太您要不要拜？", archetype: "deflect", retort: "對啦對啦，平安最重要。" },
      { id: "neighbor-chen-salary_job-006-b", text: "年薪多少不重要，土地公知道就好。", archetype: "perfect", retort: "哎唷，你這樣講也對！" },
      { id: "neighbor-chen-salary_job-006-c", text: "我年薪高到土地公都嫉妒啦。", archetype: "backfire", retort: "……（她合掌，沒理我）" },
      { id: "neighbor-chen-salary_job-006-d", text: "普通上班族薪水啦，沒特別高……", archetype: "meek", retort: "沒特別高？那要不要換跑道？" },
      { id: "neighbor-chen-salary_job-006-e", text: "年薪先別提，您要不要一起點香？", archetype: "deflect", retort: "好啊，一起拜比較有效。" },
      { id: "neighbor-chen-salary_job-006-f", text: "陳太太您該不會也想中樂透吧？", archetype: "landmine", retort: "你這孩子講話沒大沒小！" },
      { id: "neighbor-chen-salary_job-006-g", text: "我拜拜是拜心安，錢自然來啦。", archetype: "backfire", retort: "（她沒聽懂，繼續拜）" },
      { id: "neighbor-chen-salary_job-006-h", text: "夠生活啦，存款不多……", archetype: "meek", retort: "存款不多？那怎麼辦？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-007",
    text: "陳太太送禮盒來，順便問年終多少。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-007-a", text: "還沒發啦，公司說要看業績……", archetype: "meek", retort: "看業績？那你緊張嗎？" },
      { id: "neighbor-chen-salary_job-007-b", text: "年終領到手軟，手已經斷了哈哈。", archetype: "backfire", retort: "……（她笑不出來，收回手）" },
      { id: "neighbor-chen-salary_job-007-c", text: "多少不重要，禮盒我很喜歡，謝謝！", archetype: "perfect", retort: "哎唷，你這孩子嘴巴真甜！" },
      { id: "neighbor-chen-salary_job-007-d", text: "年終先不說，這禮盒是您自己做的？", archetype: "deflect", retort: "哪有，是超市買的啦。" },
      { id: "neighbor-chen-salary_job-007-e", text: "應該不多，公司今年不太好……", archetype: "meek", retort: "不好？那你要小心工作喔。" },
      { id: "neighbor-chen-salary_job-007-f", text: "陳太太您先生退休有領年終嗎？", archetype: "landmine", retort: "問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-007-g", text: "獎金的事保密，禮盒謝謝您費心。", archetype: "deflect", retort: "哎唷，你真貼心。" },
      { id: "neighbor-chen-salary_job-007-h", text: "年終多到可以買下這條巷子啦。", archetype: "backfire", retort: "（她愣住，把禮盒放下就走）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-008",
    text: "還不去考公務員？鐵飯碗多穩啊。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-008-a", text: "我這工作穩得像國營事業啦哈哈。", archetype: "backfire", retort: "……（她把車門關上，沒回應）" },
      { id: "neighbor-chen-salary_job-008-b", text: "有想過啦，但準備考試好難……", archetype: "meek", retort: "難？那就要更努力準備啊。" },
      { id: "neighbor-chen-salary_job-008-c", text: "考試的事再想想，您車停這麼準耶。", archetype: "deflect", retort: "這個要練習停車的啦。" },
      { id: "neighbor-chen-salary_job-008-d", text: "鐵飯碗穩，但這行更適合我啦。", archetype: "perfect", retort: "哎唷，你有自己的想法，好！" },
      { id: "neighbor-chen-salary_job-008-e", text: "我的工作是黃金飯碗，比鐵更貴啦。", archetype: "backfire", retort: "（她沒接話，走向電梯）" },
      { id: "neighbor-chen-salary_job-008-f", text: "考試的事先不提，您車開得真穩。", archetype: "deflect", retort: "哎唷，開了三十年了啦。" },
      { id: "neighbor-chen-salary_job-008-g", text: "陳太太您兒子考公務員考幾次了？", archetype: "landmine", retort: "你這孩子怎麼這樣講話！" },
      { id: "neighbor-chen-salary_job-008-h", text: "還在猶豫要不要考……", archetype: "meek", retort: "猶豫什麼？時間不等人喔。" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-009",
    text: "又叫外送？加班到沒空煮飯喔？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-009-a", text: "對啊，加班賺的錢剛好吃好料。", archetype: "perfect", retort: "哎唷，你這樣想很聰明！" },
      { id: "neighbor-chen-salary_job-009-b", text: "加班還好啦，您今天菜煮得真香。", archetype: "deflect", retort: "哎唷，你聞得到喔，進來吃。" },
      { id: "neighbor-chen-salary_job-009-c", text: "最近比較忙，責任制沒加班費……", archetype: "meek", retort: "沒加班費？那怎麼受得了？" },
      { id: "neighbor-chen-salary_job-009-d", text: "加班加到我變成夜行動物啦。", archetype: "backfire", retort: "……（她皺眉，聽不太懂）" },
      { id: "neighbor-chen-salary_job-009-e", text: "陳太太您先生以前也常加班嗎？", archetype: "landmine", retort: "問這個幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-009-f", text: "加班的事先別提，這外送看起來好吃。", archetype: "deflect", retort: "哎唷，要不要分我一口。" },
      { id: "neighbor-chen-salary_job-009-g", text: "常常加班，身體有點吃不消……", archetype: "meek", retort: "吃不消？那要不要看醫生？" },
      { id: "neighbor-chen-salary_job-009-h", text: "我加班加到快變公司股東啦。", archetype: "backfire", retort: "（她沒聽懂，轉頭進門）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-010",
    text: "聽你講電話，是不是快被轉正了？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-010-a", text: "轉正的事再說，陳太太您耳朵真靈。", archetype: "deflect", retort: "哎唷，隔壁陽台聽得一清二楚。" },
      { id: "neighbor-chen-salary_job-010-b", text: "轉不轉正不重要，做得開心最重要。", archetype: "perfect", retort: "哎唷，你這樣想法很正面！" },
      { id: "neighbor-chen-salary_job-010-c", text: "轉正之後我就是傳說中的正職啦。", archetype: "backfire", retort: "……（她沒聽懂，繼續曬衣服）" },
      { id: "neighbor-chen-salary_job-010-d", text: "還在試用期，有點緊張……", archetype: "meek", retort: "緊張什麼？表現好就好啦。" },
      { id: "neighbor-chen-salary_job-010-e", text: "試用期的事先別提，您衣服曬得真整齊。", archetype: "deflect", retort: "這個要有技巧的啦。" },
      { id: "neighbor-chen-salary_job-010-f", text: "陳太太是不是常常在偷聽電話？", archetype: "landmine", retort: "你這孩子怎麼這樣說，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-010-g", text: "我這試用期用得比正職還爽啦。", archetype: "backfire", retort: "（她沒回應，轉身進屋）" },
      { id: "neighbor-chen-salary_job-010-h", text: "還不確定會不會留用……", archetype: "meek", retort: "不確定？那要有備案喔。" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-011",
    text: "現在年輕人起薪這麼低喔？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-011-a", text: "是低啦，物價漲比薪水快……", archetype: "meek", retort: "那怎麼夠花？要多存一點。" },
      { id: "neighbor-chen-salary_job-011-b", text: "起薪低但我夢想很高啦哈哈。", archetype: "backfire", retort: "……（她搖搖頭，沒接話）" },
      { id: "neighbor-chen-salary_job-011-c", text: "起薪低沒關係，我漲得比別人快。", archetype: "perfect", retort: "哎唷，你這孩子有志氣！" },
      { id: "neighbor-chen-salary_job-011-d", text: "薪水先別提，您孫子最近長好高。", archetype: "deflect", retort: "對啊，長好快呢。" },
      { id: "neighbor-chen-salary_job-011-e", text: "是有點低，但先求有經驗……", archetype: "meek", retort: "求經驗？那要撐到什麼時候？" },
      { id: "neighbor-chen-salary_job-011-f", text: "陳太太您那年代物價才多少啊？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-011-g", text: "起薪先別聊，巷口這攤新開的耶。", archetype: "deflect", retort: "對啊，聽說不錯吃。" },
      { id: "neighbor-chen-salary_job-011-h", text: "起薪低沒關係，我靠愛發電啦。", archetype: "backfire", retort: "（她一臉困惑，沒接話）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-012",
    text: "你老闆對你好嗎？聽說很兇喔。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-012-a", text: "我老闆兇歸兇，抱起來很暖啦哈哈。", archetype: "backfire", retort: "……（她一臉尷尬，看向別處）" },
      { id: "neighbor-chen-salary_job-012-b", text: "還好啦，有時候壓力比較大……", archetype: "meek", retort: "壓力大？要不要考慮換工作？" },
      { id: "neighbor-chen-salary_job-012-c", text: "老闆的事先別提，這椅子好舒服。", archetype: "deflect", retort: "對啊，社區裝潢得不錯。" },
      { id: "neighbor-chen-salary_job-012-d", text: "老闆兇沒關係，學到的比罵的多。", archetype: "perfect", retort: "哎唷，你這樣想很成熟！" },
      { id: "neighbor-chen-salary_job-012-e", text: "我老闆兇是因為太愛我了啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，喝了口茶）" },
      { id: "neighbor-chen-salary_job-012-f", text: "老闆的事改天聊，您今天氣色真好。", archetype: "deflect", retort: "哎唷，你嘴巴真甜。" },
      { id: "neighbor-chen-salary_job-012-g", text: "陳太太您以前上班被罵過嗎？", archetype: "landmine", retort: "你問這個幹嘛，沒禮貌！" },
      { id: "neighbor-chen-salary_job-012-h", text: "有時候會被念，但還在學習……", archetype: "meek", retort: "被念？那要不要考慮離職？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-013",
    text: "聽說你要離職？下一步打算怎樣？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-013-a", text: "離職是為了走更遠的路，放心。", archetype: "perfect", retort: "哎唷，你這孩子想得真遠！" },
      { id: "neighbor-chen-salary_job-013-b", text: "離職的事再想想，您早餐都吃這攤喔？", archetype: "deflect", retort: "對啊，吃十年了。" },
      { id: "neighbor-chen-salary_job-013-c", text: "還沒想好，先休息一下……", archetype: "meek", retort: "休息？那收入怎麼辦？" },
      { id: "neighbor-chen-salary_job-013-d", text: "離職後我要環遊世界啦哈哈。", archetype: "backfire", retort: "……（她點餐，沒理我）" },
      { id: "neighbor-chen-salary_job-013-e", text: "陳太太您兒子當年不也裸辭過？", archetype: "landmine", retort: "你怎麼哪壺不開提哪壺！" },
      { id: "neighbor-chen-salary_job-013-f", text: "離職的事先別提，這蛋餅看起來好吃。", archetype: "deflect", retort: "要不要幫你多點一份。" },
      { id: "neighbor-chen-salary_job-013-g", text: "老實說，最近工作壓力有點大……", archetype: "meek", retort: "壓力大？要不要找人聊聊？" },
      { id: "neighbor-chen-salary_job-013-h", text: "離職後我要去當網紅啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續排隊）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-014",
    text: "做業務壓力大吧？業績獎金好賺嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-014-a", text: "業績先不說，您分類回收好仔細喔。", archetype: "deflect", retort: "這個要細心的啦。" },
      { id: "neighbor-chen-salary_job-014-b", text: "業績有壓力，但抽成讓我更有動力。", archetype: "perfect", retort: "哎唷，你這樣想法很積極！" },
      { id: "neighbor-chen-salary_job-014-c", text: "業績壓力大到我快變回收物啦。", archetype: "backfire", retort: "……（她沒聽懂，繼續分類）" },
      { id: "neighbor-chen-salary_job-014-d", text: "有壓力啦，這個月業績不太好……", archetype: "meek", retort: "不好？那獎金會少很多嗎？" },
      { id: "neighbor-chen-salary_job-014-e", text: "業績的事先別提，這瓶子要壓扁再丟？", archetype: "deflect", retort: "對啊，比較省空間。" },
      { id: "neighbor-chen-salary_job-014-f", text: "陳太太您先生做業務業績好嗎？", archetype: "landmine", retort: "問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-014-g", text: "業績壓力大到我變人體壓力鍋啦。", archetype: "backfire", retort: "（她沒聽懂，繼續整理回收）" },
      { id: "neighbor-chen-salary_job-014-h", text: "業績普通，獎金也不多……", archetype: "meek", retort: "不多？那要不要換部門？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-015",
    text: "看你都買便當，是不是在存錢啊？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-015-a", text: "是啦，最近比較節省……", archetype: "meek", retort: "節省？存了多少了？" },
      { id: "neighbor-chen-salary_job-015-b", text: "我存的是回憶，不是錢啦哈哈。", archetype: "backfire", retort: "……（她結帳，沒接話）" },
      { id: "neighbor-chen-salary_job-015-c", text: "存錢是為了以後更自由，值得。", archetype: "perfect", retort: "哎唷，你這孩子想得真周到！" },
      { id: "neighbor-chen-salary_job-015-d", text: "存錢的事先別提，這飯糰新出的？", archetype: "deflect", retort: "聽說不錯，要不要試試。" },
      { id: "neighbor-chen-salary_job-015-e", text: "存一點是一點，速度不快……", archetype: "meek", retort: "不快？那目標多久達成？" },
      { id: "neighbor-chen-salary_job-015-f", text: "陳太太您退休金存夠了嗎？", archetype: "landmine", retort: "你這孩子沒大沒小，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-015-g", text: "存款的事保密，您今天買好多東西喔。", archetype: "deflect", retort: "對啊，過年要用的。" },
      { id: "neighbor-chen-salary_job-015-h", text: "我存錢存到自己都佩服自己啦。", archetype: "backfire", retort: "（她沒聽懂，拿了發票就走）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-016",
    text: "在家上班喔？看你整天都在陽台。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-016-a", text: "我在陽台上班，風景好效率高啦。", archetype: "backfire", retort: "……（她繼續曬衣服，沒接話）" },
      { id: "neighbor-chen-salary_job-016-b", text: "是遠距上班啦，但常常忘記下班……", archetype: "meek", retort: "忘記下班？那不是更累？" },
      { id: "neighbor-chen-salary_job-016-c", text: "上班的事先別提，您衣服曬得真整齊。", archetype: "deflect", retort: "這個有訣竅的啦。" },
      { id: "neighbor-chen-salary_job-016-d", text: "在家上班效率更高，還能曬太陽。", archetype: "perfect", retort: "哎唷，你這樣想真聰明！" },
      { id: "neighbor-chen-salary_job-016-e", text: "在家上班就是躺著上班啦哈哈。", archetype: "backfire", retort: "（她瞄了我一眼，沒說話）" },
      { id: "neighbor-chen-salary_job-016-f", text: "工作的事改天聊，您這件衣服好看。", archetype: "deflect", retort: "哎唷，這是舊的啦。" },
      { id: "neighbor-chen-salary_job-016-g", text: "陳太太您整天在陽台是在監視我？", archetype: "landmine", retort: "你這什麼話，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-016-h", text: "在家上班有點孤單，效率也普通……", archetype: "meek", retort: "孤單？那要不要多出門走走？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-017",
    text: "包裹又這麼多，薪水都花光了吧？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-017-a", text: "花錢買開心，開心比存款重要一點。", archetype: "perfect", retort: "哎唷，你這孩子會過生活！" },
      { id: "neighbor-chen-salary_job-017-b", text: "花錢的事先別提，謝謝您幫我代收。", archetype: "deflect", retort: "不客氣啦，鄰居互相的。" },
      { id: "neighbor-chen-salary_job-017-c", text: "有點花超過，這個月要省一點……", archetype: "meek", retort: "超過？那下個月怎麼辦？" },
      { id: "neighbor-chen-salary_job-017-d", text: "我這是投資自己，包裹就是股票啦。", archetype: "backfire", retort: "……（她把包裹遞給我，沒接話）" },
      { id: "neighbor-chen-salary_job-017-e", text: "陳太太您怎麼知道我包裹很多？", archetype: "landmine", retort: "我當然知道，我要跟你媽講你亂花錢！" },
      { id: "neighbor-chen-salary_job-017-f", text: "包裹的事先別聊，您最近氣色真好。", archetype: "deflect", retort: "哎唷，你嘴巴真甜。" },
      { id: "neighbor-chen-salary_job-017-g", text: "薪水確實花得比較快……", archetype: "meek", retort: "那要不要記帳看看？" },
      { id: "neighbor-chen-salary_job-017-h", text: "包裹越多代表我越成功啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，轉身進門）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-018",
    text: "現在物價漲成這樣，薪水夠花嗎？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-018-a", text: "夠不夠先別說，您買菜是不是也漲？", archetype: "deflect", retort: "對啊，漲得我都不敢買肉。" },
      { id: "neighbor-chen-salary_job-018-b", text: "夠不夠不重要，會過日子最重要。", archetype: "perfect", retort: "哎唷，你這孩子講話有智慧！" },
      { id: "neighbor-chen-salary_job-018-c", text: "薪水追不上物價，但追得上我啦。", archetype: "backfire", retort: "……（她皺眉，沒聽懂）" },
      { id: "neighbor-chen-salary_job-018-d", text: "老實說有點吃緊，最近比較省……", archetype: "meek", retort: "吃緊？那要不要跟家裡拿一點？" },
      { id: "neighbor-chen-salary_job-018-e", text: "物價的事先別提，紅綠燈快變了。", archetype: "deflect", retort: "對啦，快走快走。" },
      { id: "neighbor-chen-salary_job-018-f", text: "陳太太您那年代薪水也不高吧？", archetype: "landmine", retort: "你這什麼態度，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-018-g", text: "追不上物價，但我心態超前啦。", archetype: "backfire", retort: "（她沒聽懂，繼續等燈）" },
      { id: "neighbor-chen-salary_job-018-h", text: "確實有點難撐，還在想辦法……", archetype: "meek", retort: "難撐？要不要考慮兼差？" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-019",
    text: "聽說有獵頭挖你？開的薪水多少？",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-019-a", text: "還在談啦，還沒確定條件……", archetype: "meek", retort: "沒確定？那要不要快點決定？" },
      { id: "neighbor-chen-salary_job-019-b", text: "獵頭都搶著要我，我快變獵物啦。", archetype: "backfire", retort: "……（她逗著狗，沒理我）" },
      { id: "neighbor-chen-salary_job-019-c", text: "薪水多少先保密，機會要把握。", archetype: "perfect", retort: "哎唷，你這孩子有想法！" },
      { id: "neighbor-chen-salary_job-019-d", text: "挖角的事先別提，這隻狗好可愛。", archetype: "deflect", retort: "對啊，養三年了。" },
      { id: "neighbor-chen-salary_job-019-e", text: "開的條件還不錯，但還在猶豫……", archetype: "meek", retort: "猶豫什麼？機會不等人喔。" },
      { id: "neighbor-chen-salary_job-019-f", text: "陳太太您先生退休前有人挖角嗎？", archetype: "landmine", retort: "你問這幹嘛，我要跟你媽講！" },
      { id: "neighbor-chen-salary_job-019-g", text: "挖角的事先保密，您狗今天特別乖。", archetype: "deflect", retort: "哎唷，牠今天心情好。" },
      { id: "neighbor-chen-salary_job-019-h", text: "獵頭挖我，是因為我太耀眼啦哈哈。", archetype: "backfire", retort: "（她沒聽懂，繼續遛狗）" },
    ],
  },
  {
    id: "neighbor-chen-salary_job-020",
    text: "上次看到你薪水單，領得不多喔。",
    topic: "salary_job",
    bossId: "neighbor-chen",
    options: [
      { id: "neighbor-chen-salary_job-020-a", text: "那是我小金庫，本體藏更深啦。", archetype: "backfire", retort: "……（她一臉狐疑，沒接話）" },
      { id: "neighbor-chen-salary_job-020-b", text: "是不多啦，扣一扣剩沒多少……", archetype: "meek", retort: "扣什麼扣這麼多？" },
      { id: "neighbor-chen-salary_job-020-c", text: "薪水單的事先別提，這活動不錯。", archetype: "deflect", retort: "對啊，要不要一起報名。" },
      { id: "neighbor-chen-salary_job-020-d", text: "薪水單只是數字，我的價值不只這樣。", archetype: "perfect", retort: "哎唷，你這孩子想得真開！" },
      { id: "neighbor-chen-salary_job-020-e", text: "薪水單是誘餌，真正財富在心裡啦。", archetype: "backfire", retort: "（她沒聽懂，看向公佈欄）" },
      { id: "neighbor-chen-salary_job-020-f", text: "薪水的事先別聊，這公告寫什麼？", archetype: "deflect", retort: "喔是社區大掃除的通知。" },
      { id: "neighbor-chen-salary_job-020-g", text: "陳太太您怎麼會看到我薪水單？", archetype: "landmine", retort: "我剛好經過看到的，你態度這麼差！" },
      { id: "neighbor-chen-salary_job-020-h", text: "確實不多，還在努力存……", archetype: "meek", retort: "努力存？那要存到什麼時候？" },
    ],
  },
] satisfies Question[];
