// situations: 比較紅包包多大包、比較婚禮桌數排場、比較年夜飯廚藝、
// 比較LINE好友人脈廣度、比較適應婚姻生活快慢、比較行事曆忙碌or悠閒、
// 比較早起作息規律、比較考證照進修、比較養寵物、比較穿搭品味、
// 比較退休金規劃早晚、比較另一半送禮浪漫、比較過年出國計畫、
// 比較買國外資產/美股、比較生小孩前後睡眠品質、比較生活儀式感小確幸
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-comparison-021",
    text: "我今年紅包包得比較大包，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-021-a",
        text: "包這麼大方，你們家真的很闊氣。",
        archetype: "deflect",
        retort: "還好啦，量力而為啦（笑）。",
      },
      {
        id: "biaojie-comparison-021-b",
        text: "我今年包得比較保守，錢有點緊……",
        archetype: "meek",
        retort: "緊的話量力而為就好。",
      },
      {
        id: "biaojie-comparison-021-c",
        text: "包多少不重要，你倒是算得很勤。",
        archetype: "perfect",
        retort: "……我只是隨口聊聊而已（笑）。",
      },
      {
        id: "biaojie-comparison-021-d",
        text: "包大包，那我紅包袋比較大張湊數。",
        archetype: "backfire",
        retort: "……紅包袋大小跟金額沒關係啦（笑）。",
      },
      {
        id: "biaojie-comparison-021-e",
        text: "表姊你紅包包得真的很用心。",
        archetype: "deflect",
        retort: "謝謝，看大家開心就值得（笑）。",
      },
      {
        id: "biaojie-comparison-021-f",
        text: "沒人問，你哭爸炫耀什麼？",
        archetype: "landmine",
        retort: "……好，我不講了。",
      },
      {
        id: "biaojie-comparison-021-g",
        text: "紅包預算我還沒抓好……",
        archetype: "meek",
        retort: "沒抓好的話要提早規劃。",
      },
      {
        id: "biaojie-comparison-021-h",
        text: "大包，那我包的都是舊鈔比較厚。",
        archetype: "backfire",
        retort: "……舊鈔厚度不算多包啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-022",
    text: "我婚禮辦了二十桌，你以後打算怎麼辦？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-022-a",
        text: "二十桌，你婚禮一定辦得很風光。",
        archetype: "deflect",
        retort: "對啊，那天真的很熱鬧（笑）。",
      },
      {
        id: "biaojie-comparison-022-b",
        text: "我還沒想過婚禮要怎麼辦……",
        archetype: "meek",
        retort: "還沒想的話要早點規劃預算。",
      },
      {
        id: "biaojie-comparison-022-c",
        text: "二十桌很風光，誰付的錢比較好奇。",
        archetype: "perfect",
        retort: "……錢的事，反正付清就好（笑）。",
      },
      {
        id: "biaojie-comparison-022-d",
        text: "二十桌，那我辦流水席在夜市。",
        archetype: "backfire",
        retort: "……夜市應該沒辦法包場吧（笑）。",
      },
      {
        id: "biaojie-comparison-022-e",
        text: "表姊你婚紗照一定拍得很美。",
        archetype: "deflect",
        retort: "謝謝，挑禮服挑了好久呢（笑）。",
      },
      {
        id: "biaojie-comparison-022-f",
        text: "你老公呢？該不會沒出席吧？",
        archetype: "landmine",
        retort: "……他很忙，別提了。",
      },
      {
        id: "biaojie-comparison-022-g",
        text: "我對婚禮的排場沒什麼概念……",
        archetype: "meek",
        retort: "沒概念的話可以多參考別人。",
      },
      {
        id: "biaojie-comparison-022-h",
        text: "風光，那我到時候辦直播婚禮。",
        archetype: "backfire",
        retort: "……那個好像少了點儀式感（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-023",
    text: "我年夜飯全部自己煮，你會下廚嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-023-a",
        text: "全部自己煮，你廚藝一定很厲害。",
        archetype: "deflect",
        retort: "還好啦，練久了就會了（笑）。",
      },
      {
        id: "biaojie-comparison-023-b",
        text: "我平常都吃外食，很少下廚……",
        archetype: "meek",
        retort: "很少下廚的話要學幾道拿手菜。",
      },
      {
        id: "biaojie-comparison-023-c",
        text: "煮一桌是愛心，還是逼婆家閉嘴？",
        archetype: "perfect",
        retort: "……才，才沒有這種事（笑）。",
      },
      {
        id: "biaojie-comparison-023-d",
        text: "全部自己煮，那我全部自己叫外送。",
        archetype: "backfire",
        retort: "……外送不算自己煮的啦（笑）。",
      },
      {
        id: "biaojie-comparison-023-e",
        text: "表姊你顧小孩還能下廚，太強了。",
        archetype: "deflect",
        retort: "習慣了，時間擠一擠就有（笑）。",
      },
      {
        id: "biaojie-comparison-023-f",
        text: "自己煮，大概是怕小孩鬧丟臉。",
        archetype: "landmine",
        retort: "……才不是，別亂講。",
      },
      {
        id: "biaojie-comparison-023-g",
        text: "我煮的東西常常失敗……",
        archetype: "meek",
        retort: "失敗沒關係，多練習就會了。",
      },
      {
        id: "biaojie-comparison-023-h",
        text: "廚藝好，那我開瓦斯的技術很純熟。",
        archetype: "backfire",
        retort: "……開瓦斯不算廚藝啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-024",
    text: "我LINE好友快兩千個，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-024-a",
        text: "兩千個好友，你人脈真的很廣。",
        archetype: "deflect",
        retort: "還好啦，都是工作認識的（笑）。",
      },
      {
        id: "biaojie-comparison-024-b",
        text: "我朋友圈比較小，沒那麼多聯絡人……",
        archetype: "meek",
        retort: "小圈子也好，比較單純。",
      },
      {
        id: "biaojie-comparison-024-c",
        text: "兩千個朋友，你記得住幾個？",
        archetype: "perfect",
        retort: "……大部分都記得啦（笑）。",
      },
      {
        id: "biaojie-comparison-024-d",
        text: "兩千個，那我遊戲好友也快五個。",
        archetype: "backfire",
        retort: "……那個規模差太多了啦（笑）。",
      },
      {
        id: "biaojie-comparison-024-e",
        text: "表姊你交際能力真的一流。",
        archetype: "deflect",
        retort: "謝謝，都是慢慢累積的（笑）。",
      },
      {
        id: "biaojie-comparison-024-f",
        text: "兩千個，該不會婆婆也在看？",
        archetype: "landmine",
        retort: "……那是家族群組啦。",
      },
      {
        id: "biaojie-comparison-024-g",
        text: "我不太擅長維持人際關係……",
        archetype: "meek",
        retort: "不擅長的話要多主動聯絡。",
      },
      {
        id: "biaojie-comparison-024-h",
        text: "人脈廣，那我認識的貓比較多。",
        archetype: "backfire",
        retort: "……貓應該不算人脈吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-025",
    text: "我一結婚就很快適應了，你會嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-025-a",
        text: "你適應得這麼快，一定很有智慧。",
        archetype: "deflect",
        retort: "還好啦，都是磨合出來的（笑）。",
      },
      {
        id: "biaojie-comparison-025-b",
        text: "我對婚姻這件事還很沒把握……",
        archetype: "meek",
        retort: "沒把握的話要多觀察多學習。",
      },
      {
        id: "biaojie-comparison-025-c",
        text: "適應快不快，你先生知道嗎？",
        archetype: "perfect",
        retort: "……這要問他才知道（笑）。",
      },
      {
        id: "biaojie-comparison-025-d",
        text: "適應快，那我適應躺平的速度更快。",
        archetype: "backfire",
        retort: "……躺平跟適應婚姻不太一樣（笑）。",
      },
      {
        id: "biaojie-comparison-025-e",
        text: "表姊你經營婚姻的態度真的好。",
        archetype: "deflect",
        retort: "謝謝，都是互相體諒的（笑）。",
      },
      {
        id: "biaojie-comparison-025-f",
        text: "適應快，你老公到底去哪了？",
        archetype: "landmine",
        retort: "……他在忙，別亂講。",
      },
      {
        id: "biaojie-comparison-025-g",
        text: "我還沒有這方面的經驗可以說……",
        archetype: "meek",
        retort: "沒經驗的話以後會慢慢懂。",
      },
      {
        id: "biaojie-comparison-025-h",
        text: "很快，那我換工作的速度也很快。",
        archetype: "backfire",
        retort: "……那個好像不是同一件事（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-026",
    text: "我行事曆滿到明年，你有這麼忙嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-026-a",
        text: "滿到明年，你真的是超級行動派。",
        archetype: "deflect",
        retort: "還好啦，都是提早規劃的（笑）。",
      },
      {
        id: "biaojie-comparison-026-b",
        text: "我行事曆常常都是空的，有點茫然……",
        archetype: "meek",
        retort: "空的話要找點目標填滿。",
      },
      {
        id: "biaojie-comparison-026-c",
        text: "滿不滿不重要，誰逼你排這麼滿？",
        archetype: "perfect",
        retort: "……沒，沒人逼我啦，真的（笑）。",
      },
      {
        id: "biaojie-comparison-026-d",
        text: "滿到明年，那我心理準備排到後年。",
        archetype: "backfire",
        retort: "……心理準備不算行程啦（笑）。",
      },
      {
        id: "biaojie-comparison-026-e",
        text: "表姊你安排事情真的很有條理。",
        archetype: "deflect",
        retort: "謝謝誇獎，習慣了而已（笑）。",
      },
      {
        id: "biaojie-comparison-026-f",
        text: "滿到明年，是公婆排的還是你排的？",
        archetype: "landmine",
        retort: "……當然是我自己排的啦。",
      },
      {
        id: "biaojie-comparison-026-g",
        text: "我不太會規劃長遠的事情……",
        archetype: "meek",
        retort: "不會規劃的話要練習列清單。",
      },
      {
        id: "biaojie-comparison-026-h",
        text: "忙，那我忙著猶豫要不要出門。",
        archetype: "backfire",
        retort: "……那個好像不算忙碌耶（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-027",
    text: "我每天六點起床做早餐，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-027-a",
        text: "六點起床，你真的超級自律。",
        archetype: "deflect",
        retort: "還好啦，小孩會準時吵醒我（笑）。",
      },
      {
        id: "biaojie-comparison-027-b",
        text: "我作息很亂，常常熬夜……",
        archetype: "meek",
        retort: "熬夜對身體不好，要早點調整。",
      },
      {
        id: "biaojie-comparison-027-c",
        text: "早起很好，你幾點真的睡著過？",
        archetype: "perfect",
        retort: "……這個問題有點尖銳（笑）。",
      },
      {
        id: "biaojie-comparison-027-d",
        text: "六點起床，那我六點才剛睡。",
        archetype: "backfire",
        retort: "……那個作息完全相反耶（笑）。",
      },
      {
        id: "biaojie-comparison-027-e",
        text: "表姊你的生活習慣真的很好。",
        archetype: "deflect",
        retort: "謝謝，都是被逼出來的習慣（笑）。",
      },
      {
        id: "biaojie-comparison-027-f",
        text: "六點起，不是自律，是被小孩逼的。",
        archetype: "landmine",
        retort: "……才沒有，他們很乖。",
      },
      {
        id: "biaojie-comparison-027-g",
        text: "我很難早起，賴床是我的專長……",
        archetype: "meek",
        retort: "賴床久了會影響一整天效率。",
      },
      {
        id: "biaojie-comparison-027-h",
        text: "做早餐，那我早餐配水吃維他命。",
        archetype: "backfire",
        retort: "……那樣營養好像不太夠（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-028",
    text: "我最近考到兩張證照，你有進修嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-028-a",
        text: "帶小孩還能考證照，你太厲害了。",
        archetype: "deflect",
        retort: "還好啦，擠時間讀書的（笑）。",
      },
      {
        id: "biaojie-comparison-028-b",
        text: "我畢業後就沒再進修過了……",
        archetype: "meek",
        retort: "沒進修的話競爭力會慢慢下降。",
      },
      {
        id: "biaojie-comparison-028-c",
        text: "兩張證照，兌換得了幾次稱讚？",
        archetype: "perfect",
        retort: "……你很會講話欸（笑）。",
      },
      {
        id: "biaojie-comparison-028-d",
        text: "兩張證照，那我有兩張會員卡。",
        archetype: "backfire",
        retort: "……會員卡不算證照啦（笑）。",
      },
      {
        id: "biaojie-comparison-028-e",
        text: "表姊你真的很上進耶。",
        archetype: "deflect",
        retort: "謝謝誇獎，活到老學到老（笑）。",
      },
      {
        id: "biaojie-comparison-028-f",
        text: "兩張證照，是要證明你沒退步？",
        archetype: "landmine",
        retort: "……才不是，單純想學新的。",
      },
      {
        id: "biaojie-comparison-028-g",
        text: "我對考證照這件事一直提不起勁……",
        archetype: "meek",
        retort: "提不起勁的話要找個目標。",
      },
      {
        id: "biaojie-comparison-028-h",
        text: "進修，那我進修睡眠品質提升法。",
        archetype: "backfire",
        retort: "……那個好像不是正式證照（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-029",
    text: "我們家養了黃金獵犬，你有養寵物嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-029-a",
        text: "養黃金獵犬，你們家一定很溫馨。",
        archetype: "deflect",
        retort: "對啊，小孩跟牠感情很好（笑）。",
      },
      {
        id: "biaojie-comparison-029-b",
        text: "我住的地方不能養寵物……",
        archetype: "meek",
        retort: "不能養的話要考慮換環境。",
      },
      {
        id: "biaojie-comparison-029-c",
        text: "沒養狗，但我很會看家看自己。",
        archetype: "perfect",
        retort: "……哈，這個回答不錯（笑）。",
      },
      {
        id: "biaojie-comparison-029-d",
        text: "養狗，那我養一缸孔雀魚壯膽。",
        archetype: "backfire",
        retort: "……魚跟狗的互動差很多喔（笑）。",
      },
      {
        id: "biaojie-comparison-029-e",
        text: "表姊你連寵物都照顧得很好。",
        archetype: "deflect",
        retort: "謝謝，牠也是我們家一份子（笑）。",
      },
      {
        id: "biaojie-comparison-029-f",
        text: "你狗乖，你小孩在外面很吵。",
        archetype: "landmine",
        retort: "……他們只是比較活潑。",
      },
      {
        id: "biaojie-comparison-029-g",
        text: "養寵物的責任我怕自己扛不起……",
        archetype: "meek",
        retort: "怕扛不起的話可以先想清楚。",
      },
      {
        id: "biaojie-comparison-029-h",
        text: "黃金獵犬，那我的抱枕也是黃色的。",
        archetype: "backfire",
        retort: "……抱枕不會動也不會叫（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-030",
    text: "我今天這身穿搭，是不是很有品味？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-030-a",
        text: "你穿搭一直都很有自己的風格。",
        archetype: "deflect",
        retort: "謝謝，都是慢慢摸索出來的（笑）。",
      },
      {
        id: "biaojie-comparison-030-b",
        text: "我最近都隨便穿，沒什麼心思……",
        archetype: "meek",
        retort: "隨便穿也要顧一下形象啦。",
      },
      {
        id: "biaojie-comparison-030-c",
        text: "有品味不用問，問了就掉價。",
        archetype: "perfect",
        retort: "……哎呀，你講話真直接（笑）。",
      },
      {
        id: "biaojie-comparison-030-d",
        text: "很有品味，那我今天穿睡衣出門。",
        archetype: "backfire",
        retort: "……睡衣好像不太算穿搭（笑）。",
      },
      {
        id: "biaojie-comparison-030-e",
        text: "生完兩個還能穿這麼好看，厲害。",
        archetype: "deflect",
        retort: "還好啦，都是硬擠時間打扮（笑）。",
      },
      {
        id: "biaojie-comparison-030-f",
        text: "白目喔，是婆婆幫你選的吧？",
        archetype: "landmine",
        retort: "……你很沒禮貌欸。",
      },
      {
        id: "biaojie-comparison-030-g",
        text: "我對穿搭真的沒什麼概念……",
        archetype: "meek",
        retort: "沒概念的話可以參考時尚雜誌。",
      },
      {
        id: "biaojie-comparison-030-h",
        text: "品味，那我全身都是家居服品牌。",
        archetype: "backfire",
        retort: "……家居服跟品味沒直接關係（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-031",
    text: "我們已經開始規劃退休金了，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-031-a",
        text: "這麼年輕就規劃退休，你們真周全。",
        archetype: "deflect",
        retort: "對啊，越早規劃越輕鬆（笑）。",
      },
      {
        id: "biaojie-comparison-031-b",
        text: "我連下個月的錢都不太夠用……",
        archetype: "meek",
        retort: "不夠用的話要先做好預算管理。",
      },
      {
        id: "biaojie-comparison-031-c",
        text: "規劃退休前，先規劃好現在吧。",
        archetype: "perfect",
        retort: "……這句話講得真扎心（笑）。",
      },
      {
        id: "biaojie-comparison-031-d",
        text: "規劃退休金，那我規劃退休心態先。",
        archetype: "backfire",
        retort: "……心態跟金錢是兩回事喔（笑）。",
      },
      {
        id: "biaojie-comparison-031-e",
        text: "表姊你想事情一直都很有遠見。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢學的（笑）。",
      },
      {
        id: "biaojie-comparison-031-f",
        text: "退休金，是你賺的還是你老公的？",
        archetype: "landmine",
        retort: "……這個不用你管吧。",
      },
      {
        id: "biaojie-comparison-031-g",
        text: "退休金這種事感覺離我還很遠……",
        archetype: "meek",
        retort: "覺得遠也要提早開始準備。",
      },
      {
        id: "biaojie-comparison-031-h",
        text: "退休金，那我把撲滿當退休帳戶。",
        archetype: "backfire",
        retort: "……撲滿利息應該是零啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-032",
    text: "我老公每個紀念日都會送禮物，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-032-a",
        text: "表姊夫真的很浪漫，好羨慕你。",
        archetype: "deflect",
        retort: "對啊，他一直都很細心（笑）。",
      },
      {
        id: "biaojie-comparison-032-b",
        text: "我男友對這種節日比較沒有概念……",
        archetype: "meek",
        retort: "沒概念的話可以直接跟他說。",
      },
      {
        id: "biaojie-comparison-032-c",
        text: "禮物再多，不如他常出現比較難。",
        archetype: "perfect",
        retort: "……他真的很忙啦（笑）。",
      },
      {
        id: "biaojie-comparison-032-d",
        text: "每次送禮，那我送自己一頓大餐。",
        archetype: "backfire",
        retort: "……那個是自己請自己啦（笑）。",
      },
      {
        id: "biaojie-comparison-032-e",
        text: "你們的紀念日一定過得很甜蜜。",
        archetype: "deflect",
        retort: "還好啦，都是平淡中的小確幸（笑）。",
      },
      {
        id: "biaojie-comparison-032-f",
        text: "常送禮，該不會想補什麼帳？",
        archetype: "landmine",
        retort: "……才不是這樣，別亂講。",
      },
      {
        id: "biaojie-comparison-032-g",
        text: "我還沒有另一半，沒得比較……",
        archetype: "meek",
        retort: "沒有的話，緣分還沒到而已。",
      },
      {
        id: "biaojie-comparison-032-h",
        text: "浪漫，那我浪漫地忘記紀念日。",
        archetype: "backfire",
        retort: "……那樣好像不太浪漫耶（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-033",
    text: "我們初五要去日本，你們有計畫嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-033-a",
        text: "去日本，你們一定期待很久了。",
        archetype: "deflect",
        retort: "對啊，小孩也超興奮的（笑）。",
      },
      {
        id: "biaojie-comparison-033-b",
        text: "我們今年應該哪裡都不會去……",
        archetype: "meek",
        retort: "不去的話在家也要好好休息。",
      },
      {
        id: "biaojie-comparison-033-c",
        text: "去日本很好，你自己想去的嗎？",
        archetype: "perfect",
        retort: "……當然是我自己想去的（笑）。",
      },
      {
        id: "biaojie-comparison-033-d",
        text: "去日本，那我去日式料理店抵一半。",
        archetype: "backfire",
        retort: "……那個好像不算出國耶（笑）。",
      },
      {
        id: "biaojie-comparison-033-e",
        text: "表姊你安排旅行一定很有經驗。",
        archetype: "deflect",
        retort: "還好啦，都是提早訂好的（笑）。",
      },
      {
        id: "biaojie-comparison-033-f",
        text: "去日本，機票是公婆出的嗎？",
        archetype: "landmine",
        retort: "……當然不是，我們自己付的。",
      },
      {
        id: "biaojie-comparison-033-g",
        text: "出國的預算我們還沒存夠……",
        archetype: "meek",
        retort: "沒存夠的話可以先安排國內小旅行。",
      },
      {
        id: "biaojie-comparison-033-h",
        text: "初五出發，那我初五決定要不要出門。",
        archetype: "backfire",
        retort: "……猶豫不算旅行計畫啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-034",
    text: "我們最近買了美股，你有國外資產嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-034-a",
        text: "買美股，你們研究得一定很深入。",
        archetype: "deflect",
        retort: "對啊，跟老公花時間研究的（笑）。",
      },
      {
        id: "biaojie-comparison-034-b",
        text: "我對國外投資完全沒概念……",
        archetype: "meek",
        retort: "沒概念的話可以先從小額試試。",
      },
      {
        id: "biaojie-comparison-034-c",
        text: "美股賺多少，你敢公布損益表嗎？",
        archetype: "perfect",
        retort: "……這個問題有點犀利（笑）。",
      },
      {
        id: "biaojie-comparison-034-d",
        text: "買美股，那我收藏外幣紀念鈔。",
        archetype: "backfire",
        retort: "……紀念鈔不算投資啦（笑）。",
      },
      {
        id: "biaojie-comparison-034-e",
        text: "表姊你理財的視野真的很廣。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢學的（笑）。",
      },
      {
        id: "biaojie-comparison-034-f",
        text: "沒人問，你曬美股想證明什麼？",
        archetype: "landmine",
        retort: "……好啦，我不講了。",
      },
      {
        id: "biaojie-comparison-034-g",
        text: "我連台幣存款都不太夠了……",
        archetype: "meek",
        retort: "不夠的話要先顧好基本開銷。",
      },
      {
        id: "biaojie-comparison-034-h",
        text: "國外資產，那我國外朋友也算資產。",
        archetype: "backfire",
        retort: "……朋友不算金融資產耶（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-035",
    text: "生小孩後睡不飽，你單身睡得好吧？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-035-a",
        text: "半夜還要照顧小孩，你們真辛苦。",
        archetype: "deflect",
        retort: "對啊，但看他睡臉就值得（笑）。",
      },
      {
        id: "biaojie-comparison-035-b",
        text: "我最近其實也睡不太好，壓力大……",
        archetype: "meek",
        retort: "壓力大要找方法放鬆一下。",
      },
      {
        id: "biaojie-comparison-035-c",
        text: "我睡得好，但你顧小孩比較偉大。",
        archetype: "perfect",
        retort: "……這句話讓我語塞了（笑）。",
      },
      {
        id: "biaojie-comparison-035-d",
        text: "睡得好，那我睡到中午也算天賦。",
        archetype: "backfire",
        retort: "……那個應該叫懶惰吧（笑）。",
      },
      {
        id: "biaojie-comparison-035-e",
        text: "表姊你們熬夜還能維持氣色，厲害。",
        archetype: "deflect",
        retort: "還好啦，靠意志力撐的（笑）。",
      },
      {
        id: "biaojie-comparison-035-f",
        text: "睡不飽，別怪小孩，怪你自己。",
        archetype: "landmine",
        retort: "……隨便你說，不想講了。",
      },
      {
        id: "biaojie-comparison-035-g",
        text: "我作息很亂，也常常失眠……",
        archetype: "meek",
        retort: "失眠的話要注意調整生活步調。",
      },
      {
        id: "biaojie-comparison-035-h",
        text: "睡不飽，那我幫你介紹安眠對策。",
        archetype: "backfire",
        retort: "……你自己作息也很亂吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-036",
    text: "我每天都會給自己一點儀式感，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-036-a",
        text: "還能兼顧儀式感，你生活過得真細膩。",
        archetype: "deflect",
        retort: "對啊，小地方也要顧到（笑）。",
      },
      {
        id: "biaojie-comparison-036-b",
        text: "我每天都很累，沒力氣講究這些……",
        archetype: "meek",
        retort: "沒力氣的話找個小事開心一下。",
      },
      {
        id: "biaojie-comparison-036-c",
        text: "儀式感是給自己，還是給朋友圈看？",
        archetype: "perfect",
        retort: "……這個問題很尖銳（笑）。",
      },
      {
        id: "biaojie-comparison-036-d",
        text: "儀式感，那我每天固定時間發呆。",
        archetype: "backfire",
        retort: "……發呆好像不算儀式感耶（笑）。",
      },
      {
        id: "biaojie-comparison-036-e",
        text: "表姊你真的很懂得生活耶。",
        archetype: "deflect",
        retort: "謝謝，這是我對自己的溫柔（笑）。",
      },
      {
        id: "biaojie-comparison-036-f",
        text: "北七，除了老公小孩你剩什麼？",
        archetype: "landmine",
        retort: "……你很過分，我不講了。",
      },
      {
        id: "biaojie-comparison-036-g",
        text: "我對生活儀式感一直沒什麼概念……",
        archetype: "meek",
        retort: "沒概念的話可以從小習慣開始。",
      },
      {
        id: "biaojie-comparison-036-h",
        text: "小確幸，那我覺得吃飽就是最大確幸。",
        archetype: "backfire",
        retort: "……那個好像太基本了啦（笑）。",
      },
    ],
  },
] satisfies Question[];
