// situations: 比較誰先結婚、比較出國旅遊次數、比較換休旅車、比較另一半收入、
// 比較誰先買車、比較生活行程悠閒or滿檔、比較IG追蹤數、比較存款誰先破百萬、
// 比較生兩胎後皮膚保養、比較另一半工作穩定、比較過年家族人數多寡、
// 比較誰先當爸媽的人生進度、比較另一半顧不顧家、比較運動健身頻率、
// 比較誰先換新手機、比較年假安排多寡、比較誰先學會理財投資、
// 比較年夜飯訂菜澎湃程度、比較常不常回娘家、比較才藝興趣多元
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-comparison-001",
    text: "我結婚五年了，你到現在還沒對象？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-001-a",
        text: "表姊你婚姻經營得真的很幸福。",
        archetype: "deflect",
        retort: "謝謝，都是磨合出來的（笑）。",
      },
      {
        id: "biaojie-comparison-001-b",
        text: "還沒遇到適合的，順其自然……",
        archetype: "meek",
        retort: "順其自然也要主動一點。",
      },
      {
        id: "biaojie-comparison-001-c",
        text: "不急，我在等一個不用凡爾賽的人。",
        archetype: "perfect",
        retort: "……我哪有凡爾賽（笑）。",
      },
      {
        id: "biaojie-comparison-001-d",
        text: "沒對象，那我先跟婚姻絕緣體結婚。",
        archetype: "backfire",
        retort: "……那個好像不是真的人（笑）。",
      },
      {
        id: "biaojie-comparison-001-e",
        text: "表姊夫最近好嗎？有沒有很寵你？",
        archetype: "deflect",
        retort: "有啦，他人很好（笑）。",
      },
      {
        id: "biaojie-comparison-001-f",
        text: "五年了，你老公是不是根本不想來？",
        archetype: "landmine",
        retort: "……好，我不講了。",
      },
      {
        id: "biaojie-comparison-001-g",
        text: "工作太忙，沒空談感情……",
        archetype: "meek",
        retort: "忙也要留點時間給自己。",
      },
      {
        id: "biaojie-comparison-001-h",
        text: "五年，那我單身年資也快五年了。",
        archetype: "backfire",
        retort: "……那不算什麼值得比較的（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-002",
    text: "我們家一年出國三次，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-002-a",
        text: "表姊你們去過的地方真的好多。",
        archetype: "deflect",
        retort: "對啊，都是趁小孩放假安排的（笑）。",
      },
      {
        id: "biaojie-comparison-002-b",
        text: "我最近比較少出國，存錢中……",
        archetype: "meek",
        retort: "存錢也好，但生活要平衡。",
      },
      {
        id: "biaojie-comparison-002-c",
        text: "我一年出國零次，存款倒是有三次。",
        archetype: "perfect",
        retort: "……那也是種規劃啦（笑）。",
      },
      {
        id: "biaojie-comparison-002-d",
        text: "三次，那我去過的超商也算旅遊。",
        archetype: "backfire",
        retort: "……超商應該不算旅遊景點（笑）。",
      },
      {
        id: "biaojie-comparison-002-e",
        text: "帶兩個出國，你安排能力真強。",
        archetype: "deflect",
        retort: "還好啦，習慣了就上手了（笑）。",
      },
      {
        id: "biaojie-comparison-002-f",
        text: "沒人問，妳何必主動報行程？",
        archetype: "landmine",
        retort: "……我只是分享而已。",
      },
      {
        id: "biaojie-comparison-002-g",
        text: "工作請假不太方便，很少出去……",
        archetype: "meek",
        retort: "很少出去，會累積壓力喔。",
      },
      {
        id: "biaojie-comparison-002-h",
        text: "出國三次，我原地旅行三次。",
        archetype: "backfire",
        retort: "……原地旅行是什麼意思（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-003",
    text: "我們換了七人座休旅車，你的車呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-003-a",
        text: "換休旅車，你們考慮真的周全。",
        archetype: "deflect",
        retort: "對啊，載小孩東西方便很多（笑）。",
      },
      {
        id: "biaojie-comparison-003-b",
        text: "我開的還是那台老車，暫時沒換……",
        archetype: "meek",
        retort: "老車也要注意保養安全。",
      },
      {
        id: "biaojie-comparison-003-c",
        text: "座位多不代表家裡話題也多。",
        archetype: "perfect",
        retort: "……哪有，我們聊得可多了（笑）。",
      },
      {
        id: "biaojie-comparison-003-d",
        text: "七人座，那我騎機車也能載很多東西。",
        archetype: "backfire",
        retort: "……機車跟休旅車真的差很多（笑）。",
      },
      {
        id: "biaojie-comparison-003-e",
        text: "表姊你挑車的眼光一直都很好。",
        archetype: "deflect",
        retort: "還好啦，都是聽老公建議的（笑）。",
      },
      {
        id: "biaojie-comparison-003-f",
        text: "七人座，該不會是老公自己還貸？",
        archetype: "landmine",
        retort: "算了，這話題到此為止。",
      },
      {
        id: "biaojie-comparison-003-g",
        text: "換車的預算對我來說有點吃緊……",
        archetype: "meek",
        retort: "吃緊的話可以先租車就好。",
      },
      {
        id: "biaojie-comparison-003-h",
        text: "休旅車，那我搭公車也算大眾休旅。",
        archetype: "backfire",
        retort: "……公車不算你自己的車啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-004",
    text: "我老公最近升職加薪，你男友呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-004-a",
        text: "表姊夫這麼優秀，你真的很有福氣。",
        archetype: "deflect",
        retort: "對啊，我也很以他為榮（笑）。",
      },
      {
        id: "biaojie-comparison-004-b",
        text: "我還單身，沒有這方面可以比……",
        archetype: "meek",
        retort: "沒關係，緣分還沒到而已。",
      },
      {
        id: "biaojie-comparison-004-c",
        text: "升職是他的成就，關我什麼事？",
        archetype: "perfect",
        retort: "……對啦是我要炫耀（笑）。",
      },
      {
        id: "biaojie-comparison-004-d",
        text: "升職，那我朋友圈點讚數也升了。",
        archetype: "backfire",
        retort: "……那個跟升職不太一樣耶（笑）。",
      },
      {
        id: "biaojie-comparison-004-e",
        text: "你自己當初的眼光也很厲害吧。",
        archetype: "deflect",
        retort: "還好啦，就是看對人了（笑）。",
      },
      {
        id: "biaojie-comparison-004-f",
        text: "老公升職，妳自己呢？別都算他的。",
        archetype: "landmine",
        retort: "臉一沉，抱起老二去換尿布。",
      },
      {
        id: "biaojie-comparison-004-g",
        text: "我男友的工作最近不太穩定……",
        archetype: "meek",
        retort: "不穩定的話要一起想辦法。",
      },
      {
        id: "biaojie-comparison-004-h",
        text: "加薪，那我零用錢也調漲一百。",
        archetype: "backfire",
        retort: "……那個規模差比較多（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-005",
    text: "我們家兩台車，你連一台都沒有？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-005-a",
        text: "兩台車，你們規劃真的很完整。",
        archetype: "deflect",
        retort: "對啊，各自上班方便（笑）。",
      },
      {
        id: "biaojie-comparison-005-b",
        text: "還沒有車，都是搭大眾運輸……",
        archetype: "meek",
        retort: "搭運輸也方便，但機動性差。",
      },
      {
        id: "biaojie-comparison-005-c",
        text: "兩台車，你們家客廳停得下嗎？",
        archetype: "perfect",
        retort: "……哪有那麼誇張（笑）。",
      },
      {
        id: "biaojie-comparison-005-d",
        text: "兩台車，那我兩台腳踏車扯平。",
        archetype: "backfire",
        retort: "……腳踏車跟車真的差很多（笑）。",
      },
      {
        id: "biaojie-comparison-005-e",
        text: "表姊你們家真的什麼都想周到。",
        archetype: "deflect",
        retort: "還好啦，慢慢添購的（笑）。",
      },
      {
        id: "biaojie-comparison-005-f",
        text: "兩台車，是不是都算妳老公頭上？",
        archetype: "landmine",
        retort: "……我們家的事不用你算。",
      },
      {
        id: "biaojie-comparison-005-g",
        text: "買車的預算我還沒存到……",
        archetype: "meek",
        retort: "沒存到的話要提早規劃。",
      },
      {
        id: "biaojie-comparison-005-h",
        text: "沒車，那我用走路的當代步車。",
        archetype: "backfire",
        retort: "……走路不算代步車啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-006",
    text: "我每天生活都排得滿滿，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-006-a",
        text: "你行程排這麼滿，一定很有效率。",
        archetype: "deflect",
        retort: "對啊，時間管理是必修課（笑）。",
      },
      {
        id: "biaojie-comparison-006-b",
        text: "我每天就是上班下班，很單調……",
        archetype: "meek",
        retort: "單調也要找點樂趣才行。",
      },
      {
        id: "biaojie-comparison-006-c",
        text: "行程滿，不代表心裡不空。",
        archetype: "perfect",
        retort: "……我哪有心空（笑）。",
      },
      {
        id: "biaojie-comparison-006-d",
        text: "排滿，那我行事曆寫滿發呆兩字。",
        archetype: "backfire",
        retort: "……發呆好像不算行程耶（笑）。",
      },
      {
        id: "biaojie-comparison-006-e",
        text: "表姊你安排生活的能力真的強。",
        archetype: "deflect",
        retort: "還好啦，都是被逼出來的（笑）。",
      },
      {
        id: "biaojie-comparison-006-f",
        text: "排這麼滿，笑死，不就是等我們問？",
        archetype: "landmine",
        retort: "……好啊，我以後不講了。",
      },
      {
        id: "biaojie-comparison-006-g",
        text: "我常常不知道自己在忙什麼……",
        archetype: "meek",
        retort: "不知道的話要好好規劃一下。",
      },
      {
        id: "biaojie-comparison-006-h",
        text: "我每天忙著滑手機，也算滿滿。",
        archetype: "backfire",
        retort: "……那個好像不太算安排（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-007",
    text: "我IG追蹤數破萬了，你的呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-007-a",
        text: "破萬耶，你的內容一定很吸引人。",
        archetype: "deflect",
        retort: "還好啦，都是分享日常而已（笑）。",
      },
      {
        id: "biaojie-comparison-007-b",
        text: "我IG追蹤數個位數，很邊緣……",
        archetype: "meek",
        retort: "邊緣沒關係，經營久了會變好。",
      },
      {
        id: "biaojie-comparison-007-c",
        text: "破萬，那我私訊回覆率反而更高。",
        archetype: "perfect",
        retort: "……追蹤數才是重點吧（笑）。",
      },
      {
        id: "biaojie-comparison-007-d",
        text: "破萬，那我的LINE群組人數也破十。",
        archetype: "backfire",
        retort: "……那個規模差太多了啦（笑）。",
      },
      {
        id: "biaojie-comparison-007-e",
        text: "表姊你經營帳號真的很用心。",
        archetype: "deflect",
        retort: "謝謝，看大家喜歡我就開心（笑）。",
      },
      {
        id: "biaojie-comparison-007-f",
        text: "追蹤數，是買來的還是求來的？",
        archetype: "landmine",
        retort: "臉色一僵，轉頭問老大功課寫了沒。",
      },
      {
        id: "biaojie-comparison-007-g",
        text: "我對經營社群完全沒天分……",
        archetype: "meek",
        retort: "沒天分的話多發一點就會了。",
      },
      {
        id: "biaojie-comparison-007-h",
        text: "追蹤數，那我追蹤別人比較多。",
        archetype: "backfire",
        retort: "……那應該叫粉絲不是追蹤者（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-008",
    text: "我們存款破百萬了，你存到多少？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-008-a",
        text: "存到百萬，你們理財真的很厲害。",
        archetype: "deflect",
        retort: "對啊，都是省吃儉用存的（笑）。",
      },
      {
        id: "biaojie-comparison-008-b",
        text: "我的存款離百萬還很遠……",
        archetype: "meek",
        retort: "還遠的話要開始強迫儲蓄。",
      },
      {
        id: "biaojie-comparison-008-c",
        text: "破百萬不稀奇，稀奇的是妳一直講。",
        archetype: "perfect",
        retort: "……我只是隨口講講（笑）。",
      },
      {
        id: "biaojie-comparison-008-d",
        text: "百萬，那我遊戲點數也快破萬。",
        archetype: "backfire",
        retort: "……點數不算真的存款啦（笑）。",
      },
      {
        id: "biaojie-comparison-008-e",
        text: "表姊你規劃財務的能力真的強。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢累積的（笑）。",
      },
      {
        id: "biaojie-comparison-008-f",
        text: "破百萬，頭期款到底誰出的？",
        archetype: "landmine",
        retort: "……這個你少打聽。",
      },
      {
        id: "biaojie-comparison-008-g",
        text: "薪水存不太下來，開銷太多……",
        archetype: "meek",
        retort: "開銷多的話要檢視一下花費。",
      },
      {
        id: "biaojie-comparison-008-h",
        text: "存到百萬，那我欠款也快破十萬。",
        archetype: "backfire",
        retort: "……那個方向好像不太對（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-009",
    text: "生兩個小孩，我皮膚還是很好吧？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-009-a",
        text: "你保養一定花了很多心思吧？",
        archetype: "deflect",
        retort: "還好啦，都是基本功而已（笑）。",
      },
      {
        id: "biaojie-comparison-009-b",
        text: "我最近皮膚狀況不太好，壓力大……",
        archetype: "meek",
        retort: "壓力大要記得多休息一下。",
      },
      {
        id: "biaojie-comparison-009-c",
        text: "妳保養得好，話題也保養一下？",
        archetype: "perfect",
        retort: "……我哪有話題很多（笑）。",
      },
      {
        id: "biaojie-comparison-009-d",
        text: "皮膚好，那我天天敷面膜當被子。",
        archetype: "backfire",
        retort: "……面膜不是這樣用的啦（笑）。",
      },
      {
        id: "biaojie-comparison-009-e",
        text: "表姊你皮膚真的維持得很好。",
        archetype: "deflect",
        retort: "謝謝，睡飽最重要啦（笑）。",
      },
      {
        id: "biaojie-comparison-009-f",
        text: "皮膚好？妳只出現在濾鏡裡吧。",
        archetype: "landmine",
        retort: "假笑僵在臉上，沒再說話。",
      },
      {
        id: "biaojie-comparison-009-g",
        text: "我對保養完全沒有研究……",
        archetype: "meek",
        retort: "沒研究的話可以問我幾招。",
      },
      {
        id: "biaojie-comparison-009-h",
        text: "很好，我用的保養品是自來水。",
        archetype: "backfire",
        retort: "……自來水應該不算保養品（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-010",
    text: "我老公工作很穩定，你的工作呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-010-a",
        text: "表姊夫工作穩定，你一定很安心。",
        archetype: "deflect",
        retort: "對啊，這點真的很感謝他（笑）。",
      },
      {
        id: "biaojie-comparison-010-b",
        text: "我的工作最近有點不穩定……",
        archetype: "meek",
        retort: "不穩定的話要多存點緊急預備金。",
      },
      {
        id: "biaojie-comparison-010-c",
        text: "穩定是他的事，精彩才是我的事。",
        archetype: "perfect",
        retort: "……你倒是很會轉移話題（笑）。",
      },
      {
        id: "biaojie-comparison-010-d",
        text: "穩定，那我每天穩定遲到十分鐘。",
        archetype: "backfire",
        retort: "……那個不算穩定的優點吧（笑）。",
      },
      {
        id: "biaojie-comparison-010-e",
        text: "你當初怎麼看出他適合穩定路線？",
        archetype: "deflect",
        retort: "就是感覺啦，眼光問題（笑）。",
      },
      {
        id: "biaojie-comparison-010-f",
        text: "穩定，是不是妳家安插的？",
        archetype: "landmine",
        retort: "……我們家沒有那麼閒。",
      },
      {
        id: "biaojie-comparison-010-g",
        text: "我還在摸索適合的方向……",
        archetype: "meek",
        retort: "摸索久了會累，早點定下來。",
      },
      {
        id: "biaojie-comparison-010-h",
        text: "工作穩定，我心情倒是很不穩定。",
        archetype: "backfire",
        retort: "……心情不穩定要好好調適（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-011",
    text: "我們家過年二十幾個人，你們家呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-011-a",
        text: "二十幾個人，你們家真的很旺。",
        archetype: "deflect",
        retort: "對啊，過年像辦桌一樣（笑）。",
      },
      {
        id: "biaojie-comparison-011-b",
        text: "我們家過年一年比一年少人……",
        archetype: "meek",
        retort: "少人的話氣氛會冷清一點。",
      },
      {
        id: "biaojie-comparison-011-c",
        text: "人少紅包卻更多，划算的是我。",
        archetype: "perfect",
        retort: "……你這樣算也行（笑）。",
      },
      {
        id: "biaojie-comparison-011-d",
        text: "二十幾個，那我加鄰居也差不多。",
        archetype: "backfire",
        retort: "……鄰居應該不算你們家人吧（笑）。",
      },
      {
        id: "biaojie-comparison-011-e",
        text: "表姊你張羅這麼多人一定很辛苦。",
        archetype: "deflect",
        retort: "還好啦，大家一起幫忙（笑）。",
      },
      {
        id: "biaojie-comparison-011-f",
        text: "人多，是不是每次都在吼小孩？",
        archetype: "landmine",
        retort: "臉一沉，說明年桌數再減。",
      },
      {
        id: "biaojie-comparison-011-g",
        text: "我家過年通常就幾個人吃飯……",
        archetype: "meek",
        retort: "幾個人也好，比較輕鬆自在。",
      },
      {
        id: "biaojie-comparison-011-h",
        text: "很旺，那我家靠開電視營造熱鬧。",
        archetype: "backfire",
        retort: "……電視聲音不算真的人啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-012",
    text: "我孩子都能打醬油了，你進度呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-012-a",
        text: "帶兩個小孩，你的進度真的超前。",
        archetype: "deflect",
        retort: "對啊，時間過得特別快（笑）。",
      },
      {
        id: "biaojie-comparison-012-b",
        text: "我的人生進度好像落後很多……",
        archetype: "meek",
        retort: "落後沒關係，各人步調不同。",
      },
      {
        id: "biaojie-comparison-012-c",
        text: "小孩會走路，不代表妳人生有方向。",
        archetype: "perfect",
        retort: "……我方向感一直很好（笑）。",
      },
      {
        id: "biaojie-comparison-012-d",
        text: "進度，那我遊戲角色等級倒是很前面。",
        archetype: "backfire",
        retort: "……遊戲進度不算人生進度啦（笑）。",
      },
      {
        id: "biaojie-comparison-012-e",
        text: "表姊你人生規劃一直都很有方向。",
        archetype: "deflect",
        retort: "還好啦，都是邊走邊調整的（笑）。",
      },
      {
        id: "biaojie-comparison-012-f",
        text: "除了小孩，妳還剩什麼進度？",
        archetype: "landmine",
        retort: "……我去看一下小孩。",
      },
      {
        id: "biaojie-comparison-012-g",
        text: "我對未來的規劃還很模糊……",
        archetype: "meek",
        retort: "模糊的話要早點想清楚方向。",
      },
      {
        id: "biaojie-comparison-012-h",
        text: "打醬油，那我連油都買不起。",
        archetype: "backfire",
        retort: "……這個梗好像不太好笑（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-013",
    text: "我老公下班就回家幫忙帶小孩，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-013-a",
        text: "表姊夫這麼顧家，你真的很幸福。",
        archetype: "deflect",
        retort: "對啊，我要好好珍惜（笑）。",
      },
      {
        id: "biaojie-comparison-013-b",
        text: "我男友下班比較喜歡自己放鬆……",
        archetype: "meek",
        retort: "放鬆可以，但也要顧一下家。",
      },
      {
        id: "biaojie-comparison-013-c",
        text: "顧家值得稱讚，不代表分數要比。",
        archetype: "perfect",
        retort: "……我沒有要比啦（笑）。",
      },
      {
        id: "biaojie-comparison-013-d",
        text: "顧家，那我養的貓下班也會來蹭我。",
        archetype: "backfire",
        retort: "……貓好像跟顧家不太一樣（笑）。",
      },
      {
        id: "biaojie-comparison-013-e",
        text: "你怎麼把他教得這麼顧家？",
        archetype: "deflect",
        retort: "沒教啦，他本來就這樣（笑）。",
      },
      {
        id: "biaojie-comparison-013-f",
        text: "顧家，是裝給我們看的表演嗎？",
        archetype: "landmine",
        retort: "笑容僵住，轉頭逗老二玩。",
      },
      {
        id: "biaojie-comparison-013-g",
        text: "我還沒有這方面的經驗可以比……",
        archetype: "meek",
        retort: "沒經驗的話以後要慢慢磨合。",
      },
      {
        id: "biaojie-comparison-013-h",
        text: "回家帶小孩，我回家都帶自己睡覺。",
        archetype: "backfire",
        retort: "……那個不算顧家啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-014",
    text: "我每週固定重訓三次，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-014-a",
        text: "生完兩個還能重訓，你意志力超強。",
        archetype: "deflect",
        retort: "還好啦，都是擠時間去的（笑）。",
      },
      {
        id: "biaojie-comparison-014-b",
        text: "我最近完全沒時間運動……",
        archetype: "meek",
        retort: "沒時間的話要擠一點出來。",
      },
      {
        id: "biaojie-comparison-014-c",
        text: "我不重訓，但抗壓力練得很扎實。",
        archetype: "perfect",
        retort: "……那倒也是個說法（笑）。",
      },
      {
        id: "biaojie-comparison-014-d",
        text: "重訓三次，那我滑手機的手臂也很練。",
        archetype: "backfire",
        retort: "……那個應該不算重訓啦（笑）。",
      },
      {
        id: "biaojie-comparison-014-e",
        text: "表姊你身材維持得真好耶。",
        archetype: "deflect",
        retort: "謝謝，都是流汗換來的（笑）。",
      },
      {
        id: "biaojie-comparison-014-f",
        text: "重訓時間，是不是都靠保母換來的？",
        archetype: "landmine",
        retort: "……管好你自己就好。",
      },
      {
        id: "biaojie-comparison-014-g",
        text: "我一運動就容易放棄……",
        archetype: "meek",
        retort: "放棄的話要找個伴一起練。",
      },
      {
        id: "biaojie-comparison-014-h",
        text: "健身，那我健走去便利商店買飲料。",
        archetype: "backfire",
        retort: "……那個距離太短了吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-015",
    text: "我剛換新手機，你的還是舊款吧？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-015-a",
        text: "新手機一定拍照更清楚吧？",
        archetype: "deflect",
        retort: "對啊，拍小孩的照片更美了（笑）。",
      },
      {
        id: "biaojie-comparison-015-b",
        text: "我的手機已經用了快五年……",
        archetype: "meek",
        retort: "五年的話該考慮換新了。",
      },
      {
        id: "biaojie-comparison-015-c",
        text: "手機舊，但我的存款比較新鮮。",
        archetype: "perfect",
        retort: "……存款跟手機是兩回事（笑）。",
      },
      {
        id: "biaojie-comparison-015-d",
        text: "新手機，那我幫舊手機貼新貼紙。",
        archetype: "backfire",
        retort: "……貼紙不會讓它變新款啦（笑）。",
      },
      {
        id: "biaojie-comparison-015-e",
        text: "表姊你追新品的速度真的快。",
        archetype: "deflect",
        retort: "還好啦，剛好舊的壞了（笑）。",
      },
      {
        id: "biaojie-comparison-015-f",
        text: "新手機，是不是妳老公補償妳的？",
        archetype: "landmine",
        retort: "……那是我們夫妻的事，你少管。",
      },
      {
        id: "biaojie-comparison-015-g",
        text: "換手機的預算我還沒存到……",
        archetype: "meek",
        retort: "沒存到的話可以先分期看看。",
      },
      {
        id: "biaojie-comparison-015-h",
        text: "舊款，那我說它是復古限量版。",
        archetype: "backfire",
        retort: "……那個好像只是舊而已（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-016",
    text: "我們家的年假都排得滿滿，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-016-a",
        text: "假期排這麼滿，你們一定很期待。",
        archetype: "deflect",
        retort: "對啊，全家都很興奮（笑）。",
      },
      {
        id: "biaojie-comparison-016-b",
        text: "我年假常常都是躺在家裡……",
        archetype: "meek",
        retort: "躺著也好，但偶爾要出去走走。",
      },
      {
        id: "biaojie-comparison-016-c",
        text: "排滿行程，不如排好心情。",
        archetype: "perfect",
        retort: "……我心情也顧得很好（笑）。",
      },
      {
        id: "biaojie-comparison-016-d",
        text: "排滿，那我把補眠也排進行程表。",
        archetype: "backfire",
        retort: "……補眠不算行程安排吧（笑）。",
      },
      {
        id: "biaojie-comparison-016-e",
        text: "表姊你規劃假期的能力真的強。",
        archetype: "deflect",
        retort: "還好啦，都是提早訂好的（笑）。",
      },
      {
        id: "biaojie-comparison-016-f",
        text: "年假，是不是公婆幫忙才排得出來？",
        archetype: "landmine",
        retort: "……公婆沒意見，你意見倒不少。",
      },
      {
        id: "biaojie-comparison-016-g",
        text: "我沒什麼特別的假期計畫……",
        archetype: "meek",
        retort: "沒計畫的話會覺得日子過很快。",
      },
      {
        id: "biaojie-comparison-016-h",
        text: "假期滿滿，我的心裡行事曆也滿滿。",
        archetype: "backfire",
        retort: "……那個好像看不到啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-017",
    text: "我最近開始學投資，你有理財嗎？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-017-a",
        text: "你開始學投資，一定很有計畫。",
        archetype: "deflect",
        retort: "對啊，跟老公一起研究的（笑）。",
      },
      {
        id: "biaojie-comparison-017-b",
        text: "我對投資完全沒概念，不敢碰……",
        archetype: "meek",
        retort: "不敢碰的話可以先從小額開始。",
      },
      {
        id: "biaojie-comparison-017-c",
        text: "我不投資，專心投資我自己的快樂。",
        archetype: "perfect",
        retort: "……你這樣想也不錯（笑）。",
      },
      {
        id: "biaojie-comparison-017-d",
        text: "學投資，那我玩大富翁練手感。",
        archetype: "backfire",
        retort: "……大富翁不算真的投資啦（笑）。",
      },
      {
        id: "biaojie-comparison-017-e",
        text: "表姊你理財的觀念真的很成熟。",
        archetype: "deflect",
        retort: "還好啦，也是慢慢學的（笑）。",
      },
      {
        id: "biaojie-comparison-017-f",
        text: "理財，是妳說了算還是老公點頭？",
        archetype: "landmine",
        retort: "……我自己也很懂，不用你教。",
      },
      {
        id: "biaojie-comparison-017-g",
        text: "我薪水存下來的很少，沒得投資……",
        archetype: "meek",
        retort: "沒得投資的話要先檢視開銷。",
      },
      {
        id: "biaojie-comparison-017-h",
        text: "理財，那我把零錢存進撲滿理財。",
        archetype: "backfire",
        retort: "……撲滿沒有利息喔（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-018",
    text: "我們家年菜訂了十二道，澎湃吧？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-018-a",
        text: "十二道，你們一定花很多預算。",
        archetype: "deflect",
        retort: "對啊，過年就是要豐盛（笑）。",
      },
      {
        id: "biaojie-comparison-018-b",
        text: "我們家過年菜比較簡單……",
        archetype: "meek",
        retort: "簡單也好，重點是一家團圓。",
      },
      {
        id: "biaojie-comparison-018-c",
        text: "十二道，我這桌營養密度比較高。",
        archetype: "perfect",
        retort: "……密度是什麼意思（笑）。",
      },
      {
        id: "biaojie-comparison-018-d",
        text: "十二道，那我加一道白開水湊數。",
        archetype: "backfire",
        retort: "……白開水不算年菜啦（笑）。",
      },
      {
        id: "biaojie-comparison-018-e",
        text: "表姊你張羅年菜真的很用心。",
        archetype: "deflect",
        retort: "謝謝，家人開心最重要（笑）。",
      },
      {
        id: "biaojie-comparison-018-f",
        text: "十二道，是要吃還是要發文？",
        archetype: "landmine",
        retort: "……我們家都吃光，你很沒禮貌。",
      },
      {
        id: "biaojie-comparison-018-g",
        text: "訂年菜的預算我們比較有限……",
        archetype: "meek",
        retort: "有限的話可以挑重點加菜。",
      },
      {
        id: "biaojie-comparison-018-h",
        text: "澎湃，那我家澎湃的是垃圾量。",
        archetype: "backfire",
        retort: "……這個梗好像不太得體（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-019",
    text: "我每個禮拜都帶小孩回娘家，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-019-a",
        text: "每週回去，你跟娘家感情真好。",
        archetype: "deflect",
        retort: "對啊，媽媽也很期待看孫子（笑）。",
      },
      {
        id: "biaojie-comparison-019-b",
        text: "我比較少回去，工作真的很忙……",
        archetype: "meek",
        retort: "忙也要抽空回去看看爸媽。",
      },
      {
        id: "biaojie-comparison-019-c",
        text: "回不回娘家，不該拿來打分數。",
        archetype: "perfect",
        retort: "……我沒有要打分數啦（笑）。",
      },
      {
        id: "biaojie-comparison-019-d",
        text: "每週回去，那我每週傳貼圖回去。",
        archetype: "backfire",
        retort: "……貼圖不能取代陪伴啦（笑）。",
      },
      {
        id: "biaojie-comparison-019-e",
        text: "表姊你真的很孝順耶。",
        archetype: "deflect",
        retort: "應該的啦，家人最重要（笑）。",
      },
      {
        id: "biaojie-comparison-019-f",
        text: "每週回娘家，公婆沒有意見嗎？",
        archetype: "landmine",
        retort: "臉色一沉，說婆婆最疼她。",
      },
      {
        id: "biaojie-comparison-019-g",
        text: "我離娘家有點遠，不方便常回去……",
        archetype: "meek",
        retort: "不方便的話要多打電話關心。",
      },
      {
        id: "biaojie-comparison-019-h",
        text: "回娘家，我倒是常常回冰箱找食物。",
        archetype: "backfire",
        retort: "……那個不算探望家人啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-comparison-020",
    text: "我除了帶小孩還學插花跟烘焙，你呢？",
    topic: "comparison",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-comparison-020-a",
        text: "還能學插花烘焙，你時間管理超強。",
        archetype: "deflect",
        retort: "對啊，擠一點時間給自己（笑）。",
      },
      {
        id: "biaojie-comparison-020-b",
        text: "我下班只想躺著，沒力氣學東西……",
        archetype: "meek",
        retort: "沒力氣的話要找方法紓壓。",
      },
      {
        id: "biaojie-comparison-020-c",
        text: "才藝多不多，不影響我過得好。",
        archetype: "perfect",
        retort: "……好啦你說得對（笑）。",
      },
      {
        id: "biaojie-comparison-020-d",
        text: "插花烘焙，那我插吸管算插花。",
        archetype: "backfire",
        retort: "……那個不算插花藝術啦（笑）。",
      },
      {
        id: "biaojie-comparison-020-e",
        text: "表姊你生活過得真的好精彩。",
        archetype: "deflect",
        retort: "還好啦，都是興趣使然（笑）。",
      },
      {
        id: "biaojie-comparison-020-f",
        text: "才藝一堆，是怕自己太空虛吧？",
        archetype: "landmine",
        retort: "……你很白目耶，閉嘴啦。",
      },
      {
        id: "biaojie-comparison-020-g",
        text: "我對才藝這種事一直沒有天分……",
        archetype: "meek",
        retort: "沒天分沒關係，重點是開心。",
      },
      {
        id: "biaojie-comparison-020-h",
        text: "多元，那我睡覺姿勢也很多元。",
        archetype: "backfire",
        retort: "……那個好像不算才藝（笑）。",
      },
    ],
  },
] satisfies Question[];
