// situations: 看房app互動、買在市中心地段好、頭期款自己存、貸款年限利率、
// 坪數大老大老二各一間房、裝潢風格預算、學區宅、社區游泳池健身房、
// 買兩個車位、家族群組傳社區房價漲跌、租房vs買房價值觀、公婆幫出頭期款、
// 陽台曬衣空間規劃、搬新家入厝喜宴、鄰居管委會話題、買房時機早買晚買、
// 通勤時間vs房價取捨、書房工作室規劃、婆婆常來住的客房、房仲帶看心得
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-housing-001",
    text: "我在看房app，你要不要一起看看？",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-001-a",
        text: "表姊你眼光一向很準，笑死，介紹幾間。",
        archetype: "deflect",
        retort: "好啊，我傳幾間給你參考（笑）。",
      },
      {
        id: "biaojie-housing-001-b",
        text: "幹……我頭期款還沒存夠，先看看而已……",
        archetype: "meek",
        retort: "先看看也好，多做準備沒壞處。",
      },
      {
        id: "biaojie-housing-001-c",
        text: "找我看房，他媽的不如借我頭期款。",
        archetype: "perfect",
        retort: "……靠北，講話這麼難聽。",
      },
      {
        id: "biaojie-housing-001-d",
        text: "看房app，我他媽的都拿來看室內設計圖爽。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-housing-001-e",
        text: "你們家那間是不是也是這樣挑的，笑死？",
        archetype: "deflect",
        retort: "對啊，比較了快半年呢（笑）。",
      },
      {
        id: "biaojie-housing-001-f",
        text: "白目喔？他媽的沒人問妳，歐巴桑。",
        archetype: "landmine",
        retort: "幹你娘咧，你很沒大沒小！",
      },
      {
        id: "biaojie-housing-001-g",
        text: "房價這麼高，感覺遙不可及……",
        archetype: "meek",
        retort: "遙不可及也要開始存才行。",
      },
      {
        id: "biaojie-housing-001-h",
        text: "我他媽的比較想先買一個房子模型。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-housing-002",
    text: "我們家買在市中心，地段真的好。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-002-a",
        text: "挑地段你們一定考慮很多因素，笑死。",
        archetype: "deflect",
        retort: "對啊，交通學區都想過（笑）。",
      },
      {
        id: "biaojie-housing-002-b",
        text: "幹……我們現在只能先看外圍區域……",
        archetype: "meek",
        retort: "外圍也不錯，慢慢再換就好。",
      },
      {
        id: "biaojie-housing-002-c",
        text: "地段好是真的，妳他媽的更想被誇。",
        archetype: "perfect",
        retort: "（收起笑）……去死啦你，很欠揍。",
      },
      {
        id: "biaojie-housing-002-d",
        text: "地段好，那我他媽的常去你家蹭冷氣。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-housing-002-e",
        text: "表姊你們家品味一直都很好。",
        archetype: "deflect",
        retort: "謝謝，這是我們的心血啦（笑）。",
      },
      {
        id: "biaojie-housing-002-f",
        text: "頭期款，妳他媽的敢講是誰付的，老女人？",
        archetype: "landmine",
        retort: "（大聲）你他媽的講夠了沒！",
      },
      {
        id: "biaojie-housing-002-g",
        text: "市中心對我們來說太貴了……",
        archetype: "meek",
        retort: "太貴的話要及早規劃比較好。",
      },
      {
        id: "biaojie-housing-002-h",
        text: "市中心，那我他媽的住橋下也算中心。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-housing-003",
    text: "我們頭期款是自己存的，很有成就感。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-003-a",
        text: "自己存頭期款，你們一定很拚，笑死。",
        archetype: "deflect",
        retort: "對啊，省吃儉用了好幾年（笑）。",
      },
      {
        id: "biaojie-housing-003-b",
        text: "幹……我們頭期款可能要靠家裡幫忙……",
        archetype: "meek",
        retort: "有人幫也好，但要說清楚條件。",
      },
      {
        id: "biaojie-housing-003-c",
        text: "存了幾年？他媽的跟房價比誰快？",
        archetype: "perfect",
        retort: "……幹，你到底是誰教的？",
      },
      {
        id: "biaojie-housing-003-d",
        text: "頭期款，我他媽的打算刮刮樂試試看。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-housing-003-e",
        text: "表姊你理財的能力真的很強。",
        archetype: "deflect",
        retort: "還好啦，都是跟老公一起規劃（笑）。",
      },
      {
        id: "biaojie-housing-003-f",
        text: "自己存的？還是他媽的公婆偷塞的？",
        archetype: "landmine",
        retort: "去死，誰要聽你講這個！",
      },
      {
        id: "biaojie-housing-003-g",
        text: "存頭期款的速度真的很慢……",
        archetype: "meek",
        retort: "慢的話要想辦法增加收入。",
      },
      {
        id: "biaojie-housing-003-h",
        text: "自己存，那我他媽的先去借高利貸。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-housing-004",
    text: "我們房貸貸三十年，利率談得很低。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-004-a",
        text: "談利率你們一定跑了好幾家銀行，笑死。",
        archetype: "deflect",
        retort: "對啊，比了三四家才決定（笑）。",
      },
      {
        id: "biaojie-housing-004-b",
        text: "幹……我對貸款利率完全不懂……",
        archetype: "meek",
        retort: "不懂的話要找人問清楚才好。",
      },
      {
        id: "biaojie-housing-004-c",
        text: "利率低不稀奇，機掰，稀奇的是妳講。",
        archetype: "perfect",
        retort: "……幹，你這孩子嘴巴很壞（笑容僵）。",
      },
      {
        id: "biaojie-housing-004-d",
        text: "利率低，那我他媽的去銀行辦定存比較快。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-housing-004-e",
        text: "表姊你連貸款都研究得好透徹。",
        archetype: "deflect",
        retort: "還好啦，都是老公在研究的（笑）。",
      },
      {
        id: "biaojie-housing-004-f",
        text: "北七喔，他媽的講利率想圖什麼，歐巴桑？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
      {
        id: "biaojie-housing-004-g",
        text: "三十年感覺壓力好大，會怕……",
        archetype: "meek",
        retort: "會怕正常，但撐過去就習慣了。",
      },
      {
        id: "biaojie-housing-004-h",
        text: "三十年，我他媽的連手機分期都嫌久。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-housing-005",
    text: "我們買夠大，老大老二各有一間房。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-005-a",
        text: "規劃兩間房，你們一定花很多心思，笑死。",
        archetype: "deflect",
        retort: "對啊，光格局就想了好久（笑）。",
      },
      {
        id: "biaojie-housing-005-b",
        text: "幹……我們現在住的地方連一間都擠……",
        archetype: "meek",
        retort: "擠的話要有換房的計畫比較好。",
      },
      {
        id: "biaojie-housing-005-c",
        text: "兩間房，他媽的是要住還是要曬？",
        archetype: "perfect",
        retort: "……他媽的，沒大沒小（臉一沉）。",
      },
      {
        id: "biaojie-housing-005-d",
        text: "各一間房，那我他媽的跟我家的狗分房睡。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-housing-005-e",
        text: "表姊你把家裡規劃得好周到。",
        archetype: "deflect",
        retort: "謝謝，都是為了小孩著想（笑）。",
      },
      {
        id: "biaojie-housing-005-f",
        text: "買那麼大，是他媽的想贏誰的臉？",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
      {
        id: "biaojie-housing-005-g",
        text: "坪數大真的很難負擔得起……",
        archetype: "meek",
        retort: "難負擔的話，可以先從小坪數開始。",
      },
      {
        id: "biaojie-housing-005-h",
        text: "夠大喔，那我他媽的把客廳隔成三間。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-housing-006",
    text: "裝潢花了兩百萬，走的是簡約風。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-006-a",
        text: "挑風格你們一定考慮很久，笑死。",
        archetype: "deflect",
        retort: "對啊，換了好幾次設計圖（笑）。",
      },
      {
        id: "biaojie-housing-006-b",
        text: "幹……我們預算大概只有二十分之一……",
        archetype: "meek",
        retort: "預算少也能布置得溫馨啊。",
      },
      {
        id: "biaojie-housing-006-c",
        text: "兩百萬，他媽的是簡約還是心虛？",
        archetype: "perfect",
        retort: "（笑容不見）……去你的，很敢講。",
      },
      {
        id: "biaojie-housing-006-d",
        text: "兩百萬，那我他媽的家裝潢用IKEA湊。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-housing-006-e",
        text: "表姊你的家一定很有質感。",
        archetype: "deflect",
        retort: "謝謝，歡迎你來坐坐（笑）。",
      },
      {
        id: "biaojie-housing-006-f",
        text: "兩百萬裝潢，妳他媽的老公點頭了嗎，歐巴桑？",
        archetype: "landmine",
        retort: "幹！你才是欠罵的那個！",
      },
      {
        id: "biaojie-housing-006-g",
        text: "裝潢對我們來說太奢侈了……",
        archetype: "meek",
        retort: "奢侈的話可以先做局部就好。",
      },
      {
        id: "biaojie-housing-006-h",
        text: "簡約風，那我他媽的家什麼都沒有算簡約。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-housing-007",
    text: "我們特地買學區宅，為了老大讀書。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-007-a",
        text: "挑學區你們一定做了很多研究，笑死。",
        archetype: "deflect",
        retort: "對啊，比較了好幾間學校（笑）。",
      },
      {
        id: "biaojie-housing-007-b",
        text: "幹……我們現在還沒考慮到學區問題……",
        archetype: "meek",
        retort: "沒考慮的話，要早點想清楚。",
      },
      {
        id: "biaojie-housing-007-c",
        text: "學區宅，講到底他媽的是妳想搬。",
        archetype: "perfect",
        retort: "……（氣到講台語）幹恁娘咧。",
      },
      {
        id: "biaojie-housing-007-d",
        text: "學區宅，那我他媽的搬去圖書館旁邊。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-housing-007-e",
        text: "表姊你為小孩真的很用心規劃。",
        archetype: "deflect",
        retort: "應該的，教育不能馬虎（笑）。",
      },
      {
        id: "biaojie-housing-007-f",
        text: "學區宅，是喔，他媽的講給誰聽。",
        archetype: "landmine",
        retort: "（臉色鐵青）明年不用他媽的來了。",
      },
      {
        id: "biaojie-housing-007-g",
        text: "學區宅感覺貴很多，買不起……",
        archetype: "meek",
        retort: "貴是真的，但值得長期投資。",
      },
      {
        id: "biaojie-housing-007-h",
        text: "為了讀書，那我他媽的搬去補習街。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-housing-008",
    text: "我們社區有游泳池，小孩天天去游。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-008-a",
        text: "社區設施這麼齊全，你們挑得好，笑死。",
        archetype: "deflect",
        retort: "對啊，當初就是看中這個（笑）。",
      },
      {
        id: "biaojie-housing-008-b",
        text: "幹……我們住的地方連公園都很小……",
        archetype: "meek",
        retort: "小公園也能練練體力啦。",
      },
      {
        id: "biaojie-housing-008-c",
        text: "游泳池，他媽的是拿來妳打卡的吧。",
        archetype: "perfect",
        retort: "……你很過分耶，幹（別過臉）。",
      },
      {
        id: "biaojie-housing-008-d",
        text: "游泳池，那我他媽的去河邊游算免費版。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-housing-008-e",
        text: "表姊你們的生活品質真的很好。",
        archetype: "deflect",
        retort: "謝謝，住得舒服最重要（笑）。",
      },
      {
        id: "biaojie-housing-008-f",
        text: "泳池而已，他媽的別再凡爾賽了，歐巴桑。",
        archetype: "landmine",
        retort: "你他媽的閉嘴，別再說了！",
      },
      {
        id: "biaojie-housing-008-g",
        text: "這種社區的管理費應該很貴吧……",
        archetype: "meek",
        retort: "貴是真的，但設施用得到就值得。",
      },
      {
        id: "biaojie-housing-008-h",
        text: "有游泳池，那我他媽的在家練仰式配水桶。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-housing-009",
    text: "我們買了兩個車位，方便又保值。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-009-a",
        text: "兩個車位，你們規劃得很長遠，笑死。",
        archetype: "deflect",
        retort: "對啊，順便留一格給爸媽（笑）。",
      },
      {
        id: "biaojie-housing-009-b",
        text: "幹……我們連一個車位都負擔不起……",
        archetype: "meek",
        retort: "負擔不起的話先租車位也行。",
      },
      {
        id: "biaojie-housing-009-c",
        text: "機掰，兩個車位，停得下妳的虛榮？",
        archetype: "perfect",
        retort: "……虛榮跟車位有什麼關係（笑容僵住）。",
      },
      {
        id: "biaojie-housing-009-d",
        text: "兩個車位，那我他媽的用來種盆栽。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-housing-009-e",
        text: "表姊你考慮事情真的很周全。",
        archetype: "deflect",
        retort: "還好啦，多想一步而已（笑）。",
      },
      {
        id: "biaojie-housing-009-f",
        text: "兩個車位，他媽的是不是怕被瞧不起？",
        archetype: "landmine",
        retort: "才沒有，你他媽的很沒禮貌！",
      },
      {
        id: "biaojie-housing-009-g",
        text: "車位好貴，感覺不划算……",
        archetype: "meek",
        retort: "不划算歸不划算，方便性有差。",
      },
      {
        id: "biaojie-housing-009-h",
        text: "車位，我他媽的腳踏車停路邊也行。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-housing-010",
    text: "群組傳新聞，我們社區房價又漲了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-010-a",
        text: "眼光真好，買到會漲的社區，笑死。",
        archetype: "deflect",
        retort: "運氣加眼光啦，謝謝你（笑）。",
      },
      {
        id: "biaojie-housing-010-b",
        text: "幹……我看到那種新聞都覺得很無力……",
        archetype: "meek",
        retort: "無力歸無力，還是要持續關注。",
      },
      {
        id: "biaojie-housing-010-c",
        text: "漲價關我什麼事，他媽的妳要賣？",
        archetype: "perfect",
        retort: "（尷尬）……你他媽的很敢說喔。",
      },
      {
        id: "biaojie-housing-010-d",
        text: "漲了，那我他媽的把租的房間也貼漲價貼紙。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-housing-010-e",
        text: "表姊你們投資眼光一直很準。",
        archetype: "deflect",
        retort: "還好啦，都是研究出來的（笑）。",
      },
      {
        id: "biaojie-housing-010-f",
        text: "漲跌關你屁事，他媽的別再現了，老女人。",
        archetype: "landmine",
        retort: "（拍桌）去你的，太過分了！",
      },
      {
        id: "biaojie-housing-010-g",
        text: "房價漲成這樣，感覺永遠買不起……",
        archetype: "meek",
        retort: "永遠買不起的話要調整策略。",
      },
      {
        id: "biaojie-housing-010-h",
        text: "房價漲，那我他媽的漲我的零用錢預算。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-housing-011",
    text: "租房是幫房東繳貸款，買房才實在。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-011-a",
        text: "你們買房的決心一直讓我佩服，笑死。",
        archetype: "deflect",
        retort: "謝謝，也是逼自己一把啦（笑）。",
      },
      {
        id: "biaojie-housing-011-b",
        text: "幹……現在租房比較彈性，我先租著……",
        archetype: "meek",
        retort: "彈性歸彈性，錢還是花掉了。",
      },
      {
        id: "biaojie-housing-011-c",
        text: "說買房實在，他媽的那我先借住幾天。",
        archetype: "perfect",
        retort: "……靠北，講話這麼難聽。",
      },
      {
        id: "biaojie-housing-011-d",
        text: "買房實在，那我他媽的先買個盆栽練習。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-housing-011-e",
        text: "表姊你想事情真的很有計畫。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢摸索的（笑）。",
      },
      {
        id: "biaojie-housing-011-f",
        text: "買房實在，妳他媽的老公出多少？",
        archetype: "landmine",
        retort: "幹你娘咧，你很沒大沒小！",
      },
      {
        id: "biaojie-housing-011-g",
        text: "存頭期款真的存不到啊……",
        archetype: "meek",
        retort: "存不到就要想辦法增加收入。",
      },
      {
        id: "biaojie-housing-011-h",
        text: "租房喔，那我他媽的把房間貼滿股票單。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-housing-012",
    text: "公婆幫忙出頭期款，減輕不少壓力。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-012-a",
        text: "公婆這麼疼你，你婆媳關係一定好，笑死。",
        archetype: "deflect",
        retort: "還不錯啦，互相尊重（笑）。",
      },
      {
        id: "biaojie-housing-012-b",
        text: "幹……我們家可能沒辦法這樣幫忙……",
        archetype: "meek",
        retort: "沒辦法幫忙的話，自己更要努力。",
      },
      {
        id: "biaojie-housing-012-c",
        text: "公婆出的，他媽的那房子算誰的？",
        archetype: "perfect",
        retort: "（收起笑）……去死啦你，很欠揍。",
      },
      {
        id: "biaojie-housing-012-d",
        text: "公婆出頭期款，那我他媽的跟阿姨借零用錢。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-housing-012-e",
        text: "表姊你真的嫁得很幸福耶。",
        archetype: "deflect",
        retort: "謝謝，我也很努力經營啦（笑）。",
      },
      {
        id: "biaojie-housing-012-f",
        text: "拿公婆的錢，妳他媽的敢大聲喔，歐巴桑？",
        archetype: "landmine",
        retort: "（大聲）你他媽的講夠了沒！",
      },
      {
        id: "biaojie-housing-012-g",
        text: "光靠自己存頭期款真的很難……",
        archetype: "meek",
        retort: "難的話要跟另一半好好討論。",
      },
      {
        id: "biaojie-housing-012-h",
        text: "減輕壓力，那我他媽的把貸款轉嫁給貓。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-housing-013",
    text: "我們陽台特地留大一點，方便曬衣。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-013-a",
        text: "規劃陽台你們一定花了心思，笑死。",
        archetype: "deflect",
        retort: "對啊，量了好幾次尺寸（笑）。",
      },
      {
        id: "biaojie-housing-013-b",
        text: "幹……我們家陽台小到只能放洗衣機……",
        archetype: "meek",
        retort: "小的話要想辦法善用空間。",
      },
      {
        id: "biaojie-housing-013-c",
        text: "陽台大，他媽的是曬衣還是曬命？",
        archetype: "perfect",
        retort: "……幹，你到底是誰教的？",
      },
      {
        id: "biaojie-housing-013-d",
        text: "陽台大，那我他媽的拿來種西瓜好了。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-housing-013-e",
        text: "表姊你連細節都想得好周到。",
        archetype: "deflect",
        retort: "習慣了，生活要方便一點（笑）。",
      },
      {
        id: "biaojie-housing-013-f",
        text: "陽台大，他媽的晾得出妳多少存款？",
        archetype: "landmine",
        retort: "去死，誰要聽你講這個！",
      },
      {
        id: "biaojie-housing-013-g",
        text: "現在租的地方根本沒有陽台……",
        archetype: "meek",
        retort: "沒陽台真的不太方便呢。",
      },
      {
        id: "biaojie-housing-013-h",
        text: "曬衣方便，那我他媽的去頂樓曬鄰居衣服。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-housing-014",
    text: "我們下個月入厝，記得包紅包喔。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-014-a",
        text: "辦入厝，你們一定籌備很久了，笑死。",
        archetype: "deflect",
        retort: "對啊，光挑日子就選了好幾次（笑）。",
      },
      {
        id: "biaojie-housing-014-b",
        text: "幹……我可能包不了太多，先說聲抱歉……",
        archetype: "meek",
        retort: "沒關係，心意到就好。",
      },
      {
        id: "biaojie-housing-014-c",
        text: "入厝喜宴，他媽的講白了想收租。",
        archetype: "perfect",
        retort: "……幹，你這孩子嘴巴很壞（笑容僵）。",
      },
      {
        id: "biaojie-housing-014-d",
        text: "入厝，那我他媽的送一台跑步機當賀禮。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-housing-014-e",
        text: "表姊你辦事情真的很細心周到。",
        archetype: "deflect",
        retort: "謝謝誇獎，都是為了圖個吉利（笑）。",
      },
      {
        id: "biaojie-housing-014-f",
        text: "入厝擺這麼大，他媽的想收多少，歐巴桑？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
      {
        id: "biaojie-housing-014-g",
        text: "我對入厝的規矩不太懂……",
        archetype: "meek",
        retort: "不懂沒關係，到時候我教你。",
      },
      {
        id: "biaojie-housing-014-h",
        text: "紅包喔，那我他媽的包乖乖桶意思一下。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-housing-015",
    text: "我們社區管委會超嚴格，素質很高。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-015-a",
        text: "住這種社區，你們鄰居關係一定好，笑死。",
        archetype: "deflect",
        retort: "對啊，大家都會互相照應（笑）。",
      },
      {
        id: "biaojie-housing-015-b",
        text: "幹……我們那邊鄰居都不太熟……",
        archetype: "meek",
        retort: "不熟的話要多打招呼比較好。",
      },
      {
        id: "biaojie-housing-015-c",
        text: "素質高，他媽的是你們都很會演。",
        archetype: "perfect",
        retort: "……他媽的，沒大沒小（臉一沉）。",
      },
      {
        id: "biaojie-housing-015-d",
        text: "管委會嚴格，那我他媽的去選主委好了。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-housing-015-e",
        text: "表姊你人緣一直都很好耶。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢相處出來的（笑）。",
      },
      {
        id: "biaojie-housing-015-f",
        text: "素質高，笑死，他媽的愛比較。",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
      {
        id: "biaojie-housing-015-g",
        text: "管委會的事我完全沒概念……",
        archetype: "meek",
        retort: "沒概念的話，以後要多學一點。",
      },
      {
        id: "biaojie-housing-015-h",
        text: "素質高，那我他媽的去考個社區禮儀證照。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-housing-016",
    text: "早買早享受，現在買房比以前貴多了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-016-a",
        text: "你們當初真的很有眼光，早買，笑死。",
        archetype: "deflect",
        retort: "運氣好啦，剛好遇到機會（笑）。",
      },
      {
        id: "biaojie-housing-016-b",
        text: "幹……我們現在存錢的速度追不上房價……",
        archetype: "meek",
        retort: "追不上的話要調整買房計畫。",
      },
      {
        id: "biaojie-housing-016-c",
        text: "早買早享受，他媽的晚繳晚心痛吧？",
        archetype: "perfect",
        retort: "（笑容不見）……去你的，很敢講。",
      },
      {
        id: "biaojie-housing-016-d",
        text: "早買早享受，那我他媽的早點退休享受。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-housing-016-e",
        text: "表姊你做決定一直都很果斷。",
        archetype: "deflect",
        retort: "還好啦，跟老公討論很久才決定（笑）。",
      },
      {
        id: "biaojie-housing-016-f",
        text: "早買，他媽的是不是妳家出頭的，歐巴桑？",
        archetype: "landmine",
        retort: "幹！你才是欠罵的那個！",
      },
      {
        id: "biaojie-housing-016-g",
        text: "感覺我們已經錯過買房時機了……",
        archetype: "meek",
        retort: "錯過的話，現在開始也不算晚。",
      },
      {
        id: "biaojie-housing-016-h",
        text: "現在買貴，那我他媽的先租一輩子好了。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-housing-017",
    text: "我們寧願買遠一點，通勤久也值得。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-017-a",
        text: "你們能撐得住通勤，意志力很強，笑死。",
        archetype: "deflect",
        retort: "還好啦，聽Podcast就過去了（笑）。",
      },
      {
        id: "biaojie-housing-017-b",
        text: "幹……我沒辦法忍受太久的通勤……",
        archetype: "meek",
        retort: "忍不住的話，選擇就會變少。",
      },
      {
        id: "biaojie-housing-017-c",
        text: "值得是真的，他媽的通勤的是妳老公。",
        archetype: "perfect",
        retort: "……（氣到講台語）幹恁娘咧。",
      },
      {
        id: "biaojie-housing-017-d",
        text: "通勤久，那我他媽的乾脆睡公司比較快。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-housing-017-e",
        text: "表姊你做決定一直都很有遠見。",
        archetype: "deflect",
        retort: "謝謝，都是權衡過的（笑）。",
      },
      {
        id: "biaojie-housing-017-f",
        text: "通勤久，他媽的講白了買不起。",
        archetype: "landmine",
        retort: "（臉色鐵青）明年不用他媽的來了。",
      },
      {
        id: "biaojie-housing-017-g",
        text: "我們比較在意離公司近……",
        archetype: "meek",
        retort: "近是方便，但空間會犧牲不少。",
      },
      {
        id: "biaojie-housing-017-h",
        text: "值得，那我他媽的搬到國外通勤更遠。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-housing-018",
    text: "我們特地留一間書房給老公工作。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-018-a",
        text: "留書房，你們考慮得真周到，笑死。",
        archetype: "deflect",
        retort: "對啊，在家工作方便很多（笑）。",
      },
      {
        id: "biaojie-housing-018-b",
        text: "幹……我們家連自己的書桌都沒有……",
        archetype: "meek",
        retort: "沒書桌的話工作會很不方便。",
      },
      {
        id: "biaojie-housing-018-c",
        text: "幹，書房是給老公用，還是給妳曬的？",
        archetype: "perfect",
        retort: "……曬個書房不行嗎，幹（笑容僵住）。",
      },
      {
        id: "biaojie-housing-018-d",
        text: "書房，那我他媽的把陽台改成辦公室。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-housing-018-e",
        text: "表姊你安排空間一直很有計畫。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢調整的（笑）。",
      },
      {
        id: "biaojie-housing-018-f",
        text: "書房給老公，他媽的他人在哪，歐巴桑？",
        archetype: "landmine",
        retort: "你他媽的閉嘴，別再說了！",
      },
      {
        id: "biaojie-housing-018-g",
        text: "在家工作對我們來說有點奢侈……",
        archetype: "meek",
        retort: "奢侈的話可以先弄個小角落。",
      },
      {
        id: "biaojie-housing-018-h",
        text: "工作室，那我他媽的在客廳貼個牌子。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-housing-019",
    text: "我們留了客房，婆婆常來住幾天。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-019-a",
        text: "留客房給婆婆，你真的很貼心，笑死。",
        archetype: "deflect",
        retort: "應該的啦，家人嘛（笑）。",
      },
      {
        id: "biaojie-housing-019-b",
        text: "幹……我們家空間小，親戚來都沒地方住……",
        archetype: "meek",
        retort: "沒地方住的話要提早跟親戚說。",
      },
      {
        id: "biaojie-housing-019-c",
        text: "沒隱私沒關係，機掰，妳婆婆最大。",
        archetype: "perfect",
        retort: "……機掰，你這張嘴誰教的？",
      },
      {
        id: "biaojie-housing-019-d",
        text: "客房，那我他媽的家沙發也算客房。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-housing-019-e",
        text: "表姊你們婆媳感情一定很融洽。",
        archetype: "deflect",
        retort: "還算不錯，互相體諒（笑）。",
      },
      {
        id: "biaojie-housing-019-f",
        text: "婆婆常住，他媽的是誰在當家？",
        archetype: "landmine",
        retort: "機掰，你這什麼態度！",
      },
      {
        id: "biaojie-housing-019-g",
        text: "我對接待長輩住宿有點緊張……",
        archetype: "meek",
        retort: "緊張的話多練習招待就好。",
      },
      {
        id: "biaojie-housing-019-h",
        text: "婆婆常來住，那我他媽的把客廳租給她。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-housing-020",
    text: "上禮拜房仲帶看，分享一下心得。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-020-a",
        text: "你看房這麼勤，一定很有經驗，笑死。",
        archetype: "deflect",
        retort: "還好啦，看多了就有心得（笑）。",
      },
      {
        id: "biaojie-housing-020-b",
        text: "幹……我對看房這件事完全沒有頭緒……",
        archetype: "meek",
        retort: "沒頭緒的話可以先跟房仲聊聊。",
      },
      {
        id: "biaojie-housing-020-c",
        text: "心得就是，他媽的妳想找人聽妳講。",
        archetype: "perfect",
        retort: "（尷尬）……你他媽的很敢說喔。",
      },
      {
        id: "biaojie-housing-020-d",
        text: "看房心得，我他媽的覺得都差不多貴。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-housing-020-e",
        text: "表姊你分析房子的能力真好。",
        archetype: "deflect",
        retort: "謝謝，都是實戰累積的（笑）。",
      },
      {
        id: "biaojie-housing-020-f",
        text: "看房心得，他媽的沒人想聽，老女人。",
        archetype: "landmine",
        retort: "（拍桌）去你的，太過分了！",
      },
      {
        id: "biaojie-housing-020-g",
        text: "我怕被房仲的話術騙……",
        archetype: "meek",
        retort: "怕被騙的話要多做功課比較好。",
      },
      {
        id: "biaojie-housing-020-h",
        text: "房仲帶看，那我他媽的去當房仲賺仲介費。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
] satisfies Question[];
