// situations: 頂樓加蓋舊公寓翻新、選電梯大樓vs透天、買預售屋vs成屋、
// 裝修遇工班烙跑糾紛、房貸壓力日子還是要過、買房送裝潢家電、
// 小孩房間主題佈置、陽台種菜小花園、買車位出租賺錢、房子要留給老大的繼承規劃、
// 買房登記在誰名下、搬家打包辛苦暗示租屋處小、房屋稅地價稅話題、
// 樓層採光蚊蟲問題、買房投資增值角度、家族群組討論誰家坪數最大、買房入厝紅包規矩
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-housing-021",
    text: "老家頂樓加蓋，我們花錢整個翻新。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-021-a",
        text: "靠，妳監工監這麼細，很幹練。",
        archetype: "deflect",
        retort: "靠，天天跑工地看（笑）。",
      },
      {
        id: "biaojie-housing-021-b",
        text: "靠……工班的錢我們都湊不齊……",
        archetype: "meek",
        retort: "湊不齊就分階段做啦。",
      },
      {
        id: "biaojie-housing-021-c",
        text: "幹，翻好是想收門票膩？",
        archetype: "perfect",
        retort: "……你很欠罵誒（笑容僵住）。",
      },
      {
        id: "biaojie-housing-021-d",
        text: "幹，頂樓加蓋那我陽台搭帳篷。",
        archetype: "backfire",
        retort: "……帳篷撐不了幾天啦（笑）。",
      },
      {
        id: "biaojie-housing-021-e",
        text: "靠北，妳監督工程也太仔細。",
        archetype: "deflect",
        retort: "還好啦，看久就熟練了（笑）。",
      },
      {
        id: "biaojie-housing-021-f",
        text: "幹，翻新費根本公婆出的吧，老女人還裝。",
        archetype: "landmine",
        retort: "你他媽的很沒禮貌！",
      },
      {
        id: "biaojie-housing-021-g",
        text: "幹……老房子翻新聽起來好麻煩……",
        archetype: "meek",
        retort: "麻煩是真的，但值得啦。",
      },
      {
        id: "biaojie-housing-021-h",
        text: "機掰，翻新那我把家具搬一搬。",
        archetype: "backfire",
        retort: "……那個不算翻新啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-022",
    text: "我們選電梯大樓，透天太難照顧了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-022-a",
        text: "靠北，選房型你們也太仔細了。",
        archetype: "deflect",
        retort: "對啊，比較超多次才決定（笑）。",
      },
      {
        id: "biaojie-housing-022-b",
        text: "靠……這兩種房型的差別我搞不清楚……",
        archetype: "meek",
        retort: "搞不清楚就多比較一下。",
      },
      {
        id: "biaojie-housing-022-c",
        text: "幹，透天難顧，是比小孩還難顧？",
        archetype: "perfect",
        retort: "他媽的講話很欠揍欸！",
      },
      {
        id: "biaojie-housing-022-d",
        text: "幹，電梯大樓那我家爬樓梯練體力。",
        archetype: "backfire",
        retort: "……那不算真的選擇吧（笑）。",
      },
      {
        id: "biaojie-housing-022-e",
        text: "靠，妳做決定都這麼有邏輯。",
        archetype: "deflect",
        retort: "還好啦，都聽老公分析的（笑）。",
      },
      {
        id: "biaojie-housing-022-f",
        text: "他媽的，妳老公到底顧不顧家，別裝沒事了。",
        archetype: "landmine",
        retort: "夠了，你去死啦，很過分！",
      },
      {
        id: "biaojie-housing-022-g",
        text: "幹……我們家連公寓都快撐不住……",
        archetype: "meek",
        retort: "吃力就重新規劃預算啦。",
      },
      {
        id: "biaojie-housing-022-h",
        text: "機掰，透天難顧那我住帳篷更難。",
        archetype: "backfire",
        retort: "……帳篷不算房子啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-023",
    text: "我們買預售屋，等交屋還要兩年。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-023-a",
        text: "笑死，你們也太有耐心了。",
        archetype: "deflect",
        retort: "對啊，等待也是修行啦（笑）。",
      },
      {
        id: "biaojie-housing-023-b",
        text: "幹……我對預售屋流程完全不懂……",
        archetype: "meek",
        retort: "不懂就找懂的人幫忙看。",
      },
      {
        id: "biaojie-housing-023-c",
        text: "幹，兩年是要讓老公多存幾桶金？",
        archetype: "perfect",
        retort: "……你很機掰誒（笑容僵住）。",
      },
      {
        id: "biaojie-housing-023-d",
        text: "幹，預售屋那我先預購晚餐好了。",
        archetype: "backfire",
        retort: "……晚餐不用預購兩年吧（笑）。",
      },
      {
        id: "biaojie-housing-023-e",
        text: "靠北，你們規劃時間抓得真準。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢學的（笑）。",
      },
      {
        id: "biaojie-housing-023-f",
        text: "去你的，說什麼自住，其實想炒房吧。",
        archetype: "landmine",
        retort: "你他媽的很賤，不想聊了！",
      },
      {
        id: "biaojie-housing-023-g",
        text: "靠……等兩年感覺好久，會擔心變數……",
        archetype: "meek",
        retort: "會擔心正常，多留意合約。",
      },
      {
        id: "biaojie-housing-023-h",
        text: "機掰，等交屋那我先租帳篷住兩年。",
        archetype: "backfire",
        retort: "……帳篷住兩年太辛苦了（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-024",
    text: "我們裝潢遇到工班烙跑，很崩潰。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-024-a",
        text: "靠北，妳處理事情也太冷靜。",
        archetype: "deflect",
        retort: "還好啦，事情發生只能面對（笑）。",
      },
      {
        id: "biaojie-housing-024-b",
        text: "幹……我聽到這種事就覺得好害怕……",
        archetype: "meek",
        retort: "害怕正常，簽約要小心。",
      },
      {
        id: "biaojie-housing-024-c",
        text: "幹，崩潰完，工班的錢要得回來嗎？",
        archetype: "perfect",
        retort: "……要不回來，只能認了（笑容僵住）。",
      },
      {
        id: "biaojie-housing-024-d",
        text: "幹，工班烙跑那我自己拿工具修。",
        archetype: "backfire",
        retort: "……你應該不是專業的吧（笑）。",
      },
      {
        id: "biaojie-housing-024-e",
        text: "靠，妳解決問題的能力真的強。",
        archetype: "deflect",
        retort: "謝謝，也是被磨出來的（笑）。",
      },
      {
        id: "biaojie-housing-024-f",
        text: "機掰，崩潰的時候，妳老公人咧，歐巴桑？",
        archetype: "landmine",
        retort: "他在上班，你去你的少亂講！",
      },
      {
        id: "biaojie-housing-024-g",
        text: "靠……我對裝潢合約完全看不懂……",
        archetype: "meek",
        retort: "看不懂就找人幫忙檢查。",
      },
      {
        id: "biaojie-housing-024-h",
        text: "機掰，崩潰那我去廟裡拜託土地公。",
        archetype: "backfire",
        retort: "……土地公沒辦法蓋房子啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-025",
    text: "房貸壓力真的很大，但日子還是要過。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-025-a",
        text: "靠北，扛房貸還這麼樂觀，妳很強。",
        archetype: "deflect",
        retort: "還好啦，習慣就好了（笑）。",
      },
      {
        id: "biaojie-housing-025-b",
        text: "幹……光想到房貸我就快喘不過氣……",
        archetype: "meek",
        retort: "喘不過氣要提早規劃。",
      },
      {
        id: "biaojie-housing-025-c",
        text: "幹，苦中作樂，房貸繳完了沒？",
        archetype: "perfect",
        retort: "……還早啦（笑容僵住），慢慢還。",
      },
      {
        id: "biaojie-housing-025-d",
        text: "幹，房貸壓力大那我去買樂透翻身。",
        archetype: "backfire",
        retort: "……樂透機率太低了啦（笑）。",
      },
      {
        id: "biaojie-housing-025-e",
        text: "靠，妳面對壓力的態度真的好。",
        archetype: "deflect",
        retort: "謝謝，都是為了這個家（笑）。",
      },
      {
        id: "biaojie-housing-025-f",
        text: "幹你娘，買超過能力，活該自己扛啦。",
        archetype: "landmine",
        retort: "我們算過了，你他媽的閉嘴！",
      },
      {
        id: "biaojie-housing-025-g",
        text: "靠……我怕自己扛不起這種壓力……",
        archetype: "meek",
        retort: "怕的話從小坪數開始。",
      },
      {
        id: "biaojie-housing-025-h",
        text: "機掰，日子要過，那我先過沒房貸的日子。",
        archetype: "backfire",
        retort: "……那樣講好像有點酸喔（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-026",
    text: "買房送全套家電，我們賺到了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-026-a",
        text: "靠北，談家電你們也太會殺價。",
        archetype: "deflect",
        retort: "對啊，老公很會談判呢（笑）。",
      },
      {
        id: "biaojie-housing-026-b",
        text: "幹……我完全不懂怎麼跟建商談這些……",
        archetype: "meek",
        retort: "不懂就找懂的人幫忙。",
      },
      {
        id: "biaojie-housing-026-c",
        text: "幹，送家電也要講，很怕人不知道？",
        archetype: "perfect",
        retort: "你他媽的被發現了很機車！",
      },
      {
        id: "biaojie-housing-026-d",
        text: "幹，送家電那我跟房東要冰箱試試。",
        archetype: "backfire",
        retort: "……房東的東西本來是租的（笑）。",
      },
      {
        id: "biaojie-housing-026-e",
        text: "靠，妳們真的很有議價能力。",
        archetype: "deflect",
        retort: "還好啦，多問幾間就知道（笑）。",
      },
      {
        id: "biaojie-housing-026-f",
        text: "去死啦，根本是灌水的行銷手法吧。",
        archetype: "landmine",
        retort: "才沒有，你機掰講什麼！",
      },
      {
        id: "biaojie-housing-026-g",
        text: "靠……感覺我們買房都不敢多要求……",
        archetype: "meek",
        retort: "不敢要求容易吃虧喔。",
      },
      {
        id: "biaojie-housing-026-h",
        text: "機掰，賺到那我跟超商要贈品。",
        archetype: "backfire",
        retort: "……那個規模差太多了啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-027",
    text: "老二的房間佈置成太空主題，超可愛。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-027-a",
        text: "靠北，佈置房間你們也太用心。",
        archetype: "deflect",
        retort: "對啊，挑壁貼挑了好久（笑）。",
      },
      {
        id: "biaojie-housing-027-b",
        text: "幹……我們家小孩房間還是白牆……",
        archetype: "meek",
        retort: "白牆也可以慢慢佈置。",
      },
      {
        id: "biaojie-housing-027-c",
        text: "幹，佈置這麼美，是要曬照片吧？",
        archetype: "perfect",
        retort: "……對啦，就愛拍照（笑容僵住）。",
      },
      {
        id: "biaojie-housing-027-d",
        text: "幹，太空主題那我房間貼星座運勢。",
        archetype: "backfire",
        retort: "……那個跟太空不一樣耶（笑）。",
      },
      {
        id: "biaojie-housing-027-e",
        text: "靠，妳的美感一直都很好。",
        archetype: "deflect",
        retort: "謝謝誇獎，網路找靈感的（笑）。",
      },
      {
        id: "biaojie-housing-027-f",
        text: "幹，佈置成這樣，老二根本不在乎吧，老女人。",
        archetype: "landmine",
        retort: "他很愛啦，你他媽的別亂講！",
      },
      {
        id: "biaojie-housing-027-g",
        text: "靠……佈置這種東西感覺很花錢……",
        archetype: "meek",
        retort: "花錢是真的，量力而為。",
      },
      {
        id: "biaojie-housing-027-h",
        text: "機掰，超可愛那我把家裡弄成太空艙。",
        archetype: "backfire",
        retort: "……太空艙好像不太實用啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-028",
    text: "我在陽台種菜，小孩還能學認識蔬菜。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-028-a",
        text: "笑死，種菜還能教小孩，妳想真周到。",
        archetype: "deflect",
        retort: "對啊，一舉兩得啦（笑）。",
      },
      {
        id: "biaojie-housing-028-b",
        text: "幹……我連盆栽都養不活，別說種菜了……",
        archetype: "meek",
        retort: "養不活就先種簡單的。",
      },
      {
        id: "biaojie-housing-028-c",
        text: "幹，食農教育，還是想省買菜錢？",
        archetype: "perfect",
        retort: "……好啦，被你猜中了（笑容僵住）。",
      },
      {
        id: "biaojie-housing-028-d",
        text: "幹，種菜那我陽台種發財樹賺錢。",
        archetype: "backfire",
        retort: "……發財樹不會讓你發財啦（笑）。",
      },
      {
        id: "biaojie-housing-028-e",
        text: "靠，妳連生活情趣都顧到了。",
        archetype: "deflect",
        retort: "還好啦，就是興趣使然（笑）。",
      },
      {
        id: "biaojie-housing-028-f",
        text: "他媽的，種菜是假，炫耀才是真的吧。",
        archetype: "landmine",
        retort: "夠了，去你的不用你操心！",
      },
      {
        id: "biaojie-housing-028-g",
        text: "靠……我們家陽台完全沒空間種東西……",
        archetype: "meek",
        retort: "沒空間真的比較可惜。",
      },
      {
        id: "biaojie-housing-028-h",
        text: "機掰，認識蔬菜那我帶他去超市看更快。",
        archetype: "backfire",
        retort: "……超市的菜體驗不一樣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-029",
    text: "我們多的車位租出去，順便貼補房貸。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-029-a",
        text: "靠北，出租車位你們真的很會理財。",
        archetype: "deflect",
        retort: "對啊，多一份收入不錯（笑）。",
      },
      {
        id: "biaojie-housing-029-b",
        text: "幹……我們家連自己的車位都不夠用……",
        archetype: "meek",
        retort: "不夠用要提早規劃。",
      },
      {
        id: "biaojie-housing-029-c",
        text: "幹，貼補房貸，一個月賺多少？",
        archetype: "perfect",
        retort: "……沒有很多啦，別問了（笑容僵住）。",
      },
      {
        id: "biaojie-housing-029-d",
        text: "幹，出租車位那我把陽台租給鄰居。",
        archetype: "backfire",
        retort: "……陽台沒辦法這樣租吧（笑）。",
      },
      {
        id: "biaojie-housing-029-e",
        text: "靠，妳腦筋動得真的很快。",
        archetype: "deflect",
        retort: "還好啦，多動點腦筋而已（笑）。",
      },
      {
        id: "biaojie-housing-029-f",
        text: "去你的，入不敷出還硬撐，歐巴桑妳很累吧。",
        archetype: "landmine",
        retort: "你他媽的莫名其妙，滾啦！",
      },
      {
        id: "biaojie-housing-029-g",
        text: "靠……我對出租這種事完全沒經驗……",
        archetype: "meek",
        retort: "沒經驗找中間平台。",
      },
      {
        id: "biaojie-housing-029-h",
        text: "機掰，貼補房貸那我把零用錢租出去。",
        archetype: "backfire",
        retort: "……零用錢沒辦法出租啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-030",
    text: "這間房以後要留給老大，先講清楚。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-030-a",
        text: "靠北，提早規劃財產，你們真有遠見。",
        archetype: "deflect",
        retort: "對啊，早點講清楚比較好（笑）。",
      },
      {
        id: "biaojie-housing-030-b",
        text: "幹……我們家連一間房都沒有，先別談……",
        archetype: "meek",
        retort: "先別談也好，一步一步來。",
      },
      {
        id: "biaojie-housing-030-c",
        text: "幹，先講清楚，總比以後撕破臉好。",
        archetype: "perfect",
        retort: "……也是啦，你很敢講（笑容僵住）。",
      },
      {
        id: "biaojie-housing-030-d",
        text: "幹，留給老大那我留公仔收藏給貓。",
        archetype: "backfire",
        retort: "……貓應該用不到公仔吧（笑）。",
      },
      {
        id: "biaojie-housing-030-e",
        text: "靠，妳考慮事情真的很長遠。",
        archetype: "deflect",
        retort: "還好啦，避免麻煩而已（笑）。",
      },
      {
        id: "biaojie-housing-030-f",
        text: "機掰，偏心老大，老二知道嗎？",
        archetype: "landmine",
        retort: "這是我們家的事，你他媽別管！",
      },
      {
        id: "biaojie-housing-030-g",
        text: "靠……這種家族財產的事我完全不懂……",
        archetype: "meek",
        retort: "不懂沒關係，以後會學到。",
      },
      {
        id: "biaojie-housing-030-h",
        text: "去你的，先講清楚那我先立遺囑好了。",
        archetype: "backfire",
        retort: "……你這什麼冷笑話，別烏鴉嘴（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-031",
    text: "房子登記在我跟老公名下，公平。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-031-a",
        text: "靠北，登記共同持有，感情真的好。",
        archetype: "deflect",
        retort: "對啊，什麼都一起決定（笑）。",
      },
      {
        id: "biaojie-housing-031-b",
        text: "幹……我對這種登記的規矩完全不懂……",
        archetype: "meek",
        retort: "不懂就找代書問清楚。",
      },
      {
        id: "biaojie-housing-031-c",
        text: "幹，公平最重要，那家事也對分？",
        archetype: "perfect",
        retort: "……那個不一樣啦（笑容僵住）。",
      },
      {
        id: "biaojie-housing-031-d",
        text: "幹，登記名下那我把房間登記給貓。",
        archetype: "backfire",
        retort: "……貓沒辦法當所有權人啦（笑）。",
      },
      {
        id: "biaojie-housing-031-e",
        text: "靠，妳們夫妻真的很有默契。",
        archetype: "deflect",
        retort: "還好啦，都是溝通出來的（笑）。",
      },
      {
        id: "biaojie-housing-031-f",
        text: "幹你娘咧，公平是嘴上說的，出錢的才有理吧。",
        archetype: "landmine",
        retort: "你很毒欸，去死啦，不想理你！",
      },
      {
        id: "biaojie-housing-031-g",
        text: "靠……我們家可能還沒討論到這一步……",
        archetype: "meek",
        retort: "沒討論要早點聊清楚。",
      },
      {
        id: "biaojie-housing-031-h",
        text: "機掰，公平那我把家事也登記平分。",
        archetype: "backfire",
        retort: "……家事分工跟登記不一樣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-032",
    text: "我們搬家打包三天才搬完，東西真多。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-032-a",
        text: "靠北，打包三天，你們收納超強。",
        archetype: "deflect",
        retort: "還好啦，邊搬邊丟舊東西（笑）。",
      },
      {
        id: "biaojie-housing-032-b",
        text: "幹……我們租屋處東西少，搬家很快……",
        archetype: "meek",
        retort: "東西少也好，方便搬家。",
      },
      {
        id: "biaojie-housing-032-c",
        text: "幹，東西多，是捨不得斷捨離吧？",
        archetype: "perfect",
        retort: "……好像也是啦（笑容僵住）。",
      },
      {
        id: "biaojie-housing-032-d",
        text: "幹，打包三天那我打包行李箱五分鐘。",
        archetype: "backfire",
        retort: "……你東西應該比較少啦（笑）。",
      },
      {
        id: "biaojie-housing-032-e",
        text: "靠，妳連搬家都安排得很有效率。",
        archetype: "deflect",
        retort: "謝謝誇獎，照表操課的（笑）。",
      },
      {
        id: "biaojie-housing-032-f",
        text: "去死，搬三天，是炫耀還是真的忙，老女人？",
        archetype: "landmine",
        retort: "（臉色一沉）你他媽的很沒禮貌！",
      },
      {
        id: "biaojie-housing-032-g",
        text: "靠……光想到搬家我就覺得很累……",
        archetype: "meek",
        retort: "累是真的，搬完就輕鬆。",
      },
      {
        id: "biaojie-housing-032-h",
        text: "機掰，東西真多那我幫你們辦二手拍賣。",
        archetype: "backfire",
        retort: "……我們的東西還要留著用（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-033",
    text: "我們今年房屋稅又漲了，好心疼。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-033-a",
        text: "靠北，繳這麼多稅，你們真是屋主等級。",
        archetype: "deflect",
        retort: "哪有，也是心痛地繳（笑）。",
      },
      {
        id: "biaojie-housing-033-b",
        text: "幹……我對這些稅金的東西完全不懂……",
        archetype: "meek",
        retort: "不懂以後買房要先了解。",
      },
      {
        id: "biaojie-housing-033-c",
        text: "幹，心疼歸心疼，該繳的一毛沒少吧？",
        archetype: "perfect",
        retort: "……是喔，那也沒辦法（笑容僵住）。",
      },
      {
        id: "biaojie-housing-033-d",
        text: "幹，房屋稅漲那我去繳手機月租費。",
        archetype: "backfire",
        retort: "……那個跟房屋稅沒關係吧（笑）。",
      },
      {
        id: "biaojie-housing-033-e",
        text: "靠，妳連繳稅都算得很清楚。",
        archetype: "deflect",
        retort: "還好啦，都是老公處理的（笑）。",
      },
      {
        id: "biaojie-housing-033-f",
        text: "幹，稅漲那麼多，還是老公幫妳算？",
        archetype: "landmine",
        retort: "問這個做什麼，你機掰很沒禮貌！",
      },
      {
        id: "biaojie-housing-033-g",
        text: "靠……光聽就覺得買房後面開銷還很多……",
        archetype: "meek",
        retort: "開銷是真的多，要準備。",
      },
      {
        id: "biaojie-housing-033-h",
        text: "機掰，好心疼那我幫你們默哀三秒。",
        archetype: "backfire",
        retort: "……默哀解決不了問題啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-034",
    text: "我們家選高樓層，採光好又沒蚊蟲。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-034-a",
        text: "靠北，挑樓層你們考慮真周到。",
        archetype: "deflect",
        retort: "對啊，特地挑高一點的樓層（笑）。",
      },
      {
        id: "biaojie-housing-034-b",
        text: "幹……我們住比較低樓層，蚊蟲不少……",
        archetype: "meek",
        retort: "蚊蟲多要多噴防蚊液。",
      },
      {
        id: "biaojie-housing-034-c",
        text: "幹，採光好，是曬照片還是曬太陽？",
        archetype: "perfect",
        retort: "……真的順便啦（笑容僵住）。",
      },
      {
        id: "biaojie-housing-034-d",
        text: "幹，沒蚊蟲那我家蚊子特地飛去你家。",
        archetype: "backfire",
        retort: "……蚊子應該不會挑地方吧（笑）。",
      },
      {
        id: "biaojie-housing-034-e",
        text: "靠，妳連細節都想得好仔細。",
        archetype: "deflect",
        retort: "習慣了，住得舒服比較重要（笑）。",
      },
      {
        id: "biaojie-housing-034-f",
        text: "他媽的，採光好，公婆是不是常來住？",
        archetype: "landmine",
        retort: "偶爾啦，你他媽別問這麼細！",
      },
      {
        id: "biaojie-housing-034-g",
        text: "靠……採光不好，家裡總覺得陰陰的……",
        archetype: "meek",
        retort: "陰陰的心情也會受影響。",
      },
      {
        id: "biaojie-housing-034-h",
        text: "機掰，採光好那我家開燈也算採光。",
        archetype: "backfire",
        retort: "……開燈不算天然採光啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-035",
    text: "我們這間房增值不少，算投資成功。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-035-a",
        text: "靠北，增值這麼多，你們真會挑時機。",
        archetype: "deflect",
        retort: "對啊，剛好搭上一波（笑）。",
      },
      {
        id: "biaojie-housing-035-b",
        text: "幹……我對投資這方面完全沒有概念……",
        archetype: "meek",
        retort: "沒概念要慢慢學理財。",
      },
      {
        id: "biaojie-housing-035-c",
        text: "幹，增值多少，拿去還房貸了嗎？",
        archetype: "perfect",
        retort: "……還沒啦，慢慢來（笑容僵住）。",
      },
      {
        id: "biaojie-housing-035-d",
        text: "幹，增值那我把公仔拿去估價。",
        archetype: "backfire",
        retort: "……公仔沒有房子那麼值錢啦（笑）。",
      },
      {
        id: "biaojie-housing-035-e",
        text: "靠，妳投資的眼光真的很準。",
        archetype: "deflect",
        retort: "還好啦，做了很多功課（笑）。",
      },
      {
        id: "biaojie-housing-035-f",
        text: "去你的，口口聲聲自住，其實想套現吧，歐巴桑。",
        archetype: "landmine",
        retort: "（臉都綠了）你他媽的才沒有！",
      },
      {
        id: "biaojie-housing-035-g",
        text: "靠……感覺我們永遠追不上房價漲幅……",
        archetype: "meek",
        retort: "追不上要早點行動。",
      },
      {
        id: "biaojie-housing-035-h",
        text: "機掰，投資成功那我投資我的睡眠時間。",
        archetype: "backfire",
        retort: "……那個好像不算真的投資啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-036",
    text: "群組在聊誰家坪數大，我們排第一。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-036-a",
        text: "靠北，坪數這麼大，住起來一定舒服。",
        archetype: "deflect",
        retort: "對啊，走路都不會撞到（笑）。",
      },
      {
        id: "biaojie-housing-036-b",
        text: "幹……我們家坪數應該排最後一名……",
        archetype: "meek",
        retort: "排最後沒關係，夠住就好。",
      },
      {
        id: "biaojie-housing-036-c",
        text: "幹，第一名，要不要分享裝潢費？",
        archetype: "perfect",
        retort: "……哈哈這個不能講（笑容僵住）。",
      },
      {
        id: "biaojie-housing-036-d",
        text: "幹，坪數第一那我加陽台湊坪數。",
        archetype: "backfire",
        retort: "……陽台不算室內坪數啦（笑）。",
      },
      {
        id: "biaojie-housing-036-e",
        text: "靠，妳們家真的是別人的夢想。",
        archetype: "deflect",
        retort: "哪有，都是慢慢努力來的（笑）。",
      },
      {
        id: "biaojie-housing-036-f",
        text: "坪數第一，房貸是不是也第一，老女人？",
        archetype: "landmine",
        retort: "才沒欠很多，你他媽的很白目！",
      },
      {
        id: "biaojie-housing-036-g",
        text: "靠……看到這種排名我都不敢講話……",
        archetype: "meek",
        retort: "不敢講話沒關係，慢慢努力。",
      },
      {
        id: "biaojie-housing-036-h",
        text: "去你的，排第一那我家心胸最寬廣排第一。",
        archetype: "backfire",
        retort: "……那個好像沒辦法比較啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-037",
    text: "入厝紅包有規矩，數字要吉利喔。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-037-a",
        text: "靠北，妳連這種習俗都懂這麼多。",
        archetype: "deflect",
        retort: "都是長輩教的啦，實用（笑）。",
      },
      {
        id: "biaojie-housing-037-b",
        text: "幹……我對這些數字規矩完全不清楚……",
        archetype: "meek",
        retort: "不清楚要先問清楚比較好。",
      },
      {
        id: "biaojie-housing-037-c",
        text: "幹，規矩這麼多，是要湊年終獎金？",
        archetype: "perfect",
        retort: "……哪有，圖個吉利啦（笑容僵住）。",
      },
      {
        id: "biaojie-housing-037-d",
        text: "幹，吉利數字那我包888元意思一下。",
        archetype: "backfire",
        retort: "……888元感覺有點少耶（笑）。",
      },
      {
        id: "biaojie-housing-037-e",
        text: "靠，你們家的規矩一直都辦得很周到。",
        archetype: "deflect",
        retort: "謝謝誇獎，圖個吉利嘛（笑）。",
      },
      {
        id: "biaojie-housing-037-f",
        text: "幹你娘，講這麼多規矩，根本想多收錢吧，歐巴桑。",
        archetype: "landmine",
        retort: "講這什麼話，你去死啦我不想聽！",
      },
      {
        id: "biaojie-housing-037-g",
        text: "靠……我怕包錯數字會不吉利……",
        archetype: "meek",
        retort: "怕的話提前問我就好啦。",
      },
      {
        id: "biaojie-housing-037-h",
        text: "機掰，有規矩那我包一張手寫祝福卡。",
        archetype: "backfire",
        retort: "……入厝紅包還是要包現金啦（笑）。",
      },
    ],
  },
] satisfies Question[];
