// situations: 頂樓加蓋舊公寓翻新、選電梯大樓vs透天、買預售屋vs成屋、
// 裝修遇工班烙跑糾紛、房貸壓力日子還是要過、買房送裝潢家電、
// 小孩房間主題佈置、陽台種菜小花園、買車位出租賺錢、房子要留給老大的繼承規劃、
// 買房登記在誰名下、搬家打包辛苦暗示租屋處小、房屋稅地價稅話題、
// 樓層採光蚊蟲問題、買房投資增值角度、家族群組討論誰家坪數最大、買房入厝紅包規矩
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-housing-021",
    text: "老家頂樓加蓋，我們花錢整個翻新。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-021-a",
        text: "翻新工程你們一定盯很緊。",
        archetype: "deflect",
        retort: "對啊，天天跑工地監工（笑）。",
      },
      {
        id: "biaojie-housing-021-b",
        text: "我們連請工班的錢都湊不齊……",
        archetype: "meek",
        retort: "湊不齊的話要慢慢分階段做。",
      },
      {
        id: "biaojie-housing-021-c",
        text: "翻新好，舊的地方也能發光發熱。",
        archetype: "perfect",
        retort: "說得真好，我要引用這句（笑）。",
      },
      {
        id: "biaojie-housing-021-d",
        text: "頂樓加蓋，那我在陽台搭帳篷。",
        archetype: "backfire",
        retort: "……帳篷應該撐不了多久喔（笑）。",
      },
      {
        id: "biaojie-housing-021-e",
        text: "表姊你監督工程一定很細心。",
        archetype: "deflect",
        retort: "還好啦，多看幾次就熟練了（笑）。",
      },
      {
        id: "biaojie-housing-021-f",
        text: "頂樓加蓋該不會是違建吧？",
        archetype: "landmine",
        retort: "……有申請，都是合法的。",
      },
      {
        id: "biaojie-housing-021-g",
        text: "老房子翻新聽起來很麻煩……",
        archetype: "meek",
        retort: "麻煩是真的，但值回票價。",
      },
      {
        id: "biaojie-housing-021-h",
        text: "翻新，那我把房間重新排家具。",
        archetype: "backfire",
        retort: "……那個不算翻新啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-022",
    text: "我們選電梯大樓，透天太難照顧了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-022-a",
        text: "選房型你們考慮得很仔細。",
        archetype: "deflect",
        retort: "對啊，比較了很多次才決定（笑）。",
      },
      {
        id: "biaojie-housing-022-b",
        text: "我對這兩種房型的差別搞不清楚……",
        archetype: "meek",
        retort: "搞不清楚的話要多比較一下。",
      },
      {
        id: "biaojie-housing-022-c",
        text: "難照顧才顯功力，你們選得聰明。",
        archetype: "perfect",
        retort: "謝謝你這樣說（笑）。",
      },
      {
        id: "biaojie-housing-022-d",
        text: "電梯大樓，那我家爬樓梯練體力。",
        archetype: "backfire",
        retort: "……那不算真的選擇吧（笑）。",
      },
      {
        id: "biaojie-housing-022-e",
        text: "表姊你做決定都很有邏輯。",
        archetype: "deflect",
        retort: "還好啦，都是聽老公分析的（笑）。",
      },
      {
        id: "biaojie-housing-022-f",
        text: "電梯大樓，是不是管理費很貴？",
        archetype: "landmine",
        retort: "……有一點，但物有所值。",
      },
      {
        id: "biaojie-housing-022-g",
        text: "我們家連公寓都負擔得吃力……",
        archetype: "meek",
        retort: "吃力的話要重新規劃預算。",
      },
      {
        id: "biaojie-housing-022-h",
        text: "透天難照顧，那我住帳篷更難。",
        archetype: "backfire",
        retort: "……帳篷不算房子啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-023",
    text: "我們買預售屋，等交屋還要兩年。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-023-a",
        text: "買預售屋，你們一定很有耐心。",
        archetype: "deflect",
        retort: "對啊，等待也是一種修行（笑）。",
      },
      {
        id: "biaojie-housing-023-b",
        text: "我對預售屋的流程完全不懂……",
        archetype: "meek",
        retort: "不懂的話要找懂的人幫忙看。",
      },
      {
        id: "biaojie-housing-023-c",
        text: "兩年可以慢慢存嫁妝，剛剛好。",
        archetype: "perfect",
        retort: "哈哈也是，你很會安排（笑）。",
      },
      {
        id: "biaojie-housing-023-d",
        text: "預售屋，那我先預購晚餐好了。",
        archetype: "backfire",
        retort: "……晚餐應該不用預購兩年吧（笑）。",
      },
      {
        id: "biaojie-housing-023-e",
        text: "表姊你們規劃時間都抓得很準。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢學的（笑）。",
      },
      {
        id: "biaojie-housing-023-f",
        text: "預售屋，是不是想賺轉手的價差？",
        archetype: "landmine",
        retort: "……不是，只是單純自住而已。",
      },
      {
        id: "biaojie-housing-023-g",
        text: "等兩年感覺好久，會擔心變數……",
        archetype: "meek",
        retort: "會擔心正常，多留意合約就好。",
      },
      {
        id: "biaojie-housing-023-h",
        text: "等交屋，那我先租帳篷住兩年。",
        archetype: "backfire",
        retort: "……帳篷住兩年太辛苦了啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-024",
    text: "我們裝潢遇到工班烙跑，很崩潰。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-024-a",
        text: "遇到這種事你們處理得很冷靜。",
        archetype: "deflect",
        retort: "還好啦，事情發生只能面對（笑）。",
      },
      {
        id: "biaojie-housing-024-b",
        text: "我聽到這種事就覺得很害怕……",
        archetype: "meek",
        retort: "害怕正常，簽約前要多小心。",
      },
      {
        id: "biaojie-housing-024-c",
        text: "崩潰過後才懂事，這課學費值得。",
        archetype: "perfect",
        retort: "你這樣講，我心裡好受一點（笑）。",
      },
      {
        id: "biaojie-housing-024-d",
        text: "工班烙跑，那我自己拿工具修。",
        archetype: "backfire",
        retort: "……你應該不是專業的吧（笑）。",
      },
      {
        id: "biaojie-housing-024-e",
        text: "表姊你解決問題的能力真的強。",
        archetype: "deflect",
        retort: "謝謝，也是被磨出來的（笑）。",
      },
      {
        id: "biaojie-housing-024-f",
        text: "是不是你們自己沒事先做功課？",
        archetype: "landmine",
        retort: "……也許吧，我們會更小心。",
      },
      {
        id: "biaojie-housing-024-g",
        text: "我對裝潢的合約完全看不懂……",
        archetype: "meek",
        retort: "看不懂的話要找人幫忙檢查。",
      },
      {
        id: "biaojie-housing-024-h",
        text: "崩潰，那我去廟裡拜託土地公。",
        archetype: "backfire",
        retort: "……土地公可能沒辦法蓋房子啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-025",
    text: "房貸壓力真的很大，但日子還是要過。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-025-a",
        text: "扛著房貸還這麼樂觀，你很堅強。",
        archetype: "deflect",
        retort: "還好啦，習慣就好了（笑）。",
      },
      {
        id: "biaojie-housing-025-b",
        text: "光想到房貸我就覺得喘不過氣……",
        archetype: "meek",
        retort: "喘不過氣的話要提早規劃預算。",
      },
      {
        id: "biaojie-housing-025-c",
        text: "日子要過，苦中作樂才是真本事。",
        archetype: "perfect",
        retort: "你說得真好，謝謝你（笑）。",
      },
      {
        id: "biaojie-housing-025-d",
        text: "房貸壓力大，那我去買樂透翻身。",
        archetype: "backfire",
        retort: "……樂透機率太低了啦（笑）。",
      },
      {
        id: "biaojie-housing-025-e",
        text: "表姊你面對壓力的態度真的好。",
        archetype: "deflect",
        retort: "謝謝，都是為了這個家啦（笑）。",
      },
      {
        id: "biaojie-housing-025-f",
        text: "壓力那麼大，是不是買超過能力範圍？",
        archetype: "landmine",
        retort: "……沒有，我們算過能負擔的。",
      },
      {
        id: "biaojie-housing-025-g",
        text: "我怕自己扛不起這種壓力……",
        archetype: "meek",
        retort: "怕的話可以先從小坪數開始。",
      },
      {
        id: "biaojie-housing-025-h",
        text: "日子要過，那我先過沒房貸的日子。",
        archetype: "backfire",
        retort: "……那樣說好像有點酸喔（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-026",
    text: "買房送全套家電，我們賺到了。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-026-a",
        text: "談到送家電，你們一定很會殺價。",
        archetype: "deflect",
        retort: "對啊，老公很會談判呢（笑）。",
      },
      {
        id: "biaojie-housing-026-b",
        text: "我完全不懂怎麼跟建商談這些……",
        archetype: "meek",
        retort: "不懂的話可以找懂的人幫忙。",
      },
      {
        id: "biaojie-housing-026-c",
        text: "賺到最好，我先預約來蹭冰箱。",
        archetype: "perfect",
        retort: "哈哈歡迎你隨時來拿東西（笑）。",
      },
      {
        id: "biaojie-housing-026-d",
        text: "送家電，那我跟房東要冰箱試試。",
        archetype: "backfire",
        retort: "……房東的東西本來就是租的（笑）。",
      },
      {
        id: "biaojie-housing-026-e",
        text: "表姊你們真的很有議價能力。",
        archetype: "deflect",
        retort: "還好啦，多問幾間就知道了（笑）。",
      },
      {
        id: "biaojie-housing-026-f",
        text: "送那麼多，該不會房價其實有灌水？",
        archetype: "landmine",
        retort: "……沒有，我們有比較過行情。",
      },
      {
        id: "biaojie-housing-026-g",
        text: "感覺我們買房都不敢多要求……",
        archetype: "meek",
        retort: "不敢要求的話容易吃虧喔。",
      },
      {
        id: "biaojie-housing-026-h",
        text: "賺到，那我跟便利商店要贈品。",
        archetype: "backfire",
        retort: "……那個規模差太多了啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-027",
    text: "老二的房間佈置成太空主題，超可愛。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-027-a",
        text: "布置房間你們一定花了不少心思。",
        archetype: "deflect",
        retort: "對啊，挑壁貼挑了好久（笑）。",
      },
      {
        id: "biaojie-housing-027-b",
        text: "我們家小孩房間還維持原本白牆……",
        archetype: "meek",
        retort: "白牆也可以慢慢加點佈置。",
      },
      {
        id: "biaojie-housing-027-c",
        text: "太空主題好，順便訓練未來太空人。",
        archetype: "perfect",
        retort: "哈哈說不定真的可以（笑）。",
      },
      {
        id: "biaojie-housing-027-d",
        text: "太空主題，那我房間貼星座運勢。",
        archetype: "backfire",
        retort: "……那個跟太空不太一樣耶（笑）。",
      },
      {
        id: "biaojie-housing-027-e",
        text: "表姊你的美感一直都很好。",
        archetype: "deflect",
        retort: "謝謝誇獎，都是網路找靈感的（笑）。",
      },
      {
        id: "biaojie-housing-027-f",
        text: "花這麼多錢佈置，小孩真的在意嗎？",
        archetype: "landmine",
        retort: "……他很喜歡，看他開心就值得。",
      },
      {
        id: "biaojie-housing-027-g",
        text: "佈置這種東西感覺很花錢……",
        archetype: "meek",
        retort: "花錢是真的，但可以量力而為。",
      },
      {
        id: "biaojie-housing-027-h",
        text: "超可愛，那我把家裡也弄成太空艙。",
        archetype: "backfire",
        retort: "……太空艙好像不太實用啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-028",
    text: "我在陽台種菜，小孩還能學認識蔬菜。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-028-a",
        text: "種菜還能教小孩，你想得真周到。",
        archetype: "deflect",
        retort: "對啊，一舉兩得啦（笑）。",
      },
      {
        id: "biaojie-housing-028-b",
        text: "我連盆栽都養不活，別說種菜了……",
        archetype: "meek",
        retort: "養不活的話可以先從簡單的種。",
      },
      {
        id: "biaojie-housing-028-c",
        text: "食農教育，我先預約來採收一把菜。",
        archetype: "perfect",
        retort: "哈哈歡迎你隨時來採（笑）。",
      },
      {
        id: "biaojie-housing-028-d",
        text: "種菜，那我在陽台種發財樹賺錢。",
        archetype: "backfire",
        retort: "……發財樹不會真的讓你發財啦（笑）。",
      },
      {
        id: "biaojie-housing-028-e",
        text: "表姊你連生活情趣都顧到了。",
        archetype: "deflect",
        retort: "還好啦，就是興趣使然（笑）。",
      },
      {
        id: "biaojie-housing-028-f",
        text: "種那些菜，真的有拿來吃嗎？",
        archetype: "landmine",
        retort: "……有啊，我們常常摘來煮。",
      },
      {
        id: "biaojie-housing-028-g",
        text: "我們家陽台完全沒有空間種東西……",
        archetype: "meek",
        retort: "沒空間的話真的比較可惜。",
      },
      {
        id: "biaojie-housing-028-h",
        text: "認識蔬菜，那我帶他去超市看更快。",
        archetype: "backfire",
        retort: "……超市的菜跟種的體驗不一樣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-029",
    text: "我們多的車位租出去，順便貼補房貸。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-029-a",
        text: "想到出租車位，你們真的很會理財。",
        archetype: "deflect",
        retort: "對啊，多一份收入也不錯（笑）。",
      },
      {
        id: "biaojie-housing-029-b",
        text: "我們家連自己的車位都不夠用……",
        archetype: "meek",
        retort: "不夠用的話要提早規劃停車。",
      },
      {
        id: "biaojie-housing-029-c",
        text: "貼補房貸有一套，我要跟你請教。",
        archetype: "perfect",
        retort: "沒問題，改天教你怎麼弄（笑）。",
      },
      {
        id: "biaojie-housing-029-d",
        text: "出租車位，那我把陽台租給鄰居。",
        archetype: "backfire",
        retort: "……陽台應該沒辦法這樣租吧（笑）。",
      },
      {
        id: "biaojie-housing-029-e",
        text: "表姊你腦筋動得真的很快。",
        archetype: "deflect",
        retort: "還好啦，都是慢慢學的（笑）。",
      },
      {
        id: "biaojie-housing-029-f",
        text: "租出去，是不是其實入不敷出？",
        archetype: "landmine",
        retort: "……不是，只是想多一份收入。",
      },
      {
        id: "biaojie-housing-029-g",
        text: "我對出租這種事完全沒經驗……",
        archetype: "meek",
        retort: "沒經驗的話可以找中間平台。",
      },
      {
        id: "biaojie-housing-029-h",
        text: "貼補房貸，那我把零用錢租出去。",
        archetype: "backfire",
        retort: "……零用錢沒辦法出租啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-030",
    text: "這間房以後要留給老大，先講清楚。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-030-a",
        text: "提早規劃財產，你們真的很有遠見。",
        archetype: "deflect",
        retort: "對啊，早點講清楚比較好（笑）。",
      },
      {
        id: "biaojie-housing-030-b",
        text: "我們家連一間房都沒有，先別談……",
        archetype: "meek",
        retort: "先別談也好，一步一步來。",
      },
      {
        id: "biaojie-housing-030-c",
        text: "講清楚最重要，避免以後吵成一團。",
        archetype: "perfect",
        retort: "你這樣說真的很成熟（笑）。",
      },
      {
        id: "biaojie-housing-030-d",
        text: "留給老大，那我留公仔收藏給貓。",
        archetype: "backfire",
        retort: "……貓應該用不到公仔吧（笑）。",
      },
      {
        id: "biaojie-housing-030-e",
        text: "表姊你考慮事情真的很長遠。",
        archetype: "deflect",
        retort: "還好啦，也是為了避免麻煩（笑）。",
      },
      {
        id: "biaojie-housing-030-f",
        text: "先講清楚，是不是怕老二以後搶？",
        archetype: "landmine",
        retort: "……不是，只是提早溝通而已。",
      },
      {
        id: "biaojie-housing-030-g",
        text: "這種家族財產的事我完全不懂……",
        archetype: "meek",
        retort: "不懂沒關係，以後會學到的。",
      },
      {
        id: "biaojie-housing-030-h",
        text: "先講清楚，那我先立遺囑好了。",
        archetype: "backfire",
        retort: "……你還年輕，先別想這麼遠啦。",
      },
    ],
  },
  {
    id: "biaojie-housing-031",
    text: "房子登記在我跟老公名下，公平。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-031-a",
        text: "登記共同持有，你們感情真的好。",
        archetype: "deflect",
        retort: "對啊，什麼都一起決定（笑）。",
      },
      {
        id: "biaojie-housing-031-b",
        text: "我對這種登記的規矩完全不懂……",
        archetype: "meek",
        retort: "不懂的話要找代書問清楚。",
      },
      {
        id: "biaojie-housing-031-c",
        text: "公平最重要，我先預約當公證人。",
        archetype: "perfect",
        retort: "哈哈好啊，歡迎你來公證（笑）。",
      },
      {
        id: "biaojie-housing-031-d",
        text: "登記名下，那我把房間登記給貓。",
        archetype: "backfire",
        retort: "……貓沒辦法當房屋所有權人啦（笑）。",
      },
      {
        id: "biaojie-housing-031-e",
        text: "表姊你們夫妻真的很有默契。",
        archetype: "deflect",
        retort: "還好啦，都是溝通出來的（笑）。",
      },
      {
        id: "biaojie-housing-031-f",
        text: "共同登記，是不是怕以後有變數？",
        archetype: "landmine",
        retort: "……沒有，只是覺得這樣公平。",
      },
      {
        id: "biaojie-housing-031-g",
        text: "我們家可能還沒討論到這一步……",
        archetype: "meek",
        retort: "沒討論的話要早點聊清楚。",
      },
      {
        id: "biaojie-housing-031-h",
        text: "公平，那我把家事也登記平分。",
        archetype: "backfire",
        retort: "……家事分工跟登記房子不一樣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-032",
    text: "我們搬家打包三天才搬完，東西真多。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-032-a",
        text: "打包三天，你們一定收納超強。",
        archetype: "deflect",
        retort: "還好啦，邊搬邊丟一些舊東西（笑）。",
      },
      {
        id: "biaojie-housing-032-b",
        text: "我們租屋處東西比較少，搬家很快……",
        archetype: "meek",
        retort: "東西少也好，至少方便搬家。",
      },
      {
        id: "biaojie-housing-032-c",
        text: "東西多是幸福的煩惱，我先羨慕一下。",
        archetype: "perfect",
        retort: "哈哈也是啦，謝謝你（笑）。",
      },
      {
        id: "biaojie-housing-032-d",
        text: "打包三天，那我打包行李箱五分鐘。",
        archetype: "backfire",
        retort: "……你東西應該比較少啦（笑）。",
      },
      {
        id: "biaojie-housing-032-e",
        text: "表姊你連搬家都安排得很有效率。",
        archetype: "deflect",
        retort: "謝謝誇獎，都是照表操課的（笑）。",
      },
      {
        id: "biaojie-housing-032-f",
        text: "搬那麼多東西，是不是捨不得丟舊的？",
        archetype: "landmine",
        retort: "……有一部分啦，都是回憶。",
      },
      {
        id: "biaojie-housing-032-g",
        text: "光想到搬家我就覺得很累……",
        archetype: "meek",
        retort: "累是真的，但搬完就輕鬆了。",
      },
      {
        id: "biaojie-housing-032-h",
        text: "東西真多，那我幫你們辦二手拍賣。",
        archetype: "backfire",
        retort: "……我們的東西還要留著用耶（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-033",
    text: "我們今年房屋稅又漲了，好心疼。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-033-a",
        text: "繳這麼多稅，你們真的是屋主等級。",
        archetype: "deflect",
        retort: "哪有，也是心痛地繳（笑）。",
      },
      {
        id: "biaojie-housing-033-b",
        text: "我對這些稅金的東西完全不懂……",
        archetype: "meek",
        retort: "不懂的話以後買房要先了解。",
      },
      {
        id: "biaojie-housing-033-c",
        text: "心疼歸心疼，這代表房子真的值錢。",
        archetype: "perfect",
        retort: "你這樣說，我瞬間釋懷了（笑）。",
      },
      {
        id: "biaojie-housing-033-d",
        text: "房屋稅漲，那我去繳手機月租費。",
        archetype: "backfire",
        retort: "……那個跟房屋稅沒關係吧（笑）。",
      },
      {
        id: "biaojie-housing-033-e",
        text: "表姊你連繳稅都算得很清楚。",
        archetype: "deflect",
        retort: "還好啦，都是老公在處理的（笑）。",
      },
      {
        id: "biaojie-housing-033-f",
        text: "稅漲那麼多，該不會其實漏報什麼？",
        archetype: "landmine",
        retort: "……沒有，我們都照實申報。",
      },
      {
        id: "biaojie-housing-033-g",
        text: "光聽就覺得買房後面開銷還很多……",
        archetype: "meek",
        retort: "開銷是真的多，要提早準備。",
      },
      {
        id: "biaojie-housing-033-h",
        text: "好心疼，那我幫你們默哀三秒。",
        archetype: "backfire",
        retort: "……默哀好像也解決不了問題（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-034",
    text: "我們家選高樓層，採光好又沒蚊蟲。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-034-a",
        text: "挑樓層，你們考慮得真周到。",
        archetype: "deflect",
        retort: "對啊，特地挑高一點的樓層（笑）。",
      },
      {
        id: "biaojie-housing-034-b",
        text: "我們住的地方比較低樓層，蚊蟲不少……",
        archetype: "meek",
        retort: "蚊蟲多的話要多噴防蚊液。",
      },
      {
        id: "biaojie-housing-034-c",
        text: "採光好又沒蚊蟲，先借我曬太陽。",
        archetype: "perfect",
        retort: "隨時歡迎你來曬（笑）。",
      },
      {
        id: "biaojie-housing-034-d",
        text: "沒蚊蟲，那我家蚊子特地飛去你家。",
        archetype: "backfire",
        retort: "……蚊子應該不會挑地方吧（笑）。",
      },
      {
        id: "biaojie-housing-034-e",
        text: "表姊你連細節都想得好仔細。",
        archetype: "deflect",
        retort: "習慣了，住得舒服比較重要（笑）。",
      },
      {
        id: "biaojie-housing-034-f",
        text: "高樓層，會不會其實反而很搖？",
        archetype: "landmine",
        retort: "……還好，我們住得很習慣。",
      },
      {
        id: "biaojie-housing-034-g",
        text: "採光不好，家裡總覺得陰陰的……",
        archetype: "meek",
        retort: "陰陰的話心情也會受影響喔。",
      },
      {
        id: "biaojie-housing-034-h",
        text: "採光好，那我家開燈也算採光。",
        archetype: "backfire",
        retort: "……開燈不算天然採光啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-035",
    text: "我們這間房增值不少，算投資成功。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-035-a",
        text: "增值這麼多，你們一定很會挑時機。",
        archetype: "deflect",
        retort: "對啊，剛好搭上一波（笑）。",
      },
      {
        id: "biaojie-housing-035-b",
        text: "我對投資這方面完全沒有概念……",
        archetype: "meek",
        retort: "沒概念的話要慢慢學習理財。",
      },
      {
        id: "biaojie-housing-035-c",
        text: "投資成功最重要，恭喜你們眼光好。",
        archetype: "perfect",
        retort: "謝謝你，也是運氣加眼光（笑）。",
      },
      {
        id: "biaojie-housing-035-d",
        text: "增值，那我把公仔拿去估價。",
        archetype: "backfire",
        retort: "……公仔應該沒有房子那麼值錢（笑）。",
      },
      {
        id: "biaojie-housing-035-e",
        text: "表姊你投資的眼光真的很準。",
        archetype: "deflect",
        retort: "還好啦，也是做了很多功課（笑）。",
      },
      {
        id: "biaojie-housing-035-f",
        text: "增值那麼多，是不是想賣掉套現？",
        archetype: "landmine",
        retort: "……沒有，我們是自住為主。",
      },
      {
        id: "biaojie-housing-035-g",
        text: "感覺我們永遠追不上房價漲幅……",
        archetype: "meek",
        retort: "追不上的話要早點開始行動。",
      },
      {
        id: "biaojie-housing-035-h",
        text: "投資成功，那我投資我的睡眠時間。",
        archetype: "backfire",
        retort: "……那個好像不算真的投資啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-036",
    text: "群組在聊誰家坪數大，我們排第一。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-036-a",
        text: "坪數這麼大，你們住起來一定舒服。",
        archetype: "deflect",
        retort: "對啊，走起路來都不會撞到（笑）。",
      },
      {
        id: "biaojie-housing-036-b",
        text: "我們家坪數應該是排最後一名……",
        archetype: "meek",
        retort: "排最後也沒關係，夠住就好。",
      },
      {
        id: "biaojie-housing-036-c",
        text: "第一名恭喜你，我先預約去參觀。",
        archetype: "perfect",
        retort: "隨時歡迎你來玩（笑）。",
      },
      {
        id: "biaojie-housing-036-d",
        text: "坪數第一，那我加陽台湊坪數。",
        archetype: "backfire",
        retort: "……陽台應該不算室內坪數啦（笑）。",
      },
      {
        id: "biaojie-housing-036-e",
        text: "表姊你們家真的是別人的夢想。",
        archetype: "deflect",
        retort: "哪有，都是慢慢努力來的（笑）。",
      },
      {
        id: "biaojie-housing-036-f",
        text: "坪數排第一，是不是特地拿出來比？",
        archetype: "landmine",
        retort: "……沒有，是大家自己聊起來的。",
      },
      {
        id: "biaojie-housing-036-g",
        text: "看到這種排名我都不敢講話……",
        archetype: "meek",
        retort: "不敢講話沒關係，慢慢努力。",
      },
      {
        id: "biaojie-housing-036-h",
        text: "排第一，那我家心胸最寬廣排第一。",
        archetype: "backfire",
        retort: "……那個好像沒辦法比較（笑）。",
      },
    ],
  },
  {
    id: "biaojie-housing-037",
    text: "入厝紅包有規矩，數字要吉利喔。",
    topic: "housing",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-housing-037-a",
        text: "表姊你連這種習俗都懂得好多。",
        archetype: "deflect",
        retort: "都是長輩教的啦，實用（笑）。",
      },
      {
        id: "biaojie-housing-037-b",
        text: "我對這些數字規矩完全不清楚……",
        archetype: "meek",
        retort: "不清楚的話要先問清楚比較好。",
      },
      {
        id: "biaojie-housing-037-c",
        text: "吉利數字我早就準備好了，放心。",
        archetype: "perfect",
        retort: "哎唷，你真的很懂規矩（笑）。",
      },
      {
        id: "biaojie-housing-037-d",
        text: "吉利數字，那我包888元意思一下。",
        archetype: "backfire",
        retort: "……888元感覺有點少耶（笑）。",
      },
      {
        id: "biaojie-housing-037-e",
        text: "你們家的規矩一直都辦得很周到。",
        archetype: "deflect",
        retort: "謝謝誇獎，圖個吉利嘛（笑）。",
      },
      {
        id: "biaojie-housing-037-f",
        text: "這麼多規矩，是不是想多收一點？",
        archetype: "landmine",
        retort: "……沒有，都是老一輩傳下來的。",
      },
      {
        id: "biaojie-housing-037-g",
        text: "我怕包錯數字會不吉利……",
        archetype: "meek",
        retort: "怕的話提前問我就好啦。",
      },
      {
        id: "biaojie-housing-037-h",
        text: "有規矩，那我包一張手寫祝福卡。",
        archetype: "backfire",
        retort: "……入厝紅包還是要包現金啦（笑）。",
      },
    ],
  },
] satisfies Question[];
