// situations: 圍爐催生、抱老二餵奶催生、老大在旁邊被逗叫人兼催生、親子餐廳心得、
// 家族群組發老二滿月照、月子中心費用、保母費、雙語幼兒園學費、才藝班(鋼琴)、
// 老二英文名字、婆家幫忙帶小孩、生二胎計畫、小孩挑食、不給看3C育兒方式、
// 過年紅包給小孩多少、全家福拍照名額、老公陪產神隊友發言、母乳哺餵、
// 坐月子習俗、圍爐兩寶吵鬧
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-kids-001",
    text: "你們也該生一個了吧？我陪你研究。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-001-a",
        text: "老二最近會不會走路了？超想看。",
        archetype: "deflect",
        retort: "會啊！走得歪七扭八可愛死了（笑）。",
      },
      {
        id: "biaojie-kids-001-b",
        text: "我們還在存錢啦，還沒準備好……",
        archetype: "meek",
        retort: "存錢是一回事，時間不等人的喔。",
      },
      {
        id: "biaojie-kids-001-c",
        text: "你這麼上心，等等換你生老三？",
        archetype: "perfect",
        retort: "……我、我只是關心一下啦（笑）。",
      },
      {
        id: "biaojie-kids-001-d",
        text: "我比較想先生一台車啦哈哈。",
        archetype: "backfire",
        retort: "……（表姊沒聽懂，禮貌地笑了笑）。",
      },
      {
        id: "biaojie-kids-001-e",
        text: "表姊你顧兩個小孩皮膚還這麼好？",
        archetype: "deflect",
        retort: "哎唷謝謝，我都擦習慣了（笑）。",
      },
      {
        id: "biaojie-kids-001-f",
        text: "陪我研究？你老公陪過你幾次？",
        archetype: "landmine",
        retort: "……好，我不會再多問了。",
      },
      {
        id: "biaojie-kids-001-g",
        text: "老公說再等兩年看看……",
        archetype: "meek",
        retort: "兩年很快，時間過了不會等你。",
      },
      {
        id: "biaojie-kids-001-h",
        text: "我先生一隻貓試試水溫。",
        archetype: "backfire",
        retort: "……貓跟小孩不太一樣喔（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-002",
    text: "抱著老二餵奶，順口問你何時要生。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-002-a",
        text: "老二喝奶喝得好乖，你調教有一套。",
        archetype: "deflect",
        retort: "哪有，他自己天生好帶啦（笑）。",
      },
      {
        id: "biaojie-kids-002-b",
        text: "我養活自己就已經很偉大了。",
        archetype: "backfire",
        retort: "……（表姊笑得有點僵，繼續餵奶）。",
      },
      {
        id: "biaojie-kids-002-c",
        text: "你邊餵奶邊八卦，練很久了喔？",
        archetype: "perfect",
        retort: "……哪有，我就順口問問（笑）。",
      },
      {
        id: "biaojie-kids-002-d",
        text: "我們還沒討論到這塊……",
        archetype: "meek",
        retort: "沒討論？那要找時間聊聊了。",
      },
      {
        id: "biaojie-kids-002-e",
        text: "顧小孩該不會全部丟給婆婆？",
        archetype: "landmine",
        retort: "……我自己顧的，謝謝關心。",
      },
      {
        id: "biaojie-kids-002-f",
        text: "表姊餵奶餵得好熟練，好厲害。",
        archetype: "deflect",
        retort: "習慣就好，你以後也會的（笑）。",
      },
      {
        id: "biaojie-kids-002-g",
        text: "可能要等工作穩定一點……",
        archetype: "meek",
        retort: "工作永遠不會有穩定的一天。",
      },
      {
        id: "biaojie-kids-002-h",
        text: "生小孩喔，那我要先中樂透。",
        archetype: "backfire",
        retort: "……樂透跟生小孩沒關係吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-003",
    text: "老大，快叫哥哥。你也該當爸爸了。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-003-a",
        text: "老大長得好像你，眼睛好靈。",
        archetype: "deflect",
        retort: "對啊大家都這樣說，像我小時候（笑）。",
      },
      {
        id: "biaojie-kids-003-b",
        text: "還沒有計畫啦，順其自然……",
        archetype: "meek",
        retort: "順其自然也要有點行動吧。",
      },
      {
        id: "biaojie-kids-003-c",
        text: "叫哥哥？那我先包紅包當開場。",
        archetype: "backfire",
        retort: "……現在不是包紅包的時候啦（笑）。",
      },
      {
        id: "biaojie-kids-003-d",
        text: "我先觀摩你老公怎麼當爸的。",
        archetype: "perfect",
        retort: "……他、他其實很忙的啦（笑）。",
      },
      {
        id: "biaojie-kids-003-e",
        text: "你老公顧小孩，一年出現幾次？",
        archetype: "landmine",
        retort: "……夠了，換個話題好嗎。",
      },
      {
        id: "biaojie-kids-003-f",
        text: "表姊你當媽媽氣質都變好了。",
        archetype: "deflect",
        retort: "是嗎？謝謝你，我還在適應中（笑）。",
      },
      {
        id: "biaojie-kids-003-g",
        text: "可能要看緣分吧，還沒想清楚……",
        archetype: "meek",
        retort: "緣分是自己創造的，你要努力。",
      },
      {
        id: "biaojie-kids-003-h",
        text: "當爸爸？我連貓都養不活。",
        archetype: "backfire",
        retort: "……貓跟小孩真的差很多喔。",
      },
    ],
  },
  {
    id: "biaojie-kids-004",
    text: "親子餐廳最方便，你們以後就懂了。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-004-a",
        text: "懂了以後，換我教你訂位技巧。",
        archetype: "perfect",
        retort: "……是喔，那你也太厲害了（笑）。",
      },
      {
        id: "biaojie-kids-004-b",
        text: "老二會自己拿湯匙了？好厲害。",
        archetype: "deflect",
        retort: "會啊，灑得滿地都是可愛就好（笑）。",
      },
      {
        id: "biaojie-kids-004-c",
        text: "我們現在還沒有那個需求啦……",
        archetype: "meek",
        retort: "沒需求也可以先做功課呀。",
      },
      {
        id: "biaojie-kids-004-d",
        text: "親子餐廳喔，那我先去練吃兒童餐。",
        archetype: "backfire",
        retort: "……兒童餐是給小孩吃的喔（笑）。",
      },
      {
        id: "biaojie-kids-004-e",
        text: "表姊你選餐廳的品味一直很好。",
        archetype: "deflect",
        retort: "謝謝，都是為了小孩去踩點的（笑）。",
      },
      {
        id: "biaojie-kids-004-f",
        text: "你家小孩尖叫，別人也要忍？",
        archetype: "landmine",
        retort: "……好啦，我讓他們安靜點。",
      },
      {
        id: "biaojie-kids-004-g",
        text: "可能生了才會知道差別吧……",
        archetype: "meek",
        retort: "生了才知道，那時候會很累喔。",
      },
      {
        id: "biaojie-kids-004-h",
        text: "我以後帶我家的狗去就好了。",
        archetype: "backfire",
        retort: "……狗不能進親子餐廳耶（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-005",
    text: "群組看到了嗎？老二滿月好可愛。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-005-a",
        text: "滿月照拍得好美，攝影師是誰？",
        archetype: "deflect",
        retort: "朋友介紹的，改天分享給你（笑）。",
      },
      {
        id: "biaojie-kids-005-b",
        text: "有看到啦，一直沒回覆不好意思……",
        archetype: "meek",
        retort: "沒關係，你最近是不是很忙？",
      },
      {
        id: "biaojie-kids-005-c",
        text: "滿月照喔，我猜按讚數你都在算。",
        archetype: "perfect",
        retort: "……才沒有，我很少看啦（笑）。",
      },
      {
        id: "biaojie-kids-005-d",
        text: "我也想發我家的照片，可惜沒有。",
        archetype: "backfire",
        retort: "……那你要加油了（笑）。",
      },
      {
        id: "biaojie-kids-005-e",
        text: "老二眼睛好像表姊夫，好可愛。",
        archetype: "deflect",
        retort: "對啊大家都這樣說（笑）。",
      },
      {
        id: "biaojie-kids-005-f",
        text: "發照片是曬娃，還是曬你自己？",
        archetype: "landmine",
        retort: "……算了，當我沒發過。",
      },
      {
        id: "biaojie-kids-005-g",
        text: "我看照片會沒特別回，習慣潛水……",
        archetype: "meek",
        retort: "潛水沒關係，記得按讚就好。",
      },
      {
        id: "biaojie-kids-005-h",
        text: "滿月照喔，我還在滿轉職紀念日。",
        archetype: "backfire",
        retort: "……那個好像不太一樣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-006",
    text: "我住的月子中心一個月八萬，值得。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-006-a",
        text: "住那麼好，老公有沒有很寵你？",
        archetype: "deflect",
        retort: "有啦，他說要給我最好的（笑）。",
      },
      {
        id: "biaojie-kids-006-b",
        text: "我可能只能請媽媽來幫忙了……",
        archetype: "meek",
        retort: "有人幫也不錯，看情況安排。",
      },
      {
        id: "biaojie-kids-006-c",
        text: "八萬換一個月清靜，我先羨慕。",
        archetype: "perfect",
        retort: "……對啊，值得啦，你懂（笑）。",
      },
      {
        id: "biaojie-kids-006-d",
        text: "八萬喔，我在家自己坐月子就好。",
        archetype: "backfire",
        retort: "……在家真的辛苦很多喔（笑）。",
      },
      {
        id: "biaojie-kids-006-e",
        text: "月子中心的餐好吃嗎？想聽心得。",
        archetype: "deflect",
        retort: "超好吃，我還胖了三公斤呢（笑）。",
      },
      {
        id: "biaojie-kids-006-f",
        text: "八萬到底誰付的，你敢說嗎？",
        archetype: "landmine",
        retort: "……我們家的錢，沒差好嗎。",
      },
      {
        id: "biaojie-kids-006-g",
        text: "八萬對我們來說壓力有點大……",
        archetype: "meek",
        retort: "壓力大也要為自己投資一下。",
      },
      {
        id: "biaojie-kids-006-h",
        text: "月子中心，我還以為是月租套房。",
        archetype: "backfire",
        retort: "……不是喔，是專門坐月子的（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-007",
    text: "保母費一個月三萬，你們付得起嗎？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-007-a",
        text: "你選保母的眼光一定很準吧？",
        archetype: "deflect",
        retort: "還好啦，多面試幾個就知道（笑）。",
      },
      {
        id: "biaojie-kids-007-b",
        text: "老實說我還沒認真算過這筆錢……",
        archetype: "meek",
        retort: "要早點算，不然會措手不及。",
      },
      {
        id: "biaojie-kids-007-c",
        text: "付得起，先問你付的是誰的錢？",
        archetype: "perfect",
        retort: "……我們家共同的，你很敢問（笑）。",
      },
      {
        id: "biaojie-kids-007-d",
        text: "三萬喔，那我先去考保母證照賺。",
        archetype: "backfire",
        retort: "……你沒小孩，帶誰啊（笑）。",
      },
      {
        id: "biaojie-kids-007-e",
        text: "老二給保母帶，會不會捨不得？",
        archetype: "deflect",
        retort: "會啊，每天都很掙扎（笑）。",
      },
      {
        id: "biaojie-kids-007-f",
        text: "你確定不是婆婆免費在顧？",
        archetype: "landmine",
        retort: "……不是，我們有付她錢。",
      },
      {
        id: "biaojie-kids-007-g",
        text: "可能到時候只能自己請假顧了……",
        archetype: "meek",
        retort: "自己顧很辛苦，要有心理準備。",
      },
      {
        id: "biaojie-kids-007-h",
        text: "保母費喔，我以為是保姆茶喔。",
        archetype: "backfire",
        retort: "……保母不是奶茶店啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-008",
    text: "老大讀雙語幼兒園，一學期十萬。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-008-a",
        text: "老大現在英文說得怎麼樣了？",
        archetype: "deflect",
        retort: "簡單對話沒問題，超可愛的（笑）。",
      },
      {
        id: "biaojie-kids-008-b",
        text: "我們可能負擔不起這種學費……",
        archetype: "meek",
        retort: "負擔不起也要想想別的辦法。",
      },
      {
        id: "biaojie-kids-008-c",
        text: "沒人問學費，你倒先報得真勤。",
        archetype: "perfect",
        retort: "……我、我只是分享而已（笑）。",
      },
      {
        id: "biaojie-kids-008-d",
        text: "十萬喔，那我教他英文比較省。",
        archetype: "backfire",
        retort: "……你英文很好嗎（笑）。",
      },
      {
        id: "biaojie-kids-008-e",
        text: "表姊你真的很捨得栽培小孩。",
        archetype: "deflect",
        retort: "當媽媽的都這樣啦，值得的（笑）。",
      },
      {
        id: "biaojie-kids-008-f",
        text: "花十萬炫耀，還是真心為老大？",
        archetype: "landmine",
        retort: "……當然是為他，別亂講。",
      },
      {
        id: "biaojie-kids-008-g",
        text: "普通幼兒園應該也夠用吧……",
        archetype: "meek",
        retort: "夠不夠用，起跑點差很多喔。",
      },
      {
        id: "biaojie-kids-008-h",
        text: "雙語喔，那我家教台語跟國語。",
        archetype: "backfire",
        retort: "……那個不算雙語吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-009",
    text: "老大在學鋼琴，天分好像我這邊。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-009-a",
        text: "老大彈鋼琴的樣子一定很療癒。",
        archetype: "deflect",
        retort: "超療癒，改天錄給你看（笑）。",
      },
      {
        id: "biaojie-kids-009-b",
        text: "我小時候學才藝都半途而廢……",
        archetype: "meek",
        retort: "半途而廢很可惜，小孩要堅持。",
      },
      {
        id: "biaojie-kids-009-c",
        text: "天分像你，那壓力也算你的吧？",
        archetype: "perfect",
        retort: "……這、這樣說也對啦（笑）。",
      },
      {
        id: "biaojie-kids-009-d",
        text: "鋼琴喔，我小時候學過直笛。",
        archetype: "backfire",
        retort: "……直笛跟鋼琴不太一樣喔（笑）。",
      },
      {
        id: "biaojie-kids-009-e",
        text: "表姊你以前也很有才藝吧？",
        archetype: "deflect",
        retort: "還好啦，都是媽媽逼出來的（笑）。",
      },
      {
        id: "biaojie-kids-009-f",
        text: "才藝班是你的夢，別牽拖老大。",
        archetype: "landmine",
        retort: "……是他自己想學的。",
      },
      {
        id: "biaojie-kids-009-g",
        text: "我們家目前還沒有安排才藝……",
        archetype: "meek",
        retort: "要趁早安排，長大就沒興趣了。",
      },
      {
        id: "biaojie-kids-009-h",
        text: "天分遺傳，那我也要去彈彈看。",
        archetype: "backfire",
        retort: "……你現在才學有點晚了（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-010",
    text: "老二的英文名字，你要不要幫忙取？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-010-a",
        text: "表姊取名的品味一直都很好。",
        archetype: "deflect",
        retort: "謝謝，我查了好久資料呢（笑）。",
      },
      {
        id: "biaojie-kids-010-b",
        text: "我對取名真的沒什麼靈感……",
        archetype: "meek",
        retort: "沒靈感也可以查查資料庫。",
      },
      {
        id: "biaojie-kids-010-c",
        text: "取名找我？你們家意見很少喔？",
        archetype: "perfect",
        retort: "……沒有啦，隨口問問而已（笑）。",
      },
      {
        id: "biaojie-kids-010-d",
        text: "取名喔，那就叫他二號好了。",
        archetype: "backfire",
        retort: "……那個不太像名字耶（笑）。",
      },
      {
        id: "biaojie-kids-010-e",
        text: "老大的英文名字是誰取的？",
        archetype: "deflect",
        retort: "我跟老公一起討論的（笑）。",
      },
      {
        id: "biaojie-kids-010-f",
        text: "連取名都要公婆點頭才算？",
        archetype: "landmine",
        retort: "……沒有，我們自己決定的。",
      },
      {
        id: "biaojie-kids-010-g",
        text: "我怕取的名字不好聽……",
        archetype: "meek",
        retort: "怕的話就多問問其他人意見。",
      },
      {
        id: "biaojie-kids-010-h",
        text: "英文名字，我建議叫Money。",
        archetype: "backfire",
        retort: "……這個名字有點奇怪（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-011",
    text: "婆婆幫忙顧兩個，你以後有人幫嗎？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-011-a",
        text: "婆婆幫忙顧小孩，你很幸福耶。",
        archetype: "deflect",
        retort: "對啊，我真的很感謝她（笑）。",
      },
      {
        id: "biaojie-kids-011-b",
        text: "應該只能靠自己了，家人比較遠……",
        archetype: "meek",
        retort: "那真的會辛苦，要提早規劃。",
      },
      {
        id: "biaojie-kids-011-c",
        text: "沒人幫，至少沒人來插手教法。",
        archetype: "perfect",
        retort: "……你這樣說也是啦（笑）。",
      },
      {
        id: "biaojie-kids-011-d",
        text: "沒人幫喔，那我請機器人保母。",
        archetype: "backfire",
        retort: "……那個還沒有真的做出來（笑）。",
      },
      {
        id: "biaojie-kids-011-e",
        text: "表姊你跟婆婆感情一定很好。",
        archetype: "deflect",
        retort: "還算不錯啦，互相體諒（笑）。",
      },
      {
        id: "biaojie-kids-011-f",
        text: "婆婆幫顧？該不會順便管教？",
        archetype: "landmine",
        retort: "……她只是幫忙，沒有插手。",
      },
      {
        id: "biaojie-kids-011-g",
        text: "老公家人也沒住附近，幫不上……",
        archetype: "meek",
        retort: "沒人幫真的很累，要考慮清楚。",
      },
      {
        id: "biaojie-kids-011-h",
        text: "沒關係，我自己也是被野放大的。",
        archetype: "backfire",
        retort: "……野放長大聽起來不太好聽（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-012",
    text: "我們在考慮生老三了，你一個都沒。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-012-a",
        text: "老三喔，你的體力也太好了吧。",
        archetype: "deflect",
        retort: "哪有，都是靠意志力撐的（笑）。",
      },
      {
        id: "biaojie-kids-012-b",
        text: "我們連第一個都還沒開始想……",
        archetype: "meek",
        retort: "還沒想的話，時間要抓緊了。",
      },
      {
        id: "biaojie-kids-012-c",
        text: "老三很好，順便問問誰在顧。",
        archetype: "perfect",
        retort: "……應該還是婆婆幫忙吧（笑）。",
      },
      {
        id: "biaojie-kids-012-d",
        text: "老三喔，那你們家快變球隊了。",
        archetype: "backfire",
        retort: "……球隊人數好像不太夠（笑）。",
      },
      {
        id: "biaojie-kids-012-e",
        text: "表姊你想得真長遠，好羨慕。",
        archetype: "deflect",
        retort: "還在考慮啦，看緣分（笑）。",
      },
      {
        id: "biaojie-kids-012-f",
        text: "沒人問老三，你倒急著先報。",
        archetype: "landmine",
        retort: "……好，那我不講了。",
      },
      {
        id: "biaojie-kids-012-g",
        text: "光養一個就覺得很吃力了……",
        archetype: "meek",
        retort: "吃力歸吃力，習慣就好了。",
      },
      {
        id: "biaojie-kids-012-h",
        text: "生老三，那你要不要順便算命。",
        archetype: "backfire",
        retort: "……算命跟生小孩沒關係吧（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-013",
    text: "老大都吃青菜，不像有些小孩挑食。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-013-a",
        text: "老大不挑食，你怎麼訓練的？",
        archetype: "deflect",
        retort: "慢慢引導啦，其實有撇步（笑）。",
      },
      {
        id: "biaojie-kids-013-b",
        text: "我小時候也很挑食，改不掉……",
        archetype: "meek",
        retort: "改不掉的話，以後小孩也會學。",
      },
      {
        id: "biaojie-kids-013-c",
        text: "不像有些小孩？你在酸誰家的？",
        archetype: "perfect",
        retort: "……沒有針對誰啦，別多想（笑）。",
      },
      {
        id: "biaojie-kids-013-d",
        text: "青菜喔，那我以後餵水果就好。",
        archetype: "backfire",
        retort: "……只吃水果會營養不均衡喔（笑）。",
      },
      {
        id: "biaojie-kids-013-e",
        text: "表姊你自己也很愛吃健康的吧？",
        archetype: "deflect",
        retort: "對啊，全家一起吃比較均衡（笑）。",
      },
      {
        id: "biaojie-kids-013-f",
        text: "拿老大酸別人小孩，很行喔？",
        archetype: "landmine",
        retort: "……我沒那個意思，別誤會。",
      },
      {
        id: "biaojie-kids-013-g",
        text: "我對食物真的沒什麼堅持……",
        archetype: "meek",
        retort: "沒堅持的話，小孩會更難教。",
      },
      {
        id: "biaojie-kids-013-h",
        text: "不挑食好棒，我連自己都挑食。",
        archetype: "backfire",
        retort: "……那你要先改掉自己的習慣（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-014",
    text: "我們家不給小孩看手機，你們呢？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-014-a",
        text: "你堅持不給看，一定很有耐心。",
        archetype: "deflect",
        retort: "還好啦，習慣了就好（笑）。",
      },
      {
        id: "biaojie-kids-014-b",
        text: "我們可能沒辦法完全不給看……",
        archetype: "meek",
        retort: "還是要盡量控制時間比較好。",
      },
      {
        id: "biaojie-kids-014-c",
        text: "不給看手機，那誰陪他玩？",
        archetype: "perfect",
        retort: "……當然是我陪，怎麼樣（笑）。",
      },
      {
        id: "biaojie-kids-014-d",
        text: "不給看手機，那我送他看報紙。",
        archetype: "backfire",
        retort: "……報紙他應該看不懂啦（笑）。",
      },
      {
        id: "biaojie-kids-014-e",
        text: "表姊你的育兒方式真的很用心。",
        archetype: "deflect",
        retort: "謝謝你，都是邊做邊學的（笑）。",
      },
      {
        id: "biaojie-kids-014-f",
        text: "你滑手機時數，敢跟我比？",
        archetype: "landmine",
        retort: "……我很少滑，別亂猜。",
      },
      {
        id: "biaojie-kids-014-g",
        text: "有時候忙起來就會讓他看一下……",
        archetype: "meek",
        retort: "偶爾沒關係，但別養成習慣。",
      },
      {
        id: "biaojie-kids-014-h",
        text: "3C不好，那我教他用算盤。",
        archetype: "backfire",
        retort: "……算盤現在比較少見了（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-015",
    text: "過年紅包，老大老二你打算包多少？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-015-a",
        text: "老大老二今年應該很期待紅包。",
        archetype: "deflect",
        retort: "對啊，天天問我什麼時候拿（笑）。",
      },
      {
        id: "biaojie-kids-015-b",
        text: "我還沒想好要包多少……",
        archetype: "meek",
        retort: "早點想好，不然到時候尷尬。",
      },
      {
        id: "biaojie-kids-015-c",
        text: "包多少不重要，你很在意喔？",
        archetype: "perfect",
        retort: "……是喔，那算我多嘴了（笑）。",
      },
      {
        id: "biaojie-kids-015-d",
        text: "紅包喔，那我包一張悠遊卡。",
        archetype: "backfire",
        retort: "……悠遊卡不算紅包耶（笑）。",
      },
      {
        id: "biaojie-kids-015-e",
        text: "表姊你每年紅包都包得好用心。",
        archetype: "deflect",
        retort: "謝謝，看在他們可愛的份上（笑）。",
      },
      {
        id: "biaojie-kids-015-f",
        text: "紅包看人給，是你們家家規？",
        archetype: "landmine",
        retort: "……沒有，我們一向都公平。",
      },
      {
        id: "biaojie-kids-015-g",
        text: "包太少怕失禮，包太多又吃緊……",
        archetype: "meek",
        retort: "量力而為就好，別想太多。",
      },
      {
        id: "biaojie-kids-015-h",
        text: "我打算包貼紙代替現金。",
        archetype: "backfire",
        retort: "……小孩應該比較想要現金（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-016",
    text: "拍全家福，你們要不要一起加入？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-016-a",
        text: "你們全家福構圖都拍得好好看。",
        archetype: "deflect",
        retort: "謝謝，我們找的攝影師不錯（笑）。",
      },
      {
        id: "biaojie-kids-016-b",
        text: "我現在自己拍就好，不太好意思……",
        archetype: "meek",
        retort: "沒關係啦，一起拍才熱鬧。",
      },
      {
        id: "biaojie-kids-016-c",
        text: "加入喔，那你老公這次會到？",
        archetype: "perfect",
        retort: "……他這次應該會來啦（笑）。",
      },
      {
        id: "biaojie-kids-016-d",
        text: "全家福喔，那我帶我家的貓入鏡。",
        archetype: "backfire",
        retort: "……貓應該不算家人成員吧（笑）。",
      },
      {
        id: "biaojie-kids-016-e",
        text: "表姊你當媽媽以後笑容變更甜。",
        archetype: "deflect",
        retort: "是嗎？謝謝你注意到（笑）。",
      },
      {
        id: "biaojie-kids-016-f",
        text: "全家福，你站C位很習慣喔？",
        archetype: "landmine",
        retort: "……大家一起拍，別這樣說。",
      },
      {
        id: "biaojie-kids-016-g",
        text: "我怕站進去畫面會不協調……",
        archetype: "meek",
        retort: "不會啦，家人一起拍最重要。",
      },
      {
        id: "biaojie-kids-016-h",
        text: "我自己拍證件照湊數就好。",
        archetype: "backfire",
        retort: "……證件照跟全家福不一樣啦（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-017",
    text: "我老公陪產全程握著我的手，好感動。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-017-a",
        text: "表姊夫真的是神隊友耶，好羨慕。",
        archetype: "deflect",
        retort: "對啊，他真的很用心（笑）。",
      },
      {
        id: "biaojie-kids-017-b",
        text: "我還不太敢想生產這件事……",
        archetype: "meek",
        retort: "會怕很正常，多做功課會好一點。",
      },
      {
        id: "biaojie-kids-017-c",
        text: "握手陪產，手機有放下嗎？",
        archetype: "perfect",
        retort: "……才沒有，他真的有陪（笑）。",
      },
      {
        id: "biaojie-kids-017-d",
        text: "握著手，那我陪看牙醫也算吧。",
        archetype: "backfire",
        retort: "……那個好像沒有這麼偉大（笑）。",
      },
      {
        id: "biaojie-kids-017-e",
        text: "生產的過程你一定很勇敢吧。",
        archetype: "deflect",
        retort: "還好啦，硬著頭皮撐過去的（笑）。",
      },
      {
        id: "biaojie-kids-017-f",
        text: "陪產照片呢？怎麼一張都沒？",
        archetype: "landmine",
        retort: "……手機忘記拿，別亂猜。",
      },
      {
        id: "biaojie-kids-017-g",
        text: "我對這種畫面還沒有心理準備……",
        archetype: "meek",
        retort: "沒關係，時候到了自然就懂。",
      },
      {
        id: "biaojie-kids-017-h",
        text: "神隊友，那我養電子雞練習。",
        archetype: "backfire",
        retort: "……電子雞跟生小孩差很多喔（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-018",
    text: "我親餵母乳到一歲，你要不要試試？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-018-a",
        text: "親餵一年真的很不容易，佩服你。",
        archetype: "deflect",
        retort: "謝謝，過程很值得啦（笑）。",
      },
      {
        id: "biaojie-kids-018-b",
        text: "我對這方面完全沒概念……",
        archetype: "meek",
        retort: "沒概念沒關係，可以先了解。",
      },
      {
        id: "biaojie-kids-018-c",
        text: "親餵一年，你的時間都給誰了？",
        archetype: "perfect",
        retort: "……都給小孩啊，值得的（笑）。",
      },
      {
        id: "biaojie-kids-018-d",
        text: "母乳喔，那我先囤一箱保久乳。",
        archetype: "backfire",
        retort: "……保久乳跟母乳不一樣喔（笑）。",
      },
      {
        id: "biaojie-kids-018-e",
        text: "表姊你這麼堅持，意志力超強。",
        archetype: "deflect",
        retort: "還好啦，都是為了小孩（笑）。",
      },
      {
        id: "biaojie-kids-018-f",
        text: "親餵一年，是餵他還是餵人設？",
        archetype: "landmine",
        retort: "……我是真心想給他最好的。",
      },
      {
        id: "biaojie-kids-018-g",
        text: "聽說很辛苦，我有點擔心……",
        archetype: "meek",
        retort: "確實辛苦，但撐過去就好了。",
      },
      {
        id: "biaojie-kids-018-h",
        text: "一歲，那我養成分期付款好了。",
        archetype: "backfire",
        retort: "……這個比喻我聽不太懂（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-019",
    text: "坐月子不能出門吹風，你要注意喔。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-019-a",
        text: "你坐月子那一個月一定很辛苦。",
        archetype: "deflect",
        retort: "還好，家人都很照顧我（笑）。",
      },
      {
        id: "biaojie-kids-019-b",
        text: "這些習俗我完全不熟……",
        archetype: "meek",
        retort: "不熟沒關係，到時候我教你。",
      },
      {
        id: "biaojie-kids-019-c",
        text: "規矩這麼多，你老公陪你守？",
        archetype: "perfect",
        retort: "……他也有跟著注意啦（笑）。",
      },
      {
        id: "biaojie-kids-019-d",
        text: "不能吹風，那我先練習憋氣。",
        archetype: "backfire",
        retort: "……憋氣好像沒有幫助耶（笑）。",
      },
      {
        id: "biaojie-kids-019-e",
        text: "表姊你懂的習俗真的好多喔。",
        archetype: "deflect",
        retort: "都是長輩教的，實用啦（笑）。",
      },
      {
        id: "biaojie-kids-019-f",
        text: "月子規矩多，是婆婆在管你？",
        archetype: "landmine",
        retort: "……不是，是我自己想遵守。",
      },
      {
        id: "biaojie-kids-019-g",
        text: "感覺規矩很多，會有點緊張……",
        archetype: "meek",
        retort: "會緊張正常，習慣就好了。",
      },
      {
        id: "biaojie-kids-019-h",
        text: "月子習俗，那跟坐牢有點像。",
        archetype: "backfire",
        retort: "……不太一樣啦，是為了身體好（笑）。",
      },
    ],
  },
  {
    id: "biaojie-kids-020",
    text: "兩個小孩在吵，習慣就好，你們也會。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-020-a",
        text: "他們吵鬧的樣子也好可愛喔。",
        archetype: "deflect",
        retort: "吵歸吵，看久了會捨不得（笑）。",
      },
      {
        id: "biaojie-kids-020-b",
        text: "光聽就覺得有點累了……",
        archetype: "meek",
        retort: "累是真的，但也很值得。",
      },
      {
        id: "biaojie-kids-020-c",
        text: "習慣就好？隔壁桌可不習慣。",
        archetype: "perfect",
        retort: "……小孩子難免會這樣啦（笑）。",
      },
      {
        id: "biaojie-kids-020-d",
        text: "吵鬧喔，那我先去買耳塞。",
        archetype: "backfire",
        retort: "……耳塞好像不太禮貌耶（笑）。",
      },
      {
        id: "biaojie-kids-020-e",
        text: "表姊你顧兩個還這麼有耐心。",
        archetype: "deflect",
        retort: "習慣了啦，你以後也會的（笑）。",
      },
      {
        id: "biaojie-kids-020-f",
        text: "吵成這樣，別人是該忍嗎？",
        archetype: "landmine",
        retort: "……好，我帶他們先離開。",
      },
      {
        id: "biaojie-kids-020-g",
        text: "我大概沒辦法應付這種場面……",
        archetype: "meek",
        retort: "沒辦法應付？那要多練習了。",
      },
      {
        id: "biaojie-kids-020-h",
        text: "習慣就好，那我先習慣裝沒聽到。",
        archetype: "backfire",
        retort: "……裝沒聽到解決不了問題啦（笑）。",
      },
    ],
  },
] satisfies Question[];
