// situations: 老大畫畫得獎、帶兩個出國旅遊經驗、後座裝安全座椅、家族聚餐訂位小孩椅、
// 玩具收納整齊、老大游泳比賽得獎、老大在學校當班長、婆婆接送 vs 你以後靠誰、
// 教育基金規劃、老二學會叫人只叫表姊、滑步車品牌比較、滿月禮送禮比較、
// 走春拜拜求平安符、老大背唐詩表演、尿布濕紙巾囤貨、老大生日流水席排場、班親會
import type { Question } from "@/content/types";

export default [
  {
    id: "biaojie-kids-021",
    text: "老大畫畫得獎了，你有什麼作品嗎？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-021-a",
        text: "老大的畫是不是很有創意，笑死？",
        archetype: "deflect",
        retort: "對啊，色彩用得亂中有序（笑）。",
      },
      {
        id: "biaojie-kids-021-b",
        text: "幹……我最近沒什麼拿得出手的成績……",
        archetype: "meek",
        retort: "沒關係，慢慢累積就好。",
      },
      {
        id: "biaojie-kids-021-c",
        text: "我他媽的代表作，是沒人問也活得好。",
        archetype: "perfect",
        retort: "……幹，你這孩子嘴巴很壞（笑容僵）。",
      },
      {
        id: "biaojie-kids-021-d",
        text: "作品喔，我他媽的朋友圈的迷因算嗎。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-kids-021-e",
        text: "表姊你培養小孩真的很用心。",
        archetype: "deflect",
        retort: "謝謝，看他開心我就開心（笑）。",
      },
      {
        id: "biaojie-kids-021-f",
        text: "沒人問，妳他媽的很愛現齁，歐巴桑。",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
      {
        id: "biaojie-kids-021-g",
        text: "比起小孩，我好像退步了……",
        archetype: "meek",
        retort: "退步的話要找回動力才行。",
      },
      {
        id: "biaojie-kids-021-h",
        text: "我他媽的代表作是準時上下班。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-kids-022",
    text: "帶兩個出國玩，你們什麼時候敢試？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-022-a",
        text: "帶兩個出國，行李一定很浩大，笑死。",
        archetype: "deflect",
        retort: "對啊，光行李箱就佔一台車（笑）。",
      },
      {
        id: "biaojie-kids-022-b",
        text: "幹……我連自己出國都覺得麻煩了……",
        archetype: "meek",
        retort: "麻煩歸麻煩，多練習就上手。",
      },
      {
        id: "biaojie-kids-022-c",
        text: "等我他媽的先適應妳的凡爾賽。",
        archetype: "perfect",
        retort: "……他媽的，沒大沒小（臉一沉）。",
      },
      {
        id: "biaojie-kids-022-d",
        text: "出國喔，我他媽的建議帶去夜市就好。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-kids-022-e",
        text: "表姊你安排行程一定很厲害。",
        archetype: "deflect",
        retort: "還好啦，都是經驗累積的（笑）。",
      },
      {
        id: "biaojie-kids-022-f",
        text: "妳老公呢？他媽的該不會又沒空？",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
      {
        id: "biaojie-kids-022-g",
        text: "帶小孩感覺會很崩潰，不敢想……",
        archetype: "meek",
        retort: "會崩潰是真的，要有心理準備。",
      },
      {
        id: "biaojie-kids-022-h",
        text: "帶小孩出國，他媽的聽起來像特訓營。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-kids-023",
    text: "後座裝了兩張安全座椅，超專業。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-023-a",
        text: "選安全座椅一定做了很多功課，笑死。",
        archetype: "deflect",
        retort: "對啊，比較了好幾個牌子（笑）。",
      },
      {
        id: "biaojie-kids-023-b",
        text: "幹……我對安全座椅完全沒研究過……",
        archetype: "meek",
        retort: "沒研究的話，到時候要惡補。",
      },
      {
        id: "biaojie-kids-023-c",
        text: "秀座椅，妳他媽的是想讓我誇幾句？",
        archetype: "perfect",
        retort: "（笑容不見）……去你的，很敢講。",
      },
      {
        id: "biaojie-kids-023-d",
        text: "安全座椅喔，那我他媽的先買安全帽。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-kids-023-e",
        text: "表姊你連車上都佈置得好用心。",
        archetype: "deflect",
        retort: "為了小孩安全，值得的（笑）。",
      },
      {
        id: "biaojie-kids-023-f",
        text: "後座兩張，妳他媽的老公去哪了，歐巴桑？",
        archetype: "landmine",
        retort: "幹！你才是欠罵的那個！",
      },
      {
        id: "biaojie-kids-023-g",
        text: "我們家的車座位好像也不夠大……",
        archetype: "meek",
        retort: "座位不夠大，要提早規劃換車。",
      },
      {
        id: "biaojie-kids-023-h",
        text: "後座兩張，前座他媽的留給我坐嗎。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-kids-024",
    text: "訂位要記得說有兩個小孩椅，麻煩了。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-024-a",
        text: "帶兩個孩子出來吃飯真不簡單，笑死。",
        archetype: "deflect",
        retort: "對啊，出門像打仗一樣（笑）。",
      },
      {
        id: "biaojie-kids-024-b",
        text: "幹……我訂位常常忘記考慮這些細節……",
        archetype: "meek",
        retort: "下次記得多想一下比較好。",
      },
      {
        id: "biaojie-kids-024-c",
        text: "兩個孩子椅，妳他媽的何不乾脆包場？",
        archetype: "perfect",
        retort: "……（氣到講台語）幹恁娘咧。",
      },
      {
        id: "biaojie-kids-024-d",
        text: "小孩椅喔，那我他媽的坐兒童椅陪他們。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-kids-024-e",
        text: "表姊你安排聚餐都很細心耶。",
        archetype: "deflect",
        retort: "習慣了，家庭主婦的日常（笑）。",
      },
      {
        id: "biaojie-kids-024-f",
        text: "妳小孩他媽的吵，別人憑什麼忍？",
        archetype: "landmine",
        retort: "（臉色鐵青）明年不用他媽的來了。",
      },
      {
        id: "biaojie-kids-024-g",
        text: "我對這種安排真的不太熟……",
        archetype: "meek",
        retort: "不熟沒關係，多幫忙幾次就會了。",
      },
      {
        id: "biaojie-kids-024-h",
        text: "麻煩喔，那我他媽的約速食店就好。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-kids-025",
    text: "老大的玩具都分類收好，你看多整齊。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-025-a",
        text: "教小孩收納，妳一定很有方法，笑死。",
        archetype: "deflect",
        retort: "還好啦，慢慢訓練出來的（笑）。",
      },
      {
        id: "biaojie-kids-025-b",
        text: "幹……我自己房間都收不好了……",
        archetype: "meek",
        retort: "自己都收不好，怎麼教小孩？",
      },
      {
        id: "biaojie-kids-025-c",
        text: "整齊是妳家，機掰，亂是我家常態。",
        archetype: "perfect",
        retort: "……你很過分耶，幹（別過臉）。",
      },
      {
        id: "biaojie-kids-025-d",
        text: "分類喔，那我他媽的把衣服分乾淨跟不乾淨。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-kids-025-e",
        text: "表姊你們家整體都好有質感。",
        archetype: "deflect",
        retort: "謝謝誇獎，都是花時間弄的（笑）。",
      },
      {
        id: "biaojie-kids-025-f",
        text: "曬玩具而已，妳他媽的很缺讚喔，老女人？",
        archetype: "landmine",
        retort: "你他媽的閉嘴，別再說了！",
      },
      {
        id: "biaojie-kids-025-g",
        text: "我們家空間比較小，堆不下……",
        archetype: "meek",
        retort: "空間小更要學會收納技巧。",
      },
      {
        id: "biaojie-kids-025-h",
        text: "玩具整齊，我他媽的書桌也整齊，都是灰塵。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-kids-026",
    text: "老大游泳比賽得了獎牌，超驕傲的。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-026-a",
        text: "得獎前一定練習了很久吧，笑死？",
        archetype: "deflect",
        retort: "對啊，天天陪他練，很值得（笑）。",
      },
      {
        id: "biaojie-kids-026-b",
        text: "幹……我小時候比賽都拿不到名次……",
        archetype: "meek",
        retort: "拿不到名次也是一種經驗啦。",
      },
      {
        id: "biaojie-kids-026-c",
        text: "獎狀那麼多，機掰，牆要不夠貼了。",
        archetype: "perfect",
        retort: "……機掰，你這張嘴誰教的？",
      },
      {
        id: "biaojie-kids-026-d",
        text: "得獎喔，我他媽的以前得過全勤獎。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-kids-026-e",
        text: "表姊你陪練的耐心真的很強。",
        archetype: "deflect",
        retort: "習慣了，媽媽都是這樣過來的（笑）。",
      },
      {
        id: "biaojie-kids-026-f",
        text: "得獎而已，他媽的全世界要知道？",
        archetype: "landmine",
        retort: "機掰，你這什麼態度！",
      },
      {
        id: "biaojie-kids-026-g",
        text: "我對比賽這種事一直很害怕……",
        archetype: "meek",
        retort: "害怕的話，多練習會比較有信心。",
      },
      {
        id: "biaojie-kids-026-h",
        text: "游泳比賽，那我他媽的拿手遊排名第一。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-kids-027",
    text: "老大在學校當班長了，天生領導者。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-027-a",
        text: "當班長一定很有責任感吧，笑死。",
        archetype: "deflect",
        retort: "對啊，回家還會管弟弟呢（笑）。",
      },
      {
        id: "biaojie-kids-027-b",
        text: "幹……我以前上學都很邊緣，沒當過幹部……",
        archetype: "meek",
        retort: "邊緣沒關係，長大也是能發展的。",
      },
      {
        id: "biaojie-kids-027-c",
        text: "班長而已，他媽的以後選總統再說。",
        archetype: "perfect",
        retort: "（尷尬）……你他媽的很敢說喔。",
      },
      {
        id: "biaojie-kids-027-d",
        text: "班長喔，那我他媽的以前是躲避球隊長。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-kids-027-e",
        text: "表姊你的教育方式一定很成功。",
        archetype: "deflect",
        retort: "還好啦，主要是他自己爭氣（笑）。",
      },
      {
        id: "biaojie-kids-027-f",
        text: "班長爾爾，妳他媽的很大聲欸，歐巴桑。",
        archetype: "landmine",
        retort: "（拍桌）去你的，太過分了！",
      },
      {
        id: "biaojie-kids-027-g",
        text: "我對這種競選的事一直很不擅長……",
        archetype: "meek",
        retort: "不擅長的話，以後小孩要多練習。",
      },
      {
        id: "biaojie-kids-027-h",
        text: "領導者，那我他媽的在家管我家的貓。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-kids-028",
    text: "婆婆每天接送老大，你們以後靠誰？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-028-a",
        text: "婆婆這麼幫忙，妳一定很輕鬆吧，笑死。",
        archetype: "deflect",
        retort: "輕鬆很多，我真的很感謝她（笑）。",
      },
      {
        id: "biaojie-kids-028-b",
        text: "幹……我們可能只能靠安親班了……",
        archetype: "meek",
        retort: "安親班也是個辦法，早點找。",
      },
      {
        id: "biaojie-kids-028-c",
        text: "婆婆顧這麼多，妳他媽的負責說感謝？",
        archetype: "perfect",
        retort: "……靠北，講話這麼難聽。",
      },
      {
        id: "biaojie-kids-028-d",
        text: "接送喔，那我他媽的讓他自己走路上學。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-kids-028-e",
        text: "表姊你家人感情真的好融洽。",
        archetype: "deflect",
        retort: "對啊，大家都很互相幫忙（笑）。",
      },
      {
        id: "biaojie-kids-028-f",
        text: "婆婆顧這麼多，妳他媽的顧幾天？",
        archetype: "landmine",
        retort: "幹你娘咧，你很沒大沒小！",
      },
      {
        id: "biaojie-kids-028-g",
        text: "老公家人比較遠，幫不上什麼忙……",
        archetype: "meek",
        retort: "幫不上忙的話，真的會很辛苦。",
      },
      {
        id: "biaojie-kids-028-h",
        text: "靠誰，那我他媽的養一隻導盲犬接送。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-kids-029",
    text: "你們有幫小孩存教育基金了嗎？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-029-a",
        text: "你們規劃教育基金一定花很多心思，笑死。",
        archetype: "deflect",
        retort: "對啊，跟老公研究了好久（笑）。",
      },
      {
        id: "biaojie-kids-029-b",
        text: "幹……我們連自己的存款都不太夠……",
        archetype: "meek",
        retort: "自己不夠更要提早規劃才行。",
      },
      {
        id: "biaojie-kids-029-c",
        text: "存教育基金，他媽的先教他別愛現。",
        archetype: "perfect",
        retort: "（收起笑）……去死啦你，很欠揍。",
      },
      {
        id: "biaojie-kids-029-d",
        text: "教育基金喔，那我他媽的幫他存零錢筒。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-kids-029-e",
        text: "表姊你理財觀念真的很成熟。",
        archetype: "deflect",
        retort: "還好啦，都是為了小孩打算（笑）。",
      },
      {
        id: "biaojie-kids-029-f",
        text: "存這麼多，是他媽的講給誰聽的，老女人？",
        archetype: "landmine",
        retort: "（大聲）你他媽的講夠了沒！",
      },
      {
        id: "biaojie-kids-029-g",
        text: "教育基金這塊我們還沒想到……",
        archetype: "meek",
        retort: "沒想到的話，現在開始也不晚。",
      },
      {
        id: "biaojie-kids-029-h",
        text: "基金喔，那我他媽的推薦他玩股票遊戲。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-kids-030",
    text: "老二會叫人了，第一個就叫我表姊。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-030-a",
        text: "他發音好清楚，教得真好，笑死。",
        archetype: "deflect",
        retort: "對啊，練了好幾個禮拜呢（笑）。",
      },
      {
        id: "biaojie-kids-030-b",
        text: "幹……我完全不知道小孩學說話的過程……",
        archetype: "meek",
        retort: "不知道也沒關係，以後就懂了。",
      },
      {
        id: "biaojie-kids-030-c",
        text: "他先聞到錢，機掰，才叫的表姊吧？",
        archetype: "perfect",
        retort: "……幹，你到底是誰教的？",
      },
      {
        id: "biaojie-kids-030-d",
        text: "叫表姊喔，那我他媽的教他叫我老闆。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-kids-030-e",
        text: "表姊你一定樂歪了吧，好幸福。",
        archetype: "deflect",
        retort: "對啊，我錄影錄了十幾次（笑）。",
      },
      {
        id: "biaojie-kids-030-f",
        text: "教半天，他媽的就為了聽這句？",
        archetype: "landmine",
        retort: "去死，誰要聽你講這個！",
      },
      {
        id: "biaojie-kids-030-g",
        text: "我對這種發展階段真的很陌生……",
        archetype: "meek",
        retort: "陌生沒關係，多帶小孩就熟悉了。",
      },
      {
        id: "biaojie-kids-030-h",
        text: "第一個字，我他媽的以為會是喊肚子餓。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-kids-031",
    text: "老大的滑步車是德國進口，很順暢。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-031-a",
        text: "挑玩具妳也做了不少功課吧，笑死。",
        archetype: "deflect",
        retort: "對啊，比較了好幾款才決定（笑）。",
      },
      {
        id: "biaojie-kids-031-b",
        text: "幹……我對這些品牌完全沒概念……",
        archetype: "meek",
        retort: "沒概念沒關係，可以先做功課。",
      },
      {
        id: "biaojie-kids-031-c",
        text: "進口滑步車，機掰，滑走的是荷包。",
        archetype: "perfect",
        retort: "……幹，你這孩子嘴巴很壞（笑容僵）。",
      },
      {
        id: "biaojie-kids-031-d",
        text: "德國進口，那我他媽的腳踏車也是歐洲貨。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-kids-031-e",
        text: "表姊你對小孩的東西真的講究。",
        archetype: "deflect",
        retort: "為了安全，這個不能省（笑）。",
      },
      {
        id: "biaojie-kids-031-f",
        text: "買那麼貴，妳他媽的老公知道嗎，歐巴桑？",
        archetype: "landmine",
        retort: "你他媽的給我滾出去！",
      },
      {
        id: "biaojie-kids-031-g",
        text: "感覺養小孩的東西都好貴……",
        archetype: "meek",
        retort: "貴是真的，但值得的地方也多。",
      },
      {
        id: "biaojie-kids-031-h",
        text: "滑步車，我他媽的小時候騎三輪車也很快。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-kids-032",
    text: "送老二的滿月禮，你要送什麼呀？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-032-a",
        text: "表姊你收到的禮物一定超豐富。",
        archetype: "deflect",
        retort: "對啊，親戚都好用心（笑）。",
      },
      {
        id: "biaojie-kids-032-b",
        text: "幹……我還沒想好要送什麼比較好……",
        archetype: "meek",
        retort: "早點想好，免得到時候手忙腳亂。",
      },
      {
        id: "biaojie-kids-032-c",
        text: "禮物我隨意，妳他媽的排場我隨喜。",
        archetype: "perfect",
        retort: "……他媽的，沒大沒小（臉一沉）。",
      },
      {
        id: "biaojie-kids-032-d",
        text: "送禮喔，那我他媽的包一包乖乖代替。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-kids-032-e",
        text: "你們家寶寶的用品都好講究，笑死。",
        archetype: "deflect",
        retort: "都是精挑細選的啦（笑）。",
      },
      {
        id: "biaojie-kids-032-f",
        text: "比禮物，妳他媽的人生只剩這個？",
        archetype: "landmine",
        retort: "去死啦你，講什麼鬼話！",
      },
      {
        id: "biaojie-kids-032-g",
        text: "我怕送的東西你們已經有了……",
        archetype: "meek",
        retort: "怕重複的話，可以先問問看。",
      },
      {
        id: "biaojie-kids-032-h",
        text: "滿月禮，那我他媽的送他一張股票。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
  {
    id: "biaojie-kids-033",
    text: "初一帶兩個去拜拜，求了平安符。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-033-a",
        text: "帶兩個小孩拜拜，一定很費力氣，笑死。",
        archetype: "deflect",
        retort: "對啊，追得我氣喘吁吁（笑）。",
      },
      {
        id: "biaojie-kids-033-b",
        text: "幹……我平常比較少拜拜，不太懂習俗……",
        archetype: "meek",
        retort: "不懂沒關係，跟著我學就好。",
      },
      {
        id: "biaojie-kids-033-c",
        text: "求平安符，他媽的先求自己少講兩句。",
        archetype: "perfect",
        retort: "（笑容不見）……去你的，很敢講。",
      },
      {
        id: "biaojie-kids-033-d",
        text: "平安符喔，那我他媽的隨身帶悠遊卡。",
        archetype: "backfire",
        retort: "……笑死，這什麼冷場發言。",
      },
      {
        id: "biaojie-kids-033-e",
        text: "表姊你對家裡真的很盡心盡力。",
        archetype: "deflect",
        retort: "應該的啦，家人最重要（笑）。",
      },
      {
        id: "biaojie-kids-033-f",
        text: "求平安符，是他媽的想叫人閉嘴，老女人？",
        archetype: "landmine",
        retort: "幹！你才是欠罵的那個！",
      },
      {
        id: "biaojie-kids-033-g",
        text: "我怕帶小孩去廟裡會太吵鬧……",
        archetype: "meek",
        retort: "吵鬧一下沒關係，神明不介意。",
      },
      {
        id: "biaojie-kids-033-h",
        text: "拜拜，那我他媽的在家拜我家沙發就好。",
        archetype: "backfire",
        retort: "……（乾笑）北七喔你。",
      },
    ],
  },
  {
    id: "biaojie-kids-034",
    text: "老大會背二十首唐詩，表演給你看。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-034-a",
        text: "教他背唐詩，妳一定很有耐心，笑死。",
        archetype: "deflect",
        retort: "還好啦，他自己也很喜歡背（笑）。",
      },
      {
        id: "biaojie-kids-034-b",
        text: "幹……我小時候背書都背不起來……",
        archetype: "meek",
        retort: "背不起來沒關係，各有天分。",
      },
      {
        id: "biaojie-kids-034-c",
        text: "背兩首就好，他媽的別背成炫耀大會。",
        archetype: "perfect",
        retort: "……（氣到講台語）幹恁娘咧。",
      },
      {
        id: "biaojie-kids-034-d",
        text: "唐詩喔，那我他媽的來背一段流行歌詞。",
        archetype: "backfire",
        retort: "……哭爸，你自己講完不尷尬？",
      },
      {
        id: "biaojie-kids-034-e",
        text: "表姊你陪讀真的很用心耶。",
        archetype: "deflect",
        retort: "謝謝你，都是點滴累積的（笑）。",
      },
      {
        id: "biaojie-kids-034-f",
        text: "背這個，是他媽的要證明妳會教？",
        archetype: "landmine",
        retort: "（臉色鐵青）明年不用他媽的來了。",
      },
      {
        id: "biaojie-kids-034-g",
        text: "我對這種記憶力訓練不太懂……",
        archetype: "meek",
        retort: "不懂的話，可以多學學方法。",
      },
      {
        id: "biaojie-kids-034-h",
        text: "二十首，那我他媽的背二十個星座運勢。",
        archetype: "backfire",
        retort: "……（沒人接話）廢話真多。",
      },
    ],
  },
  {
    id: "biaojie-kids-035",
    text: "尿布濕紙巾我都整箱囤，你懂嗎？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-035-a",
        text: "囤貨這麼有計劃，妳真的很細心，笑死。",
        archetype: "deflect",
        retort: "對啊，才不會臨時缺貨（笑）。",
      },
      {
        id: "biaojie-kids-035-b",
        text: "幹……我對這種日常開銷完全沒概念……",
        archetype: "meek",
        retort: "沒概念的話，以後會嚇一跳。",
      },
      {
        id: "biaojie-kids-035-c",
        text: "囤這麼多，機掰，囤不到我的耐心。",
        archetype: "perfect",
        retort: "……你很過分耶，幹（別過臉）。",
      },
      {
        id: "biaojie-kids-035-d",
        text: "整箱囤，那我他媽的囤泡麵準備過年。",
        archetype: "backfire",
        retort: "……（表姊翻白眼）你很無聊耶。",
      },
      {
        id: "biaojie-kids-035-e",
        text: "表姊你持家的功力真的很強。",
        archetype: "deflect",
        retort: "還好啦，都是被逼出來的（笑）。",
      },
      {
        id: "biaojie-kids-035-f",
        text: "囤這麼多，妳他媽的是錢太多喔，歐巴桑？",
        archetype: "landmine",
        retort: "你他媽的閉嘴，別再說了！",
      },
      {
        id: "biaojie-kids-035-g",
        text: "感覺養小孩的日常花費好驚人……",
        archetype: "meek",
        retort: "驚人是真的，要提早有心理準備。",
      },
      {
        id: "biaojie-kids-035-h",
        text: "濕紙巾，那我他媽的拿來當面紙用就好。",
        archetype: "backfire",
        retort: "……靠，這什麼冷笑話啦。",
      },
    ],
  },
  {
    id: "biaojie-kids-036",
    text: "老大生日辦流水席，你們要不要來？",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-036-a",
        text: "辦生日趴一定籌備很久吧，笑死？",
        archetype: "deflect",
        retort: "對啊，光場地就選了好幾週（笑）。",
      },
      {
        id: "biaojie-kids-036-b",
        text: "幹……我對辦這種活動完全沒經驗……",
        archetype: "meek",
        retort: "沒經驗沒關係，多辦幾次就會了。",
      },
      {
        id: "biaojie-kids-036-c",
        text: "流水席喔，機掰，我隨份子，別嫌少。",
        archetype: "perfect",
        retort: "……機掰，你這張嘴誰教的？",
      },
      {
        id: "biaojie-kids-036-d",
        text: "流水席喔，那我他媽的在家煮泡麵慶生。",
        archetype: "backfire",
        retort: "……（全桌安靜）幹，你在講三小。",
      },
      {
        id: "biaojie-kids-036-e",
        text: "表姊你辦活動的能力真的一流。",
        archetype: "deflect",
        retort: "謝謝誇獎，都是為了小孩開心（笑）。",
      },
      {
        id: "biaojie-kids-036-f",
        text: "辦這麼大，是他媽的要炫耀什麼？",
        archetype: "landmine",
        retort: "機掰，你這什麼態度！",
      },
      {
        id: "biaojie-kids-036-g",
        text: "感覺生日趴要花不少預算……",
        archetype: "meek",
        retort: "預算是真的要抓好，別亂花。",
      },
      {
        id: "biaojie-kids-036-h",
        text: "生日趴，那我他媽的去夜市套圈圈慶祝。",
        archetype: "backfire",
        retort: "……白癡喔，這什麼爛笑話。",
      },
    ],
  },
  {
    id: "biaojie-kids-037",
    text: "明天班親會，我要去幫老大爭取一下。",
    topic: "kids",
    bossId: "biaojie",
    options: [
      {
        id: "biaojie-kids-037-a",
        text: "你這麼積極參加，一定很受喜歡，笑死。",
        archetype: "deflect",
        retort: "還好啦，老師人都很親切（笑）。",
      },
      {
        id: "biaojie-kids-037-b",
        text: "幹……我對班親會這種場合真的很不熟……",
        archetype: "meek",
        retort: "不熟沒關係，之後慢慢習慣。",
      },
      {
        id: "biaojie-kids-037-c",
        text: "爭取歸爭取，他媽的老師看的是成績。",
        archetype: "perfect",
        retort: "（尷尬）……你他媽的很敢說喔。",
      },
      {
        id: "biaojie-kids-037-d",
        text: "班親會喔，那我他媽的去幫忙管秩序好了。",
        archetype: "backfire",
        retort: "……（沒人笑）你很尷尬耶。",
      },
      {
        id: "biaojie-kids-037-e",
        text: "表姊你參與小孩學校的事真投入。",
        archetype: "deflect",
        retort: "應該的，這樣才了解他的狀況（笑）。",
      },
      {
        id: "biaojie-kids-037-f",
        text: "爭取而已，妳他媽的很會凹欸，老女人？",
        archetype: "landmine",
        retort: "（拍桌）去你的，太過分了！",
      },
      {
        id: "biaojie-kids-037-g",
        text: "我可能沒辦法常常請假去參加……",
        archetype: "meek",
        retort: "沒辦法的話，小孩會有點失落。",
      },
      {
        id: "biaojie-kids-037-h",
        text: "爭取喔，那我他媽的幫你寫陳情書。",
        archetype: "backfire",
        retort: "……（表姊愣住）你有病喔。",
      },
    ],
  },
] satisfies Question[];
