import type { Question } from "@/content/types";

// situations:
// 1. 看到你手機裡的線上課程
// 2. 問你讀那麼多書為什麼還租房
// 3. 聊到他孫子成績單
// 4. 問你會不會寫程式
// 5. 聊到現在學店太多
// 6. 問你研究所畢業論文題目太冷門
// 7. 看到你朋友圈都在讀博士
// 8. 聊到他當年半工半讀
// 9. 問你會不會教他用手機
// 10. 問你有沒有轉系轉錯
// 11. 聊到大學生現在都在耍廢
// 12. 問你有沒有想過重考
// 13. 看到你書桌上的原文書
// 14. 聊到現在老師難當
// 15. 問你要不要考研究所逃避就業
// 16. 聊到讀資工的都很好賺
// 17. 問你畢業紀念冊上寫的志願

export default [
  {
    id: "dabo-education-021",
    text: "手機裡都是線上課程，花錢學這個？",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-021-a",
        text: "你手機課程跟詐騙廣告都分不清楚。",
        archetype: "landmine",
        retort: "（拍桌站起來）你講夠了沒！",
      },
      {
        id: "dabo-education-021-b",
        text: "我買課程是為了收藏，不是要學。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-021-c",
        text: "買了很多課程，但沒時間上完……",
        archetype: "meek",
        retort: "沒上完還買，錢真好賺是不是。",
      },
      {
        id: "dabo-education-021-d",
        text: "花錢學新東西，總比花錢轉台值得。",
        archetype: "perfect",
        retort: "……（清清喉嚨，不再開口）",
      },
      {
        id: "dabo-education-021-e",
        text: "線上課程我都拿來當背景音助眠。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看手機）",
      },
      {
        id: "dabo-education-021-f",
        text: "你對投資自己這件事看得真透徹。",
        archetype: "deflect",
        retort: "那當然，我也懂得投資的道理。",
      },
      {
        id: "dabo-education-021-g",
        text: "大伯你想學什麼，我幫你找課程。",
        archetype: "deflect",
        retort: "我才不學，年紀大學不動了。",
      },
      {
        id: "dabo-education-021-h",
        text: "有花一點錢，但學到的東西有限……",
        archetype: "meek",
        retort: "有限還花錢，太不划算了吧。",
      },
    ],
  },
  {
    id: "dabo-education-022",
    text: "讀那麼多書，怎麼還租房子住。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-022-a",
        text: "大伯你買第一間房花多少年？",
        archetype: "deflect",
        retort: "我啊，也是省吃儉用好幾年。",
      },
      {
        id: "dabo-education-022-b",
        text: "你對買房這件事的看法，我很想聽。",
        archetype: "deflect",
        retort: "這個要聊起來，一整晚都講不完。",
      },
      {
        id: "dabo-education-022-c",
        text: "我也想買，但頭期款存不到……",
        archetype: "meek",
        retort: "存不到，那你錢都花到哪去了。",
      },
      {
        id: "dabo-education-022-d",
        text: "讀書投資腦袋，房子等你先示範買。",
        archetype: "perfect",
        retort: "大伯母：算了算了，吃飯吃飯。",
      },
      {
        id: "dabo-education-022-e",
        text: "我讀書讀到都能背房價數字了，很厲害。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-022-f",
        text: "讀書是讀了不少，但房價真的太高……",
        archetype: "meek",
        retort: "太高也要想辦法，不然一直租。",
      },
      {
        id: "dabo-education-022-g",
        text: "租房好啊，隨時可以搬家躲債主。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
      {
        id: "dabo-education-022-h",
        text: "你那間房是阿公留的，不是你賺的。",
        archetype: "landmine",
        retort: "大伯母：這孩子今年很嗆喔！",
      },
    ],
  },
  {
    id: "dabo-education-023",
    text: "我孫子這次考第一名，你以前呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-023-a",
        text: "我以前排名都是倒數的常勝軍。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-023-b",
        text: "我小時候考試常常粗心扣分……",
        archetype: "meek",
        retort: "粗心是態度問題，要改進。",
      },
      {
        id: "dabo-education-023-c",
        text: "我以前的強項是考試作弊技巧。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續誇孫子）",
      },
      {
        id: "dabo-education-023-d",
        text: "我以前考第一的，是誰先吃完飯。",
        archetype: "perfect",
        retort: "……（把新聞轉去氣象台）",
      },
      {
        id: "dabo-education-023-e",
        text: "你孫子的作業，是你女兒幫忙寫的。",
        archetype: "landmine",
        retort: "沒禮貌，長輩面前敢這樣講！",
      },
      {
        id: "dabo-education-023-f",
        text: "你這麼疼孫子，改天教教他做人。",
        archetype: "deflect",
        retort: "這個要慢慢來，急不得。",
      },
      {
        id: "dabo-education-023-g",
        text: "大伯你孫子這麼會念書，遺傳你嗎？",
        archetype: "deflect",
        retort: "那當然，這種聰明是家族遺傳。",
      },
      {
        id: "dabo-education-023-h",
        text: "我以前成績中等，沒特別突出……",
        archetype: "meek",
        retort: "中等而已，難怪現在也普普通通。",
      },
    ],
  },
  {
    id: "dabo-education-024",
    text: "讀那麼多書，會不會寫程式啊。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-024-a",
        text: "學過一些，但工作用不太到……",
        archetype: "meek",
        retort: "用不到學那個幹嘛，浪費時間。",
      },
      {
        id: "dabo-education-024-b",
        text: "會啊，改天幫你設定電視遙控器。",
        archetype: "perfect",
        retort: "大伯母：他這叫詞窮，別理他。",
      },
      {
        id: "dabo-education-024-c",
        text: "程式語言我只會說哈囉世界。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-024-d",
        text: "會一點點，但不是很厲害……",
        archetype: "meek",
        retort: "不厲害還敢說會，太謙虛也不好。",
      },
      {
        id: "dabo-education-024-e",
        text: "你對這個領域這麼好奇，很有遠見。",
        archetype: "deflect",
        retort: "那當然，我也是與時俱進。",
      },
      {
        id: "dabo-education-024-f",
        text: "大伯你想學程式嗎，我教你基礎。",
        archetype: "deflect",
        retort: "我才不學，這輩子用不到。",
      },
      {
        id: "dabo-education-024-g",
        text: "我寫程式都是複製貼上大師。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-024-h",
        text: "你連手機開機都要問我，別嫌我。",
        archetype: "landmine",
        retort: "（用台語）夭壽喔，這什麼話！",
      },
    ],
  },
  {
    id: "dabo-education-025",
    text: "現在什麼學店都能開，學歷不值錢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-025-a",
        text: "你那年代讀書機會少，不代表你行。",
        archetype: "landmine",
        retort: "大伯母：你哪根筋不對了！",
      },
      {
        id: "dabo-education-025-b",
        text: "學歷是沒以前值錢，我也很無奈……",
        archetype: "meek",
        retort: "無奈也要想辦法突破，不然一直輸。",
      },
      {
        id: "dabo-education-025-c",
        text: "學店多沒關係，我自己開一間更好賺。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-025-d",
        text: "學歷不值錢，那我拿去換錢好了。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-025-e",
        text: "大伯你覺得什麼樣的學校才算好？",
        archetype: "deflect",
        retort: "這個要看辦學用不用心啦。",
      },
      {
        id: "dabo-education-025-f",
        text: "不值錢沒關係，我這個人比較值錢。",
        archetype: "perfect",
        retort: "……（假裝沒聽到，繼續配飯）",
      },
      {
        id: "dabo-education-025-g",
        text: "你對教育品質這麼在意，很有見識。",
        archetype: "deflect",
        retort: "那當然，我也是關心下一代。",
      },
      {
        id: "dabo-education-025-h",
        text: "確實現在學校比較多，競爭也大……",
        archetype: "meek",
        retort: "競爭大就要更努力，別抱怨環境。",
      },
    ],
  },
  {
    id: "dabo-education-026",
    text: "你那論文題目冷門成這樣，有人看嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-026-a",
        text: "題目確實有點小眾，看的人不多……",
        archetype: "meek",
        retort: "不多還寫，浪費時間跟力氣。",
      },
      {
        id: "dabo-education-026-b",
        text: "大伯你猜猜看題目在寫什麼？",
        archetype: "deflect",
        retort: "猜不到，太深奧了。",
      },
      {
        id: "dabo-education-026-c",
        text: "你對冷門這件事這麼敏銳，佩服。",
        archetype: "deflect",
        retort: "那當然，這叫社會經驗。",
      },
      {
        id: "dabo-education-026-d",
        text: "是滿冷門的，指導教授也覺得辛苦……",
        archetype: "meek",
        retort: "連教授都覺得辛苦，那你圖什麼。",
      },
      {
        id: "dabo-education-026-e",
        text: "有人看，至少你現在被逼著看完。",
        archetype: "perfect",
        retort: "大伯母：講到重點了厚？",
      },
      {
        id: "dabo-education-026-f",
        text: "我的論文比安眠藥還有效。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-026-g",
        text: "冷門好，這樣就沒人抄我的。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-026-h",
        text: "你連論文摘要都沒認真看完就嫌。",
        archetype: "landmine",
        retort: "以後過年別來了，聽清楚！",
      },
    ],
  },
  {
    id: "dabo-education-027",
    text: "你朋友一堆都在讀博士，你呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-027-a",
        text: "讀博士太累，我選擇讀空氣就好。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-027-b",
        text: "我選擇早點賺錢，先養你的紅包。",
        archetype: "perfect",
        retort: "……（把眼鏡拿下來擦，避戰）",
      },
      {
        id: "dabo-education-027-c",
        text: "你連博士碩士的差別都搞不清楚。",
        archetype: "landmine",
        retort: "（拍桌）誰准你這樣頂嘴的！",
      },
      {
        id: "dabo-education-027-d",
        text: "考慮過，但覺得自己不是讀書的料……",
        archetype: "meek",
        retort: "不是讀書的料，那你圖什麼。",
      },
      {
        id: "dabo-education-027-e",
        text: "大伯你覺得讀博士辛苦嗎？",
        archetype: "deflect",
        retort: "那當然辛苦，讀那麼久誰受得了。",
      },
      {
        id: "dabo-education-027-f",
        text: "我朋友讀博士，我負責幫他們慶祝。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-027-g",
        text: "你對這些人生選擇這麼了解，佩服。",
        archetype: "deflect",
        retort: "那當然，我看的人多了。",
      },
      {
        id: "dabo-education-027-h",
        text: "我沒有繼續讀，工作壓力也不小……",
        archetype: "meek",
        retort: "沒繼續讀，那你以後怎麼跟人比。",
      },
    ],
  },
  {
    id: "dabo-education-028",
    text: "我當年半工半讀，你們現在太享受。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-028-a",
        text: "大伯你半工半讀的故事，說給我聽聽。",
        archetype: "deflect",
        retort: "好，那我從第一天講起。",
      },
      {
        id: "dabo-education-028-b",
        text: "享受歸享受，但沒把你們氣成這樣。",
        archetype: "perfect",
        retort: "大伯母：你這孩子今年進化了。",
      },
      {
        id: "dabo-education-028-c",
        text: "我現在也要打工，但確實沒那麼辛苦……",
        archetype: "meek",
        retort: "沒那麼辛苦，那你有什麼好抱怨的。",
      },
      {
        id: "dabo-education-028-d",
        text: "我也覺得自己過得比較舒服……",
        archetype: "meek",
        retort: "知道就好，要懂得感恩。",
      },
      {
        id: "dabo-education-028-e",
        text: "你這種毅力，我真的自嘆不如。",
        archetype: "deflect",
        retort: "那當然，我可是苦過來的人。",
      },
      {
        id: "dabo-education-028-f",
        text: "我現在也半工半廢，算是傳承。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
      {
        id: "dabo-education-028-g",
        text: "半工半讀聽起來像半糖去冰，我也想試試。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-028-h",
        text: "你那時半工半讀，還不是靠阿公資助。",
        archetype: "landmine",
        retort: "大伯母：真的太超過，太超過！",
      },
    ],
  },
  {
    id: "dabo-education-029",
    text: "你讀那麼多書，教教我用這手機。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-029-a",
        text: "大伯你想學什麼功能，我先了解一下。",
        archetype: "deflect",
        retort: "我想學怎麼傳貼圖給你們。",
      },
      {
        id: "dabo-education-029-b",
        text: "教你用手機，比教數學還難。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-029-c",
        text: "教手機而已，我收費一小時三百。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-029-d",
        text: "沒問題，教到你會分辨假新聞為止。",
        archetype: "perfect",
        retort: "……（默默把音量鍵按小聲）",
      },
      {
        id: "dabo-education-029-e",
        text: "可以教，但我自己也常常忘記步驟……",
        archetype: "meek",
        retort: "你自己都不熟，還敢說要教我。",
      },
      {
        id: "dabo-education-029-f",
        text: "你連基本設定都不會，還敢滑臉書。",
        archetype: "landmine",
        retort: "你這是要氣死長輩就對了！",
      },
      {
        id: "dabo-education-029-g",
        text: "你這麼願意學新東西，很厲害耶。",
        archetype: "deflect",
        retort: "那當然，我也要跟上時代。",
      },
      {
        id: "dabo-education-029-h",
        text: "好，但我教學可能不太有耐心……",
        archetype: "meek",
        retort: "沒耐心還敢說要教，太隨便了。",
      },
    ],
  },
  {
    id: "dabo-education-030",
    text: "聽說你轉過系，是不是選錯了。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-030-a",
        text: "你這輩子連工作都沒換過，別說我。",
        archetype: "landmine",
        retort: "（用台語罵）白目喔你！",
      },
      {
        id: "dabo-education-030-b",
        text: "是有點後悔，浪費了一些時間……",
        archetype: "meek",
        retort: "浪費時間，那你當初怎麼不想清楚。",
      },
      {
        id: "dabo-education-030-c",
        text: "轉系是有點衝動，但也沒辦法了……",
        archetype: "meek",
        retort: "衝動做決定，難怪現在辛苦。",
      },
      {
        id: "dabo-education-030-d",
        text: "你對人生選擇看得這麼透徹，佩服。",
        archetype: "deflect",
        retort: "那當然，我走過的路比你多。",
      },
      {
        id: "dabo-education-030-e",
        text: "大伯你當年有沒有想過轉行？",
        archetype: "deflect",
        retort: "想過啊，但那時候不敢冒險。",
      },
      {
        id: "dabo-education-030-f",
        text: "轉系而已，人生本來就是選擇題亂猜。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-030-g",
        text: "我轉系是為了多修幾年學校美食。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-030-h",
        text: "沒選錯，繞點路，總比原地打轉好。",
        archetype: "perfect",
        retort: "大伯母：這句我記下來了。",
      },
    ],
  },
  {
    id: "dabo-education-031",
    text: "現在大學生都在耍廢，你也是吧。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-031-a",
        text: "你對年輕人的觀察真的很細膩。",
        archetype: "deflect",
        retort: "那當然，我看得多了。",
      },
      {
        id: "dabo-education-031-b",
        text: "耍廢是充電，充飽才受得了你問話。",
        archetype: "perfect",
        retort: "……（轉台，假裝找遙控器）",
      },
      {
        id: "dabo-education-031-c",
        text: "耍廢是我的專長，比讀書還拿手。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-031-d",
        text: "你退休後不也整天躺著看電視。",
        archetype: "landmine",
        retort: "（拍桌）你這什麼態度！",
      },
      {
        id: "dabo-education-031-e",
        text: "我耍廢是為了跟時代脫節，比較潮。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-031-f",
        text: "大伯你退休後都怎麼安排時間？",
        archetype: "deflect",
        retort: "我啊，看電視也算是一種休息。",
      },
      {
        id: "dabo-education-031-g",
        text: "是有比較懶散，但也還是有在努力……",
        archetype: "meek",
        retort: "懶散還敢說努力，矛盾。",
      },
      {
        id: "dabo-education-031-h",
        text: "我確實花不少時間在放鬆……",
        archetype: "meek",
        retort: "放鬆太多，難怪什麼都做不好。",
      },
    ],
  },
  {
    id: "dabo-education-032",
    text: "當初分數不夠，有沒有想過重考。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-032-a",
        text: "分數是不太理想，多少有點遺憾……",
        archetype: "meek",
        retort: "遺憾就要更努力彌補啊。",
      },
      {
        id: "dabo-education-032-b",
        text: "你以前考試成績，也沒好到哪去。",
        archetype: "landmine",
        retort: "大伯母：這孩子太過分了！",
      },
      {
        id: "dabo-education-032-c",
        text: "你對這個議題想得真周到，謝謝關心。",
        archetype: "deflect",
        retort: "那當然，我也是為你好。",
      },
      {
        id: "dabo-education-032-d",
        text: "大伯你當年考試壓力大嗎？",
        archetype: "deflect",
        retort: "大啊，那年代競爭也是很激烈。",
      },
      {
        id: "dabo-education-032-e",
        text: "有想過，但重考壓力太大就放棄了……",
        archetype: "meek",
        retort: "放棄，那你現在後悔也沒用了。",
      },
      {
        id: "dabo-education-032-f",
        text: "重考不如重生，投胎比較快。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-032-g",
        text: "我當初分數不夠，是老師改錯了。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-032-h",
        text: "想過，但重考不如重新想想你的話。",
        archetype: "perfect",
        retort: "大伯母：對啦對啦，我也這樣說。",
      },
    ],
  },
  {
    id: "dabo-education-033",
    text: "這什麼英文書，看不懂還擺著。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-033-a",
        text: "看得懂，比你電視字幕清楚多了。",
        archetype: "perfect",
        retort: "……（喝茶，不看你）",
      },
      {
        id: "dabo-education-033-b",
        text: "這書我拿來壓泡麵蓋子最實用。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-033-c",
        text: "你注意到這個，眼力真的很好。",
        archetype: "deflect",
        retort: "那當然，我什麼都看得仔細。",
      },
      {
        id: "dabo-education-033-d",
        text: "英文書擺著比較有氣質，裝飾用。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-033-e",
        text: "大伯你想學英文嗎，我教你單字。",
        archetype: "deflect",
        retort: "我才不學，年紀大記不住了。",
      },
      {
        id: "dabo-education-033-f",
        text: "你連中文報紙都看不完，別說我。",
        archetype: "landmine",
        retort: "沒大沒小，欠教訓是不是！",
      },
      {
        id: "dabo-education-033-g",
        text: "看得懂一部分，有些單字還要查……",
        archetype: "meek",
        retort: "要查才懂，那算什麼看得懂。",
      },
      {
        id: "dabo-education-033-h",
        text: "其實我也常常看不太懂內容……",
        archetype: "meek",
        retort: "看不懂還買，錢真好花是不是。",
      },
    ],
  },
  {
    id: "dabo-education-034",
    text: "現在老師難當，你們讀書也不受教。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-034-a",
        text: "現在學生確實比較有自己的想法……",
        archetype: "meek",
        retort: "有想法不代表對，還是要尊師重道。",
      },
      {
        id: "dabo-education-034-b",
        text: "你對教育現場的觀察真的很敏銳。",
        archetype: "deflect",
        retort: "那當然，我電視新聞都有在看。",
      },
      {
        id: "dabo-education-034-c",
        text: "老師難當，那我推薦他改當網紅。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-034-d",
        text: "你以前對長輩講話，也沒多客氣。",
        archetype: "landmine",
        retort: "（用台語罵）恁祖媽咧，見笑！",
      },
      {
        id: "dabo-education-034-e",
        text: "我以前也常常跟老師頂嘴……",
        archetype: "meek",
        retort: "頂嘴，難怪你現在講話這麼衝。",
      },
      {
        id: "dabo-education-034-f",
        text: "大伯你以前遇過凶的老師嗎？",
        archetype: "deflect",
        retort: "有啊，那時候老師都很嚴格。",
      },
      {
        id: "dabo-education-034-g",
        text: "我以前對老師最尊敬的方式是遲到。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-034-h",
        text: "受教啊，我最聽勸，除了你那套。",
        archetype: "perfect",
        retort: "……（大伯母憋笑，遞你雞腿）",
      },
    ],
  },
  {
    id: "dabo-education-035",
    text: "是不是找不到工作才去考研究所。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-035-a",
        text: "不是逃避，是先充電再回來嗆你。",
        archetype: "perfect",
        retort: "……（把電視音量轉大蓋過去）",
      },
      {
        id: "dabo-education-035-b",
        text: "大伯你覺得考研究所值不值得？",
        archetype: "deflect",
        retort: "這個要看你自己想清楚啊。",
      },
      {
        id: "dabo-education-035-c",
        text: "你對就業市場觀察得真透徹。",
        archetype: "deflect",
        retort: "那當然，新聞都有在報。",
      },
      {
        id: "dabo-education-035-d",
        text: "你退休前，不也是能拖就拖不上班。",
        archetype: "landmine",
        retort: "叫你爸出來，我跟他說！",
      },
      {
        id: "dabo-education-035-e",
        text: "我讀研究所是想順便找對象。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-035-f",
        text: "考研究所是為了多住幾年宿舍。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-035-g",
        text: "確實工作不好找，才想多讀一點……",
        archetype: "meek",
        retort: "多讀一點，出來還不是一樣難找。",
      },
      {
        id: "dabo-education-035-h",
        text: "是有想逃避一下沒錯，我承認……",
        archetype: "meek",
        retort: "逃避沒用，問題還是要面對。",
      },
    ],
  },
  {
    id: "dabo-education-036",
    text: "隔壁讀資工的年薪百萬，你呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-036-a",
        text: "薪水是沒那麼高，但工作還算穩定……",
        archetype: "meek",
        retort: "穩定有什麼用，錢才是實際的。",
      },
      {
        id: "dabo-education-036-b",
        text: "我年薪雖然不高，但快樂指數破表。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-036-c",
        text: "你對薪資行情這麼清楚，佩服。",
        archetype: "deflect",
        retort: "那當然，我天天在關心這些。",
      },
      {
        id: "dabo-education-036-d",
        text: "大伯你覺得什麼科系最好賺？",
        archetype: "deflect",
        retort: "這個要看時機，跟得上就好賺。",
      },
      {
        id: "dabo-education-036-e",
        text: "確實差滿多的，我也有點壓力……",
        archetype: "meek",
        retort: "有壓力就要想辦法轉行啊。",
      },
      {
        id: "dabo-education-036-f",
        text: "沒關係，我打算轉行去挖礦。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-036-g",
        text: "你退休金，也沒比人家多到哪去。",
        archetype: "landmine",
        retort: "明年不用來了，聽到沒！",
      },
      {
        id: "dabo-education-036-h",
        text: "我呢，換算成快樂算是穩賺不賠。",
        archetype: "perfect",
        retort: "大伯母：講輸就別講了啦。",
      },
    ],
  },
  {
    id: "dabo-education-037",
    text: "你畢業紀念冊寫的志願，實現了嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-037-a",
        text: "實現了，志願是讓你今天無話可說。",
        archetype: "perfect",
        retort: "……（假裝滑手機，不接話）",
      },
      {
        id: "dabo-education-037-b",
        text: "我寫的志願是總統，還沒實現。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-037-c",
        text: "你以前寫的志願，大概也是隨便交差。",
        archetype: "landmine",
        retort: "大伯母：你聽聽這是什麼話！",
      },
      {
        id: "dabo-education-037-d",
        text: "你還記得志願這種細節，記性真好。",
        archetype: "deflect",
        retort: "那當然，我什麼都記得清清楚楚。",
      },
      {
        id: "dabo-education-037-e",
        text: "大伯你畢業紀念冊寫了什麼志願？",
        archetype: "deflect",
        retort: "我寫的是要當大老闆，哈哈。",
      },
      {
        id: "dabo-education-037-f",
        text: "我志願寫要嫁豪門，還在等機會。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-037-g",
        text: "寫的跟現在做的差滿多的……",
        archetype: "meek",
        retort: "差這麼多，那你當初亂寫的喔。",
      },
      {
        id: "dabo-education-037-h",
        text: "志願是有，但現實跟理想有落差……",
        archetype: "meek",
        retort: "有落差就要努力縮小，別放棄。",
      },
    ],
  },
] satisfies Question[];
