import type { Question } from "@/content/types";

// situations:
// 1. 看到你手機裡的線上課程
// 2. 問你讀那麼多書為什麼還租房
// 3. 聊到他孫子成績單
// 4. 問你會不會寫程式
// 5. 聊到現在學店太多
// 6. 問你研究所畢業論文題目太冷門
// 7. 看到你朋友圈都在讀博士
// 8. 聊到他當年半工半讀
// 9. 問你會不會教他用手機
// 10. 問你有沒有轉系轉錯
// 11. 聊到大學生現在都在耍廢
// 12. 問你有沒有想過重考
// 13. 看到你書桌上的原文書
// 14. 聊到現在老師難當
// 15. 問你要不要考研究所逃避就業
// 16. 聊到讀資工的都很好賺
// 17. 問你畢業紀念冊上寫的志願

export default [
  {
    id: "dabo-education-021",
    text: "手機裡都是線上課程，花錢學這個？",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-021-a",
        text: "幹，老東西你連手機都不會滑。",
        archetype: "landmine",
        retort: "你他媽的翅膀硬了敢嗆我！",
      },
      {
        id: "dabo-education-021-b",
        text: "他媽的課程買來當桌布，很潮。",
        archetype: "backfire",
        retort: "……白癡喔，你錢多沒地方花。",
      },
      {
        id: "dabo-education-021-c",
        text: "幹……買了一堆，沒空上完啦……",
        archetype: "meek",
        retort: "沒上完還敢花，你是欠罵嗎。",
      },
      {
        id: "dabo-education-021-d",
        text: "幹，花錢學習總比你轉台強。",
        archetype: "perfect",
        retort: "大伯母：算了算了，吃飯吃飯。",
      },
      {
        id: "dabo-education-021-e",
        text: "幹，這課程拿來助眠，比中藥有效。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續滑手機）",
      },
      {
        id: "dabo-education-021-f",
        text: "靠，你懂投資自己這麼透徹喔。",
        archetype: "deflect",
        retort: "那當然，我也懂得投資的道理。",
      },
      {
        id: "dabo-education-021-g",
        text: "大伯你想學什麼，我幫你找課程。",
        archetype: "deflect",
        retort: "我才不學，年紀大學不動了。",
      },
      {
        id: "dabo-education-021-h",
        text: "有花一點錢，但學到的東西有限……",
        archetype: "meek",
        retort: "有限還花錢，太不划算了吧。",
      },
    ],
  },
  {
    id: "dabo-education-022",
    text: "讀那麼多書，怎麼還租房子住。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-022-a",
        text: "靠，你買第一間房花多少年啊？",
        archetype: "deflect",
        retort: "我啊，也是省吃儉用好幾年。",
      },
      {
        id: "dabo-education-022-b",
        text: "你對買房這件事的看法，我很想聽。",
        archetype: "deflect",
        retort: "這個要聊起來，一整晚都講不完。",
      },
      {
        id: "dabo-education-022-c",
        text: "靠……頭期款存不到，別提了……",
        archetype: "meek",
        retort: "存不到，那你錢都花到哪去了。",
      },
      {
        id: "dabo-education-022-d",
        text: "他媽的，讀書投資腦袋，你先買房示範。",
        archetype: "perfect",
        retort: "……（清清喉嚨，不再開口）",
      },
      {
        id: "dabo-education-022-e",
        text: "機掰，我讀書讀到會背房價數字。",
        archetype: "backfire",
        retort: "……（大伯沒理你，自顧自講電視）",
      },
      {
        id: "dabo-education-022-f",
        text: "讀書是讀了不少，但房價真的太高……",
        archetype: "meek",
        retort: "太高也要想辦法，不然一直租。",
      },
      {
        id: "dabo-education-022-g",
        text: "去你的房子，租屋方便躲債主啦。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
      {
        id: "dabo-education-022-h",
        text: "去死，老東西這間房是阿公留的。",
        archetype: "landmine",
        retort: "去你的，這什麼態度，滾邊去！",
      },
    ],
  },
  {
    id: "dabo-education-023",
    text: "我孫子這次考第一名，你以前呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-023-a",
        text: "他媽的，我以前排名都是倒數常勝軍。",
        archetype: "backfire",
        retort: "……（大伯哼一聲，喝茶不說話）",
      },
      {
        id: "dabo-education-023-b",
        text: "我小時候考試常常粗心扣分……",
        archetype: "meek",
        retort: "粗心是態度問題，要改進。",
      },
      {
        id: "dabo-education-023-c",
        text: "幹，我以前強項是考試作弊技巧。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續誇孫子）",
      },
      {
        id: "dabo-education-023-d",
        text: "靠北，我以前考第一是誰先吃完飯。",
        archetype: "perfect",
        retort: "……（把新聞轉去氣象台）",
      },
      {
        id: "dabo-education-023-e",
        text: "雞掰，老東西孫子作業是代寫的。",
        archetype: "landmine",
        retort: "幹，沒大沒小，找打是不是！",
      },
      {
        id: "dabo-education-023-f",
        text: "笑死，你這麼疼孫子，教教他做人。",
        archetype: "deflect",
        retort: "這個要慢慢來，急不得。",
      },
      {
        id: "dabo-education-023-g",
        text: "大伯你孫子這麼會念書，遺傳你嗎？",
        archetype: "deflect",
        retort: "那當然，這種聰明是家族遺傳。",
      },
      {
        id: "dabo-education-023-h",
        text: "幹……我以前成績中等，沒特別突出……",
        archetype: "meek",
        retort: "中等而已，難怪現在也普普通通。",
      },
    ],
  },
  {
    id: "dabo-education-024",
    text: "讀那麼多書，會不會寫程式啊。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-024-a",
        text: "學過一些，但工作用不太到……",
        archetype: "meek",
        retort: "用不到學那個幹嘛，浪費時間。",
      },
      {
        id: "dabo-education-024-b",
        text: "機掰，會啊，改天幫你設遙控器就好。",
        archetype: "perfect",
        retort: "大伯母：他這叫詞窮，別理他。",
      },
      {
        id: "dabo-education-024-c",
        text: "機掰，程式語言我只會哈囉世界。",
        archetype: "backfire",
        retort: "……白癡喔，哈囉世界很厲害嗎。",
      },
      {
        id: "dabo-education-024-d",
        text: "靠……會一點點，但不是很厲害……",
        archetype: "meek",
        retort: "不厲害還敢說會，太謙虛也不好。",
      },
      {
        id: "dabo-education-024-e",
        text: "你對這個領域這麼好奇，很有遠見。",
        archetype: "deflect",
        retort: "那當然，我也是與時俱進。",
      },
      {
        id: "dabo-education-024-f",
        text: "哭爸，大伯你想學程式我教你啊。",
        archetype: "deflect",
        retort: "我才不學，這輩子用不到。",
      },
      {
        id: "dabo-education-024-g",
        text: "去死，我寫程式都複製貼上大師。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-024-h",
        text: "機掰，死老頭連開機都要問我。",
        archetype: "landmine",
        retort: "幹你娘，皮在癢是不是你！",
      },
    ],
  },
  {
    id: "dabo-education-025",
    text: "現在什麼學店都能開，學歷不值錢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-025-a",
        text: "幹你娘，老不死你那年代機會少。",
        archetype: "landmine",
        retort: "去死啦你，敢這樣跟我講話！",
      },
      {
        id: "dabo-education-025-b",
        text: "幹……學歷是沒以前值錢，我無奈……",
        archetype: "meek",
        retort: "無奈也要想辦法突破，不然一直輸。",
      },
      {
        id: "dabo-education-025-c",
        text: "死一死，學店多我自己開一間更賺。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-025-d",
        text: "幹，這學歷不值錢，換錢好了。",
        archetype: "backfire",
        retort: "……（大伯愣了一下，沒接話）",
      },
      {
        id: "dabo-education-025-e",
        text: "大伯你覺得什麼樣的學校才算好？",
        archetype: "deflect",
        retort: "這個要看辦學用不用心啦。",
      },
      {
        id: "dabo-education-025-f",
        text: "去你的，不值錢沒關係，我人比較值錢。",
        archetype: "perfect",
        retort: "他媽的，你這什麼態度啊你！",
      },
      {
        id: "dabo-education-025-g",
        text: "笑死，你對教育品質這麼在意喔。",
        archetype: "deflect",
        retort: "那當然，我也是關心下一代。",
      },
      {
        id: "dabo-education-025-h",
        text: "確實現在學校比較多，競爭也大……",
        archetype: "meek",
        retort: "競爭大就要更努力，別抱怨環境。",
      },
    ],
  },
  {
    id: "dabo-education-026",
    text: "你那論文題目冷門成這樣，有人看嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-026-a",
        text: "題目確實有點小眾，看的人不多……",
        archetype: "meek",
        retort: "不多還寫，浪費時間跟力氣。",
      },
      {
        id: "dabo-education-026-b",
        text: "靠，大伯你猜猜題目在寫什麼啊？",
        archetype: "deflect",
        retort: "猜不到，太深奧了。",
      },
      {
        id: "dabo-education-026-c",
        text: "你對冷門這件事這麼敏銳，佩服。",
        archetype: "deflect",
        retort: "那當然，這叫社會經驗。",
      },
      {
        id: "dabo-education-026-d",
        text: "靠……指導教授也覺得辛苦啦……",
        archetype: "meek",
        retort: "連教授都覺得辛苦，那你圖什麼。",
      },
      {
        id: "dabo-education-026-e",
        text: "幹，有人看，至少你被逼著看完。",
        archetype: "perfect",
        retort: "大伯母：講到重點了厚？",
      },
      {
        id: "dabo-education-026-f",
        text: "機掰，我的論文比安眠藥還有效。",
        archetype: "backfire",
        retort: "……（大伯瞪著電視，沒搭理你）",
      },
      {
        id: "dabo-education-026-g",
        text: "去死，冷門好這樣沒人抄我的啦。",
        archetype: "backfire",
        retort: "……（大伯沒接話，轉頭看電視）",
      },
      {
        id: "dabo-education-026-h",
        text: "去你的，老屁股論文摘要沒看完。",
        archetype: "landmine",
        retort: "幹你娘，以後過年別來了！",
      },
    ],
  },
  {
    id: "dabo-education-027",
    text: "你朋友一堆都在讀博士，你呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-027-a",
        text: "他媽的，讀博士太累我選讀空氣。",
        archetype: "backfire",
        retort: "……白癡喔，讀空氣還敢講。",
      },
      {
        id: "dabo-education-027-b",
        text: "靠北，我選早點賺錢先養你紅包啦。",
        archetype: "perfect",
        retort: "幹，你這張嘴巴是欠罵嗎。",
      },
      {
        id: "dabo-education-027-c",
        text: "幹，老東西連博士碩士都分不清。",
        archetype: "landmine",
        retort: "他媽的，誰准你這樣頂嘴的！",
      },
      {
        id: "dabo-education-027-d",
        text: "考慮過，但覺得自己不是讀書的料……",
        archetype: "meek",
        retort: "不是讀書的料，那你圖什麼。",
      },
      {
        id: "dabo-education-027-e",
        text: "哭爸，大伯你覺得讀博士辛苦嗎？",
        archetype: "deflect",
        retort: "那當然辛苦，讀那麼久誰受得了。",
      },
      {
        id: "dabo-education-027-f",
        text: "幹，朋友讀博士，我負責慶祝。",
        archetype: "backfire",
        retort: "……（大伯皺眉，繼續轉台）",
      },
      {
        id: "dabo-education-027-g",
        text: "你對這些人生選擇這麼了解，佩服。",
        archetype: "deflect",
        retort: "那當然，我看的人多了。",
      },
      {
        id: "dabo-education-027-h",
        text: "幹……我沒繼續讀，工作壓力也不小……",
        archetype: "meek",
        retort: "沒繼續讀，那你以後怎麼跟人比。",
      },
    ],
  },
  {
    id: "dabo-education-028",
    text: "我當年半工半讀，你們現在太享受。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-028-a",
        text: "大伯你半工半讀的故事，說來聽聽。",
        archetype: "deflect",
        retort: "好，那我從第一天講起。",
      },
      {
        id: "dabo-education-028-b",
        text: "幹，享受歸享受，沒把你們氣成這樣。",
        archetype: "perfect",
        retort: "大伯母：你這孩子今年進化了。",
      },
      {
        id: "dabo-education-028-c",
        text: "靠……我現在也打工，但沒那麼辛苦……",
        archetype: "meek",
        retort: "沒那麼辛苦，那你有什麼好抱怨的。",
      },
      {
        id: "dabo-education-028-d",
        text: "我也覺得自己過得比較舒服……",
        archetype: "meek",
        retort: "知道就好，要懂得感恩。",
      },
      {
        id: "dabo-education-028-e",
        text: "笑死，你這種毅力我真的自嘆不如。",
        archetype: "deflect",
        retort: "那當然，我可是苦過來的人。",
      },
      {
        id: "dabo-education-028-f",
        text: "雞掰，我現在半工半廢算傳承啦。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
      {
        id: "dabo-education-028-g",
        text: "機掰，半工半讀像半糖去冰我也想試。",
        archetype: "backfire",
        retort: "……（大伯搖搖頭，轉頭滑手機）",
      },
      {
        id: "dabo-education-028-h",
        text: "去你的，你半工半讀還不是靠阿公。",
        archetype: "landmine",
        retort: "幹你娘，太超過了，滾一邊！",
      },
    ],
  },
  {
    id: "dabo-education-029",
    text: "你讀那麼多書，教教我用這手機。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-029-a",
        text: "大伯你想學什麼功能，我先了解。",
        archetype: "deflect",
        retort: "我想學怎麼傳貼圖給你們。",
      },
      {
        id: "dabo-education-029-b",
        text: "他媽的，教你用手機比教數學還難。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-029-c",
        text: "靠北，教手機而已我收費一小時三百。",
        archetype: "backfire",
        retort: "……（大伯瞄你一眼，喝口茶不說話）",
      },
      {
        id: "dabo-education-029-d",
        text: "機掰，沒問題，教到你分辨假新聞為止。",
        archetype: "perfect",
        retort: "……（默默把音量鍵按小聲）",
      },
      {
        id: "dabo-education-029-e",
        text: "可以教，但我自己也常常忘記步驟……",
        archetype: "meek",
        retort: "你自己都不熟，還敢說要教我。",
      },
      {
        id: "dabo-education-029-f",
        text: "死一死，死老頭連設定都不會。",
        archetype: "landmine",
        retort: "幹，你這是要氣死我就對了！",
      },
      {
        id: "dabo-education-029-g",
        text: "笑死，你這麼願意學新東西很厲害耶。",
        archetype: "deflect",
        retort: "那當然，我也要跟上時代。",
      },
      {
        id: "dabo-education-029-h",
        text: "幹……好，但我教學可能不太有耐心……",
        archetype: "meek",
        retort: "沒耐心還敢說要教，太隨便了。",
      },
    ],
  },
  {
    id: "dabo-education-030",
    text: "聽說你轉過系，是不是選錯了。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-030-a",
        text: "機掰，老不死這輩子沒換過工作。",
        archetype: "landmine",
        retort: "白目喔你，欠罵是不是！",
      },
      {
        id: "dabo-education-030-b",
        text: "是有點後悔，浪費了一些時間……",
        archetype: "meek",
        retort: "浪費時間，那你當初怎麼不想清楚。",
      },
      {
        id: "dabo-education-030-c",
        text: "靠……轉系是有點衝動，沒辦法了……",
        archetype: "meek",
        retort: "衝動做決定，難怪現在辛苦。",
      },
      {
        id: "dabo-education-030-d",
        text: "你對人生選擇看得這麼透徹，佩服。",
        archetype: "deflect",
        retort: "那當然，我走過的路比你多。",
      },
      {
        id: "dabo-education-030-e",
        text: "哭爸，大伯你當年有沒有想過轉行？",
        archetype: "deflect",
        retort: "想過啊，但那時候不敢冒險。",
      },
      {
        id: "dabo-education-030-f",
        text: "去死，轉系而已人生本來就亂猜。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續滑手機）",
      },
      {
        id: "dabo-education-030-g",
        text: "機掰，我轉系是為了多修幾年美食。",
        archetype: "backfire",
        retort: "……白癡喔，修學校美食也算轉系。",
      },
      {
        id: "dabo-education-030-h",
        text: "去死，沒選錯，繞路總比原地打轉好。",
        archetype: "perfect",
        retort: "大伯母：這句我記下來了。",
      },
    ],
  },
  {
    id: "dabo-education-031",
    text: "現在大學生都在耍廢，你也是吧。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-031-a",
        text: "你對年輕人的觀察真的很細膩。",
        archetype: "deflect",
        retort: "那當然，我看得多了。",
      },
      {
        id: "dabo-education-031-b",
        text: "幹，耍廢是充電，充飽才受得了你問話。",
        archetype: "perfect",
        retort: "……（轉台，假裝找遙控器）",
      },
      {
        id: "dabo-education-031-c",
        text: "雞掰，耍廢是我專長比讀書拿手。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-031-d",
        text: "去死，老東西退休後躺著看電視。",
        archetype: "landmine",
        retort: "去你的，你這什麼態度！",
      },
      {
        id: "dabo-education-031-e",
        text: "去你的，我耍廢是為了跟時代脫節。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，換台去了）",
      },
      {
        id: "dabo-education-031-f",
        text: "笑死，大伯你退休後都怎麼安排時間？",
        archetype: "deflect",
        retort: "我啊，看電視也算是一種休息。",
      },
      {
        id: "dabo-education-031-g",
        text: "是有比較懶散，但也還是有在努力……",
        archetype: "meek",
        retort: "懶散還敢說努力，矛盾。",
      },
      {
        id: "dabo-education-031-h",
        text: "靠……我確實花不少時間在放鬆……",
        archetype: "meek",
        retort: "放鬆太多，難怪什麼都做不好。",
      },
    ],
  },
  {
    id: "dabo-education-032",
    text: "當初分數不夠，有沒有想過重考。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-032-a",
        text: "分數是不太理想，多少有點遺憾……",
        archetype: "meek",
        retort: "遺憾就要更努力彌補啊。",
      },
      {
        id: "dabo-education-032-b",
        text: "幹，老屁股以前成績也沒好到哪。",
        archetype: "landmine",
        retort: "幹你娘咧，這孩子太過分了！",
      },
      {
        id: "dabo-education-032-c",
        text: "你對這個議題想得真周到，謝謝關心。",
        archetype: "deflect",
        retort: "那當然，我也是為你好。",
      },
      {
        id: "dabo-education-032-d",
        text: "哭爸，大伯你當年考試壓力大嗎？",
        archetype: "deflect",
        retort: "大啊，那年代競爭也是很激烈。",
      },
      {
        id: "dabo-education-032-e",
        text: "幹……有想過，但重考壓力太大放棄了……",
        archetype: "meek",
        retort: "放棄，那你現在後悔也沒用了。",
      },
      {
        id: "dabo-education-032-f",
        text: "去死，重考不如重生投胎比較快。",
        archetype: "backfire",
        retort: "……（大伯愣住，轉頭問你媽）",
      },
      {
        id: "dabo-education-032-g",
        text: "機掰，我當初分數不夠是老師改錯。",
        archetype: "backfire",
        retort: "……（大伯沒理你，自顧自講電視）",
      },
      {
        id: "dabo-education-032-h",
        text: "他媽的，想過，但重考不如重新想想你的話。",
        archetype: "perfect",
        retort: "大伯母：對啦對啦，我也這樣說。",
      },
    ],
  },
  {
    id: "dabo-education-033",
    text: "這什麼英文書，看不懂還擺著。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-033-a",
        text: "幹，看得懂，比你電視字幕清楚多了。",
        archetype: "perfect",
        retort: "……（喝茶，不看你）",
      },
      {
        id: "dabo-education-033-b",
        text: "他媽的，這書拿來壓泡麵蓋子最實用。",
        archetype: "backfire",
        retort: "……（大伯搖搖頭，繼續看政論節目）",
      },
      {
        id: "dabo-education-033-c",
        text: "你注意到這個，眼力真的很好。",
        archetype: "deflect",
        retort: "那當然，我什麼都看得仔細。",
      },
      {
        id: "dabo-education-033-d",
        text: "去你的，英文書擺著比較有氣質裝飾。",
        archetype: "backfire",
        retort: "……白癡喔，裝飾也要看得懂字。",
      },
      {
        id: "dabo-education-033-e",
        text: "笑死，大伯你想學英文我教你單字。",
        archetype: "deflect",
        retort: "我才不學，年紀大記不住了。",
      },
      {
        id: "dabo-education-033-f",
        text: "去你的，死老頭連報紙都看不完。",
        archetype: "landmine",
        retort: "幹你娘咧，沒大沒小，欠教訓！",
      },
      {
        id: "dabo-education-033-g",
        text: "看得懂一部分，有些單字還要查……",
        archetype: "meek",
        retort: "要查才懂，那算什麼看得懂。",
      },
      {
        id: "dabo-education-033-h",
        text: "靠……其實我也常常看不太懂內容……",
        archetype: "meek",
        retort: "看不懂還買，錢真好花是不是。",
      },
    ],
  },
  {
    id: "dabo-education-034",
    text: "現在老師難當，你們讀書也不受教。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-034-a",
        text: "現在學生確實比較有自己的想法……",
        archetype: "meek",
        retort: "有想法不代表對，還是要尊師重道。",
      },
      {
        id: "dabo-education-034-b",
        text: "你對教育現場的觀察真的很敏銳。",
        archetype: "deflect",
        retort: "那當然，我電視新聞都有在看。",
      },
      {
        id: "dabo-education-034-c",
        text: "死一死，老師難當我推薦他改當網紅。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-034-d",
        text: "幹你娘，老番顛講話也沒多客氣。",
        archetype: "landmine",
        retort: "幹恁娘咧，見笑死了你！",
      },
      {
        id: "dabo-education-034-e",
        text: "幹……我以前也常常跟老師頂嘴……",
        archetype: "meek",
        retort: "頂嘴，難怪你現在講話這麼衝。",
      },
      {
        id: "dabo-education-034-f",
        text: "哭爸，大伯你以前遇過凶的老師嗎？",
        archetype: "deflect",
        retort: "有啊，那時候老師都很嚴格。",
      },
      {
        id: "dabo-education-034-g",
        text: "去死，我以前對老師最尊敬就是遲到。",
        archetype: "backfire",
        retort: "……（大伯哼一聲，喝茶不說話）",
      },
      {
        id: "dabo-education-034-h",
        text: "靠北，受教啊，我最聽勸除了你那套。",
        archetype: "perfect",
        retort: "……（大伯母憋笑，遞你雞腿）",
      },
    ],
  },
  {
    id: "dabo-education-035",
    text: "是不是找不到工作才去考研究所。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-035-a",
        text: "幹，不是逃避，是先充電再回來嗆你。",
        archetype: "perfect",
        retort: "……（把電視音量轉大蓋過去）",
      },
      {
        id: "dabo-education-035-b",
        text: "大伯你覺得考研究所值不值得？",
        archetype: "deflect",
        retort: "這個要看你自己想清楚啊。",
      },
      {
        id: "dabo-education-035-c",
        text: "笑死，你對就業市場觀察得真透徹。",
        archetype: "deflect",
        retort: "那當然，新聞都有在報。",
      },
      {
        id: "dabo-education-035-d",
        text: "機掰，老東西退休前也能拖就拖。",
        archetype: "landmine",
        retort: "幹，叫你爸出來，我跟他說！",
      },
      {
        id: "dabo-education-035-e",
        text: "他媽的，我讀研究所是想順便找對象。",
        archetype: "backfire",
        retort: "……白癡喔，找對象讀什麼研究所。",
      },
      {
        id: "dabo-education-035-f",
        text: "去你的，考研究所是為了多住宿舍。",
        archetype: "backfire",
        retort: "……（大伯沒接話，轉頭看電視）",
      },
      {
        id: "dabo-education-035-g",
        text: "確實工作不好找，才想多讀一點……",
        archetype: "meek",
        retort: "多讀一點，出來還不是一樣難找。",
      },
      {
        id: "dabo-education-035-h",
        text: "靠……是有想逃避一下沒錯，我承認……",
        archetype: "meek",
        retort: "逃避沒用，問題還是要面對。",
      },
    ],
  },
  {
    id: "dabo-education-036",
    text: "隔壁讀資工的年薪百萬，你呢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-036-a",
        text: "薪水是沒那麼高，但工作還算穩定……",
        archetype: "meek",
        retort: "穩定有什麼用，錢才是實際的。",
      },
      {
        id: "dabo-education-036-b",
        text: "靠北，我年薪不高但快樂指數破表。",
        archetype: "backfire",
        retort: "……（大伯愣了一下，沒接話）",
      },
      {
        id: "dabo-education-036-c",
        text: "你對薪資行情這麼清楚，佩服。",
        archetype: "deflect",
        retort: "那當然，我天天在關心這些。",
      },
      {
        id: "dabo-education-036-d",
        text: "哭爸，大伯你覺得什麼科系最好賺？",
        archetype: "deflect",
        retort: "這個要看時機，跟得上就好賺。",
      },
      {
        id: "dabo-education-036-e",
        text: "幹……確實差滿多的，我也有點壓力……",
        archetype: "meek",
        retort: "有壓力就要想辦法轉行啊。",
      },
      {
        id: "dabo-education-036-f",
        text: "去死，沒關係我打算轉行去挖礦。",
        archetype: "backfire",
        retort: "……（大伯皺眉，繼續轉台）",
      },
      {
        id: "dabo-education-036-g",
        text: "他媽的，老不死退休金也沒多少。",
        archetype: "landmine",
        retort: "去死，明年不用來了，聽到沒！",
      },
      {
        id: "dabo-education-036-h",
        text: "機掰，我呢，換算成快樂算是穩賺不賠。",
        archetype: "perfect",
        retort: "大伯母：講輸就別講了啦。",
      },
    ],
  },
  {
    id: "dabo-education-037",
    text: "你畢業紀念冊寫的志願，實現了嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-037-a",
        text: "去你的，實現了，志願是讓你今天無話可說。",
        archetype: "perfect",
        retort: "……（假裝滑手機，不接話）",
      },
      {
        id: "dabo-education-037-b",
        text: "幹你娘，我寫的志願是總統還沒實現。",
        archetype: "backfire",
        retort: "……（大伯瞄你一眼，喝口茶不說話）",
      },
      {
        id: "dabo-education-037-c",
        text: "去死，老東西以前志願也隨便寫。",
        archetype: "landmine",
        retort: "幹，你聽聽這是什麼鬼話！",
      },
      {
        id: "dabo-education-037-d",
        text: "你還記得志願這種細節，記性真好。",
        archetype: "deflect",
        retort: "那當然，我什麼都記得清清楚楚。",
      },
      {
        id: "dabo-education-037-e",
        text: "笑死，大伯你畢業紀念冊寫了什麼？",
        archetype: "deflect",
        retort: "我寫的是要當大老闆，哈哈。",
      },
      {
        id: "dabo-education-037-f",
        text: "去你的，我志願寫嫁豪門還在等機會。",
        archetype: "backfire",
        retort: "……（大伯瞪著電視，沒搭理你）",
      },
      {
        id: "dabo-education-037-g",
        text: "寫的跟現在做的差滿多的……",
        archetype: "meek",
        retort: "差這麼多，那你當初亂寫的喔。",
      },
      {
        id: "dabo-education-037-h",
        text: "靠……志願是有，但現實跟理想有落差……",
        archetype: "meek",
        retort: "有落差就要努力縮小，別放棄。",
      },
    ],
  },
] satisfies Question[];
