import type { Question } from "@/content/types";

// situations:
// 1. 看到你的畢業照
// 2. 問你讀哪個系
// 3. 聽到你講英文
// 4. 問你研究所讀假的
// 5. 看到你書架上的書
// 6. 問你會不會五十音／日文
// 7. 聊到他當年沒讀什麼書
// 8. 問你畢業論文寫什麼
// 9. 問你有沒有考公職
// 10. 看到你電腦上的證照
// 11. 問你學貸還完沒
// 12. 聊到補習班很貴
// 13. 問你會不會用試算表
// 14. 問人工智慧是不是要取代你
// 15. 聊到讀私立比較貴
// 16. 問你有沒有出國留過學
// 17. 看到你同學開了公司
// 18. 問你博士讀完要幹嘛
// 19. 聊到現在小孩補習太多
// 20. 問你大學社團在幹嘛

export default [
  {
    id: "dabo-education-001",
    text: "翻到你的畢業照，讀這麼多書喔。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-001-a",
        text: "讀是讀了不少，但也還在摸索……",
        archetype: "meek",
        retort: "摸索什麼，年紀都不小了。",
      },
      {
        id: "dabo-education-001-b",
        text: "你對讀書這件事看得真透徹。",
        archetype: "deflect",
        retort: "這叫人生經驗，你們要聽。",
      },
      {
        id: "dabo-education-001-c",
        text: "畢業證書我拿去當扇子搧涼。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒說話）",
      },
      {
        id: "dabo-education-001-d",
        text: "畢業後才發現學的用不太到……",
        archetype: "meek",
        retort: "用不到還讀，浪費時間跟錢。",
      },
      {
        id: "dabo-education-001-e",
        text: "你年輕時也沒讀什麼書吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-001-f",
        text: "大伯你當年畢業照拍得帥不帥？",
        archetype: "deflect",
        retort: "那當然，我可是校草等級。",
      },
      {
        id: "dabo-education-001-g",
        text: "讀書多沒用，我打算靠臉吃飯。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續翻照片）",
      },
      {
        id: "dabo-education-001-h",
        text: "讀多讀少，反正紅包一樣要包。",
        archetype: "perfect",
        retort: "……有點道理，你倒是會抓重點。",
      },
    ],
  },
  {
    id: "dabo-education-002",
    text: "你大學讀什麼系？畢業能幹嘛。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-002-a",
        text: "我讀的系聽起來很潮，其實我也不懂。",
        archetype: "backfire",
        retort: "……（大伯皺眉，沒接話）",
      },
      {
        id: "dabo-education-002-b",
        text: "你以前也沒機會選，別替我惋惜。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-002-c",
        text: "讀的系不重要，能養活自己最重要。",
        archetype: "perfect",
        retort: "……有點道理，這樣講也對。",
      },
      {
        id: "dabo-education-002-d",
        text: "我讀的系畢業就是要當老闆的。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續追問）",
      },
      {
        id: "dabo-education-002-e",
        text: "讀的是……冷門一點的科系……",
        archetype: "meek",
        retort: "冷門的話以後怎麼找工作。",
      },
      {
        id: "dabo-education-002-f",
        text: "大伯你以前想讀什麼系？",
        archetype: "deflect",
        retort: "我想讀醫科，可惜沒機會。",
      },
      {
        id: "dabo-education-002-g",
        text: "你對選系這件事很有想法耶。",
        archetype: "deflect",
        retort: "那當然，我人生閱歷豐富。",
      },
      {
        id: "dabo-education-002-h",
        text: "讀的跟現在做的沒什麼關係……",
        archetype: "meek",
        retort: "沒關係那讀那個系幹嘛。",
      },
    ],
  },
  {
    id: "dabo-education-003",
    text: "你剛剛講的英文，什麼意思啊。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-003-a",
        text: "對不起，我不小心夾雜著講……",
        archetype: "meek",
        retort: "不小心？在家講中文才是規矩。",
      },
      {
        id: "dabo-education-003-b",
        text: "意思是大伯你今天特別帥啦。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-003-c",
        text: "意思是你講的話我也常常聽不懂。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-003-d",
        text: "你猜猜看，猜對算你厲害。",
        archetype: "deflect",
        retort: "這個嘛……我猜是罵人的話。",
      },
      {
        id: "dabo-education-003-e",
        text: "就工作上常用的詞，習慣了……",
        archetype: "meek",
        retort: "習慣講英文，講中文是不會喔。",
      },
      {
        id: "dabo-education-003-f",
        text: "意思是新年快樂，祝你長命百歲。",
        archetype: "perfect",
        retort: "……有點道理，這句我聽得懂。",
      },
      {
        id: "dabo-education-003-g",
        text: "這是密語，只有懂的人才懂啦。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-education-003-h",
        text: "大伯你想學英文嗎？我教你。",
        archetype: "deflect",
        retort: "我才不學，我聽電視就夠了。",
      },
    ],
  },
  {
    id: "dabo-education-004",
    text: "讀那什麼碩士，出來還不是領死薪水。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-004-a",
        text: "死薪水沒關係，活得開心比較重要。",
        archetype: "perfect",
        retort: "……有點道理，開心最重要。",
      },
      {
        id: "dabo-education-004-b",
        text: "薪水是沒差很多，但學到不少東西……",
        archetype: "meek",
        retort: "學到東西又不能拿來吃。",
      },
      {
        id: "dabo-education-004-c",
        text: "碩士學位我拿來墊桌角剛剛好。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-004-d",
        text: "你薪水也沒比我碩士同學高多少。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-004-e",
        text: "大伯你當年有機會讀碩士嗎？",
        archetype: "deflect",
        retort: "沒有啊，那時候哪有這種機會。",
      },
      {
        id: "dabo-education-004-f",
        text: "確實加薪沒想像中多……",
        archetype: "meek",
        retort: "沒想像中多，那讀那麼久幹嘛。",
      },
      {
        id: "dabo-education-004-g",
        text: "你對學歷跟薪水的關係看得很準。",
        archetype: "deflect",
        retort: "這叫社會經驗，你們還不懂。",
      },
      {
        id: "dabo-education-004-h",
        text: "讀碩士是為了多兩年學生證優惠。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
    ],
  },
  {
    id: "dabo-education-005",
    text: "你這些書都看完了？看得懂嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-005-a",
        text: "你對書的品味這麼講究，佩服。",
        archetype: "deflect",
        retort: "那當然，我年輕時也很愛看。",
      },
      {
        id: "dabo-education-005-b",
        text: "看完了，比電視上那個有深度多了。",
        archetype: "perfect",
        retort: "……有點道理，你倒是敢講。",
      },
      {
        id: "dabo-education-005-c",
        text: "你家電視櫃上也沒幾本書吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-005-d",
        text: "這些書我都拿來當泡麵蓋子。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續翻書）",
      },
      {
        id: "dabo-education-005-e",
        text: "有些看到一半就放棄了……",
        archetype: "meek",
        retort: "放棄還擺著，裝樣子而已。",
      },
      {
        id: "dabo-education-005-f",
        text: "看完是看完，但記得的不多……",
        archetype: "meek",
        retort: "記不住還看，浪費眼力。",
      },
      {
        id: "dabo-education-005-g",
        text: "我看書是為了跟書拍照發限動。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-005-h",
        text: "大伯你以前愛看什麼書？",
        archetype: "deflect",
        retort: "武俠小說啊，看了不下百遍。",
      },
    ],
  },
  {
    id: "dabo-education-006",
    text: "你讀那麼多書，會講日文嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-006-a",
        text: "會一點點，但不太流利……",
        archetype: "meek",
        retort: "不流利還敢說會，太自滿了。",
      },
      {
        id: "dabo-education-006-b",
        text: "你連中文成語都用錯還敢問我。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-006-c",
        text: "大伯你想學日文嗎，我教你。",
        archetype: "deflect",
        retort: "我才不學，太麻煩了。",
      },
      {
        id: "dabo-education-006-d",
        text: "會一點，夠跟電視上那個吵架。",
        archetype: "perfect",
        retort: "……有點道理，你這梗有意思。",
      },
      {
        id: "dabo-education-006-e",
        text: "讀是讀了，但都忘光了……",
        archetype: "meek",
        retort: "忘光了，那讀書錢都白花了。",
      },
      {
        id: "dabo-education-006-f",
        text: "我讀的書都是漫畫版日文啦。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-006-g",
        text: "你猜猜看我會講幾句，考考我。",
        archetype: "deflect",
        retort: "這個我可考不倒你啦。",
      },
      {
        id: "dabo-education-006-h",
        text: "我日文只會說歐嗨唷，很夠用。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
    ],
  },
  {
    id: "dabo-education-007",
    text: "我書讀得少，還不是照樣打拚。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-007-a",
        text: "打拚最重要，讀書只是加分而已。",
        archetype: "perfect",
        retort: "……有點道理，算你懂我意思。",
      },
      {
        id: "dabo-education-007-b",
        text: "你打拚那麼久，現在還不是在看電視。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-007-c",
        text: "我也覺得經驗有時候比學歷重要……",
        archetype: "meek",
        retort: "知道就好，早點學我就對了。",
      },
      {
        id: "dabo-education-007-d",
        text: "讀書少沒關係，看電視也算學習。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
      {
        id: "dabo-education-007-e",
        text: "我讀比較多，但沒你有經驗……",
        archetype: "meek",
        retort: "沒經驗還敢說讀書有用。",
      },
      {
        id: "dabo-education-007-f",
        text: "你這種毅力，比讀書更難得。",
        archetype: "deflect",
        retort: "那當然，我可是苦過來的。",
      },
      {
        id: "dabo-education-007-g",
        text: "打拚跟讀書一樣累啦，半斤八兩。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-007-h",
        text: "大伯你打拚的故事，我很想聽。",
        archetype: "deflect",
        retort: "好，那我從頭跟你講起。",
      },
    ],
  },
  {
    id: "dabo-education-008",
    text: "你論文寫什麼題目？聽起來很難。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-008-a",
        text: "你這麼問，是想寫論文嗎？",
        archetype: "deflect",
        retort: "我才不要，光聽就頭痛。",
      },
      {
        id: "dabo-education-008-b",
        text: "寫是寫完了，但自己也忘得差不多……",
        archetype: "meek",
        retort: "忘光了，那寫這個幹嘛。",
      },
      {
        id: "dabo-education-008-c",
        text: "你連論文兩個字的意思都搞不懂吧。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-008-d",
        text: "難是難，但至少比追劇有意義。",
        archetype: "perfect",
        retort: "……有點道理，算你有志氣。",
      },
      {
        id: "dabo-education-008-e",
        text: "大伯你猜猜看我寫什麼題目。",
        archetype: "deflect",
        retort: "這個我可猜不出來，太深了。",
      },
      {
        id: "dabo-education-008-f",
        text: "我的論文比電話簿還厚，很有份量。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-008-g",
        text: "題目有點冷門，講了你可能不懂……",
        archetype: "meek",
        retort: "不懂就別寫，浪費時間。",
      },
      {
        id: "dabo-education-008-h",
        text: "我論文題目其實是複製貼上大全。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
    ],
  },
  {
    id: "dabo-education-009",
    text: "讀這麼多書，怎麼不去考公職。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-009-a",
        text: "你對考公職這麼推崇，一定很了解。",
        archetype: "deflect",
        retort: "那當然，這是鐵飯碗啊。",
      },
      {
        id: "dabo-education-009-b",
        text: "考過一次沒上，就沒再試了……",
        archetype: "meek",
        retort: "沒上就放棄，這樣太沒毅力了。",
      },
      {
        id: "dabo-education-009-c",
        text: "有考慮過，但一直沒準備好……",
        archetype: "meek",
        retort: "沒準備好，時間都花去哪了。",
      },
      {
        id: "dabo-education-009-d",
        text: "考公職要看緣分，我比較隨緣。",
        archetype: "perfect",
        retort: "……有點道理，隨緣也是一種智慧。",
      },
      {
        id: "dabo-education-009-e",
        text: "我考慮直接應徵當你們家女婿。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-009-f",
        text: "你自己上班那幾年也沒多穩定吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-009-g",
        text: "公職太穩定，我比較愛刺激的人生。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-009-h",
        text: "大伯你覺得考公職難不難？",
        archetype: "deflect",
        retort: "難啊，我以前也考慮過。",
      },
    ],
  },
  {
    id: "dabo-education-010",
    text: "你這些證照，考來到底有沒有用。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-010-a",
        text: "用得上的沒幾張，其他都放著……",
        archetype: "meek",
        retort: "放著也是浪費，早知道別考。",
      },
      {
        id: "dabo-education-010-b",
        text: "你這麼問，是想考證照增值嗎？",
        archetype: "deflect",
        retort: "我才不要，年紀大了讀不動了。",
      },
      {
        id: "dabo-education-010-c",
        text: "你退休前的技能現在也都用不上了。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-010-d",
        text: "證照多不代表什麼，帥才是王道。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-010-e",
        text: "有用啊，至少證明我書沒白讀。",
        archetype: "perfect",
        retort: "……有點道理，算你有實力。",
      },
      {
        id: "dabo-education-010-f",
        text: "大伯你以前有考過什麼證照嗎？",
        archetype: "deflect",
        retort: "我啊，考過駕照就很厲害了。",
      },
      {
        id: "dabo-education-010-g",
        text: "有些考了但沒真的用到……",
        archetype: "meek",
        retort: "沒用到，那考來幹嘛，浪費錢。",
      },
      {
        id: "dabo-education-010-h",
        text: "這些證照我拿來當書籤剛剛好。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續翻）",
      },
    ],
  },
  {
    id: "dabo-education-011",
    text: "你學貸還完沒？讀書讀成負債。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-011-a",
        text: "你以前買房的貸款不也還了一輩子。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-011-b",
        text: "還沒還完，壓力其實不小……",
        archetype: "meek",
        retort: "壓力大就要更努力賺錢啊。",
      },
      {
        id: "dabo-education-011-c",
        text: "你對這個議題這麼關心，感動。",
        archetype: "deflect",
        retort: "那當然，我也是關心你的未來。",
      },
      {
        id: "dabo-education-011-d",
        text: "學貸還不完，我打算嫁給有錢人。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-011-e",
        text: "還在還，每個月扣一點點……",
        archetype: "meek",
        retort: "扣一點點還要扣多久，真辛苦。",
      },
      {
        id: "dabo-education-011-f",
        text: "我把學貸當健身，越還越有肌肉。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-education-011-g",
        text: "還完了，用知識換來的債最值得。",
        archetype: "perfect",
        retort: "……有點道理，你想得挺開。",
      },
      {
        id: "dabo-education-011-h",
        text: "大伯你們那個年代有學貸嗎？",
        archetype: "deflect",
        retort: "沒有啊，那時候讀書便宜多了。",
      },
    ],
  },
  {
    id: "dabo-education-012",
    text: "現在補習班這麼貴，讀書真燒錢。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-012-a",
        text: "你對教育成本這麼有概念，厲害。",
        archetype: "deflect",
        retort: "那當然，我也是有在關心時事。",
      },
      {
        id: "dabo-education-012-b",
        text: "大伯你那時候有補習過嗎？",
        archetype: "deflect",
        retort: "沒有啊，我都自己看書。",
      },
      {
        id: "dabo-education-012-c",
        text: "燒錢歸燒錢，總比燒紙錢實在。",
        archetype: "perfect",
        retort: "……有點道理，算你會比喻。",
      },
      {
        id: "dabo-education-012-d",
        text: "補習有幫助，但確實負擔很大……",
        archetype: "meek",
        retort: "負擔大還要補，真是苦了你爸媽。",
      },
      {
        id: "dabo-education-012-e",
        text: "你們那年代不用補習是因為根本沒得補。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-012-f",
        text: "補習班很貴，那我改自學當網紅。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-012-g",
        text: "我以前補習真的花不少錢……",
        archetype: "meek",
        retort: "花這麼多錢，成績有好到哪嗎。",
      },
      {
        id: "dabo-education-012-h",
        text: "補習費夠我吃一年雞排了，划算。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-education-013",
    text: "你們讀書讀那麼多，會用試算表吧。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-013-a",
        text: "試算表我都用來記錄追劇進度。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-013-b",
        text: "大伯你想學嗎？我教你用試算表。",
        archetype: "deflect",
        retort: "我才不學，手寫比較習慣。",
      },
      {
        id: "dabo-education-013-c",
        text: "我比較擅長用計算機，比較潮。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-013-d",
        text: "會用一點，但不算很熟練……",
        archetype: "meek",
        retort: "不熟練還敢說會用，太心虛了。",
      },
      {
        id: "dabo-education-013-e",
        text: "你連手機都不太會用還敢問我。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-013-f",
        text: "公司要求才學的，其實不太行……",
        archetype: "meek",
        retort: "不太行還能上班，公司也真敢用你。",
      },
      {
        id: "dabo-education-013-g",
        text: "會啊，我連你的存摺都能幫你算。",
        archetype: "perfect",
        retort: "……有點道理，改天真要你幫忙。",
      },
      {
        id: "dabo-education-013-h",
        text: "你對這些工具的重要性很有概念。",
        archetype: "deflect",
        retort: "那當然，我也懂一點時代趨勢。",
      },
    ],
  },
  {
    id: "dabo-education-014",
    text: "聽說人工智慧要取代你，緊張嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-014-a",
        text: "你退休前的工作現在也被淘汰了。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-014-b",
        text: "緊張啊，所以我先把大伯取代了。",
        archetype: "perfect",
        retort: "……有點道理，你這梗我聽懂了。",
      },
      {
        id: "dabo-education-014-c",
        text: "沒關係，機器人也需要人指揮。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-014-d",
        text: "你對這個議題想得真深，佩服。",
        archetype: "deflect",
        retort: "那當然，我看新聞都在報這個。",
      },
      {
        id: "dabo-education-014-e",
        text: "大伯你會怕被智慧型手機取代嗎？",
        archetype: "deflect",
        retort: "我才不怕，我只看電視。",
      },
      {
        id: "dabo-education-014-f",
        text: "是有點緊張，工作可能會被影響……",
        archetype: "meek",
        retort: "緊張就要多學別的技能啊。",
      },
      {
        id: "dabo-education-014-g",
        text: "我也不太確定會不會被取代……",
        archetype: "meek",
        retort: "不確定就要提早準備，別到時候慘。",
      },
      {
        id: "dabo-education-014-h",
        text: "如果我被取代，那我改行當網紅。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-education-015",
    text: "讀私立那麼貴，你爸媽真辛苦。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-015-a",
        text: "大伯你當年有機會讀私立嗎？",
        archetype: "deflect",
        retort: "沒有啊，那時候哪有這種選擇。",
      },
      {
        id: "dabo-education-015-b",
        text: "確實花不少錢，我也覺得有點虧欠……",
        archetype: "meek",
        retort: "虧欠就要好好孝順回報。",
      },
      {
        id: "dabo-education-015-c",
        text: "私立貴沒關係，反正學費不是我出。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
      {
        id: "dabo-education-015-d",
        text: "是有點貴，我爸媽也咬牙撐過來……",
        archetype: "meek",
        retort: "咬牙撐，那你更該懂得感恩。",
      },
      {
        id: "dabo-education-015-e",
        text: "讀私立比較貴，但制服比較好看。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-015-f",
        text: "你自己的孩子還不是讀最貴的私校。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-015-g",
        text: "辛苦歸辛苦，至少我沒讓他們丟臉。",
        archetype: "perfect",
        retort: "……有點道理，算你孝順。",
      },
      {
        id: "dabo-education-015-h",
        text: "你對學費這麼清楚，真的很關心我。",
        archetype: "deflect",
        retort: "那當然，我也是一直在關心你。",
      },
    ],
  },
  {
    id: "dabo-education-016",
    text: "你有出國留學過嗎？見過世面沒。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-016-a",
        text: "你這輩子也沒出過國吧。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-016-b",
        text: "沒有耶，家裡經濟沒那個條件……",
        archetype: "meek",
        retort: "沒條件也要想辦法，不然一直落後。",
      },
      {
        id: "dabo-education-016-c",
        text: "你對出國見世面這麼看重，真開明。",
        archetype: "deflect",
        retort: "那當然，見識廣才有出息。",
      },
      {
        id: "dabo-education-016-d",
        text: "大伯你想出國玩嗎？我幫你規劃。",
        archetype: "deflect",
        retort: "我才不要，語言不通麻煩死了。",
      },
      {
        id: "dabo-education-016-e",
        text: "我出國過，去過機場免稅店。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-016-f",
        text: "見過啊，最遠見到大伯的政論台世界。",
        archetype: "perfect",
        retort: "……有點道理，這梗我服了。",
      },
      {
        id: "dabo-education-016-g",
        text: "有想過，但一直沒存到錢……",
        archetype: "meek",
        retort: "存不到錢，那你錢都花去哪了。",
      },
      {
        id: "dabo-education-016-h",
        text: "我留學經驗豐富，都是靠地圖軟體。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-education-017",
    text: "你同學都當老闆了，你還在打工。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-017-a",
        text: "我也想過創業，但沒那個勇氣……",
        archetype: "meek",
        retort: "沒勇氣就一直打工，這樣行嗎。",
      },
      {
        id: "dabo-education-017-b",
        text: "你以前也沒當過老闆還敢說我。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-017-c",
        text: "我打算靠同學的公司蹭紅利。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-017-d",
        text: "確實壓力有點大，看到同學都比較好……",
        archetype: "meek",
        retort: "壓力大就要想辦法突破啊。",
      },
      {
        id: "dabo-education-017-e",
        text: "打工也好，至少我不用背債。",
        archetype: "perfect",
        retort: "……有點道理，你想得倒是開。",
      },
      {
        id: "dabo-education-017-f",
        text: "我打工是為了臥底學經驗，深謀遠慮。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-017-g",
        text: "大伯你以前有想過創業嗎？",
        archetype: "deflect",
        retort: "想過啊，可惜沒本錢。",
      },
      {
        id: "dabo-education-017-h",
        text: "你對創業這件事看得真透徹。",
        archetype: "deflect",
        retort: "那當然，我看過太多失敗案例。",
      },
    ],
  },
  {
    id: "dabo-education-018",
    text: "博士讀完打算幹嘛？該找工作了吧。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-018-a",
        text: "你對未來規劃這麼關心，我很感動。",
        archetype: "deflect",
        retort: "那當然，我也希望你有出息。",
      },
      {
        id: "dabo-education-018-b",
        text: "找工作啊，先從說服大伯開始。",
        archetype: "perfect",
        retort: "……有點道理，算你會抓時機。",
      },
      {
        id: "dabo-education-018-c",
        text: "讀完博士，我打算改行賣雞排。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-018-d",
        text: "大伯你覺得博士適合做什麼工作？",
        archetype: "deflect",
        retort: "這個我可不懂，你自己想。",
      },
      {
        id: "dabo-education-018-e",
        text: "還在想，可能會繼續做研究……",
        archetype: "meek",
        retort: "做研究賺得到錢嗎，別想太美。",
      },
      {
        id: "dabo-education-018-f",
        text: "你連博士兩個字怎麼寫都不確定吧。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-018-g",
        text: "其實我也還沒有明確方向……",
        archetype: "meek",
        retort: "讀那麼久還沒方向，白讀了。",
      },
      {
        id: "dabo-education-018-h",
        text: "博士學位拿來嚇唬相親對象最有用。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-education-019",
    text: "現在小孩補習補成這樣，太誇張了。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-019-a",
        text: "誇張，但至少他們有選擇的機會。",
        archetype: "perfect",
        retort: "……有點道理，這樣想也對。",
      },
      {
        id: "dabo-education-019-b",
        text: "補這麼多真的壓力很大……",
        archetype: "meek",
        retort: "壓力大就要撐過去，這是必經之路。",
      },
      {
        id: "dabo-education-019-c",
        text: "你孫子補成這樣還不是你逼的。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-education-019-d",
        text: "小孩補習補太多，長大都變補習班老師。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-education-019-e",
        text: "我以前也補習補很多，蠻累的……",
        archetype: "meek",
        retort: "累還不是為了你好，別抱怨。",
      },
      {
        id: "dabo-education-019-f",
        text: "補習補成這樣，我建議直接住補習班。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-education-019-g",
        text: "大伯你覺得補習該補到幾歲比較好？",
        archetype: "deflect",
        retort: "我看啊，補到能自己賺錢為止。",
      },
      {
        id: "dabo-education-019-h",
        text: "你對教育制度這麼有想法，佩服。",
        archetype: "deflect",
        retort: "那當然，我也是關心下一代。",
      },
    ],
  },
  {
    id: "dabo-education-020",
    text: "你大學參加什麼社團？有用嗎。",
    topic: "education",
    bossId: "dabo",
    options: [
      {
        id: "dabo-education-020-a",
        text: "你對大學生活這麼好奇，我很開心。",
        archetype: "deflect",
        retort: "那當然，我也想了解你的世界。",
      },
      {
        id: "dabo-education-020-b",
        text: "參加是參加，但沒學到什麼實際的……",
        archetype: "meek",
        retort: "沒學到東西，那參加幹嘛。",
      },
      {
        id: "dabo-education-020-c",
        text: "你當年應該也沒參加過什麼正經活動。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-education-020-d",
        text: "大伯你當年有參加什麼活動嗎？",
        archetype: "deflect",
        retort: "有啊，我可是風雲人物。",
      },
      {
        id: "dabo-education-020-e",
        text: "有用啊，學會怎麼跟長輩尬聊。",
        archetype: "perfect",
        retort: "……有點道理，算你會用。",
      },
      {
        id: "dabo-education-020-f",
        text: "我參加的社團專門研究怎麼耍廢。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-education-020-g",
        text: "就交交朋友而已，沒特別的收穫……",
        archetype: "meek",
        retort: "沒收穫，浪費時間跟學費。",
      },
      {
        id: "dabo-education-020-h",
        text: "我加入的社團宗旨是準時吃飯。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
] satisfies Question[];
