import type { Question } from "@/content/types";

// situations:
// 1. 轉台到政論台問你要不要一起看
// 2. 電視新聞在報房價又漲
// 3. 早報頭版寫著缺工缺蛋
// 4. 大伯滑到你分享的政治梗圖
// 5. 選舉開票夜守著電視
// 6. 問你有沒有去投票
// 7. 里長發福利品經過巷口
// 8. 議員競選車經過放歌
// 9. 大伯轉貼一則不明LINE新聞給你
// 10. 加油站看到油價又漲跟你抱怨
// 11. 全聯結帳時比價念物價
// 12. 電費帳單來了念一次
// 13. 便當店漲價
// 14. 台股大跌新聞跑馬燈
// 15. 罷工新聞
// 16. 公投連署單塞給你簽
// 17. 名嘴在節目上吵架
// 18. 問你相不相信新聞
// 19. 說對面那個又如何如何（兩岸新聞）
// 20. 大伯自己去投票要你載他

export default [
  {
    id: "dabo-politics-001",
    text: "轉到這台，電視上那個又在鬼扯了。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-001-a",
        text: "我最近比較少看新聞……",
        archetype: "meek",
        retort: "難怪你都不懂社會在幹嘛。",
      },
      {
        id: "dabo-politics-001-b",
        text: "你分析得比新聞台還準，服了。",
        archetype: "deflect",
        retort: "哎唷，這是基本常識啦。",
      },
      {
        id: "dabo-politics-001-c",
        text: "大伯你要不要乾脆去選一個？",
        archetype: "backfire",
        retort: "……（大伯愣住，喝了口茶沒回話）",
      },
      {
        id: "dabo-politics-001-d",
        text: "我手機都看不同的說法，有點亂……",
        archetype: "meek",
        retort: "亂就對了，你要學會分辨。",
      },
      {
        id: "dabo-politics-001-e",
        text: "你不就整天窩在電視前面而已嗎？",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-001-f",
        text: "大伯你看這麼久，眼睛不會酸嗎？",
        archetype: "deflect",
        retort: "酸是酸，但真相比較重要。",
      },
      {
        id: "dabo-politics-001-g",
        text: "我覺得電視裡的人比連續劇還精彩。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續轉台）",
      },
      {
        id: "dabo-politics-001-h",
        text: "你先講重點，我聽完幫你抓漏洞。",
        archetype: "perfect",
        retort: "……有點道理，你去倒茶。",
      },
    ],
  },
  {
    id: "dabo-politics-002",
    text: "新聞說房價又漲，你們年輕人慘了。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-002-a",
        text: "房價漲，我心臟也跟著漲。",
        archetype: "backfire",
        retort: "……（大伯皺眉，轉頭問別人聽不聽得懂）",
      },
      {
        id: "dabo-politics-002-b",
        text: "你那間房不也是阿公留的？",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-002-c",
        text: "慘什麼，反正我也買不起，輕鬆。",
        archetype: "perfect",
        retort: "……有點道理，這樣想也是一種本事。",
      },
      {
        id: "dabo-politics-002-d",
        text: "沒關係，我打算用信用卡買房。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看新聞）",
      },
      {
        id: "dabo-politics-002-e",
        text: "我知道啊……存頭期款很難……",
        archetype: "meek",
        retort: "難就要更努力存啊。",
      },
      {
        id: "dabo-politics-002-f",
        text: "大伯你當年薪水買房划算多少？",
        archetype: "deflect",
        retort: "划算是划算，但也是辛苦存的。",
      },
      {
        id: "dabo-politics-002-g",
        text: "房價的事，你比理財專家還懂。",
        archetype: "deflect",
        retort: "那當然，我看新聞看幾十年了。",
      },
      {
        id: "dabo-politics-002-h",
        text: "有在看房，但都買不起……",
        archetype: "meek",
        retort: "看看就好，別想太多。",
      },
    ],
  },
  {
    id: "dabo-politics-003",
    text: "報紙說缺工又缺蛋，什麼世道。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-003-a",
        text: "工作也不好找，公司都在縮編……",
        archetype: "meek",
        retort: "縮編就要更拚啊，不然呢。",
      },
      {
        id: "dabo-politics-003-b",
        text: "沒蛋沒關係，我改吃蛋黃酥。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續翻報紙）",
      },
      {
        id: "dabo-politics-003-c",
        text: "你上次不是說要退休不做了？",
        archetype: "landmine",
        retort: "你亂講什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-003-d",
        text: "你分析得比農委會官員還細。",
        archetype: "deflect",
        retort: "那當然，我看新聞的啦。",
      },
      {
        id: "dabo-politics-003-e",
        text: "最近雞蛋真的比較難買……",
        archetype: "meek",
        retort: "難買你就少吃一點啊。",
      },
      {
        id: "dabo-politics-003-f",
        text: "缺蛋沒關係，反正我不太吃早餐。",
        archetype: "perfect",
        retort: "……有點道理，年輕人都這樣。",
      },
      {
        id: "dabo-politics-003-g",
        text: "缺工的話，我去應徵好了。",
        archetype: "backfire",
        retort: "……（大伯看你一眼，沒說話）",
      },
      {
        id: "dabo-politics-003-h",
        text: "大伯你那個年代缺什麼比較多？",
        archetype: "deflect",
        retort: "我們那個年代缺的是機會啦。",
      },
    ],
  },
  {
    id: "dabo-politics-004",
    text: "你臉書分享的那個，什麼意思？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-004-a",
        text: "意思是笑一笑就好，別想太多。",
        archetype: "perfect",
        retort: "……有點道理，你們年輕人會玩。",
      },
      {
        id: "dabo-politics-004-b",
        text: "就一個玩笑而已，別當真……",
        archetype: "meek",
        retort: "玩笑也要有分寸啊。",
      },
      {
        id: "dabo-politics-004-c",
        text: "意思是政治很好笑啊，哈哈。",
        archetype: "backfire",
        retort: "……（大伯沒笑，喝了口茶）",
      },
      {
        id: "dabo-politics-004-d",
        text: "你自己看的新聞都嘛不查證。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽這孩子！",
      },
      {
        id: "dabo-politics-004-e",
        text: "大伯你也想學嗎？我教你用臉書。",
        archetype: "deflect",
        retort: "我才不要，你們亂七八糟的。",
      },
      {
        id: "dabo-politics-004-f",
        text: "我也不確定意思，隨手轉發的……",
        archetype: "meek",
        retort: "隨手轉發？你都不查證的喔。",
      },
      {
        id: "dabo-politics-004-g",
        text: "大伯你先說說你當年怎麼罵人。",
        archetype: "deflect",
        retort: "我們那時候用嘴巴罵，直接。",
      },
      {
        id: "dabo-politics-004-h",
        text: "意思是我很有幽默感啦。",
        archetype: "backfire",
        retort: "……（大伯滑掉，沒再追問）",
      },
    ],
  },
  {
    id: "dabo-politics-005",
    text: "開票開到現在，你都沒在關心？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-005-a",
        text: "開票結果你比里長還清楚。",
        archetype: "deflect",
        retort: "那當然，這叫關心地方。",
      },
      {
        id: "dabo-politics-005-b",
        text: "我關心的是明天要不要放假。",
        archetype: "perfect",
        retort: "……有點道理，我也想放假。",
      },
      {
        id: "dabo-politics-005-c",
        text: "你每次熬夜看，隔天還不是照睡到中午？",
        archetype: "landmine",
        retort: "你亂講什麼！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-005-d",
        text: "我等等要看晚間新聞的重播。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續盯電視）",
      },
      {
        id: "dabo-politics-005-e",
        text: "太晚了想睡，沒撐到最後……",
        archetype: "meek",
        retort: "這麼沒毅力，難怪什麼都做不成。",
      },
      {
        id: "dabo-politics-005-f",
        text: "我有看一下，但看不太懂……",
        archetype: "meek",
        retort: "不懂就要多學，不然被騙都不知道。",
      },
      {
        id: "dabo-politics-005-g",
        text: "開票跟看球賽一樣刺激啦。",
        archetype: "backfire",
        retort: "……（大伯瞪你一眼，沒接話）",
      },
      {
        id: "dabo-politics-005-h",
        text: "大伯你都熬夜看，精神真好。",
        archetype: "deflect",
        retort: "這個要看啊，不然明天沒話題。",
      },
    ],
  },
  {
    id: "dabo-politics-006",
    text: "你今天有去投票嗎？沒去很糟糕。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-006-a",
        text: "有去啦，但排隊排好久……",
        archetype: "meek",
        retort: "排隊而已就喊累，年輕人喔。",
      },
      {
        id: "dabo-politics-006-b",
        text: "你每次投完不都在抱怨結果？",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-006-c",
        text: "大伯你都投給誰，教教我判斷。",
        archetype: "deflect",
        retort: "這個要自己判斷，我不能講。",
      },
      {
        id: "dabo-politics-006-d",
        text: "有啊，投完還順便買了雞排。",
        archetype: "perfect",
        retort: "……有點道理，公民責任要做好。",
      },
      {
        id: "dabo-politics-006-e",
        text: "忘記了……工作太忙沒注意。",
        archetype: "meek",
        retort: "這麼重要的事都能忘，真的服了。",
      },
      {
        id: "dabo-politics-006-f",
        text: "我棄權，因為選票太重不好拿。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-politics-006-g",
        text: "你這麼關心，應該去選里長。",
        archetype: "deflect",
        retort: "我才不要，太麻煩了。",
      },
      {
        id: "dabo-politics-006-h",
        text: "我投給我自己比較實在。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看電視）",
      },
    ],
  },
  {
    id: "dabo-politics-007",
    text: "里長發衛生紙了，你怎麼沒去領？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-007-a",
        text: "領了啊，我特地留一份給你們。",
        archetype: "perfect",
        retort: "……有點道理，還算孝順。",
      },
      {
        id: "dabo-politics-007-b",
        text: "你不就是想去跟里長聊八卦？",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-007-c",
        text: "不知道有這件事，錯過了……",
        archetype: "meek",
        retort: "消息這麼慢，難怪什麼都吃虧。",
      },
      {
        id: "dabo-politics-007-d",
        text: "衛生紙而已，我上網買比較快。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
      {
        id: "dabo-politics-007-e",
        text: "我上班沒空去排隊領……",
        archetype: "meek",
        retort: "沒空領免費的？年輕人真忙。",
      },
      {
        id: "dabo-politics-007-f",
        text: "里長送的東西，你研究得真透徹。",
        archetype: "deflect",
        retort: "這叫社區情報，要跟上。",
      },
      {
        id: "dabo-politics-007-g",
        text: "我等下次選舉再一次領夠本。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒說話）",
      },
      {
        id: "dabo-politics-007-h",
        text: "大伯你人面廣，介紹我認識里長。",
        archetype: "deflect",
        retort: "這個簡單，改天帶你去。",
      },
    ],
  },
  {
    id: "dabo-politics-008",
    text: "外面競選車經過，你聽到了沒？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-008-a",
        text: "這種細節你都注意到，厲害。",
        archetype: "deflect",
        retort: "這叫觀察力，你們要學。",
      },
      {
        id: "dabo-politics-008-b",
        text: "耳機戴著，沒聽清楚……",
        archetype: "meek",
        retort: "整天戴耳機，難怪不食人間煙火。",
      },
      {
        id: "dabo-politics-008-c",
        text: "你每次都跟著車尾巴喊凍蒜。",
        archetype: "landmine",
        retort: "你亂講什麼！大伯母，你聽這孩子！",
      },
      {
        id: "dabo-politics-008-d",
        text: "聽到了，那首歌選得比政見好。",
        archetype: "perfect",
        retort: "……有點道理，你耳朵挺利的。",
      },
      {
        id: "dabo-politics-008-e",
        text: "大伯你聽過最洗腦的競選歌是哪首？",
        archetype: "deflect",
        retort: "那可多了，我唱給你聽。",
      },
      {
        id: "dabo-politics-008-f",
        text: "競選車跟消防車一樣吵啦。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒回話）",
      },
      {
        id: "dabo-politics-008-g",
        text: "有聽到，但沒特別注意內容……",
        archetype: "meek",
        retort: "不注意內容，那你聽心酸的喔。",
      },
      {
        id: "dabo-politics-008-h",
        text: "我以為是冰淇淋車耶。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看電視）",
      },
    ],
  },
  {
    id: "dabo-politics-009",
    text: "我傳的那個新聞，你有看完嗎？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-009-a",
        text: "你比記者還早知道消息，厲害。",
        archetype: "deflect",
        retort: "那當然，我消息靈通。",
      },
      {
        id: "dabo-politics-009-b",
        text: "還沒看，最近訊息太多了……",
        archetype: "meek",
        retort: "這麼重要都不看，你在忙什麼。",
      },
      {
        id: "dabo-politics-009-c",
        text: "看了一下，但有點看不懂……",
        archetype: "meek",
        retort: "看不懂還敢滑手機，唸書都白讀。",
      },
      {
        id: "dabo-politics-009-d",
        text: "看完了，也順便查了一下真假。",
        archetype: "perfect",
        retort: "……有點道理，查證是應該的。",
      },
      {
        id: "dabo-politics-009-e",
        text: "我覺得那個新聞比小說還精彩。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續傳下一則）",
      },
      {
        id: "dabo-politics-009-f",
        text: "你傳的那些十則有九則是假的。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-009-g",
        text: "這種新聞我都當睡前故事看。",
        archetype: "backfire",
        retort: "……（大伯皺眉，沒接話）",
      },
      {
        id: "dabo-politics-009-h",
        text: "大伯你這消息哪來的，好神通。",
        archetype: "deflect",
        retort: "我朋友的群組傳的，很準。",
      },
    ],
  },
  {
    id: "dabo-politics-010",
    text: "油價又漲了，你車開得起嗎？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-010-a",
        text: "油價漲，我都不太敢出遠門……",
        archetype: "meek",
        retort: "這樣哪像年輕人，太保守了。",
      },
      {
        id: "dabo-politics-010-b",
        text: "油價的事，你比加油站員工懂。",
        archetype: "deflect",
        retort: "那當然，我天天在關心。",
      },
      {
        id: "dabo-politics-010-c",
        text: "你那台車不是早就該換了？",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-010-d",
        text: "油價漲我就漲薪水抵銷啊。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒說話）",
      },
      {
        id: "dabo-politics-010-e",
        text: "開不起，所以我都搭大伯的車。",
        archetype: "perfect",
        retort: "……有點道理，算你會算。",
      },
      {
        id: "dabo-politics-010-f",
        text: "大伯你開車技術這麼好，教教我。",
        archetype: "deflect",
        retort: "這個要多練，我開幾十年了。",
      },
      {
        id: "dabo-politics-010-g",
        text: "最近都盡量搭捷運省油錢……",
        archetype: "meek",
        retort: "搭捷運是省，但也太克難了吧。",
      },
      {
        id: "dabo-politics-010-h",
        text: "沒關係，我改騎腳踏車環島。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續加油）",
      },
    ],
  },
  {
    id: "dabo-politics-011",
    text: "你看這個漲多少，日子怎麼過。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-011-a",
        text: "你買的東西也沒比較省啊。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-011-b",
        text: "有感覺變貴，但沒特別計算……",
        archetype: "meek",
        retort: "沒計算怎麼過日子，太隨便了。",
      },
      {
        id: "dabo-politics-011-c",
        text: "你精打細算，改天教教我理財。",
        archetype: "deflect",
        retort: "好啊，找一天教你。",
      },
      {
        id: "dabo-politics-011-d",
        text: "漲價沒關係，我改吃空氣。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續結帳）",
      },
      {
        id: "dabo-politics-011-e",
        text: "最近真的省很多，都吃簡單一點……",
        archetype: "meek",
        retort: "省成這樣，是不是薪水太少啊。",
      },
      {
        id: "dabo-politics-011-f",
        text: "物價漲，我心情也跟著漲高。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒理你）",
      },
      {
        id: "dabo-politics-011-g",
        text: "日子照過，反正省下來的都給你。",
        archetype: "perfect",
        retort: "……有點道理，算你有孝心。",
      },
      {
        id: "dabo-politics-011-h",
        text: "大伯你比價比得比我媽還細。",
        archetype: "deflect",
        retort: "這叫過日子的智慧，學著點。",
      },
    ],
  },
  {
    id: "dabo-politics-012",
    text: "電費又變貴，你冷氣少開一點。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-012-a",
        text: "你算電費算得比台電還快。",
        archetype: "deflect",
        retort: "那當然，我每個月都在算。",
      },
      {
        id: "dabo-politics-012-b",
        text: "大伯你省電秘訣是什麼，教我。",
        archetype: "deflect",
        retort: "這個簡單，隨手關燈就好。",
      },
      {
        id: "dabo-politics-012-c",
        text: "好啊，我開電風扇吹你的怒氣。",
        archetype: "perfect",
        retort: "……有點道理，算你會省。",
      },
      {
        id: "dabo-politics-012-d",
        text: "忘記關冷氣，帳單真的變高了……",
        archetype: "meek",
        retort: "忘記關冷氣，錢是撿來的喔。",
      },
      {
        id: "dabo-politics-012-e",
        text: "你房間冷氣不也是二十四小時開？",
        archetype: "landmine",
        retort: "你亂講什麼！大伯母，你聽這孩子！",
      },
      {
        id: "dabo-politics-012-f",
        text: "沒關係，我改用意念降溫。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看帳單）",
      },
      {
        id: "dabo-politics-012-g",
        text: "有在省了，但夏天真的很熱……",
        archetype: "meek",
        retort: "熱一下會怎樣，忍一忍就過了。",
      },
      {
        id: "dabo-politics-012-h",
        text: "電費貴，那我搬去你房間吹。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒回話）",
      },
    ],
  },
  {
    id: "dabo-politics-013",
    text: "便當都漲十塊，你吃得消嗎？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-013-a",
        text: "沒關係，我改吃泡麵配夢想。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續吃飯）",
      },
      {
        id: "dabo-politics-013-b",
        text: "大伯你便當都吃什麼，介紹我。",
        archetype: "deflect",
        retort: "我都吃家裡煮的，健康又省。",
      },
      {
        id: "dabo-politics-013-c",
        text: "便當漲價，那我改吃空氣便當。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-013-d",
        text: "最近都改帶便當上班了……",
        archetype: "meek",
        retort: "帶便當是省，但也太節儉了吧。",
      },
      {
        id: "dabo-politics-013-e",
        text: "你每次也是嫌貴還是照樣點大份。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-013-f",
        text: "漲十塊真的有感覺，錢包在哭……",
        archetype: "meek",
        retort: "哭什麼，你薪水應該加了吧。",
      },
      {
        id: "dabo-politics-013-g",
        text: "吃得消，因為我都蹭大伯的菜。",
        archetype: "perfect",
        retort: "……有點道理，算你識相。",
      },
      {
        id: "dabo-politics-013-h",
        text: "你對物價這麼了解，可以出書了。",
        archetype: "deflect",
        retort: "哎唷，這叫生活智慧。",
      },
    ],
  },
  {
    id: "dabo-politics-014",
    text: "股市又跌了，你有沒有在玩？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-014-a",
        text: "你那時候的股票不是也套牢到現在？",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-014-b",
        text: "沒在玩，我專心玩紅包比較實際。",
        archetype: "perfect",
        retort: "……有點道理，紅包比較穩。",
      },
      {
        id: "dabo-politics-014-c",
        text: "我把股票當壁紙看，很療癒。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看新聞）",
      },
      {
        id: "dabo-politics-014-d",
        text: "你對股市這麼熟，改行當分析師吧。",
        archetype: "deflect",
        retort: "我是有點天分啦，哈哈。",
      },
      {
        id: "dabo-politics-014-e",
        text: "大伯你當年買股票賺過嗎？",
        archetype: "deflect",
        retort: "當然有，我那時候眼光準。",
      },
      {
        id: "dabo-politics-014-f",
        text: "有買一點，最近都在賠……",
        archetype: "meek",
        retort: "賠錢還敢買，膽子挺大的。",
      },
      {
        id: "dabo-politics-014-g",
        text: "不太懂股票，不敢碰……",
        archetype: "meek",
        retort: "不懂就要學，不然錢都放銀行喔。",
      },
      {
        id: "dabo-politics-014-h",
        text: "股市跌，那我改投資自己好了。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
    ],
  },
  {
    id: "dabo-politics-015",
    text: "新聞說又罷工了，社會亂糟糟。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-015-a",
        text: "大伯你以前有沒有參加過罷工？",
        archetype: "deflect",
        retort: "當然有，我那時候很衝的。",
      },
      {
        id: "dabo-politics-015-b",
        text: "這種事我通常都不太關心……",
        archetype: "meek",
        retort: "不關心？以後出事你就知道了。",
      },
      {
        id: "dabo-politics-015-c",
        text: "罷工而已，我改請假抗議上班。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看電視）",
      },
      {
        id: "dabo-politics-015-d",
        text: "我也不太懂原因，感覺很複雜……",
        archetype: "meek",
        retort: "不懂就多看新聞，別只滑手機。",
      },
      {
        id: "dabo-politics-015-e",
        text: "我也想罷工，不過沒人理我。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-015-f",
        text: "你上班那幾年不也一直抱怨老闆？",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-015-g",
        text: "亂歸亂，至少大家敢講出來。",
        archetype: "perfect",
        retort: "……有點道理，這樣想也對。",
      },
      {
        id: "dabo-politics-015-h",
        text: "你對這些議題都很了解，佩服。",
        archetype: "deflect",
        retort: "這叫社會觀察，要多看新聞。",
      },
    ],
  },
  {
    id: "dabo-politics-016",
    text: "這張連署單，你幫我簽一下。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-016-a",
        text: "你自己搞不懂還叫我簽？",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-016-b",
        text: "好啦，但我沒仔細看內容……",
        archetype: "meek",
        retort: "沒看內容就簽，這樣很危險耶。",
      },
      {
        id: "dabo-politics-016-c",
        text: "這麼認真推動，改天選議員好了。",
        archetype: "deflect",
        retort: "我才不要，太累了。",
      },
      {
        id: "dabo-politics-016-d",
        text: "大伯你連署過幾次，經驗豐富吧。",
        archetype: "deflect",
        retort: "多了，我都是關心地方的人。",
      },
      {
        id: "dabo-politics-016-e",
        text: "簽名而已，我順便畫個愛心。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，收回連署單）",
      },
      {
        id: "dabo-politics-016-f",
        text: "簽可以，但你要先跟我解釋內容。",
        archetype: "perfect",
        retort: "……有點道理，你這叫謹慎。",
      },
      {
        id: "dabo-politics-016-g",
        text: "我不太懂這個議題……",
        archetype: "meek",
        retort: "不懂還簽，被騙都不知道。",
      },
      {
        id: "dabo-politics-016-h",
        text: "我簽是簽，但字我隨便寫。",
        archetype: "backfire",
        retort: "……（大伯皺眉，沒說話）",
      },
    ],
  },
  {
    id: "dabo-politics-017",
    text: "你看這兩個吵得多精彩，學著點。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-017-a",
        text: "看是有看，但覺得有點吵……",
        archetype: "meek",
        retort: "吵才有內容，安靜哪有看頭。",
      },
      {
        id: "dabo-politics-017-b",
        text: "你看這個看到都忘記吃飯了吧。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-017-c",
        text: "這節目比摔角還精彩耶。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看）",
      },
      {
        id: "dabo-politics-017-d",
        text: "我通常轉靜音，看字幕就好……",
        archetype: "meek",
        retort: "靜音是要學什麼，真敷衍。",
      },
      {
        id: "dabo-politics-017-e",
        text: "學到了，吵架不能沒邏輯。",
        archetype: "perfect",
        retort: "……有點道理，算你有看重點。",
      },
      {
        id: "dabo-politics-017-f",
        text: "我也想上去吵一場試試。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-politics-017-g",
        text: "大伯你吵架技巧比他們強多了。",
        archetype: "deflect",
        retort: "那當然，我這叫實戰經驗。",
      },
      {
        id: "dabo-politics-017-h",
        text: "你看新聞看得比評論員還深入。",
        archetype: "deflect",
        retort: "這叫閱歷，你們還嫩。",
      },
    ],
  },
  {
    id: "dabo-politics-018",
    text: "這則新聞是真的嗎？你怎麼看。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-018-a",
        text: "你分析新聞的角度真的很獨到。",
        archetype: "deflect",
        retort: "這叫看得多，自然懂。",
      },
      {
        id: "dabo-politics-018-b",
        text: "我看重點，不是每句都要信。",
        archetype: "perfect",
        retort: "……有點道理，算你有腦子。",
      },
      {
        id: "dabo-politics-018-c",
        text: "我覺得新聞跟星座運勢差不多準。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看）",
      },
      {
        id: "dabo-politics-018-d",
        text: "大伯你經驗多，你覺得是真是假？",
        archetype: "deflect",
        retort: "我看啊，八成有問題。",
      },
      {
        id: "dabo-politics-018-e",
        text: "我也不確定，感覺半信半疑……",
        archetype: "meek",
        retort: "半信半疑，你到底有沒有立場。",
      },
      {
        id: "dabo-politics-018-f",
        text: "你相信的新聞十則有八則是假的。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-018-g",
        text: "沒仔細看，只看標題而已……",
        archetype: "meek",
        retort: "只看標題，難怪什麼都不懂。",
      },
      {
        id: "dabo-politics-018-h",
        text: "真假不重要，好笑就好。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-politics-019",
    text: "對面那個又在搞事，你有在關心？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-019-a",
        text: "關心啊，關心什麼時候能安穩過年。",
        archetype: "perfect",
        retort: "……有點道理，過年最重要。",
      },
      {
        id: "dabo-politics-019-b",
        text: "這種事離我太遠，沒特別注意……",
        archetype: "meek",
        retort: "離你遠？以後影響到你就知道了。",
      },
      {
        id: "dabo-politics-019-c",
        text: "你講這個講幾十年也沒講出結果。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-019-d",
        text: "我對這個沒意見，我只在乎便當。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-politics-019-e",
        text: "有稍微關心，但不是很懂細節……",
        archetype: "meek",
        retort: "不懂細節，那你在關心什麼。",
      },
      {
        id: "dabo-politics-019-f",
        text: "反正吵歸吵，過年還是要包紅包。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看電視）",
      },
      {
        id: "dabo-politics-019-g",
        text: "大伯你對這個最有研究，說給我聽。",
        archetype: "deflect",
        retort: "這個要講起來，三天三夜講不完。",
      },
      {
        id: "dabo-politics-019-h",
        text: "這種局勢分析，你比學者還準。",
        archetype: "deflect",
        retort: "那當然，我看新聞幾十年了。",
      },
    ],
  },
  {
    id: "dabo-politics-020",
    text: "等一下載我去投票，順便學學。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-020-a",
        text: "開車順便聽你講古，我很期待。",
        archetype: "deflect",
        retort: "好啊，上車我慢慢跟你講。",
      },
      {
        id: "dabo-politics-020-b",
        text: "好，但我等一下還有事要忙……",
        archetype: "meek",
        retort: "投個票而已，是有多忙。",
      },
      {
        id: "dabo-politics-020-c",
        text: "你每次投完票還不是罵到底。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-020-d",
        text: "大伯你這麼準時，投票經驗真豐富。",
        archetype: "deflect",
        retort: "那當然，我幾十年沒缺席過。",
      },
      {
        id: "dabo-politics-020-e",
        text: "好啊，載你去順便載你回家睡午覺。",
        archetype: "perfect",
        retort: "……有點道理，你考慮周到。",
      },
      {
        id: "dabo-politics-020-f",
        text: "載你去投票，我順便去領號碼牌。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，先上車）",
      },
      {
        id: "dabo-politics-020-g",
        text: "我開車技術不太好，怕載不好……",
        archetype: "meek",
        retort: "開成這樣還敢開車，危險。",
      },
      {
        id: "dabo-politics-020-h",
        text: "投票所離超商很近，順便買茶葉蛋。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒說話）",
      },
    ],
  },
] satisfies Question[];
