import type { Question } from "@/content/types";

// situations:
// 1. 除夕圍爐電視開著政論台當背景音
// 2. 大伯翻舊照片講他當年排隊投票的事
// 3. 問你追蹤的網紅是不是都亂講政治
// 4. 停電新聞（缺電議題）
// 5. 颱風天大伯抱怨政府效率
// 6. 大伯說要辦里民大會要你陪他去
// 7. 大伯在麻將桌聽牌友講政治
// 8. 大伯抱怨基本工資調整新聞
// 9. 大伯問你手機裡有沒有加什麼政治社團
// 10. 大伯看到選舉民調新聞
// 11. 大伯抱怨計程車排班被外送搶生意
// 12. 開票結果出爐大伯很興奮
// 13. 大伯抱怨年金改革新聞
// 14. 大伯看到你滑手機看國際新聞
// 15. 大伯說政論節目來賓都嘛在演戲
// 16. 大伯問你以前有沒有參加社運遊行
// 17. 大伯翻報紙看到縣市長政見新聞

export default [
  {
    id: "dabo-politics-021",
    text: "圍爐配政論節目，正好下飯。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-021-a",
        text: "你每年圍爐都要看這個很煩耶。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-021-b",
        text: "我建議配輕音樂比較助消化。",
        archetype: "backfire",
        retort: "……（大伯搖頭，繼續看電視）",
      },
      {
        id: "dabo-politics-021-c",
        text: "配這個吃，我都食不知味……",
        archetype: "meek",
        retort: "食不知味還吃這麼多，矛盾。",
      },
      {
        id: "dabo-politics-021-d",
        text: "下飯是下飯，但年菜比較好吃。",
        archetype: "perfect",
        retort: "……有點道理，你懂吃。",
      },
      {
        id: "dabo-politics-021-e",
        text: "這樣吃飯，消化都變政治的了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續夾菜）",
      },
      {
        id: "dabo-politics-021-f",
        text: "這種配菜方式，你發明的吧。",
        archetype: "deflect",
        retort: "算是啦，我吃飯都要配新聞。",
      },
      {
        id: "dabo-politics-021-g",
        text: "大伯你邊吃邊看，功力真高。",
        archetype: "deflect",
        retort: "這叫多工，你們要學。",
      },
      {
        id: "dabo-politics-021-h",
        text: "我比較想安靜吃飯，有點吵……",
        archetype: "meek",
        retort: "吵一下會怎樣，忍一忍。",
      },
    ],
  },
  {
    id: "dabo-politics-022",
    text: "我年輕時排隊投票排三小時。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-022-a",
        text: "那個年代真辛苦，你多講一點。",
        archetype: "deflect",
        retort: "那當然，你們現在方便多了。",
      },
      {
        id: "dabo-politics-022-b",
        text: "你這毅力，換我早就放棄了。",
        archetype: "deflect",
        retort: "這叫責任感，你們要學。",
      },
      {
        id: "dabo-politics-022-c",
        text: "我上次投票也排很久，腳很痠……",
        archetype: "meek",
        retort: "腳痠而已，我當年排到腿麻。",
      },
      {
        id: "dabo-politics-022-d",
        text: "三小時？換算成紅包也太划算。",
        archetype: "perfect",
        retort: "……有點道理，你會算。",
      },
      {
        id: "dabo-politics-022-e",
        text: "排隊投票跟排隊買雞排一樣值得。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒接話）",
      },
      {
        id: "dabo-politics-022-f",
        text: "現在排隊也是要排一下……",
        archetype: "meek",
        retort: "排一下就喊累，跟我比差多了。",
      },
      {
        id: "dabo-politics-022-g",
        text: "三小時我可以睡兩覺了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
      {
        id: "dabo-politics-022-h",
        text: "你講這故事講幾十次了吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
    ],
  },
  {
    id: "dabo-politics-023",
    text: "你追蹤的那個網紅，亂講政治。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-023-a",
        text: "網紅講政治，我都當廣播劇聽。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒理你）",
      },
      {
        id: "dabo-politics-023-b",
        text: "就純粹看好玩，沒特別想那麼多……",
        archetype: "meek",
        retort: "看好玩看到腦袋都被洗了。",
      },
      {
        id: "dabo-politics-023-c",
        text: "他講的政治，比我的作業還難懂。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-politics-023-d",
        text: "亂講就退追，我也是有原則的。",
        archetype: "perfect",
        retort: "……有點道理，算你分得清。",
      },
      {
        id: "dabo-politics-023-e",
        text: "你看的政論節目也沒比較準啊。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-023-f",
        text: "你對網紅的判斷力，比我還敏銳。",
        archetype: "deflect",
        retort: "那當然，我閱人無數。",
      },
      {
        id: "dabo-politics-023-g",
        text: "大伯你比較懂，你來評評看。",
        archetype: "deflect",
        retort: "我看啊，這個一聽就有問題。",
      },
      {
        id: "dabo-politics-023-h",
        text: "我也不確定他講的對不對……",
        archetype: "meek",
        retort: "不確定還一直看，浪費時間。",
      },
    ],
  },
  {
    id: "dabo-politics-024",
    text: "新聞說又要限電了，怎麼辦。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-024-a",
        text: "不太懂原因，只知道很不方便……",
        archetype: "meek",
        retort: "不懂原因還敢抱怨，先去了解啦。",
      },
      {
        id: "dabo-politics-024-b",
        text: "怎麼辦，早點睡最省電。",
        archetype: "perfect",
        retort: "……有點道理，早睡早起。",
      },
      {
        id: "dabo-politics-024-c",
        text: "停電我就點蠟燭辦party。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-politics-024-d",
        text: "我家最近真的常常跳電……",
        archetype: "meek",
        retort: "跳電而已就抱怨，忍耐一下。",
      },
      {
        id: "dabo-politics-024-e",
        text: "你對這個議題研究得真透徹。",
        archetype: "deflect",
        retort: "這叫民生大事，要關心。",
      },
      {
        id: "dabo-politics-024-f",
        text: "大伯你那時候停電怎麼過的？",
        archetype: "deflect",
        retort: "點蠟燭啊，浪漫得很。",
      },
      {
        id: "dabo-politics-024-g",
        text: "限電剛好，我可以名正言順耍廢。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看新聞）",
      },
      {
        id: "dabo-politics-024-h",
        text: "你家冷氣也是二十四小時開著吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
    ],
  },
  {
    id: "dabo-politics-025",
    text: "這颱風處理得亂七八糟，你說呢。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-025-a",
        text: "你每次颱風天不也是窩著不出門？",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-025-b",
        text: "我只顧著綁窗戶，沒看新聞……",
        archetype: "meek",
        retort: "沒看新聞，你是活在自己世界喔。",
      },
      {
        id: "dabo-politics-025-c",
        text: "颱風天剛好放假耍廢，賺到。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-politics-025-d",
        text: "我建議政府颱風天發放珍奶。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-025-e",
        text: "大伯你經歷過的颱風比我多太多。",
        archetype: "deflect",
        retort: "那當然，我看過的風雨多了。",
      },
      {
        id: "dabo-politics-025-f",
        text: "處理不好，那我們自己顧好家裡。",
        archetype: "perfect",
        retort: "……有點道理，自己顧最實在。",
      },
      {
        id: "dabo-politics-025-g",
        text: "你對防颱準備真的很有一套。",
        archetype: "deflect",
        retort: "這叫經驗，你們要多學。",
      },
      {
        id: "dabo-politics-025-h",
        text: "我也覺得有點慢，但不太懂細節……",
        archetype: "meek",
        retort: "不懂細節還敢說慢，講話要負責。",
      },
    ],
  },
  {
    id: "dabo-politics-026",
    text: "晚上里民大會，你陪我去一趟。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-026-a",
        text: "我今天有點累，可能會打瞌睡……",
        archetype: "meek",
        retort: "打瞌睡還敢去，丟臉丟到里長那。",
      },
      {
        id: "dabo-politics-026-b",
        text: "大伯你在里民大會是不是很有名？",
        archetype: "deflect",
        retort: "那當然，大家都認識我。",
      },
      {
        id: "dabo-politics-026-c",
        text: "你對地方事務這麼熱心，佩服。",
        archetype: "deflect",
        retort: "這叫盡本分，你們要學。",
      },
      {
        id: "dabo-politics-026-d",
        text: "好，但我對這些議題不太懂……",
        archetype: "meek",
        retort: "不懂就去聽聽，別浪費機會。",
      },
      {
        id: "dabo-politics-026-e",
        text: "好啊，我陪你去順便認識鄰居。",
        archetype: "perfect",
        retort: "……有點道理，你這樣想很好。",
      },
      {
        id: "dabo-politics-026-f",
        text: "我去里民大會順便發傳單推銷自己。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-politics-026-g",
        text: "里民大會，我以為是辦桌吃飯。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，準備出門）",
      },
      {
        id: "dabo-politics-026-h",
        text: "你去那邊不就是想找人聊八卦？",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
    ],
  },
  {
    id: "dabo-politics-027",
    text: "打牌聽牌友講的，你信不信？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-027-a",
        text: "我覺得胡牌比誰執政重要多了。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-027-b",
        text: "打牌就打牌，政治留給電視講。",
        archetype: "perfect",
        retort: "……有點道理，專心打牌要緊。",
      },
      {
        id: "dabo-politics-027-c",
        text: "你打牌輸的錢比政策影響還大吧。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-027-d",
        text: "我不太懂牌桌上講的那些……",
        archetype: "meek",
        retort: "不懂就多聽，牌桌上什麼都有。",
      },
      {
        id: "dabo-politics-027-e",
        text: "大伯你牌桌上消息真的特別靈通。",
        archetype: "deflect",
        retort: "那當然，牌桌就是情報站。",
      },
      {
        id: "dabo-politics-027-f",
        text: "牌友講的政治，我都當運勢在聽。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續摸牌）",
      },
      {
        id: "dabo-politics-027-g",
        text: "你邊打牌邊分析時事，太強了。",
        archetype: "deflect",
        retort: "這叫一心多用，你們要練。",
      },
      {
        id: "dabo-politics-027-h",
        text: "聽聽就好，我也不知道真假……",
        archetype: "meek",
        retort: "不知道真假還聽這麼認真，奇怪。",
      },
    ],
  },
  {
    id: "dabo-politics-028",
    text: "新聞說基本工資要調，你有加嗎。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-028-a",
        text: "大伯你當年薪水調整過幾次？",
        archetype: "deflect",
        retort: "調過幾次，但都調得很少。",
      },
      {
        id: "dabo-politics-028-b",
        text: "有加啊，加的是我的白頭髮。",
        archetype: "perfect",
        retort: "……有點道理，辛苦你了。",
      },
      {
        id: "dabo-politics-028-c",
        text: "公司說要看情況，還沒消息……",
        archetype: "meek",
        retort: "還沒消息你就這樣算了？要問啊。",
      },
      {
        id: "dabo-politics-028-d",
        text: "聽說有調，但實際加多少不清楚……",
        archetype: "meek",
        retort: "不清楚自己薪水，這樣行嗎。",
      },
      {
        id: "dabo-politics-028-e",
        text: "你對薪資政策研究得真仔細。",
        archetype: "deflect",
        retort: "這叫關心民生，要跟上時事。",
      },
      {
        id: "dabo-politics-028-f",
        text: "基本工資調高，那我要求加十倍。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看新聞）",
      },
      {
        id: "dabo-politics-028-g",
        text: "我打算跟老闆說我基本工資是愛。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-politics-028-h",
        text: "你退休前薪水也沒調過幾次吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
    ],
  },
  {
    id: "dabo-politics-029",
    text: "你手機裡加了什麼社團，給我看看。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-029-a",
        text: "大伯你有加什麼社團，分享一下。",
        archetype: "deflect",
        retort: "我加的都是關心地方的。",
      },
      {
        id: "dabo-politics-029-b",
        text: "我手機社團都設隱藏，機密。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-politics-029-c",
        text: "我加的都是抽獎社團，比較實際。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續追問）",
      },
      {
        id: "dabo-politics-029-d",
        text: "都是美食社團啦，比較有營養。",
        archetype: "perfect",
        retort: "……有點道理，吃比較實在。",
      },
      {
        id: "dabo-politics-029-e",
        text: "手機比較亂，一時找不到……",
        archetype: "meek",
        retort: "找不到還敢用手機，真的服了。",
      },
      {
        id: "dabo-politics-029-f",
        text: "你自己滑手機的時間比我還多吧。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-029-g",
        text: "你對這些資訊掌握得真快，佩服。",
        archetype: "deflect",
        retort: "那當然，我消息靈通。",
      },
      {
        id: "dabo-politics-029-h",
        text: "就一些日常的社團而已，沒什麼特別……",
        archetype: "meek",
        retort: "沒什麼特別，那你都在關心什麼。",
      },
    ],
  },
  {
    id: "dabo-politics-030",
    text: "這個民調準不準，你有研究？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-030-a",
        text: "你相信的民調也沒準過幾次。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-030-b",
        text: "我不太懂這些數字代表什麼……",
        archetype: "meek",
        retort: "不懂數字，難怪講話沒重點。",
      },
      {
        id: "dabo-politics-030-c",
        text: "沒特別研究，隨便看看而已……",
        archetype: "meek",
        retort: "隨便看看，難怪什麼都學不到。",
      },
      {
        id: "dabo-politics-030-d",
        text: "你分析民調比記者還專業。",
        archetype: "deflect",
        retort: "那當然，我看這麼多年了。",
      },
      {
        id: "dabo-politics-030-e",
        text: "大伯你對民調的看法，說來聽聽。",
        archetype: "deflect",
        retort: "這個要講起來，可精彩了。",
      },
      {
        id: "dabo-politics-030-f",
        text: "民調準不準，我看星座比較準。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看新聞）",
      },
      {
        id: "dabo-politics-030-g",
        text: "我覺得民調跟樂透差不多概念。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-030-h",
        text: "準不準不知道，但你一定有主見。",
        archetype: "perfect",
        retort: "……有點道理，算你懂我。",
      },
    ],
  },
  {
    id: "dabo-politics-031",
    text: "外送搶了計程車生意，你說對嗎。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-031-a",
        text: "你對這個產業觀察得真深入。",
        archetype: "deflect",
        retort: "這叫關心社會，你們要學。",
      },
      {
        id: "dabo-politics-031-b",
        text: "時代在變，適應的人才活得下去。",
        archetype: "perfect",
        retort: "……有點道理，你懂變通。",
      },
      {
        id: "dabo-politics-031-c",
        text: "我建議計程車改送外送比較賺。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-politics-031-d",
        text: "你自己也常常叫外送不是嗎？",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-031-e",
        text: "我覺得騎車送餐比開車自由多了。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-politics-031-f",
        text: "大伯你以前開過車嗎，講講經驗。",
        archetype: "deflect",
        retort: "開過啊，那時候路況單純多了。",
      },
      {
        id: "dabo-politics-031-g",
        text: "我也不太懂這個行業的變化……",
        archetype: "meek",
        retort: "不懂就別亂發表意見。",
      },
      {
        id: "dabo-politics-031-h",
        text: "外送我也有在點，有點矛盾……",
        archetype: "meek",
        retort: "矛盾就對了，你們都這樣。",
      },
    ],
  },
  {
    id: "dabo-politics-032",
    text: "結果出來了，我早就說中了吧。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-032-a",
        text: "猜對了很厲害，我猜都猜錯……",
        archetype: "meek",
        retort: "猜錯就要檢討，多看點新聞。",
      },
      {
        id: "dabo-politics-032-b",
        text: "你上次猜輸也是講得很大聲。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-032-c",
        text: "你分析局勢的能力，比名嘴還強。",
        archetype: "deflect",
        retort: "這叫實力，不是隨便講講。",
      },
      {
        id: "dabo-politics-032-d",
        text: "大伯你的眼光真的很準，佩服。",
        archetype: "deflect",
        retort: "那當然，我看新聞幾十年不是白看的。",
      },
      {
        id: "dabo-politics-032-e",
        text: "喔，是喔……我都沒特別注意。",
        archetype: "meek",
        retort: "沒注意還敢說自己是公民。",
      },
      {
        id: "dabo-politics-032-f",
        text: "你這眼光，可以去買樂透了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續得意）",
      },
      {
        id: "dabo-politics-032-g",
        text: "我早就猜到了，只是沒講而已。",
        archetype: "backfire",
        retort: "……（大伯白眼，沒理你）",
      },
      {
        id: "dabo-politics-032-h",
        text: "厲害厲害，你可以去開賭盤了。",
        archetype: "perfect",
        retort: "……有點道理，我是有兩把刷子。",
      },
    ],
  },
  {
    id: "dabo-politics-033",
    text: "年金又要改了，我以後怎麼辦。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-033-a",
        text: "別擔心，到時候我養你就好。",
        archetype: "perfect",
        retort: "……有點道理，算你有良心。",
      },
      {
        id: "dabo-politics-033-b",
        text: "年金領不到，那我改領紅包過活。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續碎念）",
      },
      {
        id: "dabo-politics-033-c",
        text: "你對年金制度研究得真透徹。",
        archetype: "deflect",
        retort: "這叫關心自己的未來，要學。",
      },
      {
        id: "dabo-politics-033-d",
        text: "我打算靠中樂透養老，比較快。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-033-e",
        text: "大伯你當年繳的年金比較多吧。",
        archetype: "deflect",
        retort: "那當然，我可是繳了幾十年。",
      },
      {
        id: "dabo-politics-033-f",
        text: "你領的比我們以後領的多太多了。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-033-g",
        text: "這個我也不太懂，感覺很複雜……",
        archetype: "meek",
        retort: "不懂還敢說不用擔心，太天真。",
      },
      {
        id: "dabo-politics-033-h",
        text: "我覺得我這代可能領不到什麼……",
        archetype: "meek",
        retort: "領不到你怎麼還這麼樂觀。",
      },
    ],
  },
  {
    id: "dabo-politics-034",
    text: "你在看什麼國際新聞，看得懂嗎。",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-034-a",
        text: "有一半懂，有一半看不太懂……",
        archetype: "meek",
        retort: "看不懂還看，浪費時間。",
      },
      {
        id: "dabo-politics-034-b",
        text: "你連國際局勢都懂，太厲害了。",
        archetype: "deflect",
        retort: "那當然，我閱讀量驚人。",
      },
      {
        id: "dabo-politics-034-c",
        text: "國際新聞我都當旅遊資訊看。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續轉台）",
      },
      {
        id: "dabo-politics-034-d",
        text: "你看的新聞台連國界都搞不清楚。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-034-e",
        text: "就隨便滑滑，沒有很認真看……",
        archetype: "meek",
        retort: "隨便滑滑，難怪常識這麼少。",
      },
      {
        id: "dabo-politics-034-f",
        text: "大伯你對國際情勢也有研究吧。",
        archetype: "deflect",
        retort: "當然，我什麼新聞都看。",
      },
      {
        id: "dabo-politics-034-g",
        text: "看國際新聞比較有氣質啦。",
        archetype: "backfire",
        retort: "……（大伯翻白眼，沒理你）",
      },
      {
        id: "dabo-politics-034-h",
        text: "看得懂啊，比政論節目冷靜多了。",
        archetype: "perfect",
        retort: "……有點道理，國際新聞是理性一點。",
      },
    ],
  },
  {
    id: "dabo-politics-035",
    text: "這些來賓根本在演戲，你看得出？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-035-a",
        text: "看得出，比我論文還精彩。",
        archetype: "perfect",
        retort: "……有點道理，你懂看門道。",
      },
      {
        id: "dabo-politics-035-b",
        text: "大伯你看這麼久，都不會膩嗎？",
        archetype: "deflect",
        retort: "不會啊，每天都有新戲碼。",
      },
      {
        id: "dabo-politics-035-c",
        text: "你對這些人的個性摸得真透。",
        archetype: "deflect",
        retort: "那當然，我看好幾年了。",
      },
      {
        id: "dabo-politics-035-d",
        text: "你看這個看到都忘記自己在演什麼。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-035-e",
        text: "這種演技，奧斯卡應該頒給他們。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-035-f",
        text: "我覺得他們可以去演八點檔。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看）",
      },
      {
        id: "dabo-politics-035-g",
        text: "我看不太出來，感覺都差不多……",
        archetype: "meek",
        retort: "看不出來，你的判斷力真的堪憂。",
      },
      {
        id: "dabo-politics-035-h",
        text: "我通常都當背景音，沒仔細看……",
        archetype: "meek",
        retort: "沒仔細看還敢說自己看新聞。",
      },
    ],
  },
  {
    id: "dabo-politics-036",
    text: "你以前有去遊行抗議過嗎？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-036-a",
        text: "有想過，但一直沒付諸行動……",
        archetype: "meek",
        retort: "想想而已，難怪什麼都做不成。",
      },
      {
        id: "dabo-politics-036-b",
        text: "我比較常參加的是排隊遊行買雞排。",
        archetype: "backfire",
        retort: "……（大伯瞪你，沒理你）",
      },
      {
        id: "dabo-politics-036-c",
        text: "你對社會議題這麼關心，佩服。",
        archetype: "deflect",
        retort: "這叫責任感，你們也要有。",
      },
      {
        id: "dabo-politics-036-d",
        text: "大伯你以前參加過什麼運動嗎？",
        archetype: "deflect",
        retort: "當然有，我年輕時也是熱血的。",
      },
      {
        id: "dabo-politics-036-e",
        text: "沒有耶，我對這些不太熟悉……",
        archetype: "meek",
        retort: "不熟悉還敢說自己是年輕人。",
      },
      {
        id: "dabo-politics-036-f",
        text: "遊行太累，我用意念聲援就好。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-politics-036-g",
        text: "你年輕時參加的那些後來也沒改變什麼。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-politics-036-h",
        text: "有啊，抗議年夜飯太晚開飯。",
        archetype: "perfect",
        retort: "……有點道理，肚子餓最重要。",
      },
    ],
  },
  {
    id: "dabo-politics-037",
    text: "這政見寫得不錯，你覺得呢？",
    topic: "politics",
    bossId: "dabo",
    options: [
      {
        id: "dabo-politics-037-a",
        text: "寫得好不好不知道，先看能不能做到。",
        archetype: "perfect",
        retort: "……有點道理，你比我謹慎。",
      },
      {
        id: "dabo-politics-037-b",
        text: "政見寫得好，選我當總召好了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續看報紙）",
      },
      {
        id: "dabo-politics-037-c",
        text: "你相信的政見也沒幾個實現過。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-politics-037-d",
        text: "你分析政見的角度真的很專業。",
        archetype: "deflect",
        retort: "這叫看得多，自然練出來的。",
      },
      {
        id: "dabo-politics-037-e",
        text: "大伯你看過這麼多政見，哪個最扯？",
        archetype: "deflect",
        retort: "那可多了，講三天講不完。",
      },
      {
        id: "dabo-politics-037-f",
        text: "我覺得政見不如附贈的面紙實用。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-politics-037-g",
        text: "我沒仔細看內容，感覺都差不多……",
        archetype: "meek",
        retort: "都差不多，那你根本沒認真看。",
      },
      {
        id: "dabo-politics-037-h",
        text: "政見那些我通常都看不太懂……",
        archetype: "meek",
        retort: "看不懂還投票，太隨便了。",
      },
    ],
  },
] satisfies Question[];
