import type { Question } from "@/content/types";

// situations:
// 1. 問你一個月領多少
// 2. 問你有沒有年終
// 3. 問你要不要換工作
// 4. 聊到他當年加班到多晚
// 5. 問你要不要考慮回家接家業
// 6. 問你為什麼還在辦公室加班
// 7. 問你有沒有被裁員風險
// 8. 聊到接案不穩定
// 9. 問你為什麼不去考公務員
// 10. 問你老闆對你好不好
// 11. 聊到他當年一份工作做到退休
// 12. 問你有沒有副業
// 13. 問你什麼時候升遷
// 14. 問你加班有沒有加班費
// 15. 聊到隔壁誰誰誰換工作漲薪水
// 16. 問你要不要創業
// 17. 問你有沒有存到錢
// 18. 問你請假會不會被扣薪
// 19. 問你的工作是不是責任制
// 20. 聊到年終獎金縮水

export default [
  {
    id: "dabo-salary_job-001",
    text: "現在一個月領多少啊？講來聽聽。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-001-a",
        text: "大概三萬多……扣一扣剩沒多少……",
        archetype: "meek",
        retort: "三萬多？這樣要怎麼存錢。",
      },
      {
        id: "dabo-salary_job-001-b",
        text: "你對薪水這麼關心，一定經驗豐富。",
        archetype: "deflect",
        retort: "那當然，我上班幾十年了。",
      },
      {
        id: "dabo-salary_job-001-c",
        text: "薪水多少是秘密，跟星座一樣神秘。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-001-d",
        text: "薪水不太夠花，每個月都很緊……",
        archetype: "meek",
        retort: "緊就要省一點，別亂花錢。",
      },
      {
        id: "dabo-salary_job-001-e",
        text: "你退休前薪水也沒多少，別問我。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-001-f",
        text: "大伯你當年薪水都拿去做什麼？",
        archetype: "deflect",
        retort: "存起來啊，我可是很會理財的。",
      },
      {
        id: "dabo-salary_job-001-g",
        text: "我領的是熱情，熱情無價。",
        archetype: "backfire",
        retort: "……（大伯愣住，繼續喝茶）",
      },
      {
        id: "dabo-salary_job-001-h",
        text: "領得不多，但夠包大伯的紅包。",
        archetype: "perfect",
        retort: "……有點道理，算你會做人。",
      },
    ],
  },
  {
    id: "dabo-salary_job-002",
    text: "你們公司有發年終嗎？發多少啊。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-002-a",
        text: "年終我打算拿去買樂透翻身。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-002-b",
        text: "你退休前公司年終也沒多好吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-002-c",
        text: "有發，發的心意我留給大伯包紅包。",
        archetype: "perfect",
        retort: "……有點道理，算你會說話。",
      },
      {
        id: "dabo-salary_job-002-d",
        text: "年終發的是全勤獎狀，很有紀念價值。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-002-e",
        text: "有一點點，但沒有很多……",
        archetype: "meek",
        retort: "一點點是多少，講清楚啊。",
      },
      {
        id: "dabo-salary_job-002-f",
        text: "大伯你以前年終都拿去幹嘛？",
        archetype: "deflect",
        retort: "存起來啊，我這人比較有計畫。",
      },
      {
        id: "dabo-salary_job-002-g",
        text: "你對年終這麼關心，我很感動。",
        archetype: "deflect",
        retort: "那當然，我也是關心你的荷包。",
      },
      {
        id: "dabo-salary_job-002-h",
        text: "今年公司比較差，年終不多……",
        archetype: "meek",
        retort: "不多還敢說出來，丟臉。",
      },
    ],
  },
  {
    id: "dabo-salary_job-003",
    text: "這工作沒前途，怎麼不換一個。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-003-a",
        text: "換工作風險太大，不敢輕舉妄動……",
        archetype: "meek",
        retort: "不敢冒險，難怪一直原地踏步。",
      },
      {
        id: "dabo-salary_job-003-b",
        text: "沒前途沒關係，我打算靠中樂透翻身。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
      {
        id: "dabo-salary_job-003-c",
        text: "你這輩子也只做過一份工作吧。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-003-d",
        text: "你對職涯規劃這麼有想法，佩服。",
        archetype: "deflect",
        retort: "那當然，我走過的路比你多。",
      },
      {
        id: "dabo-salary_job-003-e",
        text: "是有考慮過換，但一直沒行動……",
        archetype: "meek",
        retort: "沒行動，那你還在等什麼。",
      },
      {
        id: "dabo-salary_job-003-f",
        text: "沒前途沒關係，反正我前途無量。",
        archetype: "perfect",
        retort: "……有點道理，你倒是自信。",
      },
      {
        id: "dabo-salary_job-003-g",
        text: "換工作太麻煩，我打算換人生比較快。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-003-h",
        text: "大伯你覺得什麼工作比較有前途？",
        archetype: "deflect",
        retort: "這個要看時機，跟對趨勢就好。",
      },
    ],
  },
  {
    id: "dabo-salary_job-004",
    text: "我當年加班到半夜，你們太爽了。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-004-a",
        text: "爽是爽，但半夜加班的辛苦我懂。",
        archetype: "perfect",
        retort: "……有點道理，算你有同理心。",
      },
      {
        id: "dabo-salary_job-004-b",
        text: "我現在也常常加班，只是沒講出來……",
        archetype: "meek",
        retort: "沒講出來，那你憋著幹嘛。",
      },
      {
        id: "dabo-salary_job-004-c",
        text: "我加班到半夜是因為捨不得下班的冷氣。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-004-d",
        text: "你加班那麼多，身體不也搞壞了。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-004-e",
        text: "大伯你加班到半夜都在做什麼？",
        archetype: "deflect",
        retort: "處理公事啊，那時候責任重。",
      },
      {
        id: "dabo-salary_job-004-f",
        text: "確實比較少加班到那麼晚……",
        archetype: "meek",
        retort: "少加班還敢說辛苦，太享受了。",
      },
      {
        id: "dabo-salary_job-004-g",
        text: "你這種拚勁，我真的自嘆不如。",
        archetype: "deflect",
        retort: "那當然，我可是拚出來的。",
      },
      {
        id: "dabo-salary_job-004-h",
        text: "加班到半夜，我都在加班費裡找快樂。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
    ],
  },
  {
    id: "dabo-salary_job-005",
    text: "要不要回來接家裡的生意，別漂了。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-005-a",
        text: "你這麼希望我回來，我很感動。",
        archetype: "deflect",
        retort: "那當然，家人還是要在一起。",
      },
      {
        id: "dabo-salary_job-005-b",
        text: "考慮啊，但先讓我漂久一點賺經驗。",
        archetype: "perfect",
        retort: "……有點道理，經驗也是本錢。",
      },
      {
        id: "dabo-salary_job-005-c",
        text: "你自己以前也沒把生意顧好啊。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-005-d",
        text: "接家業好啊，我打算先把生意收掉。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-005-e",
        text: "我也想幫忙，但怕能力不夠……",
        archetype: "meek",
        retort: "能力不夠就慢慢學，別找藉口。",
      },
      {
        id: "dabo-salary_job-005-f",
        text: "有考慮過，但外面工作還沒穩定……",
        archetype: "meek",
        retort: "還沒穩定，那家裡就不重要了嗎。",
      },
      {
        id: "dabo-salary_job-005-g",
        text: "回家接生意，我比較想接遙控器。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-005-h",
        text: "大伯你覺得接家業要準備什麼？",
        archetype: "deflect",
        retort: "這個要慢慢學，急不得。",
      },
    ],
  },
  {
    id: "dabo-salary_job-006",
    text: "別人都在家上班，你怎麼還進辦公室。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-006-a",
        text: "公司規定要進辦公室，沒得選……",
        archetype: "meek",
        retort: "沒得選，那你怎麼不跟老闆爭取。",
      },
      {
        id: "dabo-salary_job-006-b",
        text: "你退休前上班也是能摸魚就摸魚。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-006-c",
        text: "大伯你覺得在家上班好不好？",
        archetype: "deflect",
        retort: "我看啊，在家還不是照樣偷懶。",
      },
      {
        id: "dabo-salary_job-006-d",
        text: "進辦公室，順便躲開大伯的問題。",
        archetype: "perfect",
        retort: "……有點道理，算你機智。",
      },
      {
        id: "dabo-salary_job-006-e",
        text: "在家我怕會一直分心，效率不好……",
        archetype: "meek",
        retort: "分心就要自律，這是基本的。",
      },
      {
        id: "dabo-salary_job-006-f",
        text: "我在辦公室比較帥，適合被欣賞。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-006-g",
        text: "你對這種工作趨勢這麼了解，厲害。",
        archetype: "deflect",
        retort: "那當然，我看新聞都有在關心。",
      },
      {
        id: "dabo-salary_job-006-h",
        text: "進辦公室，是為了蹭公司的冷氣電費。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
    ],
  },
  {
    id: "dabo-salary_job-007",
    text: "聽說你們公司要裁員，你會不會中。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-007-a",
        text: "不會中，我把自己弄得不可取代。",
        archetype: "perfect",
        retort: "……有點道理，算你有本事。",
      },
      {
        id: "dabo-salary_job-007-b",
        text: "你以前那份工作不也是被資遣的？",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-007-c",
        text: "有點擔心，但也不知道怎麼準備……",
        archetype: "meek",
        retort: "擔心也要行動，光擔心沒有用。",
      },
      {
        id: "dabo-salary_job-007-d",
        text: "裁員沒關係，我早就準備好離職信了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-007-e",
        text: "不確定，最近公司氣氛怪怪的……",
        archetype: "meek",
        retort: "氣氛怪還不趕快找退路，太被動了。",
      },
      {
        id: "dabo-salary_job-007-f",
        text: "你對這個消息這麼敏銳，佩服。",
        archetype: "deflect",
        retort: "那當然，我消息一向靈通。",
      },
      {
        id: "dabo-salary_job-007-g",
        text: "被裁員剛好可以名正言順放假。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-007-h",
        text: "大伯你以前遇過公司裁員嗎？",
        archetype: "deflect",
        retort: "遇過啊，那時候真的很難熬。",
      },
    ],
  },
  {
    id: "dabo-salary_job-008",
    text: "接案這種工作不穩定，你想清楚沒。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-008-a",
        text: "你對這種工作型態這麼了解，厲害。",
        archetype: "deflect",
        retort: "那當然，我什麼行業都懂一點。",
      },
      {
        id: "dabo-salary_job-008-b",
        text: "確實壓力比較大，但我還在適應……",
        archetype: "meek",
        retort: "適應多久了，還沒找到方向嗎。",
      },
      {
        id: "dabo-salary_job-008-c",
        text: "你退休前公司也沒多穩定，記得嗎。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-008-d",
        text: "想清楚了，穩定的是我的實力。",
        archetype: "perfect",
        retort: "……有點道理，算你有自信。",
      },
      {
        id: "dabo-salary_job-008-e",
        text: "大伯你覺得穩定工作的定義是什麼？",
        archetype: "deflect",
        retort: "這個嘛，就是每個月都準時領錢。",
      },
      {
        id: "dabo-salary_job-008-f",
        text: "接案不穩定，那我改接紅包比較穩。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-008-g",
        text: "是不太穩定，收入有時候會斷……",
        archetype: "meek",
        retort: "會斷還做，這樣風險太大了。",
      },
      {
        id: "dabo-salary_job-008-h",
        text: "不穩定沒關係，我靠意志力硬撐。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續念）",
      },
    ],
  },
  {
    id: "dabo-salary_job-009",
    text: "考公務員最穩，你怎麼不去考。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-009-a",
        text: "你對鐵飯碗這麼推崇，一定很懂。",
        archetype: "deflect",
        retort: "那當然，這是最穩的選擇。",
      },
      {
        id: "dabo-salary_job-009-b",
        text: "考過一次沒上，就沒再試了……",
        archetype: "meek",
        retort: "沒上就放棄，太沒毅力了。",
      },
      {
        id: "dabo-salary_job-009-c",
        text: "有考慮過，但覺得自己不太適合……",
        archetype: "meek",
        retort: "不適合，那你到底適合什麼。",
      },
      {
        id: "dabo-salary_job-009-d",
        text: "我在等大伯退位讓我接手政論台。",
        archetype: "perfect",
        retort: "……有點道理，這梗有意思。",
      },
      {
        id: "dabo-salary_job-009-e",
        text: "考公務員，我打算靠關係走後門。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-009-f",
        text: "你自己上班也沒端過什麼鐵飯碗。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-009-g",
        text: "鐵飯碗太重，我拿不動。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-009-h",
        text: "大伯你覺得考公務員難不難？",
        archetype: "deflect",
        retort: "難啊，我以前也想過但沒考。",
      },
    ],
  },
  {
    id: "dabo-salary_job-010",
    text: "你老闆對你好不好？會不會欺負你。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-010-a",
        text: "老闆情緒有點不穩定，壓力不小……",
        archetype: "meek",
        retort: "情緒不穩定還做，趕快找下一份。",
      },
      {
        id: "dabo-salary_job-010-b",
        text: "你這麼關心我的職場，我很感動。",
        archetype: "deflect",
        retort: "那當然，我也是關心你過得好不好。",
      },
      {
        id: "dabo-salary_job-010-c",
        text: "你以前當老闆時對員工也沒多好吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-010-d",
        text: "我老闆脾氣差，但送禮很大方，扯平。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-010-e",
        text: "對我很好，好到我捨不得裸辭。",
        archetype: "perfect",
        retort: "……有點道理，算你識相。",
      },
      {
        id: "dabo-salary_job-010-f",
        text: "大伯你以前對員工好不好？",
        archetype: "deflect",
        retort: "那當然，我可是有名的好老闆。",
      },
      {
        id: "dabo-salary_job-010-g",
        text: "還好啦，有時候要求比較多……",
        archetype: "meek",
        retort: "要求多就要忍，工作哪有輕鬆的。",
      },
      {
        id: "dabo-salary_job-010-h",
        text: "老闆對我很好，好到常常忘記付薪水。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
    ],
  },
  {
    id: "dabo-salary_job-011",
    text: "我一份工作做到退休，你們換來換去。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-011-a",
        text: "你那份工作做到退休，還不是靠關係留下來的。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-011-b",
        text: "換工作是有點頻繁，我也在反省……",
        archetype: "meek",
        retort: "反省就好，別再一直換了。",
      },
      {
        id: "dabo-salary_job-011-c",
        text: "你這種忠誠度，現在真的很少見。",
        archetype: "deflect",
        retort: "那當然，我這叫有職業道德。",
      },
      {
        id: "dabo-salary_job-011-d",
        text: "換工作是為了收集不同的識別證。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續講古）",
      },
      {
        id: "dabo-salary_job-011-e",
        text: "我也想穩定，但機會不太理想……",
        archetype: "meek",
        retort: "機會不理想就要創造，別等別人給。",
      },
      {
        id: "dabo-salary_job-011-f",
        text: "我換工作比換衣服還勤，算興趣。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-011-g",
        text: "換來換去是為了找到最適合的位置。",
        archetype: "perfect",
        retort: "……有點道理，算你想得清楚。",
      },
      {
        id: "dabo-salary_job-011-h",
        text: "大伯你怎麼能撐這麼久，秘訣是什麼？",
        archetype: "deflect",
        retort: "忍耐加責任感，你們現在少了這個。",
      },
    ],
  },
  {
    id: "dabo-salary_job-012",
    text: "聽說要有副業才行，你有嗎。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-012-a",
        text: "你對這種趨勢這麼了解，厲害。",
        archetype: "deflect",
        retort: "那當然，我電視都有在看。",
      },
      {
        id: "dabo-salary_job-012-b",
        text: "大伯你退休生活算不算副業？",
        archetype: "deflect",
        retort: "那當然算，我這叫忙裡偷閒。",
      },
      {
        id: "dabo-salary_job-012-c",
        text: "有啊，副業是幫大伯挑毛病。",
        archetype: "perfect",
        retort: "……有點道理，你這副業做得挺好。",
      },
      {
        id: "dabo-salary_job-012-d",
        text: "試過一個副業，但沒賺什麼錢……",
        archetype: "meek",
        retort: "沒賺錢還做，浪費時間。",
      },
      {
        id: "dabo-salary_job-012-e",
        text: "你退休後不也是靠子女養才過活。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-012-f",
        text: "我的副業是收集發票，也是財富自由。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-012-g",
        text: "有想過，但下班真的沒力氣做……",
        archetype: "meek",
        retort: "沒力氣，那你以後怎麼多存點錢。",
      },
      {
        id: "dabo-salary_job-012-h",
        text: "我副業是研究怎麼躺平，很有心得。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-salary_job-013",
    text: "進公司這麼久了，什麼時候升遷。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-013-a",
        text: "升遷太累，我升等成資深躺平仔。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-013-b",
        text: "大伯你以前升遷靠什麼，教教我。",
        archetype: "deflect",
        retort: "靠實力加一點運氣，你要學。",
      },
      {
        id: "dabo-salary_job-013-c",
        text: "我升遷的秘訣是每天請假蓄積能量。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-013-d",
        text: "還沒有消息，公司升遷比較慢……",
        archetype: "meek",
        retort: "慢就要主動爭取，別傻等。",
      },
      {
        id: "dabo-salary_job-013-e",
        text: "你上班那幾年也沒升遷過幾次。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-013-f",
        text: "我沒特別想升遷，壓力太大了……",
        archetype: "meek",
        retort: "沒想升遷，那你上班圖什麼。",
      },
      {
        id: "dabo-salary_job-013-g",
        text: "快了，先升遷成大伯最喜歡的晚輩。",
        archetype: "perfect",
        retort: "……有點道理，這頭銜我先收下。",
      },
      {
        id: "dabo-salary_job-013-h",
        text: "你對升遷這麼關心，我很感動。",
        archetype: "deflect",
        retort: "那當然，我也希望你出人頭地。",
      },
    ],
  },
  {
    id: "dabo-salary_job-014",
    text: "加班有沒有加班費，別被公司佔便宜。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-014-a",
        text: "你以前工廠工人加班費也沒少被扣過。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-014-b",
        text: "有算，我可比公司會計還清楚。",
        archetype: "perfect",
        retort: "……有點道理，你懂得保護自己。",
      },
      {
        id: "dabo-salary_job-014-c",
        text: "加班費我都換算成友情價，算了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-014-d",
        text: "你這麼關心我的權益，我很感動。",
        archetype: "deflect",
        retort: "那當然，我不想你被欺負。",
      },
      {
        id: "dabo-salary_job-014-e",
        text: "大伯你以前加班有拿到加班費嗎？",
        archetype: "deflect",
        retort: "沒有啊，那時候都算做功德。",
      },
      {
        id: "dabo-salary_job-014-f",
        text: "有算一點，但沒有全部都算到……",
        archetype: "meek",
        retort: "沒全部算到，那你要去反應啊。",
      },
      {
        id: "dabo-salary_job-014-g",
        text: "其實我也不太清楚怎麼算……",
        archetype: "meek",
        retort: "不清楚怎麼算，難怪一直被佔便宜。",
      },
      {
        id: "dabo-salary_job-014-h",
        text: "沒加班費沒關係，我在辦公室學靜坐。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-salary_job-015",
    text: "隔壁小陳換工作薪水漲一倍，你呢。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-015-a",
        text: "大伯你覺得小陳換工作厲害在哪？",
        archetype: "deflect",
        retort: "厲害在他敢跳，你們就是不敢。",
      },
      {
        id: "dabo-salary_job-015-b",
        text: "我也想漲薪水，但公司沒那個預算……",
        archetype: "meek",
        retort: "沒預算就要換啊，別死守著。",
      },
      {
        id: "dabo-salary_job-015-c",
        text: "我打算漲的是體重，比較實際。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-015-d",
        text: "我還沒有那個機會，也在努力找……",
        archetype: "meek",
        retort: "努力找那麼久還沒找到，太慢了。",
      },
      {
        id: "dabo-salary_job-015-e",
        text: "薪水沒漲，但我的抱怨技能大漲。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-015-f",
        text: "你退休金也沒比小陳的爸媽多到哪。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-015-g",
        text: "我呢，我漲的是對這個話題的免疫力。",
        archetype: "perfect",
        retort: "……有點道理，你這招我服了。",
      },
      {
        id: "dabo-salary_job-015-h",
        text: "你對鄰居的消息這麼靈通，佩服。",
        archetype: "deflect",
        retort: "那當然，這都是關心得來的。",
      },
    ],
  },
  {
    id: "dabo-salary_job-016",
    text: "你這麼有想法，怎麼不自己創業。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-016-a",
        text: "你以前做生意不也是倒閉收場。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-016-b",
        text: "有想過，但風險太大不敢嘗試……",
        archetype: "meek",
        retort: "不敢嘗試，那你想想而已喔。",
      },
      {
        id: "dabo-salary_job-016-c",
        text: "你對創業這件事看得真透徹。",
        archetype: "deflect",
        retort: "那當然，我看過太多起起落落。",
      },
      {
        id: "dabo-salary_job-016-d",
        text: "大伯你當年有想過創業嗎？",
        archetype: "deflect",
        retort: "想過啊，可惜沒那個膽子。",
      },
      {
        id: "dabo-salary_job-016-e",
        text: "創業好啊，我打算賣空氣，成本最低。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-016-f",
        text: "創業要本錢，先等大伯的紅包壯大。",
        archetype: "perfect",
        retort: "……有點道理，那我紅包包小一點。",
      },
      {
        id: "dabo-salary_job-016-g",
        text: "創業需要資金，我還沒存夠……",
        archetype: "meek",
        retort: "沒存夠就想創業，太天真了。",
      },
      {
        id: "dabo-salary_job-016-h",
        text: "創業太累，我改行創造睡眠時數。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-salary_job-017",
    text: "工作這麼久，你到底存到錢沒。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-017-a",
        text: "存是有存，但金額不太多……",
        archetype: "meek",
        retort: "不多是多少，講清楚一點。",
      },
      {
        id: "dabo-salary_job-017-b",
        text: "你退休前存的也沒比我多到哪去。",
        archetype: "landmine",
        retort: "你這什麼態度！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-017-c",
        text: "我存的是回憶，比錢有價值多了。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-017-d",
        text: "物價漲得太快，存不太下來……",
        archetype: "meek",
        retort: "存不下來就要少花一點啊。",
      },
      {
        id: "dabo-salary_job-017-e",
        text: "存到啦，存的是跟大伯聊天的耐性。",
        archetype: "perfect",
        retort: "……有點道理，算你會轉移話題。",
      },
      {
        id: "dabo-salary_job-017-f",
        text: "我存款餘額跟我的自信一樣少。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-017-g",
        text: "大伯你以前存錢有什麼撇步？",
        archetype: "deflect",
        retort: "就是不亂花，你們現在花太兇。",
      },
      {
        id: "dabo-salary_job-017-h",
        text: "你對存錢這麼有心得，教教我吧。",
        archetype: "deflect",
        retort: "好啊，改天我教你記帳。",
      },
    ],
  },
  {
    id: "dabo-salary_job-018",
    text: "你請假會不會被扣薪，公司太摳了吧。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-018-a",
        text: "你這麼關心我的薪水，我很感動。",
        archetype: "deflect",
        retort: "那當然，我不想你被公司佔便宜。",
      },
      {
        id: "dabo-salary_job-018-b",
        text: "會扣，扣的錢我用微笑補回來。",
        archetype: "perfect",
        retort: "……有點道理，算你想得開。",
      },
      {
        id: "dabo-salary_job-018-c",
        text: "扣薪沒關係，我請假是為了休息心靈。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-018-d",
        text: "大伯你以前請假規定嚴不嚴？",
        archetype: "deflect",
        retort: "嚴啊，那時候請假都要寫報告。",
      },
      {
        id: "dabo-salary_job-018-e",
        text: "會扣一些，但也沒辦法，規定就是這樣……",
        archetype: "meek",
        retort: "沒辦法就要爭取，不然一直被扣。",
      },
      {
        id: "dabo-salary_job-018-f",
        text: "你以前開店請假也是想請就請。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-018-g",
        text: "其實我也不太確定規定是怎樣……",
        archetype: "meek",
        retort: "不確定還敢請假，太隨便了。",
      },
      {
        id: "dabo-salary_job-018-h",
        text: "公司扣薪，那我扣公司的信任度。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
  {
    id: "dabo-salary_job-019",
    text: "你們公司是不是責任制，做到死喔。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-019-a",
        text: "是責任制，責任就是把大伯逗笑。",
        archetype: "perfect",
        retort: "……有點道理，那你責任達成了。",
      },
      {
        id: "dabo-salary_job-019-b",
        text: "確實工時比較長，我也很無奈……",
        archetype: "meek",
        retort: "無奈就要想辦法換，別一直忍。",
      },
      {
        id: "dabo-salary_job-019-c",
        text: "你當老闆那時候不也是這樣壓榨員工。",
        archetype: "landmine",
        retort: "你這什麼意思！大伯母，你聽聽！",
      },
      {
        id: "dabo-salary_job-019-d",
        text: "做到死沒關係，反正加班費是心靈成長。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
      {
        id: "dabo-salary_job-019-e",
        text: "是責任制，常常做不完就要留下來……",
        archetype: "meek",
        retort: "做不完就要學會拒絕啊。",
      },
      {
        id: "dabo-salary_job-019-f",
        text: "責任制沒關係，我的責任就是準時吃飯。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-019-g",
        text: "大伯你覺得責任制合不合理？",
        archetype: "deflect",
        retort: "不合理啦，這種制度要改。",
      },
      {
        id: "dabo-salary_job-019-h",
        text: "你對勞動權益這麼關心，我很感動。",
        archetype: "deflect",
        retort: "那當然，我也是希望你別被欺負。",
      },
    ],
  },
  {
    id: "dabo-salary_job-020",
    text: "今年年終縮水，公司是不是虧錢了。",
    topic: "salary_job",
    bossId: "dabo",
    options: [
      {
        id: "dabo-salary_job-020-a",
        text: "你對公司財務這麼敏銳，佩服。",
        archetype: "deflect",
        retort: "那當然，我看新聞多懂一點皮毛。",
      },
      {
        id: "dabo-salary_job-020-b",
        text: "是縮水了，我也不太清楚原因……",
        archetype: "meek",
        retort: "不清楚原因，那你也太好打發了。",
      },
      {
        id: "dabo-salary_job-020-c",
        text: "你以前公司年終也沒發過幾次吧。",
        archetype: "landmine",
        retort: "你說什麼！大伯母，你聽聽這孩子！",
      },
      {
        id: "dabo-salary_job-020-d",
        text: "大伯你以前遇過年終縮水嗎？",
        archetype: "deflect",
        retort: "遇過啊，那年真的很難熬。",
      },
      {
        id: "dabo-salary_job-020-e",
        text: "虧不虧我不知道，但我心臟很大顆。",
        archetype: "perfect",
        retort: "……有點道理，這樣想比較不會氣。",
      },
      {
        id: "dabo-salary_job-020-f",
        text: "縮水沒關係，我年終換算成假期比較划算。",
        archetype: "backfire",
        retort: "……（大伯沒聽懂，繼續問）",
      },
      {
        id: "dabo-salary_job-020-g",
        text: "聽說是業績不好，大家都很無奈……",
        archetype: "meek",
        retort: "無奈也要問清楚，別傻傻接受。",
      },
      {
        id: "dabo-salary_job-020-h",
        text: "年終縮水，那我的胃口就跟著擴張。",
        archetype: "backfire",
        retort: "……（大伯搖頭，沒接話）",
      },
    ],
  },
] satisfies Question[];
